### ISSUE TITLE
[CSS] Crash when missing server only content

### ISSUE THREAD

**Issue by nyronic** [ValveSoftware/Source-1-Games#1010]
If a server has custom content on it such as hats, trails, player skins, etc. and you connect to the server using cl_downloadfilter to bypass downloading this, it will result in the game crashing shortly after connecting.

This was never a problem before the steampipe update, instead you would just see the usual error signs and checkerboards in place of the missing content.

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed.
