### ISSUE TITLE
[Left 4 Dead 2] (Beta) with [fglrx]: "Failed to create OpenGL device"

### ISSUE THREAD

**Issue by stephendcofer** [ValveSoftware/Source-1-Games#1022]
System: Xubuntu 13.04 GNU/Linux, AMD Phenom Quad Core @1.6GHz, AMD HD4550 video card, 4GB RAM.  Using fglrx-legacy driver.  Even though legacy driver is unsupported, all other games tested have worked without issue, including Team Fortress 2, Half-Life 2, and the Left 4 Dead 2 Beta (the version released for Linux before the "official" release now labeled (Beta)).

When Left 4 Dead 2 (Beta) was released, I was no longer able to play due to an error shown in a dialog box over a blank "Left 4 Dead 2 - OpenGL" window (tried both in fullscreen and in a window).  

The dialog label is "Warning!" and the text is:

"Failed to create OpenGL device!  Please see the following for more info.
http://support.steampowered.com/cgi-bin/steampowered.cfg/php/enduser/std_adp.php?p_faqid=772"

It contains an OK button; when pressed, the dialog and the OpenGL window closes, terminating the program. 

The link leads me to instructions on updating Windows Catalyst drivers, leading me to believe the issue may lie with the new version of Left 4 Dead 2's incompatibility with legacy fglrx drivers, much as the previous legacy driver (12.6) was not compatible with Team Fortress 2, needing an update to the current 13.1 drivers to work properly.  Again, it is odd that the true beta version available before ran perfectly.

Output: https://gist.github.com/stephendcofer/5930083

**Comment by kisak-valve** [comment]
Hello @stephendcofer, if you are still experiencing this issue with an up to date system, please open a new issue report.
