### ISSUE TITLE
[Left 4 Dead 2] Hard Rain escape sequence starts right as finale begins.

### ISSUE THREAD

**Issue by MissingNoGuy55** [ValveSoftware/Source-1-Games#1023]
I'm not sure if it's on my part, but this just happened when me and a friend were playing. In Hard Rain the escape starts right as you start the finale. This applies to the main game, not the beta.

If you need a video I can record one. Either way, glad I could help out!

**Comment by kisak-valve** [comment]
Hello @MissingNoGuy55, was this a one-time occurrence and are you still experiencing this issue?

**Comment by MissingNoGuy55** [comment]
@kisak-valve Nope, I have not experienced this issue since. I think a mod was affecting it, actually.

**Comment by kisak-valve** [comment]
Thanks for retesting @MissingNoGuy55, closing.
