### ISSUE TITLE
[L4D2][Linux] Receiving new steam items(trading cards) causes crash

### ISSUE THREAD

**Issue by SlickMcRunFast** [ValveSoftware/Source-1-Games#1028]
Just bought L4D2 and I can't really progress in the game because the popup for the trading cards keeps crashing/closing the game. It has happened twice and I have two more card drops left. I just played through HL2 and didn't have this issue.

I'm running 
Ubuntu 13.04 64bit
NVIDIA 250 GTS - DRIVER 310.44
4 GB RAM

**Comment by kisak-valve** [comment]
Hello @SlickMcRunFast, if you are still experiencing this issue with an up to date system, please open a new issue report.
