### ISSUE TITLE
[TF2] Your map differs from the servers

### ISSUE THREAD

**Issue by benopotamus** [ValveSoftware/Source-1-Games#1031]
I've been getting an error lately upon map change or joining a server:

```
Your map (map_name.bsp) differs from the server's
```

It doesn't happen every time. Just occasionally.

I've done some Googling and other people are having the problem but resolutions seem a bit sketchy - ranging from redownloading the map, to deleting config files and redownloading TF2.

I'm not sure what's happening to the map files. AFAIK I'm only joining servers with non-customised maps. I wonder if the files are getting corrupted but I'm not sure why that would be the case.

System config gist: https://gist.github.com/benopotamus/5938427

**Comment by kisak-valve** [comment]
Closing as this issue report does not appear to be actionable.
