### ISSUE TITLE
[Portal] Automatic moving after drowning (reproducible)

### ISSUE THREAD

**Issue by eikesauer** [ValveSoftware/Source-1-Games#1043]
When I drowned for the first time, I tried to move around to see if I could leave the water. When I respawned, I was moving backward all the time like I would still be pressing the back key. I've been using the keyboard. I could reproduce the behaviour. 

My system configuration:

Prozessor:
    Hersteller: GenuineIntel
    Geschwindigkeit: 3801 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    Debian GNU/Linux 7.1 (wheezy) (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.2.0-4-amd64
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11204000
    X-Fenstermanager: KWin
    Steam-Runtime-Version: steam-runtime-release-i386_2013-05-08

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

```
Treiber-Version: 4.3.0 NVIDIA 313.26
Desktop-Farbtiefe: 24 Bit per Pixel
Monitor-Aktualisierungsrate: 59 Hz
Anbieterkennung: 0x10de
Gerätekennung: 0x11c0
Anzahl der Monitore: 1
Anzahl der logischen Grafikkarten: 1
Prim. Anzeigeauflösung: 1680 x 1050
Desktop-Auflösung: 1680 x 1050
Prim. Anzeigegröße: 47,4 cm x 29,6 cm (55,8 cm diag.)

Primärer Bus: PCI Express 16x
Primärer VRAM: 2048 MB
Unterstützte MSAA-Modi: 2x 4x 8x 16x 
```

Soundkarte:
    Audiogerät: Realtek ID 887

Speicher:
    RAM: 3927 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 104682 MB
    Größter freier Festplattenspeicherblock: 6547 MB

Installierte Software:

Neueste Fehlerberichte:

**Comment by kisak-valve** [comment]
Closing in favor of #565.
