### ISSUE TITLE
[TF2] Window on cp_badlands mid can't be walked through anymore

### ISSUE THREAD

**Issue by hookyboysb** [ValveSoftware/Source-1-Games#1054]
While this isn't really a bug (actually being a fix since the frame should logically block player movement), it still changes the map's dynamics. I would prefer to see the frame removed altogether so it both makes sense and players can go through the window again.

**Comment by FindTheBorealis** [comment]
This was fixed in the July 24, 2013 update, which opened the windows on both the CP and KOTH versions,
but not the Arena version.

**Comment by agrastiOs** [comment]
@kisak-valve this should be closed as it's fixed

**Comment by kisak-valve** [comment]
Thanks, closing per the last couple comments.
