### ISSUE TITLE
[TF2] Some demos do not work anymore.

### ISSUE THREAD

**Issue by hookyboysb** [ValveSoftware/Source-1-Games#1056]
This update seems to have partially broke the demo system as some demos no longer work.

It seems like only demos recorded while tournament mode is active still work.

Here is a demo recorded in a normal pub, which was used to test frame rate at high loads: https://dl.dropboxusercontent.com/u/31103105/benchmark1.dem

Here is a STV demo from an ESEA match (pov demos in tournament mode also work): https://dl.dropboxusercontent.com/u/31103105/esea_match_3333384.dem

While this isn't a huge deal (unlucky for the people who had replays they were planning on editing), it might be nice to look into it.

**Comment by kisak-valve** [comment]
Hello @hookyboysb, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
