### ISSUE TITLE
[L4D2]SegFault

### ISSUE THREAD

**Issue by Kamilko47** [ValveSoftware/Source-1-Games#1061]
Linux, amd64

When in l4d2 server change map - game crash with error "seg fault"

Log
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(steam)/version(1373330809_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/assert_20130709210106_1.dmp
/home/kamilko/.local/share/Steam/SteamApps/common/Left 4 Dead 2/./hl2.sh: line 67: 27802 Naruszenie ochrony pamięci ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 550 "Left 4 Dead 2 (Beta)", ProcID 27802 
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-c66ca201-8c82-40c3-a459-d76c92130709
unlinked 2 orphaned pipes
CAsyncIOManager: 0 threads terminating. 0 reads, 0 writes, 0 deferrals.
CAsyncIOManager: 25489 single object sleeps, 0 multi object sleeps
CAsyncIOManager: 0 single object alertable sleeps, 13 multi object alertable sleeps
[2013-07-09 21:00:43] Startup - updater built Jul 8 2013 13:16:25
[2013-07-09 21:00:43] Opted in to client beta 'publicbeta' via beta file
[2013-07-09 21:00:43] Weryfikowanie instalacji...
[2013-07-09 21:00:44] Verification complete
Shutting down. . .
[2013-07-09 21:13:07] Shutdown

/hl2.sh: line 67: 27802 Naruszenie ochrony pamięci - mean segfault

My spec:
Dostawca: AuthenticAMD
Szybkość: 3200 MHz
4 procesory logiczne
4 procesory fizyczne
HyperThreading: Nieobsługiwane
FCMOV: Obsługiwane
SSE2: Obsługiwane
SSE3: Obsługiwane
SSSE3: Nieobsługiwane
SSE4a: Obsługiwane
SSE41: Nieobsługiwane
SSE42: Nieobsługiwane

Informacje o sieci:
Szybkość sieci: 

Wersja systemu operacyjnego:
Debian GNU/Linux testing (jessie) (64 bitów)
Nazwa kernela: Linux
Wersja kernela: 3.9-1-amd64
Dostawca serwera X: The X.Org Foundation
Wydanie serwera X: 11204000
Menedżer okien X: KWin
Wersja biblioteki Steam: steam-runtime-release-i386_2013-06-28

Karta graficzna:
Sterownik: NVIDIA Corporation GeForce GTS 250/PCIe/SSE2

Wersja sterownika: 3.3.0 NVIDIA 319.23
Głębia kolorów pulpitu: 24 bitów na piksel
Częstotliwość odświeżania monitora: 59 Hz
Ident. producenta: 0x10de
ID urządzenia: 0x615
Liczba monitorów: 1
Liczba logicznych układów graficznych: 1
Rozdzielczość głównego ekranu: 1280 x 768
Rozdzielczość pulpitu: 1280 x 768
Rozmiar głównego ekranu: 39,37" x 21,65" (44,92" diag)
100,0cm x 55,0cm (114,1cm diag)
Szyna: PCI Express 16x
Ilość pamięci VRAM: 512 MB
Obsługiwane tryby MSAA: 2x 4x 8x 16x 

Karta dźwiękowa:
Dźwięk: SigmaTel STAC9750,51

Pamięć:
RAM: 3964 MB

Sry for my English

**Comment by kisak-valve** [comment]
Closing as fixed.
