### ISSUE TITLE
[TF2] Terrible performance (FPS drops in action and stuttering) since roughly around SteamPipe

### ISSUE THREAD

**Issue by XMPPwocky** [ValveSoftware/Source-1-Games#1062]
I installed TF2 on January 1, 2013. It ran wonderfully. Around the time of SteamPipe, it stopped running wonderfully.

In spawn, I get FPSes of 150-200. However, two things happen:
1. Stuttering. Oh god, the stuttering. Random drops to 2 or 3FPS, just for a split second, then back up again. A _huge_ issue, as I play scout in UGC and often miss shots when trying to strafe aim when I just stutter right past my target.
2. FPS drops, occasionally to as low as 40, in action (particularly midfights). Again, huge issue because it messes up my aim enormously.

I'm running Ubuntu Raring, 32-bit, with a NVIDIA GeForce 8800 Ultra GPU and an Intel Core 2 Duo at 3GHz.

Things I have tried to fix this:
1. Literally every FPS config I can find. Chris's maxframes and highframes. m0refps. Quantum's Little Config. Improves spawn FPS, but _only_ the FPS out of action. Stuttering still occurs.
2. Tuning RAM timings. No visible effect.
3. Using latest NVIDIA drivers. No noticeable effect.
4. Switching from Linux Mint 14, 64-bit, to Ubuntu Raring 32-bit. No noticeable effect.
5. Turning compositing off. No noticeable effect.
6. Turning vsync off in Nvidia Settings Manager. No noticeable effect.
7. Overclocking GPU. No noticeable effect.
8. Specifying -heapsize in launch options. No noticeable effect.
9. +gl_nullqueries 1 in launch options. No noticeable effect.
10. Disabling multicore rendering. Slight FPS drop, stuttering still occurs.
11. -dxlevel 80, 81, 90, 92, 95 in console. No noticeable effect.
12. Extracting all VPKs to a subdirectory of /custom/ and moving the VPKs out of /tf/. No noticeable effect.
13. Enabling "Unredirect fullscreen windows" in compiz. No noticeable effect.
14. -noborders -windowed in launch options. No noticeable effect on performance.
15. Uninstalling pulseaudio and using ALSA. No noticeable effect.
16. Disabling thermal throttling and SpeedStep in the BIOS.

During action, my CPU is pinned at 100% on both cores. Memory usage is never more than about 75% of my 4GB (DDR2-800).

Playing demos where FPS drops occurred, the FPS drops still happen in playback. When playing the demos, +showbudget shows _huge_ periods of time (15ms typically) spent in Unaccounted.

I'm really at the end of my rope here, and may have to leave my UGC team if I can't get my hardware situation together.

**Comment by kisak-valve** [comment]
Closing as general performance from 2013 is no longer relevant.
