### ISSUE TITLE
Map doesn't load after a breakup of first try

### ISSUE THREAD

**Issue by marcel113** [ValveSoftware/Source-1-Games#1066]
Hey,

I don't know if this is new, but when I breakup a download of a CS:S map (because I don't have time to download it in this moment) and try it another time, CS:S does not load the map and say "missing mapname.bsp" (like "missing dust.bsp as an example) or sometimes trys to load it but after 3 download-bars or so breaks up and says "missing mapname.bsp".

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
