### ISSUE TITLE
L4D2 forces me to close it after becoming uncontrollably laggy

### ISSUE THREAD

**Issue by randallm** [ValveSoftware/Source-1-Games#1080]
On the change to survivor team on versus (though I'm unsure of whether or not this is the actual trigger), my game sometimes become unplayable. The frame rate will drop from 150ish to ~25, and my ping will jump very quickly from 10-60 up into the hundreds, then into the thousands. I do not, however, disconnect and my game still updates the screen every few seconds, with the audio stuttering throughout the entire process. The game does not kick me or crash, so I'm not aware of any way I can upload a crash dump.

System info: https://gist.github.com/randallm/e0e656388e5843691648

**Comment by kisak-valve** [comment]
Hello @randallm, there is a very high probability the framerate drop was due to part of the rendering hot path getting bumped from VRAM to system ram. Lowering video settings may mitigate the issue. Your mileage may vary.

Closing as there is nothing actionable in this issue report.
