### ISSUE TITLE
[TF2 MvM] Ready timer cannot be stopped if a ready player leaves server

### ISSUE THREAD

**Issue by CompyMcKitties** [ValveSoftware/Source-1-Games#1083]
How to reproduce:
Reproducing this bug requires 3 players if tf_mvm_min_players_to_start is set to 2 on the server, otherwise, 4 players are required.
1. (Optional) Player 1 readies
2. Player 2 readies and then leaves the server without unreadying
3. Player 1 readies if he hasn't readied yet
4. Player 1 unreadies

Expected result: The ready timer stops.
Actual result: The ready timer does not stop.

**Comment by kisak-valve** [comment]
Hello @CompyMcKitties, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
