### ISSUE TITLE
[CSGO] Light decals stay on surface after light disappeared

### ISSUE THREAD

**Issue by pfannkuchengesicht** [ValveSoftware/Source-1-Games#1087]
There is a bug with temporary light sources in Counter-Strike: Global Offensive.
The light decal stays even though the light source disappeared long ago already.
Here are two examples:

Flashbang:
![a](http://cloud-2.steampowered.com/ugc/597008222341112855/3CA2971E6FA1A2CA033887EBF19E00AB9BB7B3BC/)

muzzleflash?
![b](http://cloud-2.steampowered.com/ugc/594757598980072752/77E74E63380B87577D8753478023E972F6957A7E/)

Sys Specs:
CPU: AMD Phenom X4 II 955(3.2GHz, 4C4T)
RAM: 8GB DDR3
GPU: AMD HD5870(1GB)

Win7 x64
Catalyst 13.6

**Comment by kisak-valve** [comment]
CS:GO issues are not tracked in this issue tracker. Closing.
