### ISSUE TITLE
[CSGO] console command "sndplaydelay" has no FCVAR_SERVER_CAN_EXECUTE flag

### ISSUE THREAD

**Issue by p440** [ValveSoftware/Source-1-Games#1102]
the console command "sndplaydelay" has no FCVAR_SERVER_CAN_EXECUTE flag

i cannot execute this command on clients; i would like to

i am aware that "play" also plays sounds, the issue is, if i play 2 sounds, the second sound stops the first sound in a monophonic fashion. i would like the first sound to continue playing if possible (which it would with sndplaydelay)

this command still has the flag in counter strike source (and probably tf2)

CSS:
![ss 2013-07-22 at 02 52 22](https://f.cloud.github.com/assets/4196609/838215/2eac9bc0-f319-11e2-8ddf-79df2f6d39b4.jpg)

CSGO:
![ss 2013-07-22 at 02 50 43](https://f.cloud.github.com/assets/4196609/838217/35d8d17a-f319-11e2-9be9-9b39320fc18a.jpg)

**Comment by kisak-valve** [comment]
CS:GO is not tracked in this issue tracker. Closing.
