### ISSUE TITLE
de_dust 2 & de_dust too bright

### ISSUE THREAD

**Issue by vincent-t** [ValveSoftware/Source-1-Games#1106]
Even with hdr disabled these maps are too bright. Therefore you can't see your hud properly.
![2013-07-24_00002](https://f.cloud.github.com/assets/959709/848224/9808b5fa-f458-11e2-83c5-1309d881e188.jpg)
![2013-07-24_00003](https://f.cloud.github.com/assets/959709/848225/9cd53702-f458-11e2-9a49-7f9a4f23bafa.jpg)
![2013-07-24_00004](https://f.cloud.github.com/assets/959709/848229/baf35dea-f458-11e2-9d6e-e1ca2164923a.jpg)
System information:

Prozessor:
    Hersteller: GenuineIntel
    Geschwindigkeit: 5900 MHz <-- wrong 2800MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt
    
Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 
    
Betriebssystem:
    Ubuntu 13.04 (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.9.11-030911-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11303000
    X-Fenstermanager: Compiz
    Steam-Runtime-Version: steam-runtime-release-i386_2013-06-28
    
Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

    Treiber-Version: 4.3.0 NVIDIA 310.44
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x11c0
    Anzahl der Monitore: 1
    Anzahl der logischen Grafikkarten: 1
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktop-Auflösung: 1920 x 1080
    Prim. Anzeigegröße: 59,8 cm x 33,6 cm (68,5 cm diag.)

    Primärer Bus: PCI Express 16x
    Primärer VRAM: 2048 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 
    
Soundkarte:
    Audiogerät: Realtek ALC889
    
Speicher:
    RAM: 7953 MB
    
Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 104424 MB
    Größter freier Festplattenspeicherblock: 76918 MB

**Comment by kisak-valve** [comment]
Closing per the last comment.
