### ISSUE TITLE
Support loading custom fonts out of vpk files

### ISSUE THREAD

**Issue by peace-maker** [ValveSoftware/Source-1-Games#1113]
Changing the UI of a game and trying to add a new font to it fails when packing the clientscheme.res and font.ttf together in a vpk.

Failed to load custom font file 'e:\steam\steamapps\common\counter-strike source\cstrike\custom\mod.vpk\resource\custom_font.ttf' 

The font is correctly loaded in the "CustomFontFiles" section and works fine, if it's extracted directly into the "resource" folder of the game. If it's in the vpk, it doesn't.

**Comment by kisak-valve** [comment]
Closing as a duplicate of #338.
