### ISSUE TITLE
80+ Servers Utilizing Fake Players.

### ISSUE THREAD

**Issue by StateOfTF2** [ValveSoftware/Source-1-Games#1119]
The following IPs can be checked on gametracker.com. You can also see these servers if you refresh your master list. Be sure to untick "Has users playing" and leave the map blank. Select Team Fortress 2 for your game. Look for a bunch of servers with a completely blank hostname. If you see any servers that are 16/24, join them. Check their players, they are all bots. You can verify this with the status command followed by the ping command in console. If they are not human they will have no pings listed with the ping command. Here is a screenshot of how the servers will appear in your master server list http://i.imgur.com/aa5ltso.png. These servers are strategically placed around the United States.
Please remember that at any time these servers could change their hostnames to appear as anything else. Dozens if not hundreds of more servers like this could exist with other hostnames. Here is a list of six of the IPs found from this group of 80+ servers:

173.234.142.122
209.22.16.210
174.34.172.202
173.208.108.250
173.208.123.42
108.61.31.154

Here's the reddit post with more information on this: http://www.reddit.com/r/tf2/comments/1j6r6x/the_fake_player_problem/

**Comment by kisak-valve** [comment]
Hello @StateOfTF2, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
