### ISSUE TITLE
[CS:S] Vsync and input lag

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#112]
Issue transferred from ValveSoftware/steam-for-linux#1375
@pancakewagon posted at 2013-02-07T21:00:21Z:

When vsync is on I have input lag with both my keyboard and mouse. When I turn it off the lag goes away. 

But when I turn vsync off my game is super choppy because the frame rate is changing so much (100 to 200+ fps).

Also, enabling vsync in the ATI drivers and not the game still causes the lag.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 1600 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 14 Nadia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-17-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11300000

Video Card:
    Driver:  ATI Technologies Inc. ATI Mobility Radeon HD 5800 Series 

```
Driver Version:  4.2.12002 Compatibility Profile Context 9.012
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x68a0
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 15.04" x 8.46"  (17.24" diag)
                                        38.2cm x 21.5cm  (43.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC269

Memory:
    RAM:  5895 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  50448 Mb
    Largest Free Hard Disk Block:  11383 Mb

Installed software:

Recent Failure Reports:

**Comment by sonniesonnig** [comment]
Anything happened here? Same mouse/keyboard delay at CS:GO and CS:S - and its 2015!
With none-source games no issues at all.

**Comment by rinukkusu** [comment]
`gl_finish 1` fixed that input lag for me, too!

System Info:
>System:    Host: hakase.local Kernel: 4.1.6-3-desktop x86_64 (64 bit) Desktop: KDE Plasma 5.4.0
>           Distro: openSUSE 20150909 (Tumbleweed)
>Machine:   System: LENOVO product: 32605BG v: ThinkPad Edge E535
>           Mobo: LENOVO model: 32605BG Bios: LENOVO v: HHET35WW (1.10 ) date: 07/05/2012
>CPU:       Quad core AMD A8-4500M APU with Radeon HD Graphics (-MCP-) speed/max: 1600/1900 MHz
>Graphics:  Card: Advanced Micro Devices [AMD/ATI] Trinity [Radeon HD 7640G]
>           Display Server: X.org 1.17.2 driver: fglrx Resolution: 192x54

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with a recent version of Mesa or AMDGPU-PRO?

**Comment by calexil** [comment]
something posibbly related on 1.6 is going on @kisak-valve https://github.com/ValveSoftware/halflife/issues/1766

**Comment by kisak-valve** [comment]
Closing pending feedback.
