### ISSUE TITLE
[CS:GO] [Feature Request] Player radar information for Overwatch

### ISSUE THREAD

**Issue by nyronic** [ValveSoftware/Source-1-Games#1120]
As it currently stands in both CS:S and CS:GO, when on the spectate team it shows the location of ALL players on the overview.

When watching a CS:GO Overwatch demo, it's impossible to know if the player knew where a player was via his radar information because a team mate spotted the enemy.

It would be useful to display the player's radar information in addition to the map overview. A possible solution would be to change the look of the enemies dot when they are spotted. Such as displaying enemy dots to be transparent when out of sight, and when spotted they can be changed to be fully solid.

This could be useful for CS:S as well.

**Comment by kisak-valve** [comment]
Hello @nyronic,
CS:GO issues are not tracked in this issue tracker. I've passed this on to the CS:GO team, and there most likely won't be any updates reported here.
