### ISSUE TITLE
[TF2] [Linux] Intermittent blurring of entire screen

### ISSUE THREAD

**Issue by gmjck** [ValveSoftware/Source-1-Games#1127]
With Motion Blur enabled while playing TF2, the entire screen will become blurry (and increase in brightness) for anything from a few seconds to several minutes. Turning Motion Blur off appears to resolve this issue, but leads to a different one where the blue outline around the cart in Payload maps does not properly clear, eventually filling the screen with semi-transparent blue. There seems to be some correlation between sudden bright flashes (going from indoors to out, getting hit with a rocket, getting set on fire) and the screen going blurry, but there are also times where the problem triggers with no obvious explanation. The blurriness does not disappear when the scene gets darker (go inside, get extinguished, etc.), but tends to go away on its own after a few minutes. The blurriness occurs many times during a round.

Five screen shots are attached. Two show the same indoor scene, with the blur and after the blur has gone away. Two show the same for an outdoor scene. The last shows the cart outline bug.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2833 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 15 Olivia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6800 Series 

```
Driver Version:  4.2.12217 Compatibility Profile Context 13.101
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6738
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 3840 x 1200
Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                        51.8cm x 32.4cm  (61.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  3953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  703361 Mb
    Largest Free Hard Disk Block:  562522 Mb

Running Catalyst 13.4 now, but the same issues occurred Catalyst 13.6 beta.

![2013-07-23_00008](https://f.cloud.github.com/assets/2197587/902913/9ff1d652-fba1-11e2-98fc-21e5701cfced.jpg)
![2013-07-23_00009](https://f.cloud.github.com/assets/2197587/902914/9ff266da-fba1-11e2-992c-0fd50d31b5a0.jpg)
![2013-07-23_00010](https://f.cloud.github.com/assets/2197587/902915/9ff31ca6-fba1-11e2-9b89-4a4830d47060.jpg)
![2013-07-23_00011](https://f.cloud.github.com/assets/2197587/902916/9ff3f52c-fba1-11e2-9433-af8c0f5e82c7.jpg)
![2013-07-23_00013](https://f.cloud.github.com/assets/2197587/902917/9ff69a5c-fba1-11e2-874a-5c6dd6ffc924.jpg)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
