### ISSUE TITLE
[Left 4 Dead 2][Linux]Game crashes on startup.

### ISSUE THREAD

**Issue by Half-Shot** [ValveSoftware/Source-1-Games#1133]
I was able to play Left 4 Dead 2 to its Full functionality on a week ago albet with a bit of stutter but today it seems to have some issues which i can't pin down. The game first started up and i got as far as trying to join a quickplay game of verses. The game took a minute to do a bit of loading then crashed to desktop, no freezes. After trying to restart there was a quick flicker of the screen to indicate a new opengl window but no game appeared and sure enough the steamerrorrepor program showed up under my process list.

From trying a bit of debugging ( not my area ), i ran hl2.sh from the directory through terminal and got:

```
will@will-swagtop:~/.steam/steam/SteamApps/common/Left 4 Dead 2$ ./hl2.sh
Failed to load the launcher (libSDL2-2.0.so.0: cannot open shared object file: No such file or directory)
```

I compiled the missing library (which i couldn't find from the ubuntu repository)  and even symlinked the newly installed library into the bin folder but nothing new happened.

I did try a steam file verification beforehand and a file was required but this did nothing as did a complete reinstall of left 4 dead 2.

Over to you

--System Configuration--
https://gist.github.com/Half-Shot/563da0d93d900fee9ec6

**Comment by kisak-valve** [comment]
Hello @Half-Shot, running Left 4 Dead 2 from outside of steam is unsupported. If you are still experiencing this issue when running the game from steam on an up to date system, please open a new issue report.
