### ISSUE TITLE
[TF2] Very bad frame rates and pauses under Linux

### ISSUE THREAD

**Issue by kentonspr** [ValveSoftware/Source-1-Games#1134]
I have extremely poor frame rates and pauses while playing TF2 under Linux. I have done a fresh install of OS/Steam/TF2 on multiple versions of Ubuntu from 12.04 to 13.04 that I'm on now with the same issue. This has been the case for every Catalyst driver I have used so far as well.

My frame rates under windows are in the high 100's and into the 200's on some maps, but under Linux with all the settings turned down to the minimum it will still go to 30fps and pause regularly. It happens immediately when I start the game and nothing I change will fix it or make it perform any better. The slow downs are much worse when there is a lot of action on the screen.

My system info is below - 

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3201 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-27-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7900 Series 

```
Driver Version:  4.2.12337 Compatibility Profile Context 13.101
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6798
Number of Monitors:  3
Number of Logical Video Cards:  2
Primary Display Resolution:  2560 x 1600
Desktop Resolution: 4960 x 1600
Primary Display Size: 25.24" x 15.79"  (29.76" diag)
                                        64.1cm x 40.1cm  (75.6cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC898

Memory:
    RAM:  32120 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  87428 Mb
    Largest Free Hard Disk Block:  59012 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
