### ISSUE TITLE
[L4D2] [Linux] Crashes On Joining Online Game, Feels Unstable In General

### ISSUE THREAD

**Issue by sunnybubblegum** [ValveSoftware/Source-1-Games#1141]
Since downloading the 'stable version' of L4D2 a few days ago, I've experienced nothing but crashes and unstable-feeling gameplay. Up until then I had been playing the L4D2 Beta, which gave me very smooth gameplay and absolutely zero crashes.

The crashing happens on a few occasions. One is when I'm trying to join an online game. Two is when I get a card achievement.

The unstable-feeling gameplay is basically a lot of audio and video skipping, especially during the level opening scenes. It carries on while I'm playing through the map; when I turn quickly, I notice the video lag behind or skip. This never happened on the beta version for me.

Output from the command line:

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 83: 1024x256, total string texture memory is 2.02 MB
Generating new string page texture 84: 128x256, total string texture memory is 131.07 KB

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 87: 128x256, total string texture memory is 2.15 MB
Generating new string page texture 88: 256x256, total string texture memory is 2.42 MB

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 92: 128x256, total string texture memory is 2.55 MB
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Game update: AppID 550 "Left 4 Dead 2 (Beta)", ProcID 5216, IP 0.0.0.0:0

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4780): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20130726142109_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[0811/064639:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Running Steam on ubuntu 12.04 32-bit
STEAM_RUNTIME has been set by the user to: /home/nicholas/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/nicholas/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Setting breakpad minidump AppID = 550
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198042026480 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198042026480
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[0811/064642:ERROR:resource_bundle.cc(411)] Failed to load /home/nicholas/.local/share/Steam/SteamApps/common/Left 4 Dead 2/cef_gtk.pak
Some features may not be available.
[0811/064643:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 1048576, Total Avail: 1048576, Current Avail: 742472
GL_MAX_SAMPLES_EXT: 16
Did not detect any valid joysticks.
Querying for subscribed files
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 2, MultisampleType: 2, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO
BinkOpen( /home/nicholas/.local/share/Steam/SteamApps/common/Left 4 Dead 2/left4dead2/media/valve.bik )
ConVarRef volume doesn't point to an existing ConVar
BinkOpen( /home/nicholas/.local/share/Steam/SteamApps/common/Left 4 Dead 2/left4dead2/media/l4d2_intro.bik )
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 1 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 8 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 1272 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 1272 ps-combo 1
IDiLooking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198042026480 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198042026480
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Generating new string page texture 141: 8x256, total string texture memory is 2.56 MB
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
rect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 20 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 464 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 464 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 392 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 392 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 504 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 504 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 80 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 120 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 72 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 888 ps-combo 0
Loaded program cache file "glbaseshaders.cfg", total keyvalues: 738, total successfully linked: 738
Loaded program cache file "glshaders.cfg", total keyvalues: 5, total successfully linked: 5
Precache: Took 27794 ms, Vertex 1080, Pixel 870
Game.so loaded for "Left 4 Dead 2"
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 80 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 464 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 464 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 120 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 504 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 504 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 1 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 1 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from maLooking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198042026480 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198042026480
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
[0811/071048:WARNING:backend_impl.cc(1930)] Destroying invalid entry.
[0811/071048:WARNING:backend_impl.cc(1930)] Destroying invalid entry.
[0811/071048:WARNING:backend_impl.cc(1930)] Destroying invalid entry.
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20130811064640_1.dmp
/home/nicholas/.local/share/Steam/SteamApps/common/Left 4 Dead 2/./hl2.sh: line 67:  5220 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 550 "Left 4 Dead 2 (Beta)", ProcID 5220 
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-8866345f-0916-4278-b4f3-e30ad2130811

System Information:

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3100 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-37-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 240/PCIe/SSE2/3DNOW!

```
Driver Version:  3.3.0 NVIDIA 310.14
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xca3
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.62" x 13.39"  (27.13" diag)
                                        60.0cm x 34.0cm  (68.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  8090 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  461644 Mb
    Largest Free Hard Disk Block:  306078 Mb

Installed software:

Recent Failure Reports:
    Sun Aug 11 12:11:09 2013 GMT: file ''/tmp/dumps/crash_20130811064640_1.dmp'', upload yes: ''CrashID=bp-8866345f-0916-4278-b4f3-e30ad2130811''

**Comment by kisak-valve** [comment]
Closing per the last comment.
