### ISSUE TITLE
[SRCDS] Linux Webmin 1.640 problem or Garry Mod contaiminates SRCDS?

### ISSUE THREAD

**Issue by APGRoboCop** [ValveSoftware/Source-1-Games#1148]
Hello I just updated my Webmin to 1.640 and when I used the Custom Command ./srcds_run on TF2 after I rebooted my server I noticed something wrong. I don't think it has something to do with Webmin but I am not sure. Also I just installed Gmod 13 on my /srcds/ folder where my Source Mods are. It appears to have contaiminated my folder for some reason. This is what I had from my Webmin CMD Custom Command:

"Output from cd /home/desktop/steamcmd/srcds/ ; ./srcds_run -game tf +maxplayers 24 +port 27025 +exec server.cfg +map cp_floodzone2_final -autoupdate -steam_dir ../ -steamcmd_script update_tf2.txt -debug ..
Auto detecting CPU
Using default binary: ./srcds_linux
Enabling debug mode
Server will auto-restart if there is a crash.
INFO: Located steam: /usr/bin/steam
Updating server using Steam.
Setting breakpad minidump AppID = 4000
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed."

But when I tried ./srcds_run -game tf on the CMD Terminal Shell in Ubuntu Server Remote Desktop, the CMD gave out a different msg and appears to be booted up as Gmod not TF2 for some strange reason:

"./srcds_run -game tf +maxplayers 24 +port 27025 +exec server.cfg +map cp_floodzone2_final -autoupdate -steam_dir ../ -steamcmd_script update_tf2.txt -debug
Auto detecting CPU
Using default binary: ./srcds_linux
Enabling debug mode
Server will auto-restart if there is a crash.
INFO: Located steam: /usr/bin/steam
Updating server using Steam.
Running Steam on ubuntu 12.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 21712 with name 0eBlobRegistryMutex_07F2BEF8F5699E41955C2C09C554DDF3
removing stale semaphore last operated on by process 21712 with name 0eBlobRegistrySignal_07F2BEF8F5699E41955C2C09C554DDF3
removing stale semaphore last operated on by process 21712 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 21712 with name 0eSteamEngineLock
OpenGL GLX extension not supported by display
Console initialized.
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Logging into anonymous gameserver account.
Fetching Workshop Addons.. No -authkey
Unknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
Unknown command "port"
Server logging enabled.
Server logging data to file logs/L0815006.log
L 08/15/2013 - 22:47:42: Log file started (file "logs/L0815006.log") (game "/home/desktop/steamcmd/srcds/garrysmod") (version "5353")
Unknown command "sbox_allownpcs"
Unknown command "sbox_plpldamage"
Unknown command "sbox_playergod"
CModelLoader::Map_IsValid:  No such map 'maps/cp_floodzone2_final.bsp'
map load failed: cp_floodzone2_final not found or invalid"

Also when I run that command the Linux Steam Client appeared with the updating popup in the middle of the screen and disappeared. It seems that this server isn't compatible for Steam Client for my Ubuntu, but that isn't the purpose for my server as it is unlikely it will work without the onboard GFX cards and OpenGL drivers - which I may not bother.

**Comment by kisak-valve** [comment]
Hello @APGRoboCop, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
