### ISSUE TITLE
[HL2] Pushing APC in water on d2_coast_04 results in game over

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#1150]
https://drive.google.com/file/d/0B8l-2_JREU9IVkpGNm03SWxKZk0/edit?usp=sharing

The entity filter for the game over trigger allows all prop_vehicles, not just the buggy. Fixed it to only allowed the buggy.

**Comment by kisak-valve** [comment]
Closing as this issue report is no longer actionable.
