### ISSUE TITLE
[L4D2 Feature Request] Clean-up project

### ISSUE THREAD

**Issue by BreakinBenny** [ValveSoftware/Source-1-Games#1158]
I've been thinking of a clean-up project for Left 4 Dead 2, to clean up unused content and duplicated files. Like I did with HL2 (currently Trilogy), let's start with the textures in the alphabet:

-ITEMS & CHARACTERS
*Inside Left 4 Dead 2's original game files (left4dead2\pak01_dir)
# The Axe and Baseball Bat both contain unused textures, the Axe has a texture for the TF2 one used by our Pyro whilst the bat has something else; very white with bloodstains.

AMUSING TRIVIA: The TF2 Fire Axe also has a .vmt.bak in the game directory's materials (materials/models/weapons/melee/fireaxe)!
# (Legacy content!) The original Common Infected have their texture files located in the "materials/models/infected/common" directory, which could be seen as a foreshadowing of bringing L4D1 into L4D2 for those who did look inside the VPKs before any DLCs came out. Adding to that, two unused models exist; "common_morph_test" and "common_test", both are copies of "common_male01", but don't seem very different.
# The original Survivors have their texture & model files left lying around, once again acted as a foreshadowing or in case somebody didn't like the L4D2 survivors. "materials/models/survivors" and "models/survivors", "biker", "manager", "namvet" and "teenangst" parameters with nothing but their textures for the body (no head textures), model files for their animations and viewmodel arms (no sign of the lower bodies).
# According to "materials\models\v_models\weapons\shotgun", the L4D1 Shotgun textures still exist in here. (Did you guys originally plan to keep that version?)

GRAFFITI
*left4dead2\materialsgraffiti
-graffiti_saferoom_port_m2-3_06.vtf ("Freddy- I TOLD you that movie was based on a true case!", this part of the graffiti does not exist in the final release of The Passing)

PARTICLE
*materials\particle (balloon001, leftover TF2 textures for balloon particles... Similar thing with materials\effects\achieved which can sometimes appear in the map, mostly when a player gets the CHAOS GENERATOR achievement in the Port Finale, but is detached from the player unlocking the thing!)

SPRITES
*materials\sprites (As mentioned on Left 4 Dead - The Cutting Room Floor, death_icon and headshot_icon are both in here as well!)

VGUI
*left4dead2\materials\vgui (gfx, maps, missions, terror)
# Original Directory;

-deathscreentombstone (Originally, dead survivors showed a tombstone on the status screen)
-loadingscreen_bloodharvest&deadair&deathtoll&nomercy, outrotitle_bloodharvest&deadair&deathtoll&nomercy (Once again, anyone'd predict L4D1 would be ported to L4D2. How about moving the files from the DLCs into the main game's VPKs)
*materials\vgui\menu_mode_mutation (VTF duplicated, delete from left4dead2 files)
-s_panel_l4d1survivor (Same as two above)
## maps

-c1m#_tempname (What was going on with Dead Center back in 2009?)
## terror (A bunch of unused textures for L4D items, dating back to L4D1 during development)

THE PASSING (DLC1)
*materials\models\props\cs_assault (wirepipe.vmt, with its texture located in left4dead2!)
*materials\models\props\de_train (wood_pallet_01.vtf, for a wooden pallet located in props_industrial with a VMT of its own with left4dead2_dlc3)
*materials\models\props_unique (line_post, "Please Stay on Walkway" added)
*materials\models\survivors\$survivor (Since left4dead2 contains the body textures, only the head, eye textures and VMTs for Boomer's vomit were included and Bill only his head and hair since he gave his life to save his three companions)
*materials\nature (blend_dirt_mud_01 and blend_urbandirtlawn01wet VMTs already exist in left4dead2 files)

THE SACRIFICE (DLC2)
*materials\cable (metal_normal.vtf, unused normalmap for "materials\cable\metal.vmt")
# Model files

*models\hybridphysx ("cable" texture files? I wonder what you guys were doing when you put The Sacrifice & No Mercy into L4D2...)
*models\props\cs_militia ("shelves_wood.vmt")
*models\props_misc (hospital_banner texture files in model files, just like "cable" in "models\hybridphysx")
*models\props_unique\spawn_apartment (tarp_ref.vtf, an envmapmask in model files, too?)
*models\props_vehicles (helicopter_news_ref.vtf, another misplaced envmapmask!)
*models\w_models\weapons (w_minigun, why do we need another version of the model when it already exists in the original left4dead2 files? Plus, L4D2 DLC2 has a new physics model that is 0,03 kB bigger)
# Game Directory, not in VPK

*Models contain .dx80 and .sw.vtx files, while the survivors' texture files are pretty much "mayaswatches"

COLD STREAM (DLC3)
*materials\brick\psd (Both urban_brickwall_03 VTFs are indifferent from the "materials\brick" folder)
*materials\concrete\psd (Source files for textures, even some higher-res ones or WIP height or ssbump maps!)
*materials\decals\psd (Same as above)
*materials\glass\psd
*materials\graffiti\psd (graffiti_alleys_0#.vtf's, just source files for graffiti in Crash Course)
*materials\props_foliage (the VMTs are linking to "materials\models\props_foliage", so this folder is a "models" folder too low!)
*materials\signs\psd (sign_metalsupply.vtf isn't different at all, sign_recycling.vtf has a lower alpha and whitesignbrick.vtf is with a 1024x512 resolution!)
*materials\vgui (Since we already have the original campaigns' original aspect ratio that lacks the "_widescreen"s, just put them into the main game's files ... Same deal with the outrotitles)
*materials\vgui\maps (Simply L4D1 names of the Crash Course maps leftover)
*materials\models\deadbodies\psds (The dead Chopper Pilot's texture at 2048x2048, which was halved for optimization and because Left 4 Dead isn't officially supported in SFM yet)
*materials\models\props_equipment\psds (cargo_container01.vtf has an Eight Bit Alpha that could be useful if put into the main game's files, '03.vtf only has a lower alpha)
*materials\models\props_exteriors\psds (guardrail.vtf and guardshack.vtf seem to be unused due to no official The Last Stand, but roadsidefence.vtf and train_truss01.vtf both have resolutions of 1024x1024!)
*materials\models\props_foliage (Vertex files in the textures folder again. Plus, the model files of these forest rocks are also there in the pak01_dir!)
*materials\models\props_industrial\psds (Now, here's something interesting... the vehicle lift was also high-res, but even came with an alpha channel for... a reason I cannot explain by myself)
*materials\models\props_signs\psds (Another high-resolution sign of Riverside, or more appropriately "Welcome to HELL!"... The latter three textures are for a raised billboard depicting a ruined Burger Tank ad)
*materials\models\props_street\psds (You know it...)
*materials\models\props_unique\psds (ltrain_rails.vtf originally came with The Sacrifice, seems to be in case Xbox 360 players didn't have the former DLC already installed...)
*materials\models\props_vehicles\psds (Don't get me started)
*materials\models\v_models\weapons\pistol (A v_pistol_reference.vmt, but no textures even though the single Pistol-viewmodel and dual version-worldmodel exist)
*materials\models\w_models\minigun (w_minigun_ref.vtf, but the Minigun doesn't use an envmapmask!)
*models directory (Game Directory!); What is the whole deal with all these .VTX files only used in the pre-L4D engine?

UPDATE
*materials\models\props_skybox (milltown001.vmt duplicate, nothing different but blackness)

NOTE: The DLCs duplicating models and texture files aren't something that I can think of, they seem to be for people who have L4D on Xbox 360 and lack either of the former DLCs.

**Comment by Tiagoquix** [comment]
Hello OP, is this still revelant after The Last Stand update?

**Comment by BreakinBenny** [comment]
> Hello OP, is this still revelant after The Last Stand update?

Hi. No, apparently not.
