### ISSUE TITLE
[TF2] - error while loading shared libraries: bin/libtcmalloc_minimal.so.4: ELF file OS ABI invalid

### ISSUE THREAD

**Issue by FlyveHest** [ValveSoftware/Source-1-Games#1162]
After todays update (2013-08-28), I am getting the following errors on a 32 bit CentOS

./srcds_linux: error while loading shared libraries: bin/libtcmalloc_minimal.so.4: ELF file OS ABI invalid
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Wed Aug 28 08:18:15 CEST 2013: Server restart in 10 seconds

I am not seeing this on a CentOS 6.3 64 bit installation.

**Comment by kisak-valve** [comment]
Closing pending confirmation this is still an issue.
