### ISSUE TITLE
[TF2] account : not logged in  (Cannot locate game server account)

### ISSUE THREAD

**Issue by Thordin** [ValveSoftware/Source-1-Games#1163]
Usually after an update Steam will go down for maintenance. When an updated server comes back up it will be unable to reconnect to the Game Coordinator with this message in status:

account : not logged in  (Cannot locate game server account)

It will remain this way until the server is rebooted.

It should be trivial to make this reconnect without a reboot or to re-implement the "heartbeat" command.

**Comment by kisak-valve** [comment]
Hello @Thordin, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
