### ISSUE TITLE
Team Fortress 2 computer freezes after starting

### ISSUE THREAD

**Issue by xpris** [ValveSoftware/Source-1-Games#1168]
Hi there.

Until now game Team Fortress 2 worked for me very well, but suddenly something happened and I do not want to work.

When I run the game, after a few seconds or a few minutes, the cursor starts to a stutterand finally game stutters completely, and with it, usually a computer, too.

In practice, you can not do anything as I try to connect to the game server with which it does so in the course of merger. Gets so as soon as you start, when the game is still on the menu. Anything I can not fix it.

I started Steam in a console, then the game and as soon as the cursor started to a stutter, I minimized and copied the contents of the text console. Just in time, because as soon as I could after the entry of suspended game console computer.

Here is the log from the console:

[x@localhost ~]$ steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on mageia 3 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
unlinked 0 orphaned pipes

(steam:16142): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",

(steam:16142): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
[0901/174513:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0901/174513:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Installing breakpad exception handler for appid(steam)/version(1377723241_client)

*\* (steam:16142): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files

*\* (steam:16142): WARNING **: _nm_remote_settings_ensure_inited: (NMRemoteSettings) error initializing: The name org.freedesktop.NetworkManager was not provided by any .service files

Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1377723241_client)

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
roaming config store loaded successfully - 1709 bytes.
migrating temporary roaming config store
Adding license for package 0
Adding license for package 37
Adding license for package 64
Adding license for package 715
Adding license for package 2481
Adding license for package 7706
Adding license for package 8089
Adding license for package 11005
Adding license for package 11793
Adding license for package 12329
Adding license for package 12558
Adding license for package 13602
Adding license for package 13616
Adding license for package 14633
Adding license for package 14909
Adding license for package 14938
Adding license for package 15136
Adding license for package 15638
Adding license for package 15919
Adding license for package 16020
Adding license for package 16222
Adding license for package 16342
Adding license for package 16360
Adding license for package 16549
Adding license for package 16640
Adding license for package 16767
Adding license for package 17250
Adding license for package 17607
Adding license for package 18629
Adding license for package 18769
Adding license for package 18773
Adding license for package 26703
Adding license for package 27322
Adding license for package 31194
ExecCommandLine: "/home/x/.local/share/Steam/ubuntu12_32/steam"
System startup time: 15,19 seconds
Running Steam on mageia 3 64-bit
STEAM_RUNTIME has been set by the user to: /home/x/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 72: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 73: 128x256, total string texture memory is 442,37 KB
Generating new string page texture 74: 32x256, total string texture memory is 475,14 KB
Generating new string page texture 75: 24x256, total string texture memory is 499,71 KB
ExecCommandLine: "/home/x/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Installing breakpad exception handler for appid(steam)/version(1377723241_client)

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
[0901/174533:ERROR:cef_context.cc(499)] No data resource available for id 4501
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Generating new string page texture 90: 256x256, total string texture memory is 393,22 KB
Generating new string page texture 91: 64x256, total string texture memory is 565,25 KB
Generating new string page texture 95: 128x256, total string texture memory is 696,32 KB
Generating new string page texture 96: 256x256, total string texture memory is 958,46 KB
Generating new string page texture 98: 384x256, total string texture memory is 1,35 MB
Generating new string page texture 99: 256x256, total string texture memory is 1,61 MB
Generating new string page texture 125: 128x256, total string texture memory is 1,74 MB
Generating new string page texture 126: 2048x256, total string texture memory is 3,84 MB
Generating new string page texture 129: 512x256, total string texture memory is 4,37 MB
Generating new string page texture 137: 256x256, total string texture memory is 4,63 MB
Installing breakpad exception handler for appid(steam)/version(1377723241_client)
Game update: AppID 440 "Team Fortress 2", ProcID 16420, IP 0.0.0.0:0

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16142): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
SDL video target is 'x11'
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20130828133107_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)

(gameoverlayui:16431): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",

(gameoverlayui:16431): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",
[0901/174724:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0901/174724:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 440
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198074387172 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198074387172
Did not detect any valid joysticks.
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dbg.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dbg.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dbg.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dbg.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen stdshader_dbg.so error=stdshader_dbg.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx6.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx6.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx6.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx6.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen stdshader_dx6.so error=stdshader_dx6.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx7.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx7.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx7.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx7.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen stdshader_dx7.so error=stdshader_dx7.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx8.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx8.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen /Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx8.so error=/Acer-Dane/SteamApps/common/Team Fortress 2/bin/stdshader_dx8.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
 failed to dlopen stdshader_dx8.so error=stdshader_dx8.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu

(hl2_linux:16423): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",

(hl2_linux:16423): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",
[0901/174730:ERROR:resource_bundle.cc(411)] Failed to load /Acer-Dane/SteamApps/common/Team Fortress 2/cef_gtk.pak
Some features may not be available.
[0901/174730:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0901/174731:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: AVAILABLE
GL_ATI_meminfo: GL_TEXTURE_FREE_MEMORY_ATI: Total Free: 801285, Largest Avail: 406656, Total Aux: 1941246, Largest Aux Avail: 5120
GL_MAX_SAMPLES_EXT: 8
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2000 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4146069504
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2000 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4146069504
IDirect3DDevice9::Create: BackBufWidth: 1600, BackBufHeight: 900, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO

 ##### swap interval = 0     swap limit = 1 #####
Loaded program cache file "glbaseshaders.cfg", total keyvalues: 266, total successfully linked: 266
Loaded program cache file "glshaders.cfg", total keyvalues: 1322, total successfully linked: 1322
Precache: Took 101127 ms, Vertex 1030, Pixel 3197
Game.so loaded for "Team Fortress"

And this is my steam spec system:
Informacje o procesorze:
    Dostawca: AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x5
    CPU Stepping:  0x3
    CPU Type:  0x0
    Szybkość: 2000 MHz
    4 procesory logiczne
    4 procesory fizyczne
    HyperThreading:  Nieobsługiwane
    FCMOV:  Obsługiwane
    SSE2:  Obsługiwane
    SSE3:  Obsługiwane
    SSSE3:  Nieobsługiwane
    SSE4a:  Obsługiwane
    SSE41:  Nieobsługiwane
    SSE42:  Nieobsługiwane

Informacje o sieci:
    Szybkość sieci:  

Wersja systemu operacyjnego:
    "Mageia 3" (64 bitów)
    Nazwa kernela: Linux
    Wersja kernela: 3.10.10-desktop-2.mga4
    Dostawca serwera X: The X.Org Foundation
    Wydanie serwera X: 11304000
    Menedżer okien X: KWin
    Wersja biblioteki Steam: steam-runtime-release-i386_2013-08-26

Karta graficzna:
    Sterownik: ATI Technologies Inc. AMD Radeon HD 6500M/5600/5700 Series

```
Wersja sterownika: 4.3.12441 Compatibility Profile Context 13.20.11
OpenGL Version: 4.3
Głębia kolorów pulpitu: 24 bitów na piksel
Częstotliwość odświeżania monitora: 60 Hz
Ident. producenta: 0x1002
ID urządzenia: 0x68c1
Liczba monitorów: 1
Liczba logicznych układów graficznych:  1
Rozdzielczość głównego ekranu:  1600 x 900
Rozdzielczość pulpitu: 1600 x 900
Rozmiar głównego ekranu: 15,04" x 8,46" (17,24" diag)
```

38,2cm x 21,5cm (43,8cm diag)
    Nie wykryto głównego VRAM

Karta dźwiękowa:
    Dźwięk: Realtek ALC272X

Pamięć:
    RAM: 3954 MB

Dodatki:
    Język interfejsu: Polski
    LANG:  pl_PL.UTF-8
    Mikrofon:  Not set
    Dostępne miejsce na twardym dysku: 59053 MB
    Największy wolny blok na twardym dysku: 31965 MB

Zainstalowane oprogramowanie:

Ostatnie raporty niepowodzeń:

Help folks.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
