### ISSUE TITLE
[TF2] Switching from Quick-Fix to other weapon and back during Uber stops self-heal

### ISSUE THREAD

**Issue by powerlord** [ValveSoftware/Source-1-Games#1171]
I noticed this in a game the other day.  I was in the middle of a Quick-Fix uber and my patient died just after I activated it.

I switched to my primary to shoot someone a few times, then switched back to my Medigun expecting it to heal me... and it no longer healed me despite 30% of the Uber time left.

**Comment by kisak-valve** [comment]
Hello @powerlord, are you still experiencing this issue?

**Comment by hahagoni** [comment]
https://youtu.be/mWbjD7LjtVg
Appears to be fixed

**Comment by kisak-valve** [comment]
Thanks @hahagoni, closing.
