### ISSUE TITLE
[HL2/EP1/EP2] Corrupted shadows

### ISSUE THREAD

**Issue by ivdok** [ValveSoftware/Source-1-Games#1174]
Textures, which are being "lightened" by flashlight seem to be glitched - mixing issue?

http://steamcommunity.com/sharedfiles/filedetails/?id=175731078
http://steamcommunity.com/sharedfiles/filedetails/?id=175731142

Occurs purely random, but frequently. Not game-breaking, yet game experience is not complete.
Please note, what if you move mouse some degrees in any place or move the character, the bug occurs not at this place, but rather another one:

http://steamcommunity.com/sharedfiles/filedetails/?id=175731106
http://steamcommunity.com/sharedfiles/filedetails/?id=175731170

Arch Linux i686, Xfce4 4.10 + Xfwm + Compton (git), Radeon HD5770, Catalyst 13.6. Ubuntu 12.04.2 showed likewise troubles (see http://steamcommunity.com/sharedfiles/filedetails/?id=163371334) with texture mixing, so please don't blame me for using another distro.

UPDATE: Episode Two has likewise issue, but not by flashlight. Did not yet test on CSS, TF2 and original HL2.

http://steamcommunity.com/sharedfiles/filedetails/?id=176415616  - once again, "normal",
http://steamcommunity.com/sharedfiles/filedetails/?id=176415714 -  and "glitched".

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
