### ISSUE TITLE
L4D2 Crashes after finished loading joining game. May be MOTD/flashplugin/64 bits related.

### ISSUE THREAD

**Issue by AlejandroJD** [ValveSoftware/Source-1-Games#1179]
I am using UBUNTU 12.04 64 bits and l4d2 is the only game that crashes to desktop most of the time after finished joining a game (it actually finishes loading) and I have search a little bit and it maybe be because video ads and my flash plugin unable to see it or something. Please help and tell me the information you need.

**Comment by kisak-valve** [comment]
Hello @AlejandroJD, @kicktothecortex, are either of you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
