### ISSUE TITLE
SteamCMD [SteamCMD ERROR! Timed out waiting for AppInfo update] Half-Life 2 Deathmatch dedicated server

### ISSUE THREAD

**Issue by ibscotty** [ValveSoftware/Source-1-Games#1183]
Hello all Im trying to set up a Hl2dm dedicated server using SteamCMD and cant get it to download the files, I have followed the official guide to the letter it just seems app_update 232370 will not work and gives message ERROR! Timed out waiting for AppInfo update or ERROR! Appinfo request for AppId 232370 returned error 16 each time.

I get the above errors whether Im logged in under my steam id or anonymously. 

Im logging in and using the command force_install_dir to specify hl2dm directory then app_update 232370 but this happens everytime.. has the app id changed or something?

cheers.

**Comment by kisak-valve** [comment]
Closing per the last comment.
