### ISSUE TITLE
[HLS] Crowbar plays incorrect sounds

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#1189]
In the current beta, the crowbar makes a flesh impact sound whenever it hits any entity. In GoldSrc this only played when hitting NPCs, and everything else was a metal clang sound.

**Comment by OrutoOtaku** [comment]
I still don't understand how to fix this issue

**Comment by Yetoo1** [comment]
I understand that in the original Half-Life the noise the crowbar makes when it hits concrete is faint but can be heard in the background when breaking glass and wood. However, in HL:S while it is playing the noise as it has in Half-Life, the noise is too loud. It needs to be decreased when hitting wood and glass to a comparative level to the associated actions in goldsrc.
