### ISSUE TITLE
Ammunition for syringe gun not shown properly when 40.

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#119]
Issue transferred from ValveSoftware/steam-for-linux#1470
@Lysius posted at 2013-02-09T09:41:19Z:

In Team Fortress 2 the ammunition count for the syringe gun is not shown properly when you have 40 ammunition loaded. It just shows "4..." instead of "40". All lower ammunition counts show up properly.
I'm using a resolution of 1680x1050 and have every graphics setting at max (excluding HDR and multi core rendering).
Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=125962966
http://steamcommunity.com/sharedfiles/filedetails/?id=125962991

**Comment by micwoj92** [comment]
1440X900, issue no longer exists with cl_hud_minmode 1 and 0, could you close it @kisak-valve ?
Stock hud
![image](https://user-images.githubusercontent.com/45581170/92778454-7b2c3380-f3a1-11ea-884c-411be45ba2ff.png)
![image](https://user-images.githubusercontent.com/45581170/92778557-9303b780-f3a1-11ea-9dcc-8bb1a0e37dc6.png)

**Comment by kisak-valve** [comment]
Closing per the last comment.
