### ISSUE TITLE
Video Stresstest is broken (CS:S) (And missing From Linux!)

### ISSUE THREAD

**Issue by KyleSanderson** [ValveSoftware/Source-1-Games#12]
There was a check added for SetLocalAngles and "Bad" values at some point. In TF2, this occurred on 07/29/2011. This change resulted in the test_hardware.bsp map no longer functioning. You just stare straight at the floor during the stress test, it's quite dreadful. The old CS:S beta still supports this behavior, and the map works just as it did years ago.

This is missing from Linux, and would be a fine addition to the game.

**Comment by MarkkusCraft** [comment]
If you want to stress test, you can download the Source SDK Base 2013 Singleplayer (or Multiplayer) and run it like a normal game.

**Comment by micwoj92** [comment]
So is it Gnu/Linux or Windows? On Arch Linux I can run the stresstest without problems, could some1 check on Windows and close if the issue no longer exists?

**Comment by kisak-valve** [comment]
Closing pending feedback.
