### ISSUE TITLE
KP_ENTER not bindable in CS:Source

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#120]
Issue transferred from ValveSoftware/steam-for-linux#1480
@hustler77 posted at 2013-02-09T12:32:31Z:

HI,

I have a binding to KP_ENTER in CS_source config which used to work in windows.
In Linux this does not work :(

Greets

**Comment by kisak-valve** [comment]
Hello @hustler77, are you still experiencing this issue?

**Comment by hustler77** [comment]
Noipe

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
