### ISSUE TITLE
[Portal Beta] Doesn't launch on Linux

### ISSUE THREAD

**Issue by skype007** [ValveSoftware/Source-1-Games#1228]
Hi,
I'm able to play Portal on Linux but when I switch to the beta, it won't launch and this message appear : 

Failed to create GL context: Could not create GL context

System information : 

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x6
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2300 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.0-031100-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RV710

```
Driver Version:  3.0 Mesa 9.3.0-devel (git-395b941 precise-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9553
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                        34.4cm x 19.4cm  (39.4cm diag)
Primary VRAM Not Detected
```

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
