### ISSUE TITLE
[CS:S] Each time when switching apps, game resizes

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#125]
Issue transferred from ValveSoftware/steam-for-linux#1510
@Majkl578 posted at 2013-02-10T00:20:07Z:

Each time I switch from CS:S to other app (e.g. browser) by alt+tab, CS:S resizes as if the resolution has been changed. When I switch back, it is resized back to original size. This resizing causes some strange behavior when switching back to game, like visible resizing of overlay (if active), I also experienced some in-game glitches like incorrectly positioned kill messages (normally in the right-top corner).
My normal resolution is 1366x768, from this screenshot, it should be clear that the game is resized significantly.
![Screenshot from 2013-02-10 01:13:11](https://f.cloud.github.com/assets/144181/142752/887b40fc-7317-11e2-8f37-2989a4fdb814.jpg)

[System info](https://gist.github.com/Majkl578/f91695cbc471769b849d/ad94c0a8d36a789815d0f959b94bcc9cd72d9f90)

**Comment by kisak-valve** [comment]
Closing as there does not appear to be an actionable issue here. As long as the game returns to the expected resolution when regaining focus, then this is just the game engine trying to reduce resource usage while the system is being used for other things.
