### ISSUE TITLE
[CS:S] Sprays don't work

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#127]
Issue transferred from ValveSoftware/steam-for-linux#1521
@Sikon posted at 2013-02-10T08:09:04Z:

When I create a server with the default settings and press the spray key (whether with the default spray or a custom spray), the sound is played but nothing is painted on the wall.

**Comment by NeonSpaceTurtle** [comment]
> Fix has shipped in TF2. We'll release a CS:S update in a day or so that fixes it.

still have this exact bug on a fresh install of css with vtf spray files that should work for certain
