### ISSUE TITLE
[HL2DM] Bug with letters and textures after game folding.

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1277]
It happens when I folding hl2dm.
![421](https://f.cloud.github.com/assets/5474916/1161600/5756d17a-1ff2-11e3-91a6-901388be702b.jpg)
![01](https://f.cloud.github.com/assets/5474916/1162311/e89f7f28-200c-11e3-8aae-4b4a2df7cf3c.jpg)
![02](https://f.cloud.github.com/assets/5474916/1162312/e8c46f04-200c-11e3-8b12-d9adc878a986.jpg)
![05](https://f.cloud.github.com/assets/5474916/1162314/e8c40c08-200c-11e3-9d0c-0d96e0318298.jpg)
![04](https://f.cloud.github.com/assets/5474916/1162313/e8c69644-200c-11e3-8356-c4fd9e8836d9.jpg)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
