### ISSUE TITLE
[HL2DM] prop_vehicle_airboat working incorrectly

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1281]
When you are driving prop_vehicle_airboat:
1) The camera does not keep up with player.
2) Sometimes the airboat turns left when you press right.
3) When you stop, the airboat jumps.
(I'm using the default script file)

http://www.youtube.com/watch?v=x5v8NMi0WTw

**Comment by kisak-valve** [comment]
Closing per the last comment.
