### ISSUE TITLE
[HL2DM] trigger_teleport errors

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1308]
When I throw something into the teleport (example: granade) I will have this error in my console:
Ignoring unreasonable position (-0.000000,0.000000,-16401.125000) from vphysics! (entity weapon_ar2)

http://youtu.be/iSzzyEBxrMw?t=12m50s

**Comment by kisak-valve** [comment]
Closing as this appears to have no impact on gameplay.
