### ISSUE TITLE
[HL2DM] List of NPCs not working in game (or they don't have any animation)

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1324]
List of NPCs not working in game (or they don't have any animation):

npc_advisor
npc_alyx
npc_antlion_grub
npc_antlion_template_maker
npc_barnacle
npc_barney
npc_blob
npc_breen
npc_bullseye
npc_citizen
npc_combine_cannon
npc_combine_s
npc_combinedropship
npc_combinegunship
npc_crabsynth
npc_cranedriver
npc_eli
npc_crow
npc_cscanner
npc_dog
npc_enemyfinder
npc_enemyfinder_combinecannon
npc_fastzombie
npc_fastzombie_torso
npc_fisherman
npc_gman
npc_helicopter
npc_hunter
npc_hunter_maker
npc_ichthyosaur
npc_kleiner
npc_magnusson
npc_metropolice
npc_monk
npc_mortarsynth
npc_mossman
npc_puppet
npc_sniper
npc_spotlight
npc_stalker
npc_strider
npc_turret_ceiling
npc_turret_floor
npc_turret_ground
npc_zombine

**Comment by kisak-valve** [comment]
Closing per the last comment.
