### ISSUE TITLE
[TF2] Game freeze on jumping into water or being jarate'd

### ISSUE THREAD

**Issue by bazukas** [ValveSoftware/Source-1-Games#1331]
A short game freeze occurs when jumping into water or being jarate'd. It's really annoying. I've seen people reporting that this happens to them only the first time, but for me it every time. So it's almost impossible playing against jarate snipers.

Ubuntu 13.04 64 bit
AMD Radeon 6700M with latest beta drivers (13.8)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
