### ISSUE TITLE
[DoD:S] Joystick non-functional after latest update

### ISSUE THREAD

**Issue by LinMoon** [ValveSoftware/Source-1-Games#1332]
Confirmed through several reports, the joystick no longer responds in Day of Defeat Source since today's update (9/18/2013). This prevents many of us old farts from playing; I have arthritis and cannot play normally, so breaking the joystick leaves me completely unable to play now.

Please tell me this was an "oops" and will be fixed soon...?

**Comment by kisak-valve** [comment]
Hello @LinMoon, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
