### ISSUE TITLE
Graphic glitch

### ISSUE THREAD

**Issue by maidos** [ValveSoftware/Source-1-Games#1335]
this glitch has been here for 1.5 years and the reason why im asking for support now is because the latest nvidia driver has performance upgrade on other games. using latest nvidia driver 327.23 i get majoy graphic glitch when i ONLY play this game called team fortoress 2.

ive stream to demonstrate what im talking about http://twitch.tv/maidos/b/463528743

however older driver do work wheres theres no graphic glitches like 306.23which is really old driver. What do i expect from you? talk to nvidia since they pass the bucket when i try to approach them as they said i would need to contact you.

windows 7 64 bit, xeon 1230v2, Motherboard MSI ZH77A-G41, 6gb ram, samsung 840 pro ssd, 570gtx

**Comment by kisak-valve** [comment]
Closing as general video rendering quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
