### ISSUE TITLE
CS:Source - Multicore rendering causes stuttering

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#134]
Issue transferred from ValveSoftware/steam-for-linux#1566
@thof posted at 2013-02-11T14:24:05Z:

Hi, I bought CS:Source yesterday, but I'm facing nasty bug. I'm on Arch Linux and my laptop is equipped with Nvidia 9650GT. Hardware seems fine since I can play SS3:BFE, Killing Floor and World of Goo without any problem.

On proprietary Nvidia driver (313.18):
Almost immediately after joining to game (I can specting as long as I want) whole system hang up. After hard reset I can't find anything interesting in logs.

On Nouveau (9.0.2):
At least with Nouveau, after several minutes of play, only the game is crashing and generating dump file. This is what I found in terminal:

`Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20130211144258_1.dmp
success = yes
response:  CrashID=bp-da72b888-98be-418c-87b0-6246a2130211
[...]/Counter-Strike Source/hl2.sh: line 72:  1795 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 240 "Counter-Strike: Source", ProcID 1795 
Generating new string page texture 128: 256x256, total string texture memory is 2.90 MB
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully`

Crash log: https://dl.dropbox.com/u/1050707/crash_20130211144258_1.dmp
System information: https://gist.github.com/thof/4754646

**Comment by mlandalv** [comment]
I realize this issue is old, but I have stuttering issues perhaps related to this when playing CSGO. (I'm guessing it's related to all Source games, I had the same when playing Insurgency too.) As far as I recall they started when I started using the proprietary NVIDIA drivers. Initially when csgo was released for linux I had an AMD card and used the open source drivers and I don't remember having these micro stutter issues.

I've tried with and without multicore rendering and can't say I've noticed any difference. Both stutters. The stutter isn't long, a couple of tens of a second. A few months back the stutters could result in the keys pressed getting stuck but I haven't had that issue for long, but the small stutters remain.

My system:
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.7.2-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 370.23
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.43" x 12.76"  (24.06" diag)
                                            51.9cm x 32.4cm  (61.1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  32027 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  168880 Mb
    Largest Free Hard Disk Block:  52542 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Sun Aug 28 07:05:10 2016 GMT: file ''/tmp/dumps/crash_20160828090446_2.dmp'', upload yes: ''Discarded=1''
```

**Comment by kisak-valve** [comment]
If anyone is still experiencing this issue with CS:S on an recent, up to date system, please file a new issue report.
