### ISSUE TITLE
HL2: DM Client crash

### ISSUE THREAD

**Issue by adelina1985a** [ValveSoftware/Source-1-Games#1352]
I can crash it if I Shift+Tab (steam community keyboard shortcut) after launching the game, but barely getting into it.

Funny how I noticed this after a recent update that supposedly fixed some client crashes (also, for this game the snd_restart command still crashes client on certain servers).

EDIT: not sure how safe it is to post my sysinfo but here it is: https://gist.github.com/adelina1985a/6652165#file-sysinf_ade_21sep2013-nfo

**Comment by kisak-valve** [comment]
Closing as general stability from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
