### ISSUE TITLE
[Hammer MP] Building cubemaps WORKAROUND breaks final compile settings and dissallows all means of using cubemaps AT ALL

### ISSUE THREAD

**Issue by JorisCeoen** [ValveSoftware/Source-1-Games#1376]
Ok so I've been struggling with this for a long time, and I see there are many, many, MANY problems related to cubemaps. Thank god there IS a workaround, but I recently found another issue with this!

http://www.facepunch.com/showthread.php?t=1293081

Facepunch provides the following procedure to fix cubemaps:
- Compile map
- Open in external packing program, remove 'Texture' files.
- Save again
- Build cubemaps
- It 'worked'

Now the problem lies within removing the 'Texture' files and resaving it. I found out that when resaving the bsp, even if it's under another name and not copied over the older file, it BREAKS the FINAL COMPILE SETTINGS. Can you believe that?

I have had my cathedral (http://gamebanana.com/projects/34608) being compiled no problem and with extremely nice visual settings, except that there are no speculars at all, and I can't add them or all my models become uniformly lit without any vertex lighting at all.

This, as you may have understood, removes all means of using speculars on a final version of a map... The ONLY way I could see around it, is using custom cubemaps and implementing them in the vmt's as envmaps... THIS ALSO DOESN'T WORK IN HDR, as custom environment maps are FULLY LIT and there's NO way around it...

Please, I pledge Valve to fix this, once and for all. How can it be so difficult to just restore something that in my eyes has to do with directories (correct me if I'm wrong).

I will not resort to using LDR with envmaps which also does not allow for reflections on weapons either way as it will kill my bsp's final compile settings anyways with the current, unefficient method. I know many people compile with normal settings which I believe is unprofessional and ugly (unless it being intentionally the goal of the maps' visuals).

Anyways, shortly said, I believe Reflections are a great addon to the maps' visuals, and it's important as it cheaply adds fancy dynamic element to the environment, which now seem completely out of function due to the above reasons. I'm surprised no one yet posted this (I don't mean the cubemap problem, I mean the dissappearance of the final compile settings such as vertex lighting), perhaps I'm the only one with the problem??

Please, if someone knows why this happens, help me, I would really, really appreciate it, or else please provide a fix, it will help so many of us.

SYSTEM INFO:
- Windows 7 Premium
- CPU (Processor) - Intel Quad Core i7 860 @ 2.80GHz
- GPU (Graphics Card) - ATI Radeon HD 5870 (1Gig)
- Memory - 8 Gigabite (4x2gig)
- Soundcard: ASUS Xonar D2
- Monitor - SyncMaster B2230 (Full HD / 70000:1 Dynamic Contrast / (1920x1080)

**Comment by kisak-valve** [comment]
Hello @JorisCeoen, is this issue still occurring?

**Comment by kisak-valve** [comment]
Closing pending feedback.
