### ISSUE TITLE
[TF2] Demo smoother crashes the game

### ISSUE THREAD

**Issue by ElectricTriangle** [ValveSoftware/Source-1-Games#1391]
Pressing certain (if not nearly all) buttons in the demo smoother will crash the game. Ones I've tried to present are the show all checkbox and the select button with a smoothing range selected (reloading the demo with the reload button doesn't crash the game). I haven't had the chance to see whether or not this exists under Windows as well.

```
--Distro

Crunchbang, based on Debian Testing.

--Graphics driver

Catalyst Legacy v13.1

--System Info

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3300 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux testing (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.9-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 4600 Series
    Driver Version:  3.3.11672 Compatibility Profile Context
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x9490
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 16.14" x 10.12"  (19.02" diag)
                                            41.0cm x 25.7cm  (48.3cm diag)
    Primary VRAM Not Detected  
Memory:
    RAM:  16079 Mb
```

**Comment by kisak-valve** [comment]
Hello @ElectricTriangle, are you still experiencing this issue with an up to date system?

**Comment by ElectricTriangle** [comment]
It doesn't crash immediately anymore, I'm not sure if that's because of my new graphics card or not.

**Comment by ElectricTriangle** [comment]
Leaving my updated system specs in case this issue becomes relevant in the future
`Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Phenom(tm) II X6 1100T Processor
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3300 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux 7.11 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.9
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.20
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c81
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.87" x 12.20"  (24.17" diag)
                                            53.0cm x 31.0cm  (61.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: 
    
Memory:
    RAM:  7966 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  442810 Mb
    Largest Free Hard Disk Block:  88486 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    
`
