### ISSUE TITLE
Source Games on OS X: Vertical Sync in fullscreen mode causes "vibrations"

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Source-1-Games#1415]
This may be specific to my config but this is something I observed in all source games.

In fullscreen mode (at native resolution, 1680*1050 here), VSync makes the image "vibrate" when panning (not when strafing). Even though I get 60 fps, these vibrations are irritating to the eye (fatigue) and don't appear in windowed mode.

One way to clearly see the issue requires Quartz Debug. Launch a Source game in windowed mode with Vsync disabled (it's important). Frame rate should still be capped at 60 fps if the "Beam Sync" option in Quartz Debug is set to automatic (at least it works that way on my config). There the image "vibrates" when you pan the camera, just like it does in fullscreen mode (this is most visible at medium, constant speed and on vertical objects, motion blur curiously makes it a bit worse).
If you select the "force" option in Quartz Debug, panning becomes perfectly smooth, and easy on the eye. Enabling Vsync in the game settings also fixes the issue. Neither fixes the issue in fullscreen mode though. 

Anyway, I don't see this issue on Windows (xp) on the same Mac, and I'd like to know if I'm the only one seeing this. 

Mac Pro 1.1, radeon 4870. OS X 10.7.5.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
