### ISSUE TITLE
[HL2DM] .357 bug with reset aim vector

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1424]
When firing the .357 revolver. After every shot, the aim vector is reset to a point a few milliseconds in the past. The number of milliseconds depends on the ping-time between client and server. This bug causes an irritating "jerkiness" after every shot.

http://www.youtube.com/watch?v=pVt5aUOBckg

**Comment by StrikerMan780** [comment]
This is due to SnapEyeAngles not being predicted.

**Comment by kisak-valve** [comment]
Closing as a duplicate of #282.
