### ISSUE TITLE
[L4D2]Keyboard troubles

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#1430]
I can't use the "wqsd" keys to move in Left 4 Dead 2, when I launch steam in the console, I've got these lines : 

Keyboard layout unknown, please send the following to the SDL mailing list (sdl@libsdl.org):
The key you just pressed is not recognized by SDL.

In my X11 configuration, I'm using the XkbVariant "mac" an the XkbLayout "fr" and I'm under GNU/Linux.

But the strange things is that it worked before, and sometimes, just after the boot, it work too, I don't know why.
Do you want me to add the entire out of the steam command (I have a .dmp file too) ?
Thanks

**Comment by kisak-valve** [comment]
Closing as the user has disappeared. If anyone is still experiencing this issue, please file a bug report with libSDL.
