### ISSUE TITLE
Problem "Source" engine Game. Ubuntu

### ISSUE THREAD

**Issue by Manazius** [ValveSoftware/Source-1-Games#1432]
Hi! There is a trouble with the connection of "source" engine based games to the internet after their last update. Connection becomes very slow after 1-2 hours of playing (Dota 2, CS: Source). And Team fortress 2 connecting on startup takes about 10 minutes. 
Ubuntu 13.04 x86
Linux manazius-Aspire-5750G 3.8.0-31-generic #46-Ubuntu SMP Tue Sep 10 19:56:49 UTC 2013 i686 i686 i686 GNU/Linux
DE: Mate 1.6.0
X.Org X Server 1.13.3
Release Date: 2013-03-07
I have two Graphics card: NVIDIA GeForce GT 630M and Intel intel hd graphics 3000 (optimus technology). I use Bumblebee.
Nvidia drivers version: 325.15

**Comment by kisak-valve** [comment]
Closing due to lack of actionable information. If you are still experiencing this issue with an up to date system, please open a new issue report.
