### ISSUE TITLE
[HL2DM] SV_StartSound: npc/env_headcrabcanister/hiss.wav not precached

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1435]
When I start the map "dm_runoff.bps" I have some annoying errors in my console

SV_StartSound: npc/env_headcrabcanister/hiss.wav not precached (0)
SV_StartSound: npc/env_headcrabcanister/hiss.wav not precached (0)
SV_StartSound: npc/env_headcrabcanister/hiss.wav not precached (0)
SV_StartSound: npc/env_headcrabcanister/hiss.wav not precached (0)
SV_StartSound: npc/env_headcrabcanister/hiss.wav not precached (0)
SV_StartSound: npc/env_headcrabcanister/hiss.wav not precached (0)

**Comment by kisak-valve** [comment]
Closing as this does not appear to affect gameplay.
