### ISSUE TITLE
[HL2DM] Requesting texture value from var "$basetexture" "sky_day01_01"

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1443]
When I use skybox "sky_day01_01" I have errors in my console:

Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_day01_01rt)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_day01_01bk)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_day01_01lf)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_day01_01ft)

**Comment by kisak-valve** [comment]
Closing as fixed in the [2014-05-14 client update](http://store.steampowered.com/news/13353/).
