### ISSUE TITLE
[HL2DM] "Can't use cheat cvar" on game start

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1444]
When I start the game (The first time gamestart, after reinstall), I have this in my console:

Can't use cheat cvar fog_start in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_end in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_startskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_endskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar r_farz in multiplayer, unless the server has sv_cheats set to 1.

(+The second time gamestart):
Can't use cheat cvar cam_snapto in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_ideallag in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdelta in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdist in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistright in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistup in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_collision in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxdistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_mindistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthowidth in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthoheight in multiplayer, unless the server has sv_cheats set to 1.

P.S.: I dont use any cheats or alias cfg.
![123](https://f.cloud.github.com/assets/5474916/1276642/966de238-2e82-11e3-83d8-6590d4f411c0.jpg)

**Comment by kisak-valve** [comment]
Closing as these messages are harmless.
