### ISSUE TITLE
[HL2DM] Square shadow with shadow detail - HIGH

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1454]
Square shadow with shadow detail - HIGH, for example dm_lockdown.bsp
![1](https://f.cloud.github.com/assets/5474916/1276953/c21733a8-2ea0-11e3-92f0-5dd35d59e758.jpg)
![2](https://f.cloud.github.com/assets/5474916/1276954/c24784cc-2ea0-11e3-9635-c7e915ef6f30.jpg)

**Comment by kisak-valve** [comment]
Closing per the last comment.
