### ISSUE TITLE
[HL2] Greek fonts missing (subtitles and menu) (Ubuntu 12.04)

### ISSUE THREAD

**Issue by verdegr** [ValveSoftware/Source-1-Games#1460]
I recently bought HL2. The Steam application is set to Greek Language. When I open HL2 the in game main menu text and the in game subtitles are totally messed. If I set Steam to English, HL2 fonts are correct.

Bug exist on HL2:LC too.

Images attached
![2013-10-09_00001](https://f.cloud.github.com/assets/5059984/1293297/af1d0e30-3062-11e3-91fa-1324b63b894c.jpg)
![2013-10-09_00002](https://f.cloud.github.com/assets/5059984/1293298/af381892-3062-11e3-8f06-b4f541807dfc.jpg)
![2013-10-09_00003](https://f.cloud.github.com/assets/5059984/1293299/af55a5ec-3062-11e3-882d-1e3d9aab8016.jpg)
![2013-10-09_00004](https://f.cloud.github.com/assets/5059984/1293300/af598388-3062-11e3-980a-e5b26f49243c.jpg)

**Comment by kisak-valve** [comment]
Hello @verdegr, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
