### ISSUE TITLE
[TF2] "Automatically respawn after loadout changes in respawn zones" setting no longer works

### ISSUE THREAD

**Issue by powerlord** [ValveSoftware/Source-1-Games#1472]
As of yesterday's update, this setting is ignored and always treated as off

Which means you now must touch a resupply cabinet in order to change your loadout.

_Tested on Windows client and Windows server_

**Comment by micwoj92** [comment]
It seems to work for me on Arch Linux. Could someone with supported (ubuntu/debian) distro check?

**Comment by kisak-valve** [comment]
Thanks @micwoj92, closing per the last comment.
