### ISSUE TITLE
[HLDMS] Improved HLDMS Player Model Physics, Along with Further Data Player models

### ISSUE THREAD

**Issue by Theuaredead** [ValveSoftware/Source-1-Games#1473]
Download:
http://puu.sh/4NN8e

If you want Source files Alfred, post a comment and I'll send them via your "@valvesoftware.com" account if you have one.

Known Bugs,
Walking, Running, and Jumping animations do not load correctly.

**Comment by kisak-valve** [comment]
Closing as a duplicate of #1219.
