### ISSUE TITLE
[TF2] Client crashes on server disconnect or map change

### ISSUE THREAD

**Issue by darkmatterbutterflies** [ValveSoftware/Source-1-Games#1481]
Team Fortress 2 client crashes on server disconnect or map change.

The problem started early September 2013, right after a patch.

Console output is unhelpful, but it _always_ throws this after uploading the .dmp:

> Team Fortress 2/hl2.sh: line 67:  7695 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} 

Attempted user-side remedies and tests:
- Verified cache. Problem persisted.
- There are no custom models or skins in this installation. I'm running close to vanilla. I do have a terse listenserver.conf just to auto-launch a pair of bot teams. Hiding it had no effect on the crashes.
- When running a listen server, there hasn't been a crash no matter how many times I change map.

Edit: It also crashes when kicked from a server. (Server plug-in that kicks on high ping. Convenient for this test.)

Here is the required system information:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x2
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 17 (Beefy Miracle)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.9.10-100.fc17.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11204000
    X Window Manager:  Mutter
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  NVIDIA Corporation GeForce 9400 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 319.32
OpenGL Version: 3.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x641
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 16.14" x 10.08"  (19.02" diag)
                                        41.0cm x 25.6cm  (48.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1708B 8-Ch

Memory:
    RAM:  7986 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  877969 Mb
    Largest Free Hard Disk Block:  605417 Mb

Installed software:

Recent Failure Reports:
    Wed Aug 14 06:52:48 2013 GMT: file ''/tmp/dumps/assert_20130813225244_26.dmp'', upload no: ''HTTP response code said error''
    Wed Aug 14 07:28:11 2013 GMT: file ''/tmp/dumps/crash_20130813193610_1.dmp'', upload no: ''Couldn't connect to server''
    Mon Aug 19 11:07:45 2013 GMT: file ''/tmp/dumps/crash_20130819013014_2.dmp'', upload yes: ''CrashID=bp-15f6631f-6250-42d0-8092-ab6152130819''
    Thu Aug 22 23:35:28 2013 GMT: file ''/tmp/dumps/assert_20130822153320_17.dmp'', upload no: ''Couldn't connect to server''
    Sat Aug 24 08:57:15 2013 GMT: file ''/tmp/dumps/assert_20130824005639_16.dmp'', upload yes: ''CrashID=bp-ebba7ff1-cc69-4f6f-b7d8-89b9e2130824''
    Wed Aug 28 00:12:18 2013 GMT: file ''/tmp/dumps/crash_20130827161114_1.dmp'', upload yes: ''CrashID=bp-7fea9ae0-75a1-4754-9a95-24f612130827''
    Fri Aug 30 08:27:06 2013 GMT: file ''/tmp/dumps/crash_20130828202803_1.dmp'', upload no: ''Couldn't connect to server''
    Fri Aug 30 23:58:25 2013 GMT: file ''/tmp/dumps/crash_20130830145900_2.dmp'', upload yes: ''CrashID=bp-bd17ea68-4621-4258-9f54-2d0322130830''
    Tue Sep  3 03:03:21 2013 GMT: file ''/tmp/dumps/crash_20130902181711_2.dmp'', upload no: ''HTTP response code said error''
    Tue Sep  3 03:10:32 2013 GMT: file ''/tmp/dumps/crash_20130902181712_1.dmp'', upload no: ''HTTP response code said error''
    Tue Sep  3 09:23:51 2013 GMT: file ''/tmp/dumps/crash_20130902230751_2.dmp'', upload yes: ''CrashID=bp-0ea19abe-3356-4e99-97cc-099072130903''
    Wed Sep  4 03:49:45 2013 GMT: file ''/tmp/dumps/crash_20130903183245_2.dmp'', upload no: ''HTTP response code said error''
    Fri Sep  6 09:29:35 2013 GMT: file ''/tmp/dumps/assert_20130906012919_78.dmp'', upload yes: ''CrashID=bp-e4a7875b-244b-4e2b-b2ad-8654d2130906''
    Wed Sep 11 04:38:42 2013 GMT: file ''/tmp/dumps/crash_20130910201415_1.dmp'', upload no: ''HTTP response code said error''
    Wed Sep 11 05:40:11 2013 GMT: file ''/tmp/dumps/crash_20130910210448_1.dmp'', upload no: ''HTTP response code said error''
    Wed Sep 11 06:05:31 2013 GMT: file ''/tmp/dumps/crash_20130910214125_1.dmp'', upload no: ''HTTP response code said error''
    Wed Sep 11 07:30:40 2013 GMT: file ''/tmp/dumps/crash_20130909205814_1.dmp'', upload yes: ''CrashID=bp-5767dffe-3192-4031-9e72-217262130911''
    Thu Sep 12 08:25:37 2013 GMT: file ''/tmp/dumps/crash_20130912000836_1.dmp'', upload no: ''Couldn't connect to server''
    Thu Sep 12 12:40:41 2013 GMT: file ''/tmp/dumps/crash_20130912040020_1.dmp'', upload yes: ''CrashID=bp-c2e3cceb-4b50-4f9b-9ac1-52d192130912''
    Thu Sep 19 09:23:41 2013 GMT: file ''/tmp/dumps/crash_20130911235216_1.dmp'', upload yes: ''CrashID=bp-f3df09b5-ab4e-42fc-a915-5634a2130919''
    Tue Sep 24 10:17:51 2013 GMT: file ''/tmp/dumps/crash_20130924010407_1.dmp'', upload yes: ''CrashID=bp-52d58472-014f-430c-923a-616a52130924''
    Wed Sep 25 04:07:59 2013 GMT: file ''/tmp/dumps/crash_20130924041557_1.dmp'', upload yes: ''CrashID=bp-07bcedb9-e745-46d0-acc1-20c892130924''
    Wed Sep 25 08:59:51 2013 GMT: file ''/tmp/dumps/crash_20130924200803_1.dmp'', upload no: ''Couldn't resolve host name''
    Tue Oct  1 08:35:02 2013 GMT: file ''/tmp/dumps/assert_20131001003446_53.dmp'', upload yes: ''CrashID=bp-08bc4a35-8c8b-4363-b2e0-371ae2131001''
    Wed Oct  2 10:22:45 2013 GMT: file ''/tmp/dumps/crash_20131001232512_2.dmp'', upload yes: ''CrashID=bp-4cce78d1-9f9a-4b1d-996d-e8b4c2131002''
    Sat Oct  5 00:05:51 2013 GMT: file ''/tmp/dumps/assert_20131004160528_26.dmp'', upload yes: ''CrashID=bp-09fe9373-aba0-4dec-ad87-b48332131004''
    Tue Oct  8 07:48:49 2013 GMT: file ''/tmp/dumps/crash_20131007233717_1.dmp'', upload yes: ''CrashID=bp-55377630-ce23-4b58-9e1e-2a0932131008''
    Tue Oct  8 08:18:18 2013 GMT: file ''/tmp/dumps/crash_20131007234847_1.dmp'', upload yes: ''CrashID=bp-20945873-32bb-460f-95c0-26d3e2131008''
    Tue Oct  8 09:30:21 2013 GMT: file ''/tmp/dumps/crash_20131008001906_1.dmp'', upload yes: ''CrashID=bp-5ac7d460-44de-48a9-b428-de2822131008''
    Tue Oct  8 09:46:36 2013 GMT: file ''/tmp/dumps/crash_20131008013839_1.dmp'', upload yes: ''CrashID=bp-feac323c-dd94-4d9c-8f38-c101f2131008''
    Tue Oct  8 10:48:25 2013 GMT: file ''/tmp/dumps/crash_20131007164456_1.dmp'', upload yes: ''CrashID=bp-0b967cbf-488b-4069-b896-04fdd2131008''
    Wed Oct  9 02:42:14 2013 GMT: file ''/tmp/dumps/assert_20131008183852_14.dmp'', upload no: ''Failure when receiving data from the peer''
    Wed Oct  9 08:17:01 2013 GMT: file ''/tmp/dumps/crash_20131008232040_1.dmp'', upload yes: ''CrashID=bp-ee22a097-0778-4cc3-a14a-2d7c82131009''
    Thu Oct 10 08:20:32 2013 GMT: file ''/tmp/dumps/crash_20131010000108_1.dmp'', upload yes: ''CrashID=bp-20cfe33f-0b21-4250-a156-759ee2131010''
    Thu Oct 10 09:37:25 2013 GMT: file ''/tmp/dumps/crash_20131010002141_1.dmp'', upload yes: ''CrashID=bp-09220ce6-afb6-4c45-94bc-e1fe02131010''
    Thu Oct 10 11:02:09 2013 GMT: file ''/tmp/dumps/crash_20131009235943_1.dmp'', upload yes: ''CrashID=bp-25da48c1-fe3b-49c1-bf92-e1cc62131010''
    Thu Oct 10 18:21:37 2013 GMT: file ''/tmp/dumps/assert_20131010100259_15.dmp'', upload no: ''Failure when receiving data from the peer''
    Fri Oct 11 09:53:33 2013 GMT: file ''/tmp/dumps/crash_20131011004305_1.dmp'', upload yes: ''CrashID=bp-6233124c-7cd3-4325-9981-864d72131011''
    Sat Oct 12 22:48:19 2013 GMT: file ''/tmp/dumps/crash_20131012142557_1.dmp'', upload yes: ''CrashID=bp-e079ee7b-2f2e-44e4-b156-3986f2131012''
    Sun Oct 13 01:44:44 2013 GMT: file ''/tmp/dumps/crash_20131012173024_1.dmp'', upload yes: ''CrashID=bp-2ce5061d-6bf9-4257-a823-6ba712131012''
    Mon Oct 14 06:43:44 2013 GMT: file ''/tmp/dumps/crash_20131013222006_1.dmp'', upload no: ''HTTP response code said error''
    Mon Oct 14 08:04:45 2013 GMT: file ''/tmp/dumps/crash_20131013231822_1.dmp'', upload yes: ''CrashID=bp-8f3f1a3f-96bf-4045-8920-480de2131014''
    Mon Oct 14 09:53:09 2013 GMT: file ''/tmp/dumps/crash_20131014003748_2.dmp'', upload yes: ''CrashID=bp-2cb3b42b-9804-4e4b-96fc-aeec52131014''
    Tue Oct 15 01:53:41 2013 GMT: file ''/tmp/dumps/crash_20131014173238_1.dmp'', upload yes: ''CrashID=bp-bc96785a-9247-406c-8699-e9b162131014''
    Tue Oct 15 02:42:09 2013 GMT: file ''/tmp/dumps/crash_20131014180302_1.dmp'', upload yes: ''CrashID=bp-996fb53e-425e-414b-9d95-2990d2131014''
    Tue Oct 15 07:18:26 2013 GMT: file ''/tmp/dumps/crash_20131014225401_2.dmp'', upload yes: ''CrashID=bp-621037bb-7d32-49ca-867b-5f5c12131015''
    Thu Oct 17 08:04:30 2013 GMT: file ''/tmp/dumps/crash_20131016233834_1.dmp'', upload no: ''Couldn't connect to server''
    Fri Oct 18 06:08:24 2013 GMT: file ''/tmp/dumps/crash_20131017220813_12.dmp'', upload no: ''HTTP response code said error''
    Fri Oct 18 06:15:55 2013 GMT: file ''/tmp/dumps/crash_20131017220832_1.dmp'', upload no: ''HTTP response code said error''
    Fri Oct 18 07:22:44 2013 GMT: file ''/tmp/dumps/crash_20131017230810_1.dmp'', upload yes: ''CrashID=bp-a71a1918-9fe9-4eb1-891c-97f022131018''

**Comment by kisak-valve** [comment]
Hello @darkmatterbutterflies, if you are still experiencing this issue with an up to date system, please open a new issue report.
