### ISSUE TITLE
[HLDMS]Trigger_push- on "snarkpit" level disabled (no push)

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1488]
Trigger_push- on "snarkpit" level disabled (no push)

**Comment by kisak-valve** [comment]
Closing do to lack of information, possibly a duplicate of #1368.

**Comment by 1157** [comment]
My bad, the fan @ 1086 -555 -1500  when you press func_button on wall it turns on a fan and activates
a trigger_push at same co-ords
