### ISSUE TITLE
[HLDMS]Tools_skybox error's 

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1492]
![2013-10-20_00002](https://f.cloud.github.com/assets/5712715/1368595/6248f988-39af-11e3-910a-2e776e08fb7b.jpg)
Tools_skybox error's some skybox texture's now "streaky" distorted.

(sky_dayo1) and other stock skyboxes

**Comment by kisak-valve** [comment]
Hello @1157, are you still experiencing this issue?

**Comment by 1157** [comment]
Yes I checked today
![20161227182529_1](https://cloud.githubusercontent.com/assets/5712715/21510509/34570670-cc62-11e6-9950-8ea9ef1f4ea8.jpg)

**Comment by 1157** [comment]
Looks like you got most of the major one's labeled (game_text) is the only last one. Thank you very much on taking the time to label, I closed some other info only or dupe-ish ones.

Thanks again and I will test anything for anyone anytime.

**Comment by kisak-valve** [comment]
Thanks for retesting @1157.
