### ISSUE TITLE
[Feature Request] Ability to remap controller controls

### ISSUE THREAD

**Issue by connorshea** [ValveSoftware/Source-1-Games#1494]
This is, to some extent, possible in the console for Source games. However, it's very much not preferable and the ability to remap the controller through a proper GUI would be incredibly beneficial in the use-case of disabled gamers. While I realize this isn't a large demographic, it would be greatly appreciated by those people.

On top of this, it would be helpful to speedrunners and other users who prefer certain button setups for controllers.

**Comment by kisak-valve** [comment]
Closing as this has been superseded by the steam controller api.
