### ISSUE TITLE
CS:Go - Broken Global Lighting

### ISSUE THREAD

**Issue by SpAMCAN** [ValveSoftware/Source-1-Games#1497]
(NOTE: This is possibly the wrong place for this to go, but since this is the only place where bug reports seem to actually get acknowledged by you guys, I thought it was best to go here)

Something's broken global sunlight in CS:Go. Light that was previously cast for indoor maps appear to be completely disabled. The lighting is working elsewhere, as any outdoor areas seem to work fine. But somehow, the game is culling all indoor lighting (and making maps look pretty plain in the process).

This is perhaps best evidenced in my map Reclamation (http://steamcommunity.com/sharedfiles/filedetails/?id=154633523). You can see in screenshots how the place is supposed to look, but upon loading the game you are greeted by a dull, very plainly lit map due to the lack of sunlighting in the main area. Strangely, I can't even figure out how the culling would work, since the roof is entirely made up of Func_Details, and there is a large skybox space above it (to fit in an airplane flying over that casts a shadow - not that it does now thanks to this change).

It is also evident in the official map AR_Baggage. This map used to have sunlights coming through the windows, but these are now gone. (you can see this by opening up the map and comparing it to videos made earlier this year).

I can kind of see what you're trying to do here by lowering the number of 'dynamic' shadows, but this isn't optimisation, this is just breaking things.

Why is this a thing now, and can you make it not a thing any more?

**Comment by kisak-valve** [comment]
Closing as CS:GO issues are not tracked in this issue tracker.
