### ISSUE TITLE
[TF2] Battalion's Backup damage resist impairs rocket jumps.

### ISSUE THREAD

**Issue by Iggy2539** [ValveSoftware/Source-1-Games#1507]
While under the effects of the Battalion's Backup, the Soldier cannot rocket jump as effectively due to the 35% damage resistance carrying over to -35% knockback. Other sources of damage resistance (MvM upgrades, Demoknight Shields) don't affect self-inflicted knockback, so why does the Backup?

I am not sure whether this carries over to other classes, like Demomen stickyjumping, but it is very annoying to fail a rocket jump because you had a buff.

**Comment by kisak-valve** [comment]
Hello @Iggy2539, are you still experiencing this issue?

**Comment by hahagoni** [comment]
The bug is fixed by now
