### ISSUE TITLE
[TF2] YouTube login fails due to improper statically-linked libcurl

### ISSUE THREAD

**Issue by ElectricTriangle** [ValveSoftware/Source-1-Games#1511]
Trying to log in to YouTube through the client delivers this error message to the console.

Error: Protocol https not supported or disabled in libcurl

My system info:
https://gist.github.com/ElectricTriangle/6708900

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue?

**Comment by Alkaris** [comment]
Google has changed their login systems so much over the years that its no longer possible to sign-in from the replay editor in TF2. It would need an API overhaul just to make it work again.

**Comment by kisak-valve** [comment]
Thanks for the feedback @Alkaris. I'm going to close this issue report as the original issue is no longer relevant. Feel free to open a new issue report with regards to the current issue with youtube integration.

**Comment by ElectricTriangle** [comment]
I'm kind of surprised you'd close the bug before I'd gotten the chance to respond in the same day, @kisak-valve. In any case Alkaris is right, the old YouTube API has long since been discontinued.
