### ISSUE TITLE
SDK2006 Update for Linux servers

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#1513]
After Steam decided to move all their games to the SteamPipe content system, all Hidden Source servers were giving users the "Steam Validation Rejected" error which resulted in most Hidden servers being empty.

More information: 
http://forum.hidden-source.com/showthread.php?11788-Steam-VALIDIATION-REJECTED-when-i-join-any-server-please-help

http://forum.hidden-source.com/showthread.php?11786-Creating-a-Hidden-Source-Server-With-SteamCMD

**Comment by kisak-valve** [comment]
Closing due to the user going away.
