### ISSUE TITLE
[L4D2] Terrible perfs

### ISSUE THREAD

**Issue by terzag** [ValveSoftware/Source-1-Games#1518]
When I try to play L4D2 on Linux, I have really bad performances: a lot of input lag (despite direct mouse input being set), fps drop, small freezes happening quite often...

I thought it was coming from lack of optimization during the beta but now it's out officially and still runs poorly.

Other Source games like HL2, TF2, and Dota 2 work fine on my config (with minor issues), I disable antialiasing and Vsync and the game runs with no problem on Windows on the very same PC.

I guess it's likely a graphic driver issue (ATI RadonHD 7770 with Catalyst 13.11 beta 1 on Ubuntu 13.10) but it's a bit strange that L4D2 runs way worse than other games like Dota 2 (which is more recent).

Any idea of what I can check to see if there are specific issues that could be reported ?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
