### ISSUE TITLE
TF2 really unstable - crashing a lot on high settings

### ISSUE THREAD

**Issue by WindohsCrasher** [ValveSoftware/Source-1-Games#1519]
I have set every graphics option to the highest on my NVidia GTX 760 (2 GB VRAM, 319.60 stable driver and also tested latest 331 beta driver).
All the time that I play with high settings, TF2 crashes after ~2-3 map loading cycles. Sometimes, it gives me this error message:

http://imgur.com/bxEeaxP
(for those who don't want to load the pic, it says "Can't load lump 53, allocation of 14135737 bytes failed!!!")

Might be some VRAM issue because nvidia-settings displays a VRAM usage >= 1300 MB which is growing a lot with each map loading cycle.

Please Valve, try it yourself, because I have this bug for almost half a year now :( Join some different servers and disconnect again on very highest settings.

It's not the GPU because I had the same problems with my old GTX 460.

Sysinfo:

Prozessor:
    Hersteller: GenuineIntel
    CPU-Familie: 0x6
    CPU-Modell: 0x2a
    CPU-Stepping: 0x7
    CPU-Typ: 0x0
    Geschwindigkeit: 3401 MHz
    8 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    "openSUSE 12.2 (i586)" (32 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.4.47-2.38-desktop
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11203000
    X-Fenstermanager: KWin
    Steam-Runtime-Version: steam-runtime-release_2013-10-23

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 760/PCIe/SSE2

```
Treiber-Version: 4.4.0 NVIDIA 331.17
OpenGL-Version: 4.4
Desktop-Farbtiefe: 24 Bit per Pixel
Monitor-Aktualisierungsrate: 60 Hz
Anbieterkennung: 0x10de
Gerätekennung: 0x1187
Anzahl der Monitore: 1
Keine Grafikkartenanzahl entdeckt
Prim. Anzeigeauflösung: 1920 x 1080
Desktop-Auflösung: 1920 x 1080
Prim. Anzeigegröße: 106,0 cm x 62,6 cm (123,1 cm diag.)

Primärer Bus: PCI Express 16x
Primärer VRAM: 2048 MB
Unterstützte MSAA-Modi: 2x 4x 8x 16x 
```

Soundkarte:
    Audiogerät: SigmaTel STAC9708,11

Speicher:
    RAM: 8074 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 300328 MB
    Größter freier Festplattenspeicherblock: 11402 MB

**Comment by kisak-valve** [comment]
Hello @WindohsCrasher, @pizzadude, if either of you are still experiencing this issue with an up to date system, please open a new issue report.
