### ISSUE TITLE
[TF2] Random mouse clicks are not handled

### ISSUE THREAD

**Issue by DarkwaveMD** [ValveSoftware/Source-1-Games#1520]
While playing in TF2 sometimes 2-5 clicks in row are ignored. I reinstalled game and replace mouse - still have same problem. However mouse works great in Dota 2 and other games/programs.
My specs : - https://gist.github.com/DarkwaveMD/7231584

**Comment by kisak-valve** [comment]
Hello @DarkwaveMD, are you still experiencing this issue with an up to date system?

**Comment by DarkwaveMD** [comment]
Hello @kisak-valve , this issue was fixed about 2 years ago.

**Comment by kisak-valve** [comment]
Thanks for the feedback @DarkwaveMD.
