### ISSUE TITLE
[TF2] Crash while playing after latest update

### ISSUE THREAD

**Issue by AnAkkk** [ValveSoftware/Source-1-Games#1524]
TF2 crashed after a few minutes of playing. The crash dump can be found here:
http://rghost.net/49843924

<pre>Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  2403 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  KWin
    Steam Runtime Version:  <Runtime disabled>
    
Video Card:
    Driver:  NVIDIA Corporation GeForce 8800 GT/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 331.17
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x611
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 18,62" x 11,65"  (21,93" diag)
                                            47,3cm x 29,6cm  (55,7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 512 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC888
    
Memory:
    RAM:  2005 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  111615 Mb
    Largest Free Hard Disk Block:  57293 Mb
    
Installed software:
    
Recent Failure Reports:</pre>

**Comment by kisak-valve** [comment]
Hello @AnAkkk, if you are still experiencing this issue, please open a new issue report.
