### ISSUE TITLE
[L4D2] Persistent Lag Spikes

### ISSUE THREAD

**Issue by heavyelement** [ValveSoftware/Source-1-Games#1527]
The game takes almost 10 minutes to load a campaign and after the game loads, it's completely unplayable because of lag spikes. 

The game will go from between 30-60 fps to 2-3 fps, constantly. I have fiddled with the settings (setting everything to low, medium and high) with little noticeable improvement.

I'm on Ubuntu 13.10, with AMD's proprietary drivers (I've tried the stable versions and most of the beta versions). My graphics processor is the Radeon HD 6620G (which is an AMD A8 APU). I've got 6 gigs of RAM, and a quad-core 1.5 GHz CPU.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
