### ISSUE TITLE
[TF2] Eureka Effect Taunt (and tauntkills) overlapped by Thriller Halloween Taunt

### ISSUE THREAD

**Issue by jakeowaty** [ValveSoftware/Source-1-Games#1529]
It's not neccessarily a bug, but it is an issue that should be resolved quickly.
As you probably know, during Halloween and Blood Moon regular taunts are being replaced by Thriller taunt in about 50% of the time.

The problem is that whenever you want to use the Eureka Effect, which is based around a special game mechanic using a taunt to teleport back in the spawn, there is a high chance of you actually doing the Thriller instead of teleporting.

The issue is more annoying, when it actually costs your life or more, because instead of teleporting you just stand there and frolic. It should at least (the halloween taunt) not work upon pressing M2, but it does even with that, which is really gamebreaking and cost us a competetive match.

While mentioning the Eureka Effect taunt, I think other taunts, like the tauntkills should be fixed as well. Many times you'd like to tauntkill an enemy, which is also a part of the game mechanic, instead you taunt and it can get yourself killed. I don't think anyone would mind the taunt on harmless taunts, but it should be removed on the tauntkill taunts at least.

Hope I stated where the problem lies and I post in the right section!

Cheers!

PS: If you need any proof, here's the STV POV demo with selected ticks where it happened (official competetive match):

http://speedy.sh/9cN67/20131104-2020-pl-badwater-red-blu.dem

49000 < Attempt to teleport out of the thrid point, taunt instead
60000 < Attempt to teleport out, possibly costs us a game

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Ashetf2** [comment]
This was not fixed. I've experienced several times that taunt kills were overriden by the Thriller taunt

**Comment by MikhailaTF** [comment]
Does this also affect other functional taunts such as the phlogistinator's charge and eating any of heavy's lunchbox items? (both of which can be activated by taunting under the right conditions)

**Comment by Ashetf2** [comment]
> Does this also affect other functional taunts such as the phlogistinator's charge and eating any of heavy's lunchbox items? (both of which can be activated by taunting under the right conditions)

I think they use a different mechanism to call the taunt. I have never experienced taunting with the Eureka Effect being overriden by the thriller taunt, neither with lunchboxs. I can't confirm the phlog taunt being overriden too, but i don't think it is

**Comment by kisak-valve** [comment]
Hello @Ashetf2, `I have never experienced taunting with the Eureka Effect being overriden by the thriller taunt` makes it sound like the issue originally reported here was resolved in 2013 and a newer regression appeared sometime time more recently. Let's use #4444 to track the newer variant of this issue.
