### ISSUE TITLE
[TF2][OS X] Can't shoot while crouching 

### ISSUE THREAD

**Issue by jimbond** [ValveSoftware/Source-1-Games#1530]
On the OS X build of TF2, I can't shoot when crouching.  If I'm shooting then crouch, I can still shoot but if I crouch, then shoot it doesn't work.  Can anyone else confirm this?

**Comment by kisak-valve** [comment]
Hello @jimbond, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
