### ISSUE TITLE
[HL2DM][Linux][DedicatedServer] [S_API FAIL] SteamAPI_Init() failed

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1533]
Clear server starts with error

> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
> dlopen failed trying to load: /root/.steam/sdk32/steamclient.so
> with error:
> /root/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory

Fedora Linux 16

**Comment by kisak-valve** [comment]
Hello @darrnoktjurna, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
