### ISSUE TITLE
[HL2DM][DedicatedServer] Server doesn't create txt: mapcycle, motd, motd_text

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1534]
Clear server doesn't create txt: mapcycle, motd, motd_text
Console:

> Using map cycle file 'cfg/mapcycle_default.txt'. ('cfg/mapcycle.txt' was not found.)
> Set motd from file 'cfg/motd_default.txt'. ('cfg/motd.txt' was not found.)
> Set motd_text from file 'cfg/motd_text_default.txt'. ('cfg/motd_text.txt' was not found.)

**Comment by kisak-valve** [comment]
These files are intentionally excluded from the steam depots so that automated updates do not blindly overwrite the server's config.
