### ISSUE TITLE
[Tf2] Voice lines treat payload carts as if they were control points

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#1535]
I noticed this quite some time ago, after I created a custom keybinding for the "Help!" line. When you're pushing the cart and activate that voice command, the player will say something about capturing a control point, like "Rally 'round! Help me cap this point!" More recently I discovered that this applies to defense lines as well; I was a demoman and killed someone who was pushing their cart, and he said "That was my point you were standin' on!"

I'm surprised that, after Payload has been around for over five years, there were never any payload-specific lines recorded to replace these. Especially since the scout, heavy, and sniper (and no other classes, for some reason) all have lines that they say whenever their cart is stopped or the enemy cart goes backwards, even halfway across the map from where they are. If I had known you would be bringing all of the actors back into the studio to record new voice lines for the Halloween update, I would have brought this up sooner.

**Comment by stevethepocket** [comment]
Yep.

Incidentally, it occurred to me that this would be easier than I was making it out to be. Players already have voice lines they automatically say when they start pushing or at random times while they're pushing. So the game must be aware somehow that they're not just in a CP capture zone.

What I'd recommend is to assign the "Help!" command to a select subset of the "cartmovingforwardoffense" and/or "cartstaycloseoffense" lines that are already in the game. There are plenty to choose from. The only thing I'm unsure of is how much or little that should overlap with the existing behavior of using those lines automatically. Looking through them, there are some I'm sure I've never heard before, so I'm guessing only some are being used at the moment.

**Comment by Tiagoquix** [comment]
OP, does this still happen?

**Comment by kisak-valve** [comment]
Closing pending feedback.
