### ISSUE TITLE
TF2 Reinstall Issues

### ISSUE THREAD

**Issue by ZnaZanZ** [ValveSoftware/Source-1-Games#1537]
Hi there-

I, along with many others, have been experiencing a problem when attempting to reinstall TF2 after the SteamPipe content conversion.  After deleting all local game files through my steam library for TF2 in August, I recently attempted to install the game again.  It starts preparing the install, except it gets stuck on "Creating Local Game Cache Files" which is odd since to my knowledge SteamPipe no longer uses GCF's.

Thank you and I hope a solution can be found.

**Comment by kisak-valve** [comment]
Closing as out-of-scope for this issue tracker.
