### ISSUE TITLE
[TF2] Killcam zoom effect "sticks" to subsequent camera changes

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#1541]
The [Vertigo effect](http://tvtropes.org/pmwiki/pmwiki.php/Main/VertigoEffect) used when the game shifts to the kill cam has a habit, every so often, of getting "stuck" so that every subsequent change of camera — such as switching between character during pre-respawn specate mode and the respawn itself, as well as the shift from first to third person when the player dies — is accompanied by the effect as well.

The issue has always seemed to correct itself after a few minutes, and never lasts past the next map change. It happens rarely, and I haven't noticed any particular pattern to discern what might trigger it. I believe it's occurred on both of my computers since I started noticing it (which was at least a year ago), but for now I'll just post the specs on my primary one, where it happened just a few minutes ago:

```
Processor Information:
    Vendor:  GenuineIntel
    Speed: 2394 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  ATI Radeon HD 4800 Series

    DirectX Driver Name:  aticfx32.dll
    Driver Version:  8.961.0.0
    DirectX Driver Version:  8.17.10.1124
    Driver Date: 5 Apr 2012
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: ATI Radeon HD 4800 Series
    VendorID:  0x1002
    DeviceID:  0x944a
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 26.65" x 15.00"  (30.55" diag)
                                            67.7cm x 38.1cm  (77.6cm diag)
    Primary Bus Type Not Detected
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Speakers (High Definition Audio

Memory:
    RAM:  4095 Mb
```

**Comment by kisak-valve** [comment]
Hello @stevethepocket, are you still experiencing this issue?

**Comment by stevethepocket** [comment]
Apparently not; I'd completely forgotten about this thing.

**Comment by kisak-valve** [comment]
Thanks for retesting @stevethepocket, closing.
