### ISSUE TITLE
[TF2] mp_scrambleteams_auto_windifference miscounts wins

### ISSUE THREAD

**Issue by goosmurf** [ValveSoftware/Source-1-Games#1544]
I've noticed (over a period of many months, over many different maps) that mp_scrambleteams_auto_windifference often does not take effect when it should.

i.e. with mp_scrambleteams_auto_windifference 2 sometimes the scramble does not happen until the win difference is 3 or 4.

At first I thought it was map specific as we mostly noticed this on 5CP maps. However during Halloween when I played too much plr_hightower_event it became obvious that the problem is not map specific (i.e. NOT due to the map incorrectly registering wins).

Given that sometimes it kicks in at 1 over the specific windifference, and sometimes 2 over, it seems like there is maybe a counting error somewhere.

**Comment by kisak-valve** [comment]
Hello @goosmurf, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
