### ISSUE TITLE
[L4D2] Switching Between Weapons Crash

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#1545]
Everything it's okay using Windows 8.1 Enterprise (Build 9600) with ATI Radeon HD 6690 but sometimes, often, I get some crashes when I switch between weapons or items.

Here's a link: http://forums.steampowered.com/forums/showthread.php?t=3199423
This PC information: http://privatepaste.com/e0877381b9

**Comment by kisak-valve** [comment]
Closing as general stability from 2013 is no longer relevant.
