### ISSUE TITLE
[linux] Portal, GMod segfault with new Mesa from git

### ISSUE THREAD

**Issue by abbradar** [ValveSoftware/Source-1-Games#1548]
See https://bugs.freedesktop.org/show_bug.cgi?id=71543
Alexander wrote possible explanation for this, looks like there's a problem with libudev.so.0 provided with game.

**Comment by kisak-valve** [comment]
Closing as this appears to be a general steam runtime compatibility issue. This is currently being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4768.
