### ISSUE TITLE
TF2 Left Click / Mouse Capture Issues

### ISSUE THREAD

**Issue by gsilvers** [ValveSoftware/Source-1-Games#1553]
Hello Valvians?

I'm encountering an issue. I'm not sure if the fault really lies with the source engine or with Kwin. This issue only occurs when I'm in KDE, if I use something like I3 to manage windows the games (tf2 in this case) behaves fine. Here's what happens.

1) I run TF2 full screened or windowed full screen. Have a panel at the bottom of the screen set to hide / behind windows.

2) Try to rocket jump :)

It seems like when you drag your mouse down to where it would trigger this window the game is not keeping the mouse. I've verified removing the panel fixes this but really shouldn't the game keep the mouse locked/centered? 

Here is my system info. Graphics is an integrated intel HD5200 Iris.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.0-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11404000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 9.2.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0xd26
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 12.17" x 6.81"  (13.94" diag)
                                        30.9cm x 17.3cm  (35.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  15976 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  137426 Mb
    Largest Free Hard Disk Block:  56287 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed. If you are still experiencing this issue with an up to date system, please open a new issue report.
