### ISSUE TITLE
Gamma settings don't work in any Source games

### ISSUE THREAD

**Issue by dscharrer** [ValveSoftware/Source-1-Games#1555]
Adjusting the brightness slider simply has no effect.

This is by far not limited to source games - the underlying problem is that `XStoreColors()` [hasn't worked worked in a long time](https://bugs.freedesktop.org/show_bug.cgi?id=27222) and because of that, `SDL_SetWindowGammaRamp()` (and the `SDL_SetWindowBrightness()` wrapper) [is broken as well](https://bugzilla.libsdl.org/show_bug.cgi?id=1680).

However, there are working functions to change (display) gamma: `XF86VidModeSetGamma()` and `XRRSetCrtcGamma()` (as can be seen with the `xgamma` or `xrandr --gamma` commands)

Another option would be to do the user brightness adjustment as part of the rendering pipeline (ie: integrate it into HDR tonemapping). GoldSrc seems to do something like that for its 'gamma' setting.

This also affects the Steam overlay, which according to these [beta update notes](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1801733269149197884) is supposed to restore gamma while active: In games that _do_ manage to change the display gamma (notably Serious Sam 3 and Oil Rush), the overlay fails to change it back when activated.

**Comment by micwoj92** [comment]
The slider in menu options works for me, probably needs retesting if this depends on de/wm or maybe compositor

**Comment by dscharrer** [comment]
Yeah, works for me too. From the linked bugs it seems this was fixed in Xorg in 2016. According to that bug report there may still be problems when using the modesetting driver but I don't use that so can't confirm.
