### ISSUE TITLE
[TF2] Score table issues after Two Cities Update

### ISSUE THREAD

**Issue by vesch** [ValveSoftware/Source-1-Games#1556]
There are some issues with score table after Two Cities Update:
- Ping column is only partially visible on a 1366x768 screen (of laptop).
- Streak column is always empty. At least on cp and pl maps.
- "Streak" is not translated to Russian.

Also Highest Killstreak and Count fields on a round end screen are always empty and not translated.

Game language set to Russian.

Here is 2 screenshots:
[Score table](https://f.cloud.github.com/assets/5899372/1599977/db60bd9c-5363-11e3-8748-4b4e434a83e3.jpg)
[Round end screen](https://f.cloud.github.com/assets/5899372/1599978/db7eebdc-5363-11e3-92b8-3de2330b4c2c.jpg)

**Comment by kisak-valve** [comment]
Hello @vesch, @korden32, are either of you still experiencing this issue?

**Comment by korden32** [comment]
@kisak-valve well... It's been a loooong time (three years, oh man...)
Since Streak column no longer displayed on scoreboard, there is no issue in both English and Russian (just re-checked it in both languages).

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
