### ISSUE TITLE
[Faceposer] rebuild scenes.image not effective

### ISSUE THREAD

**Issue by tetsu0** [ValveSoftware/Source-1-Games#1559]
When rebuilding the scenes.image file after creating new .vcds, half-life 2 cannot find the new files though hammer can find them and the maps compile properly.
vcd Location: ep2/scenes

Unless the files need to go into a separate directory, I have no idea what's going on

system specs:
AMD Fx8320 @ 3.5Ghz
8Gb DDR3 RAM
Radeon HD 6900
Windows 7

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been figured out. If there is still an issue with the SDK, please open an issue report in the source-sdk-2013 issue tracker.
