### ISSUE TITLE
TF2 crashes after a while

### ISSUE THREAD

**Issue by pizzadude** [ValveSoftware/Source-1-Games#1567]
After a while of playing TF2 the game will suddenly crash with this error message in /var/log/syslog

```
kernel: [14196.852711] IOJob0[16518]: segfault at 0 ip b75ed641 sp b2355fb0 error 6 in libc-2.15.so[b74b3000+1a4000]
```

Here is my system info:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3201 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-56-generic-pae
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 319.32
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x11c0
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Nvidia GPU 41 HDMI/DP

Memory:
    RAM:  8015 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  930900 Mb
    Largest Free Hard Disk Block:  194034 Mb

Installed software:

**Comment by kisak-valve** [comment]
Hello @pizzadude, if you are still experiencing this issue with an up to date system, please open a new issue report.
