### ISSUE TITLE
TF2 Crashes Randomly During Gameplay

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#1570]
I've been having random crashes occur anywhere from 5 to 30 minutes while playing.  This was not happening before or during the Halloween Event.  It is happening on all sorts of maps, and appears the most frequent when there is a lot of action occurring on screen.  I tested again today after the latest TF2 update, and it is still happening.

Here is my info.  The last listed crash report is a result of this bug:  CrashID=bp-2b00d454-93f0-4250-b062-e69532131207

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.0-14-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  NVIDIA Corporation GeForce 9400/integrated/SSE2

```
Driver Version:  3.3.0 NVIDIA 319.60
OpenGL Version: 3.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x86a
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: Integrated
Primary VRAM: 256 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Nvidia MCP79/7A HDMI

Memory:
    RAM:  3700 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  1873515 Mb
    Largest Free Hard Disk Block:  1565845 Mb

Installed software:

Recent Failure Reports:
    Wed Dec  4 23:24:16 2013 GMT: file ''/tmp/dumps/crash_20131204182406_32.dmp'', upload yes: ''CrashID=bp-cafe1b2a-c119-4736-9c02-3a3f52131204''
    Sat Dec  7 12:56:05 2013 GMT: file ''/tmp/dumps/crash_20131207075547_15.dmp'', upload yes: ''CrashID=bp-11e58c2a-8d52-4526-82f6-b377e2131207''
    Sat Dec  7 16:43:56 2013 GMT: file ''/tmp/dumps/crash_20131207113716_1.dmp'', upload yes: ''CrashID=bp-2b00d454-93f0-4250-b062-e69532131207''

**Comment by kisak-valve** [comment]
Closing as general stability from 2013 is no longer relevant. If you are still experiencing this issue, please open a new issue report.
