### ISSUE TITLE
[TF2] Items for Professional Fabricator are not being added to the recipe

### ISSUE THREAD

**Issue by SirAss** [ValveSoftware/Source-1-Games#1577]
I'm having this issue since two days ago and, as it seems, it's very unknown for the rest of the players. I'm not being able to add some ingredients to the fabricator, not even the Roboparts. It seems this is a problem that goes to other Fabricators as well.

Recording of the Issue:
http://www.youtube.com/watch?v=ddX1PyDo1XY

**Comment by kisak-valve** [comment]
Hello @SirAss, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
