### ISSUE TITLE
[TF2]Teleport effect persists after round end

### ISSUE THREAD

**Issue by b4ckd0or** [ValveSoftware/Source-1-Games#1581]
If you teleport during the round end before the new round starts the teleport effect persists even when you die.

http://cloud-4.steampowered.com/ugc/703983393821970949/A867A73D8F1A6C217049FFE99F09B10E5E2AA5C1/

http://cloud-2.steampowered.com/ugc/703983393821968260/C205DE76F4D37D0371FCDE5B201394B358B63BB6/

Specs: https://gist.github.com/b4ckd0or/6571637

**Comment by kisak-valve** [comment]
Hello @b4ckd0or, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
