### ISSUE TITLE
[TF2] Server crash during gameplay and map change

### ISSUE THREAD

**Issue by thepparker** [ValveSoftware/Source-1-Games#1583]
We've been having consistent problems with servers crashing for a while now, both during game play and during map changes.

Here is the stack dump: https://gist.github.com/bladez-/7969459

We're running Ubuntu 12.04 @ 3.5.0-41, with libc-i386 @ 2.15-0ubuntu12.04

I currently have no steps to reproduce the problem, as it seems to occur randomly

**Comment by kisak-valve** [comment]
Hello @thepparker, @Mi1ezDR, if either of you are still experiencing this issue, please open a new issue report.
