### ISSUE TITLE
[HL2] Sound glitches and missing models/textures

### ISSUE THREAD

**Issue by Samcity** [ValveSoftware/Source-1-Games#1587]
A lot of sound glitches and missing textures/models, all I see are purple and black, mostly, and there is a lot of sound glitches, one of them I can confidently say is the combine door locks and also the gman starting sound effect...

**Comment by kisak-valve** [comment]
Closing do to lack of feedback. If you are still experiencing this issue, please let me know and we can re-open this issue report.
