### ISSUE TITLE
[TF2] Missing DT_RUNPATH on hl2_linux

### ISSUE THREAD

**Issue by ariscop** [ValveSoftware/Source-1-Games#1589]
hl2_linux requires libtcmalloc_minimal.so.4, which is in $ORIGIN/bin but is not searched
vguimatsurface.so also needs DT_RUNPATH = $ORIGIN to launch without hl2.sh

**Comment by kisak-valve** [comment]
Hello @ariscop, this appears like you are trying to run TF2 from outside steam which is not supported.
