### ISSUE TITLE
[HLDMS] Model folder missing on Rcon player Model

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1594]
Model folder missing on Rcon player Model, materials for Rcon are there, just not the models folder..
root\materials\models\player\mp
root\models\player\mp.
![recon_1](https://f.cloud.github.com/assets/5712715/1785889/ce2d8a68-68eb-11e3-98fd-1927d783ac4e.png)
![git_2](https://f.cloud.github.com/assets/5712715/1785900/e31a1248-68eb-11e3-97e2-48fd4428d4fc.png)
![recon](https://f.cloud.github.com/assets/5712715/1785903/ef8b8002-68eb-11e3-8f2d-e80a0c3388e3.jpg)

**Comment by kisak-valve** [comment]
Closing per @alfred-valve's decision at https://github.com/ValveSoftware/Source-1-Games/issues/1216#issuecomment-24551230.
