### ISSUE TITLE
[ALL][HL2DM] Game crash with setting "cl_downloadfilter none" on server with custom files (sprite .vtf)

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1596]
Game client crash with setting "cl_downloadfilter none" or "cl_downloadfilter maps only" on server with custom files and the reason of this crash is sprite .vft files. (They dont download them, and then - game crash, no errors or black-pink textrures.)
Please make an exception for sprite .vtf files (If the player doesn't have this file) with setting "cl_downloadfilter none".

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed.
