### ISSUE TITLE
TF2: Text in end-of-round counter exceeds its border

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#1606]
![2013-12-28_00001](https://f.cloud.github.com/assets/3085348/1818549/4e109f86-700d-11e3-9443-e9a4f4f9b508.jpg)

As you can see, the text at the top touches the top border now. This happened when you added the kill streak counters.

**Comment by kisak-valve** [comment]
Hello @stevethepocket, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by stevethepocket** [comment]
Oh right, I forgot about this. Yes, for the record, this one officially got fixed ages ago; I don't think it was even in the patch notes.
