### ISSUE TITLE
[L4D2][Linux][Radeon/Mesa] Crashes during versus mode

### ISSUE THREAD

**Issue by kekkj** [ValveSoftware/Source-1-Games#1610]
CPU: AMD Phenom II X4 955 Black Edition
GPU: Sapphire Radeon HD 5770 1GB
Driver: Mesa 10.0.1-1

---

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11405000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD JUNIPER

```
Driver Version:  3.0 Mesa 10.0.1
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x68b8
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 1200
Desktop Resolution: 3200 x 1200
Primary Display Size: 14.45" x 10.83"  (18.03" diag)
                                        36.7cm x 27.5cm  (45.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  3957 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  118377 Mb
    Largest Free Hard Disk Block:  81204 Mb

Installed software:

Recent Failure Reports:

---

L4D2 is the best running source game for me right now but versus mode is pretty much unplayable because at seemingly random moments my entire X session stops responding because of it.
When it crashes I only hear the last ~1 second of audio repeated over & over again, then my screens go black and I can't even switch to a different TTY. Then I'm forced to hold the power button on my case and restart.
I've been patient and waited for it to maybe recover but it just doesn't.

As far as I can tell this only happens when I play versus mode.

There also doesn't seem to be happening anything as far as errors go, I ran it through ssh on another machine to see if I could see anything and the only thing that popped up last before it crashed was this:

"Installing breakpad exception handler for appid(steam)/version(1388596836_client)"
Note that I used 1388596836 because I didn't save the exact number but I know it was a unix timestamp.

I recently switched from Manjaro to Antergos, one uses XFCE4 and I use Openbox on the other, and the exact same thing happens in both installs, I've tried changing the graphics settings, windowed mode/borderless/fullscreen, different resolutions etc.

![2013-12-30_00001_grant](https://f.cloud.github.com/assets/6055771/1829878/d29cd5b2-730a-11e3-8a20-da602cfa8896.jpg)
Thanks!

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
