### ISSUE TITLE
[TF2] ESC to skip intro video aborts connection

### ISSUE THREAD

**Issue by henke37** [ValveSoftware/Source-1-Games#1618]
The connection attempt is aborted when you launch the game by clicking on an auto connect link and then skip the intro video by hitting the ESC key. The keypress should only affect the video and nothing more.

**Comment by Wasmanr2** [comment]
@henke37 is this still happening ?

**Comment by henke37** [comment]
I have since learned that any other key will skip the intro video, but not abort the connection. This is satisfactory for me, consider it AS_DESIGNED.
