### ISSUE TITLE
[L4D2] Special polish diacritical characters are not shows

### ISSUE THREAD

**Issue by suore** [ValveSoftware/Source-1-Games#1621]
Hello L4D2 have problem with polish characters.

Screen:

http://ubuntuone.com/3btjQ3bkciSsDlAGajmVuk

At Screen is:
"NIE       YJESZ"
"...ale twoi towarzysze wci             mog      uciec"

Correctry shoud be:
"NIE ŻYJESZ"
"...ale twoi rowarzysze wciąż mogą uciec".

Works only : Ó and Ł letter.
Letter like " Ą, Ż Ź, Ć, Ń, Ś,Ę are replaced for "        " like double "TAB" at LibreOffice.

**Comment by kisak-valve** [comment]
Closing in favor of #1785.
