### ISSUE TITLE
[L4D2] Crash/Segmentation Fault After Map Load

### ISSUE THREAD

**Issue by Espionage724** [ValveSoftware/Source-1-Games#1626]
It seems with any mode, singleplayer or multiplayer, L4D2 just crashes after the loading screen is complete (I never get in-game).

I'm using a Radeon HD 7650M dGPU with oibaf's PPA on Kubuntu 13.10 (Kernel 3.13 daily). My laptop is dual graphics, and does the same thing when using my 7660G iGPU (I switch between the two with Prime)

Here's my console window output:

[0111/165435:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 550
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197992258516 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197992258516
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
[0111/165437:ERROR:resource_bundle.cc(411)] Failed to load /home/espionage724/.local/share/Steam/SteamApps/common/Left 4 Dead 2/cef_gtk.pak
Some features may not be available.
[0111/165437:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1389306532_client)
Focused window is now 0, 0
OnFocusWindowChanged to unknown window type: k_EWindowTypeNonSteamDesktop, 0
Focused window is now 3, 550
OnFocusWindowChanged to unknown window type: k_EWindowTypeGame, 550
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 8
Did not detect any valid joysticks.
Querying for subscribed files
IDirect3DDevice9::Create: BackBufWidth: 1366, BackBufHeight: 768, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO
BinkOpen( /home/espionage724/.local/share/Steam/SteamApps/common/Left 4 Dead 2/left4dead2/media/valve.bik )
ConVarRef volume doesn't point to an existing ConVar
BinkOpen( /home/espionage724/.local/share/Steam/SteamApps/common/Left 4 Dead 2/left4dead2/media/l4d2_intro.bik )
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 1 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 8 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 1272 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 1272 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
ERROR: ld.so: object '/home/espionage724/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140111165435_1.dmp
CGameStreamThread: Added instance ID 5120 for appid 550
/home/espionage724/.local/share/Steam/SteamApps/common/Left 4 Dead 2/./hl2.sh: line 67:  5081 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 550 "Left 4 Dead 2", ProcID 5081 
Focused window is now 1, 0
OnFocusWindowChanged to unknown window type: k_EWindowTypeSteamDesktop, 0
Focused window is now 0, 0
OnFocusWindowChanged to unknown window type: k_EWindowTypeNonSteamDesktop,

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
