### ISSUE TITLE
[HL1:S] (Linux) Surface Tension, hatch not working

### ISSUE THREAD

**Issue by magnush** [ValveSoftware/Source-1-Games#1627]
In the part of the Surface Tension level where you walk through a tunnel and a soldier opens the hatch and throws in a hand grenade, afterwards it's not possible to open the hatch. It just makes the "locked door" sound. Also the explosion does a lot less damage than in the original half-life.

I'm not a Source/HL hacker but If it helps I could provide a savegame file or anything else, just let me know. System info below.
# 

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 20 (Heisenbug)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.6-300.fc20.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Desktop 

```
Driver Version:  3.0 Mesa 9.2.5
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x162
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 13.31" x 10.63"  (17.01" diag)
                                        33.8cm x 27.0cm  (43.2cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  15756 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  168880 Mb
    Largest Free Hard Disk Block:  106170 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing per the last comment.
