### ISSUE TITLE
Visual glitch in TF2

### ISSUE THREAD

**Issue by roryking** [ValveSoftware/Source-1-Games#1628]
I've attached screenshots of the bug. Whenever I die, get covered in jarate, or receive an ubercharge, the screen is covered with a red/black pattern.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3206 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-031300rc7-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11405000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BARTS

```
Driver Version:  3.0 Mesa 10.1.0-devel
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6739
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 27.87" x 15.67"  (31.97" diag)
                                        70.8cm x 39.8cm  (81.2cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  7984 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  112546 Mb
    Largest Free Hard Disk Block:  63760 Mb

Installed software:

Recent Failure Reports:
    Wed Jan 15 23:19:55 2014 GMT: file ''/tmp/dumps/crash_20140115171954_5.dmp'', upload yes: ''CrashID=bp-b20d8dd5-e922-4710-98e2-128e72140115''
    Wed Jan 15 23:34:56 2014 GMT: file ''/tmp/dumps/crash_20140115173455_2.dmp'', upload yes: ''CrashID=bp-861dcd50-994a-4c4b-a0c3-25cc42140115''

![2014-01-15_00007](https://f.cloud.github.com/assets/6414678/1926278/610f3a76-7e3f-11e3-8abc-ab049be9c871.jpg)
![2014-01-15_00005](https://f.cloud.github.com/assets/6414678/1926279/610f7ce8-7e3f-11e3-8c44-e9de713e5dbe.jpg)
![2014-01-15_00006](https://f.cloud.github.com/assets/6414678/1926280/610f9f8e-7e3f-11e3-9634-d03d5fdc3983.jpg)
![2014-01-15_00003](https://f.cloud.github.com/assets/6414678/1926281/610fba78-7e3f-11e3-84cd-f1ee8cfc5817.jpg)
![2014-01-15_00002](https://f.cloud.github.com/assets/6414678/1926282/611078b4-7e3f-11e3-993c-298adc64fd75.jpg)
![2014-01-15_00004](https://f.cloud.github.com/assets/6414678/1926283/6110811a-7e3f-11e3-9c0b-f291d5d6af47.jpg)
![2014-01-15_00001](https://f.cloud.github.com/assets/6414678/1926284/6119f34e-7e3f-11e3-92d9-7ef9ee4c66dc.jpg)

**Comment by kisak-valve** [comment]
Closing per the last comment.
