### ISSUE TITLE
Checking the Source SDK Project

### ISSUE THREAD

**Issue by AndreyKarpov** [ValveSoftware/Source-1-Games#1629]
I downloaded and checked the project's source codes at the end of 2013 already and intended to write an article about it during the New Year holidays. But laziness prevailed over the craving for creativity, and I sat down to writing the article only on getting back to work. However, I doubt that the source codes have changed during this time. Now you are welcome to have a look at the suspicious code fragments found in the project code by the PVS-Studio code analyzer.

Full Article: http://www.viva64.com/en/b/0229/

**Comment by kisak-valve** [comment]
Closing as this issue is effectively untrackable. Please use separate issue reports in the source-sdk-2013 issue tracker, one issue per issue report.
