### ISSUE TITLE
HalfLife 2 abrindo no lugar do CS:S

### ISSUE THREAD

**Issue by JackCarmo** [ValveSoftware/Source-1-Games#1637]
Ola gostaria que alguém pudesse me ajudar, Tenho o CS: source na minha biblioteca steam e depois da ultima atualização quando eu clico em jogar ele não abre,ou melhor dizendo abre o jogo Half Life2 no lugar do cs source,não sei mais o que fazer agradeço desde já.

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved.
