### ISSUE TITLE
[ASK][CS:GO] Counter-Strike: Global Offensive bug section

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1645]
Where is Counter-Strike: Global Offensive bug section?
Or where I can post cs:go bugs?

**Comment by kisak-valve** [comment]
Closing as CS:GO is not tracked here. There is an issue tracker for Mac and Linux client issues at https://github.com/ValveSoftware/csgo-osx-linux (but not issues that affect all three platforms).
