### ISSUE TITLE
[L4D2][Linux] extremely small fonts in lobby chat

### ISSUE THREAD

**Issue by Mixaill** [ValveSoftware/Source-1-Games#1648]
Extremely small fonts in lobby chat in Left 4 Dead 2 in Linux (in Windows text is displayed correctly)

Ubuntu 14.04 amd64, compiz(unity)
Nvidia 740M, Nvidia blob 331.38, Optirun via nvidia-prime(not bumblebee)

Linux :
![linux](https://dl.dropboxusercontent.com/u/1517779/valve/l4d2/fonts-linux.jpg)

Windows:
![windows](https://dl.dropboxusercontent.com/u/1517779/valve/l4d2/fonts-windows.jpg)

**Comment by Inoki** [comment]
Same here still, and that's one year after this post.

**Comment by kisak-valve** [comment]
Closing in favor of #1883.
