### ISSUE TITLE
[HL2DM] Error symbols in server "History" browser in "Last played" time.

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1655]
ENGLISH
![222](https://f.cloud.github.com/assets/5474916/2143836/79f5fdc8-9379-11e3-9b67-8bf7f6449dc9.jpg)
RUSSIAN
![12233](https://f.cloud.github.com/assets/5474916/2143893/a9f7e7a6-937a-11e3-84f0-d320f7ae49ba.jpg)
ESPANOL
![320_screenshots_2014-02-12_00001](https://f.cloud.github.com/assets/5474916/2143895/bbc422ba-937a-11e3-98d0-745fc7bdf6fc.jpg)
Tested on different computers.

**Comment by kisak-valve** [comment]
Hello @darrnoktjurna, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
