### ISSUE TITLE
Game crashes, taking with parts of X.

### ISSUE THREAD

**Issue by Mumbo-Jumbo** [ValveSoftware/Source-1-Games#1657]
After upgrading from a ati hd 5650 to a 7770, i get crashes when playing games based on the source engine. so long:

-I don't think the hardware is correctly detected since it recommends me no aa (in css, lfd2, and dod:s) and a resolution of 1280xsomething in lfd2.
-The crashes itself are likely to - https://github.com/ValveSoftware/Source-1-Games/issues/1610 - game crashes, sound is looped, input not detected. however, i can reisub, so this is not a kernel panic.
-driver detects the hd7770 correct, also, neither unity engine nor any other of my non-source games crashed in this way.
-allready tried to reinstall fglrx, steam, and the games.
-temperature isn't the reason, it seems to keep stable.

Any ideas?

steam output:
http://pastebin.com/Y2NK6G0G
OpenSuse 13.1, 64 bit, xfce, 3x3,2ghz, 8 gb ram, fglrx 13.251.
hardware information:
http://pastebin.com/2sZCaqSw

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
