### ISSUE TITLE
[TF2] Allow all maps in quickplay

### ISSUE THREAD

**Issue by henke37** [ValveSoftware/Source-1-Games#1658]
Allow people to search for games using any map.

I propose a three way option: official, installed or any map. The default can be installed (since official maps are the only installed ones at first).

**Comment by Wasmanr2** [comment]
Quickplay got removed and replaced by Casual.
I guess you can close this Feature Request @kisak-valve  as it doesnt exist anymore also you can choose any map/specific maps that you want to play thanks to the Casual.

**Comment by kisak-valve** [comment]
Closing per last comment.
