### ISSUE TITLE
[L4D2][Mac OS X] Game Crashes (DownloadManager broken)

### ISSUE THREAD

**Issue by raziEiL** [ValveSoftware/Source-1-Games#1662]
Unlike WIN client that works great Mac OS X and perhaps Linux game client immediately crashes if it downloads any custom files from server.

1.) Run game (Game was installed from scratch) and connect to community server.
2.) Server send some file for ex. melee weapon script
3.) Ta-dah! Crash!

crash log: https://cloudup.com/csrEDjA2jp7

**Comment by kisak-valve** [comment]
Hello @raziEiL, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
