### ISSUE TITLE
[CS:S/TF2] Aliasing during movement

### ISSUE THREAD

**Issue by gutigen** [ValveSoftware/Source-1-Games#167]
I got a lot of odd aliasing or flickering at edge of everything which is static (buildings, terrain etc) while moving my character in game. Doesn't affect player models and items. Doesn't matter how high I set antialiasing or anisotrophy filtering (or turn it off).

Happens in Ubuntu - 12.04, 12.10 and 13.04 with Unity.
Doesn't happen in Gnome Fallback or Gnome Shell (3.6) in 12.10 and 13.04 (did not tested other DEs in 12.04).

System info:
https://gist.github.com/gutigen/4984001

**Comment by kisak-valve** [comment]
Closing as there is nothing actionable in this issue report. If you are still experiencing this issue with an up to date system, please provide new details so this can be investigated further.
