### ISSUE TITLE
[CS:GO] plugin_unload segfault on linux srcds

### ISSUE THREAD

**Issue by birkett** [ValveSoftware/Source-1-Games#1671]
To reproduce: 
1. Load CS:GO dedicated server on Linux
2. Load a VSP plugin - I have tested the latest dev branch of Mani Admin Plugin and Metamod Source
3. "plugin_unload" or "exit" will cause a segfault somewhere in engine.so. I have seen references to CInitTracker deconstrutor.

**Comment by kisak-valve** [comment]
Closing as CS:GO is not tracked in this issue tracker.
