### ISSUE TITLE
[TF2] SRCDS Random Freeze

### ISSUE THREAD

**Issue by StrikerMan780** [ValveSoftware/Source-1-Games#1673]
I've been running a standard TF2 Server (which is my main server) ever since my MvM one went down thanks to this issue that has yet to be fixed: https://github.com/ValveSoftware/Source-1-Games/issues/1551

But now, I can't even run my main server for any longer than a day without it freezing. This never used to happen, and is getting to be a real problem, because since it is freezing rather than crashing, the server does not reboot itself. Here's a dump of the process, I hope you guys can figure out what is causing the freeze, and if you do, can fix it... https://shadowmavericks.com/files/CrashDumps/srcds_140225_140924.zip

**Comment by kisak-valve** [comment]
Hello @StrikerMan780, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
