### ISSUE TITLE
[CS:S] Blue smoke in very specific places

### ISSUE THREAD

**Issue by lecbee** [ValveSoftware/Source-1-Games#1675]
In Counter Strike: Source, if you shoot the wall, there is often a smoke. But in some very limited places, this smoke is blue.

I firstly submitted a bug on the Mesa bugzilla, but it looks like it's not a driver bug.

More details (+ screenshots) are in the original bug post here:
https://bugs.freedesktop.org/show_bug.cgi?id=74085

**Comment by kisak-valve** [comment]
Closing as a duplicate of #646.
