### ISSUE TITLE
[L4D2] Problems with sound

### ISSUE THREAD

**Issue by Manazius** [ValveSoftware/Source-1-Games#1676]
No sound in the game Left 4 Dead 2. I checked another source-engine based games — there are all is fine. Is there any way to fix it? Thanks.
OS: openSUSE 13.1 i586
Hardware: Intel Core i3 2350M 2300 МГц, NVIDIA GeForce GT 630M. All proprietary drivers installed

**Comment by kisak-valve** [comment]
Hello @Manazius, are you still experiencing this issue with an up to date system?

This was most likely selinux blocking libmiles.

**Comment by kisak-valve** [comment]
Closing pending feedback.
