### ISSUE TITLE
Recent Steam Update broke almost every game server (Mainly Linux)

### ISSUE THREAD

**Issue by xerox8521** [ValveSoftware/Source-1-Games#1677]
Alot of servers do not start properly since most recent public patch (not beta). which should have "fixed" linux problems caused even more problems.
Affected games:
Zombie Panic Source
Left 4 Dead 2

as soon you try to start the server you will receive on Left4Dead2

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.
 as error tried everything google said so far.
Debian 7 64 Bit
libgcc is installed like it says on the valve wiki
this: cp steamcmd/linux32/steamclient.so ~/.steam/sdk32/steamclient.so 
doesnt help as ./steam/sdk32 is a symlink to /steamcmd/linux32 where the file already existed.

On Zombie Panic Source you will receive a 

---
- Unable to load Steam support library.*
- This server will operate in LAN mode only
  *********************************************************
  error with no other information what exactly is the error to be able to fix it

**Comment by kisak-valve** [comment]
Hello @xerox8521, are you still experiencing this issue with an up to date system?

**Comment by xerox8521** [comment]
@kisak-valve currently everything works fine with the L4D2 Server either steamcmd update or recent game updates fixed it though the issue still persist on Zombie Panic Source.

**Comment by kisak-valve** [comment]
Thanks for retesting @xerox8521.
