### ISSUE TITLE
Invisible weapons in Half-Life: Source on Mac

### ISSUE THREAD

**Issue by FilmComposer79** [ValveSoftware/Source-1-Games#1688]
Hi guys,

I'm running Half-Life Source on my quad-core 266 GHZ Mac Pro, and cannot see any weapons that I have. It's very difficult to use the crowbar on anything since it's invisible. Same with the rest of the weapons. Any tips or suggestions on how this glitch can be fixed? Also when I'm around someone who is alive (I'm still in the beginning of the game) like a scientist or Barney, they make these sounds constantly like they are getting attacked. It's quite annoying as well. Please help.

Thanks,
Matt

**Comment by kisak-valve** [comment]
Hello @FilmComposer79, are you still experiencing this issue after verifying your game cache and making sure you have an up to date system? Is the game installed on a case-sensitive filesystem?

**Comment by kisak-valve** [comment]
Closing pending feedback.
