### ISSUE TITLE
[TF2] Mouse cursor still locked when chat window is shown.

### ISSUE THREAD

**Issue by johnwchadwick** [ValveSoftware/Source-1-Games#1701]
This change occurred a bit ago, but I figured someone would notice and fix it... hasn't happened. Basically, normally when you hit say or teamsay, the chat window pops up, your mouse is unlocked and shown over the TF2 window, and you can scroll the chat window, copy/paste, etc. For some odd reason, this is broken, so the cursor remains invisible/locked.

I am running Ubuntu 13.10 with XFCE 4.10 and proprietary NVidia drivers. I have no reason to believe my setup is at all at fault, however.

**Comment by kisak-valve** [comment]
Closing pending feedback.
