### ISSUE TITLE
[l4d2][linux][ubuntu 13.10][bug]any 3rd party map campaign CRASH game,only 1st stage works

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/Source-1-Games#1705]
[l4d2][linux][ubuntu 13.10][bug]any 3rd party map campaign CRASH game,only 1st stage works

platform: ubuntu 13.10 64bit linux
steam for linux latest ver.
linux graphic driver, nvidia 319.32(ubuntu official source)

game: left for dead 2, steam ver.

third party map related: from l4dmaps.com. i test 4 maps.

crash course
death from above
skipping class
urban flight

and i also installed "valve's missing content fix" (a 12MB patch, it is here http://www.l4dmaps.com/details.php?file=26132).

how to reproduce the issue:

play linux ver. of left 4 dead 2 on steam for linux. windowed mode.

play online mode, choose play with friends(local server,my own computer play it and meanwhile as in-game server), with those 3rd party mod campaigns/maps(vpk files installed, of course).

all these 3rd party mod campaign can play with linux ver. but, only 1st stage/map working, after 1st stage, then loading to 2nd map/stage, after statistics scene for the 1st stage, it just crashes.

the ubuntu 13.10 gnome console info is quite long. view it here

http://paste.ubuntu.com/7178637/

(that is a pastebin from ubuntu website)

crash id is CrashID=bp-43e49c4a-177f-439c-9c5c-437ef2140330

i don't know why crash, i played this game months ago, and i remember linux ver. working well in the past...
## hope this issue would be fixed.

if you need the dump file or other info from gnome console,e.g. some linux command output, just reply. thanks.

my system info collected by steam client help.

http://pastebin.ubuntu.com/7178723/

thanks.

**Comment by kisak-valve** [comment]
Hello @alexanderhou, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
