### ISSUE TITLE
[HLDMS] Client model stuck on gordon

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1710]
Client model stuck on gordon, will not change from gordon unless you edit 
"C:\Program Files\Steam\steamapps\common\Half-Life 1 Source Deathmatch\hl1mp\cfg\config.cfg"

Change the cl_playermodel "models/gordon.mdl"  to gman ect. and set file to "read only"
Sometimes this too does not work and you have type in client console to "force:

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed.
