### ISSUE TITLE
[TF2] env_lightglows in Nucleus conflict with sniper's view

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#1711]
This is a really weird one. When I play as Sniper in koth_nucleus, when I scope in on the opposite side, the env_lightglows on the ceiling lights do this:

![2014-04-18_00003](https://cloud.githubusercontent.com/assets/3085348/2747270/d20d7212-c762-11e3-82fa-159cb6fb6910.jpg)

And then when you zoom back out, it stays like that:
![2014-04-18_00002](https://cloud.githubusercontent.com/assets/3085348/2747271/d20dbd26-c762-11e3-8bba-d72a5d43f513.jpg)

Proof that it happens on the other side as well:
![2014-04-18_00004](https://cloud.githubusercontent.com/assets/3085348/2747269/d1f825e2-c762-11e3-9117-d13d5450b11e.jpg)

I've played Sniper on this map before... like, not recently, but within the last year, I think, and I know this has never happened to me before. Here's a basic rundown of my specs; I'll try this out on my other two systems tomorrow and see what's what.

Intel Core 2 Quad 2.6GHz
AMD Radeon HD 4850, 1GB VRAM, Catalyst 13.9 Legacy Driver (Catalyst Control Center not installed)
4 GB DDR2 RAM
Windows 7 Pro x64 with SP1

**Comment by kisak-valve** [comment]
Closing per the last comment.
