### ISSUE TITLE
Cannot connect to any servers

### ISSUE THREAD

**Issue by Tal70** [ValveSoftware/Source-1-Games#1718]
i've had half life 2 deathmatch for quite a while and everything worked fine and now the servers dont show up for some reason, i live in Israel and my download speed is 6.46 mbps. i tried everything that came to mind and nothing worked, tried re-installing , verifying integrity trying betas ect. help if you feel like you can help, if not don't bother.

Tal

**Comment by Xeogin** [comment]
This is no longer an issue, please close.
