### ISSUE TITLE
More colorfull console

### ISSUE THREAD

**Issue by deri82** [ValveSoftware/Source-1-Games#172]
The console is very usefull when you know what to do. But It's very slow to read. 

Why not add tabs to it? Like on browsers nowadays. Different messages on different tabs (user defined yes/no).

But the idea I like more is that you should use different colors to show different messages. 

It would make the console outpot much more easier to read. When you are playing against other players you don't have that much of time to read the console output.

**Comment by kisak-valve** [comment]
Closing as this appears to have been implemented.
