### ISSUE TITLE
net_maxfilesize locked at 16 after last HL2DM update.

### ISSUE THREAD

**Issue by fuckpaypal** [ValveSoftware/Source-1-Games#1722]
Hello,

After chatting with a fellow server owner today who was having some problems with a map that wasn't downloading i started to investigate what might be causing this and to my surprise it seems that now, after the last HL2DM update, the value of "net_maxfilesize" is locked to 16 and can no longer be changed, this in term should mean that no map larger than 16MB can be downloaded.

I have also noticed the max file size has been decreased from 128 to 64 and while this is still an acceptable max file size the value remains locked at 16 regardless of the value set in server.cfg.

EDIT: After looking into the problem more it seems my friends issue was caused by something else and maps over 16MB do download fine, thankfully.

However, the question still remains, whats up with "net_maxfilesize" ?

**Comment by kisak-valve** [comment]
Hello @fuckpaypal, are you still experiencing an issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
