### ISSUE TITLE
[CS:GO] AMD CrossfireX Performance

### ISSUE THREAD

**Issue by Wolfie43** [ValveSoftware/Source-1-Games#1732]
Either crossfire is enabled or disabled i see no fps difference.
Multicore rendering is enabled, tried mat_queue_mode 2 and nothing.
My specs
e8400 @ 4.1ghz
4gb RAM DDR2 @ 900mhz
2x 6870 Crossfire
I'm 100% sure my crossfire is working because i tested it on few benchmark and games.

**Comment by kisak-valve** [comment]
Closing as CS:GO is not tracked here.
