### ISSUE TITLE
Could not find required OpenGl entry point 'gColorMaskIndexedEXT'! Either your video card is unsupported or OpenGl needs to be updated'   

### ISSUE THREAD

**Issue by meslowinski** [ValveSoftware/Source-1-Games#1735]
I have a dual boot machine with Windows 7 and Half-life2 works just fine in Windows 7.

Here are my system specs:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0xf
    CPU Model:  0x4
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3207 Mhz
    2 logical processors
    1 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.0-20-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11405000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  NVIDIA Corporation GeForce 6200/AGP/SSE2

```
Driver Version:  2.1.2 NVIDIA 304.116
OpenGL Version: 2.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x221
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1024 x 768
Desktop Resolution: 2048 x 768
Primary Display Size: 11.97" x 8.98"  (14.96" diag)
                                        30.4cm x 22.8cm  (38.0cm diag)
Primary Bus: AGP 8x
Primary VRAM Not Detected
Supported MSAA Modes:  2x 4x 16x 
```

Sound card:
    Audio device: Analog Devices AD1985

Memory:
    RAM:  3315 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  150124 Mb
    Largest Free Hard Disk Block:  106175 Mb

Installed software:

Recent Failure Reports:
    Sat May 17 16:47:41 2014 GMT: file ''/tmp/dumps/assert_20140517124725_15.dmp'', upload yes: ''CrashID=bp-800c020d-8dcd-4920-87cd-2490c2140517''

**Comment by kisak-valve** [comment]
Closing per the last comment.
