### ISSUE TITLE
TF2 lags hard for no obvious reason.

### ISSUE THREAD

**Issue by ProhibitedUser** [ValveSoftware/Source-1-Games#1738]
Well it does exactly as the title says. It's certainly not normal lag between my computer and servers, as each time I've tried I've checked my ping and every time it's been good. I tend to get chuggy framerate and delayed input, interrupted by semi-regular freezes that last about a second. All this makes the game completely unplayable, as I simply can't react to anything happening on screen. My graphics card is an AMD HD 7770, and should be more than capable of handling TF2, as it did when I ran Windows 7.

Does anyone have any ideas please?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant. If you are still experiencing this issue on an up to date system, please open a new issue report.
