### ISSUE TITLE
[TF2] Dying in negative trigger_gravity zones will make you float into infinity.

### ISSUE THREAD

**Issue by StrikerMan780** [ValveSoftware/Source-1-Games#1745]
Download this map: http://tf2.gamebanana.com/maps/161214

Then go to the jump-pad, jump, and as you are floating into the air, commit suicide. After you respawn, jump... you'll float off into the sky. This happens in all sorts of maps that use this form of locomotion for the players. It's like TF2 doesn't reset the behavior after death.

**Comment by kisak-valve** [comment]
Closing per the last two comments.
