### ISSUE TITLE
Counter Strike: Global Offensive Game Crashing Bug

### ISSUE THREAD

**Issue by kybeTV** [ValveSoftware/Source-1-Games#1746]
I was playing on with bots in casual game mode and I found this bug while trying to give myself a usp-s. I assumed you would just have to type the console command "give weapon_usp", but when I tried this, a box popped up like a debugger (check picture below). No matter what I clicked, the game would instantly crash. I loaded it back up and tried the same command and the same thing happened.

![giveweaponusp](https://cloud.githubusercontent.com/assets/7834496/3213353/0005733c-ef8a-11e3-87a9-8731070b5765.png)

**Comment by kisak-valve** [comment]
Closing as CS:GO issues are not tracked in this issue tracker.

As a side note, https://forums.alliedmods.net/showthread.php?t=223796 has some related information.
