### ISSUE TITLE
[TF2] SourceTV Relay Doesn't Autorecord Demos

### ISSUE THREAD

**Issue by thesupremecommander** [ValveSoftware/Source-1-Games#175]
According to the 11/27/07 patch, relays are supposed to be able to record demos via tv_autorecord.

However, when trying to do so via a Linux master and Linux relay, the relay connects and reports that it's recording a demo, but the files it produces are around 170KB in length and freeze the game momentarily when I attempt to play them back. The master is able to record demos fine.

**Comment by kisak-valve** [comment]
Hello @thesupremecommander, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
