### ISSUE TITLE
[CRASH][L4D2][linux][ubuntu 14.04]game crash frequently when loading map

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/Source-1-Games#1761]
[CRASH][L4D2][linux][ubuntu 14.04]game crash frequently when loading map

platform: ubuntu 14.04 LTS 64bit
steam for linux latest ver.

game: left 4 dead 2 for linux.

linux kernel: 3.13.0-30-generic (ubuntu 14.04)
graphic card: nvidia 9600gt, driver ver. 331.38 from ubuntu official source library.

system info:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x12
    CPU Model:  0x1
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2994 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-30-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  NVIDIA Corporation GeForce 9600 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 331.38
OpenGL Version: 3.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x622
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC662 rev3

Memory:
    RAM:  7979 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  144055 Mb
    Largest Free Hard Disk Block:  113813 Mb

Installed software:

Recent Failure Reports:
    Mon Jun 23 14:07:28 2014 GMT: file ''/tmp/dumps/assert_20140623220415_1.dmp'', upload yes: ''CrashID=bp-fcf36eae-e71a-4d69-9cd0-9b8b02140623''
    Mon Jun 23 14:44:59 2014 GMT: file ''/tmp/dumps/assert_20140623220729_1.dmp'', upload yes: ''CrashID=bp-0205e4fa-e568-4a38-8753-ab0362140623''

=-=-==-==-=--=-=

i just play the game with some steam group servers. official maps. those servers got some server addons/mods. e.g. some tanks got 40.000~100.000 pts of Hitpoints(server modded), and the server supporting 10+ more players at the same time.

game client crashes frequently when playing these servers.

can you help? it is quite abnormal.

the crashes often happen when map loading, i mean, from chapter 1 to chapter 2 of the same map, there'd be a loading, and when a finale stage you finished, then go to next map , into its 1st stage, there'd be a loading, such loading may cause game client crash.

thank you.

**Comment by kisak-valve** [comment]
Hello @alexanderhou, if you are still experiencing this issue with an up to date system, please open a new issue report.
