### ISSUE TITLE
[Linux] [TF2] Very Brief Frame Rate Drops

### ISSUE THREAD

**Issue by sunnybubblegum** [ValveSoftware/Source-1-Games#1764]
For the most part, Team Fortress 2 runs with great frame rates on my system -- usually 70 to 120 fps.

That's why it's confusing when I get these little dips down into the 20s to 40s, and the game hiccups. I even had the program quit mid-game two days ago; the reason I now feel nervous running it at all.

I've tried to determine whether something specific was causing the drops, such as water or fire particles, or lots of other players on screen. But alas, it truly seems random. (Granted, I have been playing on servers with 20+ players on them -- but I do the same with Counter-Strike: Source.)

I've even turned my settings down from the recommended High to Medium. This hasn't helped.

Games like Counter-Strike: Source, Half-Life 2: Deathmatch and Left 4 Dead 2 run smooth as silk for me, with frame rates in the 100s to 200s. Why does this one run the least stably?

Are there any console commands I can use that will reduce things like explosions, or high-demanding elements, in case they are the culprit?

Thank you.

System Information:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x5
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-42-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 240/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 331.38
OpenGL Version: 3.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xca3
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.62" x 13.39"  (27.13" diag)
                                        60.0cm x 34.0cm  (68.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  7984 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  232570 Mb
    Largest Free Hard Disk Block:  108001 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @sunnybubblegum, are you still experiencing this issue with an up to date system?

**Comment by hahagoni** [comment]
If we mean the same under "seemingly random hiccups, frame drops" then yes, this still can occur sometimes.

https://gist.github.com/hahagoni/359a2fdae5ee57393842558bef33e7de

**Comment by kisak-valve** [comment]
Closing as outdated.
