### ISSUE TITLE
[Linux] [TF2] Some textures flicker when viewed through sniper scope in hightower

### ISSUE THREAD

**Issue by pizzadude** [ValveSoftware/Source-1-Games#1769]
I have recorded a short video of this problem. Some textures flicker when viewed through the sniper scope. This was spotted on plr_hightower while on the blue team. Please let me know if you can reproduce this.

https://dl.dropboxusercontent.com/u/6822978/tf2hightowerscopetextureflicker.m4v

Sysinfo: http://pastebin.com/EYBUT5BV

**Comment by micwoj92** [comment]
Video is unavailable.
