### ISSUE TITLE
CSGO: Freebsd + Workshop crashing

### ISSUE THREAD

**Issue by Isheh** [ValveSoftware/Source-1-Games#1770]
When running Freebsd 10 a csgo server will fail to start if any workshop parameter options are set:

VAC secure mode is activated.
GC Connection established for server version 0
/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp (660) : Assertion Failed: bRet
Assert( Assertion Failed: bRet ):/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp:660

ExceptionHandler::GenerateDump waitpid failed:ExceptionHandler::WaitForContinueSignal                                sys_read failed:Invalid argument
Bad file descriptor
No minidump written, nothing to upload.
/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp (731) : CClientPipe::BWriteAndReadResult: BReadResult failed
/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp (731) : Fatal assert failed: /home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp, line 731.  Application exiting.

Assert( CClientPipe::BWriteAndReadResult: BReadResult failed ):/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp:731

ExceptionHandler::GenerateDump waitpid failed:ExceptionHandler::WaitForContinueSignal                                sys_read failed:Invalid argument
No minidump written, nothing to upload.
Bad file descriptor
_ExitOnFatalAssert
cat: hlds.59737.pid: No such file or directory

warning: A handler for the OS ABI "GNU/Linux" is not built into this configuration
of GDB.  Attempting to continue with the default i386 settings.

"/data/games/csgo/beta/./srcds_linux.core" is not a core dump: File format is ambiguous
No stack.
debug.cmds:2: Error in sourced command file:
No frame selected.
email debug.log to linux@valvesoftware.com
Tue Jul  1 13:42:33 UTC 2014: Server restart in 10 seconds
LD_LIBRARY_PATH=/data/games/csgo/beta/bin:/games/csgo/beta:/games/csgo/beta/bin:
# Using breakpad minidump system

Using breakpad crash handler

Debug.log:

---

CRASH: Fri Jun 13 14:44:52 UTC 2014
Start Line: ./srcds_linux -game csgo -console -usercon +game_type 0 +game_mode 0 +mapgroup mg_bomb +map de_dust -authkey `key removed by moderator` +host_workshop_collection 227761693 +workshop_start_map 125636884 -debug

**Comment by kisak-valve** [comment]
Closing as CS:GO is not tracked in this issue tracker.
