### ISSUE TITLE
half-llife:source

### ISSUE THREAD

**Issue by vedran19755** [ValveSoftware/Source-1-Games#1771]
can you please help in hl:s i have the original skins and sounds of weapons like on half-life 1 
![2014-07-02_00001](https://cloud.githubusercontent.com/assets/8044898/3452933/b4dc852c-01bc-11e4-8eaa-9091f3545a59.jpg)
![2014-07-02_00002](https://cloud.githubusercontent.com/assets/8044898/3452934/b4dec9c2-01bc-11e4-976b-a1a96c8dcf26.jpg)
![2014-07-02_00003](https://cloud.githubusercontent.com/assets/8044898/3452935/b4e43f38-01bc-11e4-86f0-4fb6e78a0ff4.jpg)
![2014-07-02_00004](https://cloud.githubusercontent.com/assets/8044898/3452936/b4ebc7c6-01bc-11e4-8da3-a114cd350695.jpg)
![2014-07-02_00005](https://cloud.githubusercontent.com/assets/8044898/3452937/b4f8a900-01bc-11e4-85f4-a2f10accd5c8.jpg)
![2014-07-02_00006](https://cloud.githubusercontent.com/assets/8044898/3452938/b50166ee-01bc-11e4-82e1-86dc0e82e313.jpg)
![2014-07-02_00007](https://cloud.githubusercontent.com/assets/8044898/3452939/b5098d92-01bc-11e4-8639-e46a57c56cd5.jpg)
![2014-07-02_00008](https://cloud.githubusercontent.com/assets/8044898/3452940/b512ff8a-01bc-11e4-8d73-3949f0d6d1d1.jpg)
![2014-07-02_00009](https://cloud.githubusercontent.com/assets/8044898/3452941/b51d3e0a-01bc-11e4-8828-98a53c641b55.jpg)

**Comment by kisak-valve** [comment]
Closing per the last comment.
