### ISSUE TITLE
[CS:GO] Problem with showing servers in Steam Community Search

### ISSUE THREAD

**Issue by faustoFF** [ValveSoftware/Source-1-Games#1773]
I have two dedicated hardware servers in different data centers in Moscow (DC1 and DC2 for example). Just for test at the same time I turn on one freshly installed CS:GO game servers in each data centers. Builds of this game servers absolutely identiсal, start map is de_dust2. Then I try to search game servers in Steam Community Search by map de_dust2: server in DC1 is found instantly (as other community servers), but in DC2... it isnt found.

This situation with all servers of customers in DC1 and DC2. No problems with online in DC1 and problems (poor online stats) in DC2.

When I set some sv_tags for this servers and search by it - server in DC1 and in DC2 showing instantly at the same time.

Steam API is returns both servers in DC1 and in DC2 is in search (by using http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=<SERVER IP HERE>&format=json)

3 days server was running: server in DC1 is almost full 24 hours of the day, but in DC2 otherwise is almost empty.

DC1: 31.131.**_.**_ (Moscow, Russia)
DC2: 83.222.**_.**_ (Moscow, Russia)
me: 37.235.**_.**_ (Cental Russia)

May be it is because wrongly working geolocation in Steam search? Is any ways to force define game server geo location (sv_region ?) or correct/adjust results of Steam search geolocation?

Thanks.

**Comment by kisak-valve** [comment]
Hello @faustoFF, 
CS:GO issues are not tracked in this issue tracker. I've passed this on to the CS:GO team, and there most likely won't be any updates reported here.
