### ISSUE TITLE
[Portal Linux] achievements are not given

### ISSUE THREAD

**Issue by illumilore** [ValveSoftware/Source-1-Games#1774]
I have attempted to get the achievement for falling 30000 feet by falling between 2 portals and then going afk for 30 minutes, however the game never awarded me the achievement for that, even though that distance should have been covered during that freefall time. I have also taken several radios to the spots where they start beeping morse/binary code and left them there for several iterations of the code sequence, but I still have no achievement progress awarded for that. 

The advanced maps also seem to be locked, even though I have previously beaten the game and have the achievement for that already awarded. Only about 4 of the beginning chapters are available when starting a new game, even though they all should be available to start for the same reason.

**Comment by kisak-valve** [comment]
Hello @illumilore, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
