### ISSUE TITLE
L4D2 Linux crashing on loading into a dedi server.

### ISSUE THREAD

**Issue by WildCard65** [ValveSoftware/Source-1-Games#1775]
It seems that the l4d2 client for linux crashes when trying to download custom content from a fast download server.
And in the server console, it shows that the player was disconnected for "No steam logon" when he/she had one.
Note: Not using myself even though it's affecting me when I join my own server.
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  1800 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-30-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x106
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                        34.4cm x 19.4cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  5849 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  594361 Mb
    Largest Free Hard Disk Block:  381788 Mb

**Comment by kisak-valve** [comment]
Hello @WildCard65, are you still experiencing this issue with an up to date system?

**Comment by WildCard65** [comment]
I haven't used linux version of steam in a while, forgot this existed, I've been using a slightly better laptop then one I was using when this happened.
