### ISSUE TITLE
[Portal on Ubuntu] Restarting doesn't work properly

### ISSUE THREAD

**Issue by njrphd** [ValveSoftware/Source-1-Games#1777]
In the options menu, under audio, I changed the spoken language, which requires a restart. I also changed captioning from no captions to subtitles (dialog only). I pressed OK and then pressed 'restart now'. The game closed, but did not automatically open back up. When I tried to open it myself manually, Steam said it was already running. Waiting for several minutes and then trying again doesn't help the matter.

I manually closed the processes hl2_linux and hl2.sh, opened Portal back up, and the language setting is still unchanged (although the subtitle setting is changed).

**Comment by kisak-valve** [comment]
Hello @njrphd, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
