### ISSUE TITLE
[CS:GO] Play GOTV demos,which recorded on older version.

### ISSUE THREAD

**Issue by hitmany** [ValveSoftware/Source-1-Games#1782]
Please update the demo-recording system. Let it not depend on cs:go client version

Our admin-team is experiencing such a problem:
We are suspecting that one player is cheating. We are collecting demos in order to prove that he is guilty. But CS:GO client updates 3 times a week and we cannot ban him, because old demos can't be played on new cs:go versions. 
And also lots of our players have errors with missing maps. Most of updated are changing map files.

**Comment by kisak-valve** [comment]
Hello @hitmany,
CS:GO issues are not tracked in this issue tracker. I've passed this on to the CS:GO team, and there most likely won't be any updates reported here.
