### ISSUE TITLE
Problems with nvidia 6800GT and HALF LIFE 2 on linux steam...

### ISSUE THREAD

**Issue by HarlockTheSin** [ValveSoftware/Source-1-Games#1787]
Hi guys,
I got a 6800GT mounted on a nforce4 chipset (asus A8N-SLI Deluxe). 3500 AMD 64 winchester 3gb RAM dual channel.
Running KUBUNTU 14.04.

I installed HL2 via steam and did get the error:
Could not find required OpenGL entry point 'glColorMaskIndexedEXT'! Either your video card is unsupported, or your OpenGL driver needs to be updated.

I used Fibbles work around (https://github.com/ValveSoftware/Source-1-Games/issues/32) and the game finally booted, all ok till the main screen but when I start new game I see artifacts and is not possible to play, I see messed poligons everywhere and I'm moving bling, I don't want to play like this.

What maybe the cause just overheating of the card?

How can I fix it?

I need only to fix the artifacts, the game goes and at a decent speed aswell.

Regards

**Comment by kisak-valve** [comment]
Closing per @Tele42's comment.
