### ISSUE TITLE
[TF2] cart sound stuck, loud, everywhere, until disconnect

### ISSUE THREAD

**Issue by volca02** [ValveSoftware/Source-1-Games#1791]
Hey,

on linux (didn't test on windows) the Hightower map (don't know if any other does this) sometimes causes the sound of the pushed cart to be heared constantly, very loudly, masking all other noises, where ever my character is standing (does not change the sound position or intensity). Nothing seems to help except disconnecting, which resets the sound to normal.

**Comment by YoshiRulz** [comment]
Temporary fix - use the console command `stopsound`. The command is self-explanatory.

**Comment by agrastiOs** [comment]
@kisak-valve this should get the audio label.

**Comment by kisak-valve** [comment]
Closing pending feedback.
