### ISSUE TITLE
[TF2][Linux] startmovie "filename" webm produces an unreadable file

### ISSUE THREAD

**Issue by Soapsuds** [ValveSoftware/Source-1-Games#1795]
Trying to record a video off of a demo with webm and the result cannot be played and ffmpeg -i complained about invalid data.
http://pastebin.com/G6LX7dcd system information.

**Comment by kisak-valve** [comment]
Hello @Soapsuds, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
