### ISSUE TITLE
[TF2] (linux) Killstreak are not counted if loadout is to be changed on next respawn

### ISSUE THREAD

**Issue by Gnurfos** [ValveSoftware/Source-1-Games#1796]
If you switch loadouts from X to Y, and the change does not occur immediately (because you are out of respawn zone, or victim of bug #1667), you will continue playing with loadout X until next death.

However, during that time, killstreak for weapons being used (from loadout X) do not count (or at least are not displayed).

**Comment by micwoj92** [comment]
This issue no longer exists
In demonstration I just recorded you can see that I changed loadout, but the kill was still counted to shotgun from previous loadout.
https://www.youtube.com/watch?v=yEDGqnt890c

**Comment by kisak-valve** [comment]
Thanks @micwoj92, closing per the last comment.
