### ISSUE TITLE
[TF2] SRCDS Freezes/Crashes on Map Change frequently.

### ISSUE THREAD

**Issue by StrikerMan780** [ValveSoftware/Source-1-Games#1802]
SRCDS seems to freeze and/or crash frequently on Map change after recent updates for TF2. I'm currently running Windows Server 2012.

Here's a minidump: https://shadowmavericks.com/files/CrashDumps/srcds_140817_233410.zip

Version Info:
Build Label:           2359471   # Uniquely identifies each build
Network PatchVersion:  2359471   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version

As far as the console for the server is concerned, there's nothing out of the ordinary that shows up, and there is no crash/error dialog box... nothing.

**Comment by kisak-valve** [comment]
Hello @StrikerMan780, if you are still experiencing this issue, please open a new issue report.
