### ISSUE TITLE
Pressing ctrl and space simultaneously minimizes Source-based games

### ISSUE THREAD

**Issue by MattiasEkstrom** [ValveSoftware/Source-1-Games#1803]
Running lubuntu 14.04, i.e. using lxde which in turn includes open box. 

However, this only happens in source games (hl2, cs:s) and not with any other application.

**Comment by kisak-valve** [comment]
Hello @MattiasEkstrom, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
