### ISSUE TITLE
[Linux] [TF2] Really low fps in MvM 

### ISSUE THREAD

**Issue by Luupuc** [ValveSoftware/Source-1-Games#1806]
Basically, the framerate is unplayably low in MvM game mode. With the same graphics settings, I get a good framerate on other game modes.

I'm running the game on latest Ubuntu with Nvidia GTX 460 graphics card with Nvidia proprietary drivers version 331.38.

EDIT: As I wrote below, it seems that disabling HDR solved the problem for me.

**Comment by kisak-valve** [comment]
Possible duplicate of #23.

**Comment by kisak-valve** [comment]
Closing as outdated.
