### ISSUE TITLE
TF2 freezes spontaneously

### ISSUE THREAD

**Issue by deterenkelt** [ValveSoftware/Source-1-Games#1809]
One day I can play two-three maps of king of the hill flawlessly, the other freezes occur each 2–3 minutes and last around 15 seconds. Screen freezes and the last bits of sound repeat. The time while the game freezes doesn’t depend on window’s focus. 

This happens immediately when the video settings are set to high, lowering them helps, but I couldn’t figure out which ones allow to play maps well (at least for some time). So I presume the problem is in the memory TF2 allocates. The freezes are rare on the maps when you hear developers’ commentaries.

Gentoo x86_64, i3, nvidia-drivers-340.17, GeForce GTX 550 Ti.

**Comment by kisak-valve** [comment]
Hello @deterenkelt, are you still experiencing this issue with an up to date system?

**Comment by deterenkelt** [comment]
Can’t say, I’ve deleted TF long ago.

**Comment by kisak-valve** [comment]
Thanks for the feedback @deterenkelt, closing.
