### ISSUE TITLE
[DOD:S] Custom player models don't work online anymore

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#1814]
Hi.
I noticed that custom player models don't work online on most servers like they used to before the steam pipe update. It's really sad that I am not able to play with for example british player models online. Basically whenever I join a server - the player models are invisible.
I would really like to ask if you could fix it so I could play online with my favourite player models.

**Comment by micwoj92** [comment]
This depends on server that  you play on, not game issue.

**Comment by kisak-valve** [comment]
Closing due to the last comment and because the reporting user has turned into a ghost.
