### ISSUE TITLE
After update clickable area of button inside all menus of TF2 are misaligned

### ISSUE THREAD

**Issue by aleksandaratanasov** [ValveSoftware/Source-1-Games#1815]
ISSUE
Clickable area of all buttons inside TF2's menus are misaligned with approximately 10-15cm on the vertical axis of the screen

OS
Debian Wheezy 7.6 64 bit with Xfce

STEPS
    Clicking on buttons inside the main menu and everywhere else in TF2

RESULTS
    Nothing happens

EXPECTED
    Buttons to be clicked and actions to occur.

INVESTIGATION
    This happened after I updated my Steam client and TF2 today. I have discovered that the clickable area of all buttons is shifted on the vertical axis of the screen downwards with 10-15cm. For example inside the class selection menu classes are selectable if mousepointer is approx. 10-15cm below the images of each class and mouse button is clicked. Due to this misalignment buttons at the bottom of the screen (including Loadout) are not clickable since clickable area is out of the screen. Player is unable to change his/her loadout because of that. Using ENTER presses the button on focus e.g. inside the match intro menu Continue button is selected by default so player can actually start a game without a problem. All this applies also to the main menu, which makes quitting the game by pressing the Quit button impossible. Console or Alt+F4 are the only way to do that. Using other keys (1,2,3 ... for class eselction, 0 for Cancel) also work. I do believe this happened after I switched from external monitor with greater resolution to internal on notebook with much smaller resolution.

**Comment by kisak-valve** [comment]
Hello @aleksandaratanasov, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
