### ISSUE TITLE
[GIT HUB] [ALL GAMES][1000 open issue's]

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1816]
1000+ open issue's?  last issue reviewed   (Nov 27, 2013). Random label's on the issue's?

Yes some of these "issue's" are quackery but a fair amount are legit.

if you sell the game, you need to support the game, (HLDMS) For those that have
worked at Valve a long time its good to remember how Valve got to where they are now.
(It was the half-life series)

Maybe hire someone just to maintain the Valve titles bugs,updates, ect

It will be two years in a couple month's hldms beta.

**Comment by ElectricTriangle** [comment]
And on it goes... these bugs aren't just gonna go away.

**Comment by danielzdunich** [comment]
Valve would rather announce hardware instead of actually fixing their games and announcing games :(

**Comment by 1157** [comment]
Sales sells the first of anything, Service always sells the second.

**Comment by BreakinBenny** [comment]
I couldn't care any less about Steam on Linux, but Valve indeed needs to fix their shit.
