### ISSUE TITLE
TF2: severe UI bug can get the game stuck

### ISSUE THREAD

**Issue by Gnurfos** [ValveSoftware/Source-1-Games#1817]
How to reproduce:

Get in a game
Press escape, click items, click backpack
Inspect an item (stockpile crate in my reproducible case)
Press escape

At this point this returns to game, but there's something wrongly "stacked" in the background.
To "clean" this up and save you, you can hit escape again: you will be back directly to the inspection screen of the item, and allowed to quit it properly by clicking close.

If instead you press y to talk, the talk box will appear, but (for example):
Pressing i (attempting to write letter i) will open the "map info" screen (the one you usually get when pressing i when there is no chat box). And the close button on that screen won't be clickable.
The only thing to do at this point, as far as I know, is killing the TF2 process.

**Comment by hahagoni** [comment]
Said issue is not performable anymore

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by LoneEch** [comment]
Issue occurs again.  Was just softlocked from opening the map info page on accident.  Does the same problem as before, close button is unclickable.

**Comment by FindTheBorealis** [comment]
I reproduced the steps, and this doesn't seem to happen anymore, but old style crates can't be inspected anymore. I tested with inspecting cases, weapons, cosmetics, and killstreak kits.

**Comment by kisak-valve** [comment]
@LoneEch, can you double check if this is fixed for you as well?

**Comment by kisak-valve** [comment]
If this issue comes up again, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker. Closing.
