### ISSUE TITLE
TF2 wonn't start on linux (see details) while JACK adio server is being used for system sound

### ISSUE THREAD

**Issue by PolishProgrammer** [ValveSoftware/Source-1-Games#1820]
TF2 fails to run on Ubuntu 13.04 under gdm display manager, while the sound system is JACK
please tell me if i miss any details.

**Comment by kisak-valve** [comment]
Hello @PolishProgrammer, if you are still experiencing crashes related to this issue, please open a new issue report.

Team Fortress 2 uses SDL 2 for audio and will need support for JACK added.
