### ISSUE TITLE
Recent updates to Steam and or Source games require "force_s3tc_enable=true" env 

### ISSUE THREAD

**Issue by nickpelone** [ValveSoftware/Source-1-Games#1821]
I can confirm that this did not occur on or before 9/5/2014 (the last time I played Team Fortress 2) on this system.

TF2 loads, but with no textures (all black) and the following errors

Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"s

are thrown.

Adding "force_s3tc_enable=true" into the environment fixes this issue, and TF2 (and LF2D, I tested that too) launched normally.

System Info:
(Note: This is an Optimus system, and for games the system uses the nVidia card. It is a nVidia Geforce GT 650M with 2GB of VRAM, on nVidia driver 331.20. It uses bumblebee to access the discrete graphics card.)

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17 Qiana (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.2-031602-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2014-08-20

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xfd1
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                        34.4cm x 19.4cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  7879 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  185774 Mb
    Largest Free Hard Disk Block:  20312 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @nickpelone, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Thanks for the feedback @nickpelone. I'm going to close this issue as this appears to be a system issue and the s3tc patent is due to expire next year. After that this issue should naturally go away if it's still a problem.
