### ISSUE TITLE
DoD:Source crashes at random intervals in game (beginning 2014-09-12)

### ISSUE THREAD

**Issue by AdamColligan** [ValveSoftware/Source-1-Games#1822]
Symptom:
DoD:Source loads normally. But after a few minutes of playing (not a specific time as far as I can tell), the game freezes in place. A short clip (maybe a quarter of a second) of the last audio that played then repeats over and over on a loop. The process has to be killed manually with a QUIT or HUP signal for good measure. This is a new issue that just arose today.

I have included system info, kernel log, and output when game is run from terminal and crashes.

System --
OS: Ubuntu 14.10 (latest updates)
Kernel: 3.16.0-14-generic #20-Ubuntu SMP Sat Sep 6 23:46:49 UTC 2014 x86_64
Model: HP Envy x360
lspci: 
00:00.0 Host bridge: Intel Corporation Haswell-ULT DRAM Controller (rev 0b)
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
00:03.0 Audio device: Intel Corporation Haswell-ULT HD Audio Controller (rev 0b)
00:14.0 USB controller: Intel Corporation 8 Series USB xHCI HC (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series HECI #0 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series HD Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 1 (rev e4)
00:1c.1 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 2 (rev e4)
00:1c.2 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 3 (rev e4)
00:1c.3 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 4 (rev e4)
00:1d.0 USB controller: Intel Corporation 8 Series USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation 8 Series LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 8 Series SATA Controller 1 [AHCI mode](rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series SMBus Controller (rev 04)
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5227 PCI Express Card Reader (rev 01)
08:00.0 Network controller: Intel Corporation Wireless 7260 (rev 9b)
09:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)

Kernel log excerpt (from game start through crash end) --

Sep 12 19:11:20   kernel: [ 4443.221907] [drm:i915_gem_open] 
Sep 12 19:11:20   kernel: [ 4443.266851] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:21   kernel: [ 4444.169675] [drm:i915_gem_context_destroy_ioctl] HW context 1 destroyed
Sep 12 19:11:21   kernel: [ 4444.486704] [drm:i915_gem_open] 
Sep 12 19:11:21   kernel: [ 4444.550210] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:25   kernel: [ 4447.852792] [drm:drm_mode_getconnector] [CONNECTOR:14:?]
Sep 12 19:11:25   kernel: [ 4447.852796] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:14:eDP-1]
Sep 12 19:11:25   kernel: [ 4447.852800] [drm:intel_dp_detect] [CONNECTOR:14:eDP-1]
Sep 12 19:11:25   kernel: [ 4447.852804] [drm:_edp_panel_vdd_on] Turning eDP VDD on
Sep 12 19:11:25   kernel: [ 4447.852809] [drm:_edp_panel_vdd_on] PP_STATUS: 0x80000008 PP_CONTROL: 0xabcd000f
Sep 12 19:11:25   kernel: [ 4447.853257] [drm:intel_dp_probe_oui] Sink OUI: 00e04c
Sep 12 19:11:25   kernel: [ 4447.853695] [drm:intel_dp_probe_oui] Branch OUI: 00e04c
Sep 12 19:11:25   kernel: [ 4447.853708] [drm:drm_edid_to_eld] ELD: no CEA Extension found
Sep 12 19:11:25   kernel: [ 4447.853711] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:14:eDP-1] probed modes :
Sep 12 19:11:25   kernel: [ 4447.853715] [drm:drm_mode_debug_printmodeline] Modeline 15:"1920x1080" 60 141000 1920 1958 2018 2104 1080 1084 1090 1116 0x48 0x9
Sep 12 19:11:25   kernel: [ 4447.853717] [drm:drm_mode_debug_printmodeline] Modeline 16:"1920x1080" 40 94000 1920 1958 2018 2104 1080 1084 1090 1116 0x40 0x9
Sep 12 19:11:25   kernel: [ 4447.853720] [drm:drm_mode_getconnector] [CONNECTOR:14:?]
Sep 12 19:11:25   kernel: [ 4447.853840] [drm:drm_mode_getconnector] [CONNECTOR:23:?]
Sep 12 19:11:25   kernel: [ 4447.853841] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:23:HDMI-A-1]
Sep 12 19:11:25   kernel: [ 4447.853843] [drm:intel_hdmi_detect] [CONNECTOR:23:HDMI-A-1]
Sep 12 19:11:25   kernel: [ 4447.853998] [drm:gmbus_xfer] GMBUS [i915 gmbus dpb] NAK for addr: 0050 r(1)
Sep 12 19:11:25   kernel: [ 4447.854000] [drm:drm_do_probe_ddc_edid] drm: skipping non-existent adapter i915 gmbus dpb
Sep 12 19:11:25   kernel: [ 4447.854001] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:23:HDMI-A-1] disconnected
Sep 12 19:11:25   kernel: [ 4447.854536] [drm:i915_gem_open] 
Sep 12 19:11:25   kernel: [ 4447.868026] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:25   kernel: [ 4447.870209] [drm:i915_gem_context_destroy_ioctl] HW context 1 destroyed
Sep 12 19:11:25   kernel: [ 4447.924708] [drm:i915_gem_open] 
Sep 12 19:11:25   kernel: [ 4447.946258] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:25   kernel: [ 4447.948970] [drm:i915_gem_context_destroy_ioctl] HW context 1 destroyed
Sep 12 19:11:26   kernel: [ 4448.579670] [drm:drm_mode_getconnector] [CONNECTOR:14:?]
Sep 12 19:11:26   kernel: [ 4448.579674] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:14:eDP-1]
Sep 12 19:11:26   kernel: [ 4448.579679] [drm:intel_dp_detect] [CONNECTOR:14:eDP-1]
Sep 12 19:11:26   kernel: [ 4448.580134] [drm:intel_dp_probe_oui] Sink OUI: 00e04c
Sep 12 19:11:26   kernel: [ 4448.580578] [drm:intel_dp_probe_oui] Branch OUI: 00e04c
Sep 12 19:11:26   kernel: [ 4448.580592] [drm:drm_edid_to_eld] ELD: no CEA Extension found
Sep 12 19:11:26   kernel: [ 4448.580596] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:14:eDP-1] probed modes :
Sep 12 19:11:26   kernel: [ 4448.580600] [drm:drm_mode_debug_printmodeline] Modeline 15:"1920x1080" 60 141000 1920 1958 2018 2104 1080 1084 1090 1116 0x48 0x9
Sep 12 19:11:26   kernel: [ 4448.580603] [drm:drm_mode_debug_printmodeline] Modeline 16:"1920x1080" 40 94000 1920 1958 2018 2104 1080 1084 1090 1116 0x40 0x9
Sep 12 19:11:26   kernel: [ 4448.580608] [drm:drm_mode_getconnector] [CONNECTOR:14:?]
Sep 12 19:11:26   kernel: [ 4448.580722] [drm:drm_mode_getconnector] [CONNECTOR:23:?]
Sep 12 19:11:26   kernel: [ 4448.580724] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:23:HDMI-A-1]
Sep 12 19:11:26   kernel: [ 4448.580725] [drm:intel_hdmi_detect] [CONNECTOR:23:HDMI-A-1]
Sep 12 19:11:26   kernel: [ 4448.580885] [drm:gmbus_xfer] GMBUS [i915 gmbus dpb] NAK for addr: 0050 r(1)
Sep 12 19:11:26   kernel: [ 4448.580887] [drm:drm_do_probe_ddc_edid] drm: skipping non-existent adapter i915 gmbus dpb
Sep 12 19:11:26   kernel: [ 4448.580889] [drm:drm_helper_probe_single_connector_modes_merge_bits] [CONNECTOR:23:HDMI-A-1] disconnected
Sep 12 19:11:26   kernel: [ 4448.588821] [drm:i915_gem_open] 
Sep 12 19:11:26   kernel: [ 4448.608805] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:26   kernel: [ 4448.610146] [drm:i915_gem_context_destroy_ioctl] HW context 1 destroyed
Sep 12 19:11:26   kernel: [ 4448.615243] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:26   kernel: [ 4448.616241] [drm:i915_gem_context_destroy_ioctl] HW context 1 destroyed
Sep 12 19:11:26   kernel: [ 4448.618085] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:26   kernel: [ 4448.620586] [drm:i915_gem_context_destroy_ioctl] HW context 1 destroyed
Sep 12 19:11:26   kernel: [ 4448.623436] [drm:i915_gem_context_create_ioctl] HW context 1 created
Sep 12 19:11:28   kernel: [ 4450.860717] [drm:edp_panel_vdd_off_sync] Turning eDP VDD off
Sep 12 19:11:28   kernel: [ 4450.860725] [drm:edp_panel_vdd_off_sync] PP_STATUS: 0x80000008 PP_CONTROL: 0xabcd0007
Sep 12 19:11:30   kernel: [ 4452.776693] [drm:drm_mode_addfb] [FB:29]
Sep 12 19:11:30   kernel: [ 4452.813738] [drm:drm_mode_addfb] [FB:30]
Sep 12 19:11:30   kernel: [ 4452.848159] [drm:drm_mode_addfb] [FB:31]
Sep 12 19:11:30   kernel: [ 4452.962763] [drm:intel_crtc_cursor_set] cursor off
Sep 12 19:12:03   kernel: [ 4486.585896] [drm:intel_crtc_cursor_set] cursor off
Sep 12 19:12:06   kernel: [ 4489.118330] [drm:intel_crtc_cursor_set] cursor off
Sep 12 19:12:07   kernel: [ 4489.853781] [drm:intel_crtc_cursor_set] cursor off
Sep 12 19:12:18   kernel: [ 4501.277413] [drm:intel_crtc_cursor_set] cursor off
Sep 12 19:12:20   kernel: [ 4503.547509] [drm:drm_mode_addfb] [FB:32]
Sep 12 19:12:21   kernel: [ 4503.742630] [drm:intel_crtc_cursor_set] cursor off
Sep 12 19:12:23   kernel: [ 4506.336495] [drm:intel_crtc_cursor_set] cursor off
Sep 12 19:12:34   kernel: [ 4517.487796] [drm:intel_crtc_cursor_set] cursor off

Steam terminal log (different run of the game, from start through crash. I'm not convinced that the last error really coincides with the moment of the crash.) --

~$ steam steam://rungameid/300
Running Steam on ubuntu 14.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1409240101_client)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steamwebhelper)/version(20140828032355)
Installing breakpad exception handler for appid(steamwebhelper)/version(1409196235)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
[0912/183702:ERROR:nss_util.cc(1018)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(20140828032355)
Installing breakpad exception handler for appid(steamwebhelper)/version(1409196235)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1409240101)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Installing breakpad exception handler for appid(steam)/version(1409240101)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1409240101)
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
Installing breakpad exception handler for appid(steam)/version(1409240101)
Adding licenses for the following package(s): 0, 25, 49875, 50140, 50161
roaming config store loaded successfully - 505 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1409240101)
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/adam/.local/share/Steam/ubuntu12_32/steam" "steam://rungameid/300" "
ExecSteamURL: "steam://rungameid/300"
System startup time: 3.78 seconds
Running Steam on ubuntu 14.10 64-bit
STEAM_RUNTIME has been set by the user to: /home/adam/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/adam/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 66: 384x256, total string texture memory is 704.51 KB
Game update: AppID 300 "Day of Defeat: Source", ProcID 11720, IP 0.0.0.0:0

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11310): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
ERROR: ld.so: object '/home/adam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/adam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 11723 != 11722, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/adam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/adam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20140828032404)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Using breakpad crash handler
Setting breakpad minidump AppID = 300
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198071729414 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198071729414
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Did not detect any valid joysticks.
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
[0912/183710:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 8
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3100 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3100 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: YES

 ##### swap interval = 0     swap limit = 1 #####
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Loaded program cache file "glshaders.cfg", total keyvalues: 233, total successfully linked: 233
Precache: Took 11194 ms, Vertex 921, Pixel 764
server.so loaded for "Day of Defeat"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 40 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 40 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 3
maxplayers set to 32
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 3
Steam config directory: /home/adam/.local/share/Steam/SteamApps/common/Day of Defeat Source/platform/config
CClientSteamContext logged on = 1
Type teleport_countdown_screen of meta class teleport_countdown_screen undefined!
MetaClass missing for teleport_countdown_screen
Hud element 'CHudWeapon' doesn't have an entry 'HudWeapon' in scripts/HudLayout.res
Hud element 'CHudHDRDemo' doesn't have an entry 'HudHDRDemo' in scripts/HudLayout.res
Hud element 'CHudFilmDemo' doesn't have an entry 'HudHDRDemo' in scripts/HudLayout.res
Hud element 'CHUDAutoAim' doesn't have an entry 'HUDAutoAim' in scripts/HudLayout.res
Hud element 'CHudGeiger' doesn't have an entry 'HudGeiger' in scripts/HudLayout.res
Unknown command "cl_thirdperson"
Can't use cheat cvar cam_snapto in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_ideallag in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdelta in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdist in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistright in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistup in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_collision in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minpitch in multiplayer, unlGame update: AppID 300 "Day of Defeat: Source", ProcID 11725, IP 108.174.61.20:27015
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
ess the server has sv_cheats set to 1.
Can't use cheat cvar c_maxyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxdistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_mindistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthowidth in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthoheight in multiplayer, unless the server has sv_cheats set to 1.
Unknown command "sv_backspeed"
Not playing a local game.

Console initialized.
Can't use cheat cvar fog_start in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_end in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_startskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_endskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar r_farz in multiplayer, unless the server has sv_cheats set to 1.
m_face->glyph->bitmap.width is 0 for ch:32 DejaVu Sans
m_face->glyph->bitmap.width is 0 for ch:32 Verdana
m_face->glyph->bitmap.width is 0 for ch:32 Verdana
m_face->glyph->bitmap.width is 0 for ch:32 Verdana
Network: IP 127.0.1.1, mode MP, dedicated No, ports 27015 SV / 27005 CL
Connecting to 108.174.61.20:27015...
Connected to 108.174.61.20:27015

Day of Defeat: Source
Map: dod_orange_the_tower_v3__op
Players: 13 / 24
Build: 2234230
Server Number: 10

Attemped to precache unknown particle system "blood_impact_red_01"!
Attemped to precache unknown particle system "blood_impact_green_01"!
Attemped to precache unknown particle system "blood_impact_yellow_01"!
Attemped to precache unknown particle system "slime_splash_01"!
Attemped to precache unknown particle system "slime_splash_02"!
Attemped to precache unknown particle system "slime_splash_03"!
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 3
The server is using sv_pure 0.  (Enforcing consistency for select files only)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_skybox/lcvp_skybox.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_vehicles/b17_skybox32.mdl)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_dod_01_hdrrt)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_dod_01_hdrbk)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_dod_01_hdrlf)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_dod_01_hdrft)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_dod_01_hdrup)
Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/sky_dod_01_hdrdn)
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/bloomadd)
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/no_pixel_write)
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/lumcompare)
[DoD TMS] You will be kicked if your ping exceeds 250!
# Game_connected

Error reading weapon data Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
