### ISSUE TITLE
TF2 memory leak on OS X

### ISSUE THREAD

**Issue by LordHDL** [ValveSoftware/Source-1-Games#1828]
The OS X version of TF2 leaks a huge amount of memory.  The people I play with who use the Windows version claim it stabilizes around 800 MB - 1 GB of memory.  On OS X I regularly see it go above 2 GB.

Furthermore, it seems to hold a lot of memory after grabbing it, causing it to become inactive and then never using it again, often with over 3 GB of inactive memory.  This results in page outs very quickly even with 8 GB total memory, which causes the game to skip and pause often.

The October 1 update claims "Improved memory usage for Mac clients" but this leak still occurs.

![activity monitor](https://cloud.githubusercontent.com/assets/5182602/4359062/05b68162-426f-11e4-8038-d84b6cef9ab8.png)
![memory](https://cloud.githubusercontent.com/assets/5182602/4359064/0de9c5d8-426f-11e4-8e9f-13d13bbe4fba.png)

**Comment by kisak-valve** [comment]
Hello @LordHDL, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by hahagoni** [comment]
Said issue was fixed with the Tough Break update
>     Mac and Linux improvements (Windows Direct3D 9 players have these already)
>         Texture streaming now enabled
>             Reduced memory consumption by ~500 megs
>             Faster map loads!
>         Players on Mac can now select 'High' texture settings
>         Eliminated many cases of hitching when using painted weapons
>         Eliminated occasional hitching caused by usingmat_picmip 2 (or selecting low quality textures in Video Options ->Advanced)
>         Massively reduced memory consumption when using painted weapons
>         Improved particle system performance, boosting overall framerate, especially in particle-heavy situations.
>         Fixed two most common forms of framerate stuttering /hitching when using popular FPS configs
>         Added -default launch option to help players triage performance / stability problems.
>             When run with -default, the game will ignore most convar settings and run purely with default options
>             Upon exit, -default runs do not overwrite the player's config.cfg file. If a player wants to save the settings of a default run, they should execute host_writeconfig <filename> in the console.
>         Fixed 5 second stall when opening options menu
>         VR players: You must now pass -vr to launch options to play TF using VR
>         Fixed multiple cases of FPS stutter related to the sound system
