### ISSUE TITLE
Source games doesn't start via optirun with nvidia drivers

### ISSUE THREAD

**Issue by gudvinr** [ValveSoftware/Source-1-Games#1830]
I'm using Ubuntu 14.04 x86_64
CPU: Intel Core i3-3210M
Intel GPU: HD3k
Nvidia GPU: 520M

I'he installed nvidia-331-updates (331.38) drivers from official repository and installed bumblebee (3.2.1) with primus.

[System information from steam](https://gist.github.com/gudvinr/1cc281a7d3b8b6fa8c75)
[Steam starting log](https://gist.github.com/gudvinr/69838908137f10c4ca29) (Before launch any game)

And when I try to start any source-based game (L4D2 or CS:GO) with launch options
    vblank_mode=0 optirun -b primus %command%

nothing happens and I've got only some messages in console:

```
Game update: AppID 550 "Left 4 Dead 2", ProcID 9399, IP 0.0.0.0:0
ERROR: ld.so: object '/home/gudvin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gudvin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gudvin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.

malloc: unknown:0: assertion botched
free: called with unallocated block argument
last command: (null)
Aborting...Game removed: AppID 550 "Left 4 Dead 2", ProcID 9399
```

Also, there are no minidumps in /tmp/dumps

This thing happens only with source-based games as I noticed, because Killing Floor runs fine, for example.
Also, those games without optirun (on intel card) runs fine.

**Comment by kisak-valve** [comment]
Hello @gudvinr, this issue was caused by libdrm-intel1-2.4.56, which is known defective when used with optimus setups and is fixed upstream. If you are still experiencing this issue with an up to date system, please open a new issue report and we can investigate further.
