### ISSUE TITLE
[TF2] Double mouse sensitivity due to outdated libSDL2.so

### ISSUE THREAD

**Issue by forivall** [ValveSoftware/Source-1-Games#1834]
In order to match sensitivity (on raw mode) between linux and windows, my linux sensitivity must be roughly half of that on windows. This seems to be a farily minor issue, but it's exacerbated by steam cloud, which syncs the setting between the two platforms. This also might only be an issue for my distro (Arch Linux).

The current workaround is to disable steam cloud for TF2, and manually set the sensitivity lower (roughly 0.5) on linux

**Comment by forivall** [comment]
Can we get any info on which API you're using to get raw input on linux? I've recently been working on a linux keyboard driver and so I have some knowledge on how the HID subsystem works. hidraw? evdev? whatever SDL exposes? some raw source emitted by the display server?

**Comment by Kiwii** [comment]
I'm also experiencing this with raw_input enabled using a 2000 DPI mouse in TF2 on linux.
An in-game sensitivity of 0.7 results in 15cm per 360° while [mouse-sensitivity.com](http://www.mouse-sensitivity.com) says this should result in around 30cm/360°. It seems to be off by a factor of pretty much exactly 2 no matter how fast I move my mouse ingame. I'd be interested in what the exact factor is, though, to be able to get really consistent settings between different games. 

I very much doubt constant acceleration is to blame since I've disabled all acceleration in xorg.conf (via the method documented in the archlinux wiki) and a [browser-based DPI test](http://www.mouse-sensitivity.com/dpianalyzer.html) results in the correct 2K DPI for my mouse or at least as close as it gets considering human error with measuring distance on the mouse pad; definitely not off by a factor of two, though.

**Comment by Tele42** [comment]
We (the players) are currently waiting for libSDL2-2.0.4 to be published for widespread distribution of https://bugzilla.libsdl.org/show_bug.cgi?id=2963.

**Comment by forivall** [comment]
Thanks for that information @Tele42 -- When in doubt, it's probably X11's fault. :+1: :+1: :+1:

**Comment by ElectricTriangle** [comment]
Tele42: Nice catch! Should be able to make use of that version whenever it gets into my distro (native lib mode in Steam is handy).

**Comment by Kiwii** [comment]
Very nice find, @Tele42! Good thing this bug isn't actually in the game and good it's really multiplied by an exact factor of two so I can just double my in-game sensitivity setting once a fixed lib is distributed. I guess somebody should close this issue then?

**Comment by ElectricTriangle** [comment]
Unless you're using native lib mode in Steam you're reliant on their
provided versions of most libs. So until Valve ships an updated SDL with
Steam this bug is still very much relevant.

**Comment by FedeDP** [comment]
I solved this issue (in tf2) by overriding steam shipped's lib32-sdl2 with my distribution's one (archlinux), as pointed out here: https://www.reddit.com/r/linux_gaming/comments/3zggjn/csgo_mouse_sensitivity_on_linux/

**Comment by Kiwii** [comment]
@FedeDP So valve fixed it in CS:GO buy bundling a newer version of sdl but they still ship the old one in TF2... Makes me wonder why they don't have one version included in the steam runtime instead of a different one for each game...

**Comment by kisak-valve** [comment]
Closing as the steam runtime currently includes libSDL2-2.0.4.

**Comment by Kiwii** [comment]
This seems to be **not fixed** for TF2 as it apparently ships the older version in the game's install folder as _"steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0"_. I guess this file should be removed?

**Comment by kisak-valve** [comment]
Thanks for catching that @Kiwii, reopening.

**Comment by jason0597** [comment]
Yes, I have this issue as well with TF2, had to divide my normal sensitivity that I use on Windows by 2
Admittedly I use Arch Linux instead of the officially supported Ubuntu, but I don't think this is the reason why I have double the sensitivity

**Comment by Fracey** [comment]
Same problem with css. Also not sure if related but scrolling fast acts as mouse4 and mouse5.

**Comment by jolty1** [comment]
This issue is still not fixed for TF2. Copying newer libSDL2-2.0.so.0 from Csgo's bin directory into tf2's bin is a temporarily fix.

**Comment by catb0t** [comment]
@jolty1 forgive me if i'm wrong, but this won't pass the checksum for a given TF2 version, might not allow you to join Valve pure servers, and could even get you VAC banned if the server decides you have a weird library loaded

it will also be overwritten by Steam's "Verify integrity of game files" but this is less important

**Comment by Kiwii** [comment]
> This issue is still not fixed for TF2. Copying newer libSDL2-2.0.so.0 from Csgo's bin directory into tf2's bin is a temporarily fix.

You can also just delete it. There's no need for the file to be there at all, as SDL2 is included in the Steam runtime anyway.

> @jolty1 forgive me if i'm wrong, but this won't pass the checksum for a given TF2 version, might not allow you to join Valve pure servers, and could even get you VAC banned if the server decides you have a weird library loaded 

VAC doesn't work that way and sv_pure doesn't enforce the integrity of libraries. I've been playing with my system's version of SDL2 preloaded for hundreds of hours and it hasn't caused any issues.

**Comment by jolty1** [comment]
> > This issue is still not fixed for TF2. Copying newer libSDL2-2.0.so.0 from Csgo's bin directory into tf2's bin is a temporarily fix.
> 
> You can also just delete it. There's no need for the file to be there at all, as SDL2 is included in the Steam runtime anyway.
> 
> > @jolty1 forgive me if i'm wrong, but this won't pass the checksum for a given TF2 version, might not allow you to join Valve pure servers, and could even get you VAC banned if the server decides you have a weird library loaded
> 
> VAC doesn't work that way and sv_pure doesn't enforce the integrity of libraries. I've been playing with my system's version of SDL2 preloaded for hundreds of hours and it hasn't caused any issues.
> 
> Anyway, can somebody please ask the janitor to just delete the file from the depot? It's a 5 minutes fix, if it even takes that long to do it.

After looking into it more, I am just preloading the working library from steam runtimes directory.

The game should be immune to updates and integrity checks then.

Trvial, as it would be doing this anyway...

Simple Launch Option.
`
LD_PRELOAD="/home/YOUR-NAME/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libSDL2-2.0.so.0:$LD_PRELOAD" %command%`

**Comment by Kiwii** [comment]
I'm doing that for month with my system library (on Arch) and it hasn't caused any issues.

    LD_PRELOAD="/usr/\$LIB/libSDL2.so:$LD_PRELOAD" %command%

**Comment by catb0t** [comment]
@kiwii re: "VAC and sv_pure don't work that way" isn't their whole purpose is to determine if the client has unknown unauthorised symbols loaded, like you might find in a later vs older version of SDL2, or like you might find in MyWallHack.so?

**Comment by Kiwii** [comment]
@catb0t VAC doesn't look for unknown stuff, but rather has a blacklist of known cheats. Valve prioritizes having no false positives over catching every cheat.

**Comment by jolty1** [comment]
Hi valve still broken. Still having to preload a newer libSDL2.

**Comment by TheThunderGuyS** [comment]
Is there any chance that this will be fixed? This issue is older than one of my cousins and a 5 minute fix still hasn't been implemented.

**Comment by lucascoelho07** [comment]
Any news on this issue? It also affects GoldSrc games

**Comment by wantija** [comment]
Using the systems native sdl2 library results in the game crashing when starting up a match, anyone else having this issue? On Arch Linux using 2.26.2-1.

**Comment by felipsmartins** [comment]
new release (64bits) fixex the issue for me (Debian Linux 12)

**Comment by Tiagoquix** [comment]
@kisak-valve Here's a comment from Joshua confirming the fix:

https://github.com/ValveSoftware/Source-1-Games/issues/5666#issuecomment-2065649922

> [...] SDL got upgraded which fixed the fact that sensitivity was being double/half of what it should be before.

**Comment by kisak-valve** [comment]
Closing per the last comment.
