### ISSUE TITLE
TeamFortress 2, glGetError problems.

### ISSUE THREAD

**Issue by N1xx1** [ValveSoftware/Source-1-Games#1844]
So I have some problems with Steam on Linux.

When I run it it says "OpenGL GLX context is not using direct rendering, which may cause performance problems.", and when I run a game like Team Fortress it won't run with the error "Could not find required OpenGL entry point 'glGetError'! Either your video card is unsupported, or your OpenGL driver needs to be updated". However I can run WebGL on the browser or run minecraft without problems, hardware acceleration is fine and stuff like that.

I'm not using amd drivers (I have a ATI Mobility Radeon HD 5650) because they don't seem to work in my system (Ubuntu 14.10). I think I'm using vesa.

Any tips?

**Comment by kisak-valve** [comment]
Closing as this is a general system config issue. If you are still experiencing this issue @N1xx1, your best bet is to reach out to your distro's community for help.
