### ISSUE TITLE
TF2 doesn't remember video settings

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#1845]
https://gist.github.com/gutigen/95d467e70df5a676a4ea

Running pretty fresh and up to date Arch with Gnome 3.14.

Other games work just fine (have not tested source engine games though).

I've tried so far:
- reinstalling Steam
- reinstalling TF2
- removing whole Steam folder
- turning off cloud sync and removing all settings (from TF2 and Steam folders)

Each time I start the game again video settings are reverted to defaults. I have no startup commands at all (had -novid, but removing it makes no change, go figure), nor custom autoexec.cfg (I do, but the only thing I got there are network settings, though I've removed that file anyway for tests).

EDIT:

This never happened under Ubuntu (since TF2 for Linux beta) and under Windows.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
