### ISSUE TITLE
[TF2] [Linux] Corrupt (or all black) load screen, main menu, in game graphics after Nov. 7 update.

### ISSUE THREAD

**Issue by gmjck** [ValveSoftware/Source-1-Games#1849]
Had TF2 running fine on Mint 17 64-bit Cinnamon, Radeon HD 6890, Catalyst 14.9. Then immediately following the Nov. 7 update @ ~6PM EST, started encountering the following problem:

1) First time running TF2 after reboot, no startup Valve animation: black screen (but with sound). No load screen, just black. No menu, just black. Alt-tab out and shut down TF2.

2) Trying to run TF2 after that: black screen for Valve start animation. Black screen for load screen. Then, main menu visible, but flickering and with corrupted graphics. Can click on Servers button, brings up servers window but text all corrupt. With somewhat blind clicking can connect to server, but no buttons on MOTD screen, various graphical corruption on team/character selection and in-game play.

Above happens regardless of Steam Overlay or Windows vs. Full Screen configuration. Other Linux users reporting same problem. SPUF thread with links to screenshots (2nd post) at:

http://forums.steampowered.com/forums/showthread.php?t=3266806

**Comment by kisak-valve** [comment]
Closing per the last comment.
