### ISSUE TITLE
CS:S fails to launch

### ISSUE THREAD

**Issue by PRabahy** [ValveSoftware/Source-1-Games#1852]
I don't know if this bug is valid because I'm on Manjaro instead of Ubuntu, so feel free to close it if that's an issue.

I loaded CS:S using steam and click the play button. It quickly pops up "Preparing to launch...", but then closes with no error message. I would be nice if it gave me some sort of reason that the game did not launch.

Second, I figured out that the proper command line to run to launch CS:S is "steam steam://rungameid/240". When I run that I get "Running Steam on manjarolinux 0.8.11 64-bit
STEAM_RUNTIME is disabled by the user". I didn't do anything to intentionally disable STEAM_RUNTIME, but after a bit of googling I found that this is controlled by an environment variable. I set STEAM_RUNTIME to both 1 and 0 manually, but both ways still gave me the same "STEAM_RUNTIME is disabled by the user" error.

Finally, I set STEAM_RUNTIME to 1, restarted the steam client, and am now getting "Game update: AppID 240 "Counter-Strike: Source", ProcID 7948, IP 0.0.0.0:0
ERROR: ld.so: object '/home/prabahy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/prabahy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 7950 != 7949, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/prabahy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/prabahy/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Failed to load the launcher
Game removed: AppID 240 "Counter-Strike: Source", ProcID 7948 " when I try to launch CS:S.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
