### ISSUE TITLE
[dota 2] Alt-tab does not move to desktop and stops interaction with the game

### ISSUE THREAD

**Issue by EvanTheB** [ValveSoftware/Source-1-Games#1853]
I have just made a fresh install of ubuntu 14.10 with fglrx for ATI. Running Dota works great, but trying to alt-tab fails. It displays the normal alt tab menu with the options, but at that point becomes unresponsive. Some keyboard shortcuts still work in the game, but the mouse is ignored. It is impossible to swap windows or actually alt-tab, you are stuck with the list of applications that are running in the middle of the screen. I am forced to swap to a shell ctrl-alt-f1 and kill dota from there.
Thanks, keep it up valve!

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-23-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11600000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-08-20

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon R9 200 Series

```
Driver Version:  4.4.12968 Compatibility Profile Context 14.201.1006.1002
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6810
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC662 rev1

Memory:
    RAM:  7936 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  105982 Mb
    Largest Free Hard Disk Block:  37899 Mb

Installed software:

Recent Failure Reports:
    Tue Dec  9 14:54:27 2014 GMT: file ''/tmp/dumps/assert_20141210015219_78.dmp'', upload no: ''Couldn't connect to server''
    Tue Dec  9 21:07:44 2014 GMT: file ''/tmp/dumps/crash_20141210080734_5.dmp'', upload yes: ''CrashID=bp-271ba6a0-6230-4fea-b5af-9e3522141209''

**Comment by EvanTheB** [comment]
Sorry been busy. What is a DE?

**Comment by Tele42** [comment]
@EvanTheB DE is short for Desktop Environment, in your case it's gnome 3, other common choices are kde, xfce, mate, and cinnamon.

**Comment by kisak-valve** [comment]
Hello @EvanTheB, if you are still experiencing this issue with an up to date system, please open a new issue report in the Dota-2 issue tracker.
