### ISSUE TITLE
TF2 screen is black, only steam community thing shows up, no sound

### ISSUE THREAD

**Issue by OriginalAndCreativeName** [ValveSoftware/Source-1-Games#1856]
I can open tf2 but there is no sound, and there is just a black screen. I am running Ubuntu 14.10.
SPECS:
Intel i7 4770K
EVGA Nvidia Geforce GTX 770 SC
32 GB 2000 mhz ram.

**Comment by kisak-valve** [comment]
Hello @OriginalAndCreativeName, are you still experiencing this issue with an up to date system?

**Comment by OriginalAndCreativeName** [comment]
@kisak-valve No, the problem was related to some of my settings in the Nvidia Control Panel

**Comment by kisak-valve** [comment]
Thanks for the feedback @OriginalAndCreativeName, closing.
