### ISSUE TITLE
Counter-Strike Source Buy Menu displays, but won't allow selection

### ISSUE THREAD

**Issue by jeffthedrumguy** [ValveSoftware/Source-1-Games#1857]
Everything about the game plays fine, but when I go to the buy menu I am only able to either Autobuy, or to purchase weapons that in the "favorites" list.
If I use the numbers for different types of weapons, or if I click on the weapon options on the left then the game closes the buy menu and I'm returned to gameplay.

System Information follows:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0xf
    CPU Model:  0x6b
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 16 Petra (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.0-12-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2014-08-20

Video Card:
    Driver:  NVIDIA Corporation GeForce 7900 GS/PCIe/SSE2

```
Driver Version:  2.1.2 NVIDIA 304.88
OpenGL Version: 2.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x292
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 18.90" x 10.63"  (21.65" diag)
                                        48.0cm x 27.0cm  (55.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM Not Detected
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Nvidia MCP77/78 HDMI

Memory:
    RAM:  4961 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  933733 Mb
    Largest Free Hard Disk Block:  420064 Mb

Installed software:

Recent Failure Reports:
    Sun Dec 21 04:19:46 2014 GMT: file ''/tmp/dumps/assert_20141220231738_36.dmp'', upload no: ''Couldn't connect to server''

**Comment by kisak-valve** [comment]
Hello @jeffthedrumguy, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
