### ISSUE TITLE
HalfLife 2 and episodes not launching on Manjaro / Ubuntu 14.x

### ISSUE THREAD

**Issue by vincent-t** [ValveSoftware/Source-1-Games#1862]
When I try to launche one of these games I get this error on Ubuntu 14.04, Manjaro: `./hl2_linux Failed to load the launcher`. This affects Half Life 2 and Episodes. Please fix this bug!

```
hwinfo --short
cpu:                                                            
                       Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz, 1810 MHz
                       Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz, 1733 MHz
                       Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz, 1666 MHz
                       Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz, 1966 MHz
keyboard:
                       Microsoft® SiderWinderTM X4 Keyboard
mouse:
                       Logitech USB-PS/2 Optical Mouse
monitor:
                       Generic Monitor
graphics card:
                       nVidia VGA compatible controller
sound:
                       Intel 6 Series/C200 Series Chipset Family High Definition Audio Controller
                       nVidia Audio device
storage:
                       Intel 6 Series/C200 Series Chipset Family SATA AHCI Controller
                       JMicron JMB362 SATA Controller
network:
  eno1                 Intel 82579V Gigabit Network Connection
  enp0s26u1u3          Realtek USB WLAN
network interface:
  eno1                 Ethernet network interface
  lo                   Loopback network interface
  enp0s26u1u3          Ethernet network interface
disk:
  /dev/sda             SanDisk SDSSDX12
  /dev/sdb             WDC WD6400AAKS-0
  /dev/sdc             WD Ext HDD 1021
partition:
  /dev/sda1            Partition
  /dev/sda2            Partition
  /dev/sda3            Partition
  /dev/sda4            Partition
  /dev/sdb1            Partition
  /dev/sdc1            Partition
cdrom:
  /dev/sr0             HL-DT-ST DVDRAM GH22LS50
usb controller:
                       Intel 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2
                       Intel 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1
                       ASMedia ASM1042 SuperSpeed USB Host Controller
                       ASMedia ASM1042 SuperSpeed USB Host Controller
bios:
                       BIOS
bridge:
                       Intel 2nd Generation Core Processor Family DRAM Controller
                       Intel Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port
                       Intel 6 Series/C200 Series Chipset Family PCI Express Root Port 1
                       Intel 6 Series/C200 Series Chipset Family PCI Express Root Port 5
                       Intel 6 Series/C200 Series Chipset Family PCI Express Root Port 6
                       Intel 6 Series/C200 Series Chipset Family PCI Express Root Port 7
                       Intel Z68 Express Chipset Family LPC Controller
hub:
                       Linux 3.18.1-1-MANJARO xhci-hcd xHCI Host Controller
                       Linux 3.18.1-1-MANJARO ehci_hcd EHCI Host Controller
                       Hub
                       Linux 3.18.1-1-MANJARO xhci-hcd xHCI Host Controller
                       Linux 3.18.1-1-MANJARO xhci-hcd xHCI Host Controller
                       Linux 3.18.1-1-MANJARO ehci_hcd EHCI Host Controller
                       Hub
                       Linux 3.18.1-1-MANJARO xhci-hcd xHCI Host Controller
memory:
                       Main Memory
unknown:
                       FPU
                       DMA controller
                       PIC
                       Timer
                       Keyboard controller
                       Intel 6 Series/C200 Series Chipset Family MEI Controller #1
                       Intel 6 Series/C200 Series Chipset Family SMBus Controller
                       Microsoft® SiderWinderTM X4 Keyboard
```

**Comment by voidplayer** [comment]
I was having the same issue.

I fixed it "verifying integrity of game cache". There was some file missing or corrupted or something :)

**Comment by vincent-t** [comment]
I have tried this, still no success... :(

**Comment by voidplayer** [comment]
Well, the error is very generic. I guess some valve employee would have to step in pointing to a log with more info or something. In my case, it worked :)

**Comment by Tele42** [comment]
@vincent-t Please include your system information as requested at https://github.com/ValveSoftware/Source-1-Games#reporting-issues, also you may find hints if you launch steam from a terminal.

**Comment by vincent-t** [comment]
**System information:**
**1. Distro:** Manjaro Linux
**2. Desktop/Window Manager:** XFCE
**3. Graphics card:** NVIDIA GTX 660, 343.36 Driver
**Only output in terminal when launching game:**
`Installing breakpad exception handler for appid(steam)/version(1422054110)
Game update: AppID 420 "Half-Life 2: Episode Two", ProcID 28463, IP 0.0.0.0:0
ERROR: ld.so: object '/home/vincent/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vincent/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 28465 != 28464, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/vincent/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vincent/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Failed to load the launcher
Game removed: AppID 420 "Half-Life 2: Episode Two", ProcID 28463`

**Comment by RobinJ1995** [comment]
Can confirm on Arch Linux. Same problem.

```
ERROR: ld.so: object '/home/robin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6575 != 6574, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/robin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/robin/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Failed to load the launcher
```

Arch Linux
core/linux 3.19.2-1
extra/nvidia 346.47-10

**Comment by fraxbe** [comment]
I have the same issue on 
Debian Unstable
Kernel: 
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux
Driver:
xserver-xorg-video-nvidia                                   340.65-2

**Comment by rick9791** [comment]
same issue here...

XUbuntu 15.10 Wily
XFCE
NVIDIA GeForce 9500GT
NVIDIA driver version: 340.96

**Comment by BangL** [comment]
same problem here.
portal games and mods are running fine. but the hl2 versions are broken.

could it be a problem with missing 32bit libs on 64bit systems?
i am running latest manjaro as 64bit version.

**Comment by BangL** [comment]
console output of hl2.sh on manjaro x64: http://pastebin.com/guEgKDm0

**Comment by Tele42** [comment]
Running a game like this may give inconsistent results because the steam runtime is not involved. Can you try to run the run.sh in the steam runtime folder followed by hl2.sh (same command). If that does not reveal anything interesting, run the steam runtime run.sh with ldd vguimatsurface.so and see if there are unresolved dependencies.

**Comment by BangL** [comment]
yep.. that actually fixes it completely for me.
starting the game like this now:
cd ~/.steam/steam/ubuntu12_32/steam-runtime && ./run.sh ../../steamapps/common/Half-Life\ 2/hl2.sh

thanks

**Comment by kisak-valve** [comment]
Closing as running steam games from outside the steam runtime is not supportable. Your mileage may vary.

**Comment by etasnadi** [comment]
> yep.. that actually fixes it completely for me. starting the game like this now: cd ~/.steam/steam/ubuntu12_32/steam-runtime && ./run.sh ../../steamapps/common/Half-Life\ 2/hl2.sh
> 
> thanks

This solves the problem, thanks.
