### ISSUE TITLE
Wrong Elf.

### ISSUE THREAD

**Issue by Hairyloon** [ValveSoftware/Source-1-Games#1867]
I have been having some problems with Counter Strike crashing, I have been getting this error message:

ERROR: ld.so: object '/home/loon/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
the
I've been to Steam support, but because I'm running Mint 17, which they don't support, they have pointed me here...

**Comment by Tele42** [comment]
This is normal and expected, when steam launches a game, it tries to use the 64 bit and 32 bit overlay library, one loads in, the other throws a harmless error. Please add your system information as requested at https://github.com/ValveSoftware/Source-1-Games#system-information.

**Comment by Hairyloon** [comment]
Sorry, here you go:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0xb
    CPU Type:  0x0
    Speed:  2404 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux Mint 17 Qiana (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RV770

    Driver Version:  3.0 Mesa 10.1.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x9440
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1024 x 768
    Desktop Resolution: 1024 x 768
    Primary Display Size: 10.63" x 7.99"  (13.27" diag)
                                            27.0cm x 20.3cm  (33.7cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Realtek ALC882
    
Memory:
    RAM:  5968 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  118080 Mb
    Largest Free Hard Disk Block:  90748 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by Hairyloon** [comment]
Actually, the elf was giving trouble on the other machine, this one is giving me:

"process 3075: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library."

**Comment by Hairyloon** [comment]
This is the Sys-info for the machine which keeps crashing:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0xf
    CPU Model:  0x6b
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2300 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux Mint 17 Qiana (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation Quadro NVS 290/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 340.46
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x42f
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1024 x 768
    Desktop Resolution: 1024 x 768
    Primary Display Size: 11.97" x 8.98"  (14.96" diag)
                                            30.4cm x 22.8cm  (38.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 256 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC662 rev1
    
Memory:
    RAM:  2001 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  298373 Mb
    Largest Free Hard Disk Block:  243833 Mb
    
Installed software:
    
Recent Failure Reports:
    Tue Jan 27 19:30:29 2015 GMT: file ''/tmp/dumps/assert_20150127193012_19.dmp'', upload yes: ''CrashID=bp-684d6a51-58b6-4944-9ba6-f3a602150127''
    Tue Jan 27 21:07:29 2015 GMT: file ''/tmp/dumps/crash_20150127201013_1.dmp'', upload yes: ''CrashID=bp-688afa1d-fe4b-4cb5-b8dc-93dc12150127''

**Comment by Tele42** [comment]
I have a laptop with a Quadro NVS 320M, which also has 256MB of vram, for me, the source engine is sensitive to overallocation of vram, and I was able to get reasonable reliability and performance once I got the settings low enough that it did not hit the max vram, you can watch your vram usage via the command line option nvidia-smi or the gui tool nvidia-settings. I recommend using `watch nvidia-smi` via ssh.

Good luck, hope this helps.

Note: I do not own CS:S or CS:GO, this is a generalization of some other source games.

**Comment by kisak-valve** [comment]
Hello @Hairyloon, are you still experiencing this issue with an up to date system? Did lowering your video settings help?

**Comment by Hairyloon** [comment]
That's a good question.  I loaned that machine to a friend, so the problem went away on that front...
I'll let you know when I get that machine back. [😉]


Thank you for asking.


________________________________

**Comment by kisak-valve** [comment]
Closing pending feedback.
