### ISSUE TITLE
[L4D2] Disabling multicore rendering setting is not persistent

### ISSUE THREAD

**Issue by lecbee** [ValveSoftware/Source-1-Games#1874]
For a reason I will explain below, I need to disable the L4D2 multicore rendering setting on my system. But this graphical setting, contrary to the others, is not persistent. So each time I launch the game I need to go to the setting and re-disable it. Could you please fix it (if it's a bug) or implement this feature (if it's not a bug) ?

Why I need to do this ?
Because I have a AMD Radeon HD5850 video card and it seems there is a bug somewhere (hardware ? driver ? game engine ? I don't know) which leads *sometimes* (but too often...) to a darker and darker screen when playing. At start, all looks fine, and step by step the contrast of the screen is coming darker and darker. Finally it's nearly completely black !

I had the same problem also with a Radeon HD4850. I'm currently using Fedora 21 with Mesa driver built regularly from git. That's a behavior already described on the Web [1] [2] with AMD hardware in L4D2 (even with fglrx). And I found somewhere the fix to disable the multicore rendering and indeed have no more problem since I do this.

[1] http://forums.steampowered.com/forums/archive/index.php/t-2267935.html
[2] http://forums.steampowered.com/forums/archive/index.php/t-1751957.html

**Comment by jwcalla** [comment]
There was another bug report about this and it was mentioned that it wouldn't be fixed, therefore you have to set this launch option for the game to force multicore rendering disabled:  "+mat_queue_mode 0".  You can set launch options in the game properties.

**Comment by lecbee** [comment]
Thank you for the tip! It works.
