### ISSUE TITLE
[TF2] Characters do not speak after the button is pressed "ready" in MVM

### ISSUE THREAD

**Issue by Manazius** [ValveSoftware/Source-1-Games#1875]
After today's (3/12/2015) update TF2 characters in MVM stopped talking after pressing the "ready".
This happens on all servers (which I was) and all the characters.
Video (if you need): http://www.youtube.com/watch?v=GSrk33qPA_8&feature=youtu.be
I look forward to a fix. Thank you!

**Comment by ElectricTriangle** [comment]
That's because someone removed them from the vpk files, I checked... they're just gone (the sound directory was updated with the new taunts, someone goofed).

in the console: Failed to load sound "vo/soldier_mvm_ask_ready02.wav", file probably missing from disk/repository

**Comment by Yttrium-tYcLief** [comment]
This bug was cross-platform and was fixed, at least on Windows, in the [March 18, 2015](https://wiki.teamfortress.com/wiki/March_18,_2015_Patch) patch. Please close it if this bug has been fixed for you, or reply to this comment if it hasn't been.
