### ISSUE TITLE
steam cmd for linux arm processor

### ISSUE THREAD

**Issue by bmorello** [ValveSoftware/Source-1-Games#1878]
I bought the $35 raspberry pi 2 and it's equivilent to what a quad core pentium 3 600-700mhz but only uses a maximum of 10 watts of power. It handles a loaded quake(1,2,3,4,live etc) server very well.... the thing is that no one plays it.

I was wondering if you guys would be willing to try and compile the steam cmd and Half-Life - counterstrike/TF2 server to a linux ARM binary? I think it would end up being better than using qemu.

**Comment by NothingMuchHereToSay** [comment]
It won't be likely unless Ubuntu "superphones" with extremely high-end hardware with ARM processors have a hardware translation layer for ancient x86 games that might never be ported over, or if SteamOS is on a portable console, like maybe the Dragonbox Pyra or Nvidia Shield. I dunno.

**Comment by bmorello** [comment]
I think halflife 2 was ported to android arm processor, so i figured id ask..... The device i mentioned is well neat to say the least.

**Comment by Tele42** [comment]
Nvidia did the port for the Shield, not valve, and that's just the single player game mode.

**Comment by kisak-valve** [comment]
Closing as this request is outside the scope of this issue tracker.
