### ISSUE TITLE
Weird graphical effect visible in class selector.

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/Source-1-Games#188]
This has happened a few times, I’ve died and one of the character models on the loadout screen has a corrupted texture.
I think it may be related to what class a spy is currently using - as it has sometimes been on my Heavy model when I know one of the enemies spy is me… but i’m not sure - its hard to reproduce.

http://steamcommunity.com/sharedfiles/filedetails/?id=129898778
http://steamcommunity.com/sharedfiles/filedetails/?id=129898897

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-18-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11203000
    X Window Manager:  Metacity
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xf00
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ID 662

Memory:
    RAM:  16050 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  295295 Mb
    Largest Free Hard Disk Block:  15021 Mb

Recent Failure Reports:
    Tue Feb 26 12:33:57 2013 GMT: file ''/tmp/dumps/assert_20130226123314_1.dmp'', upload yes: ''CrashID=bp-14cfe828-570c-4ae0-938e-702062130226''
    Tue Feb 26 16:14:47 2013 GMT: file ''/tmp/dumps/assert_20130226161414_1.dmp'', upload yes: ''CrashID=bp-acf24534-66e4-406c-8012-118b12130226''
    Wed Feb 27 22:01:19 2013 GMT: file ''/tmp/dumps/assert_20130227220044_1.dmp'', upload yes: ''CrashID=bp-19ee9db8-7485-4dcf-a52d-c951a2130227''

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If anyone is still experiencing this issue, please open a new issue report.
