### ISSUE TITLE
Can't launch TF2

### ISSUE THREAD

**Issue by Awesomepizzaman5** [ValveSoftware/Source-1-Games#1885]
I installed Ubuntu 14.04 LTS 2 days ago, and every since then I have not been able to launch TF2. Whenever I click play, it opens up the message "Preparing to launch Team Fortress 2" for around 1 second, then closes and nothing happens. I've tried a lot of things like verifying integrity of game cache, reinstalling TF2, restarting my PC, deleting appcache. I'm a total Linux noob so if anyone can help me, I would really appreciate it.

**Comment by s0r00t** [comment]
Run steam in a terminal, and look at the output.
Can you put the whole output on Pastebin? I'll take a look.

**Comment by kisak-valve** [comment]
Closing pending feedback.
