### ISSUE TITLE
[TF2] [SDK] [Feature Request] Move insertion of default cubemaps embedded by VBSP to a compile argument

### ISSUE THREAD

**Issue by worMatty** [ValveSoftware/Source-1-Games#1888]
Greetings.

At present when compiling a map in TF2's Hammer, VBSP will insert a pair of black cubemaps named cubemapdefault.vtf and cubemapdefault.hdr.vtf in to the finished BSP, as well as a black cubemap for each env_cubemap entity in the map (including an HDR variant, even when a map is not compiled in HDR).

This is convenient when creating a work-in-progress version of a map that needs to be tested, free of the annoyance of hideous reflections. However, authors who wish to publish a detailed version of their map must endure an irritating, confusing and risky procedure to get proper cubemaps:

These cubemaps cannot be overwritten in the BSP by the game's buildcubemaps command. Mappers that wish to publish the finished version of their work must use an editor like Pakrat or VIDE to remove the cubemap files and save the BSP before they are able to build their own. This process also risks breaking the BSP.

I propose introducing a compile argument to VBSP to control the insertion of these cubemaps. We could use it on Fast and Default compile presets in Hammer, and leave it out for our Final compiles.

Thanks for your time.

**Comment by 1157** [comment]
I second the motion.

**Comment by kisak-valve** [comment]
Hello @worMatty, is this still an issue since the [2016-02-04 source sdk 2013](http://store.steampowered.com/news/20296/) update?

**Comment by 1157** [comment]
I can't say about Tf2 but Hldms still has this problem here is a map from 2 weeks ago i compiled
I have not used env_cubemaps on levels sine 2013, the workaround fix is hackish and breaks map packs sometimes.
![cubemaps_default](https://cloud.githubusercontent.com/assets/5712715/21574603/d31107d0-cec3-11e6-89d3-f5306e7166eb.png)

**Comment by kisak-valve** [comment]
Thanks for the feedback @1157.

**Comment by worMatty** [comment]
Howdy.

Yes, this issue seems to have been fixed, in TF2. Default cubemaps are now overwritten when building cubemaps in the game.

Not long after I reported this issue I discovered that BSPZIP has an argument to remove cubemaps from a BSP. Mappers could add in a step to the compile process to remove them before the BSP is copied to the game's map folder.

`bspzip -deletecubemaps <bspfile>`

Note that this removes all VTF files from the pak, so if you have any custom compile steps that pack custom content, make sure you perform those after this.

**Comment by kisak-valve** [comment]
Thanks for the feedback @worMatty. Because the original issue has been resolved, I'm going to close this issue report.

@1157, if you wish to pursue this further for HLDM:S, please open a new issue report in the source-sdk-2013 issue tracker.
