### ISSUE TITLE
Dear Valve, Publicly admit you canned this Steampipe update project

### ISSUE THREAD

**Issue by Theuaredead** [ValveSoftware/Source-1-Games#1890]
as you can see, tons of users here are reporting errors for various games for the past nearly 2 years with no response.

Now, none of these users know that you guys canned this project, and I feel as if you need to tell the public that you guys did. It is unfair for these users to report bugs that wont ever be fixed with false hope that they will be fixed. To make it worse, not fixing these bugs are much worse.

**Comment by TheObscure** [comment]
This would be great to prevent people to spend a full day on finding bugs and typing them in a nicely compiled report. 

I wish this were here sooner. :(

**Comment by Redeemer6666** [comment]
Yeah this takes this piss, is there perhaps a more "official" way we can get this dealt with. Posting shit here never seems to help and I feel utterly conned by Valve, I'm beginning to believe that storming their offices brandishing a rusty crowbar may in fact be the only course of action left open to me. Don't worry friends, I'll list HL3 as part of my hostage demands XD

**Comment by Redeemer6666** [comment]
@TheObscure And as far as I'm concerned your a Legend. Seems you've paid way more love to HLS than Valve. Playing that truly broken game to write that comprehensive bug list you posted must have been painful. I salute you sir, one of us had to do it and i'm sure as shit glad it wasn't me, So thanks.

**Comment by Theuaredead** [comment]
@Redeemer6666 It isn't the fact the GitHub didn't work, it's the fact Valve canned the project. Plus, @TheObscure 's list is actually full of bugs that became a thing with these updates (imagine breaking your game more than fixing them)

**Comment by Redeemer6666** [comment]
@Theuaredead Tbh I've lost all respect of Valve over this, Like you said they should at least tell us we're all screwed and that we'll never see functioning versions of the games we PAID for. What annoys me is that with a decent SDK for HLS the community could fix the SP aspect at least.

**Comment by TheObscure** [comment]
@Redeemer6666 Thanks for appreciating the list I made. And yeah well if you grew up playing Half-Life, you will always go back playing it no matter what. And for me nostalgia is a big thing and that makes me love the game even more. So when I saw that they made a Source version of it I was very excited until I played it myself not too long ago and I was very disappointed. Then the steampipe update came and killed the game even more to where it is now. So I felt that compiling a list like that might save the game, but now upon discovering that Valve is not using this site for bug reports anymore, I am really pissed.

I guess they think that we can have Black Mesa instead, and use that as an excuse to not fix HLS and HLDMS for us. Overall they are making much more money off of their cut from BM, so why should they care about this game. Then they have CSGO and other successful games so I don't see them ever returning here to fix their shit. Sad but true.

**Comment by ATrustedFriendInScience** [comment]
Source 1 is over 10 years old guys, frankly you can't even get a licence for it anymore.

I don't know why you mentioning Steampipe since it was just a better way Digital Download the games.

It isn't that they are not using GitHub, its that they are no longer supporting their older games.

**Comment by Theuaredead** [comment]
@ATrustedFriendInScience These updates were apart of the Steampipe update. They canceled the updates to Source that came with the Steampipe project. CSGO, Dota 2, and TF2 still get updated, Dota 2 is being ported to Source 2, while CSGO and TF2 are not.

**Comment by 1157** [comment]
HLDMS worked just fine on the 2006 ep1 engine, until this 2013MP/Steampipe update. Its not a question of supporting older games, It's fixing what was broke in the update.

Its as simple as this: If you sell it you support it.

**Comment by eNTi** [comment]
this is discouraging...
