### ISSUE TITLE
 [TF2] Server crash on quit, exit and _restart command

### ISSUE THREAD

**Issue by fukkisi** [ValveSoftware/Source-1-Games#1894]
If you run quit, _restart or exit it does not exit cleany. It just sits there with 2 errors. 
It used to exit cleanly prior to the last update. We've been restarting our servers every morning at 6 for about ~1.5 years. 

There are more people experiencing this problem. They did not have this prior to the latest update. Its been spoken about on the hlds_linux mailing list and people made a thread on [alliedmodders] (https://forums.alliedmods.net/showthread.php?t=264275) looking for a solution.

r_message: "quit"
L 06/12/2015 - 19:48:28: Log file closed.
L 06/12/2015 - 19:48:28: server_message: "restart"
[MessageBot] Please wait until Thread is finished...
L 06/12/2015 - 19:48:29: Log file closed.
L 06/12/2015 - 19:48:29: Error log file session closed.

/home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/fileio.
cpp (3997) : Assertion Failed: CFileWriterThread: pending file writer content_log
.txt
Assert( Assertion Failed: CFileWriterThread: pending file writer content_log.txt 
):/home/buildbot/buildslave/steam_rel_client_linux/build/src/tier1/../tier1/filei
o.cpp:3997

assert_20150612194830_18.dmp[1764]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150612194830_18.dmp
Bad thread local/home/buildbot/buildslave/steam_rel_client_linux/build/src/tier0/
threadtools.cpp (1416) : Assertion Failed: Thread synchronization object is unuse
able
Bad thread localassert_20150612194830_18.dmp[1764]: Finished uploading minidump (
out-of-process): success = no
assert_20150612194830_18.dmp[1764]: error: Failed sending data to the peer
assert_20150612194830_18.dmp[1764]: file ''/tmp/dumps/assert_20150612194830_18.dm
p'', upload no: ''Failed sending data to the peer''

Distro : Linux Aranea 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u2 x86_64
Desktop/Window Manager : Screen

**Comment by 1157** [comment]
https://github.com/ValveSoftware/Source-1-Games/issues/1823

**Comment by fukkisi** [comment]
@1157 Updates this problem. Was in a hurry when i made it. It does not just happen with quit, it also does with _restart or exit. I'd hoped someone on here might knew a solution.

**Comment by 1157** [comment]
I see what you mean now, I looks like its trying to write a log file and it can't.
hlds_linux mailing list will get it fixed.

**Comment by powerlord** [comment]
This was fixed in the last update, so you might want to close this bug.

**Comment by fukkisi** [comment]
Yes you are 100% right. Forgot to close it.
