### ISSUE TITLE
[HL1: Source] No sound when shotgun is shot

### ISSUE THREAD

**Issue by ossorio** [ValveSoftware/Source-1-Games#1895]
There is a problem in HL1: Source (which I bought from Steam) : The shots fired with the shotgun don't produce any sound, excepting the sound of the objects hit by the bullets. The reload sound is ok, too.

I have noted this bug in chapter 4: Office Complex.

**Comment by 1157** [comment]
Sounds like the game is missing a sound file.On your lower steam icon, right click on it and go to
library, Select Half-life:Source right click on"Half-life:Source" and and go to properties and under local files 
select "verify integrity of game cache" let it check your files and if should pick up the missing file.

**Comment by ossorio** [comment]
I have tried verifying the integrity of game cache, and it does not work.
Moreover, I have discovered that the sound issue only occurs with the HD content loaded. Without HD content (like the original Half-Life) the sound works ok. 
And now I have noted a disfunction with the pistol reloading sound which had been unnoticed to me.

**Comment by 1157** [comment]
save your "saves" and reload the game, I had to re-load once already, with some weird issues.

**Comment by kisak-valve** [comment]
Hello @ossorio, if you are still experiencing this issue, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Closing pending feedback.
