### ISSUE TITLE
Half life 2 weapon glitch

### ISSUE THREAD

**Issue by IskU0os** [ValveSoftware/Source-1-Games#1899]
When i play halfe life 2, and try to shoot (left click) it imediately changes to gravity gun. Please help me :(

**Comment by 1157** [comment]
From start screen go to >options>keyboard>primary weapon and secondary weapon
select "edit key" for primary, click left mouse repeat for right mouse click apply then ok.

**Comment by kisak-valve** [comment]
Hello @IskU0os, did @1157's suggestion fix your issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
