### ISSUE TITLE
[L4D2] Segfault on launch

### ISSUE THREAD

**Issue by stuartf** [ValveSoftware/Source-1-Games#1902]
It was just working 2 days ago, but now when I launch from Steam I get (in ~/.steam/error.log):

    The program 'hl2_linux' received an X Window System error.
    This probably reflects a bug in the program.
    The error was 'BadMatch (invalid parameter attributes)'.
      (Details: serial 623 error_code 8 request_code 42 minor_code 0)
      (Note to programmers: normally, X errors are reported asynchronously;
       that is, you will receive the error a while after causing it.
       To debug your program, run it with the --sync command line
       option to change this behavior. You can then get a meaningful
       backtrace from your debugger if you break on the gdk_x_error() function.)
    /home/stuart/.steam/SteamApps/common/Left 4 Dead 2/./hl2.sh: line 67: 20587 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
    Game removed: AppID 550 "Left 4 Dead 2", ProcID 20587

I tried verifying the game cache as well as removing and reinstalling the game.

System info is:

    Processor Information:
        Vendor:  AuthenticAMD
        CPU Family:  0x10
        CPU Model:  0x2
        CPU Stepping:  0x3
        CPU Type:  0x0
        Speed:  2600 Mhz
        4 logical processors
        4 physical processors
        HyperThreading:  Unsupported
        FCMOV:  Supported
        SSE2:  Supported
        SSE3:  Supported
        SSSE3:  Unsupported
        SSE4a:  Supported
        SSE41:  Unsupported
        SSE42:  Unsupported
    
    Network Information:
        Network Speed:  
    
    Operating System Version:
        Debian GNU/Linux unstable (sid) (64 bit)
        Kernel Name:  Linux
        Kernel Version:  4.0.0-2-amd64
        X Server Vendor:  The X.Org Foundation
        X Server Release:  11702000
        X Window Manager:  awesome
        Steam Runtime Version:  steam-runtime-release_2015-06-12
    
    Video Card:
        Driver:  NVIDIA Corporation GeForce 9800 GT/PCIe/SSE2
    
        Driver Version:  3.3.0 NVIDIA 340.76
        OpenGL Version: 3.3
        Desktop Color Depth: 24 bits per pixel
        Monitor Refresh Rate: 60 Hz
        VendorID:  0x10de
        DeviceID:  0x614
        Number of Monitors:  1
        Number of Logical Video Cards:  1
        Primary Display Resolution:  1920 x 1080
        Desktop Resolution: 1920 x 1080
        Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                                59.7cm x 33.6cm  (68.5cm diag)
        Primary Bus: PCI Express 16x
        Primary VRAM: 1024 MB
        Supported MSAA Modes:  2x 4x 8x 16x 
    
    Sound card:
        Audio device: Realtek ALC888
    
    Memory:
        RAM:  3956 Mb
    
    Miscellaneous:
        UI Language:  English
        LANG:  en_US.UTF-8
        Microphone:  Not set
        Total Hard Disk Space Available:  949773 Mb
        Largest Free Hard Disk Block:  727758 Mb
    
    Installed software:
    
    Recent Failure Reports:
        Sun Jul  5 13:03:30 2015 GMT: file ''/tmp/dumps/assert_20150705090255_19.dmp'', upload yes: ''CrashID=bp-ab37198d-1208-46bf-a548-7772b2150705''

**Comment by steamlinux** [comment]
maybe because you using unstable? I using debian testing (x86_64 gnome) and all games normal work

**Comment by stuartf** [comment]
Sure, but it was working on unstable as of July 3, 2015. So, I assume some package upgrade in unstable breaks it, that package will eventually migrate to testing and break it there.

**Comment by frostschutz** [comment]
I get the same error on (unstable) Gentoo ~amd64. It used to run fine before. TF2 still works normally.

Haven't tried to play in a while so - no idea which package update could be responsible.

**Comment by stuartf** [comment]
This appears to have been fixed. I'm not sure if there was a l4d2 update that did it or if Debian replaced the conflicting library with a backwards compatible one. Either way it's working again.
