### ISSUE TITLE
TF2: Sentry explosive jumping

### ISSUE THREAD

**Issue by Valafar123** [ValveSoftware/Source-1-Games#1903]
Since the Gun Mettle Update, explosive jumping with sentries appears to be broken (much like rocket jumping was broken before the recent patch). The speed and distance travelled is now drastically shorter than it once was. This is not a listed change in the update, so I assume it is a bug.

To recreate the issue, an Engineer must wrangle his own sentry and use it to rocket jump in the same manner that a Demoman or Soldier would. The distance travelled used to be comparable to a Demoman using two sticky bombs, but is now significantly shorter.

I have asked other users, and they are experiencing the same issue.

System specs are unlikely to be relevant as all users appear to be experiencing this issue. In any case, mine are as follows:

OS: Windows 8.1 Pro
CPU: Intel Core i7-3770K
MoBo: Gigabyte GA-Z77X-D3H ATX LGA1155
RAM: Corsair Vengeance DDR3-1600 (2x 8GB)
GPU: Nvidia GeForce GTX 760 Windforce (4GB)
HDD: Corsair Neutron Series GTX (480GB)

**Comment by s0r00t** [comment]
Is it still happening after all the patches released?

**Comment by Valafar123** [comment]
It seems to have been resolved with the patch released on July 6th.
