### ISSUE TITLE
[TF2] Game crashes when joining a game since Gun Mettle update

### ISSUE THREAD

**Issue by s0r00t** [ValveSoftware/Source-1-Games#1905]
The latest update broke the client on Linux (here, Arch x64).
Everytime I join a game, I get a "Failed to lock vertex buffer error". 
[System specs here.](https://gist.github.com/s0r00t/b7df787a68942a5edce6)
The last 2 crashes are linked to TFC, which crashed twice.
EDIT: More infomations:
Lowering the graphics at its minimum won't help.
I managed to load Asteroid once. Retrying crashes the game.
It seems you can play once on a map fully before crashes.
It's been a week and I still can't play... But this tracker seems dead anyways. Still updating this issue though.

**Comment by s0r00t** [comment]
More infomations:
Lowering the graphics at its minimum won't help.
I managed to load Asteroid once. Retrying crashes the game.
It seems you can play once on a map fully before crashes.
It's been a week and I still can't play...

**Comment by s0r00t** [comment]
A hacky fix for most maps is to set this as launch options:
>cd ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/ && find . -name "*.cache" -type f -delete && %command% -novid
However, for Gun Mettle maps, this error shows up:
>Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 860160 of shader (dyn=160)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 3833862 of shader (dyn=24)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 860240 of shader (dyn=160)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 1998080 of shader (dyn=160)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 145200 of shader (dyn=160)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 11796864 of shader (dyn=24)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 71680 of shader (dyn=160)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 884742 of shader (dyn=24)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 1867782 of shader (dyn=24)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 1597440 of shader (dyn=24)

I'll try with shaders disabled and check.

**Comment by s0r00t** [comment]
Lowering shadows, shaders and textures fixed it, along with a cleaning of cache files at startup.

**Comment by cripplet** [comment]
Confirmed, also seems to work on my system (Ubuntu 14.04, OpenGL 3.0).

**Comment by dankegel** [comment]
Lowering shadows, shaders and textures one click each seemed to work around it here.
(Ubuntu 15.04, i5-5200U, 8GB ram, probably Intel HD default drivers, see http://www.kegel.com/new-computer-2015b.html ).  Hmm, it's a 32 bit binary, maybe it was hitting the 4GB limit...

**Comment by chemistru** [comment]
I renamed the file (just in case of...) glshaders.cfg to glshaders.cfg.bak located 
~/.local/share/Steam/steamapps/common/Team Fortress 2/tf/glshaders.cfg and ran the game. This file was recreated automatically and no errors any more!! Linuxmint 17.2 86_64 i5 4gb. Have fun, be smart.
