### ISSUE TITLE
l4d2 linux audio speakers don't saving

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/Source-1-Games#1906]
after re-launch game. setting "speaker type" set to "headphones", I have speakers 5.1

**Comment by Tele42** [comment]
Left 4 dead 2 currently only supports stereo on linux, pulseaudio can expand this a bit, but it is still stereo.

**Comment by steamlinux** [comment]
no! l4d2 normal support surround sound! I go to take screenshot

**Comment by steamlinux** [comment]
![2015-07-09 14-06-49](https://cloud.githubusercontent.com/assets/11569159/8593831/e6cd0582-2643-11e5-9a26-f01b0e95ea9c.png)

**Comment by steamlinux** [comment]
look at screenshot, surround sound normally support and work!

**Comment by s0r00t** [comment]
Duplicate of #1881.

**Comment by steamlinux** [comment]
the problem because no one reacts

**Comment by s0r00t** [comment]
Duplicating the issue here won't help.

**Comment by steamlinux** [comment]
I am ready to create 100 such topics, just to have corrected this trouble

**Comment by Tele42** [comment]
"Do not intentionally multi-post an issue." from the <a href="https://github.com/ValveSoftware/Source-1-Games#conduct">code of conduct</a> for this issue tracker. Spamming issue reports will _not_ end well.

**Comment by steamlinux** [comment]
I understand. but the developers did not react. and the CS:GO this problem fixed in a couple of days

**Comment by steamlinux** [comment]
someone fix this bug?

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.

**Comment by steamlinux** [comment]
anwer #1881
