### ISSUE TITLE
OpenGL AMD graphics glitches Linux

### ISSUE THREAD

**Issue by DarekDeo** [ValveSoftware/Source-1-Games#1914]
As written in steam forums: http://steamcommunity.com/app/221410/discussions/2/528398719799977421/

http://i.imgur.com/cH4p13d.jpg

vsync enabled and multicore off slightly helps, at least Portal is playable.

**Comment by Tele42** [comment]
This should also be reported to the video driver vendor (AMD/fglrx), as there is a high chance that is where the corruption is coming from.

**Comment by DarekDeo** [comment]
Might be, I've just submit request to AMD through this: http://www.amdsurveys.com/se.ashx?s=5A1E27D23CFE9B36

**Comment by DarekDeo** [comment]
Installing newest propietary AMD drivers from Ubuntu repository solved the issue for me.
sudo apt-get --purge remove fglrx*
sudo apt-get install fglrx-updates fglrx-amdcccle-updates

more info: http://askubuntu.com/questions/78906/ati-amd-proprietary-fglrx-graphics-install-fails-how-can-i-resolve-the-problem
in case propietary drivers won't work for someone after reboot, this always helped me to install open source ones: http://askubuntu.com/questions/68306/how-do-i-remove-the-proprietary-ati-drivers

**Comment by kisak-valve** [comment]
Closing per the last comment.
