### ISSUE TITLE
[linux] source-1 games will suffer severe performance loss on recent linux kernels

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Source-1-Games#1915]
see https://bugzilla.kernel.org/show_bug.cgi?id=103781
Core scheduler issue, same for dota2 reborn.

**Comment by kisak-valve** [comment]
Closing as self-inflicted kernel issues are outside the scope of this issue tracker. If you are still experiencing this this issue with an up to date system, please contact the kernel devs involved with that subsystem.
