### ISSUE TITLE
TF2 Crashes randomly upon death after latest update.

### ISSUE THREAD

**Issue by StrikerMan780** [ValveSoftware/Source-1-Games#1919]
It seems in the latest update for TF2, players will crash randomly after getting killed. The chance of it happening isn't completely consistent. Not sure where things are going wrong.

Try joining 64.74.97.177:27050 and play for a bit. Eventually, you'll crash randomly to desktop upon getting killed.

TF2 doesn't seem to generate a dump, so I don't know what I should do.

**Comment by Theloserlad** [comment]
Here is the .Dmp files that have generated from said crashes. https://www.dropbox.com/s/ymkmjylvr6q0jl7/dumps.rar?dl=0 They are in a .rar file.

**Comment by StrikerMan780** [comment]
Seems we're not the only ones either. https://www.reddit.com/r/tf2/comments/3m9cxb/latest_update_makes_me_crash_to_desktop/

**Comment by kisak-valve** [comment]
Closing as fixed.
