### ISSUE TITLE
[Feature request] Add Opus codec support for voice chat

### ISSUE THREAD

**Issue by ksnd** [ValveSoftware/Source-1-Games#192]
It's a quite new codec created specifically for internet communication and other low-latency stuff. I'll just quote this (https://wiki.xiph.org/OpusFAQ)

_Opus is distinguished from most formats for high quality audio (AAC, Vorbis, MP3) by having low delay and it is distinguished from most low delay formats (G.711, GSM, Speex) by supporting high audio quality. It meets or exceeds existing codecs' quality across a wide range of bitrates, and it operates at lower delay than virtually any existing compressed format. Further, the Opus format itself and the reference implementation are available under liberal royalty-free licenses, making it easy to adopt, compatible with free software, and suitable for usage as part of the basic infrastructure of the Internet._

As said, you can even use reference implementation. (http://www.opus-codec.org/license/)

_In brief:
✔ You can encode or decode Opus-compatible streams for any purpose at no cost.
✔ You can integrate the reference Opus encoder and decoder in any application, program, or product, even commercially, at no cost.
✔ You can create your own compatible implementations of the Opus specification and give them away or sell them.
✘ You may not do these things if you engage in Opus-related patent litigation against any user of Opus._

Here's some demos (http://www.opus-codec.org/examples/), here's some graphs http://www.opus-codec.org/comparison/) and it's not difficult to try the reference encoder. (http://www.opus-codec.org/downloads/)

I thought about this after hearing someone play music through the voice chat and it didn't sound as good as they might have thought.

**Comment by TheJJ** [comment]
suggestion for ingame audio: ValveSoftware/steam-for-linux#2337

**Comment by agrastiOs** [comment]
@kisak-valve May be closed. Already implemented in the Jungle Inferno Update.

**Comment by kisak-valve** [comment]
Thanks for pointing this out, closing per "The default voice codec now defaults to Steam Voice" "Steam Voice is now using Opus audio at a higher bitrate than the default CELT codec" in the [2017-10-20](http://www.teamfortress.com/post.php?id=33661) TF2 update.
