### ISSUE TITLE
TF2 Developer Commentary playback issues

### ISSUE THREAD

**Issue by GlacialTurtle** [ValveSoftware/Source-1-Games#1920]
Playback progress bars for the developer commentary tracks don't correspond to actual length, progress and time left for all of the commentary tracks. This will either cause playback to stop when the progress bar hits the end (cutting off longer commentary tracks) or will continue filling up with the commentary node still spinning if the track ends first.

Ubuntu 15.04, Catalyst 15.9, TF2 up to date as of filing date.

**Comment by kisak-valve** [comment]
Hello @GlacialTurtle, per "Fixed the developer commentary audio files not being played properly" in the [2017-01-16 update](http://www.teamfortress.com/post.php?id=26867), are you still experiencing this issue?

**Comment by agrastiOs** [comment]
Commentary's fixed @kisak-valve

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by GlacialTurtle** [comment]
I can confirm it's fixed, just tested on TC Hydro and commentary nodes work as expected.

**Comment by kisak-valve** [comment]
Thanks for retesting @GlacialTurtle.
