### ISSUE TITLE
[Bug]TF2, annoying freezes

### ISSUE THREAD

**Issue by Amadren** [ValveSoftware/Source-1-Games#1925]
From the "Invasion" update, I have a lot of bugs with TF2. I'm using
Linux (Fedora 22) with kernel 4.1.10 and AMD Open Source drivers (well,
with official drivers it's worse but it's AMD's fault cause they don't
update their drivers at all). Well, I have freezes+crashes on every
Invasion map. It just stop working after 2/3 minutes, freezes, then
crashes. Tried with 4.1.8, same. Tried with Ubuntu 15.10 with the
backport 4.0.6, same bug. It might work on Ubuntu 14.04 with Linux
3.16 (just switched to it, I'm now redownloading TF2 :) ). Please do
something :( It's even worse now with the latest 14mb update cause it doesn't even load up any invasion maps!

Edit:
SysInfos:
DM: KDE 5 but same bug with latest GNOME 3, XFCE and Mate
GPU: AMD Radeon HD 7770 with Open Source driver
CPU: AMD A10-6800k
Mouse: Logitech MX Revolution
Keyboard: A classic HP keyboard
HDD: ext4 partition LUKS crypted, 376gb

**Comment by bpearson** [comment]
Same: Gnome 3, Intel Video, Intel CPU, Generic Mouse/Keyboard, SSD HDD encrypted

**Comment by kisak-valve** [comment]
Hello @Amadren, @bpearson, are either of you still experiencing this issue with an up to date system?

**Comment by bpearson** [comment]
Yep, just tried on a community 2fort invasion map. It wouldn't get past downloading the extra content.

**Comment by kisak-valve** [comment]
Thanks for retesting @bpearson, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. If you can find any CrashIDs or minidumps related to this issue, please include them in this issue report.

**Comment by bpearson** [comment]
SysInfo... https://gist.github.com/bpearson/cbd7a30e9b870d50de5656f536391d52
Haven't seen any crash ids or minidumps, where would these reside if I did have some?

**Comment by kisak-valve** [comment]
You can check the log at `/tmp/dumps/<username>_stdout.log` or completely close steam, then run steam from a terminal to get the console spew. This includes the stdout of steam and steam games. Minidump files can be found in /tmp/dumps, and if you compress them, you can drag and drop the archive into the comment box.

**Comment by bpearson** [comment]
Nothing in /tmp/dumps after a crash, but I get this from the console...
`This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
OpenGL: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) x86/MMX/SSE2 3.0 Mesa 12.0.3 (3.0.0)
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_ARB_buffer_storage: AVAILABLE
GL_EXT_texture_sRGB_decode: AVAILABLE
Timed out waiting for game mapping!
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 8
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3200 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3200 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 2880, BackBufHeight: 1620, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: DISABLED

 ##### swap interval = 0     swap limit = 1 #####
`

**Comment by bpearson** [comment]
Not sure if that is helpful or not?

**Comment by kisak-valve** [comment]
Closing as outdated.
