### ISSUE TITLE
[linux] l4d2. today update with bugs!

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/Source-1-Games#1932]
debian sid 64bit, gnome 3.18, nvidia propietary 358.09.
I hate you, valve! with this update you solved my issue and option "dynamics type" in settings saved after re-launch the game..... and dynamics 5.1 don't work!!!! with 5.1 no sounds!! and with "4 dynamics" no sound! "2 dynamics" work. with "7.1 dynamics" sounds not normally! a lot of bass, the sound disappears.
afetr half year you try fix one bug and create new bugs! good job, valve's developers!

**Comment by steamlinux** [comment]
before update "dynamics type" always change to "2 dynamics", after update changing to "dynamics 5.1" and doesn't saving after re-launch!
it's fail

**Comment by MrSchism** [comment]
This was probably a bit more confrontational than it needed to be.  Please fix your ticket.

**Comment by steamlinux** [comment]
no, I'm russian cattle

**Comment by kisak-valve** [comment]
Closing as fixed on 2016-01-14 per https://github.com/ValveSoftware/steam-for-linux/issues/4113#issuecomment-171766405.
