### ISSUE TITLE
L4D2: November 6 update broke sound

### ISSUE THREAD

**Issue by undeference** [ValveSoftware/Source-1-Games#1933]
Now sound is always quiet, regardless of in game volume setting (which has happened before, but quitting and starting again usually fixed it)
After playing for a while the current sound clip loops forever and no other sounds play

**Comment by steamlinux** [comment]
I have the same problem
And gamma becomes low, despite the fact that setting the brightness to the maximum

**Comment by undeference** [comment]
Ehm, looping is a probable dup of https://github.com/ValveSoftware/steam-for-linux/issues/4113

**Comment by kisak-valve** [comment]
Closing as fixed on 2016-01-14 per https://github.com/ValveSoftware/steam-for-linux/issues/4113#issuecomment-171766405
