### ISSUE TITLE
L4D2 random 'Segmentation fault' when connecting to server or changing map on dedicated servers

### ISSUE THREAD

**Issue by Einlander** [ValveSoftware/Source-1-Games#1934]
Starting from the November 6 update all my servers have started exhibiting 'Segmentation fault' crashes. I have tried reinstalling the server and have also tested it on Ubuntu 12,13,14,15 and Debian 7 and 8. Vanilla server and modded server, they all give the same error.

Server Log:
http://pastebin.com/mys39Sby

I will now see what centos does.

**Comment by Einlander** [comment]
Centos 7.5 continuosly restarts.

**Comment by dPing** [comment]
From my understanding, this affects all l4d2 servers, official or not.  usually occurring on map 2 or 3 where the server will crash.  I've even heard this can happen on locally hosted servers as well.

**Comment by kisak-valve** [comment]
Hello @Einlander, are you still experiencing this issue?

**Comment by Einlander** [comment]
I am no longer having this issue. It has been stable. I have not updated the server or updated metamod/sourcemod since. So I'll make a new Issue and reference this one if it happens. You can close this.

**Comment by kisak-valve** [comment]
Thanks for retesting @Einlander.
