### ISSUE TITLE
Mouse click does not always fire. CSGO and CSS in Linux

### ISSUE THREAD

**Issue by fbc** [ValveSoftware/Source-1-Games#1935]
I'm using Mint 17.2 (Icore-7, 16gb ram and Nvidia 750ti). I have to double-click to get it to fire. This occurs intermittently. This behaviour does not occur when I'm booted into windows and playing.

**Comment by kisak-valve** [comment]
Hello @fbc, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
