### ISSUE TITLE
[Linux] Team Fortress 2 - much worse performance after latest patch

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Source-1-Games#1942]
Hi,

I read in changelog, that new patch for TF2 improve performance in Linux. I try it and gets much worse performance :/ Also not only I, look at quick benchmark from Phoronix:

http://phoronix.com/scan.php?page=news_item&px=TF2-AMD-Quick-Test

Any chance to trully improve FPS on Linux?

**Comment by kellzap** [comment]
I can confirm that my performance has been worse as well. I was getting about 110fps regularly, and maybe around 60-80fps with a lot of stuff going on. Now, I get around 40-50fps regularly, with about 15-20fps with a lot happening.

My Setup: Ubuntu MATE 15.10 64-bit ;;; AMD Dual-Core 3.0GHz ;;; Nvidia 650 TI-Boost w/ closed driver version 358.16 ;;; 4 GB RAM

**Comment by Lukypie** [comment]
Same here, with random PC freeze after some minutes of play

**Comment by xylicon** [comment]
I am experienceing the same thing, TF2 crashes within 10-15 minutes of gameplay regardless of the map.

Arch/Antergos
AMD Radeon HD7870  - Mesa 11.0.7
Intel i7 3770k
8 Gigs Ram

**Comment by TheBatman** [comment]
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x16
    CPU Model:  0x30
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2000 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux Mint 17.3 Rosa (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon(TM) R5 Graphics        

    Driver Version:  4.5.13416 Compatibility Profile Context 15.302
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x9851
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                            34.4cm x 19.3cm  (39.4cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: ATI R6xx HDMI
    
Memory:
    RAM:  6848 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  461830 Mb
    Largest Free Hard Disk Block:  412855 Mb
    
Installed software:
    
Recent Failure Reports:
    Sat Dec 19 18:44:03 2015 GMT: file ''/tmp/dumps/crash_20151219124359_5.dmp'', upload yes: ''Discarded=1''
    
Its happening to me too, also when i open the console this appears.
![2015-12-19_00001](https://cloud.githubusercontent.com/assets/13712357/11916536/36324948-a6a0-11e5-9091-2364fc854409.jpg)

**Comment by xstaticxgpx** [comment]
I have also been having terrible performance since the update, I tried lowering all the video settings and was still having stutters, so obviously something else is going on...

Not sure how anecdotal this is, but I noticed this message is getting spammed like crazy to terminal output by steam while running the game, and I don't remember seeing it previously

`controller.cpp (7898) : Assertion Failed: No cached sticky mapping in Get*ActionHandle. This is very bad. Game probably won't work.`

I tried restarting steam with stdout/stderr piped to /dev/null and now the game runs smooth as butter again

`steam &>/dev/null`

Can anyone else see if this works for them?

**Comment by TheBatman** [comment]
@xstaticxgpx Steam controller related maybe? im not getting that btw im downloading TF2 again.

**Comment by Lukypie** [comment]
Am I the only who is getting complete freeze, artifacts  and radeon gpu lockup? 
http://m.imgur.com/a/FacOE

**Comment by bigstiffy** [comment]
Another Arch user here, have had the same issues with tf2 as @xstaticxgpx 
>controller.cpp (7898) : Assertion Failed: No cached sticky mapping in Get*ActionHandle. This is very bad. Game probably won't work.
I've been logging the output and after a little while of running tf2 the log grows to several GB with that error being spammed rapidly, and using the glances package to monitor my system resources, I see it started to fill swap space but not RAM. Eventually swap space fills to capacity and the entire system begins to become unresponsive, forcing me to either reboot or disable/enable the swap partition.
Swap space remains filled even after terminating TF2.

>Arch 64bit / Linux 4.2.5-1-ARCH
>NVidia driver version: 358.16
>X.Org server version 11

**Comment by bigstiffy** [comment]
Another error that began to happen occasionally caused a total lockup of my OS, a popup referencing GL_load_Glyph followed by tf2 crashing, haven't been able to keep the error open long enough without a total crash for too long.

**Comment by TheBatman** [comment]
Driver related most of TF2 problems are propietary driver issue looks like, with Open driver the game runs smooth and loads faster and with propietary driver the game will load slow and have fps drop-.

Happy Xmas!.

**Comment by aggroskater** [comment]
Same is as @xstaticxgpx , with NVIDIA proprietary drivers. I'm running Debian testing. The freeze spikes are correlated with a temporary drop in CPU utilization down to near zero.

**Comment by xstaticxgpx** [comment]
I dug a little further into this and I see in the steam shell wrapper script, they utilize `tee` (if installed) to pipe the output to `/tmp/dumps/<user>_stdout.txt` as well as your terminal

While running steam with normal output in the terminal, the game is unplayable given the message spam described above. With it piped, it's at least playable.

I am running Arch, and I'm not 100% sure how other distributions setup their /tmp space - it could be possible that the log spam into the `/tmp/dumps` file is causing the swap space/crash issues for other people. I've never noticed swap utilization, nor experienced any crashes myself.

If anyone with those issues is so inclined, try altering the steam script as such:

```
$  cat `which steam`
..
# go to the install directory and run the client
cp "$LAUNCHSTEAMBOOTSTRAPFILE" "$LAUNCHSTEAMDIR/bootstrap.tar.xz"
cd "$LAUNCHSTEAMDIR"
if [ "`command -v tee`" != "" ]; then
	mkdir -p --mode=777 /tmp/dumps
	exec "$LAUNCHSTEAMDIR/$STEAMBOOTSTRAP" "$@" &>/dev/null
	#2>&1 | tee "/tmp/dumps/${USER}_stdout.txt"
else
	exec "$LAUNCHSTEAMDIR/$STEAMBOOTSTRAP" "$@"
fi
```

Dis-regarding all that, I must say that my performance seems to be vastly reduced with the new update, however I can't be 100% sure given the inability to downgrade. At first I thought it might just be the new Tough Break maps, but it seems that I'm lagging a lot more in all situations.

> Arch 64-bit (4.3.3-2-ck)
> NVIDIA 680 GTX (358.16)

**Comment by bigstiffy** [comment]
I've set swappiness to 0 on my system to prevent anything from being stored in swap space, and now while tf2 runs, something is accumulating in my /home partition. I cannot locate the data being stored, but within half an hour almost 3gb has been used up by data that I cannot find. I loaded up xdiskusage to try and pinpoint what is using up the entire partition, and it shows nearly 9gb is used up by (Permission Denied), even when running with root privileges. First time running xdiskusage it showed ~6gb usage of this mysterious (Permission Denied) block, after running TF2 for 30-45 minutes, 3gb more had been used up. Performance of the application aside, having it eat up all available disk space for what I assume is the error it continues to spew out, this is a major issue.

**Comment by TheBatman** [comment]
i changed my OS (mostly a re-install) i'm using AMD and after making some
tests at least for me everything is fixed at least with Source 1 games if i
want to play other 3rd party Linux AAA games i have to use privative
drivers and those games (example boderlands 2 or civ 5) the game will run
smooth.

privative driver gave me a result of a bunch of spam (see screenshot in my
last comment) and open driver will give me a smooth experience in all
source 1 games.
greetings.
btw is valve reading this or...? i mean its hard i know but come on at
least a word from valve maybe?

2015-12-28 22:49 GMT-06:00 bigstiffy <notifications@github.com>:

**Comment by Lukypie** [comment]
So, with this "new update", we got:
- GPU driver module lockup after minutes of playing on some AMD video cards using the foss driver http://imgur.com/a/FacOE (me and other people is having that problem after minutes of playing)
- Worse performance https://www.phoronix.com/scan.php?page=news_item&px=TF2-AMD-Quick-Test
- A BIG logging problem which saturates your hard disk and ....what else? 

And what? The latest tf2 update obsiously fixes only OS X and Windows problems.

**Comment by TheBatman** [comment]
TF2 and CS:GO is broken.

ty Valve

2015-12-29 4:32 GMT-06:00 Luca <notifications@github.com>:

**Comment by xpris** [comment]
So, anyone tested @xstaticxgpx tip? It works? Gives normal performance at latest?

**Comment by aggroskater** [comment]
@xstaticxgpx tip worked for me to reduce the freeze spikes at first, though it didn't eliminate them. Eventually though, the freeze spikes stopped all together. I'm running the beta version of the client, which has had several updates since (though none that appear to indicate fixes for this issue; granted, that doesn't mean a fix hasn't worked its way in). I'll revert his changes and see if the issue persists in TF2.

**Comment by xstaticxgpx** [comment]
It appears one of the updates did fix the assertion logging spam, I'm not seeing that anymore so the STDOUT redirection shouldn't be necessary at this point.

On a full server on the new tough break maps I still get really disappointing performance, however. Really got nothing quantifiable though...

**Comment by ivan-kolmychek** [comment]
Another ArchLinux user here, got the huge performance drop in both CS:GO and TeamFortress 2 week ago or so.

**Comment by xpris** [comment]
Two new update to TF2 in march. So anyone tested it? It change something in performance on Linux?

**Comment by TheBatman** [comment]
its nothing really only preps for competitive closed beta and some minor
bug fixes

2016-03-06 10:46 GMT-06:00 xpris <notifications@github.com>:

**Comment by Lukypie** [comment]
I have to say, that's really a shame, they don't even test releases. And now probably the freedesktop developers should fix the Mesa drivers for a tf2 bug.
If something similar would happen for Windows, the situation would be different.

**Comment by TheBatman** [comment]
Valve never really cared about Linux it was just only a backup if windows 10 sucked ass.

They are not even working in SteamOS alot.

**Comment by xylicon** [comment]
I'm still in the same boat I was in 4 months ago. Ever since the Tough Break update TF2 has been broken for me, locks up my whole system at random times, no error messages or console output that is useful. Bummer because this is my favorite game.

**Comment by TheBatman** [comment]
@xylicon i have to use windows for the same reason.....

**Comment by fourpoint7** [comment]
I'd also like to echo the previous sentiments expressed above.

**Comment by Lukypie** [comment]
Some updates.

Some bad updates. Seems like that amdgpu drivers are also affected. Same problem using linux 4.5 with powerplay enabled, after minutes of gameplay everything stucks.

**Comment by xylicon** [comment]
Checking in, I've been scouring the internet and trying every suggestion I can find and I still cannot play TF2 for more than ten minutes. Complete system lockup.

**Comment by TheBatman** [comment]
well poop looks like valve ignore us

**Comment by volca02** [comment]
I suffer from occasional bad performance, and I tracked the problem down to what seems to be a material loader thread. Basically if this happens, the tf2 process never ever regains high FPS, as this thread pretty much eats all CPU and never stops.

In perf, it looks like this when it happens:

> Samples: 178K of event 'cycles:u', Event count (approx.): 71743293195                
>   Children      Self  Command          Shared Object        Symbol                   
> +   18.90%     0.00%  MatQueue0        [unknown]            [.] 0x0000000040400000   
> -   17.99%    17.99%  MatQueue0        [unknown]            [.] 0x00000000f4560411   
>      17.99% 0x40400000;0xf4560411                                                    
> -   13.96%     3.14%  MatQueue0        [vdso]               [.] __vdso_gettimeofday  
>    - 10.82% __vdso_gettimeofday;entry_SYSENTER_compat                                
>      0.89% __vdso_gettimeofday                                                       
>    + 0.73% 0x89830fff;__vdso_gettimeofday                                            
>    + 0.52% 0;0;__vdso_gettimeofday                                                   
> -   11.05%     0.00%  MatQueue0        [unknown]            [.] 0000000000000000     
>    + 2.24% 0;0;__vdso_gettimeofday;entry_SYSENTER_compat                             
>    + 1.50% 0;__vdso_gettimeofday;entry_SYSENTER_compat                               
>    + 0.52% 0;0;__vdso_gettimeofday                                                   
> -   10.82%    10.82%  MatQueue0        [kernel.kallsyms]    [k] entry_SYSENTER_compat
>    + 2.94% __vdso_gettimeofday;entry_SYSENTER_compat                                 
>    + 2.24% 0;0;__vdso_gettimeofday;entry_SYSENTER_compat                             
>    + 2.18% 0x89830fff;__vdso_gettimeofday;entry_SYSENTER_compat                      
>    + 1.50% 0;__vdso_gettimeofday;entry_SYSENTER_compat                               
>    + 1.43% 0x8001004;__vdso_gettimeofday;entry_SYSENTER_compat                       
> +    9.11%     0.00%  MatQueue0        [unknown]            [.] 0x0000000008001004   
>      7.74%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1c8b58d   
>      7.74%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1cef340   
>      7.74%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1c8d39f   
>      7.74%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f5e5ba10   
>      7.74%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f5e3b8b4   
>      7.74%     0.00%  hl2_linux        [unknown]            [.] 0x000000000804877b   
>      7.74%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f74d0196   
>      7.72%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1c8b47f   
>      7.66%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1b9f181   
>      7.66%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1b9f3ee   
>      7.66%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1b9f4f9   
>      7.66%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1c8f84b   
>      5.16%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1b8412d   
>      5.13%     0.00%  hl2_linux        [unknown]            [.] 0x00000000f1b817df

**Comment by TheBatman** [comment]
Nothing we can do then right?

2016-10-21 14:12 GMT-05:00 volca02 <notifications@github.com>:

**Comment by ICHx** [comment]
It happens to me  1 out of 10 joining competitive mode server
```

System:    Host: GlaDOS Kernel: 4.18.0-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.13.3
Distro: Manjaro Linux
Machine:   Type: Desktop System: ASUS product: All Series v: N/A serial: <root required>
Mobo: ASUSTeK model: H81M-E v: Rev X.0x serial: <root required> UEFI: American Megatrends v: 3602
date: 03/26/2018
CPU:       Quad Core: Intel Core i5-4460 type: MCP speed: 798 MHz min/max: 800/3200 MHz
Graphics:  Card-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics driver: i915 v: kernel
Card-2: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 396.24
Display: x11 server: X.Org 1.19.6 driver: nvidia resolution: 1920x1080~60Hz
OpenGL: renderer: GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 396.24
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169
Drives:    Local Storage: total: 698.65 GiB used: 207.01 GiB (29.6%)
Info:      Processes: 278 Uptime: 1d 22h 33m Memory: 7.67 GiB used: 3.01 GiB (39.2%) Shell: bash inxi: 3.0.18
```

**Comment by Nephyrin** [comment]
The original bug here, that certain drivers had lowered FPS from a 2015 update, is no longer really actionable.  Many changes have been made to the renderer since then, tweaks to OpenGL performance.  Anyone with a specific issue would be better served opening a new bug.
