### ISSUE TITLE
[TF2] Strange Vaccinators do not track ubercharge uses correctly

### ISSUE THREAD

**Issue by Valafar123** [ValveSoftware/Source-1-Games#1948]
It appears that Strange quality Vaccinators are not counting the use of ubercharges correctly. It should track any ubercharge that is used, but instead only appears to count when the fourth charge is used.

I tested this in a private server with another player to confirm my thoughts. It only counts the fourth ubercharge use, even when the Vaccinator is fully connected to the patient with no interruptions.

I would imagine the problem is item server side, but here are my system specs if they are of any use:

OS: Windows 8.1 Pro
CPU: Intel Core i7-3770K
MoBo: Gigabyte GA-Z77X-D3H ATX LGA1155
RAM: Corsair Vengeance DDR3-1600 (2x 8GB)
GPU: Nvidia GeForce GTX 760 Windforce (4GB)
HDD: Corsair Neutron Series GTX (480GB)

**Comment by jokleinn** [comment]
This is most likely intentional, to show that the four-ubercharge usage is a "full uber" as a single one of them are 31.25% of a "full uber" in comparison to stock, or 25% in comparison to having 4 charges.

**Comment by kisak-valve** [comment]
Closing per the last comment.
