### ISSUE TITLE
segfaults in datacache.so with mat_queue_mode -1

### ISSUE THREAD

**Issue by vincent-t** [ValveSoftware/Source-1-Games#1949]
first crash:
[ 4851.162059] MatQueue0[12982]: segfault at 4 ip 00000000f0bb571d sp 00000000d8303080 error 4 in datacache.so[f0b89000+6b000]
second crash:
[19510.580039] MatQueue0[11171]: segfault at 4 ip 00000000f0b8b71d sp 00000000a69e1080 error 4 in datacache.so[f0b5f000+6b000]

OS: Ubuntu 14.04
CPU: Intel
GFX: Nvidia

**Comment by kingseva** [comment]
I'm agree. 

[  811.362895] hl2_linux[4269]: segfault at 4 ip 00000000f2a4c05d sp 00000000ffc70fd0 error 4 in datacache.so[f2a1e000+74000]
[ 1084.882433] hl2_linux[4768]: segfault at 4 ip 00000000f2a8a05d sp 00000000ffc46130 error 4 in datacache.so[f2a5c000+74000]

Last update of CSS results crash every time during playing.

OS: Ubuntu 14.04
CPU/GPU: Intel

**Comment by vincent-t** [comment]
@gdrewb-valve is someone at valve working on this?

**Comment by gdrewb-valve** [comment]
You'll have to wait for the team to comment.  If anything changes they'll update this issue.

**Comment by ElectricTriangle** [comment]
@vincent-t They don't comment here anymore (or tag here, or even exist here, hell if I know why). Although it's worth mentioning they're probably watching. Probably.

**Comment by vincent-t** [comment]
@ElectricTriangle It's sad, why they have this issuetracker...

**Comment by kisak-valve** [comment]
Hello, if anyone is still experiencing this issue, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. Also, please include any CrashIDs or minidump files related to this issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.
