### ISSUE TITLE
Game state missing from HUD

### ISSUE THREAD

**Issue by ksnd** [ValveSoftware/Source-1-Games#195]
I have asked about this on a few servers, but haven't got any answers.

Is this a bug, or can servers disable it for reason or another?

Here's a screenshot from pl_badwater... I can't see where the payload is at.

![](http://i.imgur.com/tCU7Rie.jpg)

No time display either.

This makes the game close near unplayable.

**Comment by kisak-valve** [comment]
Hello @ksnd, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
