### ISSUE TITLE
Unable to connect to Valve Luxembourg servers

### ISSUE THREAD

**Issue by Oniiku** [ValveSoftware/Source-1-Games#1950]
Since May of last year I have been having great trouble connecting to valve Luxembourg TF2 servers. I would turn on the game, input "Valve" in the tag search box, refresh the server browser and then find that I can't find any Valve Luxembourg servers. After maybe ten minutes of waiting and refreshing I might find maybe five or six Luxembourg servers. Now recently when I have been playing on one of the few servers that my server browser could find and let me connect to, I just instantaneously get disconnected from the server and am unable to reconnect to it or find it in the server browser. This problem as a whole has severely limited what maps and game modes I can play on and has started to get annoying, especially since it has been a problem for a long time.

My computer specs are as follows:

CPU: i5-3470 3.20GHz
Operating system: Windows 7 home premium
RAM: 8GB
Graphics card: GTX 660 2GB

**Comment by Wasmanr2** [comment]
You no longer can join Valve servers trough the server browser (it doesnt allow AD-HOC connections anymore)
Since Casual was added.
@kisak-valve you may close this ?

**Comment by kisak-valve** [comment]
Closing per last comment.
