### ISSUE TITLE
[TF2] Phlogistinator + Knockback

### ISSUE THREAD

**Issue by Aminthea** [ValveSoftware/Source-1-Games#1956]
I've discovered a bit of a pickle when it comes to the Phlogistinator and it's recent changes. When Tough Break was announced and released, the Phlogistinator was updated to give the Pyro a small burst of uber and immunity to any knockback effects. More recently, I've noticed, (after the small nerf to the Phlogistinator recently,) the Phlogistinator can still be affected by knockback.

Doing some field tests, I've noticed the Phlog can still take knockback from compression blasts. Bullets and rockets don't affect the Pyro while he's taunting + ubered, but this becomes an issue when an opposing Pyro can compression blast back the Phlog Pyro once, which takes them out of their taunt, and gives them a free uber to charge at the enemy with while having a full mmph bar of crits.

It's pretty scary and probably a bug that only I've noticed, but I believe its worth bringing up.

**Comment by hahagoni** [comment]
taunting on top of a player that moves afterwards/ on top of a building that gets destroyed also cancels the taunt.
In that case, the user should just fall down and continue the taunt in the air (or the weapon should be rebalanced)

**Comment by jh34ghu43gu** [comment]
Request this be closed as airblast no longer does this (proof can be seen in this timestamped video https://youtu.be/fvl1_hfMI_s?t=54 ), probably since the JI airblast changes. The taunt cancel as described by ghost has been opened in a separate issue.

**Comment by kisak-valve** [comment]
Closing per the last comment.
