### ISSUE TITLE
[HL2 - Lost Coast] question about commentary 

### ISSUE THREAD

**Issue by ajloveslily14** [ValveSoftware/Source-1-Games#1963]
I was wondering if there is a list of commands that the commentary nodes use as there isn't a commentary file. Id love to know how to show that HDR graph

**Comment by BreakinBenny** [comment]
If you go into Lost Coast's directory and m"aps", there should be a d2_LostCoast_commentary.txt

**Comment by ajloveslily14** [comment]
There is but its empty, i think because they added in the commentary before standardizing it, I think that its just hard coded in.

**Comment by BreakinBenny** [comment]
Then it's because the commentary text file is located inside Lost Coast's VPK.

**Comment by ajloveslily14** [comment]
ohhh so what do i need to get that then

**Comment by BreakinBenny** [comment]
It's easy: you get ahold of GCFScape, then open the "_dir.vpk" for Lost Coast since the other files aren't supposed to be opened.

**Comment by ajloveslily14** [comment]
I dont see that anywhere in the dir

On Fri, May 27, 2016 at 1:47 AM, BreakinBenny <notifications@github.com>
wrote:

> It's easy: you get ahold of GCFScape, then open the "_dir.vpk" for Lost
> Coast since the other files aren't supposed to be opened.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ValveSoftware/Source-1-Games/issues/1963#issuecomment-222072815>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFTY8JDUYWVIIgLLP3RL77ADOK0CiSZuks5qFpORgaJpZM4Hp3ce>
> .
>



-- 
yours truly,
A.J. Wallen

**Comment by BreakinBenny** [comment]
"Half-Life 2\lostcoast\lostcoast_pak_dir.vpk\maps"
