### ISSUE TITLE
[Team Fortress 2 Linux] Window mode switch = disconnect from server

### ISSUE THREAD

**Issue by Kengur8** [ValveSoftware/Source-1-Games#1965]
Hello.

When I switch game res or window mode it would usually take 4-5 seconds and the game become completely unresponsive and the server connection drops. On Windows this doesn't happen on the same PC.

Fedora 23
OpenGL renderer string: Gallium 0.4 on AMD ARUBA (DRM 2.43.0, LLVM 3.7.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.1.0 (git-525f3c2)

**Comment by Tele42** [comment]
This sounds like mesa is recompiling shaders. Since mesa doesn't have a shader cache at this time, the effect is more severe than other driver stacks (and the windows client uses pre-compiled shaders).

**Comment by kisak-valve** [comment]
Closing as this is expected with OpenGL drivers that do not support an on-disk shader cache.
