### ISSUE TITLE
[TF2] [Feature Request] Cvar to disable texture streaming

### ISSUE THREAD

**Issue by ElectricTriangle** [ValveSoftware/Source-1-Games#1968]
I'm requesting an option to disable texture streaming for the reason that it tends to cause major bugs on some cards/graphics stacks (and seems to be causing crashes already), and can cause somewhat undesirable effects with all cards.

**Comment by StrikerMan780** [comment]
Good luck, last time a request like this was actually responded to was years ago.

**Comment by BoctorPoo** [comment]
It's a pretty bad attempt at a "perf fix" to mask the overhead from the gaudy weapons skins. The texture streaming makes everything look like oatmeal on high-end machines, and makes the game stagger around on low-end machines. Who was the removal of _cl_forcepreload_ supposed to help?

**Comment by BoctorPoo** [comment]
There is a ConVar to disable this, but I don't think the patch notes ever mentioned it. Everyone who has tried this so far replied that it worked, though:
`mat_mipmaptextures 0`
Credit to my friend Matt for mentioning it.

**Comment by ElectricTriangle** [comment]
This is no longer relevant, since the game no longer crashes using AMD graphics.
