### ISSUE TITLE
L4D2, Ubuntu 16.04 beta: Freezes when window loses then gains focus

### ISSUE THREAD

**Issue by AgentME** [ValveSoftware/Source-1-Games#1969]
If I start up L4D2, select a different window, L4D2 minimizes if it was in full screen mode, it's fine and sound is still going, but then when I switch back to the window (or even just mouseover it if it's in windowed mode), then L4D2 completely freezes. Sound stops, video freezes, I can't close the window, and I have to `kill -9` the process.

No other Source games that I've tested (Portal 2, Half Life 2, Team Fortress 2) have this issue.

I'm running the Ubuntu 16.04 beta, and I have the nvidia driver version 361.28 and the nvidia 980 ti video card.

**Comment by zootboy** [comment]
I'm experiencing the same issue. Running Arch Linux, NVidia GeForce GTX 570, blob driver 361.28. I'm running the Awesome window manager.

I'm also currently using the __GLVND_DISALLOW_PATCHING=1 workaround as referenced in https://github.com/ValveSoftware/Counter-Strike-Global-Offensive/issues/610 and losing/regaining focus works fine in HL2 ep2 with this same workaround applied.

**Comment by AgentME** [comment]
(Yeah, I'm using __GLVND_DISALLOW_PATCHING=1 too because I'm on 361.28.)

**Comment by rphl321** [comment]
Same here with gentoo! Looks like last game patch broke game for linux!

Info:
OS: Gentoo
Kernel: x86_64 Linux 4.4.0-pf6
CPU: AMD Athlon II X4 635
GPU: Radeon HD5850 Driver r600 Mesa 11.3.0-devel (git-4bc3b1c) (did try "stable" Mesa 11.1.2 with no luck)
Xorg 1.18.1

**Comment by steamlinux** [comment]
I try  352.63, 352.79, 358.16, 361.16, 361.28, 361.42, 364.12 and nothing
I have this bug after update steam (1st beta release, 2nd public release)

**Comment by raku-cat** [comment]
Running arch with xfce, nvidia drivers 364.16, also happens here.

**Comment by Cheeseness** [comment]
As a workaround, this doesn't seem to happen for me when the Steam Overlay is open.

**Comment by steamlinux** [comment]
now I try open steam overlay and minimizing game, it's doesn't help for me

**Comment by raku-cat** [comment]
Here's the full log of me opening steam, opening l4d2, flicking around in menus(didn't produce any log output fwiw), moving the mouse out of and then back in the window, xkilling l4d2 after it froze. and closing steam
https://gist.github.com/raku-cat/9c27a9071dc546bb8630b8b30fa11b60
The relevant lines start at 285
` ##### CMaterialReference::Init got error material for particle\warp4_warp_noz.vmt in tex grhl2_linux: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
oup Other textures`
The 'grhl2' part is where the log stopped when the game finished launching, it sat with just gr, then after i killed it the hl2_linux message went in, and the end of that log line 'oup Other textures' printed.

**Comment by KuriKai** [comment]
This is also happening for me
`Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
    
Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.5.0-040500-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI (DRM 2.43.0, LLVM 3.9.0)

    Driver Version:  3.0 Mesa 11.3.0-devel (padoka PPA)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 23.62" x 13.39"  (27.13" diag)
                                            60.0cm x 34.0cm  (68.9cm diag)
    Primary VRAM: 3072 MB
    
Sound card:
    Audio device: Realtek ALC889
    
Memory:
    RAM:  16045 Mb`

**Comment by dscharrer** [comment]
I also experienced this but was able to fix the hang by removing `~/.steam/root/ubuntu12_32/libSDL2-2.0.so.0` so that the game ends up using the steam-runtime copy of SDL2. It also works fine with my system SDL2.

[system information](https://gist.github.com/dscharrer/03839bf61c2f5cd5a18b00cf4a5a6f68)

**Comment by raku-cat** [comment]
That didn't work here, running arch.

**Comment by Cheeseness** [comment]
> That didn't work here, running arch.

I'm confused. I thought you said in IRC that dscharrer's suggestion did allow you to switch away from the game without it hanging.

**Comment by afwang** [comment]
Just did a quick test with dscharrer's suggestion. Game is launched and tabbing out and in works fine! I'm running Ubuntu 16.04 with Nvidia driver 361.42. I play the game in windowed mode.

Test procedure:

1. Moved libSDL2.2.0.so.0 to out of .steam file tree.
2. Launch L4D2. Joined a game.
3. Press escaped to bring up menu.
4. Tabbed out. Clicked outside the window.

**Comment by raku-cat** [comment]
@cheeseness it did, this one is different from the one on irc, refers to different file. Even then, the other fix only allowed me to alt tab with the overlay up.

**Comment by Cheeseness** [comment]
@raku-cat Ah, I see. There must've been a miscommunication then - I was referring to the files @dscharrer mentioned when I brought it up in IRC. Which files did you end up poking around with that allowed you to alt+tab with the overlay?

**Comment by raku-cat** [comment]
@cheeseness The one from the arch wiki.

**Comment by steamlinux** [comment]
after last update Steam Beta I don't have this issue (I don't remove libSDL from steam directory)

**Comment by raku-cat** [comment]
Can also confirm opting in to steam client beta fixed it for me.

**Comment by kisak-valve** [comment]
Closing per the last comment.
