### ISSUE TITLE
[TF2] Assert: Failed to connect to master html process

### ISSUE THREAD

**Issue by GoTeamAnt** [ValveSoftware/Source-1-Games#1970]
I am on Archlinux and since upgrade to mesa 11.2 TF2 exits after the loading screen with the assertion:

--- log snip ---
Assert(`Assertion Failed: !"Failed to connect to master html process"`):../common/html/chrome_ipc_client.cpp:348
-- log snip ---

Downgrading mesa to 11.1 fixes the problem.

system infomation (it is not possible to copy the text from the steam client):

Archlinux
Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
Linux linux 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
Intel GPU

installed mesa packages:

libva-mesa-driver 11.2.0-1
mesa 11.2.0-1
mesa-libgl 11.2.0-1
mesa-vdpau 11.2.0-1
opencl-mesa 11.2.0-1 
lib32-mesa 11.2.0-1
lib32-mesa-libgl 11.2.0-1
lib32-mesa-vdpau 11.2.0-1

**Comment by xgdgsc** [comment]
Same here with archlinux.

**Comment by robinleruth** [comment]
Hi, did you manage to fix this issue ? I've got the same with RocketLeague, it crashes with the same error. I'm on fedora 24

**Comment by xgdgsc** [comment]
@robinleruth He mentioned "Downgrading mesa to 11.1 fixes the problem".

**Comment by GoTeamAnt** [comment]
I use Mesa 12 now.

On Intel TF2 still segfaults for me (although different cause).

Just as Valve, I have given up on this and bought myself an AMD card.

**Comment by ViBE-HU** [comment]
AMD...lol. Not a good deal since Linux-AMD relation is bad.

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render and an updated OS?

**Comment by kisak-valve** [comment]
Closing as outdated.
