### ISSUE TITLE
Linux TF2 - Game re-scales when I minimize

### ISSUE THREAD

**Issue by lmao-emerald** [ValveSoftware/Source-1-Games#1978]
Game gets a lower window size every time I go to another Window, for example chromium or steam.

Image proof: http://i.imgur.com/SNz8pNj.png
System Information: https://gist.github.com/lmao-emerald/a0a03c442cd352c71dce58584451db98

**Comment by ElectricTriangle** [comment]
The game always does this when set to fullscreen and it's out of focus (possibly to lower system load).

**Comment by kisak-valve** [comment]
Closing as this is intended behavior. If you do not want source 1 games to do this, you should be able to set the ```SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0``` environment variable.
