### ISSUE TITLE
[TF2][Arch x64] Impossible to run game since Tough Break

### ISSUE THREAD

**Issue by s0r00t** [ValveSoftware/Source-1-Games#1981]
Since the Tough Break update, I can't play the game anymore.
I'm using tweaked configurations to lower the game graphics to a maximum (well I think I could lower them more), but the game keeps crashing on the first loading screen, with an "Out of Memory" error.

[My specs are here.](https://gist.github.com/s0r00t/b7df787a68942a5edce6)

**Comment by MRebhan** [comment]
I'm running Arch x64 too and do not have any problems running the game (from the occasiconal crashing on map change, that may be related to my addons though)

"RAM : 3848 Mo"
Maybe you need more RAM. 4GB isn't enough these days anyways.
Do any other source games crash or only TF2?

**Comment by s0r00t** [comment]
Every other Source game (including CS:GO+D2 (if that counts)) besides GMod runs.

I also have swap RAM to compensate with those 4GB. I don't want to upgrade my RAM just for GMod and TF2. That's insane.

**Comment by MRebhan** [comment]
Well, does your RAM ever fill up while the game is open?

**Comment by s0r00t** [comment]
I'll check my RAM while running the game when I'll be able to.

**Comment by kisak-valve** [comment]
Hello @s0r00t, are you still experiencing this issue?

**Comment by s0r00t** [comment]
Someone suggested that I should remove the sound.cache files. I'll try later and give you the results.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by s0r00t** [comment]
Hi there.

I finally took the time to retry starting TF2 with a clean sound cache. Unfortunately, the issue is still present. TF2 won't start : it hangs on the loading menu, and eats all the available RAM. (actually, I cannot prove this point : TF2 eats so much RAM that the computer becomes unusable)

However, reading the logs showed me that a lot of textures were missing in the materials/models/workshop folder. Verifying the game files' integrity did not find any missing files.

(PS: @kisak-valve, I am sorry for the delay that occured. I had this problem for more than a year, without any help. Nowadays, I rarely play on Steam, so I stopped thinking about it even after your comments.)

**Comment by kisak-valve** [comment]
Thanks for retesting @s0r00t.

While this issue was closed it looks like a very similar issue report was opened at #2212 where this was investigated further and some insight has been given by a TF2 dev at https://github.com/ValveSoftware/Source-1-Games/issues/2212#issuecomment-288856916.

I'm going to re-close this issue report in favor of #2212.
