### ISSUE TITLE
[TF2] Memory Allocation Crash: tcmalloc: allocation failed

### ISSUE THREAD

**Issue by robobenklein** [ValveSoftware/Source-1-Games#1982]
Crash log: http://hastebin.com/raw/inepiqopow

The game starts normally with the expected loading screen, then slowly increases in RAM usage to just under 4GB. Eventually, it crashes to this error before entering the main menu.

System: Ubuntu 16.04 amd64  

```
Linux robo-unhexium 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
MemTotal:        7951368 kB
MemFree:         3185732 kB
MemAvailable:    4496896 kB
Buffers:           58628 kB
Cached:          1792040 kB
SwapCached:        28096 kB
Active:          2507920 kB
Inactive:        1960216 kB

TF2 BuildID: 1120072

```

TF2 was originally working on my system within the past 2 months.  
I tested HL2, which ran fine using less than 400mb.

Both `hl2_linux` executables are `ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.32`

**Comment by DaimyoKirby** [comment]
Yeah, I seem to be having the same issue - crashes while on the main loading screen.
Log: https://gist.github.com/DaimyoKirby/36ff71499ddc30104384b14a96f55437
System Specs: 
    Steam - https://gist.github.com/DaimyoKirby/352cb092e86df220df21eb371122bcc3
    Running Arch Linux, up to date.

**Comment by kisak-valve** [comment]
Hello @robobenklein, @DaimyoKirby, are either of you still experiencing this issue? This appears to be memory exhaustion of the 32 bit 4GB limit which is related to the fact the Intel driver uses per-process system ram.

**Comment by robobenklein** [comment]
@kisak-valve I am no longer using intel drivers since I've moved computers.

On my new system (GTX 970M) I have no problems with TF2, it uses only 1.3GB virtual / 1GB res. on the new computer. Same (or heavier) game configs and Linux setup.

**Comment by kisak-valve** [comment]
Thanks for the feedback @robobenklein.

**Comment by DaimyoKirby** [comment]
@kisak-valve TF2 appears to be running fine for me now. I haven't noticed any performance issues lately.

**Comment by kisak-valve** [comment]
Thanks for the feedback @DaimyoKirby, closing.
