### ISSUE TITLE
How difficult is to port Left for dead 1 to Linux?

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/Source-1-Games#1986]
How difficult is to port Left for dead

**Comment by ElectricTriangle** [comment]
Not a bug, not a suggestion. Also nearly entirely pointless since L4D2 includes the original maps.

**Comment by ViBE-HU** [comment]
@ElectricTriangle that's true but the games are not compatible with each other. so if a user only have L4D for some reason(s), L4D maps in L4D2 does not make any sense, so...

**Comment by Tele42** [comment]
@ViBE-HU, the main map campaigns from L4D(1) are included in L4D2, but with the L4D2 game mechanics.

Really, this issue report should be a straight request for L4D(1) for linux, not a leading questing in that direction. I enjoyed the L4D(1) game mechanics a bit better than L4D2, but that's just personal opinion.

**Comment by steamlinux** [comment]
l4d2 doesn't have legs:D

**Comment by kisak-valve** [comment]
Closing as a duplicate of #1812.
