### ISSUE TITLE
[L4D2] Crash in shaderapidx9.so

### ISSUE THREAD

**Issue by vincent-t** [ValveSoftware/Source-1-Games#1988]
I got a crash in shaderapidx9.so:

```
hl2_linux[6659]: segfault at 18 ip 00000000ee0b2e8c sp 00000000ffdf1700 error 4 in shaderapidx9.so[ee080000+e1000]
[ 4396.325881] 
hl2_linux[8318]: segfault at 18 ip 00000000ee0b2e8c sp 00000000ffb0c510 error 4 in shaderapidx9.so[ee080000+e1000]
```

Systeminfo: Ubuntu 16.04, Intel Core i5, Nvidia GTX 660

**Comment by kisak-valve** [comment]
Hello @vincent-t, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. Also, if you can find any CrashIDs or minidump files related to this issue, please include them.

**Comment by kisak-valve** [comment]
Closing pending feedback.
