### ISSUE TITLE
[HLDMS] 

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1992]
HLDMS 11th birthday is This Saturday July 2nd It sure would be nice to get some Issue's fixed :

1 . func_physbox for example would leave a duplicate static brush (as if it weren't tied to an entity).
     This break's levels with fans, doors, or any entity everything is x2.

2.No enemy icon (player name)while looking at enemy in crosshair's.

3.Func_ladder error- "attempted to create unknown entity func_ladder"
(spammed hundreds of times in console)

4.Client model stuck on gordon, will not change from gordon unless you edit
"C:\Program Files\Steam\steamapps\common\Half-Life 1 Source Deathmatch\hl1mp\cfg\config.cfg"

Change the cl_playermodel "models/gordon.mdl" to gman ect. and set file to "read only"
Sometimes this too does not work and you have type in client console to force model change.

5."game_text" no longer works.
no display, also if you try to use game_text with SDK on new map.
It wont render any text.

6 Stats broken ,Previous server version logged player events to a log file at hl1mp "logs"
I.E. player (userid) killed player (userid) with weapon (weaponid), to be scanned
by Gameme stats or another stats plug-in.  Client's could connect to the  server and get full stats.
 with yesterday's "winners" and today's leaders.
This is what is logged now:
L 11/09/2013 - 19:55:56: "maurice_f98<48><>" killed "battisottobanco<50><>"
L 11/09/2013 - 19:56:04: "maurice_f98<48><>" killed "\o/ Vollkornbrett \o/<47><>"
L 11/09/2013 - 19:56:06: "battisottobanco<50><>" killed "maurice_f98<48><>"
L 11/09/2013 - 19:56:25: "battisottobanco<50><>" killed "\o/ Vollkornbrett \o/<47><>"
L 11/09/2013 - 19:56:46: "brownysurfschool<52><>" killed "maurice_f98<48><>"
L 11/09/2013 - 19:56:57: "\o/ Vollkornbrett \o/<47><>" killed "brownysurfschool<52><>"
L 11/09/2013 - 19:56:59: "PulveriserTX<49><>" killed "maurice_f98<48><>"

Oct 2013 12:16:45 Dear Customer, we have found why kills are not tracked properly. It seems there is no weapon included in the gameserver logs and valve breaks their own logging standard (https://developer.valvesoftware.com/wiki/HL_Log_Standard). They log kills just completely without weapons! Best regards The gameME - Team 

7.Weapon mp5 spam- "Playing sequence 2 but theres only one in total/" error
weapon mp5 ,shotgun,

8.No voice icon (who is talking?) Icon bottom part of screen like before

**Comment by kisak-valve** [comment]
This type of multi-issue issue report is effectively untrackable. Closing in favor of the existing separate issue reports.
