### ISSUE TITLE
[TF2/Mac] Changing weapons is broken.

### ISSUE THREAD

**Issue by CrazyGunman** [ValveSoftware/Source-1-Games#1994]
I'm a windows user that's why I can't give detailed information, but there are a lot of complaints on the official TF2 Hub ("SCUD"). They said that they can hear the scroll sound, but can't select the weapon. Pressing Q still works, but they aren't able to use their melee weapons which is a huge issue.

I helped a few mac users by providing a workaround, but it seems like it's a bit glitchy. I told them to check their config.cfg files, maybe the following commands are missing:
bind "MWHEELUP" "invprev"
bind "MWHEELDOWN" "invnext"

Also some noted that creating class configs like medic.cfg also fixed the problem, but only temporary.
I can confirm that the PC version works fine.

**Comment by kisak-valve** [comment]
Closing as this is a second-hand report. If any Mac user can confirm this issue, we can re-open this issue report.
