### ISSUE TITLE
[TF2] [Linux] Losing focus (by close or alt+tab etc) causes input to be disabled

### ISSUE THREAD

**Issue by jokleinn** [ValveSoftware/Source-1-Games#1995]
Gentoo Linux, XFCE4 w/ XMonad derivative, every other openGL game (including CSGO, HL2:DM, Portal 2, L4D2 - source games)  does not have this problem.

When TF2 loses focus, be it alt+tab, mod1+j/k (switches "active" window), mod1+num (switches workspace), clicking the root window (desktop) on another monitor, or by closing, TF2 seems to take all X server input with it. I cannot use my keyboard or mouse to do any input; although the mouse cursor still moves around with my mouse, clicking does nothing. The X-server "kill X" key combination, which is enabled in the config, does nothing. I have to SSH into my computer and forcibly log myself off or reboot in order to restart X in such a manner that X will have input again. What's weird is X itself doesn't seem to be frozen -- if, for example, I have TF2 open in workspace 1 and Mumble in workspace 2, and while playing TF2 I swap my monitors so workspace 1 is on the other monitor and my focus is in workspace 2, I can still see people moving around in TF2, the game is still rendering things, clearly, and its network connection remains active, it's just that X has become unusable.

I figured I'd report this as a TF2 bug as TF2 is the only thing that causes this, and perhaps somebody else would have an idea as to how it might be solved.

**Comment by kisak-valve** [comment]
Hello @jokleinn, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by jokleinn** [comment]
Yes, it is still happening. Just made it happen again -- TF2 spams the ever-loving Christ out of the XOrg logs, and attempting to interface with something that must go through XOrg instead of being passed through to the game causes XOrg to start writing all the logs to stdout, which causes the freeze until it finishes writing about ~500MB of text data to the tty that `startx' was run on. I've figured out a workaround for the bug, but it'd be fantastic if TF2 wouldn't cause so many BadWindow X errors. 

The workaround, for those who are interested, is to either redirect the standard output of XOrg to /dev/null, or to run TF2 in a ewmh-style fullscreen window (look in XMonad's xmonad-contrib source for an example)

**Comment by Tiagoquix** [comment]
@jokleinn Does thil still happen with an updated OS?

**Comment by kisak-valve** [comment]
Closing pending feedback.
