### ISSUE TITLE
[Linux] -dxlevel option, but for OpenGL

### ISSUE THREAD

**Issue by lolwat97** [ValveSoftware/Source-1-Games#2002]
Hello.
Are there any options like -dxlevel 81 and such to improve FPS performance on linux systems, which use opengl?

**Comment by Tele42** [comment]
Hello @lolwat97, source 1 games on linux uses an internal directx to opengl translation layer called ToGL. This is opengl 2.1 + srgb and does not have multiple opengl render paths to pick from.

**Comment by kisak-valve** [comment]
Closing per the last comment.
