### ISSUE TITLE
[TF2] [Linux] TF2 Unplayable (Microfreezes)

### ISSUE THREAD

**Issue by jokleinn** [ValveSoftware/Source-1-Games#2007]
As of yet, with no modification to my previous configuration for TF2, it now will not play on public servers. I can play on tr_walkway_rc2 on a listen server just fine, with minimal issue; connecting to a public server causes the game to play the same loop of audio for approximately 5 seconds, render the next frame, and play the loop of audio from that frame for approximately 5 seconds. I haven't changed any system or TF2 configuration since the last time I played, but I did notice the last time I played any new sound being played would freeze the game briefly. Happens with SDL_AUDIODRIVER=alsa, SDL_AUDIODRIVER=pulse, not setting SDL_AUDIODRIVER, launching with -safe, and launching with -safe and the previous environment variables. Nothing out of the ordinary in the Xorg log. Nothing tremendously out of the ordinary displayed in the TF2 console (although, at first -- selecting, for example, the scout class, will result in the console being spammed "'scout.cfg' not present -- not executing" or whatever, in between each freeze). I'm asssuming what's going on, because of the class.cfg spam, is something like a graphics autoexec is recursing and calling itself -- but this bug happens in safe mode, and it happens with my autoexec and config.cfg being default (with steam cloud disabled)

I'm at my wit's end here as it seems TF2 wants to constantly execute something that restarts the render engine when on a public server (but not a listen server).

**Comment by kisak-valve** [comment]
Hello @jokleinn, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Closing pending feedback.
