### ISSUE TITLE
[Linux] [TF2] startup time & fps inversely proportional to kernel Hz config

### ISSUE THREAD

**Issue by Kiwii** [ValveSoftware/Source-1-Games#2011]
I noticed Team Fortress 2's startup time scales inversely proportional to the Linux kernel's Hz setting: 
- on a kernel compiled with 1000Hz, it takes about 2 minutes 
- on a kernel compiled with 100Hz, it takes about 20 minutes
- on a kernel compiled with 300Hz, it takes about 7 minutes

It also seems to be only using one CPU core during that time.
CPU reclocking/powersaving is disabled (performance governor).

Framerate seems to also be affected: 
- <10 to 20 fps @ 100Hz
- 60 to 120 fps @ 1000Hz

[system info via steam](https://gist.github.com/Kiwii/326a2bddf0dafc82e527928d184d96ae)

**Comment by Nephyrin** [comment]
At the lower kernel tickrates, do you see the game using 100% of a core, or is it seemingly idle? I would suspect some system call is producing unexpected latency based upon tickrate, or perhaps an odd driver interaction.

Does this occur on a vanilla (non -ck) kernel?

**Comment by mastercoms** [comment]
If you add
```
gl_paircache_rows_lg2 15
gl_paircache_ways_lg2 10
```
to the `autoexec.cfg`, does the startup time decrease? And by how much on each tickrate?

**Comment by Kiwii** [comment]
Sorry for the late reply; didn't see the notification. 

@Nephyrin It seems to be using about 80% of one core. It's currently _only_ happening on a vanilla kernel since a recent release of linux-ck has implemented "high resolution timeouts to improve behaviour of userspace that is inappropriately Hz dependent allowing low Hz choices to not affect latency". 

It might entirely be an odd driver interaction, though, as I'm forced to use amd catalyst (15.12) which isn't known for its quality. 

@mastercoms Thanks, I'll do some tests tomorrow if I can find the time to compile the kernels.

**Comment by mastercoms** [comment]
@Kiwii Did you have the chance to do the tests?

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
The FGLRX video driver has been retired by the vendor. If anyone is seeing a similar issue, then that will need to be investigated from scratch.

Closing as outdated.
