### ISSUE TITLE
[TF2] End of the round map thumbnail does not match the map

### ISSUE THREAD

**Issue by redredacted** [ValveSoftware/Source-1-Games#2024]
The end of the round map voting thumbnail for Swiftwater is a thumbnail for Highpass.
Here is an image showcasing the issue: [http://imgur.com/a/sxyav](http://imgur.com/a/sxyav).

**Comment by hahagoni** [comment]
Adding to this; the thumbnail for pass_district is a watergate one.

As for Swiftwater-Highpass, it has been that way in the comp match overview since the initial launch of the Meet your Match update

**Comment by kisak-valve** [comment]
From @FindTheBorealis at #2051:

A few map thumbnails show the wrong map. Pass Time maps District and Timbertown show as
Player Destruction map Watergate, and Payload map Swiftwater shows as the King of the Hill map Highpass.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2017-01-16 update](http://www.teamfortress.com/post.php?id=26867).
