### ISSUE TITLE
[TF2] [Bug Report] [Casual Matchmaking] [URGENT!]: Players Not Being Matched Into Servers After Map-Vote

### ISSUE THREAD

**Issue by Contradicktory** [ValveSoftware/Source-1-Games#2025]
Right now, Casual MM is only matching players into servers that are playing their first match, before a map vote has been made. Once a match ends, a map vote is made and the people who stayed in the server progress to the next round, no new players will be matched into the server.

This becomes especially problematic if a lot of people quit. This also leads to game slowly, but steadily bleeding players, until a 12v12 has inevitably become a 4v4 and enough people are tired of continuing to play.

This is an urgent issue with the latest update, and needs to be fixed **immediately.**

**Comment by hahagoni** [comment]
Players can actually be assigned. I've had a match on pl_borneo where this happened. The odd thing was, a mass of players arrived at the same moment. There's definitely some bug with the system, should be fixed asap.

**Comment by Contradicktory** [comment]
@hahagoni Can you verify that this is happening after the map-vote? This is inconsistent with the experience that most people are reporting.

**Comment by hahagoni** [comment]
@Contradicktory as I have no footage recorded, for the time of being, no.
For the matter of fact, that one was the only case I experienced people joining in, if this helps. I will be looking into this, but I can't promise anything

**Comment by Nephyrin** [comment]
There are a few tuning issues on the matchmaker currently resulting in far too many games running resulting in not enough players to fill empty slots.  We are tuning things and keeping an eye on the situation.  We don't see any evidence that there is a specific bug related to rolling matches, just a general issue of matches-to-players ratio, which would be more evident the longer a match goes on (and the more original players drop).

We're keeping an eye on it and tweaking the system to improve things.

**Comment by FindTheBorealis** [comment]
This appears to have been fixed, at least on more popular maps. New rounds fill with players fairly quickly.

**Comment by kisak-valve** [comment]
Hello @Contradicktory, are you seeing the same?

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/Source-1-Games/issues/2025#issuecomment-423829024.
