### ISSUE TITLE
[TF2] [Feature Request] Queuing in the background

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2028]
Currently, players are forced to stay on the search screen while waiting to get into a competitive/ casual game and the search cannot start if the player is connected to a community server. My proposed suggestion is to make it possible to search for a match and pass the waiting time on various activities such as crafting, using the mann co. store or playing on a community server. People can already circumvent the screens using the developer console and so I can't find a reason to why this should not be implemented. 
Base concept:
![tf_search_comm](https://cloud.githubusercontent.com/assets/24685208/21436070/01b06ec0-c87d-11e6-8001-4ca6a9c4c9b6.png)
![tf_search_mainmenu](https://cloud.githubusercontent.com/assets/24685208/21436072/01b340dc-c87d-11e6-8a1a-0596afdfb3d7.png)
![untitled-3](https://cloud.githubusercontent.com/assets/24685208/21436900/14712604-c881-11e6-9767-b9128a5f2afc.png)

The search options tab is now accessible under the gear.
Party chat can be brought up from under the gear icon. 
Additionally, a clickable plus sign could be added to provide broader information abot the game you are going to join (server info, map name, latency).

EDIT: Also, MvM queues would behave identically
EDIT2:
![info](https://cloud.githubusercontent.com/assets/24685208/22902563/cbee52ec-f235-11e6-90a1-9637e54ffa86.png)

**Comment by Contradicktory** [comment]
This would be a massive QOL (Quality of Life) improvement.

**Comment by stevethepocket** [comment]
On a related note, and I think I've brought this up before somewhere, it would be nice if the process of connecting to a server didn't freeze the UI and let me do other stuff while I wait, especially when connecting to a community map that has to spend a minute downloading.

**Comment by hahagoni** [comment]
@stevethepocket I've heard that it's that the engine is not capable of that. Even CS:GO and Titanfall (which uses an altered version of Source) freeze for a small time when loading a map, they just handle it smoother (possibly due to newer engine branch).

**Comment by hahagoni** [comment]
Additionally; a plus sign could appear that shows what server you are about to connect to (shows ping, current map and server name)

**Comment by hahagoni** [comment]
![Dropdown info box concept](https://cloud.githubusercontent.com/assets/24685208/22902498/8988066e-f235-11e6-8e6d-b5f46895949e.png)

**Comment by hahagoni** [comment]
This feature has now been implemented into the game with the Jungle Inferno update. Closing
