### ISSUE TITLE
[TF2] [Bug] Respawn time covered by Matchmaking 'overlay' when using minimal HUD

### ISSUE THREAD

**Issue by christmasdog** [ValveSoftware/Source-1-Games#2029]
When using the 'Minimal HUD' setting and in a casual or competitive game, the part of the HUD that shows players on both teams and time remaining covers the time to respawn when you have died.

Here's a screenshot that probably describes it better than me:
![20161222184248_1](https://cloud.githubusercontent.com/assets/23142622/21436969/0cf21d5a-c879-11e6-8a65-c0efc20d6fbb.jpg)

**Comment by kisak-valve** [comment]
Noted by @FindTheBorealis in #2075, "the box that appears in the killcam that says how to save screenshots, and the killfeed if the kill report is long enough" are also affected.

**Comment by FindTheBorealis** [comment]
This has been fixed as of the Jungle Inferno Update.

**Comment by kisak-valve** [comment]
Closing per @FindTheBorealis's comment.
