### ISSUE TITLE
[TF2] [Bug] Untradable Giftapults can't be used

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2031]
The untradable Giftapults one does get from Gift Stocking Stuffers do not work.
When trying to use the item, a message is shown: "There are no eligible items." While there of course are.

**Comment by agrastiOs** [comment]
@kisak-valve could you change the name "Untradable Giftapults can't be used" to "[TF2][Bug]Untradable Giftapults can't be used" ?

**Comment by vfjpl** [comment]
I'm also affected…

**Comment by kisak-valve** [comment]
Closing per "Fixed not being able to use non-tradable Giftapults" in the [2017-02-14 TF2 update](http://www.teamfortress.com/post.php?id=27507).
