### ISSUE TITLE
Tf2 Labels   It would be nice to label everyone else's issue's too.

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#2033]

**Comment by kisak-valve** [comment]
Hello @1157, just so it is clear, I am a community moderator. I will be evaluating all the remaining open issue reports and they will be labeled accordingly, however, this process takes time.

**Comment by 1157** [comment]
Thanks for the reply, labels are nice, Getting three year old issue's fixed would be nicer. Half-life deathmatch source, (The source version of Valve's claim to fame) has been broke since the Steampipe update. Never the less it's nice to see some action here on Git hub.

**Comment by hahagoni** [comment]
@kisak-valve Does that mean Valve personally contacted you specifically to manage their Github repository?
