### ISSUE TITLE
[TF2] Can't spectate own buildings while dead in Casual/CompMM

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#2034]
While dead, you cannot select to spectate your buildings directly. This was previously possible in quickplay and is still possible in community servers, but in Casual and Competitive Matchmaking servers, you can only spectate your teammates and not your own buildings.

**Comment by FindTheBorealis** [comment]
This has been fixed in the March 28, 2018 [update](http://www.teamfortress.com/post.php?id=38643).

**Comment by kisak-valve** [comment]
Closing per "Fixed not being able to spectate observer points or your own buildings in Casual Mode" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update and because the reporting user has turned into a ghost.
