### ISSUE TITLE
[TF2][Feature Request] Enable CTFHudMatchStatus HUD element outside of Causal/CompMM

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#2043]
In Casual and Competitive Matchmaking, there is a useful HUD element at the top that neatly shows the amount of players on each team, if they're dead, and (if they're on your team) how long it will be until they respawn. 

In CS:GO, a similar element is found on the HUD and is enabled permanently on every server. However, in TF2, this element is only enabled inside of Casual/CompMM. For non-matchmaking competitive matches and pubs, the feature would be great for quick glances to see who's up and who's down, but there is no way to enable it on a serverside or clientside basis legally. 

TF2 should have this HUD element permanently enabled on all servers or alternatively have a cvar that can be set by the server to enable/disable it.

**Comment by agrastiOs** [comment]
Yea, that's what I suggested on Reddit.

**Comment by FindTheBorealis** [comment]
You can enable and disable the match HUD at will, in official or community servers, as of the March 28, 2018 [update.](http://www.teamfortress.com/post.php?id=38643)

**Comment by agrastiOs** [comment]
@kisak-valve this can be closed

**Comment by kisak-valve** [comment]
Thanks, closing.
