### ISSUE TITLE
[TF2] Alt-Fire activates taunt on non-Amputator Medic melee weapons

### ISSUE THREAD

**Issue by bleghfarec** [ValveSoftware/Source-1-Games#2044]
All of the medic's melee have an alt-fire that cause the medic to taunt. This feature should be specific to the Amputator, but for some reason it is enabled on all medic melees. This can lead to immobility and most certainly death in gameplay if a medic accidentally right-clicks during a fight with his melee out.

**Comment by agrastiOs** [comment]
Haha, and I thought it was for taunt-killing.

**Comment by hahagoni** [comment]
It's fine on the Ubersaw

**Comment by Haze33E** [comment]
Never knew this existed only thought it was a Amputator thing well Ubersaw taunt kills just got easier lol.

**Comment by FindTheBorealis** [comment]
The Ubersaw and Amputator are the only Medic melees that can activate the taunt with alt-fire now, 
I believe this can be closed @kisak-valve.

**Comment by kisak-valve** [comment]
Thanks for checking. Closing.
