### ISSUE TITLE
[TF2] [Feature Request] tf_scoreboard_mouse_mode 2 should be the default value

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2057]
Mouse input on the scoreboard is very convenient. Sadly, it's not enabled on by default. You have to enable it in Adv. Options, but it's the less convenient version. (Value 1) The Value 1 version doesn't let you look around when scoreboard is opened. However, Value 2, which can only be used with the console, let's you look around until you click on the scoreboard, similarly to CS:GO. The muting and reporting is incredibly useful, so value 2 should be the default, and also the option for it should be added to Adv. Options.

**Comment by Haze33E** [comment]
I think this is needed as well.  Another change that would help is being able to use the mouse input while on the respawn screen.

**Comment by agrastiOs** [comment]
Yes, and also that it should be implemented for MvM as in #2061.

**Comment by Tiagoquix** [comment]
This has been implemented in the game as an undocumented change.

https://wiki.teamfortress.com/wiki/October_10,_2024_Patch

> tf_scoreboard_mouse_mode default value changed from 0 to 2.

**Comment by kisak-valve** [comment]
Closing per the last comment.
