### ISSUE TITLE
[TF2] [Bug] Problems with c_models

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2062]
C_models were added through TF2 updates for most weapons and replaced v and w_models. However, some c_models have problems. For example, the Sapper. When you switch to the Sapper, Spy does not flip the switch anymore. Or the Bottle. It no longer breaks when a critical hit with it is done. And it's not intentional. The updated c_  broken bottle model is in the game. However, the code is not changed to accommodate that. It still attempts to switch to the old model, and fails, because there isn't one anymore. The code should be changed.
So, the Sapper and Bottle should be fixed.

**Comment by agrastiOs** [comment]
I would like to add about the Sandvich. When the player uses the Sandvich, he won't see the bite mark.   However, other players will see the bite mark. Interestingly, having tf_taunt_first_person 1 (for taunting in first person), the player *will* see the bite mark.

**Comment by agrastiOs** [comment]
Also, no longer you can see the grenades in the Grenade Launcher.

**Comment by hahagoni** [comment]
Ullapool Caber doesn't break open in first person

**Comment by agrastiOs** [comment]
Closing due to this having been fixed as of the Jungle Inferno Update, thanks.
