### ISSUE TITLE
[TF2] Demo playback does not display the casual/ comp UI bar on the top of the screen 

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2065]
I don't think further explanation is needed, but I will provide if requested

**Comment by FindTheBorealis** [comment]
Not only has this been fixed in the March 28, 2018 [update](http://www.teamfortress.com/post.php?id=38643), but you can enable and disable the match HUD at will, even when viewing demos.

**Comment by agrastiOs** [comment]
@kisak-valve this can be closed

**Comment by kisak-valve** [comment]
Thanks, closing.
