### ISSUE TITLE
[CS:GO] Season Effects Camera convar not working

### ISSUE THREAD

**Issue by yamiM0NSTER** [ValveSoftware/Source-1-Games#2070]
Hello,

I wanted to turn off the overlay that pops up in deathmatch when you die with **cl_freezecameffects_showholiday** set to 0, however it doesn't seem to work. Neither setting it to "1" or "0" turns off the overlay effect.

Best Regards,
yamiM0NSTER

**Comment by kisak-valve** [comment]
Hello @yamiM0NSTER, CS:GO issues are not tracked in this issue tracker. I've passed this on to the CS:GO team, but there most likely won't be any updates reported here.
