### ISSUE TITLE
[TF2] Restoring connection message on initial connection with matchmaker

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2076]
When the matchmaker finds a game, before the map loads, a screen quickly flashes by. This screen says
"Match in progress, restoring connection to game server".

**Comment by kisak-valve** [comment]
Hello @FindTheBorealis, please open a separate issue report for the second issue. In general, there should be one issue per issue report so that each issue can be tracked properly.

**Comment by FindTheBorealis** [comment]
Closing as the matchmaking UI has been overhauled in the Jungle Inferno Update.
