### ISSUE TITLE
sv_pure 1 and 2 on servers crash TF2 client with mods

### ISSUE THREAD

**Issue by Wasmanr2** [ValveSoftware/Source-1-Games#2078]
If you use mods on sv_pure 1 or 2 it makes most poeple crash from what i experienced.

Would'nt be it better to force the client to load default models instead of making the client crash if he/she uses custom models/sounds/etc. ?

**Comment by kisak-valve** [comment]
Hello @Wasmanr2, just to check, is the adjusted title accurate?

**Comment by hahagoni** [comment]
Do custom sounds cause a game crash? I think they just produce a screeching noise. Haven't tested it in a while

**Comment by Wasmanr2** [comment]
Yes the title is correct thanks. Im not pretty sure but im sure that models and custom textures 100% crashing the client if used on sv_pure 1 / 2

**Comment by Wasmanr2** [comment]
Seems like it fixed it self with the Jungle inferno update. 
Now custom models dont lead to instant crash, instead it draws out some buggy hats with missing textures sometimes which is alot better then crashing with custom models.

If somebody has still this Problem they can reopen it or whatever.

**Comment by Wasmanr2** [comment]
So apperently it still appears.
Using custom models (except custom sounds) leads to a crash when preloading them and joining a sv_pure 1-2+casual server.
Joining a casual server without preloading the models works when you do 1 match, but starting another match and joining a casual/sv_pure 1/2 server leads to a instant crash.
