### ISSUE TITLE
HL2DM: Respawn after death not working correctly.

### ISSUE THREAD

**Issue by richi902** [ValveSoftware/Source-1-Games#208]
every time i die, i have to press ESC or a button on the xbox360 controller to respawn.

Prozessor:
    Hersteller: GenuineIntel
    Geschwindigkeit: 3292 MHz
    4 logische Prozessoren
    2 technische Prozessoren
    HyperThreading:  Unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    Ubuntu Raring Ringtail (development branch) (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.8.0-12-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11302000
    X-Fenstermanager: Compiz
    Steam-Runtime-Version: steam-runtime-release-i386_2013-03-08

Grafikkarte:
    Treiber: ATI Technologies Inc. AMD Radeon HD 7700 Series 

```
Treiber-Version: 4.2.12172 Compatibility Profile Context 12.10.17
Desktop-Farbtiefe: 24 Bit per Pixel
Monitor-Aktualisierungsrate: 59 Hz
Anbieterkennung: 0x1002
Gerätekennung: 0x683f
Anzahl der Monitore: 1
Anzahl der logischen Grafikkarten: 1
Prim. Anzeigeauflösung: 1680 x 1050
Desktop-Auflösung: 1680 x 1050
Prim. Anzeigegröße: 47,4 cm x 29,6 cm (55,8 cm diag.)

Kein prim. VRAM entdeckt
```

Soundkarte:
    Audiogerät: Realtek ALC892

Speicher:
    RAM: 7931 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 183903 MB
    Größter freier Festplattenspeicherblock: 134116 MB

Installierte Software:

Neueste Fehlerberichte:

**Comment by kisak-valve** [comment]
Hello @richi902, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
