### ISSUE TITLE
[TF2] [Feature Request] Bring back CTF Well and CTF Sawmill to Casual

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2082]
CTF Well and CTF Sawmill are really fun maps and people are disappointed that they aren't included in Casual. They should be brought back.

**Comment by FindTheBorealis** [comment]
CTF Well and CTF Sawmill have been added to casual, along with CTF 2Fort Invastion, CTF Foundry, and 
CP 5Gorge in the March 28, 2018 [update](http://www.teamfortress.com/post.php?id=38643).

**Comment by agrastiOs** [comment]
Closed.
