### ISSUE TITLE
[TF2] Competitive related voice lines playing in casual matchmaking

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2085]
They are not sorted out at all, the ones that should not be playing still are being played and it's quite annoying as they not only don't match the gamemode, they can barely be understood due to the bigger team size in casual.

**Comment by agrastiOs** [comment]
Yeah, I got Soldier's "Mess with the Pocket, get a rocket!" or Spy's "I like my teams like I like my romances: in groups of six."

**Comment by hahagoni** [comment]
This has been fixed with [March 28th's update](http://www.teamfortress.com/post.php?id=38653), closing
