### ISSUE TITLE
[TF2] Missing Pit of Death map thumbnail error

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2091]
Occasionally an error message will appear in the console:
"--- Missing Vgui material vgui/..\vgui\maps\menu_thumb_pd_pit_of_death_event".
This appears to be a naming inconsistency, as the map thumbnail file is listed as
`menu_thumb_pd_pit_of_death.vtf`, without the `event` at the end.

**Comment by agrastiOs** [comment]
@kisak-valve [Fixed in April 13, 2017 Patch](https://github.com/SteamDatabase/GameTracking-TF2/commit/97e9eb7db3ae24953b050e7dffc62f59e3e2b70f)

**Comment by kisak-valve** [comment]
Thanks for catching this change, closing per [this line](https://github.com/SteamDatabase/GameTracking-TF2/commit/97e9eb7db3ae24953b050e7dffc62f59e3e2b70f#diff-31be800256ddf259f83aba42c5433b8bR17526) in that diff. This looks like it was in a mvm_rottenburg specific file so if this happens with other maps, please let us know and I can re-open this issue report.
