### ISSUE TITLE
[TF2] [Bug] Commentary is still broken

### ISSUE THREAD

**Issue by mitchcliff123** [ValveSoftware/Source-1-Games#2092]
I checked the commentary after the new update saying the bug was fixed. It isn't, there is still no sound coming out.

**Comment by kisak-valve** [comment]
Hello @mitchcliff123, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report.

If there is some interesting output in the console, please include that as well in the gist.

**Comment by agrastiOs** [comment]
It should work. I just saw a player streaming the commentary mode now, and it worked.

**Comment by agrastiOs** [comment]
As it works for other players, I think this should be closed @kisak-valve

**Comment by mitchcliff123** [comment]
I will check one more time.

**Comment by mitchcliff123** [comment]
@kisak-valve 
`Computer Information:
    Manufacturer:  System manufacturer
    Model:  System Product Name
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2712 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
    
Video Card:
    Driver:  Intel(R) HD Graphics 530

    DirectX Driver Name:  igdumdim32.dll
    Driver Version:  20.19.15.4463
    DirectX Driver Version:  20.19.15.4463
    Driver Date: 25 May 2016
    OpenGL Version: 4.4
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: Intel(R) HD Graphics 530
    VendorID:  0x8086
    DeviceID:  0x1912
    Revision:  0x6
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                            53.1cm x 29.9cm  (60.9cm diag)
    Primary Bus Type Not Detected
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Headphones (3- Astro MixAmp Pro
    
Memory:
    RAM:  8072 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Media Type:  Undetermined
    Total Hard Disk Space Available:  1067837 Mb
    Largest Free Hard Disk Block:  818519 Mb
    OS Install Date: Jan 01 1970
    Game Controller: None detected
    VR Headset: None detected
    
`

**Comment by kisak-valve** [comment]
@mitchcliff123 The commentary volume is controlled by the music volume (from https://www.reddit.com/r/tf2/comments/32481w/i_cant_hear_the_developer_commentary_over_the/), can you confirm this is not set low?

**Comment by mitchcliff123** [comment]
It is set to low, thank you for helping. It would be good though if there was something saying that.
