### ISSUE TITLE
[TF2] Scoreboard (supposedly) not tracking kills correctly 

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2096]
I was playing on `pl_thundermountain` (in Casual mode) and I noticed that I had gottan a kill (it appeared in the killfeed)
However upon pressing tab, my kill count was not updated. Important to note that I am using a custom HUD, so I'll ask the creator as soon as I can in case the issue is on that side. The HUD:
http://huds.tf/forum/showthread.php?tid=276
Here's the console showing the Iron Bomber kill I got and the stats displayed on the HUD:

![20170117193015_1](https://cloud.githubusercontent.com/assets/24685208/22036161/d7f1011e-dcf2-11e6-8f07-0b0320eacf3c.jpg)
![20170117193018_1](https://cloud.githubusercontent.com/assets/24685208/22036166/da9d4896-dcf2-11e6-8958-179f9117a1a9.jpg)

System information
https://gist.github.com/hahagoni/359a2fdae5ee57393842558bef33e7de

**Comment by agrastiOs** [comment]
Wasn't it a Dead Ringer Spy?

**Comment by hahagoni** [comment]
Not sure, I think it was a sniper, but does the console show dr feigns as normal kills?

**Comment by agrastiOs** [comment]
I don't know, but probably

**Comment by Wasmanr2** [comment]
It was a DR spy man. Look at your console feed.

It said "My bad"(you) killed SADOOM with iron_bomber (in that second he dr'ed)

Then he probably run away while he was in dr to the solly which and dr'ed again.

As you can see as WILDFIRE killed SADOOM with tf_projectile_rocket.

Then after his dr run out the spy named SADOOM finished off the soldier with his diamondback.

As you can clearly see it in the console: "SADOOM killed WILDFIRE with diamondback (crit)"

And also why do you even report a HUD bug when its a bug from a custom HUD. 
(P.S im using custom HUD too, never had a problem with kill tracking)
o.o

Its not the work of the tf2 devs to fix custom HUD bugs man.

Maybe you should close this as its not a bug that is affecting default tf2 HUD.
Dunno

**Comment by hahagoni** [comment]
Closing per last comment
I will be reopening this issue when further data is gathered
