### ISSUE TITLE
[TF2] Teammate names and health visible with mp_fadetoblack

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2098]
When using `mp_fadetoblack`, after the player dies and sees the killcam, the camera fades to black,
but the player can still see teammates' names and health bars present above the player outlines.

**Comment by Tiagoquix** [comment]
OP, does this still happen?

Also, try `mp_forcecamera 2` in conjunction with `mp_fadetoblack 1` and see if it fixes the issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.
