### ISSUE TITLE
S3TC and pulseaudio needed for TF2

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#21]
Issue transferred from ValveSoftware/steam-for-linux#57
@xpressrazor posted at 2012-12-20T04:27:55Z:

Note from jljusten: Removed Intel drivers label (S3TC portion considered solved)
Note from jljusten: Added Audio label (BTW, Mailaender's note below seems helpful)

Can not start TF2 without enabling S3TC and pulseaudio for SDL_AUDIODRIVER as 

export force_s3tc_enable=true SDL_AUDIODRIVER=pulseaudio

model name  : Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
Graphics : Intel HD 3000
OS : Ubuntu 12.04 64bit
Drivers upgraded using x-swat

**Comment by kisak-valve** [comment]
Closing as SDL2 has a sensible fallback layout for audio and S3TC is a mesa has a known additional dependency to provide this functionality.

**Comment by Mailaender** [comment]
We also documented the workarounds: https://en.opensuse.org/SDB:Team_Fortress_2#Troubleshooting
