### ISSUE TITLE
[TF2] [Feature Request] Give party members a choice to disconnect with party leader in Casual

### ISSUE THREAD

**Issue by doublah** [ValveSoftware/Source-1-Games#2101]
An extra feature request to #2027 .

Party leaders should be able to disconnect and go back to the party screen for Casual with their party members still there (covered in #2027 )
This is specifically requesting in addition to this an on screen option to appear for other party members to either disconnect and go back to the party screen with the other party members or leave the party and stay in their current connected game.

**Comment by hahagoni** [comment]
I think this was the case until map voting was added

**Comment by Wasmanr2** [comment]
But this is sure something that need to be added back

**Comment by Wasmanr2** [comment]
With the new Party system in the JI update leaders can now stay and also disconnect with their team without leaving the team or leaving the team trough the menu etc.
@kisak-valve  you may close this.

**Comment by kisak-valve** [comment]
Thanks, closing.
