### ISSUE TITLE
[TF2][Feature Request] Game mode specific map voting

### ISSUE THREAD

**Issue by Haze33E** [ValveSoftware/Source-1-Games#2142]
> Updated the logic used to pick the maps players can vote on in the end-of-match map vote on Casual servers to help maintain healthier game mode representation across regions
Casual servers were often rotating to unrelated game modes during votes, resulting in partially filled servers in certain regions

We're still getting options for voting for several game modes at the end of matches. From these patch notes it sounded like servers were going to be game mode specific again like they used to be in old pub servers. I'm pretty certain the problem with servers not filling up is being caused by servers changing game modes. Every time servers change game modes or maps people leave the server. Primarily they leave when a server changes game mode.  
  
Myself personally I pretty much only ever play payload. I leave when I see other game modes pop up in the map voting at the end of matches. Sometimes I stay if the server votes to stay on the same payload map we just played. The thing is I queue up for a specific game mode I don't care what other people queued for. If they want to queue up for 4 different game modes let them get put into a random game mode specific server. And once they get sick of that game mode they can leave the server and queue up again. Right now people are just being scattered across an unnecessary amount of servers. When a server changes game modes generally half the players or less actually stay in the server. So every time a server changes game mode it creates a half empty server that needs filling. But dozens of other servers could have just switched to the same game mode. So now you've got lots of half empty servers and lots of players re-queuing for the game mode they initially queued for, but had to leave because the server changed to a game mode they don't like. Having game mode specific servers would significantly cut down on queue times and you wouldn't have as much trouble back filling players who left the server.
  
**Edited:** to reflect changes from moderator.

**Comment by agrastiOs** [comment]
I think you misunderstood the patch note. They only updated the logic. If you read the Smissmas patch notes, it said that the maps are chosen depending on what the players did choose before queuing. My guess they updated the logic for it so it would prioritise related maps, if the players did choose some.

**Comment by Haze33E** [comment]
Yeah I know about that, but the second part of the patch notes made it seems like they made the servers game mode specific again. Servers not being game mode specific is why servers have been having issues with backfilling. When servers constantly change game mode it's just spreading players out across too many servers.

**Comment by FindTheBorealis** [comment]
As of the March 28, 2018 update you can only vote for the map you just played, and maps from the same game category. This has the effect of being only able to vote for maps of the same gamemode, except for the Misc and Halloween categories.

**Comment by kisak-valve** [comment]
Closing per "Updated the match-end map voting to only vote on maps for the current game mode (if you are playing Payload, you will only vote on Payload maps)" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update.
