### ISSUE TITLE
[TF2] VAC banned users connecting to Valve servers

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2146]
Users that received a VAC ban in Team Fortress 2 can join official MM servers by repeatedly spamming the rejoin button.

[A banned player joining a Valve bootcamp server](https://youtu.be/S3XJoDvpPUM?t=2m15s)

**Comment by Haze33E** [comment]
Yeah cheaters and vac banned people are just running amok without a care in the world. There's so many cheats for TF2 now it's ridiculous. I really wish the Devs would add another anti-cheat or two like BattlEye and or FairFight and start doing hardware ID bans. The once in a blue moon VAC ban waves don't mean much in a free to play game.

**Comment by kisakvalve** [comment]
Good day, I've received word from the VAC team that this is intentional and not open for discussion on Github.

In general VAC issues are not handled on Github in any capacity and further issue reports on this may result in being banned from the Valve Software issue trackers.

**Comment by agrastiOs** [comment]
This is probably fixed from the many matchmaking and VAC updates since 2017-2-15

**Comment by kisak-valve** [comment]
Closing per the last comment.
