### ISSUE TITLE
[TF2][Feature Request] Update the MvM UI

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2147]
The Meet your Match update introduced casual and competitive matchmaking with newer-looking, similar UI that was based on the MvM one.
MvM however has yet to receive a UI upgrade from the current, dated looking one and it would also make the menus more consistent. 
This is a low-priority request as the gamemode hadn't gotten major content updates for a long time, so there aren't many people that would use that'd use it.

**Comment by FindTheBorealis** [comment]
The MvM UI was updated like the rest of the matchmaking UI in the Jungle Inferno Update, although I don't think the tour/mission picker was changed.

**Comment by agrastiOs** [comment]
The whole UI was changed. @kisak-valve feel free to close this.

**Comment by FindTheBorealis** [comment]
I meant I think this part was taken from the old UI, but yeah the rest was changed.
![image](https://user-images.githubusercontent.com/24868101/32396350-d2161212-c0b2-11e7-8af7-7a86793d9469.png)

**Comment by kisak-valve** [comment]
Thanks, closing per the discussion.
