### ISSUE TITLE
[TF2] Low Populated games after a map vote still remains a problem.

### ISSUE THREAD

**Issue by VirtualSoda** [ValveSoftware/Source-1-Games#2149]
I know this isn't a bug, but it's still a major problem for those who enjoy 12v12 matches.

**Comment by Haze33E** [comment]
Yeah I sent them an email like two months ago saying they need to make the servers game mode specific again to fix this issue. But instead they "updated the logic" which didn't do anything to fix the issue. Servers are still having issues filling up because they still keep changing game mode.

**Comment by kisak-valve** [comment]
I've adjusted the title of #2142 to try to better express the request on how to handle this issue. Closing in favor of that issue report.
