### ISSUE TITLE
[TF2] Cow Mangler should be crit boosted in Humiliation and when getting the Crits powerup in Mannpower

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2160]
The Cow Mangler has an attribute that it cannot be crit boosted. There should be these two exceptions. First, because in Humilation you already won; no need for "balance", having no crits. Second, the Crits powerup in Mannpower is intended to work for all weapons: it's made so the losing team can get out of spawn, and try to get revenge on the enemy team.

**Comment by kisak-valve** [comment]
Possibly related to #2152.

**Comment by agrastiOs** [comment]
Closing due to this having been fixed as of the Jungle Inferno Update, thanks.
