### ISSUE TITLE
[TF2] In Casual the losing of the round voice line incorrectly plays for RED if BLU captures one point but loses in Payload

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2172]
Players might incorrectly say lines that they lost but will try to win the second round if BLU captures only one point and loses.

**Comment by hahagoni** [comment]
These are the `cm_[class]_pregamelostlast` lines

**Comment by agrastiOs** [comment]
Might be fixed? Has anyone experienced this recently?

**Comment by kisak-valve** [comment]
Closing per the last comment.
