### ISSUE TITLE
[TF2] Panic Attack on Pyro has a visible floating shotgun shell in the loadout screen.

### ISSUE THREAD

**Issue by Crostil** [ValveSoftware/Source-1-Games#2181]
[Screenshot 1](https://i.gyazo.com/8adf826cfbf688c1fabc98e70d7e4d36.png)
[Screenshot 2](https://i.gyazo.com/08998dc7f01b4e2565b80d655bf34f16.png)

I found this bug while making a custom Team-Colored panic attack skin. I am sure this is not my own fault, because i removed all mods in the tf/custom folder and verified my TF2 game files. 2 of the game files had to be retrieved, but the bug was still there. Thank you for reading this if you did. Please tell me if you require more information.

Also, if you're still rewarding people with hats or items for finding and submitting bugs to you, please discuss that with me at my email; jonathanclaerr@att.net 

P.S.: I have also sent this information about this bug to the TF team's email.

**Comment by kisak-valve** [comment]
Closing per "Fixed a visual artifact when inspecting the Panic Attack" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update.
