### ISSUE TITLE
[L4D2] invisible prop on the terminal

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#2182]
On dead air "The terminal" chapter, In order to proceed through the baggage handling area of The Terminal, Survivors must rev up a van crashed into the wall nearby, which will barrel through a locked gate.
Once the van is triggered it is not possible to walk anywhere in front on the van,even well in front of the van ,seem's like a Invisible dynamic prop on a track train,well ahead of the model,as it pushes you out of the way.
This stops players from getting to the coveted trash cans in the corner.
This can be replicated each and every time even after a restart.

**Comment by Treescrub** [comment]
If this behavior ends after the van has gone through the fence, then it's intended.

**Comment by 1157** [comment]
Prop_dynamic  I understand what you mean, but this is well ahead, 600 units or more in front of the van, no where near any possible interpenetrating entity issue.

**Comment by Treescrub** [comment]
Yes, but then it goes through the fence, which becomes non-solid a little before the van hits it.

**Comment by hesitationvr** [comment]
This invisible wall was put in place because originally you could stand in front of the fence where the van crashes and it would push you through to the other side, which in turn would allow you to avoid fighting the commons that drop from above and allow you to rush the rest of the map with most common stuck chasing after you

**Comment by hesitationvr** [comment]
It may only save you 5 seconds of waiting really but well, whats better, letting players squish themselves between a van and fence or just repel players from that section once the van is triggered for 5 seconds

**Comment by 1157** [comment]
It hackish at best and not realistic, Having a invisible brush parented to prop physic's pushing players out of the way? you could hold them there with many other things that can be seen IE electric box sparking triggering a 200 hp  trigger_hurt if they try to sneak by early.Really does·n't matter only go and tf2 is getting any kind of fixes, every other game is and has been abandoned.

**Comment by hogsy** [comment]
Adjustments for the sake of gameplay don't have to be realistic, and to be quite honest I think Valve have probably gone the best route without having to dramatically change things.

An electric sparking box that instantly downs the players probably makes even less sense as it's a gameplay element not used in any other Left 4 Dead campaigns to my knowledge - Valve would need to introduce environmental hints to ensure players understand this electric box is going to hurt them and then they would need to do extensive play testing, any mistakes players make towards this hazard are going to be harsh by your suggestion.

This "hack" is definitely an easier solution and I don't really see why this is even worth discussing considering Valve aren't going to change it, there's no reason for them to do so.

**Comment by 1157** [comment]
Huh? 
"An electric sparking box that instantly downs the players probably makes even less sense as it's a gameplay element not used in any other Left 4 Dead campaigns to my knowledge - Valve would need to introduce environmental hints to ensure players understand this electric box is going to hurt them and then they would need to do extensive play testing, any mistakes players make towards this hazard are going to be harsh by your suggestion

They would need to have players understand that a sparking box will shock them?

They do things like this that start up a "No mercy" game and at the finale jump off roof ---game over
There is no hints or warning that jumping off roof will cause your player death.
