### ISSUE TITLE
[TF2] Inconsistent naming of Festive weapons

### ISSUE THREAD

**Issue by DrinkerOfCoke** [ValveSoftware/Source-1-Games#2184]
Basically, the naming scheme for Festive weapons with Killstreak Kits attached to them differs between the 2011-2014 weapons and the 2015-2016 weapons.

The 2011-2014 Festive weapons follow this naming scheme:

(Strange Prefix) (Killstreak Prefix) Festive (Weapon name)

For example, Strange Specialized Killstreak Festive Medi Gun

However, the 2015-2016 Festive weapons have a different naming scheme altogether:

(Strange Prefix) Festive (Killstreak Prefix) (Weapon Name)

For example, Strange Festive Specialized Killstreak Quick-Fix

The issue probably stems from the fact that the 2015-2016 Festives are pre-existing weapons with a Festivizer applied to them and the Festivized item attribute, instead of being all new weapons in the schema like the old Festive weapons.

![festive](https://cloud.githubusercontent.com/assets/25768465/23646387/4f00f9c0-0319-11e7-9e62-78d701cd489f.png)

**Comment by FindTheBorealis** [comment]
As of the Jan 4, 2018 [update](http://www.teamfortress.com/post.php?id=36096) festivised weapons say festivised instead of just festive, fixing this inconsistency.

**Comment by kisak-valve** [comment]
Closing per @FindTheBorealis's comment.
