### ISSUE TITLE
[TF2][BUG] OSX users can't join any server after 3/14 update

### ISSUE THREAD

**Issue by NeoDesignBill** [ValveSoftware/Source-1-Games#2197]
Here we go again - the lowly Mac user...

- Can't join Casual or Community servers. It offers to blacklist the server, then after that it says "server uses different class tables". 
- Complete crash (exit to desktop, no messages) when trying to start a practice or self server.

(OSX 10.11.6 here)

**Comment by NeoDesignBill** [comment]
WORKAROUND: 
In Steam UI 
-->Library
-->Right click on Team Fortress 2, select Properties 
-->Betas tab 
-->Select 'previous - The Previous Release'

Seems to work for now.

**Comment by kisak-valve** [comment]
Looks like the 2017-03-14 TF2 update was rolled back. If this is still an issue after the next update, let me know and we can re-open.
