### ISSUE TITLE
[TF2] r_drawclipbrushes 2 crashes game

### ISSUE THREAD

**Issue by FamesGER** [ValveSoftware/Source-1-Games#2200]
So while going over some maps I tried to use the r_drawclipbrushes 2 command and everytime I execute it, my game straight up crashes.
Edit: This didn't happen during the beta. During the beta the command didnt even work; it didn't show the brushes.

**Comment by kisak-valve** [comment]
Hello @FamesGER, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Reproduced on gentoo linux. The game generated:
```
tcmalloc: large alloc 1207959552 bytes == (nil) @ 
Out of memory or address space.  Texture quality setting may be too high.
```
Along with CrashID=bp-f506a18b-377c-41f1-a49f-411112170315
([crash_20170315101025_1.dmp.zip](https://github.com/ValveSoftware/Source-1-Games/files/844796/crash_20170315101025_1.dmp.zip))

**Comment by FamesGER** [comment]
[crash_hl2.exe_20170315153609_1.dmp.zip](https://github.com/ValveSoftware/Source-1-Games/files/844844/crash_hl2.exe_20170315153609_1.dmp.zip)
[Specs](https://gist.github.com/FamesGER/fdcbee6cb45b5f898e4fa7d65f6e99fc)

**Comment by FamesGER** [comment]
Seems to be fixed now

**Comment by kisak-valve** [comment]
Looks like the 2017-03-14 TF2 update was rolled back. If this is still an issue after the next update, let me know and we can re-open.
