### ISSUE TITLE
[TF2] Wrong voice lines played when losing comp mmr

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2208]
No matter the outcome of a game, the administrator will always use the 'positive' voice lines
[Edit] this is still present after the [March 28, 2018](http://www.teamfortress.com/post.php?id=38643) update

**Comment by agrastiOs** [comment]
@kisak-valve No longer the Administrator says only the 'positive' voice lines. Having played comp, Administrator now says the negative voice lines if your team loses. This can be closed.

**Comment by kisak-valve** [comment]
Thanks, closing per the last comment.
