### ISSUE TITLE
[TF2] Fix mat_phong 0 issues

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2213]
Request transferrred [from /r/tf2](https://redd.it/617wfv)
The game would look a lot better on worse computers that their user decided to disable this and would provide a more consistent look of the game (for instance on video streaming sites such as youtube, twitch etc).
Major issue includes the bonesaw, butterfly knife, MvM upgrade stations and australium weapons.

**Comment by kisak-valve** [comment]
Hello @hahagoni, this issue is already being tracked at #2087. Closing as a duplicate.

**Comment by hahagoni** [comment]
Oh, I forgot about that one, thanks for the heads up.
