### ISSUE TITLE
[TF2] Contract drawer UI bug

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2237]
When opening the contract drawer in-game (default key F2) in matchmaking games the match status
HUD disappears. The two timers in KOTH games will stay, but that seems to be the only exception.
Example:
![image](https://cloud.githubusercontent.com/assets/24868101/25149809/4feecf18-2445-11e7-9d6a-efdd15cc0053.png)

**Comment by hahagoni** [comment]
Regular, non-matchmaking games are affected aswell, they will have their round timer removed when opening the contract drawer

**Comment by FindTheBorealis** [comment]
Closing due to the contract drawer being replaced with the ConTracker in the Jungle Inferno Update.
