### ISSUE TITLE
[HL2DM PIPE SERVER] Ignoring unreasonable position...

### ISSUE THREAD

**Issue by sosi-deadeye** [ValveSoftware/Source-1-Games#224]
I'm getting continuously following console spam:

Ignoring unreasonable position (0.000000,0.000000,-43719604.000000) from vphysics! (entity weapon_357)
Ignoring unreasonable position (0.000000,0.000000,-43729560.000000) from vphysics! (entity weapon_357)
Ignoring unreasonable position (0.000000,0.000000,-43739512.000000) from vphysics! (entity weapon_357)
Ignoring unreasonable position (0.000000,0.000000,-43749468.000000) from vphysics! (entity weapon_357)
Ignoring unreasonable position (0.000000,0.000000,-43759424.000000) from vphysics! (entity weapon_357)
Ignoring unreasonable position (0.000000,0.000000,-43769380.000000) from vphysics! (entity weapon_357)
Ignoring unreasonable position (0.000000,0.000000,-43779332.000000) from vphysics! (entity weapon_357)

ServerType: Vserver (OpenVZ)
Distribution: Debian 6.0.7
Kernel: Linux 2.6.32-5-openvz-amd64 #1 SMP Sun Sep 23 11:32:18 UTC 2012 x86_64
CPU: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
MEM: 15626MiB physical Ram free

No failcounts in /proc/user_beancounters

 ldd -v /lib32/libc.so.6 
        /lib/ld-linux.so.2 (0xb771e000)

```
    Version information:
    /lib32/libc.so.6:
            ld-linux.so.2 (GLIBC_PRIVATE) => /lib/ld-linux.so.2
            ld-linux.so.2 (GLIBC_2.3) => /lib/ld-linux.so.2
            ld-linux.so.2 (GLIBC_2.1) => /lib/ld-linux.so.2
```

Gameserver Information:

status
hostname: Linux-Gamers by ******
version : 1702177/24 5240 secure
udp/ip  : 37.114.54.250:27015  (public ip: 37.114.54.250)
map     : dm_lockdown at: 0 x, 0 y, 0 z
players : 0 (16 max)

 userid name                uniqueid            connected ping loss state  adr
version
Protocol version 24
Exe version 1702177 (hl2mp)
Exe build: 18:44:10 Mar 13 2013 (5240) (320)

Startcommand: ./srcds_run -game hl2mp -maxplayers 16 +map dm_lockdown

**Comment by XxTWDxX** [comment]
I have the same problem too! I reloaded the map a lot times and still happening. I have no clue how to fix it. I need help please very apprecited!

**Comment by kisak-valve** [comment]
Closing as there is nothing actionable in this issue report.
