### ISSUE TITLE
[TF2] [Feature Request] Option to choose default weapon slot for Medic and Spy

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2240]
The Medic spawns holding his primary weapon, when the Mediguns are the core of the class, which
may confuse new players, and some players may wish to have the Spy spawn holding a revolver.

**Comment by kisak-valve** [comment]
Hello @FindTheBorealis, I think it's more appropriate to switch the existing issue report at #1767 to a feature request. Closing as merged.
