### ISSUE TITLE
[TF2] Voice chat no longer works in TF since mid-april update

### ISSUE THREAD

**Issue by ocedalv** [ValveSoftware/Source-1-Games#2241]
Voice chat stopped working for me since an update was issued to TF2 in mid-april (after april 10, can't be exactly sure). This is NOT a hardware issue, since other voice chat software work without issues (Discord, Skype, TeamSpeak, Steam). This is an issue introduced with a recent update.

Since voice chat no longer works, I'm not able to hear or talk to anyone. This error ALWAYS shows in the game console when I open settings: "Unable to load voice codec 'vaudio_celt'. Voice disabled.".

I already verified the game files (multiple times), tried redownloading the entire BIN folder. I also tried changing the default recording device from my USB headset (Logitech G430) to the onboard Realtek one, and no change. I also tried changing ports and disconnecting the USB headset but the issue persists.

Other source engine games that use the CELT codec (CS: GO, for instance) have no issues.

(IF I was to take a guess I'd point to Miles Sound System's inability to load the voice DLL codecs. If I replace MSS files from TF with the ones from CS:GO, voice starts working again).

Thanks for any help.

![error_console](https://cloud.githubusercontent.com/assets/15329810/25323150/dab7758a-2893-11e7-811c-6c4bd623aff2.jpg)

**Comment by kisak-valve** [comment]
Hello @ocedalv, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ocedalv** [comment]
Here it is:
https://gist.github.com/ocedalv/0e2b77e6c30ff998f992cf40128842b0

**Comment by ocedalv** [comment]
Here is another one with my system's MSINFO32 dump:
https://gist.github.com/ocedalv/2c14b6e50e7bdf408b094b9e6b5f3100

**Comment by Nephyrin** [comment]
It would be useful to try setting sv_voicecodec to `steam` prior to testing voice and seeing if this has any effect.  Launching the game with `-default` in your command line options would also rule out any configuration changes that may be culprits.

**Comment by ocedalv** [comment]
@Nephyrin It does - voice starts working. But as soon as I join a server voice stops working again, since all valve servers default to the CELT codec.

I have steam cloud disabled. I also tried removing the entire CFG folder, and verifying the game to download the stock CFGs. Still doesn't work.

**Comment by Wasmanr2** [comment]
Uhm is there any reason why your voice transmit volume is at 0 @ocedalv  ?
And maybe try to write in the console "differences" (without quotes) to see which commands are not default.
Check if those commands are set to that values:
sv_voiceenable 1
voice_enable 1
sv_use_steam_voice 1
voice_inputfromfile 0
voice_forcemicrecord 1

And check your cfg folder if autoexec is still there. 
Double check is better then checking 1 time.

**Comment by ocedalv** [comment]
> Uhm is there any reason why your voice transmit volume is at 0 @ocedalv ?
And maybe try to write in the console "differences" (without quotes) to see which commands are not default.
Check if those commands are set to that values:

Like I said in the OP, voice gets disabled AFTER game startup, as soon as I open options or join a game. I have tried MANY types of voice commands on my CFG, and none of them make it work.

**Comment by Wasmanr2** [comment]
You mentioned that if you replace the MSS files from TF with the ones from CS:GO then it starts to working again?  
But i guess that just works until you play the game ?
Also be sure that you didn't forget to remove -default from the launch options.

(Why even CELT, i mean CELT got merged to Opus and CELT got abandoned from the dev team).

**Comment by ocedalv** [comment]
> You mentioned that if you replace the MSS files from TF with the ones from CS:GO then it starts to working again? But i guess that just works until you play the game ? Also be sure that you didn't forget to remove -default from the launch options.

No, it works works, as in I can hear people and speak to them, like before. These are the files I took from CS: GO:

`mss32.dll
mssdolby.flt
mssds3d.flt
mssdsp.flt
msseax.flt
mssmp3.asi
msssrs.flt
vaudio_celt.dll
vaudio_miles.dll
vaudio_speex.dll`

Also, to clarify, NONE of the VAUDIO_*.dll voice codecs work. It fails to load all of them. That includes SPEEX and MILES.

**Comment by Nephyrin** [comment]
@ocedalv Does this work for you if *just* vaudio_celt is brought over from CS:GO?  I wouldn't expect MSS files to affect this.

Today's optional TF2 update added some more debugging information to the "Unable to load voice codec" message, so if you are still hitting this, it would be helpful to know what that says.

**Comment by ocedalv** [comment]
@Nephyrin No, it does not. That's what prompted me to try and copy all files from MSS.

I'll do that as soon as I get home? Are there any specific steps I need to take in order to invoke the debugging messages?

Thanks!

**Comment by ocedalv** [comment]
So, the console info changed to this:
`Unable to load voice codec 'vaudio_celt'. Voice disabled. (module 0, iface 0, codec 0)`

**Comment by FindTheBorealis** [comment]
@ocedalv, could this be retested? The Jungle Inferno update modified Steam voice to be the default, with 
the higher quality Opus codec, and also added a higher bitrate option for the CELT codec.

**Comment by kisak-valve** [comment]
Closing pending feedback on the last comment.
