### ISSUE TITLE
[TF2] [Feature Request] Option to enable beta muzzleflashes

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2246]
Early TF2 trailers featured weapons with cartoon-like muzzleflashes, some may think these fit the TF2 style better than the ones at release, and since they are 2D images, may give a performance boost.

**Comment by hahagoni** [comment]
This is very unlikely to happen as the dev team has been aiming for a more consistent look of the game, at least that's what the Meet your Match costumization changes suggest.
