### ISSUE TITLE
[TF2][Feature Request] Increase the maximum allowed download speed for all servers

### ISSUE THREAD

**Issue by Wasmanr2** [ValveSoftware/Source-1-Games#2247]
If a dedicated server has set an unlimited amount for bandwhidht downloading custom materials, maps,  models, sounds, still seems to download with low speed technicly with 200 kbytes/s even with fastdl servers.

Is it even possible to remove the download cap from the game/or setting it slightly higher?

Is there any speed cap/command for the client/server ?

If, yes i would like to know then i could close this issue.

If, no players would gladly like to download maps,etc.. faster of the cost of the bandhwidht, so raising the cap to somewhat like higher speeds would shorten the time to take to download custom stuff for clients.

(FYI: My network speed is 24,6mbytes/s | 200mbit/s)
(This problem is only related to TF2 other programms or games don't have this issue)

**Comment by kisak-valve** [comment]
Typically FastDL is used with Source games to increase download rates, which offloads the transfer to a web server. Take a look at the FastDL section of https://steamcommunity.com/sharedfiles/filedetails/?id=151341897.

**Comment by Nephyrin** [comment]
When not using sv_downloadurl to provide assets, the built-in file transfer system is used (net_maxfilesize affects this).  This system is inline with game traffic and very limited.  Servers wanting to provide higher download rates should use sv_downloadurl or the maps workshop (which downloads from the Steam CDN).
