### ISSUE TITLE
[TF2] [Feature Request] Give the TF2 soundtrack as a Steam DLC

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2249]
Several other Valve titles like Half-Life and Portal feature their soundtracks as a free DLC. This could increase awareness of TF2's soundtrack and its physical release.

**Comment by agrastiOs** [comment]
The DLC has been released. http://store.steampowered.com/app/629330/Fight_Songs_The_Music_Of_Team_Fortress_2/?snr=1_5_9__405 @kisak-valve you may close this.

**Comment by kisak-valve** [comment]
Closing per the last comment.
