### ISSUE TITLE
[TF2][Bug] Rescue Ranger bolts hover in the air if a sentry gun is moved

### ISSUE THREAD

**Issue by CommodoreKong** [ValveSoftware/Source-1-Games#2251]
If a sentry gun is moved after it was shot by a Rescue Ranger bolt the Rescue Ranger bolt will just hover in the air where the sentry gun used to exist. See screenshot:
![c9az2au](https://cloud.githubusercontent.com/assets/24358216/25645638/e5abbf3c-2f7d-11e7-90c9-fdc3c598ff79.jpg)

**Comment by hahagoni** [comment]
I believe that this is the case with all buildings

**Comment by FindTheBorealis** [comment]
This appears to be fixed, at least with the Rescue Ranger, though the bolts will be stuck on the wireframe blueprints when moving the buildings.

**Comment by agrastiOs** [comment]
@kisak-valve should be closed as it's fixed.

**Comment by kisak-valve** [comment]
Thanks, closing per the last couple comments.
