### ISSUE TITLE
[TF2] Disconnecting from casual via console or server browser displays false 'penalty'

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2264]
Casual mode was introduced on July 7, 2016
In order to help out the backfilling system in resolving unbalanced games, a _leaver penalty_ was put in place

On July 22, it's been removed from the game

> Matchmaking Update
> July 22, 2016 - TF2 Team
> Abandon penalties have been removed, which means players can come and go as they please. 

However, using the developer console to diconnect from a game/ join a 3rd party server via console or server browser will trigger the old prompt and can disable the matchmaking buttons in the main menu (Casual, Competitive and Mann vs Machine)

The false penalty appears to come delayed and display when the player is joining or is already in a game.

![20170503193819_1](https://cloud.githubusercontent.com/assets/24685208/25817017/4d7a88ee-3426-11e7-9f26-4ded558d7847.jpg)

Uncut footage [here](https://youtu.be/HmgcT57x_Eo)

**Comment by agrastiOs** [comment]
Duplicate of #2090. However, this one is much more detailed.

**Comment by hahagoni** [comment]
Forgot to check, thanks for mentioning @agrastiOs
