### ISSUE TITLE
[Linux,Counter-Strike: Source] Mic not working when sv_use_steam_voice is set to 0

### ISSUE THREAD

**Issue by grubsteak** [ValveSoftware/Source-1-Games#2269]
Microphone works fine when using sv_use_steam_voice 1, but when it's disabled the microphone doesn't work at all on Linux.

Any help/tips would be appreciated.

Running Debian 3.16.39-1 (2016-12-30) on 64bit

**Comment by grubsteak** [comment]
I believe I am experiencing the same issue from ValveSoftware/Source-1-Games#33 if that helps any

**Comment by OlegMaltzev** [comment]
https://steamdb.info/forum/1491/counter-strike-source-and-other-source-engine-games-prerelease-update-for-31417
We are waiting for the release ...

**Comment by kisak-valve** [comment]
Closing as this convar has been removed in the [2017-06-15](http://store.steampowered.com/news/30120/) CS:S update.
