### ISSUE TITLE
[L4D2] [BUG] Developer Console Server Browser Covering Dialog Glitch

### ISSUE THREAD

**Issue by CanadianJeff** [ValveSoftware/Source-1-Games#2274]
What I find is if I have developers console or server browser open and join a game to get kicked from the game or go idle and get disconnected it will drop back to server browser or developers console but I cant use them because the message box that I have been kicked is open and being covered by the console or browser so I can not click the OK button or do anything except to exit L4D2 and restart it.

**Comment by Treescrub** [comment]
I believe a way to get out of it is to press the dev console key (~ by default) and then pressing enter, or the other way around.

**Comment by hashar** [comment]
My workaround is to have the console and server browser on the sides of the screen. This way on disconnection the popup in the background would be visible and then you can click the OK button to dismiss it.

**Comment by CanadianJeff** [comment]
this bug report is really old as for no one really giving a shit gonna close it as I no longer play L4D2 anyone can feel free to reopen
