### ISSUE TITLE
Team Fortress 2 freezes on load screen with -novid

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Source-1-Games#2280]
These comments are from https://github.com/ValveSoftware/steam-for-linux/issues/2294.

***
@Polochamps commented on 2015-01-27T00:25:19

I had the same error you mentioned but only appears when launching the game.
I fixed it by removing the "-novid" in launch options

on 
__GL_THREADED_OPTIMIZATIONS=1 %command% -novid

into
__GL_THREADED_OPTIMIZATIONS=1 %command% 

***
@hhiru commented on 2017-05-25T12:35:39

I'm having the same problem. Using Ubuntu Gnome and the -novid launch option

OS: Ubuntu 17.04 zesty
Kernel: x86_64 Linux 4.10.0-21-generic
Resolution: 1920x1080
CPU: Intel Core i7-6700K CPU @ 4.2GHz
GPU: GeForce GTX 980 Ti
RAM: 3803MiB / 15997MiB
nVidia Drivers: 375.39

**Comment by hhiru** [comment]
Updated nVidia drivers to 375.66
Same problem.

**Comment by MetalNeo** [comment]
I am running into this same issue with the Steam Deck. Issue is occurring with stock TF2 settings and no other changes than `-novid`. Although, the game does silently crash after freezing up.

**Comment by kisak-valve** [comment]
Closing as outdated.
