### ISSUE TITLE
[TF2] Func_lod Pomson, Bison and Wrap Assasin collision issues

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#2281]
If `func_lod` is applied to an entity, projectiles from the following weapons will collide with the bounding box (especially bad if the bounding box is large)

- Pomson 6000 (Engineer)
- Righteous Bison (Soldier)
- Wrap Assasin (Scout)

[Here's](https://youtu.be/-QKb9f6ApW4) a video demonstration with a carved brush
And here's a picture of how the map looks like in hammer
![func_lod](https://cloud.githubusercontent.com/assets/24685208/26459783/ee776cd6-4177-11e7-9996-dcff59d86de4.png)

I'd also like to note that the sparkle upon colliding is misplaced somewhere onto the `func_lod` sphere, but only with the Bison and Pomson.

[EDIT] [This](https://youtu.be/3D4VHbfUgQM) is how the collision is with normal brush (ie no collision occurs)

**Comment by 1157** [comment]
Did you try to set the key values?

Keyvalues
Disappear Distance <integer>
    Distance at which these brushes should fade out. 
Solid <choices>
    Set whether or not these brushes should collide with other entities.

        0 : Solid
        1 : Nonsolid

**Comment by hahagoni** [comment]
@1157
I only tested one disappear distance, can't remember what it was, but I will take a look at it after I have taken a sleep.
The issue only happens with solid entities, so things like fading bushes are safe to use in your map.

**Comment by kisak-valve** [comment]
Closing in favor of #2702 and because the reporting user has turned into a ghost.
