### ISSUE TITLE
[TF2] XBoX interface when controller attached

### ISSUE THREAD

**Issue by akuzia** [ValveSoftware/Source-1-Games#2292]
After recent update game always recognize Xbox gamepad. For example:
Different engi (combined F4+F5) and spy menus
Cursor dissapears, cl_software_cursor 1 - same story, but i can fastforward video in training via A button on gamepad, while select screen is on I can shoot via LMB
Other variation of XBox input, like weapon selection
etc.

All that behavior dissapears when I unplug XBox controller from USB. 

Both win and linux clients

**Comment by hahagoni** [comment]
I'd like to note that this was a result of a recent update to Steam, not to TF2 itself.
