### ISSUE TITLE
[TF2] Crash on load with Widevine error

### ISSUE THREAD

**Issue by zeflap** [ValveSoftware/Source-1-Games#2293]
Starting TF2 on my Debian 9 laptop produces the following crash every time I try starting it.
I'm using awesomewm if that matters at all.

https://gist.github.com/zeflap/a1ac566c2d2da4cb0c2b2fd00b33281f

**Comment by kisak-valve** [comment]
Hello @zeflap, I fired up TF2 with a fresh Debian 9 install on a terrible-spec laptop (800MHz dual core / nvidia 8400GS) and did not reproduce this issue. Did you install steam using the [Debian wiki](https://wiki.debian.org/Steam) instructions with the trivial adjustment for Debian 9? 

Please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by zeflap** [comment]
@kisak-valve I think this ends up being a case of #2212 / #1584 after researching the issue further.
