### ISSUE TITLE
On the server CS Go is not properly displayed the number of players

### ISSUE THREAD

**Issue by Legend161** [ValveSoftware/Source-1-Games#2295]
On the server CS Go is not properly displayed the number of players, a lot of occupied slots empty, but actually they are not, this problem on all servers of CS GO

**Comment by kisak-valve** [comment]
Hello @Legend161, let's track this CS:GO issue in the CS:GO issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1442.
