### ISSUE TITLE
Linux Random Crashes TF2

### ISSUE THREAD

**Issue by MrTorch** [ValveSoftware/Source-1-Games#2300]
Hello, I've been playing  the linux version of TF2 on Ubuntu 16.04 and in the beginning I never had any issues, but it slowly got worse and worse on crashing. Now if the map even finishes loading, I can usually get through about 10-20 minutes before the game crashes. I play mainly on 2fort and I noticed that if I go in water I get a massive fps drop. I do get other crashes unrelated to that though too and will crash just walking around on land sometimes. CPU is 6770HQ, GPU is Intel Iris Pro 580, 8gb ram. I've tried having the settings on high and low and combinations in-between and nothing seems to stop me from crashing. 

Here is my console.log file, not sure if that helps. 

[console.log.zip](https://github.com/ValveSoftware/Source-1-Games/files/1103442/console.log.zip)

Thanks!

Edit: Also, probably unrelated, I also get a crash when loading a map after the last one finished on the rare occasions I make it through a map. The reason given is "out of ram." This doesn't seem like a likely reason, when I run the game by itself with nothing but steam open and still get the same crash.

**Comment by kisak-valve** [comment]
Hello @MrTorch, this issue is being tracked at #2212. Closing as a duplicate.

**Comment by MrTorch** [comment]
That's only one issue, the other crash has even happened on just loading the game when it got to the main menu, so I think that's only part of the problem.

**Comment by kisak-valve** [comment]
Okay, can you please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, please include any CrashIDs or minidumps related to the issue.

**Comment by MrTorch** [comment]
Here's the gist: https://gist.github.com/MrTorch/1ab41912ae87de6edf5cf2f170ef1189

And I'm assuming these are the minidumps. 
[Dumps.zip](https://github.com/ValveSoftware/Source-1-Games/files/1103638/Dumps.zip)

**Comment by kisak-valve** [comment]
Thanks for attaching the info. Unfortunately, the attached minidumps are mangled or incomplete, so it's not immediately clear what's going on here.

**Comment by MrTorch** [comment]
Hm, well I'll play some more and upload some more and hope those are complete. Any suggestions on settings that are usually problematic I can turn off?

**Comment by MrTorch** [comment]
Finally got a readout during a crash. Not sure if this is related to memory or not.

![screencapture](https://user-images.githubusercontent.com/12021603/27571255-59389176-5ad2-11e7-88a8-5d5795affeae.png)

[dumps.zip](https://github.com/ValveSoftware/Source-1-Games/files/1104195/dumps.zip)

**Comment by MrTorch** [comment]
I upped my VRAM in the BIOS and the out of ram crash seems to have gone away, but the Vertex crash continues to happen and the random crashes that don't have logs and no pop-up box also still happen even on the main menu when I'm changing settings.

**Comment by kisak-valve** [comment]
#2234 is already open to track that vertex buffer issue.

**Comment by MrTorch** [comment]
Gotcha, is there a way I can try to debug the crashes that don't have a pop-up box?

**Comment by kisak-valve** [comment]
Hello @MrTorch, can you check if mesa 18.1.5 improves the situation?

**Comment by kisak-valve** [comment]
Closing presumed fixed in the video driver.
