### ISSUE TITLE
[TF2] Crash on connection

### ISSUE THREAD

**Issue by OctoNezd** [ValveSoftware/Source-1-Games#2301]
Game just crash when I try to connect to any server

I have tried removing configs, custom content, but game still crashes.

[Gist with System Information](https://gist.github.com/OctoNezd/7975195c8ad33eb5b18fb8803bf4a115)

**Comment by Wasmanr2** [comment]
Even if you remove your configs, the settings will be the same with configs unless you disabled steam cloud saving .
So try the launch option -autoconfig or -default so Tf2 sets all back to Default settings.

**Comment by OctoNezd** [comment]
I removed configs with steamcloud disabled and started game with -autoconfig option. It didn't help

Отправлено из ProtonMail mobile

-------- Исходное сообщение --------
Вкл 10 июл. 2017 г., 13:23, Wassy написал(а):

**Comment by ChampionCynthia** [comment]
First, please remove any **-autoconfig** launch option.

Then, please add the launch options **-condebug -console** using the game's _Properties_ window (**SET LAUNCH OPTIONS…**), then run the game. Once in the main menu, please type the command **developer 4** then **differences**.

Finally, try to join a server. Once the game has crashed, please get to your Team Fortress 2 directory (Right-Click on __Team Fortress 2__ in the __LIBRARY__, __Properties__, __LOCAL FILES__ tab, click on __BROWSE LOCAL FILES…__. Enter the __tf__ directory, and find the **console.log** file.

You may upload this file or open it using any text editor to copy-paste the content in a __gist__ or PasteBin.

**Comment by OctoNezd** [comment]
Weird. After doing all you said to me, game started connecting to servers normally...
Can this be xscreensaver issue? Cause everything I changed in my system before you said me to do that is removing xscreensaver
