### ISSUE TITLE
TF2 Hasn't Started for Me for Months

### ISSUE THREAD

**Issue by Nz17** [ValveSoftware/Source-1-Games#2317]
Unfortunately, Team Fortress 2 stopped running under Linux for me a few months ago when a new patch was released. I'm not sure when, so let's say around March 2017 or perhaps earlier. I was hoping it was a temporary situation, but even now, after all of the game's recent patches, TF2 won't run. I made no major changes to my Linux distro at the time of the original problematic update that could have caused this to occur. All TF2 files verify as correct through Steam. My other Source Engine and Gold Source Engine games still run perfectly fine under my Linux install (e.g. Portal 2, Left for Dead 2, etc.). TF2 still runs properly via Windows XP with all Windows and game patches applied on the same computer.

Steam Support directed me to here after I communicated my problem to them and informed them that I am running Debian Linux.

I have attached a log - this is from Steam from when I try to start TF2.

[steam_tf2_stdout_log-Nz17-2017-09-02.txt](https://github.com/ValveSoftware/Source-1-Games/files/1272594/steam_tf2_stdout_log-Nz17-2017-09-02.txt)

Also attached is a copy of my computer's specifications.

[tf2_crash_report-computer_specs-Nz17-2017-09-02.txt](https://github.com/ValveSoftware/Source-1-Games/files/1272595/tf2_crash_report-computer_specs-Nz17-2017-09-02.txt)

Please advise. Thank you.

**Comment by kisak-valve** [comment]
Hello @Nz17, at a glance these do not look healthy in your log:
```
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
```
```
AppFramework : Unable to load module datacache.so!
Unable to load interface VDataCache003 from datacache.so
```
The p11-kit error is during steam's startup, not the game, so it may be unrelated.

Can you try completely closing steam, then running `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal, and retesting the game. Additionally, if you can find any minidumps in `/tmp/dumps/` related to this issue, please include them in this issue report.

**Comment by Nz17** [comment]
Here's the logs and dumps I got when I tried to run TF2 with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`.

[crash_dumps-Nz17-2017-09-02.zip](https://github.com/ValveSoftware/Source-1-Games/files/1272630/crash_dumps-Nz17-2017-09-02.zip)
[sean_log.txt](https://github.com/ValveSoftware/Source-1-Games/files/1272631/sean_log.txt)
[sean_stdout.txt](https://github.com/ValveSoftware/Source-1-Games/files/1272632/sean_stdout.txt)

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by Nz17** [comment]
Pardon me, but I'm not sure what that means exactly.

Is there anything else I can provide which might help?

**Comment by kisak-valve** [comment]
I got TF2 on my Debian 9 testbox, which is also using nvidia 340.102, and it fired up without trouble.

Having both `<username>_log.txt` and `<username>_stdout.txt` in /tmp/dumps indicates that you've installed steam with the valve-provided steam package, while my test box has the distro-provided steam package. This is not indicative of a problem, just noting the difference.

Can you open a terminal and `cd ${HOME}/.local/share/Steam/steamapps/common/Team\ Fortress\ 2/bin && LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH" ldd datacache.so` and check if there are any lines with => not found?

If there's nothing missing there then the next step I would take in troubleshooting this issue would be to take ~/.local/share/Steam and ~/.steam and moving them somewhere safe, then re-bootstrap steam on the system and see if a fresh install of TF2 makes a difference. If that makes no difference, you can remove the new steam instance and move the folders back, or copy the steamapps folder into the new instance while steam is not running.

Beyond that we'll need to see if anyone else has had a similar experience or a TF2 dev has some ideas.

**Comment by Nz17** [comment]
I followed your instructions, and I checked my Steam library directories.  Strangely, TF2 is missing its datacache.so, but L4D2, Portal, and Portal 2 all have theirs.

The response to your command was `ldd: ./datacache.so: No such file or directory`

**Comment by Nz17** [comment]
Strangely, now when I try to verify the files, it says something like 948 files failed to verify, and now it wants to reload 7.6 GB.

**Comment by Nz17** [comment]
I'll update this thread/issue when the re-download completes.  Unfortunately, slow rural Internet speeds mean that it will be about three hours from now.

Thank you for all the help, by the way.

**Comment by Nz17** [comment]
Several hours later, once the download was complete, running TF2 resulted in... the download restarting.  For some reason, Steam didn't like those 7.6 GB, and it said it needed to re-download it all again.

This isn't the first time this endless loop of downloading has happened to me.  It's one of the reasons I gave up trying to fix this months ago.  Back then, a fresh install of Steam and TF2 did not solve the problem.  However, I'll try it again soon, and I'll respond with the results then.

**Comment by Nz17** [comment]
OK, moving ~/.local/share/Steam and ~/.steam and redownloading everything worked.  How strange.  I wonder why Steam has only had this problem with TF2 and none of the other games which my account has (both the not-running problem and the "endless" redownloading loop problem).

I'll try combining the good data downloads with the original Steam / SteamApps directories later and I'll report my results here.

**Comment by kisak-valve** [comment]
At this point it is clear this was an issue with steam, not the game. If you can figure out the difference between the steam instances that causes this behavior, please open a new issue report in the [steam-for-linux](https://github.com/ValveSoftware/steam-for-linux/) issue tracker.
