### ISSUE TITLE
All Source Games Crash A Few Minutes Into Gameplay

### ISSUE THREAD

**Issue by WizardCarter** [ValveSoftware/Source-1-Games#2320]
Title says it all, really. All of the Source Games I have (Portal 2, TF2, GMod) will start up fine and work for a couple of minutes before crashing. Launching Steam from the console reveals that all of the games crash due to a segmentation fault. I run UbuntuMATE 16.04  on a Lenovo Yoga laptop.

Specs: 
8GB RAM
2.5 GHz processor
Intel Graphics Card
256GB SSD (where I have my OS)
1TB External HDD (where all my Steam games are)

Edit: [gist link](https://gist.github.com/WizardCarter/cde61fb79143e2e8d67a72cf2a4ff5ca)
Edit 2: [Minidump](https://gist.github.com/WizardCarter/412da5a94a8801dc8d396cdb4b77221d)

I only added about half of the minidump because the rest was entirely the same thing.

**Comment by kisak-valve** [comment]
Hello @WizardCarter, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps (commonly found in /tmp/dumps/) related to this issue, please include them in this issue report.

**Comment by WizardCarter** [comment]
@kisak-valve Ok, updated original comment to include the information.

**Comment by kisak-valve** [comment]
There's a decent chance this is the same issue as https://github.com/ValveSoftware/csgo-osx-linux/issues/1509. Can you check dmesg and see if the gpu is resetting. You can also retest with MSAA 2x or switch to a mesa release before 17.2 and see if that makes a difference.

**Comment by WizardCarter** [comment]
Sorry it took me a while, got busy. I added the link to the minidumps. I wasn't able to locate any crash dumps. I tried using the multicore anti-aliasing settings, but it turns out all of my games were already using that setting. I didn't exactly understand what you meant by checking dmesg to see if the gpu was resetting. Will update again after I try downgrading mesa.

**Comment by WizardCarter** [comment]
Ok, so I tried switching to another Anti-aliasing setting and back to the one I have and everything works fine now (in TF2 at least). Will try other games in the morning ( and reopen if there's any issues). Otherwise, thanks for the help!
