### ISSUE TITLE
Team Fortress 2 crashing

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Source-1-Games#2330]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/5204.
@diamondburned posted on 2017-10-11T04:53:11:

* Steam client version (build number or date): 1.0.0.54-1, 1507158695, built Oct 4 2017, 22:37:25
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

Normally, I was able to play Team Fortress 2 on my machine. However, when I join a server, TF2 suddenly crash. Here's the crash log: https://dtf2second.ddns.net/dumps/

#### Steps for reproducing this issue:

1. Launch the game
2. Join a server
3. TF2 prints out crash dump at /tmp

**Comment by kisak-valve** [comment]
Hello @diamondburned, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

For reference, the attached minidump is a SIGABRT in linux-gate.so.

**Comment by diamondburned** [comment]
Here's the gist: https://gist.github.com/diamondburned/54db345779b005111947e4255c44e3cf

Also some more details: I tested this with my own servers. The servers which have sv_downloadurl set to a custom value and sv_allowdownload 0 crashes (which is weird because in LinuxGSM FastDL document, it said to set sv_allowdownload 0). Those that has sv_allowdownload 1 don't crash.

**Comment by Tiagoquix** [comment]
@diamondburned Can you retest with the new 64-bit binaries + Vulkan render?

**Comment by diamondburned** [comment]
Hi, unfortunately I won't have the hardware nor the server to test this. I'm not too sure what the issue was, but the 64-bit Vulkan version of TF2 has been far more stable and have not crashed once based on my recent plays!

Since this issue is very stale, I think it can just be closed.
