### ISSUE TITLE
[TF2] Changing screen resolutions is impacting the use of the main menu

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2336]
[TF2] Changing screen resolutions is impacting the use of the main menu.

After the Jungle Inferno Update I noticed switching between resolutions was not scaling the main menu properly.

Original Res:  1920 x 1080 - OK
Smaller Res:  1600 x 900 - Can't see the find game or quit game buttons
Larger Res:  2560 x 1440 - Screen is not fully used, menu is crowded in the upper left corner

Attached screenshots for reference.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 17.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.13.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11905000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) x86/MMX/SSE2
    Driver Version:  3.0 Mesa 17.2.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x5916
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5760 x 1800
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC3246

Memory:
    RAM:  15923 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  479190 Mb
    Largest Free Hard Disk Block:  79899 Mb
    VR Headset: None detected

Recent Failure Reports:

[Screenshot_2017-10-20_17-54-17.png.gz](https://github.com/ValveSoftware/Source-1-Games/files/1403560/Screenshot_2017-10-20_17-54-17.png.gz)

**Comment by nightsky30** [comment]
Also, it appears the scaling is only an issue when the game was loaded in one resolution and then switched to another while it is running.

If you:

Change the resolution so that buttons can't be seen
Alt+tab or otherwise minimize the game
Right click and then select close on the minimized window
Restart the game

The game will start in the newly applied resolution, scaled perfectly...until you change it again in game.

**Comment by nightsky30** [comment]
[Screenshot_2017-10-20_18-40-44.png.gz](https://github.com/ValveSoftware/Source-1-Games/files/1403618/Screenshot_2017-10-20_18-40-44.png.gz)
[Screenshot_2017-10-20_18-42-44.png.gz](https://github.com/ValveSoftware/Source-1-Games/files/1403619/Screenshot_2017-10-20_18-42-44.png.gz)

Uploaded two more examples because it appeared the second upload above failed.

**Comment by agrastiOs** [comment]
Not just on Linux. Can confirm it happens on Windows.

**Comment by FindTheBorealis** [comment]
From my duplicate issue:

The top game bar seems to never change size until a restart, but the find a game bar does change size if it's hidden during the resolution change.

Switching to 720p windowed from 900p fullscreen: [link](https://user-images.githubusercontent.com/24868101/32638398-b0479774-c584-11e7-8ba8-717edf04a59a.png)

And the reverse with the find a game bar out during the resolution change: [link](https://user-images.githubusercontent.com/24868101/32639248-9703d4e0-c588-11e7-8a5f-d255c3bb52b0.png)

**Comment by FindTheBorealis** [comment]
This has been fixed as of the 2017/12/01 update.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing per "Fixed the main menu not updating its layout after a resolution change" in the [2017-12-01](http://www.teamfortress.com/post.php?id=35157) TF2 update.
