### ISSUE TITLE
[TF2] Ammo/Health not respawning on Mercenary Park

### ISSUE THREAD

**Issue by CommodoreKong** [ValveSoftware/Source-1-Games#2344]
On the new map Mercenary Park there's a spot between the blu spawn and the first point where health and ammo don't seem to respawn after the first time someone picks them up. 

Here's a screenshot of the health/ammo location: [https://i.imgur.com/L3s8H2e.jpg](url)

**Comment by hahagoni** [comment]
Actually, it does work as intended. Capturing point A will prompt those pickups not to spawn anymore.

**Comment by CommodoreKong** [comment]
Yeah I found that out a couple of hours after I made this post. It's kinda weird, no other TF2 maps do that with health or ammo pickups. I'll go ahead and close this since it appears to be what's intended by the map maker.
