### ISSUE TITLE
[TF2] Contracker 4 billion Contract Points

### ISSUE THREAD

**Issue by baxter5469** [ValveSoftware/Source-1-Games#2347]
I was in a game yesterday on a valve server and when the game ended multiple people including me had their contracker upgraded to 4 billion contract points. I have contacted Steam Support and they told me to post the issue here. Hope this issue is resolved.

-Thanks
Andrew

**Comment by baxter5469** [comment]
Here is my inventory link if you need to see the contracker: https://steamcommunity.com/id/baxter5469/inventory#440

**Comment by kisak-valve** [comment]
Per "Fixed a bug related to the ConTracker not displaying the correct number of earned contract points" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update, please retest this issue.

**Comment by agrastiOs** [comment]
@kisak-valve It is indeed fixed.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
