### ISSUE TITLE
[TF2] Console starts in the background.

### ISSUE THREAD

**Issue by ChampionCynthia** [ValveSoftware/Source-1-Games#2350]
Hello.

Since the Jungle Inferno update, the developer console is hidden behind the main menu's elements (I can only see it while the game loads the main menu).

I am running:
Debian GNU/Linux unstable (sid)
GPU: NVIDIA GeForce G210
  Driver: NVIDIA Legacy Driver 340.104 (non-free)
Using Xorg (X Server) with GNOME 3.26.1

Thank you.

**Comment by Wasmanr2** [comment]
Also happening on Windows platforms.

**Comment by FrankenFuchs** [comment]
Same. It's painful.

**Comment by kisak-valve** [comment]
Per "Fixed the console, server browser and options menus sometimes going behind the main menu and becoming unclickable" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update, please retest this issue.

**Comment by hahagoni** [comment]
Appears to be fixed.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
