### ISSUE TITLE
Duped contract weapons?

### ISSUE THREAD

**Issue by alexavil** [ValveSoftware/Source-1-Games#2351]
Yesterday I completed a Banana contract. But when I looked in my inventory to equip it, I had this...

![20171022213607_1](https://user-images.githubusercontent.com/32246131/31883713-cac1f1b2-b7fb-11e7-9663-df3f46204c17.jpg)

How is this even possible?

**Comment by alexavil** [comment]
Here's the link
http://steamcommunity.com/id/nomercyforkap/inventory/#440_2_6261547146

**Comment by nightsky30** [comment]
I've also had this happen with the dragon's fury.

**Comment by cinister** [comment]
One is the reward for completing the contract, the other is a loaner item. The loaner will [expire on November 12](https://puu.sh/y5LaU/22fa7c5ff7.jpg) or disappear before then if you switch to a different contract.

**Comment by alexavil** [comment]
But shouldn't it be taken away instantly?

**Comment by nightsky30** [comment]
I thought it would have disappeared instantly upon fulfillment of contract and receipt of the rewarded, permanent, non-tradable version of the item.  Or even just flip a flag variable in the item's properties which makes it your permanent item vs a loaner, and avoid any duplication of items at all...But we have no way of knowing how objects are created, or why Valve chose to do what they did behind the scenes.  I guess the expiration is good enough, meh.
