### ISSUE TITLE
tf2: only first letter is shown of chemistry set inputs

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Source-1-Games#2353]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/3242.
@mtmkls posted on 2014-04-06T21:30:59:

It looks like this:
S x 3
R x 3
Both in the new item found dialog, and in the inventory.
***
@mtmkls commented on 2014-12-08T13:41:00

This issue still exists.

***
@mtmkls commented on 2014-12-13T20:16:16

Here's a screenshot

![2014-12-08_00002](https://cloud.githubusercontent.com/assets/957339/5425215/310e264c-830d-11e4-9232-83dd7ddd4951.jpg)

***
@mtmkls commented on 2015-01-17T17:48:17

The same applies for the paint selection popup (BTW replacing the buttons with the popup was a bad idea IMHO)

***
@mtmkls commented on 2015-12-07T21:29:27

This issue is still there. It also affects the progress bar text of the mission shelf.

***
@mtmkls commented on 2016-09-25T15:03:55

This issue is still there.

***
@mtmkls commented on 2017-10-23T11:56:12

This also affects the contract names in the contract tracker.

**Comment by mtmkls** [comment]
When a casual match ends and the XP bar is getting filled, the reasons for getting XP is shown above the bar. This has been unaffected until the latest update.

I guess you are using builtin strlen() on UTF16 strings.

**Comment by Tiagoquix** [comment]
@mtmkls Can you retest with the new 64-bit binaries + Vulkan render and an updated OS?

**Comment by mtmkls** [comment]
I now tried the game again after the summer update has dropped. It looks like this problem is fixed.
