### ISSUE TITLE
Cathook vac error 

### ISSUE THREAD

**Issue by b1gpaster** [ValveSoftware/Source-1-Games#2354]
I was playing tf2 when i realized i am terrible at the game so i decided to use a free Linux cheat called Cathook i downloaded it and compiled it but when i injected and tried to join a server i kept getting vac errors @kisak-valve so Mr. Kisak do you have a fix for this?

**Comment by kisak-valve** [comment]
Hello @b1gpaster, it should be fairly obvious, but cheats are not supported.
