### ISSUE TITLE
[TF2] [Linux] TF2 crashes with FL_Load_Glyph

### ISSUE THREAD

**Issue by FizzBuzz3000** [ValveSoftware/Source-1-Games#2355]
[Gist for HW info](https://gist.github.com/FizzBuzz3000/d08c77a08f045497447867e72bc7d305)

I've been getting crashes/hang for the past few months with TF2 on GNU/Linux, and I think it might be due to unicode in steam names/text in chat. Pic below is what happens, this happened to me twice within 2 hours and it's getting pretty frustrating since TF2 doesn't let go of my cursor when it crashes and I have to switch to a TTY to kill it.

![screenshot_cropped](https://user-images.githubusercontent.com/24493801/31979321-a60c53c4-b90b-11e7-9c10-1f7dbd6eb186.png)

**Comment by kisak-valve** [comment]
Hello @FizzBuzz3000, can you take a look at #2110 and see if this is the same issue?

**Comment by kisak-valve** [comment]
Hello @FizzBuzz3000, this issue is already being tracked at #2110. Closing as a duplicate.
