### ISSUE TITLE
[TF2] "Inspect In Game" function not working properly

### ISSUE THREAD

**Issue by Litronom** [ValveSoftware/Source-1-Games#2356]
As of right now, the "Inspect In Game" function only works with certain items. Using the function used to bring up a preview window for almost every item.

I assume the game tries to load up the new 3D preview feature, introduced in the Jungle Inferno update, but this feature only really works with weapons or, for example the contract tracker.

Trying with anything else, like a cosmetic item or a taunt, just opens up the general items menu in game.

**Comment by FindTheBorealis** [comment]
This has been potentially addressed per "Fixed not being able to preview Community Market items in-game" in the December 23, 2021 [update](https://www.teamfortress.com/post.php?id=112967), is this still an issue?

**Comment by shiro-2k** [comment]
Retested and confirmed that items can be successfully inspected ingame via the button on community market listings or profile inventories.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
