### ISSUE TITLE
[TF2] [Bug Report] Spy-cicle Not Functioning Properly

### ISSUE THREAD

**Issue by Contradicktory** [ValveSoftware/Source-1-Games#2359]
Whenever flames make contact with the Spy-cicle, it seems to take a solid second or two for the Spy-cicle to actually activate. 

This is a problem on both sides: Pyros attempting to stop Spies from landing a stab at the last moment will be rendered unable to, and Spies using the Spy-cicle to help them cloak away will still be lit by afterburn and take the full blunt of flame damage until it activates.

**Comment by Contradicktory** [comment]
Bumping this as it still hasn't been fixed and doesn't seem to have been noticed.

**Comment by kisak-valve** [comment]
Per "Fixed the Spy-cicle not giving the Spy fire immunity" in the [2017-11-17](http://store.steampowered.com/news/34651/) TF2 update, please retest this issue.

**Comment by agrastiOs** [comment]
@kisak-valve Retested, it's fixed. May be closed.

**Comment by kisak-valve** [comment]
Thanks for testing @agrastiOs, closing.
