### ISSUE TITLE
[TF2] Console launch lag, console unfocused and dont work at start

### ISSUE THREAD

**Issue by xacatis** [ValveSoftware/Source-1-Games#2360]
1. Console launch lag (press ~)
Run console now give lag to whole tf2 and cpu up. Before update it is on-off very fast on each hit.
Now - when you press on its on. But after you close and hit fast after another - it not opened, you need wait about 2 seconds to open it again.

2. unfocused and dont work at start
Before update "-toconsole" launch parameter give console ready with menu immediately. Now console load and it like unfocused, and you cant click it to focus, so need to off and on again

**Comment by kisak-valve** [comment]
Hello @xacatis, the second issue sounds like #2350.

**Comment by FindTheBorealis** [comment]
The second issue has been fixed as of the March 28, 2018 [update](http://www.teamfortress.com/post.php?id=38643), the first issue needs retesting.

**Comment by agrastiOs** [comment]
@kisak-valve this is fixed and can be safely closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
