### ISSUE TITLE
Dealing x3 falling damage to players as any class

### ISSUE THREAD

**Issue by alexavil** [ValveSoftware/Source-1-Games#2363]
Hello, there's a bug with Dealing 3x falling damage to players attribute.

You can crush players without having Manthreads or The Thermal Thruster. And (it's important) with any class!

To do it, you just need to land on the player.

Videos: 1) https://youtu.be/0Ts3Jnpbm90
             2) https://youtu.be/-OPuy1YV3KA

**Comment by kisak-valve** [comment]
Closing per "Fixed all classes doing 3x damage when landing on enemies" in the [2017-10-27 TF2](http://www.teamfortress.com/post.php?id=34096) update.
