### ISSUE TITLE
[TF2] Hud end map-vote menu remain to new at map-loading

### ISSUE THREAD

**Issue by xacatis** [ValveSoftware/Source-1-Games#2369]
Hud end map-vote menu remain to new at map-loading

**Comment by FindTheBorealis** [comment]
Seems like this was fixed in the March 28, 2018 [update](http://www.teamfortress.com/post.php?id=38643):

"Fixed the match-end map vote menu drawing if you disconnect from a server during a vote and then connect to a new server "

**Comment by agrastiOs** [comment]
@kisak-valve is fixed.

**Comment by kisak-valve** [comment]
Thanks, closing.
