### ISSUE TITLE
Source games - FPS drops and slowdowns after minimizing

### ISSUE THREAD

**Issue by mattyy1hp** [ValveSoftware/Source-1-Games#238]
I noticed that all Source games have a big slowdowns if they are minimalized and maximized.

I noticed this in following games:
- Team Fortress 2
- Team Fortress 2 Beta
- Half-Life 2: Deathmatch
- Counter-Strike: Source

Steps to reproduce:
1/ Start any game described above
2/ Connect to any server
3/ Minimize a game (ALT+Tab, WIN+D etc.)
4/ Maximize a game
5/ You may now have very unstable and lower FPS

Solution is disconnect from a server and re-connect or restart a game.

For example:
- FPS before minimizing = 60
- FPS after minimizing = <30

I tried:
- windowed mode = I can't reproduce it, it's more likely fullscreen-only
- disable AMD Tear-Free = did not help
- disable AMD Catalyst A.I. = did not help
- disable forced "wait for vertical refresh" in AMD Catalyst = did not help
- re-install AMD drivers = did not help

---

System specs:
Drivers: AMD 13.3 Beta2 Catalyst (it's same on the stable 13.1)
Desktop environment: Cinnamon 1.6.7

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-030800-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-08

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6520G

```
Driver Version:  4.2.12172 Compatibility Profile Context 12.10.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9647
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3418 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  581060 Mb
    Largest Free Hard Disk Block:  178983 Mb

Installed software:

Recent Failure Reports:
    Thu Mar 21 18:41:44 2013 GMT: file ''/tmp/dumps/assert_20130321194134_1.dmp'', upload yes: ''CrashID=bp-26a2ae16-d08d-4455-b8e4-0440f2130321
    ''

**Comment by wubli** [comment]
It happens to me with nvidia too

**Comment by ambaca** [comment]
Well, don't play fullscreen or minimize game screen.
:simple_smile:
play noooo

**Comment by kisak-valve** [comment]
Closing as general video driver / DE quality from 2013 is no longer relevant. If anyone is still experiencing this issue on an up to date system, please open a new issue report.
