### ISSUE TITLE
[TF2] Some paints colors dont shows (dark black)

### ISSUE THREAD

**Issue by xacatis** [ValveSoftware/Source-1-Games#2385]
Some paints colors dont shows it shows with no paint (dark black). Yeti Coated and some another (have fps config)

**Comment by Yetoo1** [comment]
Can confirm.

System info here:
http://web.archive.org/web/20200131035943/https://pastebin.com/2ND0ap12

**Comment by Tiagoquix** [comment]
OP, does this still happen?

FPS config. may affect the paint behavior.

**Comment by kisak-valve** [comment]
Closing pending feedback.
