### ISSUE TITLE
[TF2] Match queue and resume game UI overlap

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2392]
When queued in game, the element that says what mode you're queuing for overlaps with the resume 
game button.

**Comment by CriticalFlaw** [comment]
If this is to be fixed, here's how it can be done. The end result can be seen in the screenshot below.
- In **tf_english.txt**, change value of `MMenu_ResumeGame` to just say "Resume".
- In **resource/ui/matchmakingdashboard.res** change the width of `ResumeButton` to 90

![image](https://user-images.githubusercontent.com/6818236/42914542-e5d713ec-8ac8-11e8-977e-0a736dd4b470.png)

**Comment by FindTheBorealis** [comment]
Closing as this has been fixed in the 2019/03/26 update, thanks @CriticalFlaw
