### ISSUE TITLE
[TF2] [Suggestion] Show what maps now in queue for party members

### ISSUE THREAD

**Issue by xacatis** [ValveSoftware/Source-1-Games#2395]
Show what maps now in queue for party members
Maybe in chat or graphically same in find game menu mirroring checkboxes
If on map in queue show it in existing pop-up window: "in queue "map_name""

**Comment by agrastiOs** [comment]
It's already possible to see what are going to be the maps

**Comment by kisak-valve** [comment]
Closing per the last comment.
