### ISSUE TITLE
[TF2] Black day collection box image dont load at inventory

### ISSUE THREAD

**Issue by xacatis** [ValveSoftware/Source-1-Games#2398]
Black day collection box image dont load at inventory, it load 1 time after "watch it" and after going to next page and go back it is show like empty inventory space. (have fps config)

**Comment by Tiagoquix** [comment]
OP, does this still happen?

FPS config. may affect the texture behavior, such as lower texture quality for backpack items, disabling phong/specular/bumpmap and/or mip-map textures.

**Comment by kisak-valve** [comment]
Closing pending feedback.
