### ISSUE TITLE
[TF2] No pyro flame or fire projectiles present since Jungle Inferno update

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2404]
I held back on this since I thought perhaps it was known and would be addressed, but there has been an absence of pyro flame or fire projectiles since Jungle Inferno update.

Examples being the Backburner and Dragon's Fury.  It is very hard to gauge if you are within close enough proximity to ignite a target or tell if you are aiming correctly when the flamethrower's flame/projectile are not visible.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 17.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.13.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11905000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) x86/MMX/SSE2
    Driver Version:  3.0 Mesa 17.2.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x5916
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5760 x 1800
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC3246

Memory:
    RAM:  15923 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  479190 Mb
    Largest Free Hard Disk Block:  79691 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by kisak-valve** [comment]
This looks to be limited to mesa/Intel hardware, the console also has:
```
Attempting to create unknown particle system 'new_flame'
Attempting to create unknown particle system 'new_flame'
Failed to create new_flame particles.
```

**Comment by Nephyrin** [comment]
We're aware of this issue - as a workaround, setting `mat_reducefillrate` to `0` may improve the issue.

**Comment by kepgnar** [comment]
mat_reducefillrate to 0 did not improve the issue for me. I am playing on macOS 10.12.6. All flamethrower particles have been absent since one of the incremental updates right after the initial pyro update. I have re-installed TF2 to no avail.

**Comment by FindTheBorealis** [comment]
This has apparently been fixed as of the November 7, 2017 update, can anyone who experiences this bug
see if it has been fixed for them?

**Comment by nightsky30** [comment]
@kisak-valve @Nephyrin I can confirm this is indeed fixed in Linux.  Thanks 

@kepgnar Is it working now in MacOS??

**Comment by kisak-valve** [comment]
It's also behaving on my test systems.

**Comment by nightsky30** [comment]
@kisak-valve If your test systems include MacOS, and it is working for you, then I have no issue closing this as fixed.
