### ISSUE TITLE
[TF2] Pyro enters reference pose with the Thermal Thruster

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2415]
After falling some distance after using the Thermal Thruster, the Pyro will be in the reference pose until
reaching the floor. I believe this is because the Thruster has the Mantreads stomp effect, and the Pyro
doesn't have a stomp fall animation like the Soldier, but that's anecdotal I think.

**Comment by FindTheBorealis** [comment]
Actually the Thruster's stomp effect was removed in the October 27, 2017 update, so I don't really know the 
cause of this.

**Comment by kisak-valve** [comment]
Per "Fixed a Pyro animation bug related to jumping" in the [2017-11-17](http://store.steampowered.com/news/34651/) TF2 update, please retest this issue.

**Comment by FindTheBorealis** [comment]
This hasn't been fixed, although it looks it me like the Pyro needs to fall further to enter the reference pose,
though I may be misremembering.

**Comment by FindTheBorealis** [comment]
Closing as this has been fixed in the April 12, 2018 [update](http://www.teamfortress.com/post.php?id=39125), thanks.
