### ISSUE TITLE
[TF2] Game In Progress Rejoin Match Prompt UI Broken

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2437]
System Info:  https://gist.github.com/nightsky30/cdf65dde88540714c027b19e176dbcb6

When TF2 has crashed in the past, I was able to rejoin the match I was in prior to the crash.  This seems to be broken now.  When I restart TF2 after a crash and enter the main menu, I can hear a notification sound, and see a black rectangle in the upper left hand corner.  The rectangle soon fades away.  This does not appear when I first start TF2, only when I've crashed out of a game.  I believe this is the Game In Progress/Rejoin prompt, and the UI is messed up.

This functionality was working during the Jungle Inferno update a few weeks ago.

![rejoin_ui_box](https://user-images.githubusercontent.com/6024315/32986625-dd00459a-cc9b-11e7-8376-63744638cf32.png)

**Comment by Tiagoquix** [comment]
OP, does this still happen?

**Comment by kisak-valve** [comment]
Closing pending feedback.
