### ISSUE TITLE
Source games work without textures on Fedora 18 i686 on notebook NP300E5C-U06RU

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Source-1-Games#244]
Games based on Source engine such as TF2 and CS work without textures on Fedora 18 i686 on notebook NP300E5C-U06RU

System Info:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2501 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 18 (Spherical Cow)" (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.4-202.fc18.i686.PAE
    X Server Vendor:  Fedora Project
    X Server Release:  11303000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-08

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile 

```
Driver Version:  2.1 Mesa 9.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xde8
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  7872 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  92496 Mb
    Largest Free Hard Disk Block:  65147 Mb

Installed software:

Recent Failure Reports:

![Screenshot from 2013-03-25 04:36:44](https://f.cloud.github.com/assets/200750/296055/6f3c1678-94d4-11e2-834b-60550938769a.png)

![Screenshot from 2013-03-25 04:36:28](https://f.cloud.github.com/assets/200750/296056/7726e5ca-94d4-11e2-86f5-9fbab8e37d68.png)

**Comment by kisak-valve** [comment]
Closing as this was a system configuration issue.

Until the S3TC patent expires and the functionality is built into Mesa, the additional libtxc_dxtn package is required for textures to render properly when using Mesa.

**Comment by NTMan** [comment]
Why not create official steam client with all needed 3rd party components for rpm based distridution such as Fedora?

**Comment by kisak-valve** [comment]
Hello @NTMan, in this specific case, libtxc_dxtn is only needed for mesa users, AMDGPU-PRO and nVidia's proprietary driver has support baked into the driver.

**Comment by NTMan** [comment]
> Hello @NTMan, in this specific case, libtxc_dxtn is only needed for mesa users, AMDGPU-PRO and nVidia's proprietary driver has support baked into the driver.

I understand, but a couple of the official client can solve this problem too.
In addition, if we have a pair of the official client for distribution on the basis of speed, game developers will also have to spend more time to test their games in other distributions, and the quality will be better.

Ubuntu with its decisions (Mir instead Wayland, a swap file instead of a swap partition, snappy instead of packaging etc.) become more and more distant from Linux world.
