### ISSUE TITLE
[TF2] Enforcer Damage Pierce Doesn't Work On Fists of Steel

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2452]
Wonder why this weapon isn't used? Maybe because it doesn't work...

![Screenshot](https://steamuserimages-a.akamaihd.net/ugc/877503482686271646/545900F5D0408CAB6B2612E6F1B0C0FB1D2FA626/)
http://steamcommunity.com/sharedfiles/filedetails/?id=1219754648
-35
vs
![Screenshot 2](https://steamuserimages-a.akamaihd.net/ugc/877503482686269767/C9B534AF0E9A9AEF5DC470823B9E336B5794FB6A/)
http://steamcommunity.com/sharedfiles/filedetails/?id=1219754288
-59

**Comment by FindTheBorealis** [comment]
This has been fixed as of the March 28, 2018 update.

**Comment by kisak-valve** [comment]
Closing per "Fixed the resistance-piercing property on The Enforcer not working against some items or effects (Wrangler shields, Battalion's BackUp, Fists of Steel, Spy invisibility passive resistance, The Dead Ringer, Brass Beast and Natascha)" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update. Thanks for retesting.
