### ISSUE TITLE
Enforcer Does Not Work On Dead Ringer

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2453]
This video shows the problem:

https://www.youtube.com/watch?v=Nb9Boz3Fr2M

Enforcer shots don't do full damage to the dead ringer.

Edit: Longer video by someone else here:
https://www.youtube.com/watch?v=ntGJCdC0H2w

**Comment by kisak-valve** [comment]
Closing per "Fixed the resistance-piercing property on The Enforcer not working against some items or effects (Wrangler shields, Battalion's BackUp, Fists of Steel, Spy invisibility passive resistance, The Dead Ringer, Brass Beast and Natascha)" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update.
