### ISSUE TITLE
Can't backtrace in secure mode

### ISSUE THREAD

**Issue by mrsteyk** [ValveSoftware/Source-1-Games#2454]
When i try to do backtracing with gdb, after some time i get kicked out of server with the gayest possible message: "An issue on your computer is blocking the VAC system. You cannot play on secure servers.". I never got this message before early august 2017.

**Comment by kisak-valve** [comment]
Hello @mrsteyk, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, what OS are you running on and what game(s) are affected?

**Comment by mrsteyk** [comment]
Can't rn. But rn i can say that its a problem for a few other people. I know certainly it happens on Arch Linux 64 bit (for me and one other guy for sure). Used only with TF2, so i cant say anything about other games.

**Comment by kisak-valve** [comment]
Closing pending feedback.
