### ISSUE TITLE
TF2 straight up closes randomly on Linux Mint

### ISSUE THREAD

**Issue by kamild1996** [ValveSoftware/Source-1-Games#2456]
After a random amount of time (usually **under five minutes**), the game basically shuts down. No error message, no logs/dumps in the game folder or in the terminal, nothing. The game just disappears from the screen and drops me right back to the desktop.

OS: Linux Mint 18.3 Cinnamon, kernel 4.13.0-17, Mesa 17.3.0-rc4.
Hardware: Core i5-3570K, ASRock P67 Pro3, Radeon RX 480, 8GB RAM

**Comment by kisak-valve** [comment]
Hello @kamild1996, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps related to this issue, please include them.

It may be worthwhile to check ~/.steam/error.log after this happens as there may be a hint as to what's going on here. Alternatively, you can completely close steam, then run steam from a terminal to get the same terminal spew. `dmesg` may also log a hint as to that's happening.

**Comment by kamild1996** [comment]
https://gist.github.com/kamild1996/b776566c725c5fcde704caa822d02c1f
No CrashIDs or minidumps present anywhere within the game folder. I've already launched Steam from terminal and watched the terminal window while playing, after the game closed, no message showed up.

However, error.log seems to show something. Not sure what make out of it. https://gist.github.com/kamild1996/5aaaec29d07b2441f9a1f351b4948c42

**Comment by kamild1996** [comment]
So there is a minidump, just not in a place I have expected it to be. Attached below. 

[crash_20171204203951_1.dmp.tar.gz](https://github.com/ValveSoftware/Source-1-Games/files/1528589/crash_20171204203951_1.dmp.tar.gz)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in vguimatsurface.so.

Also, `Missing interface adapter for SteamNetworkingSocketsSerialized001` from the log may be interesting, but potentially unrelated.

**Comment by kamild1996** [comment]
I noticed the "memory access violation" error, which seemed out of place for me. So I checked something.

Surely enough, it was my CPU's overclock. Didn't come to my mind at first because Windows was completely stable, but curiosity forced me to check, and surely enough, the issue is gone at stock clocks. I owe you an apology for wasted time :)

**Comment by kisak-valve** [comment]
Closing per the last comment.
