### ISSUE TITLE
[TF2] Linux: Focus loss minimizes game

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2460]
If you click on another window the game minimizes itself.

This is a bug because it causes TF2 to minimize itself when you focus an app on another monitor, such as Twitch.TV.
I was trying to stream one monitor and use the other one to read/respond to comments, but every time I clicked on twitch.tv, TF2 minimized itself.

Also please fix the spy bugs. :)

**Comment by kisak-valve** [comment]
Hello @Exaeta, this is the expected behavior for all SDL 2 applications.

You can override this with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` in the game's launch options.
