### ISSUE TITLE
[TF2] Missing string when opening the Contracker while taunting

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2461]
The 2017/12/13 update made it so the Contracker can't be opened while taunting, and the text string when
doing so is missing, the text is present in the english localization file, "You cannot open the ConTracker menu while taunting" but in game its "#TF_CYOA_PDA_Taunting". Don't know about other languages.

**Comment by agrastiOs** [comment]
For me the text is correct.

**Comment by FindTheBorealis** [comment]
Closing since this affects all text added after Jungle Inferno, not just this string.

[New issue.](https://github.com/ValveSoftware/Source-1-Games/issues/2527)
