### ISSUE TITLE
[TF2] Opening Contracker while dead unmaps movement keys

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2462]
Respawning after having opened the contracker whilst being dead will render the player unable to move and also unmaps taunt and attack keys.

**Comment by kisak-valve** [comment]
Per "Fixed not being able to move if you opened the ConTracker menu while dead and closed it after you respawned" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update, please retest this issue.

**Comment by hahagoni** [comment]
Appears to be fixed. Closing
