### ISSUE TITLE
[TF2] Dead Ringer does not affect overhead strip

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2467]
Yet another Dead Ringer bug, again! Valve, if you want the Dead Ringer to be useful for its intended purpose and not spamming, fix these bugs.

With the original tab scoreboard, the "dead" icon shows while the player is feigning and the player's name is greyed out (fake death).

Around MYM Valve added a strip at the top of the screen that shows when players are dead. This strip is not affected by the feign, as it should be. Affects all platforms as far as I know.

**Comment by kisak-valve** [comment]
Hello @Exaeta, per "Fixed the Spy's feigned deaths with the Dead Ringer not showing up in the matchmaking quick team status bar " in the [2022-06-21](https://www.teamfortress.com/post.php?id=139819) Team Fortress 2 update, please retest this issue.

**Comment by Ashetf2** [comment]
Retested. Fixed 👍

**Comment by kisak-valve** [comment]
Closing as fixed.
