### ISSUE TITLE
[TF2][Feature Request] Genteel smoke particle effect for the Soldier's Stogie

### ISSUE THREAD

**Issue by Bukz** [ValveSoftware/Source-1-Games#247]
I believe it would be a nice addition to this item, I assume there might be some reason why it was left out in the fist place?

**Comment by FindTheBorealis** [comment]
The genteel smoke was added to the item in the 2014-4-1 [update](http://www.teamfortress.com/post.php?id=12815), @kisak-valve I believe this can be closed.

**Comment by kisak-valve** [comment]
Thanks @FindTheBorealis. Closing.
