### ISSUE TITLE
[TF2] Won't Start on Fedora

### ISSUE THREAD

**Issue by colonelpanic-42** [ValveSoftware/Source-1-Games#2473]
Trying to launch TF2, nothing loads and no error is returned in Steam. Tried running through Steam and hl2.sh directly, neither work.

Output of hl2.sh: https://gist.github.com/colonelpanic-42/084ff3f816357ff2fe8db6e1c5d66ebe
System Information: https://gist.github.com/colonelpanic-42/8cef56969489ef8b3310398e7b6c16e8

**Comment by kisak-valve** [comment]
Hello @colonelpanic-42, what does `~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ldd ~/.local/share/Steam/steamapps/common/Team\ Fortress\ 2/bin/engine.so | grep found` output?

Anything other than:
```
	libtier0.so => not found
	libvstdlib.so => not found
	libsteam_api.so => not found
```
are missing dependencies that need to be resolved.

**Comment by colonelpanic-42** [comment]
In addition to the three lines above, I got this output as well:
```
/home/colpanic/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so: /lib/libgnutls.so.26: version `GNUTLS_1_4' not found (required by /home/colpanic/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libcurl-gnutls.so.4)
/home/colpanic/.local/share/Steam/SteamApps/common/Team Fortress 2/bin/engine.so: /lib/libgnutls.so.26: version `GNUTLS_1_4' not found (required by /home/colpanic/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/librtmp.so.0)
```

The file /lib/libgnutls.so.26 exists, and from what I can tell from Google that should be providing GNUTLS_1_4, unless that error doesn't say what I think it says.

**Comment by kisak-valve** [comment]
I read that as the steam-runtime variant of libcurl-gnutls.so.4 trying to tell us it is not compatible with the system variant of libgnutls.so.26.

Try pinning the steam-runtime variant of libgnutls.so.26 with `ln -s ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgnutls.so.26 ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libgnutls.so.26`

**Comment by colonelpanic-42** [comment]
That seemed to fix it :) never knew about the pinned libraries function, will have to keep it in mind for future references. Thank you!
