### ISSUE TITLE
TF2: Strange Part "Projectiles reflected" is not working properly. 

### ISSUE THREAD

**Issue by Xetr0n** [ValveSoftware/Source-1-Games#2474]
Currently for me and some players I asked most of the Projectiles I reflect are not being counted on my Flame Thrower, Degreaser and/or Back Burner.

E.g. I reflect a rocket and the counter of "Projectiles reflected" will stay the same. If I kill someone with this reflect the kill counter of my Flame Thrower will increase but the "Projectiles reflected" counter will not.

I did some testing with some friends on Valve and Community Servers to see which weapon projectiles are being counted and which ones are not.

The only projectiles that are being counted are: Any Sticky Bomb from any Demoman Sticky Launcher (Sticky Bomb Launcher, Scottish Resistance, Quickie Bomb Launcher, Sticky Jumper) and the Sandman Ball from the Sandman from the Scout.

All other projectiles do not add to my "Projectiles reflected" counter. Which includes all Rocket Launchers, all Flare Guns, all Grenade Launchers, every throwable secondary, the Medics Crossbow and the Huntsman.

Also it doesn't matter if I'm using a strange Flame Thrower (Festive/Not Festive/Skin/No Skin) or a Degreaser (Skin/No Skin/Festive).

Since only a minority uses a Strange Flame Thrower with the "Projectiles reflected" attachment not many have noticed it probably. But you could look into this problem yourself if youre using this Strange Part on your weapons.

**Comment by brorot29** [comment]
Add me piz

**Comment by Xetr0n** [comment]
Sorry, where should I add you? And why?

**Comment by FindTheBorealis** [comment]
This has been fixed as of the March 28, 2018 [update](http://www.teamfortress.com/post.php?id=38643).

**Comment by kisak-valve** [comment]
Closing per "Fixed the Deflect Projectiles strange part not counting deflections" in the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update.
