### ISSUE TITLE
[TF2] Username triggers VAC ban

### ISSUE THREAD

**Issue by ikfe** [ValveSoftware/Source-1-Games#2475]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): not needed. (4.14.8-1-ARCH)
* Have you checked for system updates?: [Yes/No] Yes.
* Game : TF2

#### Please describe your issue in as much detail as possible:
_Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/)._
So when you have an username on your GNU/Linux machine containing "catbot", you get a VAC ban.
I understand that it's a way to fight agaisnt cheaters, but this could hit innocent users that would use that as username.
I'm simply looking for explanations, Thanks in advance.

#### Steps for reproducing this issue:

1. Install a GNU/Linux distro (Debian, Solus ...)
2. Create an user account wich contains "catbot"
3. Install steam, create an account/login, wait..
4. Enjoy the VAC ban for TF2.

**Comment by BenCat07** [comment]
Can Confirm this issue.

**Comment by Marc3842h** [comment]
Can confirm this happened to a innocent account of mine. I never cheated and I do not associate with cheaters _lol_ and this is very sad that this is happening.

**Comment by Kr4ken-9** [comment]
![asdf](https://i.imgur.com/wFw4F76.png)

Users named catbot are chiters now? It seems this change is undocumented, I wonder why?

**Comment by WhiteX6** [comment]
I can confirm that this is infact true, I installed ubuntu on a virtual machine and named the computer catbot-918 and installed steam, within an hour of not playing anything I received a VAC ban.

**Comment by kisaksnumberonefan** [comment]
I can confirm this.

Also, Kisak also ignored me on IRC when I tried to give him a Christmas present. 
:frowning_face:

**Comment by 1157** [comment]
Prob. related to this
https://github.com/nullifiedcat/catbot-setup
If your running this then it is a "cheat", why would you be running a vm named catbot?

**Comment by kritzsie** [comment]
Confirmed with one long-standing account and one fresh account, both under the same Linux username starting with "catbot".
But consider yourselves lucky! Valve have a history of hunting down users who don't adapt to policy changes and banning their accounts, often worth thousands of dollars, with no indication as to why. I have been caught in a ridiculous but unrelated permanent community and trade ban for trying to sell a large amount of items on the community market, even though Steam support never bothered to confirm this.
Don't be surprised when Steam support discard your ticket due to "privacy policy" issues. I know I wasn't.

**Comment by 1157** [comment]
Why would anyone set the username to a known cheat?

**Comment by kisaksnumberonefan** [comment]
@1157 
what if someone's username was catbottom or something

**Comment by mrsteyk** [comment]
@1157 WHY THE FUCK NOT, BRUH? What if I have bot network for other purposes and I want to play tf2. And I can't and I get ban on my account for literally nothing. What a stupid move @ValveSoftware

**Comment by kisak-valve** [comment]
Good day, I've received word from the VAC team that this is intentional and not open for discussion on Github.

In general VAC issues are not handled on Github in any capacity and further issue reports on this may result in being banned from the Valve Software issue trackers.

**Comment by kisak-valve** [comment]
For the random visitor looking to this issue report for some drama, feel free to give https://www.reddit.com/r/linux_gaming/comments/7ndjdt/valve_will_vac_ban_you_automatically_for_having/ds2dulw/ a read as a follow up.
