### ISSUE TITLE
[TF2] Username still triggers VAC Ban.

### ISSUE THREAD

**Issue by Skeptyc** [ValveSoftware/Source-1-Games#2476]
Affected Distros: All

So when you have an username on your GNU/Linux machine containing "catbot", you get a VAC ban.  For instance, if your username is 'Brocatbottle', you will get a VAC ban.  Supposedly Valve will also ban you for reporting this terrible security practice, which is caused by VAC not working properly on Linux, and so they are going for the low-hanging fruit.  

This is a ridiculous method of attempting to detect cheats, and will lead to false positives and is blatantly anti-consumer.  Valve, are you taking lessons from EA in how to deal with problems?  Because this is how you get yourself Streisand-effected.

**Comment by LaxWasHere** [comment]
¯\\_(ツ)_/¯
