### ISSUE TITLE
TF2 for Linux: Unusual hat effect on other players

### ISSUE THREAD

**Issue by YellowSloth** [ValveSoftware/Source-1-Games#248]
Recently I started playing the scout again on TF2 on Linux. I own an Unusual Flipped Trilby with the Stormy Storm effect. When I die and see other people playing while I am waiting for the respawn, my Stormy Storm effect is visible above other player's heads and that in a rather glitchy fashion. (It jumps around instead of staying still above one's head.)

Since it is hard to explain I made a couple of screenshots which can be seen at the bottom.

If it is not clear enough yet and there is a wish for it I could make a video.

```
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3200 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.4-202.fc18.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11303000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-25

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6900 Series

    Driver Version:  4.2.12002 Compatibility Profile Context 9.01.8
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6718
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                            47.7cm x 26.8cm  (54.7cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: VIA VT2020

Memory:
    RAM:  15985 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  189331 Mb
    Largest Free Hard Disk Block:  145257 Mb
```

![2013-03-27_00002](https://f.cloud.github.com/assets/3274364/310908/072137d2-972a-11e2-8f74-f4b0ce6f08b8.jpg)
![2013-03-27_00005](https://f.cloud.github.com/assets/3274364/310909/0737d9ba-972a-11e2-88da-7042b05fb92b.jpg)
![2013-03-27_00003](https://f.cloud.github.com/assets/3274364/310910/0722e852-972a-11e2-9ac1-e186acf3821e.jpg)
![2013-03-27_00004](https://f.cloud.github.com/assets/3274364/310911/072824f2-972a-11e2-8fa1-7fda96ac9bd1.jpg)
![2013-03-27_00006](https://f.cloud.github.com/assets/3274364/310912/07392d4c-972a-11e2-8d3d-64eaca9a1384.jpg)
![2013-03-27_00008](https://f.cloud.github.com/assets/3274364/310913/074e3f7a-972a-11e2-83cb-e4591bae845c.jpg)
![2013-03-27_00009](https://f.cloud.github.com/assets/3274364/310914/073ac44a-972a-11e2-89c7-0b7030c98cfd.jpg)
![2013-03-27_00011](https://f.cloud.github.com/assets/3274364/310916/075123f2-972a-11e2-8e9d-945e9ea84d05.jpg)
![2013-03-27_00010](https://f.cloud.github.com/assets/3274364/310915/073f88ea-972a-11e2-8081-5431a97c26b4.jpg)
![2013-03-27_00014](https://f.cloud.github.com/assets/3274364/310918/07511538-972a-11e2-8320-5b18b91664eb.jpg)
![2013-03-27_00015](https://f.cloud.github.com/assets/3274364/310919/0777523e-972a-11e2-930e-cf8dac9207a2.jpg)
![2013-03-27_00016](https://f.cloud.github.com/assets/3274364/310920/076863a0-972a-11e2-90a4-9048b307797f.jpg)
![2013-03-27_00017](https://f.cloud.github.com/assets/3274364/310921/077b1f2c-972a-11e2-9f6b-9eb527b3e919.jpg)
![2013-03-27_00018](https://f.cloud.github.com/assets/3274364/310922/07669480-972a-11e2-9ff3-4fafa0f2e3c2.jpg)
![2013-03-27_00019](https://f.cloud.github.com/assets/3274364/310923/078d39c8-972a-11e2-8ba7-3ae875917007.jpg)
![2013-03-27_00022](https://f.cloud.github.com/assets/3274364/310924/077a8c56-972a-11e2-8db4-afbdb2b82e88.jpg)
![2013-03-27_00021](https://f.cloud.github.com/assets/3274364/310925/079091ea-972a-11e2-832f-69e8baa0f9ff.jpg)
![2013-03-27_00007](https://f.cloud.github.com/assets/3274364/310926/077db3a4-972a-11e2-8d93-208f96417c9c.jpg)
![2013-03-27_00023](https://f.cloud.github.com/assets/3274364/310927/07a0fe0e-972a-11e2-9742-6be28da51149.jpg)
![2013-03-27_00024](https://f.cloud.github.com/assets/3274364/310928/07942a3a-972a-11e2-9441-ea45a756167c.jpg)
![2013-03-27_00025](https://f.cloud.github.com/assets/3274364/310929/07aa2f60-972a-11e2-8679-67782f2ae5f3.jpg)
![2013-03-27_00020](https://f.cloud.github.com/assets/3274364/310930/07bd34b6-972a-11e2-97dc-ea4f2dda5962.jpg)

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing as fixed in the [2013-06-05 TF2 client update](https://wiki.teamfortress.com/wiki/June_5,_2013_Patch).
