### ISSUE TITLE
[TF2][BUG] "Out of memory or address space" on linux with amdgpu

### ISSUE THREAD

**Issue by ibrokemypie** [ValveSoftware/Source-1-Games#2483]
Game consistently crashes on community servers as soon as the map loads, even with 16gb of system ram and a vega 56 (8gb vram). Crashes also with same error after a few rounds of official servers.

Running mesa-git, xorg-server-git, xf86-video-amdgpu-git.

**Comment by kisak-valve** [comment]
Hello @ibrokemypie, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps related to this issue, please include them.

There's a decent chance this is TF2 running out of virtual address space. If you can keep an eye on resident memory being used by the game just as it crashes, that could also be helpful.

**Comment by ibrokemypie** [comment]
Clicking gather system information is causing steam to crash at the moment.

**Comment by Mastergatto** [comment]
I have this very same issue, with very same GPU and RAM, although xorg and mesa are the stable version. Here is [my gist (a bit dated)](https://gist.github.com/Mastergatto/082c71debf222b58246af7781e558e0c). I'll look for more info and post them here.

**Comment by kisak-valve** [comment]
Hello @Mastergatto, it's not new enough yet, but when https://aur.archlinux.org/packages/lib32-mesa-git/ updates to something from this year, please give that a try and let us know if it makes a difference.

**Comment by Mastergatto** [comment]
Ok, I will do it! Hopefully that package updates very soon, so that I'll be able to do some tests.

**Comment by kisak-valve** [comment]
Per "Improved memory usage on OS X and Linux systems" and "This should reduce the occurrence of "Out of memory or address space" errors on high texture quality settings" in the [2019-01-22](http://www.teamfortress.com/post.php?id=47741) TF2 update, please retest this issue.

**Comment by Mastergatto** [comment]
I just had some match, things seem to be improved, but to say for 100% sure I need to do some match on 2fort. Thanks for the patch!

**Comment by kisak-valve** [comment]
Closing as fixed. If anyone is still experiencing this issue please open a new issue report. Mesa 19.0 also has some improvements that reduces memory pressure.
