### ISSUE TITLE
[TF2] Nerf WM1 Pyros

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2495]
Recently, Valve buffed the WM1 Pyro and nerfed skilled Pyro play.

Currently, if you walk forward (hold W), and fire flames (M1) they travel farther than if you try to strafe and avoid other players. This encourages walking in a straight line towards other players and discourages strafing.

Because this encourages poor pyro play (WM1), and reduces the skill required to play pyro, I suggest reverting this change.

**Comment by Wasmanr2** [comment]
Look the pyro needed the buff to make him not situational class like engineer or sniper or spy, as a pyro you already need to hold down m1 anyway i mean you dont strafe as a pyro if you dont dodge bullets or whatever pyro isnt a class which trows pills or rockets, its a close combat class, you need to run at people and flame them strafing for that will be ineffective(unless as said dodging stuff or using secondary) people will try to escape you they dont stand still and wait until you made kebab outta them they will back off. The thing is the faster flames pushed the dps to a new level. Pyro isnt OP as you might think but his damage needs atleast to be scaled down as he deals too much damage in less time. So reducing the damage would be better and the particles of the flames need to be atleast have a opacity of 50%  less to atleast see what you hit. And If you think i flavour this class then you are **wrong**  im thinking generally for all players. 
Pyro is a hard to balance class.
(I dont main pyro anyway)

**Comment by Exaeta** [comment]
@kisak-valve 
Recent changes to pyro are good. Pyro is less overpowered now, but there's two changes I'd still suggest:

Make damage different depending on how close you are to the center of each flame projectile. Right now a fire particle that grazes you seems to do around the same damage as a direct hit. While spreading has been nerfed a bit, I think pyro is still a bit too good at killing players without skill.

I would also make the flames slower, but make them last longer so they travel the same distance.

**Comment by agrastiOs** [comment]
@kisak-valve 
Considering that WM1 Pyro is nerfed now, this issue should be closed, just like #2485 was.
Another issue could be made for Pyro suggestions.

**Comment by kisak-valve** [comment]
I'm in agreement, @Exaeta, feel free to open a new issue report for your newer suggestion.

Closing per the feedback on the request in the opening post.
