### ISSUE TITLE
Being VAC blocked by TF2 VAC secure server

### ISSUE THREAD

**Issue by BenCat07** [ValveSoftware/Source-1-Games#2502]
System Version: Ubuntu 16.04.05
Using Newest Steam-launcher from offical website (not apt)

How to reproduce the issue:
- Start tf2
- Try to join any VAC secured server

This is happening to alot of people, not just me:
https://www.reddit.com/r/linux_gaming/comments/7rid12/i_suddenly_cant_play_tf2_getting_kicked_with_the/

**Comment by delet-this** [comment]
Confirmed on Arch Linux, newest Steam and latest updates. Tried rebooting/verifying game cache.

**Comment by Roguezilla** [comment]
Can confirm, same happening on my end, But Antergos as distro with XFCE4 here.

**Comment by Roguezilla** [comment]
http://steamcommunity.com/app/440/discussions/0/1693785035814078209/ users reporting the same issue here

**Comment by kritzsie** [comment]
Confirmed on Arch Linux with the latest updates (pacman -Syu)
Chances are this is 100% intentional as VAC errors on Linux are usually a result of actions taken by Valve developers to inconvenience frustrated users away from Steam.

**Comment by SpaghettiSoup27** [comment]
same on manjaro

**Comment by BenCat07** [comment]
-insecure = ineffective

**Comment by mastercoms** [comment]
This has been fixed @kisak-valve 

https://github.com/ValveSoftware/csgo-osx-linux/issues/1596#issuecomment-359055526
