### ISSUE TITLE
[TF2, at least] Windowed mode misbehaving in KDE

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#2509]
I run TF2 in a window so I can quickly Alt-Tab out and multi-task when I'm dead and during map loads, and I keep my Friends window on left edge of the screen, which means it slightly overlaps the TF2 window. And I discovered a new weird behavior today. I tried to bring up an up-to-date server list for one of the groups I'm in by clicking the Groups tab, expanding the group, and then clicking the little arrow on the right. But when I clicked it, the TF2 window stole focus. When I Alt-Tabbed back over to the Friends window, the menu had popped up, but it wasn't clickable. I tried the arrow again, and TF2 again stole focus.

I have not seen this happen with any other Steam client component or any other program, so I have no idea what's happening here.

Running Kubuntu 17.10.

**Comment by kisak-valve** [comment]
Closing pending feedback.
