### ISSUE TITLE
[TF2] Inspecting an item using a link is broken, returns error in console

### ISSUE THREAD

**Issue by Weetile** [ValveSoftware/Source-1-Games#2511]
When trying to inspect an item using a link in TF2, it shows this in the developer console.

"Invalid rich presence join string: "+tf_econ_item_preview S76561198216469957A6615751716D10057581045009475908""

**Comment by zyox123cc** [comment]
Still need repair

**Comment by FindTheBorealis** [comment]
This has been likely addressed per "Fixed not being able to preview Community Market items in-game" in the December 23, 2021 [update](https://www.teamfortress.com/post.php?id=112967), is this still an issue?

**Comment by shiro-2k** [comment]
> This has likely been addressed per "Fixed not being able to preview Community Market items in-game" in the December 23, 2021 [update](https://www.teamfortress.com/post.php?id=112967), is this still an issue?

Retested and confirmed that items can be successfully inspected ingame via the button on community market listings or profile inventories.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
