### ISSUE TITLE
Rendering glitches after locking/unlocking xfce4 session

### ISSUE THREAD

**Issue by nullifiedcat** [ValveSoftware/Source-1-Games#2512]
*which game you're reporting the bug on (TF2, CS:S, all)*: TF2, but it also probably happens on other games. Didn't test.

*a short, descriptive title*: Rendering glitches after locking and unlocking the xfce4 session

*a detailed description of the issue, including any output from the command line*:

Output of `differences` command in TF2 console: https://gist.github.com/nullifiedcat/7bd107257f1c3871e7e67b5c24fae6b4

Video demonstrating the bug: https://youtu.be/IeojaWq8jSo

On the local server (in that video), the amount of glitches was minimal. On casual servers the game becomes literally unplayable. 

*steps for reproducing the issue*

- Launch TF2
- Join a server
- Lock the session using `xflock4` command
- Unlock the session (enter password)
- Un-minimize TF2

*your system information*

https://gist.github.com/nullifiedcat/1ad0434c4569e48d50af3024a93f95fa

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render and an updated OS?

**Comment by kisak-valve** [comment]
Closing pending feedback.
