### ISSUE TITLE
[L4D2] Chainsaw server crash

### ISSUE THREAD

**Issue by Accelerator74** [ValveSoftware/Source-1-Games#2526]
Chainsaw crashes server after update ~2.1.4.3

Dump:

0        server_srv.so!CSoundPatch::ChangePitch(float, float) + 0x6
1        server_srv.so!CChainsaw::ItemPostFrame() + 0x7f8
2        server_srv.so!CBasePlayer::ItemPostFrame() + 0x47f
3        server_srv.so!CTerrorPlayer::ItemPostFrame() + 0xba
4        server_srv.so!CBasePlayer::PostThink() + 0xe3b
5        server_srv.so!CCSPlayer::PostThink() + 0xc5
6        server_srv.so!CTerrorPlayer::PostThink() + 0x140
7        server_srv.so!CPlayerMove::RunPostThink(CBasePlayer*) + 0xb7
8        server_srv.so!CPlayerMove::RunCommand(CBasePlayer*, CUserCmd*, IMoveHelper*) + 0x6ce
9        server_srv.so!CBasePlayer::PlayerRunCommand(CUserCmd*, IMoveHelper*) + 0x9c
10        server_srv.so!CCSPlayer::PlayerRunCommand(CUserCmd*, IMoveHelper*) + 0x1d9
11        server_srv.so!CTerrorPlayer::PlayerRunCommand(CUserCmd*, IMoveHelper*) + 0x323

this is still relevant: https://crash.limetech.org/stats/server_srv.so/CSoundPatch::ChangePitch(float,%20float)

This crash is obtained in completely different times. The only thing I saw when the player started using the chainsaw, the server crash, but again, this does not always happen.

Please fix this problem (

**Comment by TyUser** [comment]
I can confirm.

**Comment by MixJay** [comment]
Can confirm this problem too. Server crashes sometimes, when used chainsaw. Last that i heared - loop sound of the chainsaw. Then server crashed...

**Comment by MartLegion** [comment]
I have noticed today that if you use the IncapPlayer function into a client with a chainsaw in use (firing) the server also crashes, don't know if it's related. Just reporting.

**Comment by ProdigySim** [comment]
Based on the coredumps you posted in #3372 , it looks like this is a null pointer dereference.

```
│  >0xedfd46c6  or     DWORD PTR [eax+0x50],0x2                                                                                                                                                                                             
```
this is the instruction crashing, and `eax` is set to `0` in the core dump.

This variable is passed in from some field on `CChainsaw`

Some code like:
```cpp
void CChainsaw::ItemPostFrame() {
  // ... other code
  CSoundEnvelopeController::GetController()->ChangeSoundPitch(this->someSoundPatch, ...);
}
```
(`CSoundController::ChangeSoundPitch()` jumps directly to `CSoundPatch::ChangePitch()`.)

During the crash, this `CSoundPatch* someSoundPatch == NULL`.  

This variable, at offset `6140`, is used for the `"Chainsaw.FullThrottle"` sound:

```cpp
this->StartSound(this + 6140, "Chainsaw.FullThrottle");
```

Perhaps the code should check if the sound is currently available (i.e. non-NULL) before usage?

Do you have any steps to reproduce this crash?

**Comment by ProdigySim** [comment]
Looks like this code is trying to scale the pitch of the chainsaw full-throttle `0.4s` after it hits certain things. Could try to repro by swapping from chainsaw to another weapon--or dropping the chainsaw--shortly after hitting various things.

**Comment by Accelerator74** [comment]
Minidump https://dropmefiles.com/d9neS

**Comment by Accelerator74** [comment]
I can only say my decision against this crash.

In function CChainsaw::ItemPostFrame(void) i patched 39 bytes to nop. From `0x7CD to `0x7FE.
After applying patch, when, for example, without a patch, we use chainsaw on a wall or a zombie, the sound changes. With the patch, the sound is always unchanged, as if we were sawing air.

**Comment by Accelerator74** [comment]
who will need a fall fix (check CSoundPatch ==  NULL):
```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <dhooks>

public void OnPluginStart()
{
	char sPath[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, sPath, sizeof(sPath), "gamedata/chainsaw_fix.txt");
	if( !FileExists(sPath) )
	{
		File hFile = OpenFile(sPath, "w+");

		if( hFile == null )
			SetFailState("Error: Couldn't create gamedata/chainsaw_fix.txt file.");

		hFile.WriteLine("\"Games\"");
		hFile.WriteLine("{");
		hFile.WriteLine("	\"left4dead2\"");
		hFile.WriteLine("	{");
		hFile.WriteLine("		\"Functions\"");
		hFile.WriteLine("		{");
		hFile.WriteLine("			\"CSoundPatch::ChangePitch\"");
		hFile.WriteLine("			{");
		hFile.WriteLine("				\"signature\"		\"CSoundPatch::ChangePitch\"");
		hFile.WriteLine("				\"callconv\"		\"thiscall\"");
		hFile.WriteLine("				\"return\"		\"int\"");
		hFile.WriteLine("				\"this\"			\"address\"");
		hFile.WriteLine("			}");
		hFile.WriteLine("		}");
		hFile.WriteLine("		\"Signatures\"");
		hFile.WriteLine("		{");
		hFile.WriteLine("			/* CSoundPatch::ChangePitch(float, float) */");
		hFile.WriteLine("			\"CSoundPatch::ChangePitch\"");
		hFile.WriteLine("			{");
		hFile.WriteLine("				\"library\"		\"server\"");
		hFile.WriteLine("				\"linux\"			\"@_ZN11CSoundPatch11ChangePitchEff\"");
		hFile.WriteLine("			}");
		hFile.WriteLine("		}");
		hFile.WriteLine("	}");
		hFile.WriteLine("}");

		delete hFile;
	}

	Handle hGameConf = LoadGameConfigFile("chainsaw_fix");
	if( hGameConf == null ) SetFailState("Failed to load gamedata/chainsaw_fix.");
	Handle hDetour = DHookCreateFromConf(hGameConf, "CSoundPatch::ChangePitch");
	if( !hDetour )
		SetFailState("Failed to find \"CSoundPatch::ChangePitch\" signature.");
	if( !DHookEnableDetour(hDetour, false, ChangePitch) )
		SetFailState("Failed to detour \"CSoundPatch::ChangePitch\".");
	delete hDetour;
	delete hGameConf;
}

// CChainsaw::ItemPostFrame() crash fix
public MRESReturn ChangePitch(int pThis, Handle hReturn, Handle hParams)
{
	if(!pThis)
	{
		DHookSetReturn(hReturn, 0);
		return MRES_Supercede;
	}
	
	return MRES_Ignored;
}
```

**Comment by Accelerator74** [comment]
After the update (2.2.1.3) from June 15, 2021, the function on which the crash occurs has changed. Now the crash happens on the `CSoundControllerImp::SoundChangePitch(CSoundPatch *, float, float)` function. The reason is the same as it was, as described by @ProdigySim above. Need to check for `CSoundPach` value is not `NULL`
