### ISSUE TITLE
[HLDMS] Pre-release [Question]

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#2529]
Any idea when Hldms can get out of pre-release mode? We have been here for over 4 years.
Thank's
![hldms_prerelease](https://user-images.githubusercontent.com/5712715/36645505-d0d0eba0-1a37-11e8-97e4-74ef4d58ae9d.png)

**Comment by kisak-valve** [comment]
Hello @1157, **prelease** in brackets indicates you've opted into a beta branch. Right click on the game -> Properties -> Betas -> Select None from the drop down menu.

**Comment by 1157** [comment]
I was told to opt-in (pre-release) to get updates. would be nice to get some things fixed , I think over 4 years is long enough.
