### ISSUE TITLE
[TF2] Skinned weapons occasionally don't have the crit glow or ubercharged texture

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2531]
Occasionally the textures for crit-boosted and ubercharged weapons won't apply on skinned weapons, it seems random.

**Comment by agrastiOs** [comment]
Strange decorated weapons don't get ubercharged.

**Comment by jh34ghu43gu** [comment]
Anyone have this happen to them recently? The March 1, 2023 update fixed @agrastiOs 's reply but not sure if OP's issue still persists. I cannot recall this bug happening in recent memory.

**Comment by kisak-valve** [comment]
Closing pending feedback.
