### ISSUE TITLE
[TF2] [Bug] Checkbox "Only missions not yet completed" broken

### ISSUE THREAD

**Issue by CrazyHackGUT** [ValveSoftware/Source-1-Games#2535]
After something update, this checkbox doesn't work if i one in the lobby:
![default](https://user-images.githubusercontent.com/12576822/37299889-fc7607ce-263d-11e8-837a-11a4c1abaf6c.png)
Mission "Metro Malice" already completed, but the game still adds it to the search.
If i play with someone friend (in lobby), this checkbox works correctly.

P.S.: Sorry for my english if I made any mistakes. I'm from Russia, and learning the English language is given to me more difficult than my native language.

**Comment by CrazyHackGUT** [comment]
Looks like it fixed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
