### ISSUE TITLE
[TF2] Incorrect Badge Shows on HUD

### ISSUE THREAD

**Issue by Harritron** [ValveSoftware/Source-1-Games#2546]
![20180330174210_1](https://user-images.githubusercontent.com/13120164/38157220-04346b24-3442-11e8-99c1-b06b2a444a88.jpg)
Badge in the HUD is different than the real badge (badge in the scoreboard should be tier 2 level 145, but displays as tier 1, level 145).

**Comment by Exaeta** [comment]
Still not fixed... *grumbles unpleasantly*

**Comment by Brownshome** [comment]
How are people supposed to know about how badly I am wasting my life if they can't see my badge tier...

**Comment by stackia** [comment]
same. please fix this 😒

**Comment by Ciriak** [comment]
Still not fixed

**Comment by VirtuaPlastic** [comment]
Feb 2020, still not fixed

**Comment by Ciriak** [comment]
Jun 2020, still not fixed

**Comment by CriticalFlaw** [comment]
The July 3, 2020 update supposedly fixed this issue. Just need someone with tier 2+ badge to retest. 

https://www.teamfortress.com/post.php?id=63061

**Comment by lebrunregis** [comment]
Can confirm it's fixed 
![20200705215551_1](https://user-images.githubusercontent.com/34442304/86541120-ac543780-bf0a-11ea-94e4-c2986dd0e5ce.jpg)

**Comment by CriticalFlaw** [comment]
This ticket can now be closed @kisak-valve can verify it has been fixed.
