### ISSUE TITLE
loadout selection screen, model spinning

### ISSUE THREAD

**Issue by raenii** [ValveSoftware/Source-1-Games#2553]
whenever i try to rotate the class in the loadout selection screen, the class spins in one direction no matter what direction i move the mouse.

edit: this is in team fortress 2

**Comment by kisak-valve** [comment]
Hello @wave98, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please clearly indicate which game you're seeing this behavior with.

**Comment by wave98** [comment]
@kisak-valve [here you go](https://gist.github.com/wave98/02a2ff46851c0881f35522dc3078c6ae)

**Comment by kisak-valve** [comment]
Closing pending feedback.
