### ISSUE TITLE
Model doesn't have attachment.

### ISSUE THREAD

**Issue by JoinedSenses** [ValveSoftware/Source-1-Games#2555]
Console spam. Reported online in tons of places. Occurs a ton, especially on rocket jump servers. Unknown solution.

"Model '(null)' doesn't have attachment 'backblast' to attach particle system 'rocketbackblast' to."

https://i.imgur.com/M1AIciO.png

**Comment by Combine900** [comment]
Can we get a fix for that? It would be a nice thing for the Smissmas 2021 update :)

**Comment by mastercoms** [comment]
This seems to be fixed in the Smissmas 2021 update.

![image](https://user-images.githubusercontent.com/2672245/144531245-2ec11769-44c5-4146-89d5-60747344099e.png)

**Comment by Combine900** [comment]
> This seems to be fixed in the Smissmas 2021 update.
> 
> ![image](https://user-images.githubusercontent.com/2672245/144531245-2ec11769-44c5-4146-89d5-60747344099e.png)

Indeed, i hope they didnt just hide that problem from the dev-console. However @kisak-valve look like this thread can be closed.

**Comment by mastercoms** [comment]
I can confirm that the error message no longer shows in game.

**Comment by JoinedSenses** [comment]
id wager all they did was comment out the print statement rather than fixin the actual issue. anyways, nice to know it doesnt spam console any more.

**Comment by mastercoms** [comment]
It wasn't a meaningful error afaik

**Comment by Combine900** [comment]
Well, can be closed?
