### ISSUE TITLE
[TF2] Destruction PDA HUD model bug.

### ISSUE THREAD

**Issue by matty4kek** [ValveSoftware/Source-1-Games#2564]
Engineer holds the Destruction PDA as if it was the Wrangler.
![20180412191247_1](https://user-images.githubusercontent.com/37917707/38689977-a9f01890-3e85-11e8-85e8-c7a0d7c73cb6.jpg)

EDIT : : It's just for the Destruction PDA, Build PDA is fine.

**Comment by Ashetf2** [comment]
Fixed in December 15, 2023 patch

"Fixed the Engineer's Destruction PDA using the wrong animation in the 3D HUD player model (community fix from gidi30)"

![image](https://github.com/ValveSoftware/Source-1-Games/assets/63692647/6f95d15c-d26b-4133-bad3-aedaf4a8cfda)

**Comment by kisak-valve** [comment]
Closing per the last comment.
