### ISSUE TITLE
[TF2] Last-stage carts on multi-stage Payload Race maps can't be pushed

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2577]
Believe this has been a bug since the Blue Moon update.

**Comment by matty4kek** [comment]
Any way to replicate this so I can test it?

**Comment by FindTheBorealis** [comment]
I've not seen the bug myself, but you can just play any multi-state PLR map and go to the final stage.

**Comment by kisak-valve** [comment]
Hello @FindTheBorealis, if this is a second-hand report, please at least include references to where you heard it, or encourage the other user to report it directly.

**Comment by FindTheBorealis** [comment]
Source [1](https://www.reddit.com/r/tf2/comments/8d6mzi/why_is_nobody_talking_about_broken_payload_race/) and [2](https://www.reddit.com/r/tf2/comments/8djdat/valve_fix_pipeline_pls/), the issue stems from the fixing of capturing points during setup time, it broke some maps with no timer, making setup run indefinitely.

Someone made a fix [plugin](https://forums.alliedmods.net/showthread.php?t=306853):

"What this does is wait until players are able to move at teamplay_round_active, then disables setup if there are no active timers currently in setup."

**Comment by matty4kek** [comment]
I've failed to replicate this bug offline, does this happen 100% of time in Casual?

**Comment by FindTheBorealis** [comment]
Tested on Pipeline, and the cart couldn't move.

**Comment by matty4kek** [comment]
Tested and can confirm, It's a bug on last stages of plr maps. Seems like It get's stuck in "warmup" since warmup doesn't even start.

**Comment by nosoop** [comment]
@kisak-valve This was fixed in the [April 26, 2018 update](http://www.teamfortress.com/post.php?id=39289).

**Comment by kisak-valve** [comment]
Thanks, closing per the last comment.
