### ISSUE TITLE
[CS:GO] Matchmaking: Increase first time match abandoning penality

### ISSUE THREAD

**Issue by incognico** [ValveSoftware/Source-1-Games#2578]
Not a game bug but I don't know where to suggest this else:

Increase the first time match abadoning penality of 30 minutes in MM games.

Lately I had so many matchmaking games where a player of the team abandons the match in the first few rounds thus being forced to play 4v5 for the rest of the game (bots don't really help, they go rouge into their death most of the time anyways).

Since the TF2 matchmaking update, the first time penality for abadoning is 24 hours in that game while in CS:GO it's 30min, 2hours, 24h... IMHO in CS:GO where it's 5v5 and not 6v6 it's a even bigger handicap when one player leaves. I understand it's probably legit to leave if there is a cheater in the other team who is not being kicked but the same holds true for TF2 too.

Maybe 4, 6 or 8 hours for the first time offence would work better. Or just mercilessly use the same penalities as in TF2.

**Comment by kisak-valve** [comment]
Hello @incognico, currently bugs with CS:GO are being tracked at https://github.com/ValveSoftware/csgo-osx-linux and feature requests should go to the forums or send an [email](http://www.valvesoftware.com/email.php) to the CS:GO Team.

Closing as out-of-scope for this issue tracker.
