### ISSUE TITLE
[TF2] Jittery mouse after map change

### ISSUE THREAD

**Issue by DrDoctor13** [ValveSoftware/Source-1-Games#2582]
After the map changes for the first time, the mouse will become extremely jittery for a couple of minutes then it will subside. It then persists through every map change afterwards.

**Comment by kisak-valve** [comment]
Hello @DrDoctor13, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by DrDoctor13** [comment]
https://gist.github.com/DrDoctor13/c43466c86f048b4d96d4718ca9349db7

**Comment by DrDoctor13** [comment]
Further testing: This happens in KDE when playing a YouTube video on my secondary monitor. It doesn't happen in any other native Linux game.

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
