### ISSUE TITLE
[TF2] Visual Casual Badge bug.

### ISSUE THREAD

**Issue by matty4kek** [ValveSoftware/Source-1-Games#2584]
Tier 2-9 badges only show their "colors" in the main menu.

On the scoreboard, the badge looks like a regular Tier 1 badge. Please fix this, so we can actually identify what "tier" other players are.

**Comment by Exaeta** [comment]
This bug still isn't fixed.

**Comment by CriticalFlaw** [comment]
This is the same as https://github.com/ValveSoftware/Source-1-Games/issues/2546

**Comment by kisak-valve** [comment]
Thanks @CriticalFlaw, closing as a duplicate of #2546.
