### ISSUE TITLE
[TF2] [Feature Request] Alphabetically sort the Mute list

### ISSUE THREAD

**Issue by feikname** [ValveSoftware/Source-1-Games#2594]
It's a bit of a pain to mute someone on TF2 in servers with a lot of players because you never know where their name is and many players don't know you can click on the headers to sort. 

Alphabetically sorting the list of players **by default** in the Mute UI would make finding a player much easier.

Additionally, perhaps the already muted players could always appear on top (or bottom) of the list.

I did not confirm, but it seems the Report player UI list also has doesn't sort alphabetically by default, so it would be nice to have it there too if that's not the case already.

**edit:** illustrations below:
<details>
<summary>Before</summary>

![Actual sorting](https://user-images.githubusercontent.com/4926869/41153176-61039830-6aec-11e8-8685-e019ecd4e16f.png)
</details>

<details>
<summary>After</summary>

![Proposed sorting](https://user-images.githubusercontent.com/4926869/41153192-71de2e04-6aec-11e8-8812-5e18dd68b0d1.png)
</details>

**Comment by kisakvalve** [comment]
Good day, I've received word from the VAC team that this is intentional and not open for discussion on Github.

In general VAC issues are not handled on Github in any capacity and further issue reports on this may result in being banned from the Valve Software issue trackers.

**Comment by PazerOP** [comment]
It's probably sorted by userid or entindex by default, but you can sort by name (ascending or descending) by clicking on the "Player Name" header. Still, I think it should do this by default.

**Comment by feikname** [comment]
Ooops, I never realized that the headers are clickable. In this case, I agree the default sorting should be changed to sort ascending by name, both in Mute and in Report interfaces.

Furthermore, the second header in Mute sorts by Properties instead of the much more useful "Is muted", I propose that should be changed as well.

There's also a Properties header on the Report UI, that header should probably be removed or changed to something like "You reported this player recently".

**Comment by CriticalFlaw** [comment]
The July 3, 2020 update added a new Mute Player panel which allows for sorting player names alphabetically.

![image](https://user-images.githubusercontent.com/6818236/86551755-0a394d00-bf14-11ea-966b-38368c32e039.png)

**Comment by PazerOP** [comment]
@CriticalFlaw are they alphabetically sorted by default though? I believe that was the desired behavior.

**Comment by CriticalFlaw** [comment]
@PazerOP It doesn't, it still seems to sort them by an ID. Sorry, I didn't notice that a default sort was the desired behavior. Please disregard.

**Comment by feikname** [comment]
That's my bad, sorry. I updated the issue's description to better reflect that the desired behavior is an alphabetical sorting by default.

**Comment by CriticalFlaw** [comment]
@feikname Should this stay opened? The ability to sort alphabetically has been added a while ago and while that's not the default sort, the user can do so themselves by clicking the header.

**Comment by kisak-valve** [comment]
Closing per the last comment.
