### ISSUE TITLE
Tf2 segfault at launch

### ISSUE THREAD

**Issue by voidplayer** [ValveSoftware/Source-1-Games#2596]
I removed steam and tf2 and reinstalled both. No luck

driver: NVIDIA-Linux-x86_64-396.24

I had to install nvidia driver to 396.18.05 to be able to run tomb raider. I noticed tf2 stopped working

After i was over with tomb raider, I removed the beta driver and installed latest driver from debian repositories (390.48-3). Same problem

I used one env variable I found somewhere to launch steam and it worked! but i cant remember the name. it was 3 or 4 words ```USE_LIBRARIES_SOMETHING_SOMETHING=1 ``` Sorry. I cant remember or find it again (the computer lost power and lost the bash history)

I attach thedifferent outputs:

[This is the strace of launching the game](https://github.com/ValveSoftware/Source-1-Games/files/1977957/tf2.strace.txt)
[This is the output of launching the game](https://github.com/ValveSoftware/Source-1-Games/files/1977959/tf2.manual.launching.txt)
[This is output of steam during the whole thing](https://github.com/ValveSoftware/Source-1-Games/files/1977958/tf2.steam.output.txt)

**Comment by kisak-valve** [comment]
Hello @voidplayer, `~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ./hl2.sh -game tf -steam` may give you more useful terminal spew.

**Comment by voidplayer** [comment]
Im afraid it didnt :(

$ ~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ./hl2.sh -game tf -steam
SDL video target is 'x11'
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system supports the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 4.6.0 NVIDIA 396.24 (4.6.0)
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_ARB_buffer_storage: AVAILABLE
GL_EXT_texture_sRGB_decode: AVAILABLE
/home/birdperson/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh: line 72:  6545 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

**Comment by kisak-valve** [comment]
Please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, if there are any CrashIDs or minidumps (commonly found in `/tmp/dumps`) that may be related to this issue, please put them in an archive and include them as well.

**Comment by voidplayer** [comment]
Please tell me if i can provide any more details. I need my tf2 daily fix :)

system information:
https://gist.github.com/voidplayer/07bca481428d618f6341a28d4c5c84c9

I hope this file is related
```/tmp/dumps/voidplayer_stdout.txt```
https://gist.github.com/voidplayer/aab65b1e74d6a8fb63fe230c873df18d

Thanks!

**Comment by voidplayer** [comment]
Fwiw, I created a new user and installed everything from scratch... it still segfaults :(

**Comment by voidplayer** [comment]
I had already tried, but I tried with this new user with the nvidia-driver from testing 390.48-3. Same problem

Before the upgrade to the beta driver it had started failing

Can you think of any other test I can do to see whats at fault here?

**Comment by lisplord** [comment]
I've got the same problem on AMD/ATI hardware with open source radeon drivers. TF2 works fine with fglrx and outdated mesa/xorg, but with radeon and latest mesa it just can't launch.

**Comment by voidplayer** [comment]
My productivity is skyrocketing without tf2 

I tried latest NVIDIA-Linux-x86_64-390.59.run. Same thing

I also tried to install oldest version of the nvidia driver, but it doesnt seem to work with latests kernels

I guess this is goodbye to my tf2 pro career

**Comment by voidplayer** [comment]
Just a note, other valve games like left 4 dead 2 work just fine

Also, with this much free time im starting my own bussiness

**Comment by kisakvalve** [comment]
Good day, I've received word from the VAC team that this is intentional and not open for discussion on Github.

In general VAC issues are not handled on Github in any capacity and further issue reports on this may result in being banned from the Valve Software issue trackers.

**Comment by voidplayer** [comment]
I tried the different betas

- pre_jungle_inferno: it works!!! but theres no servers available

- prerelease: crash
- no beta opt-in: crash

The first clients are starting to flew into my business. They say they really like how much time I put into their problems

**Comment by voidplayer** [comment]
last update fixed it

Thanks!
