### ISSUE TITLE
Issues with dust on HL2 on linux

### ISSUE THREAD

**Issue by lkreq** [ValveSoftware/Source-1-Games#2597]
I'm having issues with dust/smoke on HL2 where the effect is applied differently in different quadrants of my screen, screenshots are from Episode One but I also saw the same issue on HL2. All other effects/particles are not affected.
 
Running debian testing 4.16 (I also saw the same issues on 4.15) on a G4560, RX460 and Mesa 17.3.9

![20180506195227_1](https://user-images.githubusercontent.com/36826966/39680553-b623ca0e-5167-11e8-9512-ef3ed28d4703.jpg)
![20180506195225_1](https://user-images.githubusercontent.com/36826966/39680554-b645981e-5167-11e8-9ce5-41d884acc44b.jpg)
![20180506195028_1](https://user-images.githubusercontent.com/36826966/39680555-b65e7c6c-5167-11e8-950f-e33cf016b9ff.jpg)
![20180506194712_1](https://user-images.githubusercontent.com/36826966/39680556-b679959c-5167-11e8-9082-b00bb44646ad.jpg)
![20180506194709_1](https://user-images.githubusercontent.com/36826966/39680557-b694e73e-5167-11e8-86c9-9a8bea8d270a.jpg)

**Comment by random2324** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=103814

Again a llvm 5 issue. So bad that no one cares fixing that in Mesa. 
Everyone just hope that users upgrade to llvm 6. 
Too bad for some users, left alone for one year, or longer depending on their distro...

**Comment by lkreq** [comment]
Thanks for the research. Hopefully mesa 18.0.2 will hit buster soon with llvm6.

**Comment by lkreq** [comment]
Just updated to Mesa 18 and all is good.
