### ISSUE TITLE
TF2 settings change themselves

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2601]
TF2 settings don't seem to be saving with regard to graphics and shadow details. They also can't be changed mid match. This is causing some unacceptable lag. I don't have any config files adjusting this.
It keeps changing itself to "high" and lagging.

**Comment by kisak-valve** [comment]
Hello @Exaeta, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Exaeta** [comment]
Update: settings do save (sometimes) I'm not sure why it wasn't saving before, but maybe related to steam sync or something?

**Comment by agrastiOs** [comment]
Do you use an Intel GPU?

**Comment by Exaeta** [comment]
No, I have a GTX 1060. I think it was a problem with steam cloud sync overwriting my settings rather than it being a driver issue, since it was working before? It also started working again (although I'm still noticing lag, just not as much)

**Comment by Exaeta** [comment]
Hasn't happened again since latest steam client update. I donno what happened, but it's not happening now.
