### ISSUE TITLE
r_screenoverlay 0

### ISSUE THREAD

**Issue by fearts** [ValveSoftware/Source-1-Games#2605]
Maps and plugins use this command to clear any overlays on players. However, some server owner is forcing a file download called 0.vmt to:

C:\Steam\steamapps\common\Team Fortress 2\tf\download\materials

Having a file with the name 0 in that location makes r_screenoverlay 0 point to that location and is causing people to have a overlay that looks like this instead of clearing overlays:

https://steamcommunity.com/sharedfiles/filedetails/?id=1347220928
https://steamcommunity.com/sharedfiles/filedetails/?id=1347224201

I don't know if any Valve maps use this command but it would be nice if you put r_screenoverlay 0 it will point to nothing and just clear the overlays.

Content of the file here:

```

"Refract"
{
    "<dx90"
    {
        "$fallbackmaterial" "nature/water_warp01_dx8"
    }
 
    "$refractamount" ".04"
//  "$refracttint" ".25 .47 .32}"
    "$bluramount" "1"
    "$ignorez" "1"
 
    "$scale" "[1 1]"
 
    "$bumpmap" "nature/water_coast01_dudv"
    "$normalmap" "nature/water_coast01_normal"
   
    "$bumpframe" "0"
    "Proxies"
    {
        "TextureScroll"
        {
            "texturescrollvar" "$bumptransform"
            "texturescrollrate" .1
            "texturescrollangle" 45.00
        }
    }
}
```

**Comment by fearts** [comment]
There are 13 files not just one. I attached them here:

[vmts.zip](https://github.com/ValveSoftware/Source-1-Games/files/2042898/vmts.zip)

**Comment by Nephyrin** [comment]
`r_screenoverlay off` is the proper (magic, undocumented) command to clear an overlay.  I will alias `0` to `off` for a future update, as that is the usual convention for source commands/convars.

**Comment by kisakvalve** [comment]
Good day, I've received word from the VAC team that this is intentional and not open for discussion on Github.

In general VAC issues are not handled on Github in any capacity and further issue reports on this may result in being banned from the Valve Software issue trackers.

**Comment by kisak-valve** [comment]
Hello @fearts, per "Updated r_screenoverlay command to accept '0' as well as 'off' to disable overlays. This fixes some community mods that were incorrectly expecting 0 to disable the overlay, resulting in unexpected behavior." in the [2018-06-07](http://www.teamfortress.com/post.php?id=40961) TF2 update, please retest this issue.

**Comment by fearts** [comment]
I have retested this issue and it is now resolved. Thank you.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
