### ISSUE TITLE
[TF2] Community Stamp Donation Panel not displaying properly

### ISSUE THREAD

**Issue by CriticalFlaw** [ValveSoftware/Source-1-Games#2610]
Before checkout, the panel that asks about buying a map stamp is not displaying properly. This effects custom HUDs as well. This is on Windows 10 in 1920x1080 resolution

![20180601215427_1](https://user-images.githubusercontent.com/6818236/40869293-74181f28-65e6-11e8-826e-197ea18029e4.jpg)

**Comment by CriticalFlaw** [comment]
For whateve reason, the height of the panel is dependent on the ypos of **ExplanationLabel** in **resource/ui/stampdonationadd.res**. Changing the ypos from 50 to 150 

![20180602105753_1](https://user-images.githubusercontent.com/6818236/40877733-d4d62fd6-6653-11e8-8d11-52519cc50ff9.jpg)

**Comment by CriticalFlaw** [comment]
I've made a fix for this, but it might not be ideal since the two text boxes are now flipped ("Wow, you've played..." has to be on top). Still though, as a quick fix it should work fine.

![image](https://user-images.githubusercontent.com/6818236/42914834-81757eb4-8aca-11e8-9ea3-e107ebf62398.png)

![image](https://user-images.githubusercontent.com/6818236/42914882-b2cefde6-8aca-11e8-83c8-083f5323a5cf.png)

**Comment by FindTheBorealis** [comment]
This has been fixed in the 2019/03/26 update.

**Comment by CriticalFlaw** [comment]
Tested it myself as well. The panel has been fixed in the latest update. Thank you everyone!
