### ISSUE TITLE
[TF2] m_bShielded no longer available for CObjectSentryGun

### ISSUE THREAD

**Issue by JoinedSenses** [ValveSoftware/Source-1-Games#2614]
Not sure if this prop has been removed - removed ability to enable/disable shield on sentry gun

**Comment by Nephyrin** [comment]
This prop looks to have been removed almost five years ago.  There is a `m_nShieldLevel` prop that accomplishes something similar, but help with that would be more appropriately found on a [modding forum](https://forums.alliedmods.net/).

**Comment by JoinedSenses** [comment]
I see, thanks. Was not aware of how recent the change was. Modifying m_nShieldLevel did not produce the results I was looking for. The same thing was suggested by a member of that community when I brought the question to them yesterday.
