### ISSUE TITLE
[TF2] Badges in Scoreboard Do Not Display Proper Level Tiers

### ISSUE THREAD

**Issue by Harritron** [ValveSoftware/Source-1-Games#2617]
Lots of people have noticed this recently, but after the March 28, 2018 patch (the competitive update), badges in the scoreboard display the incorrect tier. For me, it displays a tier 1 level 77 badge, when the badge on the main menu and the badge next to the XP display the tier 3 badge.

![20180614181921_1](https://user-images.githubusercontent.com/13120164/41494918-211e0b5e-70d9-11e8-9f72-9e2780e6b074.jpg)

Hopefully this can be fixed soon, as people cannot tell what others tiers currently are.

**Comment by kisak-valve** [comment]
Hello @Harritron, I'm failing to see the difference between this and your issue report at #2546. Closing as a duplicate.

**Comment by Harritron** [comment]
Understandable.
