### ISSUE TITLE
Team Fortress 2 - Having p11-kit-modules:i386 installed on debian stretch will cause segfault in TF2

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Source-1-Games#2619]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/5536.
@sovietnorm posted on 2018-06-19T08:52:53:

#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Debian Stretch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

`hl2_linux[12032]: segfault at 58494b50 ip 00000000f75ca3d7 sp 00000000ff92368c error 4 in libc-2.24.so[f748d000+1b1000]`

It will very consistently crash at that address on my system.

I was able to find the issue with 

`    GAME_DEBUGGER="strace -f -e trace=open -o strace.log" %command%`

set as the launch options and looking at the strace file. The last file loaded was

`/usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so`

And then a hard malloc error occurs, causing death.

Other files loaded right before this are;

```
13660 open("/usr/lib/x86_64-linux-gnu/libfakeroot/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/lib/i386-linux-gnu/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/lib/i386-linux-gnu/tls/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/lib/i386-linux-gnu/sse2/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/lib/i386-linux-gnu/libffi.so.6", O_RDONLY|O_CLOEXEC) = 37
13660 open("/proc/sys/crypto/fips_enabled", O_RDONLY) = -1 ENOENT (No such file or directory)
13660 open("/dev/urandom", O_RDONLY)    = 37
13660 open("/etc/pkcs11/pkcs11.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/home/jason/.config/pkcs11/pkcs11.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/home/jason/.config/pkcs11/modules", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/etc/pkcs11/modules", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/share/p11-kit/modules", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 38
13660 open("/usr/share/p11-kit/modules/gnome-keyring.module", O_RDONLY|O_CLOEXEC) = 39
13660 open("/usr/share/p11-kit/modules/p11-kit-trust.module", O_RDONLY|O_CLOEXEC) = 39
```

Immediately after, it will die.

#### Steps for reproducing this issue:

1. Have steam installed
2. Have  p11-kit-modules:i386 (0.23.3-2) installed
3. Attempt to start tf2
4. Watch tf2 die.
5. Remove p11-kit-modules:i386
6. Start tf2
7. Watch TF2 start

**Comment by Nephyrin** [comment]
@sovietnorm Do you have anything interesting in `.config/pkcs11` that might cause additional modules to load?

**Comment by Nephyrin** [comment]
Also, if you are given a crash ID on stdout, or if the game produces any minidumps into `/tmp/dumps`, those would be helpful in narrowing down the problem.

**Comment by sovietnorm** [comment]
Still occurs in build 2957279
Same symptoms, even the address.

**Comment by kisak-valve** [comment]
TF2 segfaults on start

Issue transferred from https://github.com/ValveSoftware/Source-1-Games/issues/2520.
@netfab posted on 2018-02-10T15:47:55:

I did not played TF2 for months. 

Just give it a new try, and TF2 is segfaulting on start \:
> Team Fortress 2/hl2.sh : line 72 :  6403 Segmentation fault  ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

OS \: Gentoo
Steam beta \: no
Drivers \: nvidia-drivers-390.25
System infos \: [here](https://gist.github.com/netfab/077a29e2b7a66da899cfd1efaa9b07ae)
[crash_dump.zip](https://github.com/ValveSoftware/Source-1-Games/files/1713518/crash_dump.zip)

Can someone please have a look ? I do not have any problems with other games. Thanks.
***
@kisak-valve commented on 2018-02-10T16:07:57

Hello @netfab, does `/tmp/dumps/<username>_stdout.txt` have a hint as to what's going on? Do you have the `steamgames_tf2` useflag enabled for games-util/steam-games-meta?

For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so
***
@netfab commented on 2018-02-10T16:20:12

Before the segfault I have some errors concerning gameoverlayrenderer.so LD_PRELOAD \\: [stdout](https://gist.github.com/netfab/bebbdffd95c4121c94b42ae27c4c25da)

> Do you have the steamgames_tf2 useflag enabled for games-util/steam-games-meta?

No, but is it really required since I'm using the steamruntime package ?
***
@netfab commented on 2018-10-25T17:31:35

Hi,

After each TF2 update I'm trying it, but it always crash in the same way.
Since the first post I updated some packages :
 - nvidia-drivers 396.54
 - kernel 4.14.65

I also tried various things, including :
 - deleted all game files, and re-downloaded it
 - -nojoy -nointro -autoconfig -windowed command line options
 - mat_queue_mode "0" or "1"

No result.

I also tried to run it from command line with :
> GAME_DEBUGGER="strace -f -o strace.log" ./hl2.sh

The strace.log ends with segfault after a [futex call](https://gist.github.com/netfab/6ca4304a18ecd8d285278561aa8c5a66).
***
@netfab commented on 2018-10-26T09:24:39

Ok I got it.
On my system, all libraries are built by default with 32 bit support.
Rebuilding app-crypt/p11-kit **without** 32 bit abi makes TF2 run :
> \\# grep x86_32 package.use/*
> package.use/common:app-crypt/p11-kit -abi_x86_32

This is app-crypt/p11-kit-0.23.12.

#2619 is duplicate.

**Comment by Nephyrin** [comment]
If this is occurring for you, could you share the contents of any configuration files in `/etc/pkcs11/`, as well as the list of module files found in `/usr/share/p11-kit/modules/`?

**Comment by netfab** [comment]
I rebuilt app-crypt/p11-kit with 32bit ABI to make the crash appear again.

In **/etc/pkcs11/** directory, I have only this file \: [pkcs11.conf.example](https://gist.github.com/netfab/f65563b67e9480743ab5363a29be9746).
In **/usr/share/p11-kit/modules/** directory, I have only this one \: [p11-kit-trust.module](https://gist.github.com/netfab/4d48d7bd4856b4a82e4b9449e2affcca)

**~/.config/pkcs11/** does not exists. I never tried to customize any user's or system's configuration file for this package.

This is app-crypt/p11-kit version **0.23.12** built with **asn1 libffi trust** useflags (default on gentoo).

**Comment by netfab** [comment]
About 5 years later this seems to not happen anymore here on gentoo.
For other reasons I had to rebuild app-crypt/p11-kit **0.24.1-r1** with 32bit support, and it seems for now that I am able to play TF2 without crash.

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
