### ISSUE TITLE
[TF2] Aimware.net for tf2. Stop hack pls!

### ISSUE THREAD

**Issue by hxsbsu5356n** [ValveSoftware/Source-1-Games#2625]
Undetected cheat since 2014, when it was even released. Cheaters began to move to this software due to the fact that the Lmaobox, Nullcore can be detected soon + not everyone knows aw. Please stop this horror! A lot of cheaters in tf2.

**Comment by hxsbsu5356n** [comment]
Valve i hope that you can stop them. (109.99 CHF = 110,18 USD)

**Comment by Nephyrin** [comment]
This is not the right forum for discussing cheat software.  Please see below for information on reporting information on cheats:

https://support.steampowered.com/kb_article.php?p_faqid=370#report
