### ISSUE TITLE
[TF2] Connect Dialogue Box no longer opening (Resolved with workaround)

### ISSUE THREAD

**Issue by JoinedSenses** [ValveSoftware/Source-1-Games#2628]
~~~Based on a sourcemod function no longer working, SM dev, Psychonic , suggested there is an issue with IServerPluginHelpers::CreateMessage .~~~

~~~SM fuctions are DisplayAskConnectBox()/CreateDialog(), which seems to use this to open the "Accept Connection" ```askconnect_accept``` dialogue window. This breaks plugins with this feature, such as Server Hop.~~~

**Comment by JoinedSenses** [comment]
Update:

This is not an issue with displayaskconnectbox. The reason this happens is because ```cl_showpluginmessages``` now defaults to 0, which is an annoying change; however, Im not sure if this was done for security reasons. I noticed an old issue post from PowerLord which mentioned a few other security flaws related to this, and not sure if that was ever fixed.

**Comment by JoinedSenses** [comment]
I have instead found a workaround by instead taking advantage of the ```redirect``` client command.

**Comment by Nephyrin** [comment]
`cl_showpluginmessages` was intentionally defaulted to zero in a recent update.  It is not needed for redirection as you've noted.
