### ISSUE TITLE
[GMOD] Out of Memory / Failed to lock index buffer in cmeshDX8::LockIndexBuffer

### ISSUE THREAD

**Issue by Alexander88207** [ValveSoftware/Source-1-Games#2643]
I know GMOD shouldnt be here but the facepunch forum isnt helpful
----------------------------------------------------------------------------
I want to join a Litte Sandbox-Server with a few Addons (50) after loading all addons, my game close without a message but i can read in the terminal the game crash with "Out of Memory".

Is this releated to Facepunch or Linux?

Linux : The Game Crash until hit 2,5GB Ram usage

Windows: The Game runs fine with ~1GB Ram usage.

Lower the Graphic Settings or set 8MB Sound Cache in Pulseaudio dont worked for me.
I can also see the message sometimes "Failed to lock vertex buffer"
------------------------------------------------------------------------
Ram: 16GB 2x8GB 1600Mhz
CPU: AMD FX 8350 8x Ghz
GPU: AMD RX 570 4GB VRAM Driver: 18.2.99 AMDGPU enabled by default in Ubuntu 16.04+
Tried in OS: Ubuntu 18.04 and Zorin OS 12.4

**Comment by hogsy** [comment]
Pretty sure Garry's Mod uses it's own fork of the Source Engine does it not? And this is pretty specific to Garry's Mod as well, which isn't a Valve title, so I don't think there's much value in having this issue here.
