### ISSUE TITLE
intermittent stalling in graphics rendering

### ISSUE THREAD

**Issue by robotjunkyard** [ValveSoftware/Source-1-Games#2649]
Reporting for the Linux version of TF2;  I am using Mint 19 and nvidia 390.48 drivers, Linux kernel version 4.15.0-33-generic #36-Ubuntu SMP, 16GB RAM, GPU is a GeForce GTX 750 Ti.  X.Org version 1.19.6.

Description:  rendering seems to completely freeze intermittently.  It only unfreezes after a small number of keypresses and/or mouse clicks.  Note this seems to be SPECIFICALLY TF2's rendering thread -- the _game and gameplay itself does not freeze_:  I can still reliably hear action going on around me (contrast this to the more familiar "entire game stalls and the sound just stutters a short loop of the sound buffer of what was already playing for about two minutes" kind of freeze, which I haven't experienced in years).

This does not happen ONLY during gameplay, _but also in the main menu when not on any server at all_;  clicking the button to search for a Casual server, the UI curiously didn't update, but the sound effects pertaining to finding-a-server eventually played, and only when clicking the mouse a couple times did it show exactly what it should be showing at that point.

There does not seem to be a way to reliably reproduce this at-will, but the longest I've gone _without_ it happening has been about 10-15 minutes.

A short list of various things I've attempted to alleviate this which did NOT work in resolving the issue so far included (not necessarily in order):
- Turning off multicore rendering option in Video settings
- Lowering most graphics settings to lowest possible in Video settings
- Turning off "Sync to VBlank" and "Allow Flipping" in nvidia-settings
- Going offline from Steam Friends
- Disabling the Steam Overlay
- Reverting to regular version of Steam instead of the Beta version
- Turning off demo recording
- Rebooting

It's been over 6 or 7 months since I've last played TF2 and this is an issue I've never experienced prior;  I can't say with any certainty if it was upgrading from Mint 18.3 to 19 that influenced this to happen, or if that's merely a coincidence.

**Comment by kisak-valve** [comment]
Hello @robotjunkyard, what desktop environment are you using?

Separately, it may be worthwhile checking a never version of the nvidia driver.

**Comment by robotjunkyard** [comment]
Interesting.  Here's what I found:
Updated to a manual install of the 390.87 driver, which is the most recent long-term Unix driver that nvidia had on their website.

The result: The issue still persisted, exactly as previously described.

So then I got curious and purged all things nvidia from my system, rebooted, and then installed the older 340.106 driver (my memory may not be 100% correct here, but I _think_ that this was the driver I used most of the time when my OS was Mint 18.3... had the chance to upgrade but never did get around to it).  After installing nvidia 340.106 I played TF2 for many rounds, maybe for 2 or 3 hours.

The result:  This problem didn't manifest at all.  It played smoothly and without any issue whatsoever.

(Also, to answer your other question, I'm using the XFCE4 version of Mint 19, using xfce 4.12 with window manager xfwm4 4.13.0)

**Comment by robotjunkyard** [comment]
Haven't yet made any changes whatsoever from using nvidia-340.106, or any other change to OS configuration since yesterday.  Played TF2 again today and ... the problem came back.  Nothing significant changed with system/video/Xorg configuration at all, so I'm at a loss as to what might be doing it.  As with last time, when the renderer freezes, gameplay is still audibly coherent but graphics do not unfreeze until keyboard and/or mouse input is hit a few times.

Just to rule out a hardware cause, I'm going to be playing TF2 in Windows 7 for a couple of days to see if it repros there too.

**Comment by robotjunkyard** [comment]
No, doesn't happen in Windows 7 at all.  nvidia driver 376.33.

**Comment by robotjunkyard** [comment]
Update:  This might indeed be a driver issue and not necessarily an issue that's arising from within TF2 or the Source engine.

Long story short:  Just tested a buddy's Unity game, and this _exact same thing_ happens in the 64-bit Linux build of his game, but not the 32-bit build (relevant or not, unsure -- TF2's 'hl2_linux' is 32-bit, after all) -- the exact same situation as how it happened in Team Fortress 2.

So I'm not sure who to take this up with now, maybe nvidia has a formal bug report channel I can go to for Linux issues, I'll have to check and just play TF2 in Win7 until it's fixed.

Should this issue be Closed now or...?

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by robotjunkyard** [comment]
I can not, I don't care about TF2 anymore and no longer play it.
