### ISSUE TITLE
Slow tf2 on linux

### ISSUE THREAD

**Issue by voidplayer** [ValveSoftware/Source-1-Games#2656]
Im getting 1-8 fps in the menu. Even less while playing

Everything was running smooth until i run out of space in disk. When this started happening. I freed some space afterwards, but it didnt fix the issue, so something else must be it

nvidia Drivers are installed and nothing else changed in the system when i started having this problem. I tried to reinstall steam client and tf2

I did remember that i copied ~.local/share/config/config.vdf from the old installation to try keep the games installed because i couldnt add the old folder (it kept saying that new steam library folder had to be empty- and it worked!)

- system info:
https://gist.github.com/voidplayer/45412f37370432f28804c36c991490bb

- output after launching tf2 : 
https://gist.github.com/voidplayer/426025b9094bc2c36c5c6a7b2688f53b

- output after starting steam client (i switched to beta in the middle):
https://gist.github.com/voidplayer/96dddaa45eabeaa8ae8c1dc3d2b52b70

I dont know what else to try

Help please!

**Comment by kisak-valve** [comment]
Hello @voidplayer, `Driver: VMware, Inc. llvmpipe (LLVM 6.0, 256 bits)` in your system info indicates that you're not using any gpu. Llvmpipe is mesa's faster cpu renderer and poor performance is expected.

**Comment by voidplayer** [comment]
It worked!

thanks!
