### ISSUE TITLE
[TF2] It's 2018, maybe it is time to fix damn spells already

### ISSUE THREAD

**Issue by roboderpy** [ValveSoftware/Source-1-Games#2664]
* Energy ball spell suck in spectators
* Skeletons are not properly lag compensated
* You get prediction errors and even could stuck for 1 second inside ally skeleton
* Killing with fire of fireball (afterburn) does not count as player damage but as environmental damage (but you still get frag as "Finished off" since fireball itself inflicts damage from the caster)
* Meteor Storm does from little to no damage to MVM Tanks and engineer buildables
* Meteor Storm can easily stuck on non flat surfaces (displacements)
* Under "invisibility" you can still airblast enemies without loosing invisibility
* Invisibility is still producing spy's dead ringer sound
* Coming out of invisibility interrupts next attack of performed within small interval
* some other bugs i don't remember

Frankly, part of the bugs were [documented](https://wiki.teamfortress.com/wiki/Magic_spells#Bugs) before i opened this issue ticket, but most of issues were not present in wiki since i last checked it in 2016

This really got pissed me off finally, after it's very release from 2013

**Comment by kisak-valve** [comment]
Hello @roboderpy, multi-issue issue reports are bad for any issue tracker. Please open separate issues, one issue per issue report.

**Comment by roboderpy** [comment]
This issue is fully related to one small feature, it is overkill to open for each of these paragraphs a separate issue

**Comment by ldesgoui** [comment]
I'd rather important bugs get fixed rather than ones that affect the game once a year.
