### ISSUE TITLE
[TF2] [Linux] datacache.so segfaults "randomly" a while after Screamfortress X update

### ISSUE THREAD

**Issue by FizzBuzz3000** [ValveSoftware/Source-1-Games#2665]
Hello, I've been getting what seems to be random crashing after the recent ScreamFortress X  Update, and dmsg spits this out:

```
hl2_linux[29772]: segfault at 4 ip 00000000edaad855 sp 00000000fff69b70 error 4 in datacache.so[eda82000+77000]
Code: e8 50 33 94 08 85 ff 0f 84 eb fe ff ff e9 33 ff ff ff 8d 76 00 8b 45 0c 89 44 24 04 8b 43 40 83 c0 08 89 04 24 e8 3b 82 01 00 <8b> 78 04 e9 ab fe ff ff 8d 76 00 31 f6 e9 bc fe ff ff 89 f6 8d bc
```

It seems to commonly happen when the zoom-in for the deathcam happens, hope this get fixed!

My specs:
OS: Funtoo Linux
CPU: AMD Ryzen 5 2600 Six-Core @ 3.4GHz
GPU: Radeon RX 580 Series (POLARIS10, DRM 3.26.0, LLVM 6.0.0) using AMDGPU/Mesa 18.2.0-r1
DE: Plasma 5.12.3

I will provide more specs if needed.

**Comment by kisak-valve** [comment]
Hello @FizzBuzz3000, if you can find any CrashIDs or minidumps related to this issue (commonly found in /tmp/dumps/ related to this issue, please put them in an archive and drag and drop the archive into the comment box.

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are SIGSEGV in datacache.so (that's a good thing).

**Comment by Alkaris** [comment]
I came across this error today, not sure if it might be related.

```
traps: hl2_linux[19507] trap divide error ip:369dd3d7 sp:ff8ebedc error:0
```

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
