### ISSUE TITLE
[CRASH] [TF2] Panzer Pants taunt causes memory leak

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2668]
Panzer Pants can crash everyone in the server.

How to reproduce:
1. Use the Panzer Pants taunt for a while.
2. Eventually, people in the server will crash.

If the taunt uses model scale changing, that might cause the crashes.

**Comment by kisak-valve** [comment]
Hello @agrastiOs, per "Fixed a common crash related to the Panzer Pants taunt" in the [2018-10-22](http://www.teamfortress.com/post.php?id=45119) TF2 update, please retest this issue.

**Comment by agrastiOs** [comment]
Haven't experienced any crashes since, this is probably fixed.
