### ISSUE TITLE
[TF2] Stamp XML Leaderboards

### ISSUE THREAD

**Issue by Geit** [ValveSoftware/Source-1-Games#267]
Since Map Stamps were added to TF2, there have been a number of leaderboards available for browsing on the Global Gameplay Stats section for TF2 on steamcommunity.com, these leaderboards display the top 200 stamp owners for each map, however an XML API is also available that responds (by default) with the top 5000 stamp owners and is capable of listing all players that are on the leaderboard

These XML APIs are available at the following location,
[http://steamcommunity.com/stats/TF2/leaderboards/`Leaderboard ID`/?xml=1](http://steamcommunity.com/stats/TF2/leaderboards/30380/?xml=1)
where the Leaderboard ID is one of the following:

| ID | Map | ID | Map | ID | Map |
| --: | :-- | --: | :-- | --: | :-- |
| 30380 | Fastlane | 30386 | Hoodoo | 30392 | Mountain Lab |
| 30381 | Turbine | 30387 | Offblast | 30393 | Mann Manor |
| 30382 | Steel | 30388 | Yukon | 35072 | Nightfall |
| 30383 | Egypt | 30389 | Harvest | 35073 | Frontier |
| 30384 | Junction | 30390 | Freight | 35074 | Lakeside |
| 30385 | Watchtower | 30391 | Coldfront | 79364 | Gullywash |
|  |  |  |  | 117008 | Kong King |

However, all of these Leaderboards, except for Kong King and Gullywash are broken and return incorrect data. There are two distinct causes for this statement, which I've put into sections below.
### Maps that no longer update

Maps affected:
- Frontier
- Lakeside
- Nightfall

These maps have not gained any stamps, or people who own stamps, in a very long time (to be more "precise", they stopped gaining stamps somewhere in between 2012-02-21 and 2013-01-09, when I was not tracking any stamps), leaving me to believe that they have stopped being updated on the back-end. These maps were all added to the game at the [same time](http://wiki.teamfortress.com/wiki/February_24,_2011_Patch).
### Maps that have artificial inflation

Maps **NOT** affected:
- Gullywash
- Kong King

All the maps with stamps attached to them, bar the two listed above, have this issue, which is that they are reporting data that is entirely impossible. Using the historical data I've scraped for the past few years, I found a three day period in which extreme growth occurred.

The graph below shows the growth per hour for "Mann Manor" over the period ranging from 2011-07-19 00:00 to 2011-07-22 23:00. Please note that outside of this range: growth per hour typically had a maximum of 30 per hour.

![](http://imgkk.com/i/jnxf.png)
**The period of growth shown above accounts for 80% of all map stamps recorded for Mann Manor.**

I have no idea what caused this issue, however, by filtering out this period from the data, the value which is returned for the amount of stamps closely correlates to the amount actually earned by the map authors (Who receive about 0.5~0.75 USD per stamp).

Before filtering:
![](http://imgkk.com/i/4_35.png)
After filtering:
![](http://imgkk.com/i/rhcx.png)

I've collated these findings into my stamp tracker at [geit.co.uk](http://stamps.geit.co.uk), so this issue is not as poignant as the one in which maps are not receiving updates at all, which I can't do anything to work around.

PS: I did send this information to Valve before, back in January, however I haven't heard anything since.

**Comment by kisak-valve** [comment]
Hello @Geit, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
