### ISSUE TITLE
Lacking Support for Japanese/Chinese Characters in Team Fortress 2

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#2674]
Currently, for Team Fortress 2, Japanese characters (hiragana, katakana and kanji) are not rendered. This makes reading the chat and plenty of player names impossible. Suspecting that it is a font issue, but not sure why Valve wouldn't be rolling their own font. On the other hand, the fonts used by Steam are general are worse under Linux.

**Comment by huupoke12** [comment]
The problem still exists in-game. While the Steam UI still renders Japanese properly but in TF2, the Japanese characters are invisible. I have Noto CJK installed.

**Comment by yhlfh** [comment]
> installing wqy fonts does help in arch, but I could not see any effect in OpenSUSE 42.3
> 
> in addition to wqy, my system also have noto cjk fonts installed

Installing wqy fonts doesn't work in openSUSE because the font package in openSUSE is the new version, and font name is actually 'WenQuanYi Zen Hei Mono', not 'WenQuanYi Zen Hei. The following lines will fix:
``` 
<match target="pattern">
  <test qual="any" name="family"><string>WenQuanYi Zen Hei</string></test>
  <edit name="family" mode="assign" binding="same"><string>WenQuanYi Micro Hei</string></edit>
</match>
```

**Comment by Tiagoquix** [comment]
Is this still relevant as of 2024?

**Comment by GuestSneezeOSDev** [comment]
is this still an issue i think there is a community of mods that can support it

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by huupoke** [comment]
Just tested. It works when Noto Sans CJK fonts are installed.
