### ISSUE TITLE
[HL2:DM] Server Console errors on startup

### ISSUE THREAD

**Issue by Pricetx** [ValveSoftware/Source-1-Games#269]
Below are a list of console errors generated on the HL2:DM Linux server after a completely fresh install. They represent non-critical errors, but nonetheless it would be good if they were cleaned up at some point.

//I believe these two exist in all linux source servers (TF2, CSS, etc.)
`ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef room_type doesn't point to an existing ConVar`

I believe this is the server looking for steamclient.so in the location that is used by the
  steam desktop client. I'm not sure if this is correct behaviour, but if it is, it's odd that it
  would  be set to give an error if it can't find it, as I imagine most people running servers
 don't also have a steam client installation

`dlopen failed trying to load:
/home/ggo/.steam/sdk32/steamclient.so
with error:
/home/ggo/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory`

//Not sure on this one
`S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.`

**Comment by kisak-valve** [comment]
These log messages are harmless.
