### ISSUE TITLE
[HL2] Feature request: recompile certain maps regarding HDR usage

### ISSUE THREAD

**Issue by Pinsplash** [ValveSoftware/Source-1-Games#2699]
If I remember right, HDR was added to Source in Episode One? Or maybe it was two. Anyway, when it was added, some of the HL2 maps were recompiled to use HDR however when this was done, the data lump(?) for regular lighting got erased. _Please for the love of god_ fix this, it causes anybody with HDR disabled to suddenly enter fullbright when the map loads.

This guide lists affected maps: https://steamcommunity.com/sharedfiles/filedetails/?id=428896861&searchtext=hdr

**Comment by kisak-valve** [comment]
Hello @Pinsplash, this issue is already being tracked at #577. Closing as a duplicate.
