### ISSUE TITLE
TF2: Jittery gameplay

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#27]
Issue transferred from ValveSoftware/steam-for-linux#159
@epitron posted at 2012-12-20T20:19:35Z:

I'm running TF2 on Arch Linux under XFCE4 (compositing disabled) and the latest NVidia drivers (310.19).

TF2 on Windows (with highest video quality settings) runs with a consistent 300fps.
TF2 on Linux (with the lowest video quality settings) runs between 10fps and 300fps.

The FPS seems to correlate to the complexity of the scene. It's very frustrating because whenever I see an enemy (and especially if they're close), the game locks up for a second. It's really hard to kill anyone! :)

Is there any diagnostic information I can give to help sort this out?

**Comment by sergiorgb** [comment]
I think it's only happening to me is that I changed to arch everything smooth and with the propietary Nvidia drivers but TF2 is lagging a lot sound issues and it's unplayable that didn't happened to me in fedora or Kubuntu is there anything I can do to fix it
