### ISSUE TITLE
TF2 vertex buffer crash since Gun Mettle Update

### ISSUE THREAD

**Issue by joeyjojojuniorshabadoo** [ValveSoftware/Source-1-Games#2706]
Since the Gun Mettle Update a few weeks ago my previously stable TF2 install has become extremely unstable. 

The main menu loads normally, but the game crashes while joining a server approximately 80% of the time. The other 20% of the time I'm able to join a server, play for a while, then the game promptly crashes mid round, or during a map change.

Sometimes (not always) I get this error popping up:

`failed to lock vertex buffer in CMeshDX8::LockVertexBuffer: nVertexCount=266, nFirstVertex=0`

I'm running Ubuntu 14.04, Intel graphics, newest Steam client, all game updates applied.

**Comment by Nephyrin** [comment]
We believe this is the same issue as #2212, and should be discussed there.  Today's TF2 update should greatly improve the situation, and Mesa 19.0 has memory usage improvements that should improve things further.
