### ISSUE TITLE
[TF2] [Linux] sound issues

### ISSUE THREAD

**Issue by buyBread** [ValveSoftware/Source-1-Games#2708]
So to sum it up, I have no sound in TF2, unless I either opt into the Steam Beta Update or opt out of it (have to do one of these things as the sound breaks again after I reboot).

[System Information](https://gist.github.com/buyBread/08dece74c07d906ba88ed49a7f1bec5f)

**Comment by kisak-valve** [comment]
Hello @buyBread, this reads like a Steam runtime issue on Arch. Does restarting Steam have the same effect as rebooting?

**Comment by buyBread** [comment]
Nevermind, you can close this, seems like it was an issue on my side.
