### ISSUE TITLE
[HLDMS] Issues status question 

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#2709]
Could someone here send a internal e-mail to check to see if at least the double entity (everything) bug could be fixed. (its been over five years).(I have read the fine print and any issue(s) that are five years old or older can have their status "pinged" (lol)  Sure would be nice to get at least that fixed, Then doors will work,lifts will work and prop physics will behave properly. 

Thanks

**Comment by kisak-valve** [comment]
Hello @1157, proxy requests for the status of an open issue report are not going work. Closing in favor of #1368.
