### ISSUE TITLE
[TF2] Graphics bugs with robot models + specific items

### ISSUE THREAD

**Issue by Tauphi** [ValveSoftware/Source-1-Games#271]
Hello,

I know it's not official supported in TF2, that human players play with robot models, but there are a few community plugins out there which use them... That's the reason why I post it here ....  

There are 3 items which create rendering errors on robot models, two wearables and one weapon:

Heavy - Equipped with definition index 835 - Promo Triad Trinket:
![heavy](https://f.cloud.github.com/assets/3597388/340649/41af346a-9d58-11e2-89ff-dde9469f8225.jpg)

Heavy - Equipped with definition index 814 - The Triad Trinket:
![heavy2](https://f.cloud.github.com/assets/3597388/340654/51826196-9d58-11e2-8f2d-9cf85fdd98c5.jpg)

Scout - Equipped with definition index 448 - The Soda Popper:
![scout1](https://f.cloud.github.com/assets/3597388/340656/5de02a40-9d58-11e2-9881-2ce0cf146511.jpg)
![scout2](https://f.cloud.github.com/assets/3597388/340657/64fcdd00-9d58-11e2-9b56-47b6218c9615.jpg)

100% low priority - Just for boring times :-)
- Andreas

**Comment by kisak-valve** [comment]
Using robot models in this way is undefined behavior. Your mileage may vary.
