### ISSUE TITLE
Half-Life 2 - Black Mesa East: After entering the mantrap, triggers fail to fire

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#2712]
When entering the mantrap for the first time during normal gameplay, the trigger event for the NPC's animation and the audio does not occur and the gameplay is stuck at this event. The decontamination and laser scanning does occur. Reloading the autosave that occured when the Black Mesa East chapter began yielded correct behavior in the mantrap.

**Comment by NULLYUKI** [comment]
Can be closed as the author of the issue has turned into a ghost.
