### ISSUE TITLE
Half-Life 2 - Fire rendering appears to stop mid animation

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#2713]
In scenes like "We Don't Go to Ravenholm" where the fire/propane traps are set, the fire animation will run normally for a short while, then appear to stop and randomly pick up again after a few seconds. The image of the fire doesn't go away it just stays at one image.

System specs:

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3200 Mhz
    3 logical processors
    3 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-23-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Marco
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  NVIDIA Corporation GeForce 8500 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 304.88
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x421
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  16050 Mb

Recent Failure Reports:

**Comment by NULLYUKI** [comment]
Can be closed as the author of the issue has turned into a ghost.
