### ISSUE TITLE
TF2 crashes with SIGILL on a Ryzen 7 1700X

### ISSUE THREAD

**Issue by Tyrewt** [ValveSoftware/Source-1-Games#2725]
After the December 2018 updates I've noticed TF2 randomly closes shortly (approx 10 min) after the game is launched. Initially I thought it was in a match only, but as I compose this report it crashed too (complete exit) while on the main menu. The crash produces no errors and the game must be restarted, but doesn't occur again once started a second time. Verifying integrity of game local game files seems to correct the issue for duration of the session, however, this action must be taken before initially starting the game for the first time.

As TF2 crashes/closes, I've noticed Steam is running the Cloud Sync on TF2. May be related.

In an effort to resolve the issue I disable Cloud Sync, started TF2 with "-autoconfig" and reversed the process. Issue remains.

Current content BuildID: 3418242
Source Engine Build: 4883963
Ubuntu 18.04 Linux Kernel 4.15.0-43-generic

**Comment by kisak-valve** [comment]
Hello @Tyrewt, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, if you find any CrashIDs or minidumps related to this issue (commonly found in /tmp/dumps), please throw them in an archive and drag and drop the archive into the comment box.

It's unlikely Steam's cloud sync is related to your issue.

**Comment by Tyrewt** [comment]
> Hello @Tyrewt, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, if you find any CrashIDs or minidumps related to this issue (commonly found in /tmp/dumps), please throw them in an archive and drag and drop the archive into the comment box.
> 
> It's unlikely Steam's cloud sync is related to your issue.

I've also submitted a bug report in game, does that collect what you request, or shall I do it here as well?

**Comment by Tyrewt** [comment]
<script src="https://gist.github.com/Tyrewt/cfdd63faddcb7b6e04d3c74dd5b10576.js"></script>

[crash_2019010.zip](https://github.com/ValveSoftware/Source-1-Games/files/2738731/crash_2019010.zip)

**Comment by Tyrewt** [comment]
**Update**: Since the January 8, 2019 update, I have not experienced the crash (12+ hours of game play) nor have I ran the Verify Integrity on game files. Perhaps it was the new localization files in the latest update?

**Comment by kisak-valve** [comment]
Glad to hear it's working for you @Tyrewt. If this is a short-term fluke, let me know and we can re-open this issue report.
