### ISSUE TITLE
[TF2 Bug] Contracts Available

### ISSUE THREAD

**Issue by my3t** [ValveSoftware/Source-1-Games#2727]
### The right side of the screen still says *Contracts Available* even though there are none.

![image](https://user-images.githubusercontent.com/33184869/50764935-4227eb80-12af-11e9-8e3f-8e2457e97242.png)

![image](https://user-images.githubusercontent.com/33184869/50764900-23c1f000-12af-11e9-879d-d84966c0b00d.png)

**Comment by agrastiOs** [comment]
@kisak-valve Has been fixed on https://www.teamfortress.com/post.php?id=62459

**Comment by kisak-valve** [comment]
Thanks, closing per `Fixed getting the "Incoming message..." quest HUD notification when you've already completed all available quests` in the linked update.
