### ISSUE TITLE
Windows HL2DM SteamPipe Dedicated Server Crashes upon using Gravity Gun

### ISSUE THREAD

**Issue by StrikerMan780** [ValveSoftware/Source-1-Games#274]
I'm currently trying to run a HL2DM Dedicated server, on Windows Server 2003 x64, and whenever someone attempts to use the gravity gun alt-fire on a prop, the server immediately crashes.

This is what displays in the server console as it freezes:

Missing shutdown function for Sys_InitAuthentication() : Sys_ShutdownAuthenticat
ion()
Missing shutdown function for S_Init() : S_Shutdown()
Missing shutdown function for Decal_Init() : Decal_Shutdown()
Missing shutdown function for InitStudioRender() : ShutdownStudioRender()
Missing shutdown function for StaticPropMgr()->Init() : StaticPropMgr()->Shutdow
n()
Missing shutdown function for modelloader->Init() : modelloader->Shutdown()
Missing shutdown function for InitMaterialSystem() : ShutdownMaterialSystem()
Missing shutdown function for HLTV_Init() : HLTV_Shutdown()
Missing shutdown function for g_Log.Init() : g_Log.Shutdown()
Missing shutdown function for sv.Init( bDedicated ) : sv.Shutdown()
Missing shutdown function for g_GameEventManager.Init() : g_GameEventManager.Shu
tdown()
Missing shutdown function for NET_Init( bDedicated ) : NET_Shutdown()
Missing shutdown function for Key_Init() : Key_Shutdown()
Missing shutdown function for Filter_Init() : Filter_Shutdown()
Missing shutdown function for saverestore->Init() : saverestore->Shutdown()
Missing shutdown function for COM_Init() : COM_Shutdown()
Missing shutdown function for V_Init() : V_Shutdown()
Missing shutdown function for g_pCVar->Init() : g_pCVar->Shutdown()
Missing shutdown function for Cmd_Init() : Cmd_Shutdown()
Missing shutdown function for Cbuf_Init() : Cbuf_Shutdown()
Missing shutdown function for Con_Init() : Con_Shutdown()
Missing shutdown function for Memory_Init() : Memory_Shutdown()
Missing shutdown function for Host_Init( s_bIsDedicated ) : Host_Shutdown()
Missing shutdown function for Sys_InitMemory() : Sys_ShutdownMemory()
Missing shutdown function for Sys_Init() : Sys_Shutdown()
Missing shutdown function for COM_InitFilesystem( info.m_pInitialMod ) : COM_Shu
tdownFileSystem()

**Comment by kisak-valve** [comment]
Hello @StrikerMan780, are you still experiencing this issue? If you are, are you able to collect a backtrace of the crash?

**Comment by kisak-valve** [comment]
Closing pending feedback.
