### ISSUE TITLE
Left 4 dead 2 full screen lags

### ISSUE THREAD

**Issue by peon501** [ValveSoftware/Source-1-Games#2746]
#### Your system information

* Steam client version (build number or date):  ver, 1553209175
* Distribution: Ubuntu 18.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

Week or two before my game was working perfectly, but now It lags and If I go to desktop and back I have empty bar on top of game (when in fullscreen setting) where I can see desktop. Not sure if it is ubuntu bug or stream bug. Also other display modes does not work as it should. If I use windowed mode without border and exit game and run it again I have border(I mean with title) at top of screen so yeah.
![Screenshot from 2019-03-18 02-25-26](https://user-images.githubusercontent.com/1125765/54844762-51c8a500-4ce0-11e9-9c2d-77e8382ec4c4.png)

### EDIT I FOUND HOW TO REPRODUCE LAGS BUG
The main problem I found is 2 displays set up.

That's how I found where the problem is:
![Screenshot from 2019-04-04 16-41-37](https://user-images.githubusercontent.com/1125765/55560305-9b5dba80-56f8-11e9-8178-d6f956752d2d.png)
[Picture 1 : display settings screen]
- Before I play Left 4 Dead 2 I change display settings [Picture 1] in os to show only 1 display (my laptop display).
- After that, I start the game, but then game lags as fuck(probably it is still rendering for 2 displays or something like that maybe even desktop).
- If I restart os with saved 1st. display setting, no lags 60+ fps at all times and smooth as butter.

### If speaking about visible desktop after minimizing and maximizing it still does not fix it.

**Comment by kisak-valve** [comment]
Hello @peon501, the lobby chat issue is already being tracked at #2647, so let's only track the second issue here.

**Comment by peon501** [comment]
@kisak-valve I found how to reproduce lags bug. I edited the main post so scroll up :)

**Comment by peon501** [comment]
Hmm. I just updated all apt and to ubuntu 19.10 and looks like these bugs are gone, but still I need to test more.

**Comment by peon501** [comment]
I dont have problems anymore. So Iam closeing it.
