### ISSUE TITLE
[TF2] Level badge overlaps the text in the main menu (all resolutions)

### ISSUE THREAD

**Issue by Kruphixx** [ValveSoftware/Source-1-Games#2759]

**Comment by CriticalFlaw** [comment]
Could you post a screenshot of this happening please?

**Comment by CriticalFlaw** [comment]
The user is referring to what you see in the screenshot below. The way the panels are sized and layed out, changing the zpos of the text so to not overlap the badge would make the badge unclickable, so I think this was left like this intentionally. 

![image](https://user-images.githubusercontent.com/6818236/86551564-60f25700-bf13-11ea-897f-a22f2948f503.png)
