### ISSUE TITLE
[hldms] Game _text no operation after steampipe

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#2766]
"game_text" no longer works,This is on new maps or old well proven maps. a func_button or a logic_timer
would trigger scrolling text on client's screen, now it has no operation (since steampipe update)
#2 Issue is a "wishlist "for css This issue with Hldms is something that has worked fine for year's.
(till steampipe update)

**Comment by kisak-valve** [comment]
Hello @1157, this is a copy of #1546 and there's no reason to give a different assessment. Closing as a duplicate of #1546 / #2.

**Comment by 1157** [comment]
#2 Issue is a "wishlist "for css This issue with Hldms is something that has worked fine for year's.
(till steampipe update)  #1546 is closed and it is getting mixed up with #2  Game_text and hud text is two different things Game_text is a entity used in Source SDK.
