### ISSUE TITLE
[TF2]  Launch option -novid doesn't work on Linux Mint

### ISSUE THREAD

**Issue by 1337miro** [ValveSoftware/Source-1-Games#2767]
Using the launch option `-novid` doesn't work on Linux Mint 19.1, showing the Valve intro when launching the game.

Currently using XFCE as my DE and OpenBox as my WM.

I am running the game on a GeForce GT 740M using the 418.56 drivers.

**Comment by kisak-valve** [comment]
Possibly related to #2280.

**Comment by kisak-valve** [comment]
Closing pending feedback.
