### ISSUE TITLE
[TF2] MvM Boot camp mission selection tab is truncated

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/Source-1-Games#2775]
You can't read the missions anymore. You can select/deselect them and start searching for a match. Happens after having entered an MvM match, but not always.

**Comment by CriticalFlaw** [comment]
Could you post a screenshot of this please?

**Comment by echaskaris** [comment]
I'll take one as soon as it happens again.

**Comment by echaskaris** [comment]
Here it is, it happened after I finished a mission, match in progress selected, normal bootcamp the only mission selected
![20190715103050_1](https://user-images.githubusercontent.com/30810224/61202004-fe46f080-a6ee-11e9-9a97-e0e1d2c48378.jpg)

**Comment by CriticalFlaw** [comment]
This has been fixed in the [August 11, 2022 Update](https://www.teamfortress.com/post.php?id=141793). This was also reported with a fix in https://github.com/ValveSoftware/Source-1-Games/issues/4125.

**Comment by agrastiOs** [comment]
#4125 was a duplicate.
