### ISSUE TITLE
[TF2] mat_use_compressed_hdr_textures “0” missing sky texture

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Source-1-Games#2783]
When setting mat_use_compressed_hdr_textures to “0”, the skybox texture will be missing, resulting in pink and black squares.

**Comment by shoober420** [comment]
In favor of https://github.com/ValveSoftware/Source-1-Games/issues/1408, I’m going to close this, as it may do the same thing.

**Comment by agrastiOs** [comment]
@shoober420 Should keep this open, this is still a separate issue, even if it could be related.

**Comment by shoober420** [comment]
This doesnt occur in CSS, so it must be exclusive to TF2, although Im not 100% sure about that, since HL2 will not launch for me at the moment. Could you be so kind @agrastiOs, and test this in HL2 to see if the pink and black boxes show up as the sky texture?

**Comment by shoober420** [comment]
Nevermind, I got HL2 too work. This doesnt effect the HL2 branch of games, so it must only be a thing for TF2. Weeeeeeeeeeeeeeeeeeeeeeeird

**Comment by Nephyrin** [comment]
Textures would need to be compiled in a way to support running through the non-compressed path, and weren't authored as such in TF.  

This convar is entirely meant for debugging and isn't meant to be a supported mode.  Even for supported textures, the only affect of disabling this convar would be decreased performance.

**Comment by shoober420** [comment]
Thank you for the explanation.
