### ISSUE TITLE
[TF2] Killcam First Death Will Show %KILLERNAME% (mat_antialias)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Source-1-Games#2784]
Upon joining a server, and dying for the first time, the players name who killed me will always be displayed as %KILLERNAME%. This has been a thing for quite some time, ever since I started playing TF2 on Linux. Its still happening. It’s more than likely the same as this issue.

https://github.com/ValveSoftware/Source-1-Games/issues/74

I can’t officially confirm it happens when you are being dominated for the first time on the server, but I could have sworn this did actually occur upon being dominated the first time in a server. The second time it was normal.

So it seems that %KILLERNAME% and %NEMESISNAME% happen only on first occurrence. When you get killed the first time, and when you get dominated the first time.

**Comment by agrastiOs** [comment]
Also happens on Windows

**Comment by shoober420** [comment]
Dang, I’ll update the title. Thanks for checking @agrastiOs

**Comment by shadyfan0** [comment]
I noticed this issue appears for me if I have Antialiasing mode set to anything different than "None". Also the issue can be fixed ingame by writing "hud_reloadcheme" in console. But has to do that every time you start the game.

**Comment by shoober420** [comment]
I have antialiasing disabled completely on my system, so that can’t be the cause.

**Comment by shadyfan0** [comment]
One more thing that I remember this was related to was that I used to have -dxlevel 81 in launch options. Adding -autoconfig to launch options would fix that, but it would reset your custom settings.

**Comment by shoober420** [comment]
@shadyfan0, I was going through my script, and to my surprise, it was "mat_antialias". You are right. So I tried different settings for this cvar, and came up with these results.

mat_antialias "0" (bug)
mat_antialias "1" (good)
mat_antialias "2" (bug)
mat_antialias "4" (bug)
mat_antialias "8" (bug)

So when you set it to "1", the bug doesnt occur, but every other setting will cause it. I personally play with this setting on "0". Thanks for the help.

**Comment by shadyfan0** [comment]
I solved this by adding hud_reloadscheme in the autoexec.cfg, but this should really be fixed by Valve's side, as not everyone knows how to use autoexec.cfg.

**Comment by kisak-valve** [comment]
Hello, per "Fixed %killername% and other placeholder names sometimes showing up on the kill cam and stats screen" in the [2022-06-21](https://www.teamfortress.com/post.php?id=139819) Team Fortress 2 update, please retest this issue.

**Comment by agrastiOs** [comment]
Didn't get it yet.

**Comment by shadyfan0** [comment]
Not sure if this is related, but there seems to be a similar issue when someone starts a vote: https://steamcommunity.com/sharedfiles/filedetails/?id=2837984723

I don't remember encoutering this while having hud_reloadscheme in the autoexec.cfg. The screenshot is quite recent too: 20 Jul @ 10:39pm

**Comment by kisak-valve** [comment]
Hello @shadyfan0, please open a new issue report so that your issue can be tracked properly.

**Comment by agrastiOs** [comment]
@shoober420, I've been playing the game for a while and didn't experience this issue yet, now that it's patched.
