### ISSUE TITLE
[TF2] [Linux] Item Loadout Screen Sensitivity Way Too High For Character Inspection

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Source-1-Games#2790]
When checking out your character at the item loadout screen to look at your cosmetics and gear, if you attempt to spin the character around with the mouse, he will spin around drastically and at super high speeds. If you try and move the mouse just a tad, it will spin the character almost 90 degrees, making it impossible to be precise, and inspect your characters practically.

**Comment by crwn1337** [comment]
It's really weird, it seems like it doesn't "reset" the mouse distance, the further you move your mouse from the spot you started holding down M1, the faster the character spins.

**Comment by ThisAMJ** [comment]
I'm experiencing this too, just want to mention that changing `m_rawinput` from what it currently is (I turned it off) fixes the issue. The same issue is present in the demo playback 'drive' mode, at least in Portal 2.
Yes I'm aware this is an ancient necropost and I should be hanged immediately.

**Comment by doclic** [comment]
> This has been fixed with the 64-bit update, because the SDL2 library was updated.

Can confirm.

**Comment by Tiagoquix** [comment]
@kisak-valve Here's proof it works correctly now:

https://github.com/ValveSoftware/Source-1-Games/assets/30274161/9275b00b-e267-409e-8c7f-e6eb6d7685ce

**Comment by kisak-valve** [comment]
Closing per the last several comments.

**Comment by le-toast3r** [comment]
after at least a year it's still a thing for me, somehow. no matter if a custom hud is installed or not
