### ISSUE TITLE
[TF2] Game mode goal hints do not appear in Casual, hindering newcomers

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2792]
In Community Servers, when playing a match, at the start of the round on the HUD appears a hint. For example, if playing a Attack/Defense map, the hint for RED will appear: "Defend the Control Points!" For some reason, these hints do not appear in Casual. They were important for new players of TF2 to quickly know what the objective of the game mode is. Considering Casual is now the main way to play TF2, new player friendliness of the game has been reduced.

Steps to reproduce:
1. Go to a Community Server or do a listen server.
2. Notice the hint on the HUD in the start of the round.
3. Go to a Casual match.
4. Notice the lack of a hint in the start of the round.

**Comment by agrastiOs** [comment]
@kisak-valve This can be given a "reviewed" label. Eric Smith, one of the TF2 devs responded to my e-mail mentioning this issue with "We’ll look into it. Thanks for the email."

**Comment by kisak-valve** [comment]
Hello @agrastiOs, per "Fixed not seeing the team-goal hints during Casual matches" in the [2019-07-25](https://store.steampowered.com/news/52741/) TF2 update, please retest this issue.

**Comment by agrastiOs** [comment]
![20190726161319_1](https://user-images.githubusercontent.com/15906773/61954332-4f919280-afc1-11e9-8a2b-d20cb5eacf1f.jpg)

@kisak-valve Fixed, thanks.
