### ISSUE TITLE
[Garry's Mod] [Linux] Requires old libgcrypt (1.5.6) and libpng (1.2.59)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Source-1-Games#2793]
Garry's Mod requires old versions of libgcrypt (1.5.6) and libpng (1.2.59). Please update Garry's Mod to use the modern versions of these libraries (1.8.4 and 1.6.37)

**Comment by kisak-valve** [comment]
Hello @shoober420, issues with Garry's Mod should be reported to the game's dev(s) and you have a general request for the engine at #2787. Closing as out-of-scope.
