### ISSUE TITLE
[TF2] [Linux] ctf_turbine main room strairways will render buggy shadows

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Source-1-Games#2807]
https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

In the main room on ctf_turbine, with the two large stairways, when a player is on them, their shadow will render very buggy at times. It will scatter about and look very odd.

**Comment by kisak-valve** [comment]
Closing pending feedback
