### ISSUE TITLE
[FeatureRequest] sv_hostname as backup for IP changes in server favorite entries

### ISSUE THREAD

**Issue by Tauphi** [ValveSoftware/Source-1-Games#281]
Hello,

When gameservers move to another root server and get a new IP address (by upgrading the root server hardware for example) it's a problem for the owners and players.

Players lose the server entry in their favorite list, because the old IP address is no longer available and the server owners lose their complete playerbase.

It needs a lot of time, money and work to get a server populated and players get frustated when they think, that their most favorite gameserver is offline (simply because they didn't notice the IP change)

I would like to suggest to add a new server cvar called "sv_hostname" which gives the ability to set a hostname for the current gameserver.

Adding a server to the favorites would save it's ip address as usual + it's sv_hostname value. Now when a gameserver gets a new IP address and keeps it's sv_hostname, a client could repair the broken favorite entry.

When a query to a favorite server IP fails, the client could also check the saved hostname. If the IP differs from the saved one and if there's the same gameserver available (same port, same game, (same name as security?)), then update and repair the current broken entry.

The whole community could benefit from a feature like that.
- Andreas

**Comment by kisak-valve** [comment]
Closing in favor of #1566.
