### ISSUE TITLE
L4D2 Linux reverting speaker configuration and launch option bugs

### ISSUE THREAD

**Issue by vargbeaumont** [ValveSoftware/Source-1-Games#2816]
I will start with the speaker configuration issue. By default the game puts my speaker configuration in the audio option on 5.1 speakers however I use stereo earphones so I change it to the headphones option. This works however once you relaunch the game it will revert back to 5.1 speakers. My audio options in Ubuntu are set to analogue stereo.

The second issue I have discovered is the -novid launch option causes L4D2 to launch with a not responding window, this will shortly go away however it tabs you out of the game after a couple flashes, you have to manually tab back into the game.

System information:
```Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.0-23-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20190711.3

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 430.26
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.73" (23.94" diag)
                                            53.1cm x 29.8cm (60.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  7850 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  31368 Mb
    Largest Free Hard Disk Block:  18305 Mb
    VR Headset: None detected

Recent Failure Reports:

```

**Comment by kisak-valve** [comment]
Hello @vargbeaumont, the audio setting issue is already being tracked at #2000.

With regard to the game minimizing on focus loss, this is the expected behavior for all SDL 2 applications.

You can override this with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` in the game's launch options.

Closing in favor of the existing issue report.

**Comment by vargbeaumont** [comment]
@kisak-valve while the command `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` does manage to stop the game from minimising when the program is not responding dialog comes up it doesn't prevent that said dialog.

When the `-novid` command is used on Ubuntu 18.04 and Ubuntu 19.04 the program is not responding dialog will pop up on every launch of both CS: GO and L4D2 and presumably any other Source 1 game.
