### ISSUE TITLE
[Bug] [TF2] Festive Sappers are silent

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2817]
There is a bug with Festive Sappers. They sap silently, unlike the Sapper, thus giving an unfair advantage to the owners of the Festive Sapper.

Why the bug is important to fix?
This gives an unfair advantage to people that bought the Festive Sapper. No weapons in TF2 are supposed to be pay-to-win.

Steps to reproduce:
1. Use a Sapper on the Sentry and observe the sapping sound.
2. Use a Festive Sapper on the Sentry and observe that there is no sapping sound.
This video shows the bug: https://www.youtube.com/watch?v=ZYDwQP55k6Y

**Comment by agrastiOs** [comment]
@kisak-valve This can be given the "Reviewed" label. Eric Smith responded to the e-mail detailing this issue with "We'll look into it."

**Comment by agrastiOs** [comment]
@kisak-valve This can be given the "Reviewed" label. Eric Smith, one of the TF2 devs responded to the e-mail detailing this issue with "We'll look into it. Thanks for the email."

**Comment by agrastiOs** [comment]
@kisak-valve This can be given the "Reviewed" label. Eric Smith, one of the TF2 devs responded to the e-mail detailing this issue with "We'll look into it. Thanks for the email."

**Comment by agrastiOs** [comment]
@kisak-valve Will you give this issue that label? You did give it to #2792 before.

**Comment by agrastiOs** [comment]
@kisak-valve ?

**Comment by agrastiOs** [comment]
@kisak-valve can you respond please?

**Comment by kisak-valve** [comment]
Hello @agrastiOs, I've pondered this request for a bit too long and I don't want to bother the TF2 devs on a regular basis to confirm that they received an email.

Regardless, your feedback is getting to them, either here or via email and the team will prioritize the issues at their discretion.

**Comment by agrastiOs** [comment]
@kisak-valve Alright, thank you for responding. I won't bother you with this issue anymore.

**Comment by agrastiOs** [comment]
@kisak-valve Fixed today.
