### ISSUE TITLE
[TF2] Engineer buildings will not fire OnDestroyed when sapped with a Red-Tape Recorder

### ISSUE THREAD

**Issue by Gamecube762** [ValveSoftware/Source-1-Games#2818]
obj_dispenser will not fire "OnDestroyed" if they are destroyed wit a Red-Tape Recorder. 

I made a small map with to test this with. In the map there are 4 dispensers each with a red box above them. When the dispenser fire's OnDestroyed the box will turn green.

I also made a [short video demonstrating this issue.](https://www.youtube.com/watch?v=DJfzCxN-BnM)
The map can be found at [this gist.](https://gist.github.com/Gamecube762/4310ccf217fda050f393cc3574bd5d63)

Easiest way to reproduce:

1. Download and load the map above
2. Go blue spy
3. Sap a dispencer
4. If the box above the dispencer turned green, then OnDestroyed was fired.

**Comment by Gamecube762** [comment]
I realized I had only tested this on dispensers before submitting. This issue affects all engineer buildings.

**Comment by Gamecube762** [comment]
With the recent code leak, I looked more into this issue.

The issue stems from `tf_obj.cpp` > `CBaseObject::FinishedBuilding` missing a `m_OnDestroyed.FireOutput( info.GetAttacker(), this);` call just before `Killed( info );` is called.

**Comment by kisak-valve** [comment]
Hello @Gamecube762, per "Fixed the OnDestroyed output not getting fired when an object is destroyed by the Red-Tape Recorder" in the [2020-06-16](https://www.teamfortress.com/post.php?id=62459) Team Fortress 2 update, please retest this issue.

**Comment by Gamecube762** [comment]
This issue has been fixed.
