### ISSUE TITLE
[TF2] Multiple teleporter entrances are "buggy"

### ISSUE THREAD

**Issue by Tauphi** [ValveSoftware/Source-1-Games#283]
Hello,

I just want to report a small "bug" with multiple teleporter entrances. This is more a fix request for community/mod stuff, because this effect isn't present on vanilla/offical servers.

When I enable the ability to build more than one teleporter entrance (3 in this example) by modifying the MaxObjects value in the objects.txt...

OBJ_TELEPORTER
{
                [...]
                MaxObjects 3
                [...]
}

...then there is the following "bug" ...
1. I build 3 entrances at first, then the exit -> everything works fine:
   http://cloud-2.steampowered.com/ugc/939249452182621821/16F407570E4B6C8887711CD061C9CD35253FAC68/
   ![t1](https://f.cloud.github.com/assets/3597388/366312/38f67ca8-a27f-11e2-9dac-5e3887e658b2.jpg)
2. I destroy 2 entrances, that only one entrance-exit connection exists -> still fine:
   http://cloud.steampowered.com/ugc/939249452182621011/74B98CCDD82812ACA7E7F27420D5ECDFE72BE418/
   ![440_screenshots_2012-07-11_00002](https://f.cloud.github.com/assets/3597388/366316/58fb373c-a27f-11e2-9743-e3f9f58f05e1.jpg)
3. I rebuild the 2 entrances, but when they get ready they don't get connected to the existing exit:
   http://cloud-2.steampowered.com/ugc/939249452182620049/874425D57922561F8102574E66BAAA04539B2A0E/
   ![440_screenshots_2012-07-11_00003](https://f.cloud.github.com/assets/3597388/366320/76e19dfe-a27f-11e2-9952-b0cea30e3e21.jpg)

Any additional entrance doesn't get connected to it's exit when theres already a connection present. Only destroying and rebuilding the exit activates all entrances.

It worked without any problems a long time ago.

Is there any chance to re-add that "connect everything" stuff when building entrances?
Like it is when building exits?
- Andreas

**Comment by kisak-valve** [comment]
Using multiple teleporters like this is undefined behavior. Your mileage may vary.
