### ISSUE TITLE
[CSS] Sound Failure: appears when someone throws any grenade

### ISSUE THREAD

**Issue by knacki-gizmo123** [ValveSoftware/Source-1-Games#2832]
as the subject line says, a strange annoying sound appears when I (or another player) throw a grenade on any server or map.
of course, i cant make a screenshot
i have a windows 7 installation on a macbook (bootcamp)
other specs:
Windows 7 (Bootcamp)
MacBook Pro 13", middle 2012
Intel HD Graphics 4000 1536 MB
2,5 GHz Intel Core i5 (i5-3210M)
seriesnr: C1MP4P02DTY3

**Comment by knacki-gizmo123** [comment]
ok it seems like the bug is already gone

**Comment by kisak-valve** [comment]
Closing per the last comment.
