### ISSUE TITLE
Question missing Combine Sounds

### ISSUE THREAD

**Issue by karl-police** [ValveSoftware/Source-1-Games#2843]
Which sounds were fixed?

https://store.steampowered.com/news/54632/

> Fixed missing sounds on combine soldiers

Is it okay to ask that, maybe I won't get an answer at all but it's worth a try?

Thanks

**Comment by agrastiOs** [comment]
Combine Soldiers area using their pain sounds again, and they're also saying their 'took minor damage' and 'took major damage' voice lines (COMBINE_COVER and COMBINE_TAUNT in sentences.txt)

@kisak-valve should be closed.
