### ISSUE TITLE
[TF2][Linux]  running tf2 under proton 4.11-6 with d9vk enabled is more performant than native binary

### ISSUE THREAD

**Issue by ovlx** [ValveSoftware/Source-1-Games#2844]
So I was curious to see how it would behave, and was surprised to find that the game runs about with about 50%-75% higher fps (on my machine) under proton with d9vk enabled, compared to the native linux install.

the only problem I found was that the game launches in insecure mode using proton.

I suppose this would be more of a request than a "bug", but perhaps it might be worth investigating whether d9vk can be integrated into the game or eventually switching over to proton as the preferred install option on linux.

**Comment by bkdwt** [comment]
> So I was curious to see how it would behave, and was surprised to find that the game runs about with about 50%-75% higher fps (on my machine) under proton with d9vk enabled, compared to the native linux install.
> 
> the only problem I found was that the game launches in insecure mode using proton.
> 
> I suppose this would be more of a request than a "bug", but perhaps it might be worth investigating whether d9vk can be integrated into the game or eventually switching over to proton as the preferred install option on linux.

Are you using Steam windows version + lutris for play TF2 in DX9 or you just enable the proton on steam for Linux? 

In my case, if I enable proton, the Linux version of TF2 still has priority over the windows version, in other words, I'll play in OpenGL instead of DX9.

**Comment by ovlx** [comment]
I'm using the native Linux client
You can force the windows version by ticking  the "force the use of a steam play compatibility tool" option in tf2's properties menu

**Comment by bkdwt** [comment]
> I'm using the native Linux client
> You can force the windows version by ticking the "force the use of a steam play compatibility tool" option in tf2's properties menu

I tried using dxvk9 on TF2, but the game only shows a black screen or a screen full of artifacts.

**Comment by ovlx** [comment]
make sure you have the correct vulkan drivers installed, it will black screen if d9vk is not enabled.

**Comment by bkdwt** [comment]
> make sure you have the correct vulkan drivers installed, it will black screen if d9vk is not enabled.
> 
> edit also , im using Radv , not sure what would happen on nvidia or intel if applicable

I'm using a RX570 on Fedora 31. Fedora comes with vulkan and mesa libs installed by default with the last version.

**Comment by bkdwt** [comment]
I redid the whole procedure again and now it worked. Regarding performance, there is a lot of falling frames in singleplayer mode. I have no way to test in multiplayer mode because the game is running in "unprotected" mode.

**Comment by ovlx** [comment]
I should also mention that i am using the experimental Fsync patches, so you might want to try disabling esync and see if the frame-drops go away

**Comment by bkdwt** [comment]
> I should also mention that i am using the experimental Fsync patches, so you might want to try disabling esync and see if the frame-drops go away
> 
> edit: for further detail, im using the 5.2 kernel, with futex wait(fsync) on kubuntu 18.04.3 with the latest mesa git
Installed the kernel with fsync support on Fedora. It seems that fsync has made the situation worse because now I can't play even in training mode because the game is running in an insecure mode. lol

**Comment by ovlx** [comment]
> 
> 
> > I should also mention that i am using the experimental Fsync patches, so you might want to try disabling esync and see if the frame-drops go away
> > edit: for further detail, im using the 5.2 kernel, with futex wait(fsync) on kubuntu 18.04.3 with the latest mesa git
> 
> Installed the kernel with fsync support on Fedora. It seems that fsync has made the situation worse because now I can't play even in training mode because the game is running in an insecure mode. lol

strange,  What framerate are you running? and do you have tearfree enabled?  I was running my testing by creating a local server with bots, i noticed slight stuttering  when the framrate dipped below 90fps, but most of the time the framerate was well above 140.

**Comment by ovlx** [comment]
small update, it would appear that the "insecure mode" problem is because steam cannot validate the signature  of the client.dll /server.dll in the tf/bin  folder, strangely, ive run the exact same install of tf2 on stock wine with the windows version of steam and it doesn't have any problems validating  the file, so this appears to be a proton/steam specific issue as seen here https://github.com/ValveSoftware/Proton/issues/2704

**Comment by PineconesUpMyButthole** [comment]
Wait... if you use normal wine steam it works? As in it just starts in secure mode or do you not get VAC banned either? Can i ask how you set it up, and if you did anything weird in the process? What launch settings did you use for tf2?

I've been having a hard time getting tf2 running on my system through wine/dxvk. I can get steam to run in a wineprefix with dxvk installed, but tf2 just crashes and messes up my screen resolution. are there some log files somewhere i should be looking at first?

sorry for so many questions

**Comment by Yetoo1** [comment]
@PineconesUpMyButthole You won't get VAC banned. What I've done in the past is set the Steam Windows executable to be a 64bit wine prefix (with normal wine) and set steam to start with `-no-cef-sandbox` argument and things are smooth from there. Have you tried starting TF2 with `-windowed`, though?

**Comment by PineconesUpMyButthole** [comment]
64-bit wineprefix seems to work a lot better, thanks @Yetoo1. I can see the library/store pages now, they're just a bit glitchy. -no-cef-sandbox doesn't seem to have any effect.

I think i am a lot closer now. However, when I launch I am still getting a few errors about ntlm_auth and a couple X11 BadWindow errors: https://pastebin.com/qv0fg2p6

**Comment by Yetoo1** [comment]
@PineconesUpMyButthole For the ntlm_auth errors, have you installed the `winbind` package (ntlm_auth log message suggests that ntlm_auth can be found there)? Just to confirm, did you start TF2 with `-windowed` as a launch option set via the properties dialog in steam or is TF2 still not launching at all?

**Comment by ovlx** [comment]
an interesting development, looks like valve added the dxvk backend to portal 2 !
some performance numbers are available courtesy  of phoronix https://www.phoronix.com/scan.php?page=article&item=portal-2-radv&num=1

**Comment by Munoida** [comment]
would be awesome if valve added it too tf2....

**Comment by NukeThief** [comment]
Is there any chance it would be added to tf2 and windows?

**Comment by SupinePandora43** [comment]
> Is there any chance it would be added to tf2 and windows?

There's always hope, but looking at recent tf2 updates, there are chances...

**Comment by NukeThief** [comment]
> > Is there any chance it would be added to tf2 and windows?
> 
> There's always hope, but looking at recent tf2 updates, there are chances...

I hope so, Vulkan runs so much better for me.

**Comment by NukeThief** [comment]
if i install dxvk manually in tf2 will i get banned?

**Comment by lflo5727** [comment]
Playing on slightly more limited hardware, having dxvk-native for TF2 would be amazing. 
Hoping its part of the "fixes" being included in the summer update.

**Comment by SpidFightFR** [comment]
+up. Do we have any news about this ?

**Comment by sqrtd** [comment]
Any news about this? The summer update came out yesterday but unfortunately DXVK wasn't a part of it.

**Comment by zurrty** [comment]
Any updates? TF2 is nearly unplayable on my system at the moment performance wise. I'm hoping dxvk-native gets added soon.

**Comment by Evonos** [comment]
Soo... i get sent from Steam support to here... with a question about DXVK on windows about CSS... then get sent to a TF2 Discussion on linux... classic.
any idea to my original question?

**Comment by Noted-Jrelvas** [comment]
Vulkan would be a big improvement for hybrid graphics laptops; Vulkan is multi-gpu aware and is capable of direct scanout and automatically choosing the discrete gpu.

I've also noticed that TF2 on Linux is pretty taxing on the CPU, so anything which reduces the load on that would probably have a big effect. Even though my hardware is more than capable of running TF2 (i7-13800h, nvidia rtx 4000 ada workstation graphics), I still get pretty bad stutters and low performance under certain conditions, like being near a group of player models.

Valve has to either make TF2 work under Proton or ensure feature parity with running it there. (Vulkan/DXVK, Wayland)

**Comment by jrelvas-ipc** [comment]
> Valve has to either make TF2 work under Proton or ensure feature parity with running it there. (Vulkan/DXVK, Wayland)

Aged like fine wine :)

tf2's x64 linux beta implements dxvk-native and ships a newer sdl2 version which is capable of Wayland.

**Comment by ovlx** [comment]
took a while but it happened. retail linux binary now uses dxvk and the game was updated to be 64bit. Guess that closes this chapter!
