### ISSUE TITLE
[TF2/FeatureRequest] Add "Territorial Control" (tc_hydro) into Quickplay

### ISSUE THREAD

**Issue by Tauphi** [ValveSoftware/Source-1-Games#285]
Hello,

I would like to suggest to add a Quickplay option for the game mode "Territorial Control". tc_hydro is a classic TF2 map with normal gameplay (people can use all their wapons, not like in degrootkeep for example), which brings a lot of fun to play.

Since "Special Delivery" contains only one map I don't understand, why you didn't add tc_hydro, too.

Are there any deeper reasons against this map or mode? I'm just curious
- Andreas

**Comment by agrastiOs** [comment]
@kisak-valve TC is already added to Casual. Close this
