### ISSUE TITLE
Characters voices and some voice commands are not played when playing TF2 on Fedora 31

### ISSUE THREAD

**Issue by bkdwt** [ValveSoftware/Source-1-Games#2855]
When running TF2 on Fedora 31, voice commands and other background voices are not played. All other sounds such as ambient sounds, music, and menus play smoothly.

Here a cat from steam executable:
[steam.txt](https://github.com/ValveSoftware/Source-1-Games/files/3722145/steam.txt)

**Comment by kisak-valve** [comment]
Hello @bkdwt, `Warning: MP3 decoder has failed to start. Most likely SELinux is disabling JITing?` is the line of interest in the log, which points towards https://github.com/ValveSoftware/Source-1-Games/issues/1880#issuecomment-149066462.

Please check if `setsebool -P allow_execheap 1` resolves the issue.

**Comment by bkdwt** [comment]
> Hello @bkdwt, `Warning: MP3 decoder has failed to start. Most likely SELinux is disabling JITing?` is the line of interest in the log, which points towards [#1880 (comment)](https://github.com/ValveSoftware/Source-1-Games/issues/1880#issuecomment-149066462).
> 
> Please check if `setsebool -P allow_execheap 1` resolves the issue.

Kisak, many thanks! Now all voice commands are working! :D  

You can close this issue. ;)

**Comment by kisak-valve** [comment]
Thanks for confirming.

**Comment by Doomsdayrs** [comment]
https://wiki.centos.org/TipsAndTricks/SelinuxBooleans

```
allow_execheap (Memory Protection)
    Allow unconfined executables to make their heap memory executable. Doing this is a really bad idea. Probably indicates a badly coded executable, but could indicate an attack. This executable should be reported in bugzilla
```

The practice seems to be a really bad idea as noted by CentOS and Gentoo.
