### ISSUE TITLE
TF2 locked at 60FPS on Fedora 31 with Xorg on fullscreen (vsync off)

### ISSUE THREAD

**Issue by bkdwt** [ValveSoftware/Source-1-Games#2856]
Hi. This problem is not new and only occurs to me only in Fedora. TF2 gets the frame rate locked at 60FPS even with vsync=off and fullscreen, but if I switch to windowed mode, the frame rate gets unlocked.

If I start the gnome-session with Wayland, it works normally but gives a lot of stutters, so I prefer to use Xorg. I'm using Gnome 3.34.1.

[steam.txt](https://github.com/ValveSoftware/Source-1-Games/files/3722721/steam.txt)
[tf2.txt](https://github.com/ValveSoftware/Source-1-Games/files/3722722/tf2.txt)

```
glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.1
OpenGL core profile shading language version string: 4.50
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.1
OpenGL shading language version string: 4.50
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix,
```
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef) (prog-if 00 [VGA controller])
	Subsystem: Gigabyte Technology Co., Ltd Radeon RX 570
	Flags: bus master, fast devsel, latency 0, IRQ 31
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=2M]
	I/O ports at e000 [size=256]
	Memory at f7e00000 (32-bit, non-prefetchable) [size=256K]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
```

**Comment by kisak-valve** [comment]
Hello @bkdwt, can you try adding `vblank_mode=0 %command%` to the game's launch options and retest.

**Comment by bkdwt** [comment]
> Hello @bkdwt, can you try adding `vblank_mode=0 %command%` to the game's launch options and retest.

I already did this, but doesn't solve the problem. :/

**Comment by dragoniansec** [comment]
This is still an issue with Fedora 35. Same exact problem as @bkdwt described.

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by p0p-dog** [comment]
> Hello [@bkdwt](https://github.com/bkdwt), can you try adding `vblank_mode=0 %command%` to the game's launch options and retest.

This worked for me. Thank you.
