### ISSUE TITLE
[HL2] Maps missing lightmaps AGAIN! 2019

### ISSUE THREAD

**Issue by McBean56545** [ValveSoftware/Source-1-Games#2859]
This issue has popped up in the past, and I can confirm that it is a problem with the maps themselves rather than the graphics engine. I had tested this on Garry's Mod and HL2 by going to the maps with broken lighting. The lighting is broken in both GMod and HL2, leading me to believe that the maps themselves are broken. The first map to feature broken lighting is the map that takes place directly after exiting the mines in Ravenholm. I have also noticed that the cubemap reflections have also taken a hit, as they are not present on the guns that have reflective surfaces.

**Comment by kisak-valve** [comment]
Hello @McBean56545, this reads like #2621 or #652. Can you check if one of those already covers your issue or better describe how the lighting issue differs from the existing issue report.

**Comment by kisak-valve** [comment]
Closing in favor of the existing issue reports. If this in not the case, please clarify the difference.
