### ISSUE TITLE
[TF2] [Linux] WM-breaking problems on startup

### ISSUE THREAD

**Issue by stuartpb** [ValveSoftware/Source-1-Games#2861]
Also reported on the [Arch Linux Forums](https://bbs.archlinux.org/viewtopic.php?pid=1868809):

I'm running Steam on GNOME with the AMDGPU driver, and when I launch TF2, it stops acknowledging clicks, and all keyboard input stops. However, audio plays correctly, and, about 50% of the time, the game's UI will still render and animate normally (the other half of the time, the screen freezes on the loading screen, or the initial window).

If I press Ctrl+Alt+F2 and log into ptty2, running `gnome-shell --replace` fails after a while with an X server error (even when specifying DISPLAY). Running `pkill hl2_linux` only causes the audio to stop and the screen to freeze. Even running `sudo systemctl restart display-manager` only works once or twice before trying to log in just kicks me back to the login screen.

The one way I found to work around this issue is to start the game with `-safe` in the launch options (so the game loads in a window instead of fullscreen), and then **switch to another window** between the time when the game window appears and when the game starts loading. If I do this, I can change the options to use fullscreen once the game has started.

**Comment by kisak-valve** [comment]
Hello @stuartpb, is only GNOME 3.34 affected? This reads like the gnome regression being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2187.

**Comment by stuartpb** [comment]
I think I tried this on Budgie Desktop, and it still failed, though that may come from Budgie sharing a lot of the same components as GNOME.

**Comment by kisak-valve** [comment]
Hello @stuartpb, can you update your system and retest this issue? Arch should have picked up the fix for this in mutter.

**Comment by stuartpb** [comment]
One thing I didn't realize when I wrote this is that I was never booting into Wayland, as a side effect of using LightDM as my display manager - after switching to GDM, I no longer had this issue (though I do have a bunch of other issues now...)

**Comment by kisak-valve** [comment]
Thanks for retesting. I've seen Arch, Ubuntu 19.10, and Fedora 31 have GNOME 3.34.

Ubuntu 19.10 is still affected: https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1845302

Arch is fixed: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/mutter&id=16dc45483d3d5044f341b00490608f38c291bbc3 

Fedora 31 is fixed: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FPD6BAZ2BBSHMRDI2NSV4CH4L6TVR3AP/

I'd prefer to wait to close this issue until lp-1845302 is resolved.

**Comment by kisak-valve** [comment]
Per https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1845302/comments/7, mutter has been updated on Ubuntu 19.10.
