### ISSUE TITLE
[TF2] [Linux] Nvidia driver 440.26 crashing TF2 at menu

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2866]
After installing Nvidia driver version 440.26-0ubuntu0~gpu19.10.2, TF2 is crashing while trying to load the main menu.  The following error message is displayed:

![Screenshot_2019-10-20_06-26-14](https://user-images.githubusercontent.com/6024315/67209532-296f6900-f3dd-11e9-98da-a224cf482b46.png)

Console.log shows the following:

```
For FCVAR_REPLICATED, ConVar must be defined in client and game .dlls (sv_use_steam_voice)
ProtoDefs post data loaded.
ProtoDefs loaded. 13.34 MB used
ProtoDefs post data loaded.
ProtoDefs loaded. 13.34 MB used
[TF Workshop] Got 36 subscribed maps, 36 new
maxplayers set to 24
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
FT_New_Memory_Face failed. font:HalfLife2 error:64
Out of memory or address space.  Texture quality setting may be too high.
```

Reverting to driver version 435.21-0ubuntu2 fixes the issue.

**Comment by dotWAVE** [comment]
Do you have issue with any other source 1 game? It happens to me with all of them.

**Comment by nightsky30** [comment]
> Do you have issue with any other source 1 game? It happens to me with all of them.

I had not tried other source 1 games before switching back to 435.xx drivers, but I believe you.  I think it is very possible that it affects them all.

**Comment by dotWAVE** [comment]
My issue turned out to be my filesystem and not my graphics driver.

**Comment by mastercoms** [comment]
This does not happen with Wayland, so it might be a problem the Nvidia xorg driver.

**Comment by nightsky30** [comment]
Maybe same as #2876?

**Comment by mastercoms** [comment]
The issue was not created for this issue, but people commented there about this one since it was the same result (crash on start).

**Comment by mastercoms** [comment]
Seems to be a bug with OpenGL shader linking. If you create a folder in `tf/custom` called `noshaderlinking` and then create two empty files in that folder called `glbaseshaders.cfg` and `glshaders.cfg`, TF2 does not crash.

**Comment by leinardi** [comment]
Can confirm the same issue after upgrading the Nvidia drivers from 435.21 to 440.26.

**Comment by nightsky30** [comment]
Same here. Thanks! @mastercoms

**Comment by huupoke12** [comment]
I have upgraded the driver to 440.36 and it seems that solved the issue. Can anyone else also confirm this?

**Comment by nightsky30** [comment]
> I have upgraded the driver to 440.36 and it seems that solved the issue. Can anyone else also confirm this?

I do see they added a 440.31 package to the PPA within the last day or so.  Not sure why not 440.36, but the latest 440 builds are still 440.26.  I'll try when they update.

**Comment by StidOfficial** [comment]
Same problem on 440.36, i confirm the solution of @mastercoms work :
```
mkdir -p tf/custom/noshaderlinking
touch tf/custom/noshaderlinking/glbaseshaders.cfg
touch tf/custom/noshaderlinking/glshaders.cfg
```

Thanks !

**Comment by kisak-valve** [comment]
Closing as outdated.
