### ISSUE TITLE
[HL2] Discolored shadows

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#2868]
There are many darker corridors or areas where it seems like shadows are overlaying existing shadows or light maps and having discoloration. Here are some examples with arrows to mark what I'm talking about. 

http://web.archive.org/web/20191020194543/https://gist.github.com/Yetoo1/9ceb4bafdd38618f5d75b469fd191dfb

HL2 version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

This was found on a Fedora 30 install. uname -a yields Linux yetoo-Inspiron-570 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
This was reproduced on a Windows 10 1903 install.

Specs are here: http://web.archive.org/web/20191019013218/https://pastebin.com/UAZAxspk
Specs for Windows here: http://web.archive.org/web/20191020123630/https://pastebin.com/upriRckX

**Comment by kisak-valve** [comment]
Hello @Yetoo1, this issue is already being tracked at #632. Closing as a duplicate.
