### ISSUE TITLE
TF2 crashes on load on Linux 

### ISSUE THREAD

**Issue by zeflap** [ValveSoftware/Source-1-Games#2876]
#### Your system information

* Steam client version: appid(steam)/version(1481912289)
* Distribution (e.g. Ubuntu): Debian stretch/sid
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No]Yes
#### Steps for reproducing this issue:

1. Start TF2 on my Debian unstable laptop
2. Get https://gist.github.com/zeflap/91c8fcb145d823e157ed867027105240
3. That's it

Any idea on what's making this happen?

**Comment by kisak-valve** [comment]
Hello @zeflap, are you still experiencing this issue on an up to date system?

**Comment by anders-larsson** [comment]
Hi @kisak-valve,

I've started experiencing the same issue as  original poster. I didn't experience these problems a few days ago and found this thread while searching for an answer.

Logs from starting game using `~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ./hl2.sh -game tf -steam`: http://dpaste.com/0GK9DTV
Dump file: https://send.firefox.com/download/baed858b3617760c/#jzprz0fnDWjnhCrnQhpBXg

Thanks!

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGABRT in linux-gate.so.

**Comment by anders-larsson** [comment]
BTW. I did update my nvidia graphics card driver 2019-10-25 and I don't believe I've attempted to place TF2 before now.

Version: nvidia-drivers-440.26

**Comment by DaneBuson** [comment]
I also had this same crash behaviour immediately after updating to Nvidia 440.26

Other games willl play, but not TF2 ( I have not tried other Source engine games ).

**Comment by Wuerstchen** [comment]
Same problem here.

Dump file: [crash_20191101153434_1.tar.gz](https://github.com/ValveSoftware/Source-1-Games/files/3798358/crash_20191101153434_1.tar.gz)

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "openSUSE Tumbleweed" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.3.7-1-default
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20191007.0

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.26
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x13c0
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  23981 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  226887 Mb
    Largest Free Hard Disk Block:  78480 Mb
    VR Headset: None detected

Steam Linux Runtime Information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/home/niklas/.local/share/Steam",
    "data_path" : "/home/niklas/.local/share/Steam",
    "issues" : [
    ]
  },
  "runtime" : {
    "path" : "/home/niklas/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20191007.0",
    "issues" : [
    ]
  },
  "os-release" : {
    "id" : "opensuse-tumbleweed",
    "id_like" : [
      "opensuse",
      "suse"
    ],
    "name" : "openSUSE Tumbleweed",
    "pretty_name" : "openSUSE Tumbleweed",
    "version_id" : "20191028"
  },
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /home/niklas/.local/share/Steam/ubuntu12_64/libVkLayer_steam_fossilize.so: wrong ELF class: ELFCLASS64\n",
          "renderer" : "GeForce GTX 980",
          "version" : "1.1.119 (device 10de:13c0) (driver 440.104.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce GTX 980/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.26"
        },
        "egl_x11/gl" : {
          "renderer" : "GeForce GTX 980/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.26"
        },
        "egl_x11/glesv2" : {
          "renderer" : "GeForce GTX 980/PCIe/SSE2",
          "version" : "OpenGL ES 3.2 NVIDIA 440.26"
        }
      }
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
        "cannot-load"
      ],
      "library-details" : {
        "libcurl.so.4" : {
          "messages" : "Unable to find the library: /home/niklas/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: undefined symbol: SSL_CTX_set_srp_password, version OPENSSL_1.0.1\n",
          "path" : null,
          "issues" : [
            "cannot-load"
          ]
        }
      },
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /home/niklas/.local/share/Steam/ubuntu12_32/libVkLayer_steam_fossilize.so: wrong ELF class: ELFCLASS32\n",
          "renderer" : "GeForce GTX 980",
          "version" : "1.1.119 (device 10de:13c0) (driver 440.104.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce GTX 980/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.26"
        },
        "egl_x11/gl" : {
          "renderer" : "GeForce GTX 980/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.26"
        },
        "egl_x11/glesv2" : {
          "renderer" : "GeForce GTX 980/PCIe/SSE2",
          "version" : "OpenGL ES 3.2 NVIDIA 440.26"
        }
      }
    }
  },
  "locale-issues" : [
    "i18n-supported-missing",
    "i18n-locales-en-us-missing"
  ],
  "locales" : {
    "<default>" : {
      "resulting-name" : "de_DE.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "resulting-name" : "C.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/10_nvidia.json",
        "library_path" : "libEGL_nvidia.so.0"
      },
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0"
      }
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/etc/vulkan/icd.d/nvidia_icd.json",
        "library_path" : "libGLX_nvidia.so.0",
        "api_version" : "1.1.119"
      }
    ]
  }
}

The Steam Linux Runtime container tool is not installed.
```

**Comment by DaneBuson** [comment]
Updated from 440.26 -> 440.31 - still seems to crash with same msg


[crash_20191104173627_1.dmp.tar.gz](https://github.com/ValveSoftware/Source-1-Games/files/3806845/crash_20191104173627_1.dmp.tar.gz)

**Comment by kiroma** [comment]
I wasn't experiencing this issue before but right after updating to 440.26 I've started crashing as well.

**Comment by kiroma** [comment]
I've made a post on nvidia's Unix drivers forum, [here](https://devtalk.nvidia.com/default/topic/1066054/linux/team-fortress-2-crashes-with-oom-after-update-to-440-26)

**Comment by fbe** [comment]
Can confirm this issue with 440.26/31 on gentoo stable.

Nvidia, the giant master of regressions..

Possible fix: throw broken Nvidia crap out of your window and buy an AMD card :(

**Comment by Ronan-Kelley** [comment]
I'm also seeing this issue after updating my arch install today
`Linux ronan-archbox 5.3.10-arch1-1 #1 SMP PREEMPT Sun, 10 Nov 2019 11:29:38 +0000 x86_64 GNU/Linux
`
I also have the meta-package "steam-runtime-native" installed, and this issue is present both using steam-native and steam-runtime. nvidia driver version is 440.31, card is 1050ti.

I've never had problems with this game before on this machine.

**Comment by mastercoms** [comment]
This does not happen with Wayland, so it might be a problem the Nvidia xorg driver.

**Comment by mastercoms** [comment]
Seems to be a bug with OpenGL shader linking. If you create a folder in `tf/custom` called `noshaderlinking` and then create two empty files in that folder called `glbaseshaders.cfg` and `glshaders.cfg`, TF2 does not crash.

**Comment by tunanachos** [comment]
> Seems to be a bug with OpenGL shader linking. If you create a folder in `tf/custom` called `noshaderlinking` and then create two empty files in that folder called `glbaseshaders.cfg` and `glshaders.cfg`, TF2 does not crash. Then, you can remove the folder once launching successfully.

Bravo. No idea how you figured that out but this is the solution for me :clap:

**Comment by kiroma** [comment]
I have no clue how you managed to figure that out but it works.

**Comment by mastercoms** [comment]
This error prints quite a few times when this bug happens. Still not able to fully figure it out, but it seems like something is causing program arrays to be offset, because of some vertex shaders being skipped over?

```
m_pHardwareShaders was null
CGLMShaderPair::SetProgramPair: Centroid masks differ at link time of vertex shader vertexlit_and_unlit_generic_bump_vs20 and pixel shader shadow_ps20b!
CGLMShaderPair::SetProgramPair: Centroid masks differ at link time of vertex shader vertexlit_and_unlit_generic_bump_vs20 and pixel shader lightmappedgeneric_ps20b!
```

**Comment by ChildishGiant** [comment]
I still get a crash when loading into a map around 1/10 times. Mesa drivers, not nvidia.

**Comment by shelchang** [comment]
Getting the "out of memory or address space" bug again after a recent Arch update. Currently on mesa 22.3.3-1.

> Seems to be a bug with OpenGL shader linking. If you create a folder in `tf/custom` called `noshaderlinking` and then create two empty files in that folder called `glbaseshaders.cfg` and `glshaders.cfg`, TF2 does not crash. Then, you can remove the folder once launching successfully.

This fixed the crash while loading into a server, but now the game throws the error and crashes unexpectedly in the middle of a game.

Before the update I was running mastercomfig's TF2 config on medium-high with no issues, but now I get the out of memory error if I use anything above medium.

**Comment by kisak-valve** [comment]
Closing pending feedback.
