### ISSUE TITLE
TF2 crashes right after the intro screen

### ISSUE THREAD

**Issue by xHatchx** [ValveSoftware/Source-1-Games#2882]
I'm trying to run TF2 on Artix Linux (basically arch with openrc), but it keeps crashing after the intro screen.
[My system info.](https://gist.github.com/xHatchx/fb6dee720373cf93ddb357437ccea698)
[Output when launching tf2 using ./hl2.sh](https://gist.github.com/xHatchx/fa805d07716aff2790bbb986aab2e37c)

**Comment by kisak-valve** [comment]
Hello @xHatchx, you're running Steam with the steam runtime disabled. This is an unsupported configuration. Please completely close Steam and retest with `steam-runtime`.

Additionally, please check if `/tmp/<username>_stdout.txt` has any interesting hints.

**Comment by kisak-valve** [comment]
In terms of Navi support, your kernel is very old bleeding edge build. It may be worthwhile to try something newer and mainline.

**Comment by xHatchx** [comment]
I ran steam via `steam-runtime`, switched over to Plasma and upgraded my kernel to

**Comment by xHatchx** [comment]
Oh well, after another `pacman -Syu`, something (mesa i think) got upgraded and it works again. Weird...
