### ISSUE TITLE
[CS:S] Errors in game console after open game

### ISSUE THREAD

**Issue by kilroy98** [ValveSoftware/Source-1-Games#2894]
Hud element 'CHudVote' doesn't have an entry 'CHudVote' in scripts/HudLayout.res
Unknown command "cl_thirdperson"
Can't use cheat cvar cam_snapto in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_ideallag in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdelta in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdist in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistright in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistup in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_collision in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxdistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_mindistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthowidth in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthoheight in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cl_upspeed in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cl_forwardspeed in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cl_backspeed in multiplayer, unless the server has sv_cheats set to 1.
Unknown command "weapon_accuracy_logging"
Unknown command "weapon_accuracy_model"
Unknown command "mat_spewalloc

**Comment by kisak-valve** [comment]
Hello @kilroy98, like #268, these messages are harmless. Are you seeing a functional issue?

**Comment by kilroy98** [comment]
Hello @kisak-valve, no.
