### ISSUE TITLE
[TF2] Inspect Item sometimes does not show items

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2903]
[TF2] Inspect Item sometimes does not show items.  Other items load fine.

https://gist.github.com/nightsky30/d6e5e435c7825f7c5d1570e51930cfba

![missing_item_model](https://user-images.githubusercontent.com/6024315/69395339-3fa26a80-0ca4-11ea-9650-5696b44bab0f.png)
![Item_model_fine](https://user-images.githubusercontent.com/6024315/69395345-4204c480-0ca4-11ea-9ace-af1f483c941d.png)

**Comment by kisak-valve** [comment]
Hello @nightsky30, this issue is already being tracked at #2341. Feel free to add which items you're seeing this to the existing issue report.

Closing as a duplicate.

**Comment by nightsky30** [comment]
Ah thanks!  Sorry, I did actually try finding prev reports before submitting.  I'll see what I can find regarding the items and add them there.
