### ISSUE TITLE
[TF2] Contracker Sometimes Loads With UI Issues

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2905]
[TF2] Contracker Sometimes Loads With UI Issues.  This happens rarely.

https://gist.github.com/nightsky30/d6e5e435c7825f7c5d1570e51930cfba

![contracker_wonky](https://user-images.githubusercontent.com/6024315/69395484-b8a1c200-0ca4-11ea-8c45-b97398cb503c.png)

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
