### ISSUE TITLE
[TF2] Gas Passer can sometimes be equipped though not usable before gauge fills

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2906]
[TF2] Gas Passer can sometimes be equipped though not usable before gauge fills.  This seems to happen and is repeatable at the beginning of matches ??

https://gist.github.com/nightsky30/d6e5e435c7825f7c5d1570e51930cfba

![Screenshot_2019-11-18_17-05-00](https://user-images.githubusercontent.com/6024315/69395595-1fbf7680-0ca5-11ea-9ced-672fe6f54599.png)
![Screenshot_2019-11-18_17-43-39](https://user-images.githubusercontent.com/6024315/69395598-22ba6700-0ca5-11ea-8f18-54ffc588409b.png)

**Comment by CriticalFlaw** [comment]
This issue has been previously reported here: https://github.com/ValveSoftware/Source-1-Games/issues/2622

**Comment by kisak-valve** [comment]
Thanks @CriticalFlaw, closing in favor of the older issue report.
