### ISSUE TITLE
[TF2 Beta] Bots refuse to spawn after two rounds of Highlander King of the Hill

### ISSUE THREAD

**Issue by Nightgunner5** [ValveSoftware/Source-1-Games#292]
![image](https://f.cloud.github.com/assets/638796/377393/7afef4d0-a4a6-11e2-83a6-46b4c4df277e.png)

(screenshot is of lolcano, but it happens on all koth maps)

server.cfg:

```
host_thread_mode 2
sv_downloadurl "http://192.168.1.97/fastdl/"

tf_bot_kick all
tf_bot_join_after_player 0
tf_bot_quota 18
tf_bot_difficulty 3
//tf_bot_force_class auto
tf_bot_keep_class_after_death 1

mp_highlander 1
mp_idledealmethod 0
mp_stalemate_enable 1
mp_timelimit 30

tv_enable 1
tv_transmitall 1
tv_delaymapchange 30

replay_enable 1
replay_fileserver_offload_enable    "0"
replay_local_fileserver_path        "/usr/share/nginx/html/replay"
replay_fileserver_host          "192.168.1.79"
replay_fileserver_port          "80"
replay_fileserver_path          "/replay"
```

After two more-or-less normal rounds of king of the hill, the bots all get stuck in a perpetual state of being dead with no selected class (the names are given by a sourcemod plugin whenever they spawn, which hasn't happened since the end of the second round). The "replays are now being recorded" message pops up, followed almost immediately by a message that says that replays are no longer being recorded. After that, nothing of interest.

**Comment by kisak-valve** [comment]
Hello @Nightgunner5, are you still experiencing this issue?

**Comment by BenLubar** [comment]
@kisak-valve Honestly, I haven't played TF2 in years. I have no idea.

**Comment by kisak-valve** [comment]
Closing pending feedback this is still occuring.

**Comment by BenLubar** [comment]
@kisak-valve I am @Nightgunner5.
