### ISSUE TITLE
[HL:S] Fully extended Barnacle tongue can only be rendered if moving in and out of room.

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#2939]
I'm not sure what exactly is going on with this bug, but Barnacle tongue in a room initially show retracted/short length when they are actually the full length. Going under a retracted tongue will yield the full tongue pulling the player up. The way this is fixed if one leaves a room and goes back in or noclips in and out of the viewable bush. Here is an example on c1a1c:
Here are the far line of barnacles (also the other barnacles) in a retracted state when they are really fully extended:
![20191207235740_1](https://user-images.githubusercontent.com/12403440/70386505-16453800-194e-11ea-834b-9257fc3762da.jpg)
The player goes back in through the door to the previous area and leaves the flowing sewer area:
![20191207235819_1](https://user-images.githubusercontent.com/12403440/70386513-3543ca00-194e-11ea-9cae-b0a1934a4ba2.jpg)
The player goes back through door back to the flowing sewer with all the barnacles in the room extended:
![20191207235826_1](https://user-images.githubusercontent.com/12403440/70386574-9ff50580-194e-11ea-8d89-7b60d7697d72.jpg)
![20191207235830_1](https://user-images.githubusercontent.com/12403440/70386572-99668e00-194e-11ea-978f-fd9f2d684fa9.jpg)

HL:S Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

System info here:
https://web.archive.org/web/20191207232514/https://pastebin.com/qJ5SPXg3

**Comment by kisak-valve** [comment]
Hello @Yetoo1, this issue reads like #1193. Closing as a duplicate.

**Comment by Yetoo1** [comment]
> Hello @Yetoo1, this issue reads like #1193. Closing as a duplicate.

This has nothing to do with the tentacle npc nor that issue, this is solely barnacles who's full length tongue disappears for some reason and full length reappears when entering back into the room after leaving.

**Comment by Yetoo1** [comment]
> Hello @Yetoo1, this issue reads like #1193. Closing as a duplicate.

I've removed all instances of tentacle in the bug report.

**Comment by kisak-valve** [comment]
Sorry to do this again, but this issue is already being tracked at #1272. Closing as a duplicate.
