### ISSUE TITLE
[TF2] [MvM] Wave 666 bots take up to 30 slots

### ISSUE THREAD

**Issue by goosmurf** [ValveSoftware/Source-1-Games#301]
Since the 4th April update my 24x7 Wave 666 server has been regularly running into situation where it appears to be spawning so many bots that it ends up taking up all but 2 slots.

I have not been able to catch this problem starting, but during the buildup the console shows a lot of this message:

CreatePlayerBot: Unable to create bot TFBot - CreateFakeClient() returned NULL.

What happens is that as players leave their slot is taken up by a bot (shown in 'status') and the server goes from 6/6 players to 5/5, 4/4 etc until it eventually ends up as 2/2 and ultimately 0/2 as players quit.  At this point attempting to change maps (to reset everything) causes the server to crash.

I was running SourceMod on this server but have since disabled it to rule out MM/SM issues - i.e. the server exhibits this behaviour even _without_ SourceMod.  Server has been running in this 24x7 Wave 666 config for several months.

Ubuntu 11.10 64 bit.

**Comment by kisak-valve** [comment]
Hello @goosmurf, are you still experiencing this issue?

**Comment by goosmurf** [comment]
Lol this bug was opened over 3.5 years ago and I stopped playing TF2 a year ago due to the lack of support and general disdain shown towards community server operators.
