### ISSUE TITLE
[L4D2] Fails to start: "Could not find required OpenGL entry point"

### ISSUE THREAD

**Issue by chinoto** [ValveSoftware/Source-1-Games#3030]
I get an error dialog and a message in the terminal when attempting to launch Left 4 Dead 2.
Dialog: `Could not find required OpenGL entry point 'glGetError'! Either your video card is unsupported, or your OpenGL driver needs to be updated`
Terminal: `PROBLEM: You appear to have OpenGL 0.0.0, but we need at least 2.0.0!`

From what I can tell, the error I'm getting means the game thinks I don't have an OpenGL driver at all, which I do. The driver worked before and still does for other Source games such as Half-Life 2, Portal 2, and Team Fortress 2 as well as some more intensive games like Serious Sam Fusion and Tomb Raider. I actually had this issue a month ago and hoped it was just temporary, but after a lot of digging and now having the same issue happen with the Garry's Mod x86-64 beta*, I've decided to submit a bug report. *works normally, just trying to fix lua's "not enough memory" issue

I've tried disabling the Steam overlay and these launch options to fix it.
```
MESA_GL_VERSION_OVERRIDE=4.1
MESA_GLSL_VERSION_OVERRIDE=4.1
LIBGL_DRIVERS_PATH="/usr/lib64/dri:/usr/lib/dri"
```

I tried getting more information, but it didn't look helpful.
`LIBGL_DEBUG=verbose LD_DEBUG=bindings`

Various sources claimed that removing these steam runtime files can fix issues with Mesa. I've since ran `steam --reset`.
`find ~/Steam/ubuntu12_{32,64} | grep -E '(libstdc++|libgcc_s|libxcb).so' | xargs rm`

I tried making sure I wasn't missing any packages by running ldd on the runtime libraries, L4D2's hl2_linux, and L4D2's libraries in bin/. Also tried and failed to use `STEAM_RUNTIME=0 steam`.
https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Debugging_shared_libraries

Possibly duplicate/relevant issues.
https://github.com/ValveSoftware/Source-1-Games/issues/299
https://github.com/ValveSoftware/Source-1-Games/issues/1844

I tried to use the Steam system information tool, but when I try to copy the information, Steam crashes...
```
Form Factor: Laptop
CPU: Intel(R) Core(TM) i5-5200U
GPU: Intel(R) HD Graphics 5500 (Broadwell GT2)
OS: openSUSE 15.1 64 bit
Kernel: 4.12.14-lp151.28.32-default
DE/WM: KDE/Kwin
Mesa: git20191227 from https://build.opensuse.org/project/show/home:khnazile:video (happens with openSUSE's own version as well)
Driver: i965
Filesystem: Btrfs
```
glxinfo: https://pastebin.com/53pM0eUD

**Comment by khnazile** [comment]
I believe the root of the problem is within libglvnd package, but I have no idea how to debug this.

**Comment by khnazile** [comment]
Ok, I've figured this out: it's SDL2 fails to initialize EGL. I don't know why this is happening, but that's the issue. I've removed SDL2 from my repo, switch back to distro package or any other third-party SDL2 package. It seems that SDL2 is only affected is built against newer Mesa/libglvnd.

**Comment by chinoto** [comment]
That fixed it, thanks, and thanks for the up to date Mesa repo! I thought I had tried completely disabling your repository and switching everything back, but apparently not.

Btw, how did you come across this issue?
Would it be possible to add the [Gallium3D based Iris driver](https://www.phoronix.com/scan.php?page=news_item&px=Mesa-20.0-Defaults-Intel-G3D) to your repo? I've had little luck figuring out how to compile Mesa myself.
