### ISSUE TITLE
[CS:S] de_dust 2 Box Flickering Issue

### ISSUE THREAD

**Issue by natko1** [ValveSoftware/Source-1-Games#305]
![240_screenshots_2013-04-08_00001](https://f.cloud.github.com/assets/4186392/394470/377018a2-a7c1-11e2-8a81-06e1c38fa5f0.jpg)

See the screenshot, been happening for a while now. There are a couple of other boxes it's happening to as well.

**Comment by kisak-valve** [comment]
Hello @natko1, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
