### ISSUE TITLE
[L4D2][Linux]Tunnel vision/Darkness glitch

### ISSUE THREAD

**Issue by peon501** [ValveSoftware/Source-1-Games#3050]
**OS:** Ubuntu 19.10
**Desktop:** KDE
The screen darkens and it's really hard to see after that.
So you use a flashlight and see like in a tunnel.
The screen just fades to darker (I think it fades, and I think in 1-2 sec) and then you can't do anything about it.
It's like you lost some shade of colors because on flashlight or light spites you can see lines separating shades around.
You have to [alt] + [f4] because it affects the whole game, not only one round.

Also, I meet some people in-game who know this bug.
It might be the same on Windows.

ps. I don't have a screenshot, but it happens from time to time.

**Comment by kisak-valve** [comment]
Hello @peon501, this issue is already being tracked at #2737. Closing as a duplicate.
