### ISSUE TITLE
[HL:S] [HL2] [LC] [EP1] [EP2] [Linux] Executing cl_soundscape_printdebuginfo in console in main menu or map crashes game

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#3059]
Executing cl_soundscape_printdebuginfo in console in the main menu or a map crashes game. This is reproducible in every new instance of the games this issue occurs in.

HL:S Version:
Build Label:           5377866   # Uniquely identifies each build
Network PatchVersion:  5377866   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version

HL2 Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

LC Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

EP1 Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

EP2 Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

System info here:
https://web.archive.org/web/20200101232850/https://pastebin.com/i7S7xp1e

**Comment by kisak-valve** [comment]
Hello @Yetoo1, I'm not seeing enough difference between this issue report and #3057 to justify having it split into two issue reports. Feel free to add a note to the older issue report with how the behavior varies between titles.
