### ISSUE TITLE
Throwing Guilottine Console Error [STEAMPIPE]

### ISSUE THREAD

**Issue by DontWannaName** [ValveSoftware/Source-1-Games#306]
In the steampipe beta, throwing this item results in this red console error:

Failed to find attachment point specified for particle effect anim event. Trying to spawn effect 'energydrink_splash' on attachment named 'drink_spray'

**Comment by kisak-valve** [comment]
Hello @DontWannaName, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
