### ISSUE TITLE
[CS:S/VPK] Map loading regression (Engine Crash) V_AppendSlash.

### ISSUE THREAD

**Issue by KyleSanderson** [ValveSoftware/Source-1-Games#310]
http://www10.pic-upload.de/19.04.13/f7izeyz6tp2c.png

Clients on Windows and Mac platforms are unable to load custom maps. Im not sure if its from them placing content on their own or not, but I've had at least 6 people report the problem. I can provide more pictures of different maps, on different platforms, if requested. I'm not sure if Linux suffers from the same regression.

**Comment by kisak-valve** [comment]
Hello @KyleSanderson, @hansmi, are either of you still experiencing this issue?

**Comment by hansmi** [comment]
@kisak-valve I'd have to re-test myself, but I am no longer using Mac OS X

**Comment by kisak-valve** [comment]
Closing pending feedback.
