### ISSUE TITLE
[TF2] Unable to change fov and other viewmodel related settings after a competitive match has ended until game restart

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#3148]
Playing competitive restricts the FOV to 75 and forces the drawing of the view model most likely as well as other settings I am not aware of. However, these restrictions remain even after leaving competitive and the only way to change them is to restart the game. This is very annoying if custom settings want to be used when playing casual matches or other between every competitive game. I like setting the FOV 90 and use cl_first_person_uses_world_model 1, but I can't use these after a competitive game because the restriction persists after the match ended. It would be great if the settings that competitive restricts would stay in competitive and change back to the user defined values after the match has ended. 

TF2 Version:
Build Label:           5615298   # Uniquely identifies each build
Network PatchVersion:  5615298   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:        5615298
Server AppID:           232250
Client version:        5615298
Client AppID:              440

System info here:
http://web.archive.org/web/20200104055738/https://pastebin.com/GyuQddLm

**Comment by CriticalFlaw** [comment]
This has already been reported in #2544

**Comment by kisak-valve** [comment]
Thanks @CriticalFlaw, closing in favor of the older issue report.
