### ISSUE TITLE
Can't see text written in Russian on Manjaro Linux (KDE).

### ISSUE THREAD

**Issue by r1ddle1** [ValveSoftware/Source-1-Games#3156]
Dear TF2 Developers, 
I have got a problem. I can not see some text on Russian. I am using Manjaro Linux. The system language is English. For example, I can see the name of the rocket launcher but I can't see the description of the weapon.
![image](https://user-images.githubusercontent.com/46493085/73138048-6ba8e600-406f-11ea-8e3a-58b089dc31f8.png)

**Comment by r1ddle1** [comment]
![Screenshot_20200126_191248](https://user-images.githubusercontent.com/46493085/73138102-fa1d6780-406f-11ea-99af-340e275e873a.png)
![image](https://user-images.githubusercontent.com/46493085/73138108-0ef9fb00-4070-11ea-9c4b-b4e4baf1906b.png)

**Comment by kisak-valve** [comment]
Hello @r1ddle1, can you check if https://github.com/ValveSoftware/Source-1-Games/issues/153#issuecomment-18713374 has an effect?

**Comment by r1ddle1** [comment]
It didn't help me

**Comment by r1ddle1** [comment]
I think it's problem of KDE because I have the same error in Half-Life 1
![image](https://user-images.githubusercontent.com/46493085/73139544-188b5f00-4080-11ea-87e3-a4df6be66bb5.png)

**Comment by r1ddle1** [comment]
So I've removed Manjaro and installed Kubuntu 19 and I don't have problems on Kubuntu with fonts. I don't know if I should close this topic?

**Comment by kisak-valve** [comment]
Hello @r1ddle1, glad to hear you got it working. I'm going to close this because there isn't a test case anymore and there aren't any clues in this issue report as to what went wrong.

Closing per the last comment.
