### ISSUE TITLE
[TF2 MvM] Missions starting with 'event' can be selected from voting menu on mvm_coaltown

### ISSUE THREAD

**Issue by CompyMcKitties** [ValveSoftware/Source-1-Games#316]
http://steamcommunity.com/sharedfiles/filedetails/?id=142403567 (Updated screenshot)
The 'event' mission ($TF2/scripts/population/mvm_coaltown_event.pop) as shown on the 
changemission vote menu is actually the 'normal' mission for the map mvm_coaltown_event. Other missions that start with 'event' that show in the menu on mvm_coaltown are custom missions for the map mvm_coaltown_event.

If the vote for 'event' passes on mvm_coaltown, the server loads the mission, runs it, but will stop spawning bots mid-wave.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
