### ISSUE TITLE
[TF2] Shortstop shove damage counts as self-damage

### ISSUE THREAD

**Issue by TheBoctor** [ValveSoftware/Source-1-Games#3162]
When a scout wielding the Shortstop successfully pushes an enemy player with their alternate fire, the damage dealer is set incorrectly. The last time I tested, this also meant that the Gas Passer's explosion upgrade could teamkill the originating pyro, in Mann Vs. Machine. All that needs to happen is that a scout shoves a gasoline-coated robot.

I understand MvM (and TF2 for that matter) is currently "unmanned," but understanding this behavior might be useful to community server owners or modders, if not the TF Team.

**Comment by nosoop** [comment]
Addressed in the update on 2022-07-07:
> - Fixed The Shortstop shove showing as self-inflicted damage

**Comment by thejaviertc** [comment]
Now it's fixed, video created by shounic:

https://youtube.com/clip/UgkxqfkRYYJwmYWlgjqmnxU3uFY0kKW1Cran

**Comment by agrastiOs** [comment]
@TheBoctor
