### ISSUE TITLE
[TF2 MvM] Wrong popfile loaded on map change after completing a mission

### ISSUE THREAD

**Issue by CompyMcKitties** [ValveSoftware/Source-1-Games#317]
After completing a mission, the server changes to the next map as specified in the missioncycle specified by tf_mvm_missioncyclefile, but it loads the normal popfile regardless of what popfile is set to be loaded for the next map.

Here's an example of this happening:
Example missioncycle: http://pastebin.com/grCjR7xe
The team completes mvm_decoy_expert1 on mvm_decoy. Then, the server changes to the next map, mvm_coaltown. Instead of loading the popfile mvm_coaltown_intermediate during the change, it loads mvm_coaltown (popfile) instead.

However, the command tf_mvm_nextmission loads the next map and popfile as expected.

**Comment by agrastiOs** [comment]
@kisak-valve Fixed on latest patch.

**Comment by kisak-valve** [comment]
Closing per the last comment.
