### ISSUE TITLE
TF2: Loose Cannon can still push enemies around during truces on Halloween maps

### ISSUE THREAD

**Issue by Pinsplash** [ValveSoftware/Source-1-Games#3172]

**Comment by kisak-valve** [comment]
Hello @Pinsplash, per "Fixed players receiving knockback from enemy weapons during a truce" in the [2021-11-15](https://www.teamfortress.com/post.php?id=101361) TF2 update, please retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed.
