### ISSUE TITLE
[CS:S] buildcubemaps concommand nolonger functions properly

### ISSUE THREAD

**Issue by KyleSanderson** [ValveSoftware/Source-1-Games#318]
According to reports, the command buildcubemaps will still go through the process of building cube maps, but they're never added to the BSP. Upon the automatic reconnection, the map will be the exact same as it was before the command was issued.

**Comment by kisak-valve** [comment]
Hello, can someone confirm if this is still an active issue?

**Comment by KyleSanderson** [comment]
@kisak-valve not complaining, but if you're going to comment on every issue just asking if they're reproducible years later; can't you check yourself?

**Comment by kisak-valve** [comment]
@KyleSanderson, not every issue, but yes, there is going to be a large amount of requests for retesting in the effort to improve the signal-to-noise ratio in this issue tracker.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2015-11-09 update](http://store.steampowered.com/news/19249/).

**Comment by KyleSanderson** [comment]
@kisak-valve that's for HL2:DM.

**Comment by kisak-valve** [comment]
Thanks for catching that @KyleSanderson, I updated the link.
