### ISSUE TITLE
TF2 MvM: +2s Uber Duration upgrade does not function with Vaccinator

### ISSUE THREAD

**Issue by Startacker** [ValveSoftware/Source-1-Games#3180]
https://www.youtube.com/watch?v=7M42W_pqFg4

**Comment by kisak-valve** [comment]
Hello, per "Fixed Übercharge charge rate and duration upgrade not working for the Vaccinator" in the [2022-07-07](https://www.teamfortress.com/post.php?id=140004) Team Fortress 2 update, please retest this issue.

**Comment by Startacker** [comment]
Retested on the 2022-07-07 update, issue has been resolved and the Vaccinator now benefits from the upgrade. Thanks much!

Video for posterity: https://www.youtube.com/watch?v=9Zf9wdTgI3o

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.
