### ISSUE TITLE
voice chat vgui breaks on resolution change

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/Source-1-Games#321]
Similar issue to https://github.com/ValveSoftware/Source-1-Games/issues/320 changing resolution doesn’t cause the speaker texture to resize, so you get a cropped symbol

![2013-04-23_00010](https://f.cloud.github.com/assets/7708/417140/c3d4f510-ac5d-11e2-91d5-70fb1a74679a.jpg)
![2013-04-23_00009](https://f.cloud.github.com/assets/7708/417141/ce014250-ac5d-11e2-9275-f1f50faab35b.jpg)

This is on the latest TF2 steampipe beta.
sysinfo https://gist.github.com/johndrinkwater/4721913

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
