### ISSUE TITLE
[Source 1 Engine] [Linux] Sound gets off sync and stutters if computer lags/freezes too much for a long duration of time

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#3211]
I tend to reach my maximum ram capacity a lot and so I swap a lot. During these times my whole system lags and sound output in a Source game or other programs skip. When this happens while a Source 1 game is open, after the swapping and lag/freeze has finished, the sound in the game gets off sync and stutters and persists even after the game is restarted (and sometimes after a reboot but that may be another issue with snd_mixahead and is rare). To resolve the sync issue and stutters, `pulseaudio -kD` or a reboot usually work until the next time I lag intensely due to swaps. However, the game needs to be closed before the aforementioned command is run or else the audio is silent. The other programs that output sound don't skip and don't have sync issues after the intense swap, it's just the Source 1 game. L4D2 seems the least affected by this from what I've tested, but if the lag is long enough (freeze essentially due to swapping (like 3 - 5 minutes or longer)) then, most of the time, it will have sync and audio issues. Though, sometimes the audio issues occur in shorter periods of lag/freeze. Essentially, it would be great if the audio didn't get off sync and stutter if the system freezes/skips for a period due to swapping or other resource demanding task.

System info here:
https://web.archive.org/web/20200221005747/https://pastebin.com/MHNqqxRV

**Comment by kisak-valve** [comment]
Hello @Yetoo1, if pulseaudio puts itself into a bad state and persists until the daemon is restarted, then it's an issue for pulseaudio to resolve.

**Comment by Yetoo1** [comment]
I reported this bug on the pulseaudio issue tracker here:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/811
