### ISSUE TITLE
[Linux][Srcds] Cheching multiple directories for ibcurl.so.4

### ISSUE THREAD

**Issue by DanielMowitz** [ValveSoftware/Source-1-Games#3218]
Today I tried running the srcds for TF2 on Fedora 30. It crashed and didn't produce any helpful logs. After some search i found a fix: 
`ln -s /usr/lib/libcurl.so.4 /usr/lib/libcurl-gnutls.so.4`
Would it be possible to check more than one directory for these object files, so the server works easily on distros other than ubuntu?

**Comment by kisak-valve** [comment]
Hello @DanielMowitz, in 2017, the srcds dedicated servers transitioned to expecting the [Steam runtime](https://github.com/ValveSoftware/steam-runtime/) or similar environment to run. It sounds like you've had luck running outside of that, but it's not considered a supported configuration.

References:
https://www.mail-archive.com/hlds@list.valvesoftware.com/msg56664.html
https://www.mail-archive.com/hlds@list.valvesoftware.com/msg57214.html
