### ISSUE TITLE
[HL2] Closed Captions doesn't work for Brazilian Portuguese

### ISSUE THREAD

**Issue by floppyD** [ValveSoftware/Source-1-Games#3224]
Since this game has been released, people have been following guides like [these](https://steamcommunity.com/sharedfiles/filedetails/?id=293351385) to get CCs working, by creating files based on the official Portuguese (PT-PT) translation or just renaming the files from the English language. The issue occurs if the Steam language is set to Brazilian Portuguese, which makes the game look for files that doesn't exist.

Example:
`CLocalizedStringTable::AddFile() failed to load file "resource/closecaption_brazilian.txt".`

A quick fix would be just setting the subtitles language to English if there are no files for the target language, and in the case of PT-BR, just using PT-PT files, since both languages are very similar, just like EN-US and EN-UK.

**Comment by Perkzitos** [comment]
This also occurs with Portal 1 and Portal 2.

**Comment by floppyD** [comment]
Looks like there are official Brazilian Portuguese CCs in HL2 and Portal 1/2 now, so this issue is solved.
