### ISSUE TITLE
Option to enable HD models in Half-Life: Source completely missing.

### ISSUE THREAD

**Issue by T-P0SE** [ValveSoftware/Source-1-Games#3226]
![Half-Life_ Source + Uplink Extended 3_1_2020 12_08_01 PM](https://user-images.githubusercontent.com/62455125/77218027-51760c00-6ae4-11ea-80a4-ad0980074a99.png)
As seen above the option to enable HD content is missing. Verifying the game cache and a full reinstall failed to fix the issue.

**Comment by 1157** [comment]
Not sure what operating system you are using, but on Windows the HD option is working fine on the latest build.but Linux is reporting it is on by default, do you see the M4 in game or a Mp5 .
https://github.com/ValveSoftware/steam-for-linux/issues/891
![hls_hd_page](https://user-images.githubusercontent.com/5712715/77370610-a362a000-6d37-11ea-8cae-ede6069c3dde.jpg)
![build_id_hls](https://user-images.githubusercontent.com/5712715/77370619-a8bfea80-6d37-11ea-94cd-f109d706f6f2.png)

**Comment by T-P0SE** [comment]
Running on Windows 10 currently. Perhaps the text file relating to what content is placed onto the menu was corrupted to some extent? No clue why a full reinstall wouldn't replace it with a functional one.

**Comment by Yetoo1** [comment]
@T-P0SE Are you running out of space on the drive/is the filesystem in good health/is drive in good health via S.M.A.R.T?

**Comment by T-P0SE** [comment]
@Yetoo1 Hard Drive has plenty of room, filesystem is fully functional, and drive status is ok.

**Comment by chipsnapper** [comment]
Check your game version string. You can do this by typing 'version' into the Console.
Here is my string, where the HD pack option is visible:
`] version
Build Label:           5377866   # Uniquely identifies each build
Network PatchVersion:  5377866   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
`

**Comment by T-P0SE** [comment]
Version is identical.

Build Label:           5377866   # Uniquely identifies each build
Network PatchVersion:  5377866   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version

**Comment by Thegoldenwolf1999** [comment]
I found a working fix you have to delete the hl and hl_hd then verify the files

**Comment by T-P0SE** [comment]
> I found a working fix you have to delete the hl and hl_hd then verify the files

That seems to have done it! Not sure why verifying the game without deleting the files didn't work but you're a lifesaver. Appreciate the help!

**Comment by Thegoldenwolf1999** [comment]
No problem!
