### ISSUE TITLE
[TF2] Pre-match warmup score and other stat counters don't increment on scoreboard

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#3237]
During the pre-match warmup, the score counter next to each player on the scoreboard doesn't increment, only at the bottom where the player stats for the match are displayed are the deaths and kills counted but nothing else (like damage done, etc...). This inevitably resets and works as normal after warmup ends, but it's annoying since its harder to get a gauge of the other player's skill before a match starts. Also, it's annoying that this works fine in CS:GO, but not here. Here are some screenshots during the pre-match warmup showing the discrepancy:
Notice my one kill and player stats but no score: 
![20200414143102_1](https://user-images.githubusercontent.com/12403440/79277992-bc0a3580-7e5f-11ea-901c-1ae55b14a6d6.jpg)
Notice my three kills and player stats but no score:
![20191231204203_1](https://user-images.githubusercontent.com/12403440/79278051-d0e6c900-7e5f-11ea-919a-61c1be81ae71.jpg)

TF2 Version:
Build Label: 5799494 # Uniquely identifies each build
Network PatchVersion: 5799494 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version
Server version: 5799494
Server AppID: 232250
Client version: 5799494
Client AppID: 440

System information:
https://web.archive.org/web/20200408111054/https://pastebin.com/9cSnadag

**Comment by kisak-valve** [comment]
Hello @Yetoo1, this does not read like a bug.

**Comment by Yetoo1** [comment]
> Hello @Yetoo1, this does not read like a bug.

@kisak-valve I updated my comment, please verify to reopen.
