### ISSUE TITLE
[TF2] Charged Medigun effects aren't reset upon death

### ISSUE THREAD

**Issue by dirkd** [ValveSoftware/Source-1-Games#324]
For some weeks now I've encountered the bug, that the audiovisual effects on fully charged mediguns aren't reset properly when you die while having it selected. It happens on both the Windows and Linux version of TF2 (can't test on OSX).

**Steps to reproduce**:
- Join a game, join a team and choose to play medic
- Get your Medigun (or Kritzkrieg/QuickFix/Vaccinator) fully charged
- Kill yourself having your fully charged medigun selected
- The sizzling sounds and particle effects persist for the rest of the game session (even after changing class)

Console spew that might be related (output when medigun is fully charged):
`Model '(null)' doesn't have attachment 'muzzle' to attach particle system 'medicgun_invulnstatus_fullcharge_blue' to.`

**Workarounds**:
- `snd_restart` to get rid of the sounds (Which unfortunately isn't side-effect free either. I had a player going invisible client-side, probably b/c I used the command while he was spawning [untested wild guess]; on Linux it simply closes TF2 for me)
- `record foo; stop` to get rid of the particle effects

The issue also happens if you use the charge and die before it is fully depleted.

If I recall correctly this was the case many, many updates ago, so this might be a regression.

[System information](https://gist.github.com/dirkd/ce7bd1280aa561394988)

**Comment by kisak-valve** [comment]
Closing per the last comment.
