### ISSUE TITLE
Left 4 Dead 2 detecting wrong speaker configuration upon startup and ignoring last speaker configuration selection on the latest LTS release of Ubuntu

### ISSUE THREAD

**Issue by ContentPersonality2** [ValveSoftware/Source-1-Games#3244]
I am not sure why this happens. On the OS level my audio output is set to my motherboards builtin audio output with the analogue stereo output profile selected however every time I launch Left 4 Dead 2 the in-game speaker configuration setting gets set to 5.1 speakers instead of either 2 speakers or headphones.

This raises two issues. The first issue is Left 4 Dead 2 doesn't save the selection you chose prier in the speaker configuration setting, instead it determines the setting on each launch regardless to what you chose to set it to previously. The second issue is Left 4 Dead 2 isn't detecting the correct speaker configuration in the first place.

**Steps to produce issue:**

1. Launch Left 4 Dead 2
2. Change the speaker configuration setting from 5.1 speakers to headphones
3. Quit Left 4 Dead 2
4. Launch Left 4 Dead 2

**What's expected to happen:** Left 4 Dead 2 remembers you've selected headphones under the speaker configuration setting.

**What actually happens:** Left 4 Dead 2 incorrectly assumes you're using 5.1 speakers and changes your previous selection.

This is a somewhat annoying issue because the only solution is to change this setting every time you launch the game. I really hope this issue is looked into further and possible fixed. Best regards, a long time Left 4 Dead 2 fan.

**Comment by kisak-valve** [comment]
Hello @ContentPersonality2, this issue is already being tracked at #1881. Closing as a duplicate.
