### ISSUE TITLE
csgo host_timer_spin_ms

### ISSUE THREAD

**Issue by makefury** [ValveSoftware/Source-1-Games#325]
This command is currently missing in csgo, but available in all other builds of the engine, should we expect the other games to eventually drop this command? Or is it not included for specific reasons within csgo?

TF2
"host_timer_spin_ms" = "0" ( def. "0" )
- Use CPU busy-loop for improved timer precision (dedicated only)

CSGO
host_timer_spin_ms
Unknown command "host_timer_spin_ms"

**Comment by makefury** [comment]
Bump.

**Comment by kisak-valve** [comment]
CS:GO is not covered by this issue tracker. Closing.
