### ISSUE TITLE
[TF2] [Issue] Stickybombs can be hidden inside the new memorial statues

### ISSUE THREAD

**Issue by matsGitGot** [ValveSoftware/Source-1-Games#3253]
Hello, I found an issue regarding the new statues added to commemorate Rick May's passing:

The statues have no projectile collision, so you can hide stickybombs traps inside of them. This is consistent throughout all of the statues, and you can reproduce it by simply shooting stickies into the statue and detonating them. Though it isn't too major, I can see this being used to grief others, especially since a lot of people are standing around the statues at this time.

Here's footage of it being used: https://streamable.com/wk3prh

**Comment by Yetoo1** [comment]
Is this still an issue since the statues got removed?

**Comment by kisak-valve** [comment]
Closing per the last comment.
