### ISSUE TITLE
[TF2] [Bug] Cosmetics unequipping themselves from player's inventory

### ISSUE THREAD

**Issue by lebrunregis** [ValveSoftware/Source-1-Games#3267]
Users are reporting their cosmetic items unequipping themselves, in various different ways, like all slots from all classes, one randomly or sniper's second and third slots only.

**Comment by AzureAzel** [comment]
This occurs when a player who's cosmetics are conflicting joins a match, usually with modified game files. The server treats those slots as invalid for every person on the server but said player. It happens typically when you get near the player who has modified game files, or at least within render distance.

**Comment by lebrunregis** [comment]
It seems like it's been further documented before in [this post](https://www.reddit.com/r/tf2/comments/exl6nh/the_complete_anticheater_guide/).

In case the post disappears here's a quote of what has been written about it : 

> Custom Item Schema : This is one of the more destructive cheats, in my opinion. Custom Item Schema basically allows cheater to load custom schema. This allows the cheater to, add backpack slots, which actually tricks steam into thinking the backpack slots are genuine, they could remove equip region restrictions, and more stuff. MASSIVE NOTE: CHEATERS WHO REMOVE EQUIP REGION RESTRICTIONS AND EQUIP HATS IN MISPLACED REGIONS CAN CAUSE OTHER PLAYERS TO UNEQUIP HATS AND MISCS. This happens when anyone looks at the cheater's loadout. If the cheater removed the equip region and, say for example, put 3 hats, they can cause other players to unequip hats and miscs when they look at the cheater.

**Comment by agrastiOs** [comment]
@kisak-valve Fixed in https://www.teamfortress.com/post.php?id=63061

**Comment by kisak-valve** [comment]
Thanks, closing per `Fixed a bug where cosmetic items in the second and third equip slots would be un-equipped` in the linked update.
