### ISSUE TITLE
[TF2] URGENT! Joining a community server while leaving a casual game is impossible

### ISSUE THREAD

**Issue by MisterVector** [ValveSoftware/Source-1-Games#3268]
When joining someone elses game on a community server while currently in a casual match is not possible. While the server is loading, the countdown timer to put you back into a casual game starts counting down, meanwhile you can't even stop the timer. By the time you get into the community server the timer has already elapsed and you are placed back into the casual server.

Edit: I used the "Auto-Join when slots are available" feature when attempting to join their server. I played some casual to have some fun while waiting for available slots.

THIS NEEDS TO BE ADDRESSED ASAP!

**Comment by Pinsplash** [comment]
Already tracked at #2821, and not urgent.

**Comment by kisak-valve** [comment]
Thanks @Pinsplash, closing in favor of the older issue report.

**Comment by MisterVector** [comment]
I appreciate the response, thanks!
