### ISSUE TITLE
[HL2DM] [WINDOWS] snd_restart crashes game

### ISSUE THREAD

**Issue by Apollyon094** [ValveSoftware/Source-1-Games#3272]
This one server added a new audio file to the FastDL and anytime you try and stop all sounds using snd_restart, it displays the following message:

MXR_LoadAllSoundMixers: unable to open 'scripts/soundmixers.txt'

**Comment by kisak-valve** [comment]
Hello @Apollyon094, this issue is already being tracked at #802. Closing as a duplicate.
