### ISSUE TITLE
[TF2] Bug with the "metal" war paints (and a way to fix it)

### ISSUE THREAD

**Issue by 1556197** [ValveSoftware/Source-1-Games#3278]
There is a problem with "metal" war paints using wrong .vmt file in first-person view.

These war paints use $selfillum parameter to achieve metal shining look (for example, "dressed to kill" or "coffin nail" collections). This effect can best be demonstrated in dark rooms.
<img width="978" alt="image1" src="https://user-images.githubusercontent.com/6933683/84383408-e58fd500-abf4-11ea-8c9f-b794f93b915a.png">

The $selfillum parameter is represented in "_metal.vmt" files (materials\models\paintkits\cig). The only difference those files have from default .vmts is the following parameters:
"$selfillum" 1
"$selfillumtint" "[5 4 1]"
"$selfIllumFresnel" "1"
"$selfIllumFresnelMinMaxExp" "[0 13 18]"

However, if a weapon has stat clock attached, this effect disappears in first-person viewmodel. This is because, for some reason, the skin uses the default ".vmt" file instead of "_metal.vmt" file.
<img width="978" alt="image2" src="https://user-images.githubusercontent.com/6933683/84383470-00624980-abf5-11ea-8d20-46ee3351da0d.png">

The illumination effect can be achieved by copying $selfillum values from "c04_shotgun_metal.vmt" and pasting into the default shotgun file "c_shotgun.vmt". After this modification of the default .vmt, the stock shotgun begins to shine in first-person view, as well as "stat clock dressed to kill shotgun".
<img width="978" alt="image3" src="https://user-images.githubusercontent.com/6933683/84383505-0fe19280-abf5-11ea-99cb-cde1eb11c74a.png">

This proves that a "metal" war paint with stat clock uses the wrong .vmt file in first-person view (default c_#.vmt instead of c04_#_metal.vmt).
This problem has nothing to do with phong shading or graphics settings (as stated in "wiki.teamfortress.com/wiki/Decorated" buglist), it seems to be much simpler and easier to fix.
![false_bug](https://user-images.githubusercontent.com/6933683/84383518-18d26400-abf5-11ea-91d5-a0c923bf203d.png)

Please, take this bug in consideration.

**Comment by Mocha-Bean** [comment]
I have the same issue, showing this here with a Strange Coffin Nail Shotgun and a non-strange variant.

**Strange Coffin Nail Shotgun (first-person)**
![20210406011251_1](https://user-images.githubusercontent.com/8892160/113666901-99c38600-9675-11eb-9df3-4c7cd2fb6d56.jpg)

**Unique Coffin Nail Shotgun (first-person)**
![20210406011321_1](https://user-images.githubusercontent.com/8892160/113666913-9fb96700-9675-11eb-8e7c-6fcd2f95caf4.jpg)

**Strange Coffin Nail Shotgun (third-person, issue does not occur in third-person)**
![20210406011354_1](https://user-images.githubusercontent.com/8892160/113666958-b069dd00-9675-11eb-976a-7a652386f192.jpg)

System:
Windows 10 Pro 20H2 build 19042.867
Nvidia RTX 3060 Ti, driver ver. 465.89

**Comment by 1556197** [comment]
Hello, @kisak-valve . I think I figured out the actual solution within the tf2 source code. Can you please refer this post to tf2 team?

### Viewmodel structure
A viewmodel consists of several entities connected to each other via child-parent relationship. «Hands» viewmodel is represented in CBaseViewModel class, and the «weapon» viewmodel is represented in C_ViewmodelAttachmentModel class, which is pointed to from CTFWeaponBase class with m_hViewmodelAttachment pointer.

A Statclock viewmodel is represented in CTFWeaponAttachmentModel class, which is pointed to from CTFWeaponBase class with m_viewmodelStatTrakAddon pointer. When CTFWeaponAttachmentModel is created (in viewmodel case), it links itself to C_ViewmodelAttachmentModel as a child.

So, the viewmodel structure looks like this:
![Viewmodel structure](https://user-images.githubusercontent.com/6933683/192782324-90bb57cf-6139-4228-82f9-060be1b9947e.png)

 ### Viewmodel drawing
Entire viewmodel is drawn by the C_BaseViewModel::DrawModel function (c_baseviewmodel.cpp). This function calls CEconEntity::DrawOverriddenViewmodel (econ_entity.cpp) function, which draws the weapon (m_hViewmodelAttachment).
 
![2](https://user-images.githubusercontent.com/6933683/192782414-f372fe26-8070-462c-b4de-b031c759b9c4.jpeg)

CEconEntity::DrawOverriddenViewmodel function draws a weapon with Uber or Econ material overrides using «modelrender-> ForcedMaterialOverride» function. After the drawing, the override material is reset to NULL (only for Econ material, the Uber material resets in C_TFPlayer::DrawOverriddenViewmodel function).
 
![3](https://user-images.githubusercontent.com/6933683/192782450-7e10c368-9c2b-4887-9883-2d73eb7b151a.jpeg)

After this is done, the C_BaseViewModel::DrawModel function draws a Statclock viewmodel.
 
![4](https://user-images.githubusercontent.com/6933683/192782462-4c4fa4b7-ba39-4082-b6ea-fffb4db4394c.jpeg)

### The problem
The problem is: when m_viewmodelStatTrakAddon is drawn, it calls C_BaseAnimating::DrawModel function (c_baseanimating.cpp), which checks for «followed» entities (i.e. Parents) attached to bones, and then draws these Parents.
 
![5](https://user-images.githubusercontent.com/6933683/192782517-75dcd740-9055-4c0a-803d-7f292197644f.jpeg)

In other words, the weapon viewmodel (m_hViewmodelAttachment) is drawn a second time, but this time without any material overrides. As a result, no Uber or metal shining effects.

### Solution
1. A simplest solution seems to draw Stattrak viewmodel **before** everything else. So we need to move three corresponding lines of code in C_BaseViewModel::DrawModel function above the first overriding «if» clause. That would make all weapon material overrides happen **after** the first weapon «bone structure» drawing.
 
![6](https://user-images.githubusercontent.com/6933683/192782531-a956c7d0-5258-49ab-9be5-47bd8858ec42.jpeg)

2. If that maneuver isn’t allowed, I think it’s possible to create a derived DrawModel function specially for m_veiwmodelStatTrakaddon that wouldn’t check for any parents to draw them.

**Comment by Ashetf2** [comment]
According to the original poster in Reddit, this will be fixed in a future update.

![image](https://user-images.githubusercontent.com/63692647/217310127-705671e8-424e-4d42-bbeb-2f60615f5b33.png)

**Comment by kisak-valve** [comment]
Hello, per "Fixed Stat Clock cancelling out ÜberCharge and self-illuminating materials on weapons using War Paints (community fix from makaroffilya)" in the [2023-03-01](https://www.teamfortress.com/post.php?id=190461) Team Fortress 2 update, please retest this issue.

**Comment by 1556197** [comment]
@kisak-valve Hello, can confirm that the bug is fixed. Works with festive attachment, with killstreak sheen and with uber.

**Comment by MikhailaTF** [comment]
I've found that my top shelf minigun now has some pixelated-looking bit on the tip of the barrel when crit-boosted. This is I assume because there is a blood splatter here as I don't see this anywhere else on this item. It also only happens on the BLU team and looks normal on the RED team or when ubered on either team. Tested several other gentlemanne's skins but this seems to be the only case I can find.
![20230302194454_1](https://user-images.githubusercontent.com/71837773/222523868-8557eef2-75f8-476c-a019-85dab4fd1cbd.jpg)

I've also found that the higher roller's rocket launcher is not self-illuminated but the SMG is. Not sure if this is an inconsistency with the skins or intentional.
![20230302194343_1](https://user-images.githubusercontent.com/71837773/222524061-dcde156c-1f13-449f-873e-a25b32bb70a2.jpg)
![20230302194323_1](https://user-images.githubusercontent.com/71837773/222524044-bfe660e8-f3c6-45a8-b2b6-5b0aac0618a5.jpg)

**Comment by 1556197** [comment]
@MikhailaTF Can I use your screenshots to make a fix report?

**Comment by MikhailaTF** [comment]
> @MikhailaTF Can I use your screenshots to make a fix report?

Absolutely!

**Comment by MikhailaTF** [comment]
> I've made a workshop fix submission, however it's hidden from search because I can't provide tax information. Anyone with full workshop access is welcome to copy this submission so people can actually vote for this. If someone can do it, contact me and I will provide all nessesary files. https://steamcommunity.com/sharedfiles/filedetails/?id=2942723946

Fixed as per [today's update](https://www.teamfortress.com/post.php?id=191209). See screenshots below (don't have a medi gun to check). Thank you @1556197 for the effort!
![20230320204111_1](https://user-images.githubusercontent.com/71837773/226449366-09739320-c1a0-4a8c-b1ec-34df0b4cd2b4.jpg)
![20230320204120_1](https://user-images.githubusercontent.com/71837773/226449375-e33e1861-3ace-4f02-98f1-e9260d27a794.jpg)

**Comment by 1556197** [comment]
Great! I suppose, everything is fixed now.
