### ISSUE TITLE
[L4D2] Main Menu Produces No Ambience/Music

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/Source-1-Games#3288]
Installing and launching the Linux version of the game causes the main menu to be silent (not counting sound effects).
I've asked other people to try it too and they seem to be able to reproduce it on other distributions too.
(I'm using Manjaro KDE)

[System Info](https://gist.github.com/ThisNekoGuy/8a6bc016eac8b40d2b4cb41875a6cd69)

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, this issue is already being tracked at #416. Closing as a duplicate.
