### ISSUE TITLE
Outbound voice chat not working when server has "sv_use_steam_voice 0"

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#33]
Issue transferred from ValveSoftware/steam-for-linux#261
@rio-steam posted at 2012-12-22T05:30:09Z:

I have already posted this issue in the beta forum a while ago now but thought it would be a good idea to post it in the bug tracker as well.

Outbound voice in game does not work when the server being played on is using "sv_use_steam_voice 0". No errors appear in either the console or command line.

Steps to reproduce this issue:
- Open the console and enter in sv_use_steam_voice 0. This can be done either in a locally hosted game or in the main menu for TF2
- Go to voice chat options and test microphone using the voice chat tester. Alternatively if in a match you can open up the console and enter in voice_loopback 1 to test the microphone.

-Switch between sv_use_steam_voice 0 and sv_use_steam_voice 1 via the console. Outbound voice works when 1 is set. Outbound voice stops working when 0 is set.

System Information:

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3415 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.1 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-35-generic-pae
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560/PCIe/SSE2/3DNOW!

```
Driver Version:  4.3.0 NVIDIA 313.09
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 119 Hz
VendorID:  0x10de
DeviceID:  0x1201
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  8072 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  113858 Mb
    Largest Free Hard Disk Block:  87864 Mb

Installed software:

Recent Failure Reports:

**Comment by kingseva** [comment]
Still doesn't work. Any works on this issue? Damn, Linux port of game cs source is not complete over 2 years!

**Comment by glenswift** [comment]
816 days since issue created. Thank you Valve for this awesome level of product maintenance.

**Comment by Timm-Tahler** [comment]
The same problem on my Fedora 21 (GNOME) :-( Help!

**Comment by glenswift** [comment]
869 days since issue created.

**Comment by Lukypie** [comment]
Any update? 
No...

**Comment by glneo** [comment]
Is there any progress on this issue? any intent to fix this?

**Comment by Fedcomp** [comment]
does not work in CS : S for me either. Is it going to be fixed?

**Comment by fape** [comment]
Is there any good news?

**Comment by glenswift** [comment]
1122 days since issue was created.

![image](https://cloud.githubusercontent.com/assets/2373285/13760521/9771c228-ea44-11e5-904f-3729c19c4c24.png)

**Comment by Fedcomp** [comment]
Valve loves linux and opensource.

**Comment by Azelphur** [comment]
I think it's more that they want to force us to use steam voice.

**Comment by Lukypie** [comment]
there are also really worse problems with mesa drivers that make your computer unusable while playing tf2 which valve doesn't seem to care, so that's a general "I don't care about Linux users"

**Comment by Fedcomp** [comment]
> I think it's more that they want to force us to use steam voice.

Not sure what steam voice you talking about. I can't talk using microphone on random game server, windows users can. Simple as that.

**Comment by glenswift** [comment]
@Fedcomp Exactly. I'm pretty sure that if micro wasn't working on Windows, the fix would be immediate. Cause, it isn't kinda small bug, this stuff destroys great part of gameplay. But who cares about Linux.

**Comment by glenswift** [comment]
1313 days since issue was created

**Comment by Fedcomp** [comment]
Valve loves linux, yep.

**Comment by Konfuz** [comment]
The Bug still exists for Linux-Systems and so do servers explicitly setting **sv_use_steam_voice 0**. One might think that after 4 years everyone would be using the new system, but that is not the case.

I recognize that no one likes fixing bugs in deprecated systems, but due to the popularity of the engine it affects a large multitude of games and the server owners are usually not aware of the problem. (Some sources on the web actually suggest setting the old system to avoid problems with the new one.)

If this is going to be a wont-fix (and after 4 years a decision on that would be nice) there should be some kind of warning for server-admins and regular users to communicate the deprecated voice-infrastructure to them.

**Comment by Nephyrin** [comment]
Native (non-steam) voice was fixed for OS X and Linux clients in the CELT beta update last month, and non-steam voice is once again the default as of today's update.

(There may well still be bugs therein -- if you encounter bugs with the updated voice system, please open a new issue)

**Comment by ibrokemypie** [comment]
getting the issue in tf2 still today...
