### ISSUE TITLE
Steam does not save DNS records for server IP

### ISSUE THREAD

**Issue by MatteoInfi** [ValveSoftware/Source-1-Games#3327]
I just tried to switch IP in my DNS record and the server disappear from my favorite list, why is that? It should save the domain name instead so I do not have to "re-favorite" again

**Comment by kisak-valve** [comment]
Hello @MatteoInfi, please do not intentionally open duplicate issue report. Closing as a duplicate of #1566.

**Comment by MatteoInfi** [comment]
@kisak-valve Hello @kisak-valve, that issue is 7 years old and nothing has been done since then, maybe you should close it and open a new one since it seems to be forgotten?
