### ISSUE TITLE
[TF2] Potato.tf Community MvM Event Medal Issue [Item Distribution Halted]

### ISSUE THREAD

**Issue by AzureAzel** [ValveSoftware/Source-1-Games#3331]
There's currently a community MvM event going on, and medals related to it were recently added to the game in the latest update. However, there seems to be a problem with how one of them was added, using the same name as one of the other medals. As a result, medal distribution cannot occur until the issue is resolved, due to the nature of how the item distribution process works.

### **These are the medals that were added in relation to donations for COVID relief. Their names are _correct_:**
![donationM](https://user-images.githubusercontent.com/39247293/90986040-060dd100-e54e-11ea-959e-e8e141ba832a.png)

### **However, the actual event-related badge itself incorrectly shares the exact same name as one of the donation badges:**
![badgeP](https://user-images.githubusercontent.com/39247293/90986097-669d0e00-e54e-11ea-9a2a-256ed7eec4c8.png)
_Images courtesy of [Trade.tf](https://www.trade.tf/items/updates)_

### The correct name for the above badge should be the _"Titanium Tank Participant Medal"_.
**This issue, as it stands, makes it impossible to distribute these items.**

**Comment by AzureAzel** [comment]
@kisak-valve This issue has been resolved in the [2020-8-27](https://www.teamfortress.com/post.php?id=74907) Team Fortress 2 update per "Fixed the name of the Replica Titanium Tank 2020 medal"

**Comment by kisak-valve** [comment]
Glad to hear it. Closing.
