### ISSUE TITLE
[TF2] No text renders, but otherwise game's fine 

### ISSUE THREAD

**Issue by w3bb** [ValveSoftware/Source-1-Games#3336]
None of the text is rendering on Linux native TF2. The game otherwise seems to work fine. 

![](https://webber.rocks/8268f47c4b3ef5.png)

# System information:
- Gentoo
- [DWM](https://dwm.suckless.org/) (also tested on XFCE)
- GTX 1060 ![GPU info](https://webber.rocks/0f15527f44aec7.png)

I installed the Microsoft corefonts. Garry's Mod and CS:Source seems to have an okay time font-wise. 

## Locale variables:
![](https://webber.rocks/ad1d8608e8c77f.png)
# Steps to reproduce:
- Install Steam on Gentoo using portage
- Run the game
- Profit (not)

# [-condebug logs](https://gist.github.com/w3bb/683e29209524be9ded7af4fa45b1659f)

**Comment by kisak-valve** [comment]
Hello @w3bb, can you check if `media-fonts/ttf-bitstream-vera` is installed on your system? (#2717)

**Comment by w3bb** [comment]
> Hello @w3bb, can you check if `media-fonts/ttf-bitstream-vera` is installed on your system? (#2717)

It wasn't installed, I installed and uninstalled it and it made no difference.

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
