### ISSUE TITLE
[TF2] Iron Bomber projectiles have a 3x-4x larger hitbox compared to other Grenade Launchers

### ISSUE THREAD

**Issue by AzureAzel** [ValveSoftware/Source-1-Games#3340]
The Iron Bomber has a more generous area of where you can aim that allows your projectiles to hit enemies compared to all other Grenade Launchers. The gif below shows that the Iron Bomber can hit shots that other Grenade Launchers cannot without moving at all. This isn't stated in it's stats, so it's most likely a bug.

![bomberissue](https://user-images.githubusercontent.com/39247293/91873724-61734980-ec47-11ea-9c2f-440c1ff49dd3.gif)

### Update (9/5/20)
**Upon further investigation, it seems as if the issue resides in the size of the Iron Bomber projectile's hitbox.**
(**Left**: _Grenade Launcher/Loch-n-Load_) (**Middle**: _Loose Cannon_) (**Right**: _Iron Bomber_)
![size](https://user-images.githubusercontent.com/39247293/92310815-d44e2e80-ef7f-11ea-81eb-28149fc9f5ec.png)

**Comment by AzureAzel** [comment]
Edited the post with new information regarding the issue.

**Comment by sapphonie** [comment]
Could you include instructions on how you recreated this?

**Comment by wgetJane** [comment]
![](https://media.discordapp.net/attachments/743724583697383435/752200792768774292/unknown.png)

**Comment by SJMistery** [comment]
I still think that the programmers messed up and mixed the hitboxes of the Loose Cannon and Iron Bomber. Like seriously how does a big-ass cannonball have such a small box?

**Comment by wgetJane** [comment]
> I still think that the programmers messed up and mixed the hitboxes of the Loose Cannon and Iron Bomber. Like seriously how does a big-ass cannonball have such a small box?

they were not mismatched, all of the grenades are supposed to have the same 4x4x4 size of bounding box

the iron bomber's bounding box is larger than it should be because its `custom_projectile_model` item attribute causes its model to be changed after its bounding box size has been set to 4x4x4, overwriting it

changing an entity's model also changes its bounding box size because the `UTIL_SetModel` calls `SetCollisionBoundsFromModel`

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/util.cpp#L1330

**Comment by SJMistery** [comment]
> 
> 
> > I still think that the programmers messed up and mixed the hitboxes of the Loose Cannon and Iron Bomber. Like seriously how does a big-ass cannonball have such a small box?
> 
> they were not mismatched, all of the grenades are supposed to have the same 4x4x4 size of bounding box
> 
> the iron bomber's bounding box is larger than it should be because its `custom_projectile_model` item attribute causes its model to be changed after its bounding box size has been set to 4x4x4, overwriting it
> 
> changing an entity's model also changes its bounding box size because the `UTIL_SetModel` calls `SetCollisionBoundsFromModel`
> 
> https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/util.cpp#L1330

That sounds a little stupid, honestly. Different projectiles should have different hitboxes that match their size and shape. At the very least the Loose Cannon should get it's model reduced to more closely match the hitbox. Otherwise it throws off people that attempt to aim with it.

**Comment by kisak-valve** [comment]
Hello, per "Fixed the Iron Bomber's projectile collision size not matching other projectile collision sizes" in the [2022-07-07](https://www.teamfortress.com/post.php?id=140004) Team Fortress 2 update, please retest this issue.

**Comment by agrastiOs** [comment]
I've retested it, has been fixed. @AzureAzel thoughts?

**Comment by kisak-valve** [comment]
Thanks for retesting @agrastiOs. Closing as fixed.
