### ISSUE TITLE
[CS:S] [Request] Improve cl_downloadfilter

### ISSUE THREAD

**Issue by nyronic** [ValveSoftware/Source-1-Games#335]
A better cl_downloadfilter is needed, many servers have various sounds, materials, models, etc. that you are forced to download if you do not use a filter.

Right now the current options are:

all
none
nosounds

Using the none option works great when I already have the maps that are being played, but if I want to download a new map from a server I have to temporarily change it to one of the other 2 options. After the .bsp finishes downloading I have to disconnect and change it back none in order to avoid downloading all the extra stuff that I don't want.

A maps only option would be great, or possibly a section in the options with check boxes for different file types. Something like this could benefit all source multiplayer games, not just CS:S.

**Comment by micwoj92** [comment]
@kisak-valve This should be closed, mapsonly is available in cs:s (also TF2 and probably rest of mp games)

![image](https://user-images.githubusercontent.com/45581170/91680822-cc8c2580-eb4c-11ea-82e4-c014102969f3.png)

**Comment by kisak-valve** [comment]
Thanks @micwoj92, closing.
