### ISSUE TITLE
[TF2; Feature Request] Remove autobalancing in Casual, change votekick system, break up Casual lobbies, enable alltalk on Casual, sv_pure 0 on Casual, remove Random Crits on Casual, Cow Mangler Buff, Arena mode in Casual, Chat ban, Source 2, etc.

### ISSUE THREAD

**Issue by tariqmudallal** [ValveSoftware/Source-1-Games#3354]
Let's face it. We all know how frustrating it is when we are playing any sweaty Casual match, especially with a party. But when it turns into a situation where, for instance there are 10 in BLU and 8 on RED, a player is thrown to the other team without their knowledge, either the next time they die or after a certain amount of time (preceded by a warning inserted stating they they will be moved "if the teams are still not balanced"). Besides, should the player be in a party with other players, they WILL be separated from there, seeing how autobalancing can take away the fun. So our solution? **Have bots occupy unoccupied player slots**, just like in the not so popular Competitive mode and various community servers (and like in _CS:GO_ casual modes, like Deathmatch), and then kick them when a real player comes. By doing that, it'll ALWAYS feel like a full server, even when it's not so full. And again, doing it this way can REMOVE the need for autobalancing unbeknownst to the player.

I would like to make it so that on a (community) server with ABSOLUTELY ZERO players, and NO bots, the game is in an infinite pregame state, and that once a (real) player comes and joins the team opposite to the lone player, the game will start with a "Game Commencing!" message, EXACTLY like on the classic Counter Strike 1.6. And allow admins to disable the "Game Commencing!" system if they desire.

We also want to end the toxicity behind vote kicking on Casual. Sure it's useful to boot out spammers, voice spammers and cheaters/hackers, especially aimbotters and spinbotters and "Fine shot, m8" spammers, but at the same time it can also be used to one's advantage to remove someone "just for being stupid or gay". If we make it so that ONLY 1 teammate can call a vote every 3-5 minutes, and that no other teammate can vote during the cooldown period, we can lower or even end high levels of in game toxicity. However, should a vote pass, especially with those pesky hackers/cheaters, then the cooldown will be bypassed, useful for kicking a series of other hackers within the same server. Also I would like to make it impossible for one to ever try kicking themselves. This can be achieved by pulling up the console, writing "status" into it, taking note of the ID listed beside the player's own name (in the # row), and then writing "callvote kick * ID *" to try to get themselves kicked. Again, we want to basically prevent the said command from working for one to kick themselves. After all, we want to get the player to capture or defend the objective rather than spamming to get themselves kicked.

We also want to add an option to the Vote menu in Casual to enable alltalk. Basically, we want to let players from both teams decide whether they want to enable teams from both ends to talk, mess around, and have fun. However, since toxicity can rise, we can add an option to vote to disable alltalk, especially should voice chat be used for location callouts by teammates. 

There is a solution should we need to balance out the teams in Casual. We can add a vote option to "**Auto Scramble**" teams, just like in community servers. At the same time, we also need to take into account the other users in the player's party, as a deciding factor as to whether to move the others with them or not, so there'd be no frustration when users are separated from their party members.

We would like to see players (re)spawn with an Über effect every time, _just_ like in Mannpower. Very useful in Casual (especially in 2Fort), and Competitive, as an enemy team sometimes likes to spawn trap the player's team and basically make it "impossible" for their team to leave the spawn room. Giving the mini Über on spawn enables their team to counter and distract the enemy team with ease and enable them to keep the flow going. I also would like to make it so that NOT A SINGLE thing, including projectiles, stickybombs and bullets can make their way into the spawn room (they should end up hitting on the invisible wall to the enemy team who tries to shoot into the player's team's spawn room), which could after all make it the SAFEST place for a teammate to be, and therefore produce NO hitsound, if any, and cause any damage. This would mean that if a RED Engineer puts up a Lvl. 3 Sentry atop the roof near BLU's spawn room in Dustbowl, the Sentry's bullets and/or rockets wouldn't go through the skip sign, making spawn trapping impossible. As for BLU, the Über effect on respawn allows them to easily take down that Sentry, and therefore counter the spawn trap set up by that RED Engie.

In an effort to crack down on the bot pandemic going on in _TF2_, I would like for Casual lobbies to break up, after EVERY game, like in Competitive, and like it did in the early days of the Meet Your Match update (and just like in Call of Duty: Modern Warfare). You know, the thing that would say "Game will end in x seconds. It is safe to leave." in chat when the final scoreboard appears before a closed Casual/Competitive door. Sure many could hate on this idea, as it prevents Casual lobbies from having the same levels of fun across different maps, but again, making players search for a whole another match could be a good thing, especially since it encourages players to try different game modes or just straight up quit and take a break from the game, and can "benefit" the bots as they will be forced to search for different matches, too, and therefore get bored with other bots as well, and then quit all together, effectively toning down the bot pandemic.

When it comes to Casual matchmaking, we would like to make it connection based, or at the very least, "nerf" the Glicko-based SBMM matchmaking system that Casual uses. This way we can get more of a balance between sweatiness and straight up noobs. We all love seeing opportunities to pubstomp varying enemies and get a win streak going. Some may be against this idea, but doing this could make _TF2_ the best place to chill in all of eternity, and make it as fun as it was back in the days of the Meet Your Match update, or even before it. In conclusion, Glicko based matchmaking should be reserved for _TF2_'s least played Competitive mode.

We all know how frustrating it is when our custom sounds or mods are blocked by sv_pure 1 in Valve servers. Besides, they can also introduce earrape noises, unless the cache files in the custom directory is removed. If we make them sv_pure 0, we could be proud of thr mods we did, abd enjoy them to the max. Sure, that could allow one to get the higher ground through map texture mods, but we can stop it via VAC (if it's ever possible), or just filter map textures to prevent custom ones from loading.

THE MOMENT YOU'VE ALL BEEN WAITING FOR!!! REMOVING RANDOM CRITS!!! I mean sure I do love random crits, as I sometimes get lucky, especially when trying to mow down a Scout from a distance, or even another Heavy. However, many are complaining how they are "unfair & unbalanced", and how it leaves ZERO chance for the enemy to counter strike back (get it?!). So if we disable random crits for all official Valve servers, except MvM, the game can be more enjoyable for all. Also I was wondering what if those crits could destroy sentries more easily, especially when making a push as a team to get to the Intel room in 2Fort... now we have a new use of getting crits on weapons.

You know how we are kicking aimbotters from Casual servers? And then they find a way back in or different bots appear and then we have to do our due diligence on kicking them all? What if we made it so that if the bots get kicked enough number of times, say like 30 times at once, then they will get a matchmaking ban, something that could vary in length from a week to a month to a year or even a lifetime. Also take into accounts how many recent reports did the hacker get at once in the recent weeks or months to determine whether the player being kicked deserves a ban of such. We also need to patch up the vote kicking system due to the fact when we try to vote out the bots they tend to _still_ count as a "fail", since bots are trying to stay in the game and ruin the fun, hence why earlier I said we should break up Casual lobbies every game. I think if we made it so that 11 votes end the vote immediately end count as a pass, this could be a much needed change.

Let's advertise Competitive mode everywhere as much as possible in _TF2_, just like it was back when the Meat Your Match update came out. We could advertise it within the maps, via the main menu, in game notifications, you name it! We would like to get a competitive scene for _TF2_ going and be as big as _CS:GO_'s.

Let's add the ability for community servers to use graphics from Casual mode, including its post game map voting interface, and the warmup/"Waiting for players" feature (and customize the warmup time). If we add these in, then there'd be no need for the mid game voting system to be utilized, nor the need for any server mods/plugins to do so. We also would want to see an _indirect_ return of the old Quickplay feature by having community servers qualify for Casual mode, much like MvM Boot Camp, provided they have met the old Quickplay server requirements (the only [suggested] change to it being that it's sv_pure 0). This could make great use of the community servers to keep the playerbase alive and thriving. Also we want to remove the joining restriction set by official Valve Casual servers, so that it's easy for one to join up on a friend.

I suggest buffing the Soldier's Cow Mangler 5000 so that it has the ability to do normal, full on cirts as opposed to downgrading crit boosted hits to Mini Crits. That way we could encourage players to use it more, especially how different it is compared to other primaries of the Soldier.

You know how sometimes when you kill en enemy, especially if you're a Pyro whose ricocheted crocket hits the enemy Soldier who first shot it, you would do one of your taunts, like the Schadenfreude/laughing taunt. I would like to make it so that you can cancel those non shareable taunts so that should a suspected Spy or enemy Heavy come during your taunt you can cancel the taunt and take care of the enemy from there and move on.

I know this may or may not happen anytime soon, but I think it's time we bring _TF2_ to the newer Source 2 engine, that is only being popularly used in Dota 2. Doing so could mean many advantages. In addition to nice looking graphics, we also have better security, better compatibility, and the ability to work with modern day x64 PCs and modern graphics APIs like DX11 & Vulkan. If I am right, due to Source 2 being newer, and therefore Valve constantly updating the engine itself with newer bugfixes and patches, aimbotters would be out more quickly than they think they would be.

Last but not least we should reintroduce back the beta muzzle flash into the game. Sure we all love to customize our _TF2_ to stand out to our eyes more (hence the paragraph about making Valve Casual servers sv_pure 0). By adding the beta muzzle flash into the game, the game can stay more true to its cartoony look that game was initially aiming for, making _TF2_ more fun! Also we would like to see Arena mode added to the Misc. section of Casual matchmaking, and therefore bring about a resurgence to the long forgotten Arena mode!

Thanks for reading this ridiculously long "request", and hopefully, most, _if not all_ of the requests & suggestions will come true! :)

**Comment by kisak-valve** [comment]
Hello @tariqmudallal, in general multi-issue issue reports are bad for any issue tracker. This is the feature request equivalent of that. Each individual request should be discussed and tracked separately.

Closing as untrackable.

**Comment by tariqmudallal** [comment]
> Hello @tariqmudallal, in general multi-issue issue reports are bad for any issue tracker. This is the feature request equivalent of that. Each individual request should be discussed and tracked separately.
> 
> Closing as untrackable.

Ok will break it all up into separate threads.
