### ISSUE TITLE
[TF2] [Linux] Custom files from community servers will not download

### ISSUE THREAD

**Issue by SheepyChris** [ValveSoftware/Source-1-Games#3359]
Even when removing all custom files, resetting configs, verifying cache, changing internet connections and testing with multiple community servers, Team Fortress 2 on Linux is unable to obtain any maps/sounds/models/files from community servers that are hosted with FastDL. This issue corresponds to the one reported over at the CS:GO repo over 6 years ago, which has been fixed by Valve in late 2018: https://github.com/ValveSoftware/csgo-osx-linux/issues/11

System information: https://gist.github.com/SheepyChris/a784cb994305145097df006402024b2e

**Comment by kisak-valve** [comment]
Closing pending feedback.
