### ISSUE TITLE
[Portal] I can't see Korean in Portal and Portal 2

### ISSUE THREAD

**Issue by ensup** [ValveSoftware/Source-1-Games#3361]
I can't see Korean in Portal and Portal 2 (I tried editing '/.fonts.conf ' and installing zenhei)
![93660023-da670380-fa85-11ea-9cfe-5d08fa86d688](https://user-images.githubusercontent.com/38882082/93660166-01720500-fa87-11ea-886b-5616f8a6e602.jpg)
System: Ubuntu 20.04 (GNOME) x64

**Comment by kisak-valve** [comment]
Closing as a duplicate of #3360.
