### ISSUE TITLE
[L4D2] Autoaim crashes after update ...and other old crashes

### ISSUE THREAD

**Issue by Accelerator74** [ValveSoftware/Source-1-Games#3372]
I get quite frequent server crashes with this function.

```
server_srv.so CBasePlayer::AutoaimDeflection(Vector &,autoaim_params_t &) -> 0x774f26 or 0x774f66
server_srv.so CBasePlayer::GetAutoaimVector(autoaim_params_t &) -> 0x775595 - Very often
```

Since the update, there were crashes on this function.

core dump: https://drive.google.com/file/d/1B5mMvAt-Y9cY51-wna_pTomf1M3W1pao/view?usp=sharing
minidump: https://drive.google.com/file/d/1J6rTVIatrWYMB4ZjofmpOqBMXakuUjTo/view?usp=sharing
Raw: https://drive.google.com/file/d/1iMvqGEcVgQXE7K6q2ApYFUzfk6J0NyA9/view?usp=sharing

And also, could you please pay attention to this problem and fix it, please https://github.com/ValveSoftware/Source-1-Games/issues/2526 this error still exists...

**Comment by Accelerator74** [comment]
And there is also another old crash problem:
`server_srv.so CHinderingEscapeAwardTemplate::FireGameEvent(IGameEvent *) + 0x81124d`

This error is also frequent.

**Comment by ProdigySim** [comment]
@Accelerator74 Do you have Core dumps for this crash? Or any steps to reproduce?

**Comment by Accelerator74** [comment]
Unfortunately no. I do not know the reasons for calling these errors, I can only show the stack trace of crashes from the Accelerator Extension. Hosting does not provide access to core dumps.

**Comment by Accelerator74** [comment]
Chainsaw ChangePitch crash (https://github.com/ValveSoftware/Source-1-Games/issues/2526) core dump - https://dropmefiles.com/f16XN

**Comment by ProdigySim** [comment]
@Accelerator74 I believe accelerator (crash.limetech.org) has a way to download the raw minidumps / more information if you click on "Download Minidump" or "View Raw". Both of those would be helpful.

**Comment by Accelerator74** [comment]
CBasePlayer::GetAutoaimVector(autoaim_params_t &) crash:
core dump: https://drive.google.com/file/d/1B5mMvAt-Y9cY51-wna_pTomf1M3W1pao/view?usp=sharing
minidump: https://drive.google.com/file/d/1J6rTVIatrWYMB4ZjofmpOqBMXakuUjTo/view?usp=sharing

**Comment by Accelerator74** [comment]
More crash dumps with error
> server_srv.so!CBasePlayer::AutoaimDeflection(Vector&, autoaim_params_t&) + 0x686
> server_srv.so!CBasePlayer::GetAutoaimVector(autoaim_params_t&) + 0xf5
or
> 0xc125b0c0
> server_srv.so!CBasePlayer::GetAutoaimVector(autoaim_params_t&) + 0xf5
> server_srv.so!CBasePlayer::GetAutoaimVector(float, float, float, AimResults*) + 0x40
> server_srv.so!CTerrorGun::FireBullet() + 0x413
> server_srv.so!CPistol::PrimaryAttack() + 0x13
> server_srv.so!CBaseCombatWeapon::ItemPostFrame() + 0x397
> server_srv.so!CTerrorWeapon::ItemPostFrame() + 0x2e3
> server_srv.so!CTerrorGun::ItemPostFrame() + 0x38

Dumps: https://drive.google.com/file/d/1T23x1bDOudOIwlwmDRB26jXWpB7S1gRa/view?usp=sharing

**Comment by Accelerator74** [comment]
Fix: `autoaim_max_deflect 0`
