### ISSUE TITLE
[L4D2] CMoveableCamera::FollowTarget crash

### ISSUE THREAD

**Issue by accelerator74** [ValveSoftware/Source-1-Games#3388]
Another very old crash.

Stack trace
> server_srv.so!CMoveableCamera::FollowTarget() + 0x3b
> server_srv.so!CBaseEntity::PhysicsDispatchThink(void (CBaseEntity::*)()) + 0xae
> server_srv.so!CBaseEntity::PhysicsRunSpecificThink(int, void (CBaseEntity::*)()) + 0xb9
> server_srv.so!CBaseEntity::PhysicsRunThink(CBaseEntity::thinkmethods_t) + 0x42
> server_srv.so!CBaseEntity::PhysicsNoclip() + 0xcd
> server_srv.so!CBaseEntity::PhysicsSimulate() + 0xa9c
> server_srv.so!Physics_SimulateEntity(CBaseEntity*) + 0x15a
> server_srv.so!Physics_RunThinkFunctions(bool) + 0x2aa
> server_srv.so!CParallelProcessor<QueryCacheUpdateRecord_t, CFuncJobItemProcessor<QueryCacheUpdateRecord_t>, 1>::Run(QueryCacheUpdateRecord_t*, unsigned int, int, IThreadPool*) + 0x716
> server_srv.so!CGlobalEntityList::CleanupDeleteList() + 0xc4
> server_srv.so!Physics_RunThinkFunctions(bool) + 0x253
> server_srv.so + 0x479780

Coredump: https://drive.google.com/file/d/1zKCzSeO2rvbqmwB1J8MTKlOHqIKtgWCR/view?usp=sharing
Minidump: https://drive.google.com/file/d/1WGuMdGOR8MfJYx-LJ3PsZ9PMCQCQZo6U/view?usp=sharing

**Comment by ProjectSky** [comment]
* Found the same error, it happens every day on my server

```
server_srv.so!CMoveableCamera::FollowTarget() + 0x3b
server_srv.so!CBaseEntity::PhysicsDispatchThink(void (CBaseEntity::*)()) + 0xae
server_srv.so!CBaseEntity::PhysicsRunSpecificThink(int, void (CBaseEntity::*)()) + 0xb9
server_srv.so!CBaseEntity::PhysicsRunThink(CBaseEntity::thinkmethods_t) + 0x42
server_srv.so!CBaseEntity::PhysicsNoclip() + 0xcd
server_srv.so!CBaseEntity::PhysicsSimulate() + 0xa9c
server_srv.so!Physics_SimulateEntity(CBaseEntity*) + 0x15a
server_srv.so!Physics_RunThinkFunctions(bool) + 0x2aa
```

**Comment by dragokas** [comment]
**Accelerator74**, can you please explain, how correctly collect core and mini-dump (Linux) ?

Same crash happen to me: https://crash.limetech.org/sjm727nci6ej

**Comment by Accelerator74** [comment]
@dragokas coredump can be found in /var/lib/systemd/coredump
minidump can download after logging into crash.limetech.org (Download Minidump).

**Comment by ProjectSky** [comment]
is there any solve? after update my server keep crashing, i no idea about this, i can't solve it

**Comment by dragokas** [comment]
If somebody still suffering from this crash, I've made a detour fixing that. 
Welcome to the thread: https://forums.alliedmods.net/showpost.php?p=2725811&postcount=19

**Comment by ProjectSky** [comment]
> If somebody still suffering from this crash, I've made a detour fixing that.
> Welcome to the thread: https://forums.alliedmods.net/showpost.php?p=2725811&postcount=19

* Changing some plugins, my server no longer crashes frequently, but I am still not sure what plugins/code caused the crash.
*  Thanks a lot

**Comment by shqke** [comment]
Can anyone confirm whether this fixes an issue? I've always had my own test case which I've used to "restart" some servers. Probability of which is quite low unless some custom plugins were involved (notably ones that messing with cameras).

```
#include <sourcemod>
#include <sdktools_functions>
#include <sdktools_entinput>

public void OnClientDisconnect(int client)
{
    if (!IsClientInGame(client)) {
        return;
    }
    
    int viewEntity = GetEntPropEnt(client, Prop_Send, "m_hViewEntity");
    if (!IsValidEdict(viewEntity)) {
        return;
    }
    
    char cls[64];
    GetEdictClassname(viewEntity, cls, sizeof(cls));
    if (strncmp(cls, "point_viewcontrol", 17) != 0) {
        return;
    }
    
    // Identify a CSurvivorCamera, CTriggerCamera
    if (strcmp(cls[17], "_survivor") == 0 || cls[17] == '\0') {
        // Disable entity to prevent CMoveableCamera::FollowTarget to cause a crash
        // m_hTargetEnt EHANDLE is not checked for existence and can be NULL
        // CBaseEntity::GetAbsAngles being called on causing a crash
        AcceptEntityInput(viewEntity, "Disable");
    }
    
    // Identify a CTriggerCameraMultiplayer
    if (strcmp(cls[17], "_multiplayer") == 0) {
        AcceptEntityInput(viewEntity, "RemovePlayer", client);
    }
}
```

**Comment by dragokas** [comment]
DHook fix is updated with Windows signatures.
See: https://forums.alliedmods.net/showpost.php?p=2725811&postcount=19

**Comment by A1mDev** [comment]
if you don't use custom maps, just delete the plugin l4d_skip_intro.smx (https://forums.alliedmods.net/showthread.php?p=2686527). This plugin creates a random crash on the server. if you still need to remove intro scenes use this, but it doesn't work on all custom maps (you need to add this to the stripper):
; =====================================================
; =================  INTRO REMOVAL  ===================
; =====================================================
filter:
{
	"targetname" "relay_intro_setup"
}
modify:
{
	match:
	{
		"targetname" "relay_intro_start"
	}
	insert:
	{
		"OnTrigger" "camera_introDisable0-1"
		"OnTrigger" "relay_intro_finishedTrigger1-1"
	}
}

**Comment by A1mDev** [comment]
Plugin from @shqke does not fix this crash. Some collection reports, and the code that made those reports. Maybe someone needs it. Code: (https://pastebin.com/wLetQ5MC), logs: (https://pastebin.com/aP6m01qu).
