### ISSUE TITLE
[L4D2] Achievement

### ISSUE THREAD

**Issue by Alfa1337** [ValveSoftware/Source-1-Games#3392]
Unable to achieve The Last Stand achievement, even on an Official Dedicated server.

Already tried :

1. Uninstalling the mods, unsubscribing them, clean and add-on folder
2. Clean install of the game

**Comment by Alfa1337** [comment]
Oh wait, I couldn't get any of the achievements:

1. Ghost of Chirstmas Present
2. Still Standing
3. Elephant In The Room
4. Three's A Crowd
5. Get Skeeted On
6. Z-Genocidest 2: Episode 2 (it's 0/53599)

**Comment by Alfa1337** [comment]
Update:

7. Household Names

**Comment by Tiagoquix** [comment]
Hi OP, is this still relevant as of 2024?
