### ISSUE TITLE
[SteamPipe] Can't override localisation files in the TF2 beta

### ISSUE THREAD

**Issue by Strasedon** [ValveSoftware/Source-1-Games#340]
The title says it all, but I modify and add some strings to tf_english.txt and TF2 isn't loading the file from the VPK.  The main reasons for modifying it:
- Storing the HUD name(s) & version, which let me solve an annoying merge conflict for some other flavors of PVHUD.
- The "x" present in the default value for ControlPointIconCappers causes the text to clip on the smaller icons I use in my HUD.
- I like the time formatting I use for the scoreboard :)

A zip archive containing the VPK files is here: https://dl.dropboxusercontent.com/u/1565165/pvhud.zip

**Comment by Wasmanr2** [comment]
@kisak-valve you may close this since TF2 beta got removed.

> Team Fortress 2 Beta was a separate beta version of the game and open to all premium players. Released on December 2, 2010 and removed on June 7th, 2013

**Comment by kisak-valve** [comment]
Hello @Strasedon, are you still experiencing this issue with the current TF2 client?

**Comment by Strasedon** [comment]
I no longer play TF2 and do not have it installed so I'm unable to test this.

**Comment by kisak-valve** [comment]
Thanks for the feedback. If someone else comes across this issue and wants to pursue it further, then we can re-open this issue report.
