### ISSUE TITLE
[TF2] The Razorback is invisible in the inventory and other panels.

### ISSUE THREAD

**Issue by Kruphixx** [ValveSoftware/Source-1-Games#3401]
The Razorback model is invisible on the player model in the loadout menu and the small player model HUD in-game. It's also invisible when trying to inspect it in the backpack. It's obviously still visible in-game on the player model, just not in the UI as I mentioned.

I don't use any custom mods. I also tested this bug on two PCs and it's still happening. 
![20201008100704_1](https://user-images.githubusercontent.com/50501742/95602990-fbec5700-0a55-11eb-98a4-7b5fe8785902.jpg)
![20201008100652_1](https://user-images.githubusercontent.com/50501742/95602993-fc84ed80-0a55-11eb-8b4d-ff476b5b6de9.jpg)

**Comment by kisak-valve** [comment]
Hello @Kruphixx, this issue is already being tracked at #2341. Closing in favor of the existing issue report.

**Comment by Ashetf2** [comment]
@kisak-valve This is a different issue. This is about the Razorback specifically not appearing in the loadout. It neither appears in the 3D character.

![image](https://user-images.githubusercontent.com/63692647/212570229-fb0a1e75-56ee-47c9-a23c-0619af7f0a1e.png)

![image](https://user-images.githubusercontent.com/63692647/212570222-e39f75c2-53f4-4135-968d-fb24d7970753.png)

**Comment by kisak-valve** [comment]
Hello @Ashetf2, re-reviewing this issue report took me to #3518 where it is mentioned.
