### ISSUE TITLE
[L4D2] Issued to many commands to server.

### ISSUE THREAD

**Issue by hover9000** [ValveSoftware/Source-1-Games#3406]
Multiple unknown disconnections, occurred from October 12 to today.
"Disconnect - Disconnect: Issued to many commands to server."
The same thing is happening to all the official servers and to several players:
If it happens again, I'll copy everything that comes out on the console.
![disconnect](https://user-images.githubusercontent.com/43052252/95904429-217ea680-0d5d-11eb-8807-2780e95e0e4a.jpg)

System information:
Windows 10

**Comment by kisak-valve** [comment]
Hello @hover9000, this issue is already being tracked at #3405. Closing as a duplicate.
