### ISSUE TITLE
MacOS Steam has numerous leaks.

### ISSUE THREAD

**Issue by azav** [ValveSoftware/Source-1-Games#3407]
Under MacOS 10.14.6, run Team Fortress 2 for a few hours.  
In Terminal, check the PID of Steam and enter leaks and heap on that PID.

Loads of objects are leaked.  Over 1237568 bytes.

Process 39009: 2125689 nodes malloced for 187142 KB
Process 39009: 11199 leaks for 1237568 total leaked bytes.

    11199 (1.18M) << TOTAL >>

Physical footprint:         418.0M
Physical footprint (peak):  447.9M

Found 719 ObjC classes
Found 225 CFTypes

Heap and leaks output are enclosed.

[Steam leaks.txt](https://github.com/ValveSoftware/Source-1-Games/files/5380997/Steam.leaks.txt)
[Steam heap.txt](https://github.com/ValveSoftware/Source-1-Games/files/5380998/Steam.heap.txt)

**Comment by kisak-valve** [comment]
Hello @azav, please use [Steam Support](https://help.steampowered.com/) for feedback on the Steam-for-Mac client. Closing as out-of-scope for this issue tracker.
