### ISSUE TITLE
Steam on MacOS 10.14.6 has 7 steam helper processes.  Many of them leak memory.

### ISSUE THREAD

**Issue by azav** [ValveSoftware/Source-1-Games#3408]
Launch TF2 on MacOS 10.14.6 and play for a few hours.
In Activity Monitor, filter on Steam.  You may see up to 7 Steam Helper processes.
Run leaks and heap on each PID.

Results: there are many processes with memory leaks.
Heap and leaks output supplied.

[Steam Helpers leaks.txt](https://github.com/ValveSoftware/Source-1-Games/files/5381036/Steam.Helpers.leaks.txt)
![Screen Shot 2020-10-14 at 4 54 46 PM](https://user-images.githubusercontent.com/4999784/96049715-09328880-0e3e-11eb-9876-c43104a72cbf.png)
[Steam Helpers heap.txt](https://github.com/ValveSoftware/Source-1-Games/files/5381041/Steam.Helpers.heap.txt)

**Comment by kisak-valve** [comment]
Hello @azav, please use [Steam Support](https://help.steampowered.com/) for feedback on the Steam-for-Mac client. That said, Steam uses libcef (embedded chromium) for it's web component and the memory leaks are most likely an upstream issue.

Closing as out-of-scope for this issue tracker.
