### ISSUE TITLE
Half-life is not suitable for high resolution.

### ISSUE THREAD

**Issue by duowzj** [ValveSoftware/Source-1-Games#3419]
Half-life is not a good match for high resolution, the interface will not automatically zoom to the right state when you change the resolution.Once the resolution is raised, the font and the interface, including the crosshair, become very small and almost invisible.Half-life 2 and its sequels also have this problem.

**Comment by kisak-valve** [comment]
Hello @duowzj, this issue is already being tracked at #2510. Closing as a duplicate.
