### ISSUE TITLE
Mouse click do not cause any effect in Team Fortress2

### ISSUE THREAD

**Issue by Qaridarium** [ValveSoftware/Source-1-Games#342]
I tested Team Fortress2 but after the game starts my mouse clicking do not cause any effect.....
I tested it with Kubuntu 12.10 and now 13.04 
Mouse clicking works in KDE and wine games like arma2 and in other native games the mouse works to. 
The mouse also works in the "steam-app"

**Comment by kisak-valve** [comment]
Hello @Qaridarium, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
