### ISSUE TITLE
[TF2] Mute players window does not use the new Steam chat filter

### ISSUE THREAD

**Issue by treacherousfiend** [ValveSoftware/Source-1-Games#3425]
Normally the new Steam chat filter will censor any text that is blacklisted, but this does not occur in the "Mute Players?" window.
For example, if I name myself "Slur" (just an example), then it will show up in game as "****", but in the Mute Players window it will show up uncensored as "Slur".

This likely happens on other source games as well, but I have not tested it.

Edit: the filter also does not seem to work on items (I.e name tags, description tags)

**Comment by Tiagoquix** [comment]
I think this is purposeful, because if there are 2 players with censored names, you will not know who is who and therefore will not be able to silence the correct player.

**Comment by Yetoo1** [comment]
> I think this is purposeful, because if there are 2 players with censored names, you will not know who is who and therefore will not be able to silence the correct player.

But the slurs are offensive and hurt my feelings and make me impure and my feelings and my good soul are more important than utility.

**Comment by treacherousfiend** [comment]
At some point, this was fixed, closing
