### ISSUE TITLE
[TF2] broken shadows on Bloodwater

### ISSUE THREAD

**Issue by niobium93** [ValveSoftware/Source-1-Games#3427]
I'm on Arch Linux, kernel linux-zen 5.9.1, Radeon RX 5700 XT, Mesa 20.2.1
[Video](https://youtu.be/e09eoOYQE6w)
This only happened sometimes. Usually it was fine.

**Comment by kisak-valve** [comment]
Possibly related to #2807.

**Comment by niobium93** [comment]
I played a game on Bloodwater and couldn't reproduce this issue. Then again even back in 2020 it only happened the one time. Feel free to close this.

**Comment by Tiagoquix** [comment]
Thanks for updating the issue. You can close it if you want to.
