### ISSUE TITLE
[L4D2] Replace ERROR model with something less annoying

### ISSUE THREAD

**Issue by dragokas** [ValveSoftware/Source-1-Games#3431]
Related to https://github.com/ValveSoftware/Source-1-Games/issues/3429

If you don't plan to return back the old behavior of "cl_downloadfilter",
at least, please, replace the red "ERROR" model on client-side with something less annoying / less noticeable, like a little dot / or something semitransparent, a model that would not interfere with playing.

Thank you.

**Comment by kisak-valve** [comment]
Hello @dragokas, this would be an anti-feature for map development and counter-productive.

**Comment by dragokas** [comment]
You are putting map development ahead of the convenience of the gameplay itself. That is not appropriate.
Why not split entities: development and gameplay?
During development let's missing models refers to the RED ERROR mdl file.
And, during gameplay let's missing models refers to some less annoying mdl file.
That is quite easy to implement.
And that doesn't create conflict between developers and players.

**Comment by Yetoo1** [comment]
> You are putting map development ahead of the convenience of the gameplay itself. That is not appropriate.
> Why not split entities: development and gameplay?
> During development let's missing models refers to the RED ERROR mdl file.
> And, during gameplay let's missing models refers to some less annoying mdl file.
> That is quite easy to implement.
> And that doesn't create conflict between developers and players.

It's annoying for the average player to troubleshoot or know that something is wrong with a model if it's hard to ascertain what's missing when the model is a dot on a transparent slate. The error model keeps it simple and concise.

**Comment by dragokas** [comment]
The golden mean should be between ease of development and gameplay.

There are a lot of special reports (logs) during map compilation
and a batch tools (scripts), helping to found such missing references during the creation of the models itself.

Visual inspection of the map for "ERRORS" does not make sense and not productive when we already have such logs.

IMHO, personally, when I'm working with fixing/creating the model,
it doesn't matter to me, whether I'll see the ERROR or just the absence of the model
to understand where I failed and what files are missing. 

Again, if it's really required, game devs could modify Hammer in way
that ERROR could only be visible there, not in-game, saving a lot of nerves
for the end players and server admins who are constantly asked about
ERROR due to the recently introduced cl_downloadfilter behaviour.

**Comment by Yetoo1** [comment]
I was thinking that the average player in question here would usually be playing in other situations not related to cl_downloadfilter and may not have the content that the game is attempting to call due to it be uninstalled or in another location.

**Comment by dragokas** [comment]
Moreover, game devs and map makers are technically smart enough
to install vpk with red error model, overriding the default model (which I would really like to be invisible or at least not such noticeable).

**Comment by MartLegion** [comment]
I don't have much knowledge of map development, but I think that hammer is used for creating maps (I don't know if is the only tool), but I already read some guides about changing how entities look inside hammer.
This link is the one that I'm talking about: https://steamcommunity.com/sharedfiles/filedetails/?id=1685639284
So, if I'm correct, what Dragokas is asking is possible.
