### ISSUE TITLE
[L4d2] Too small font size in console window ~

### ISSUE THREAD

**Issue by dragokas** [ValveSoftware/Source-1-Games#3433]
It's almost impossible normally read anything from the console window:

![image](https://user-images.githubusercontent.com/19956568/98002777-9beb9500-1df6-11eb-8f0c-c9074b2e0d5b.png)

Please, increase the font size.
Thank you.

**Comment by kisak-valve** [comment]
Hello @dragokas, this issue is already being tracked at #2235. Closing as a duplicate.
