### ISSUE TITLE
[Portal Windows] Achievements are not given

### ISSUE THREAD

**Issue by faruk8727** [ValveSoftware/Source-1-Games#3438]
I have fisihed all the bonus maps and the requirements for their related achievements. The achievements are seems to be finished in game but not in steam overlay or library. Please help.
![Ekran Görüntüsü (5)](https://user-images.githubusercontent.com/74071577/98404400-8cc94900-207b-11eb-9d53-ac289b50bb37.png)
![Ekran Görüntüsü (3)](https://user-images.githubusercontent.com/74071577/98404406-8e930c80-207b-11eb-8f53-0a8f819442e7.png)
![Ekran Görüntüsü (4)](https://user-images.githubusercontent.com/74071577/98404411-90f56680-207b-11eb-8176-0fd214431bce.png)

**Comment by kisak-valve** [comment]
Hello @faruk8727, this issue is already being tracked at #981. Closing in favor of the older issue report.
