### ISSUE TITLE
[TF2] After switching between tty's the game is not displayed normally

### ISSUE THREAD

**Issue by likhner** [ValveSoftware/Source-1-Games#3439]
If you switch the tty's, the game stops showing up normally when you return to it.
Video: https://youtu.be/965KrObVz6k

System: Arch Linux
Kernel: Linux 5.9.3-zen1-1-zen
NVIDIA Driver Version: 455.38
X Server Vendor: The X.Org Foundation
X Server Release: 12009000
X Window Manager: GNOME Shell
OpenGL Version: 4.6

**Comment by kisak-valve** [comment]
Hello @likhner, I'm fairly sure this is a video driver issue. There's a long standing issue with the nVidia proprietary driver where the video driver can loose track of what it is doing in an OpenGL application when you switch to a VT and this can lead to rendering anomalies or crashes. This is not limited to Source 1 games and Team Fortress 2.

Unless there's a stronger indicator, this issue should be evaluated by your video driver vendor.
