### ISSUE TITLE
[CS:S] the main branch and the prerelease branch srcds.exe wont launch

### ISSUE THREAD

**Issue by CutieRin** [ValveSoftware/Source-1-Games#344]
had me and a friend download the cs:s dedicated server and i'm sure the windows loading thing appears and disappears for us and it doesn't appear in the processes on windows task manager when we try to launch it, no errors occurred as far as we know.

**Comment by kisak-valve** [comment]
Hello @CutieRin, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
