### ISSUE TITLE
[TF2] Invisibility texture broken on viewmodel arms after latest patch

### ISSUE THREAD

**Issue by AzureAzel** [ValveSoftware/Source-1-Games#3460]
The latest patch added some community fixes for invisibility textures while playing as Spy. While it improved the textures in third person, the first person textures fail to render on your arms while cloaked.

Here's an image of what it currently looks like in-game, courtesy of r/tf2. Your weapons cloak successfully, but your arms remain visible.

![invis](https://user-images.githubusercontent.com/39247293/101795459-ed620080-3ad5-11eb-9d8d-1da99b0b20f9.jpg)

**Comment by kisak-valve** [comment]
Hello @AzureAzel, per "Fixed the Spy's arms not cloaking" in the [2020-12-11 TF2 update](https://steamcommunity.com/games/TF2/announcements/detail/2933496588889446441), please retest this issue.

**Comment by AzureAzel** [comment]
> 
> 
> Hello @AzureAzel, per "Fixed the Spy's arms not cloaking" in the [2020-12-11 TF2 update](https://steamcommunity.com/games/TF2/announcements/detail/2933496588889446441), please retest this issue.

The issue seems fully fixed from what I can see.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
