### ISSUE TITLE
[TF2] More Backpack Slots

### ISSUE THREAD

**Issue by fearts** [ValveSoftware/Source-1-Games#3464]
The last time Backpack slots were increased was 12/21/2017. Since then 100s of new hats, taunts, unusualifiers, war paints tournament badges and charity items have been added to the game. I suggest increasing the limit from 3,000 to 4,000.

Thank you.

**Comment by AzureAzel** [comment]
I still agree with this being a possibility. The more items there are in the game, the more important it is to allow players to have space for those items. On the topic of extra space/slots, this request should also be looked at and considered: https://github.com/ValveSoftware/Source-1-Games/issues/2399

**Comment by fearts** [comment]
Here is a email I sent to Eric back in Feb on this issue with some addition information/suggestions.

My friend who runs a site which gathers data related to TF2 items and updates gave me the following information. Since 12/21/2017 (the last time backpack slots were increased) 3,545 unique items have been added to TF2. Before this date there were only 3,016 unique items in the game. So over the past 4+ years the amount of unique items has doubled and while the backpack slots have remained the same. Also, I would like to point out these numbers don't include the various combinations of War Paint wears and their weapon applied versions which would increase this number greatly.

I realize this probably doesn't affect the majority of the player base who have F2P accounts, but it has started to affect those who enjoy trading and collecting and do spend very large sums of money in this game. We are running out of space and the only viable method to continue collecting and trading is by using a second account which is not ideal. There are also now items in the game, the Golden Pan for example, which goes for over 3,000 TF2 keys and make it very hard to trade with limited slots.

I'd like to offer a few solutions:

1. Increase the number of allowed backpack slots using Expanders.
2. Create Storage containers like CS:GO has so we can store our items if we need free space.
3. Add a new option to the existing crafting system. This option will allow a player to combine X numbers of the same Key and the output would be a new item called a "Pile of X Keys". There are already items like this for example "Pile Of End Of The Line Key Gifts", the only change would be when you used it you would get the keys and not people on the server.
4. Create a new form of Metal that requires X Refine.

I understand there are very few people still working on the game. I hope you will look into this as it would greatly improve the quality of life for traders and collectors.

**Comment by AzureAzel** [comment]
> 

I agree with all of these. I genuinely think every one of these options should be considered or added, as it would add longevity to the system itself for little to no maintenance required by the TF2 Team, preventing the "treadmill" problem of additions causing more problems than they solve.

I'm not sure if Github posts can get "bumped" or anything like that, but I really wish we could do it for suggestions like this. It seems like a lot of our problems are being solved at the current moment, so I'd like for this to be more visible.

**Comment by Quintus24** [comment]
Hello,

According to the new update, this request seems to have been successfully implemented!
Very cool, TF2 Team!

![image](https://github.com/user-attachments/assets/e11aa009-1e96-44f2-8f40-834b4b714c0f)

**Comment by fearts** [comment]
The slots were increased so the original posts suggestion was fullfilled. However, I did later post again with additional ideas for inventory improvements which I still feel are valid for consideration. Not sure if you want to leave this open or have me make a new suggestion. I leave it to Kisak to decide. Thank you.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
