### ISSUE TITLE
[TF2] Matchmaking does not detect you being automatically disconnected to join a community server

### ISSUE THREAD

**Issue by CriticalFlaw** [ValveSoftware/Source-1-Games#3466]
When you're in an official Valve matchmaking server, you can queue for another official match and be connected to it when one has been found. But if you're set to Auto-Join a community server while in a Casual match and start connecting - the game's matchmaking assumes that you left unintentionally and will start a ten second countdown to join you back in.

The game's matchmaking does not seem to detect that you've been automatically disconnected to join a community server while in a casual match. This results in you being pulled back into your previous casual match while connecting to a community server.

**Comment by kisak-valve** [comment]
Possible duplicate of #2821.

**Comment by CriticalFlaw** [comment]
It's a similar issue, though not reproducible the same way as #2821. I can add my notes to that issue if you want to close this one.

**Comment by CriticalFlaw** [comment]
Added my note on how else to reproduce the issue to #2821. Closing this one as a duplicate. Thanks @kisak-valve
