### ISSUE TITLE
[EP1] Can't pass combine glass door in wrecked train after Zombine attacks with the grenade because he does not die (ep1_c17_00)

### ISSUE THREAD

**Issue by rataje** [ValveSoftware/Source-1-Games#3480]
EDIT: The Combine Zombie Soldier does not die from (his own) grenade which causes the passage to fail !!!

I've did "Verify Integrity of Game Files", 
A complete reinstall 
first Half-Life 2, then Episode One and second try was only Episode One. 
I did "Verify Integrity of Game Files" again after reinstall. 
I've tried some older versions of maps, scenes, scripts and models but nothing works!

**Comment by Yetoo1** [comment]
Can you make a separate save before it wakes up and one after it explodes, copy them to a zip, and post the zip here.
