### ISSUE TITLE
**January 2021** - Still ZERO support on HL2DM/TF2/CSS for multichannel audio > 2

### ISSUE THREAD

**Issue by scorpius2k1** [ValveSoftware/Source-1-Games#3494]
**January 2021** - Still ZERO support on HL2DM/TF2/CSS for multichannel audio > 2

_Originally posted by @scorpius2k1 in https://github.com/ValveSoftware/Source-1-Games/issues/93#issuecomment-760301921_

**Comment by kisak-valve** [comment]
Hello @scorpius2k1, this issue is already being tracked at #1678. Closing as a duplicate.
