### ISSUE TITLE
[Feature Request] [Linux] [Source] Feature Request: Vulkan backend using DXVK-native

### ISSUE THREAD

**Issue by Rajalolxd** [ValveSoftware/Source-1-Games#3499]
As mentioned here https://github.com/ValveSoftware/csgo-osx-linux/issues/2495 it would be good if this would be implemented in Source 1 games.

1. Wine + DXVK in CS GO (or any other source 1 game) for example is much faster than native version with ToGL
2. If you try to run any Source games with VAC via Proton (to get better performance bc of dxvk), VAC just doesnt work (but with wine it does)

**Comment by kisak-valve** [comment]
Hello @Rajalolxd, this request is already being tracked at #2844. Closing in favor of the older issue report.
