### ISSUE TITLE
[HL:S] Elevator sound doesn't play when going down it in Anomalous Materials.

### ISSUE THREAD

**Issue by AFellowSpeedrunner** [ValveSoftware/Source-1-Games#3504]
This might be stupid to say this but well I mean I wanna get this game fixed up a bit more. I don't think anyone cares about HL:S anymore and like Black Mesa a lot better.

**Comment by IAmTheNerdNextDoor** [comment]
Closing this since HL:S has been delisted on Steam and I highly doubt that Valve will attempt to fix it.
