### ISSUE TITLE
Trailing slash in vpk_linux32 directory path.

### ISSUE THREAD

**Issue by omp** [ValveSoftware/Source-1-Games#353]
When the directory passed to the vpk command has a trailing slash, the file gets created as a hidden file named '.vpk' within the directory, instead of a file named 'dirname.vpk' in the parent directory.

```
$ ~/.steam/steam/SteamApps/common/Team\ Fortress\ 2/bin/vpk_linux32 tf2hud/
Finding files and creating temporary control file...
Control file lists 138 files
  Total file size . . . . :      1014801 bytes
  Size in preload area  . :            0 bytes
  Size in data area . . . :      1014801 bytes
omp@scht ~/dev $ find . -iname *vpk
./tf2hud/.vpk
```

I suppose it's just adding '.vpk' to the argument as-specified; it might be a better idea to remove the trailing slash before doing so.

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved.
