### ISSUE TITLE
TF2 crashed upon alt-tab

### ISSUE THREAD

**Issue by zelmor** [ValveSoftware/Source-1-Games#3543]
System information via Steam: 
https://gist.github.com/zelmor/c18f1f7a1c746152e0b4dae8a07c2685

Issue description: 
while in game, alt tabbing causes crash with the following output on console:
https://gist.github.com/zelmor/723fb04da945385da2da7b78cdc0b272

I have checked the file in question, and 
```/home/zelmor/games_drive/Steam/steamapps/common/Team Fortress 2/tf/textwindow_temp.html!```
does not exist on the system. I have noticed however that the space character is not properly escaped in the filesystem location. In bash it should be: ```Team\ Fortress\ 2/```

I have attempted to start the game with the -autoconfig flag, no to avail.
The issue started after I attempted to create player scripts for engineer and spy. I removed the scripts entirely, but the issue remained. I removed the game via Steam Library, and reinstalled, but this didn't resolve the issue either.

Please let me know if any more information is needed to resolve this, or if there is a known workaround.

Thank you

**Comment by kisak-valve** [comment]
Closing as outdated.

**Comment by LethalManBoob** [comment]
still crashes on alt tab for me sometimes

**Comment by kisak-valve** [comment]
Hello @LethalManBoob, please open a new issue report with logs and system info.
