### ISSUE TITLE
[TF2] Blood particles and effects randomly appearing in the cut version

### ISSUE THREAD

**Issue by gindiener** [ValveSoftware/Source-1-Games#355]
![2013-05-01_00002](https://f.cloud.github.com/assets/4311903/448907/80e4b624-b260-11e2-879c-0aa4684104e0.jpg)
Since the steampipe-update I noticed that even though I am playing the cut version of the game (duo to germany...) the blood particle effects on hitting someone and the blood effects on objects do occasionally appear.
But apart from these rare occasions the usual cut yellowish blood is used (and no blood on objects).
It seems to happen randomly and in about two hours playing I saw it about three times.
On my game i do not have any mods installed, the server did not have game changing mods installed either.
Running Windows 7.

**Comment by kisak-valve** [comment]
Hello @gindiener, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
