### ISSUE TITLE
[TF2] MvM - Tour descriptions do not properly describe possible loot, demotivating players from playing the tour

### ISSUE THREAD

**Issue by AzureAzel** [ValveSoftware/Source-1-Games#3554]
The descriptions for some tours do not accurately describe the possible loot for that tour. They have shared the same descriptions since the very beginning, despite one particular patch from 2014 changing what tours you can get Australium weapon drops in:

[This patch](https://www.teamfortress.com/post.php?id=15304) adds compatibility for Australium weapon drops in **all** Advanced and Expert tours, per _"MvM : Added chance to find Australium weapon rewards to all Advanced and Expert Mann vs. Machine tours. Previously only available on the Two Cities tour."_

However, the descriptions of these tours were not altered to match this change. As a result, a lot of players are still completely unaware that this change was made, resulting in an overwhelming majority of MvM players queuing solely for the Two Cities tour due to thinking that Australium weapons are unique to that specific tour still.

In order to fix this, you just need to mention that Australium drops are enabled inside the descriptions of the tours listed below. I guarantee you'll absolutely see a spike in players in these tours if you were to fix this.

### The following tours have **_active Australium drops._** However, **_their descriptions completely omit mentioning it:_**
![](https://i.imgur.com/4L44C4l.png)
![](https://i.imgur.com/7zQzQjG.png)
![](https://i.imgur.com/WtZghl9.png)

### The Two Cities tour has always had support for Australium drops, and appears as such:
![](https://i.imgur.com/iQNSIav.png)

**Comment by thejaviertc** [comment]
It seems like they added it on [August 11, 2022](https://www.teamfortress.com/post.php?id=141793) update but they didn't mentioned it:

![imagen](https://user-images.githubusercontent.com/45662206/184366606-9e4d26be-ad2a-44a1-831a-a8157659a5c1.png)
