### ISSUE TITLE
TF2 Crashes After Loading

### ISSUE THREAD

**Issue by jachan** [ValveSoftware/Source-1-Games#356]
TF2 boots up, then crashes after getting to the screen with the picture of 2fort.

**Comment by kisak-valve** [comment]
Closing as there is nothing actionable in this issue report.

**Comment by El-Capitan** [comment]
Bravo,  No attempts to troubleshoot in three years... hope nobody makes the mistake of getting me any valve products for the holidays.

**Comment by kisak-valve** [comment]
This issue report fell into limbo when there was no response in May 2013 and nothing was provided to investigate further.
