### ISSUE TITLE
Japanese characters on tf2 (all source games?) on linux.

### ISSUE THREAD

**Issue by jimmysavile** [ValveSoftware/Source-1-Games#3565]
it seems like a font for japanese characters is just assumed to be installed, not installed with the game, as when in a name, japanese characters appear to be long strings of spaces, and things that are supposed to go after the name (killfeed icons, the colon after your name in chat) will appear before the name. I noticed this when playing on a community server, so might be due to that in relation to sv_pure or it could be as simple as a font pack not being installed with the game.

**Comment by kisak-valve** [comment]
Hello @jimmysavile, this issue is already being tracked at #2674. Most likely due to `fonts-wqy-zenhei` or equivalent not being installed as a system package.

Feel free to add your experience to the older issue report. Closing as a duplicate.
