### ISSUE TITLE
Tf2 stuck at motd and steam crashes after latest steam beta update

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/Source-1-Games#3569]
#### Your system information

* Steam client version (build number or date): 1621893676
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] y
* Have you checked for system updates?: [Yes/No] y
* System info: https://gist.github.com/echaskaris/c9ff74152ff8b360da6ac8f9963a25b5

#### Steps for reproducing this issue:

1. Get into a casual tf2 match
2. Tf2 unresponsive at motd/welcome screen, cannot click next/continue, steam also unresponsive, have to kill the process

Please verify that the issue appears for you too, because it may be some packages I installed related to the missing libpipewire issue yesterday.

EDIT: I uninstalled some pipewire packages, rebooted and the issue persists.

**Comment by AzureAzel** [comment]
I dealt with this issue earlier today on Windows. It also had the side effect of making the community server browser unresponsive when trying to get server info, resulting in almost every server name being replaced with it's IP, and every player count being either 1/1 players, or 0/1 players, based upon if there's people playing on the server or not.

I reinstalled Steam, and that seemed to solve the problem.

**Comment by TechdudeGames** [comment]
I was having the same problem on Linux as well, and it appears the newest update 1621998891 fixes the problem as I have been able to enter a TF2 match without is crashing.

**Comment by echaskaris** [comment]
Yes fixed
