### ISSUE TITLE
TF2 Crashes after loading

### ISSUE THREAD

**Issue by desertedbart** [ValveSoftware/Source-1-Games#357]
Hi,
I just installed the latest tf2, and didn't know about the resource and scripts folder, so I deleted them, but learned that I had to do the custom thing. For some reason, it won't restore the resource and scripts folder. Is there a fix for this?
Thanks,
Soup

**Comment by xgdgsc** [comment]
I started having this for 2 months. I' ve validated local cache.

**Comment by kisak-valve** [comment]
Closing as there is nothing actionable in this issue report.

@xgdgsc, if you are still having a problem and https://wiki.archlinux.org/index.php/Steam/Troubleshooting does not help, then open a new issue report.
