### ISSUE TITLE
L4D2 crashes when loading a map, `null not valid`

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/Source-1-Games#3585]
OS: OpenSUSE Tumbleweed
GPU: Nvidia 1650 Super @ 465.31
CPU: AMD Ryzen 5 3600
System Info: [gist](https://gist.github.com/kiroma/a02e797e82266f29f4aac4ab4ef57275)

No workshop items loaded, when loading into any map, close to the end of the process the game crashes with the message:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```
Backtrace points to the last frame being from `chromehtml.so`

**Comment by kiroma** [comment]
Yes

**Comment by Yetoo1** [comment]
@kiroma I wasn't able to reproduce the issue. I need to update to latest fedora kernel though (5.12.10-200; current is 5.12.9-200) and retest.

L4D2 Version:
Version 2.2.1.3 (left4dead2)
Network Version 2.1.0.0
Exe build: 00:51:56 May 20 2021 (8230) (550)

System information:
https://pastebin.com/Gzm6KYxx

**Comment by tnbp** [comment]
Might be an OpenSUSE problem. I have the same problem on at least two machines, one with a Ryzen 9 and 2080ti, the other with a Vega 3 integrated.

Additionally, "non-static" strings seem to be missing: Friends' names, server names, even resolutions are missing entirely. The loading screen reads "Starring: ,,,".

**Comment by tnbp** [comment]
![grafik](https://user-images.githubusercontent.com/4947589/122459173-e4844700-cfb0-11eb-8d21-f0a036bbdd52.png)

**Comment by tnbp** [comment]
I *think* it works again for me after installing `gcc7-locale`, `glibc-locale-base` and `glibc-i18ndata`.
I also started Steam with `LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam`. I now have text again and the game didn't crash on joining an online game.

HTH

**Comment by Superwaitsum** [comment]
@tnbp , thanks for listing the possible packages, after testing them, I found the missing package was `glibc-locale-base-32bit` (didn't try to install `gcc7-locale` since it had lots of dependencies and game still works after uninstalling `glibc-i18ndata`). I already had `glibc-locale-base` installed, but after installing 32 bit version, l4d2 worked perfectly without preloads

**Comment by kiroma** [comment]
Yeah, no preloading needed and it works, but also ties into https://github.com/ValveSoftware/portal2/issues/321 which is solved after installing that package.
