### ISSUE TITLE
[L4D2] New FOV slider value doesn't persist through subsequent game launches

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#3586]
The FOV slider in options -> multiplayer -> field of view doesn't persist through subsequent game launches. It resets back to 90. I tested setting gore to low and it persists through to a subsequent game launch, but the FOV slider value doesn't. 

L4D2 Version:
Version 2.2.1.3 (left4dead2)
Network Version 2.1.0.0
Exe build: 00:51:56 May 20 2021 (8230) (550)

System information: 
https://pastebin.com/Gzm6KYxx

**Comment by Yetoo1** [comment]
@kisak-valve This issue appears to be resolved in the latest (7/8/2021) update.

**Comment by kisak-valve** [comment]
Thanks @Yetoo1, closing per "- Set FOV value as archived" in the [2021-07-08](https://store.steampowered.com/news/app/550/view/2990935241286354880) Left 4 Dead 2 update.
