### ISSUE TITLE
L4D2 - Latest patch removes ability to change in game Brightness

### ISSUE THREAD

**Issue by thoughtcrimeo** [ValveSoftware/Source-1-Games#3588]
The Brightness bar is no longer available in Options after the latest patch. The game is now too dark.

Furthermore, Steam Support directed me here to make this report. Having to make a github account to file a bug report, rather than using Steam's built in function is absurd.

**Comment by dcanning** [comment]
try this:
1. open cfg folder here:
    `<program files x86>\Steam\steamapps\common\Left 4 Dead 2\left4dead2\cfg`
1. add this line to `video.txt` file (using any text editor)
    `	"setting.mat_tonemapping_occlusion_use_stencil" "1"
    `
    just above the closing `}`
1. save the file
1. right click the file, click properties, check `read only` box
that last step is critical or l4d2 will overwrite the file and remove that change.

I found this long ago, props here: 
https://steamcommunity.com/sharedfiles/filedetails/?id=954836428

**Comment by thoughtcrimeo** [comment]
I followed these instructions but they did not solve the issue. The Brightness option is back but it is now greyed out and cannot be interacted with. There is no Brightness slider to the right of it.

**Comment by Yetoo1** [comment]
I was able to change brightness in the linux build. This may just be a Windows issue.

**Comment by thoughtcrimeo** [comment]
I'm using Win7.

**Comment by mustymaster** [comment]
if you are using "windowed" no border or "windowed" your game will automatically set the brightness to your moniter's brightness.
make sure try the fullscreen mode to adjust the brightness in game.

**Comment by thoughtcrimeo** [comment]
Thanks mustymaster, somehow my game was set to Windowed No Border, not Fullscreen. Set to Fullscreen and the Brightness option is back.

**Comment by mustymaster** [comment]
> 
> 
> Thanks mustymaster, somehow my game was set to Windowed No Border, not Fullscreen. Set to Fullscreen and the Brightness option is back.

you're welcome. wish you a happy time :)
