### ISSUE TITLE
[TF2] [QoL] Make "tf_viewmodels_offset_override" a usable command outside of sv_cheats

### ISSUE THREAD

**Issue by AzureAzel** [ValveSoftware/Source-1-Games#3589]
"tf_viewmodels_offset_override" is a console command that controls the X Y Z coordinates of your viewmodel origin, allowing you to customize the position of your viewmodels. You can input 3 numerical values after the command, each separated by spaces, that will change the offset of your viewmodel. This command is currently locked under sv_cheats, and is therefore unusable on most servers.

CS:GO already allows you to (mostly) freely customize the position of your viewmodels through 3 similar commands with the same function; "viewmodel_offset_x", "viewmodel_offset_y", and "viewmodel_offset_z". These commands aren't sv_cheats locked. But the one from TF2 is. As such, I don't see any real reason to lock it. While I do enjoy the already existing minimized viewmodels, it'd be nice to be able to change the positioning myself freely without having to decompile the existing viewmodel animations, change their $origin, and then recompile them all over again to be used as an animation mod.

**Comment by kisak-valve** [comment]
Hello @AzureAzel, this feature request is already being tracked at #2484. Closing as a duplicate.
