### ISSUE TITLE
TF2: Crash in class selection menu if multicore rendering is enabled

### ISSUE THREAD

**Issue by nairol** [ValveSoftware/Source-1-Games#359]
**Steps to reproduce:**
1. Have "multicore rendering" enabled in the advanced video options
2. Connect to a server
3. In the MOTD screen click continue
4. Select a team
5. Hover your mouse over each class OR press one of the number keys to select a class
6. Repeat step 5 until game crashes

[Here is a video](http://www.youtube.com/watch?v=2NYxG0cBn-g) showing the problem. First with multicore disabled, then enabled. The window freezes after this video. I was not able to record that though.
[Here is a screenshot](http://i.imgur.com/zX2IJG6.png) of TF2 after the crash happened. It's in German but I guess you all know this little window.

**Additional info:**
- Only tested on Windows 7
- This all started with an update in the second half of February 2013. I can't remember which one, sorry.
- I've had multicore rendering enabled for at least a year, if not forever, without a problem.
- If I turned multicore rendering off, the game would crash while changing maps (at ~20% progress bar). I could only play one map per TF2 instance.
- The crashes after each map also started to happen with multicore rendering _enabled_ in late March or early April 2013. So then I had random crashes while selecting classes _and_ guaranteed crashes after each map.
- With the update that introduced Steampipe those crashes during map changes disappeared completely.
- All of the mentioned crashes ONLY happen(d) on remote servers, NOT if I used the built in server (Listen-server?). I did not test with local dedicated server.
- Hovering over Scout (or pressing 1) has a very high probability of triggering the crash on an empty server.
- I've had crashes for almost all other classes too. Definitely for Demoman, Soldier and Pyro.
- I've deleted all files in the cfg folder and it still happened.
- I don't have a custom HUD and never had one on this PC.
- Yes, I've clicked the "verify integrity of game files" button. No I haven't done a re-install.
- It also happens on official Valve servers (that have no mods and plugins).
- It happens in fullscreen and window mode
- It happens with and without Fraps running
- My steam ID is STEAM_0:0:23394812
- I have 42 crashdump files in the ...\Steam\dumps folder. Should I upload them somewhere or will they automatically be collected by Valve?

--> [**Hardware Info**](https://gist.github.com/nairol/2324102e600845444ae5#file-gistfile1-txt) <--

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
