### ISSUE TITLE
[TF2] Wrong Mouse input in item/player overview

### ISSUE THREAD

**Issue by SupinePandora43** [ValveSoftware/Source-1-Games#3599]
# Video

https://user-images.githubusercontent.com/36124472/123535765-5a21ad00-d73f-11eb-8474-3c2a3bcc2763.mp4

# info

it is only smooth when used in middle (few mid pixels)

# Platforms

- [x] Linux

**Comment by SupinePandora43** [comment]
It looks much worse with custom huds that let's scale and angle (on other axis)

**Comment by kisak-valve** [comment]
Hello @SupinePandora43, this issue is already being tracked at #95. Closing as a duplicate.
