### ISSUE TITLE
[L4D2] Huge Lag And Performance Issues

### ISSUE THREAD

**Issue by nitro-1** [ValveSoftware/Source-1-Games#3603]
Dedicated L4d2 Servers : Linux / Windows

Left 4 Dead 2 : After the Last Game Update almost all Maps With Water No More Playable, Huge Lag And Big Performances Drop.

The problem happens only when many Survivors in Water at same time, Very Big CPU Spikes when that happens and if the CPU is not a strong fast one, those maps are no more playable.

We tested few things like Remove Water from maps, Remove the Slowdown Function, Even Remove Fog and use some patches using some plugins too but the problem persists.

The game Performance in Water has to be fixed because it's using so much ressources for now.

**Comment by A1mDev** [comment]
The problem was solved after the last update! You can close!
