### ISSUE TITLE
[ANY] Death in prop_vehicle_driveable = client crash

### ISSUE THREAD

**Issue by Bubka3** [ValveSoftware/Source-1-Games#362]
Sometimes, when you die inside of a "prop_vehicle_driveable" (driving it) your client will crash. It's very annoying.

**Comment by kisak-valve** [comment]
Hello @Bubka3, are you still experiencing this issue? If you are please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. Also include any CrashIDs or minidump files related to this issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.
