### ISSUE TITLE
[L4D2] Client side issues

### ISSUE THREAD

**Issue by lunatixxx** [ValveSoftware/Source-1-Games#3626]
Cause: 
Connection drop or alt tab.

Problem: 
Case 1 -> A player become invisible.
Case 2-> A player is not moving when it should.
Case 3 rare -> A survivor model is cloned and replace another survivor model (for example two zoey and bill missing)

Solution that is not really one is to type in console:

```
record demo 
stop
```

**Comment by kisak-valve** [comment]
Hello @lunatixxx, you've already reported this issue at #3485. Please do not intentionally create duplicate issue reports.

Closing as a duplicate.

**Comment by lunatixxx** [comment]
This is a different issue, duplicate survivor was adding a 5th survivor on server...

**Comment by lunatixxx** [comment]
Ah this one: https://github.com/ValveSoftware/Source-1-Games/issues/3485

I did not remember.
