### ISSUE TITLE
[Portal Window] Achievement is not given

### ISSUE THREAD

**Issue by gusals4001** [ValveSoftware/Source-1-Games#3627]
I already meet the requirements but three achievements not completed including the "Aperture Science" achievement.
Can you give me some help?
![portal1](https://user-images.githubusercontent.com/87918819/126884610-99d30bef-e7dd-4668-be68-669d807a9a46.jpg)
![portal2](https://user-images.githubusercontent.com/87918819/126884611-d3232d83-cd07-4b01-a720-c8b3b29c513e.jpg)
https://drive.google.com/file/d/1Ka5OgnAba_F7pl22EUdu2PgD6J2-vQ2q/view?usp=sharing

**Comment by kisak-valve** [comment]
Hello @gusals4001, this issue is already being tracked at #3502. Closing as a duplicate.
