### ISSUE TITLE
[TF2] Two disable sprays check boxes instead of one.

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#3659]
This may have been an issue before the recent September 16 update, but there are two disable sprays checkboxes in in Options -> Multiplayer -> Advanced with one near the bottom and one at the very bottom. The former is the one that's checked by default, but the very one at the very bottom is unchecked.

One near the bottom:
![20210916174158_1](https://user-images.githubusercontent.com/12403440/133706092-76972039-9245-4024-a6d9-7287b47a6762.jpg)

One at the very bottom:
![20210916174202_1](https://user-images.githubusercontent.com/12403440/133706105-89ce8883-2294-48a7-a111-b158ad3ea937.jpg)

TF2 version:
Build Label:           6770799   # Uniquely identifies each build
Network PatchVersion:  6770799   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:        6770799
Server AppID:           232250
Client version:        6770799
Client AppID:              440

System info:
https://gist.github.com/Yetoo1/1517bcf2040d7e9301ea76da6ccbf301

**Comment by Gamecube762** [comment]
Adding on, the cvar `cl_playerspraydisable` was replaced with `cl_spraydisable`.  This wasn't mentioned in the update log and likely related to why a 2nd "Disable Sprays" checkbox exists. I'm assuming the developer who worked on this intended to update the checkbox's cvar instead of creating a 2nd checkbox.

**Comment by FindTheBorealis** [comment]
I don't have this duplicate setting and the October 5 patch updated the spray settings again, could you retest?

**Comment by kisak-valve** [comment]
Closing per the last comment.
