### ISSUE TITLE
[TF2] Add setting / cvar to disable the new automatic spray cache purge

### ISSUE THREAD

**Issue by cyberkitsune** [ValveSoftware/Source-1-Games#3663]
Since the update on 9/16/2021, the `materials/temp` folder is purged when the game launches, as well as when loading into a new server.

I understand the rationale for adding this behavior but I'd like an **opt-out** option for this, either as a cvar or advanced setting option, as generally it adds seconds of loading time to game launch for me, server loading, and it incurs additional bandwidth use as the same sprays have to be redownloaded all the time.

**Comment by cyberkitsune** [comment]
This was added in the Scream Fortress 2021 Update:
```
Added ConVar "tf_delete_temp_files" to control custom player sprays and other temp files being deleted on shutdown
```

**Comment by kisak-valve** [comment]
Closing per the last comment.
