### ISSUE TITLE
I am not receiving some achievements from Portal on Steam.

### ISSUE THREAD

**Issue by Danropu** [ValveSoftware/Source-1-Games#3664]
Mi problema es el siguiente: he completado todos los desafíos de los mapas de bonificación en Portal en sus tres modalidades (menos tiempo, portales y pasos), todos ellos con su respectiva medalla de oro y no consigo desbloquear los logros correspondientes de "Ciencia de instituto", "Ciencia aeronáutica" y "Ciencia dimensional". Así como adjunto en las fotos, se puede ver que, pese a haber completado los 18 desafíos en todas sus dificultades, tanto en Steam como en el propio juego Portal no tengo los logros anteriormente mencionados desbloqueados. Cabe recalcar que he activado los comentarios de los desarrolladores, por lo que supongo que ahí es donde reside el problema. En caso de que este sea el causante del mismo, ¿cuál sería la manera de quitarlo o resolver el problema en general?

Un saludo.
![Captura de pantalla (978)](https://user-images.githubusercontent.com/90985007/133906515-66ec8329-2813-40f1-bd46-f86a91094e4f.png)
![Captura de pantalla (976)](https://user-images.githubusercontent.com/90985007/133906516-8a04266f-afc1-4add-b343-9cb8d9d6a9ca.png)

---
Google translate:
My problem is the following: I have completed all the challenges of the bonus maps in Portal in its three modes (less time, portals and steps), all of them with their respective gold medal and I cannot unlock the corresponding achievements of "Science of institute "," Aeronautical Science "and" Dimensional Science ". As attached in the photos, you can see that, despite having completed the 18 challenges in all their difficulties, both on Steam and in the Portal game itself I do not have the aforementioned achievements unlocked. It should be noted that I have activated the comments of the developers, so I guess that is where the problem lies. If this is the cause of it, what would be the way to remove it or solve the problem in general?

**Comment by kisak-valve** [comment]
Hello @Danropu, this issue is already being tracked at #3502. Closing as a duplicate.
