### ISSUE TITLE
[TF2] Add new entity filter_activator_context to the game

### ISSUE THREAD

**Issue by SpookyToad2** [ValveSoftware/Source-1-Games#3681]
This is a Feature Request for adding `filter_activator_context` entity in Team Fortress 2.

TF2 as the most Source games has the **Response Contexts System** built in it.
We can look at response contexts as at the key value pairs of some unique entity.
There're several inputs mappers can use to Create|Remove|Update those.
But there's no way to Get them...

TF2 is mostly multiplayer game and sometimes you have to check players if they have set some *flags*.
There're few ways of adding *flags*, but each of these allow to implement only one-two of them in summary.
At present we only have the ability to filter by team and targetname, which makes it extremely difficult to create the interesting new gameplay experiences we want to.
An example scenario is checking if a player has collected and is carrying *keys* that allow access to special areas, or if a player has had some necessary experience, or some form of aspect change.
But sometimes you have to check if player have multiple *keys*.

[This is the example video](https://youtu.be/aeiBIywUgSY) with map that has five *flags* or *keys*:
1. Is player small.
2. Is player red.
3. Is player transparent.
4. Does player have a key to open the first door?
5. Does player have a key to open the second door?

It's impossible for player to have all five *flags*, because there's no way to implement it.
But `filter_activator_context` entity is great for that task, this entity can support enough number of *flags*,
because this entity can filter depending on which response contexts a player or entity has.
Using filters is the best way to check flags as it's the part of native functionality. There're many things supporting filters.
One of them are triggers. Filters are the only way to filter the *Touching* with some triggers, especially with `trigger_hurt`.
By the way, the **Response Contexts System** is used for unique stuff in Team Fortress 2.
That is used to say if player has [fly](https://wiki.teamfortress.com/wiki/Brundle_Bundle) or [princess](https://wiki.teamfortress.com/wiki/Grand_Duchess) sets and many other cool features. With that entity it would be possible to filter players by those criteria.

You should add this entity as it's very useful entity and easy to do, because Team Fortress 2 already has the **Response Contexts System**.
Also this entity is already implemented in "Source-1-Game" L4D2, so you literally could just copy paste existing code.
At [wiki page of filter_activator_context](https://developer.valvesoftware.com/wiki/Filter_activator_context) it's said that in code, it is represented by the `CFilterContext` class, defined in the `filters.cpp` file.

[The map's gist.](https://gist.github.com/SpookyToad2/ba03f306914a606a0f34d4a46edc1ef0)

**Comment by R60D** [comment]
Definently, this something that should have been in TF2 from the beginning. As it allows mappers to effectively use player set context as "variables" with the filter.
As a custom gamemode mapper myself, I have had to create unnecessary complicated setups just to achieve something simple as storing and using information set from the player.

**Comment by Berke111** [comment]
This entity definitely would be very handy, I can't stress how many times I had to save a state of a player, but had to use a workaround to achieve such thing, even that it is very limited, this would be very useful for us mappers.

**Comment by St-Relock** [comment]
*This is really going to be the best filter ever...*
If i used it for my [infection system](https://www.youtube.com/watch?v=ERB1J7EhABA), it could be done **much** easier...
The power of this entity is behind of understanding.

Please, add this entity.
You could add the little update for mappers, the collection of all issues related to entities.
It would make content more interesting and bring a lot of new ideas for us.

**Comment by worMatty** [comment]
I'd love the ability to add flags to a player and filter by them. Only being able to use the targetname is so limiting. The response rules system is not the ideal way to do this but you could consider it killing two birds with one stone - the ability to filter responses could be beneficial for custom game modes.

**Comment by Ashetf2** [comment]
I've heard that this entity "could" be replaced with a table of players and variables now that we have VScript, but that adding this entity would be easier since it's pure logic.

**Comment by worMatty** [comment]
I don't like using things for purposes they were not intended to be used for, as it brings potential for conflicts. I think using VScript to keep track of flags and such is better, and requires more work, but hopefully in the future some people will make scripts for this that can be interacted with using logic, that can be imported as a prefab.

**Comment by SpookyToad2** [comment]
No point to add this entity any more since vscript has been added.
