### ISSUE TITLE
[TF2] Halloween class masks are not obtainable from Halloween packages anymore

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/Source-1-Games#3683]
I have not gotten a new one or even a duplicate one for 2 or 3 scream fortresses now. Got 4 of them fairly quickly and then nothing.

**Comment by jh34ghu43gu** [comment]
Public data does not back this up, for example the [gifted origin (what package item origins are) scout mask](https://backpack.tf/premium/search?item=Scout+Mask&origin=6) has item ids in the 10.8 billions which is the aprox. current item id area.

**Comment by echaskaris** [comment]
I see, thank you. I went ahead and opened some Halloween packages I had and got an engineer mask, which I didn't have.
