### ISSUE TITLE
[TF2]  MvM Workshop map population files refuse to load

### ISSUE THREAD

**Issue by Matty-64** [ValveSoftware/Source-1-Games#3698]
After the October 22nd update,  MvM maps loaded using the workshop no longer load their similarly named .pop files.  Saying the population file is 'invalid'.

In order to use MvM maps with the workshop.  The host must sync the map with `tf_workshop_map_sync <id>` and then load the map with `map workshop/<bsp_name>.ugc<id>` right?

Maps loaded this way won't look for files named after the BSP, but will look for files using the name inputted above (even if you did `map workshop/<id>` instead).  I'll use [MvM Damm](https://steamcommunity.com/sharedfiles/filedetails/?id=1092381461&searchtext=MvM+Damm) as an example: If we load that workshop map using `map workshop/mvm_damm_r1.ugc1092381461`.  MvM will attempt to load this population file: `scripts/population/workshop/mvm_damm_r1.ugc1092381461.pop`.  This naming scheme isn't exclusive to pop files either, even the map's nav mesh and resource file need to follow this naming scheme in a workshop subfolder in order to be loaded.  I'm still unsure if this is intentional.

But before the update, population files named like this would load without problem and no issues were observed using them.  Which allows MvM server owners like myself to host MvM maps through the workshop.  But now the population files refuse to load no matter what, making it impossible for dedicated servers to host MvM maps using the workshop.

**Comment by agrastiOs** [comment]
@kisak-valve Fixed in latest patch.

**Comment by kisak-valve** [comment]
@agrastiOs, thanks for the ping.

@Matty-64, per "Fixed servers not being able to load Mann vs. Machine .pop files for workshop maps" in the [2021-11-15](https://www.teamfortress.com/post.php?id=101361) TF2 update, please retest.

**Comment by kisak-valve** [comment]
Closing as fixed.
