### ISSUE TITLE
"Game language" option's logic is inconsistent

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#37]
Issue transferred from ValveSoftware/steam-for-linux#294
@kunitsin posted at 2012-12-22T19:27:15Z:

On Windows, game language option (right click on game/Settings/Language/Select a language) controlled only the language used in audio files, but the text in this game is always displayed using Steam client's language setting (at least for Valve's games). So, if user selects English for TF2 and Russian for Steam client, voice acting in TF2 will be English, and text strings will be in Russian.
On Linux, game language option sets language for both audio and text.

**Comment by kisak-valve** [comment]
Hello, Is anyone still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Shished** [comment]
I just tried and the problem still persists.
After changing language in TF2 audio settings, game asks for restart and then opens a specific url:

`steam://run/440/english`

which starts the game but it changes the whole UI to a selected language.

BTW, selecting Ukrainian changes UI language but voice lines are still in English.

**Comment by Ashetf2** [comment]
> I just tried and the problem still persists. After changing language in TF2 audio settings, game asks for restart and then opens a specific url:
> 
> `steam://run/440/english`
> 
> which starts the game but it changes the whole UI to a selected language.
> 
> BTW, selecting Ukrainian changes UI language but voice lines are still in English.

I guess that there aren't translations to Ukrainian for voice lines
