### ISSUE TITLE
Linux Freezing During Gameplay (TF2)

### ISSUE THREAD

**Issue by Pinky022** [ValveSoftware/Source-1-Games#3709]
During gameplay, the game will freeze once per match for >10 seconds without fail. It seems to happen at a random time and when it does there is a sound loop as well. After 10-30 seconds the game will continue as normal and there will not be another big freeze until the next match. In addition after the freeze occurs some players turn invisible.  This only happens on my Linux system and not Windows. Windows the game runs perfectly. The game is on an external hdd for both operating systems formatted ntfs.

Launch options:

gamemoderun %command% -w 1920 -h 1080 -novid -freq 144 -refresh 144 -tickrate 128 -noipx -nod3d9ex -console -high -noforcemaccel -noforcemspd -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -heapsize 4194304

Config: https://drive.google.com/file/d/13965BGwin0fFL1xbeWnn3HcrDsf_8Lp7
Specs:

OS: Manjaro Linux x86_64
Kernel: 5.13.19-2-MANJARO
Resolution: 1920x1080, 1920x1080
DE: Plasma 5.22.5
WM: KWin
WM Theme: Sweet-Dark
Theme: ArchPurple [Plasma], Breeze [GTK2/3]
CPU: Intel i7-2600 (8) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1060 3GB
Memory: 15982MiB

**Comment by Pinky022** [comment]
After trying some things out, I think that the problem seems to be in game demo support that automatically records demos of your matches. After stopping demo support, the game runs perfectly with no freezes.

**Comment by CrezyDud** [comment]
why did you provide your WM Theme? (lol)
much better if you said if you are using wayland or not
wayland sucks on nvidia
stay away from nvidia
(and as long as you have nvidia, stay away from wayland)

**Comment by Pinky022** [comment]
I am using x11 I believe

**Comment by Yetoo1** [comment]
@Pinky022 Did a recent update fix this issue for you?

**Comment by Pinky022** [comment]
Before I was running the game on an ntfs partition.  After moving the game to an ext4 partition, no more freezes occurred.
