### ISSUE TITLE
[Portal Linux Beta] Crash after loading with Bublebee

### ISSUE THREAD

**Issue by VlasovRoman** [ValveSoftware/Source-1-Games#371]
Ubuntu 13.04
Intel Core i5 2.6GHz
Video card: NVIDIA GeForce GT 620M
Video Driver: 319.12 with Bumblebee

Without video driver Portal started normally

**Comment by kisak-valve** [comment]
Hello @VlasovRoman, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
