### ISSUE TITLE
[TF2] tf_projectile_ball_ornament colliding with func_lod entities

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#3724]
Hello,

The Wrap Assassin's bauble - tf_projectile_ball_ornament also has the issue of breaking on func_lod, just like Dragon's Fury, Short Circuit, and tf_projectile_energy_ring projectiles were before. Adding tf_projectile_ball_ornament to the entity list to ignore func_lod would fix this issue.

Thanks for reading this bug report.

**Comment by kisak-valve** [comment]
Hello @agrastiOs, this issue is already being tracked at #2702. Closing as a duplicate.

**Comment by agrastiOs** [comment]
@kisak-valve alllright. Considering that this is the only one that remains in that post, could that issue be updated with my title?

**Comment by kisak-valve** [comment]
I'm going to wait for feedback from others, and if there's no other indicator, then the title will be adjusted when the retest label is removed.

**Comment by Ashetf2** [comment]
Ok, last update fixed bauble colliding with func_lods entities. However, it's still colliding with dynamic props. For example, last point on Badwater Basin and Snowycoast.

**Comment by agrastiOs** [comment]
> Ok, last update fixed bauble colliding with func_lods entities. However, it's still colliding with dynamic props. For example, last point on Badwater Basin and Snowycoast.

That's correct.
