### ISSUE TITLE
[TF2] Smissmas 2021 requests

### ISSUE THREAD

**Issue by Combine900** [ValveSoftware/Source-1-Games#3732]
can we have a "borderless window mode" for tf2.. almost any valve game had it.

fix this plz..
Model '(null)' doesn't have attachment 'backblast' to attach particle system 'rocketbackblast' to.

**Comment by kisak-valve** [comment]
Hello @Combine900, these issues are already being tracked at #2691 and #2555. Closing as a duplicate.
