### ISSUE TITLE
[TF2] Your Eternal Reward no longer fades out killed enemies

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#3733]
Hello, I would like to report a bug:

Your Eternal Reward attribute is currently broken. On backstab, the ragdolls and the cosmetics do not fade out anymore.

Thanks for reading this bug report.

**Comment by agrastiOs** [comment]
Also seems to had been broken on one of the November patches.

**Comment by ZMBanshee** [comment]
Fixed today, thank you Valve.

**Comment by kisak-valve** [comment]
Hello @agrastiOs, per "Fixed Your Eternal Reward ragdolls not fading" in the [2021-12-17](https://www.teamfortress.com/post.php?id=102740) TF2 update, please retest as well.

**Comment by agrastiOs** [comment]
Confirmed to be fixed. Both ragdolls and the cosmetics now fade out.
