### ISSUE TITLE
[TF2] [Bug] Dead Ringer Fake Deaths Do Not Show Spy as Dead on Match HUD

### ISSUE THREAD

**Issue by VirtualSoda** [ValveSoftware/Source-1-Games#3742]
If you "kill" a Spy that had used Dead Ringer, it does not fake that death on the Match HUD; making it really easy to tell that the Spy is using Dead Ringer and had used it when you "killed" the Spy. 

This removes the entire purpose of the Dead Ringer: to fake/mimic death. Hopefully this can get addressed.

**Comment by kisak-valve** [comment]
Hello @VirtualSoda, this reads like #2467. Closing as a duplicate.
