### ISSUE TITLE
[TF2] [Feature Request] Allow both teams to have a kick vote active

### ISSUE THREAD

**Issue by ZMBanshee** [ValveSoftware/Source-1-Games#3746]
Sometimes several bots join at once, and because they often get placed onto both teams, they can wreck havoc on the match before they're kicked in time.

Part of the problem here slowing down the kicking process is that only one team can have a kick vote active. When one team is currently kicking a player, the other team, despite not seeing the vote box, gets a message that there is currently an active vote and that they cannot start one.

If this were changed, we could literally be kicking bots twice as fast as we are now. I don't see any downside to allowing this.

**Comment by kisak-valve** [comment]
Hello @ZMBanshee, closing as implemented with "Both teams can have a kick vote running at the same time" in the [2022-06-21](https://www.teamfortress.com/post.php?id=139819) Team Fortress 2 update.

**Comment by ZMBanshee** [comment]
Perfect, thanks a lot. Great update full of fixes.
