### ISSUE TITLE
[TF2] Flamethrower damage does not ramp up if an enemy is near a wall

### ISSUE THREAD

**Issue by ZMBanshee** [ValveSoftware/Source-1-Games#3764]
The Flamethrower is supposed to ramp up from 6.5 damage to 13 per particle if you are successfully landing consecutive particles/tracking your opponent.

However, if the opponent is near a wall, particles will count as a miss even if all of them are hitting. This causes it to never ramp up beyond 50% damage output in indoor areas, which ironically is where you'd expect Pyro to be more effective.

This is easily reproducible. Just have a bot stand near a wall, and you'll see the damage per tick never increase.

**Comment by kisak-valve** [comment]
Hello @ZMBanshee, this issue is already being tracked at #3720. Closing as a duplicate.
