### ISSUE TITLE
Add High DPI (4K) Menu's and Subtitles to Half Life 2, Episodes & Source SDK 2013

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [ValveSoftware/Source-1-Games#3783]
I'll also report this in the SDK issues. I already made a comment about this on another issue but that may be for HL1 source games - 
https://github.com/ValveSoftware/Source-1-Games/issues/2510

Half Life 2 and episodes as well as Source SDK 2013 mods all scale the in game HUD elements well to 4K (I refer to latest beta versions). The exception is subtitles/messages although that can be fixed by altering the correct ".res" file to show a larger font size. For example see - https://developer.valvesoftware.com/wiki/Modifying_Source_GameUI - I have confirmed by testing it that fonts can in fact be increased in size to be visible on my 4K display. The settings menu does not scale to 4K but could also be fixed although this is a bigger job. It uses VGUI - https://developer.valvesoftware.com/wiki/VGUI_Documentation - There are even "high_def" switches in the resource files to allow different sizes for different displays. I experimented with modding this myself but its quite a big job for someone not familiar with VGUI as an entire menu layout needs adding for 4K (3840x2160). But its obviously possible. So I don't understand why Valve have not updated their games to be fully visible on 4K/High DPI displays. Half Life 2 looks really good in 4K but I suspect most people don't stay with it for very long because the player cannot see Keyboard controls to change or other settings if they try and go into the menu in 4K. It just becomes a massive inconvenience so I usually end up dropping down to 1920x1080. So it would be nice if this classic game were updated for modern displays and new players.

**Comment by kisak-valve** [comment]
Hello @Michael-Z-Freeman, the issue report you've referenced, #2510, is not a closed issue report as indicated in the top left corner of that page.

Closing as a duplicate.

**Comment by Michael-Z-Freeman** [comment]
OK cheers. Missed that for some reason.
