### ISSUE TITLE
[TF2] CTF notifications not appearing in HUD

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#3785]
Currently, the notifications that shows when a player picks up or drops the intelligence (e.g. "Your INTELLIGENCE has been PICKED UP!") are not appearing. Proof: https://youtu.be/dYHzeTG9gII
![image](https://user-images.githubusercontent.com/63692647/148695159-40c9a3c2-9894-48ee-bde0-efede59f7721.png)

**Comment by shiro-2k** [comment]
I was only able to reproduce this by using the cl_hud_minmode command. As you can see, the notification does not appear with cl_hud_minmode set to 1. I am not sure if this is by design or not.

[cl_hud_minmode 0](https://i.imgur.com/BnJ0O7p.png)
[cl_hud_minmode 1](https://i.imgur.com/rTZ90yC.png)

**Comment by Ashetf2** [comment]
Alright, it's not a bug. The command `tf_hud_notification_duration` disables these messages, so i'm closing this.
