### ISSUE TITLE
[HL2] Plasic boxes dissapearance at certain angles of view

### ISSUE THREAD

**Issue by VladimirVSC** [ValveSoftware/Source-1-Games#3787]
The pile of colorful plastic boxes in the area before the bridge (Highway 17 Chapter) vanishes sometimes when looking at it from different positions
![d2_coast_070000](https://user-images.githubusercontent.com/96921167/149179794-36f3ab14-8269-457a-8802-15cb70d6f822.jpg)
![d2_coast_070001](https://user-images.githubusercontent.com/96921167/149179826-24f3289b-38ab-49de-ac8a-8cec113ac956.jpg)
![d2_coast_070003](https://user-images.githubusercontent.com/96921167/149179864-8e591ad7-52e6-4cce-a884-ed23133c6f0c.jpg)
![d2_coast_070004](https://user-images.githubusercontent.com/96921167/149179886-767cb28d-4c9f-4b66-b635-284bfbb7496b.jpg)
.

**Comment by kisak-valve** [comment]
Hello @VladimirVSC, this issue is already being tracked at #609. Closing as a duplicate.
