### ISSUE TITLE
[Portal 1] Numbers in challenge results screen show up as symbols

### ISSUE THREAD

**Issue by catte-go-nya** [ValveSoftware/Source-1-Games#3804]
In the Linux port of Portal 1, the numbers that show how many portals, steps, or seconds you took display as some sort of internal Wingdings-type font the game uses.

Distro: Xubuntu 20.04 LTS
Desktop environment: XFCE 4.14
Window manager: XFWM 4
GPU: EVGA NVIDIA GeForce RTX 2080 Revision A
CPU: AMD Ryzen 7 1800X @ 3.6GHz

![20220119223716_1](https://user-images.githubusercontent.com/98241923/150659830-fd5b8236-1b37-46df-87ff-49455921031f.jpg)
![20220120010955_1](https://user-images.githubusercontent.com/98241923/150659853-c1cfa6cb-5fc3-4241-848c-de2df49da3f4.jpg)

**Comment by kisak-valve** [comment]
Hello @catte-go-nya, we've seen the same font issue before in #3537. Since this adds some additional symptoms, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/3537#issuecomment-1019392037.
