### ISSUE TITLE
All source 1 games crash on gentoo. Missing CFLAGS.

### ISSUE THREAD

**Issue by aTosser** [ValveSoftware/Source-1-Games#3806]
Rip my issue:

Anyway, 
launch > black screen > CTD:

Assuming the minidump uploader works as expected:
CrashID=bp-296f9331-a81a-4662-b82a-bf6f72220125
CrashID=bp-1b39fa73-b9dc-4e91-a2ba-4b6c52220125
CrashID=bp-afc42da6-10de-4a95-8228-ab5612220125
CrashID=bp-7672aea0-0986-465c-9913-6b16d2220125
CrashID=bp-e8854d99-08bb-4f9b-910a-aec5b2220125
CrashID=bp-4f137fc3-7ba3-492c-892f-976262220125
CrashID=bp-f16c05d3-793b-4e57-8387-ffe8b2220125
CrashID=bp-77f347f1-bf91-42dc-b76a-f300a2220125
CrashID=bp-b560f414-e847-4c8e-8ade-959742220125
CrashID=bp-7fa509ec-9544-4067-acfd-399582220125
CrashID=bp-6ac8d41c-09ee-4a28-b41f-7d6d32220125
CrashID=bp-95d1e6bd-377e-493f-a2d4-a45042220125

Sorry, I am not comfortable uploading the *.dmp to github and steam support refers me here every time if the issue is a linux issue.

Operating System: Gentoo Linux
Kernel Version: 5.16.2-gentoo (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2

**Comment by kisak-valve** [comment]
Hello @aTosser, please give #3727 a read and test if that is relevant to your system.

**Comment by aTosser** [comment]
You had me at "I have a Gentoo test box" This IS the issue I am having, -novid fixed it instantly. I will go grumble in my normal IRC places.
