### ISSUE TITLE
[TF2] Console can't be opened from the main menu with binds 

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#3807]
Pressing a binded key to open the console won't work if the user is on the main menu (wether on a server or not).

This does works in CS:GO

**Comment by treacherousfiend** [comment]
I'm fairly certain this is an issue with alt-tabbing, as whenever this happens to me, it is always after I have alt-tabbed, and it is fixed if I alt-tab in and out again.

**Comment by Ashetf2** [comment]
Ok, this is weird, the console DOES open in the main menu. However, using the key "\" doesn't work to open the console. I changed my key to F3 and now works. However, i could manage to make it work when spamming it while opening the Items tab.
