### ISSUE TITLE
[Portal beta] No sound at fullscreen startup

### ISSUE THREAD

**Issue by eikesauer** [ValveSoftware/Source-1-Games#381]
Hello!

Thanks for providing Steam for Linux and Portal 1!

Today I launched Portal for Linux (beta) for the first time. But I got no sound at all. I found the option to disable sound if window is in background. I switched it and sound started. So the game thought my windows was in background - but in fact, it was fullscreen and so it was the only window shown. 

My graphics card is a GeForce 660, I'm using the closed source drivers from NVidia.

Ciao,
  Eike

**Comment by kisak-valve** [comment]
Closing per the last comment.
