### ISSUE TITLE
why valve

### ISSUE THREAD

**Issue by nitro-1** [ValveSoftware/Source-1-Games#3813]
This TLS team is fucking the game l4d2 only stupid updates so far and everytime you make a big update and no beta and not warning and its fucking community who keeping this game alive....you have to understand if you dont know valve the community who is keeping this game alive so you still make money, at least before make a big update and mess up servers inform us, most of the mods no more work and servers most of them are gone and like this you just pushing people away so just keep up and soon you will kill this shit game.and TLS good work guys.

**Comment by kisak-valve** [comment]
This is an inappropriate way to communicate to anyone.
