### ISSUE TITLE
[L4D1] We need a real update

### ISSUE THREAD

**Issue by AshThe9thSurvivor** [ValveSoftware/Source-1-Games#3819]
L4D1 has been receiving small patches that in the end fix things that hardly anyone uses, what's more, hardly anyone knows about, but the most common bugs haven't been fixed to this day, I've filed bugs and requests here that have been ignored, they say out there they don't want to touch the game code for fear of messing it up, if something works why manipulate it; Me and some friends did an unofficial update for L4D1, added new maps, events that don't exist in L4D1, new common infected, model fixes, texture fixes, a new and updated mainmenu, and much, much more, and we didn't mess up the code, what's more, we don't even touch it, and they can't touch it?, it's the dumbest excuse I've ever heard, get down to business and start working, or approve our community update and we'll do your job.

**Comment by kisak-valve** [comment]
Hello @AshThe9thSurvivor, this issue report lacks specific information for a developer to take action upon and it would be more appropriate to post this in the forums. 

Closing as not a actionable bug.

**Comment by AshThe9thSurvivor** [comment]
> Hello @AshThe9thSurvivor, this issue report lacks specific information for a developer to take action upon and it would be more appropriate to post this in the forums.
> 
> Closing as not a actionable bug.

Show me a place where I can make this publication, and don't tell me it's in the game's discussion area, because I've already done it there about 3 times and they don't even review it.
