### ISSUE TITLE
Portal (beta) Linux. Game crash soon after loading.

### ISSUE THREAD

**Issue by T2-Archimedes-Stench** [ValveSoftware/Source-1-Games#382]
The Game crashes to desktop within 30-60 seconds of starting to run the game with no error message.

My specs are as follows.

Ubuntu 12.04LTS (fully updated)
GTX560 using Nvidia 310 drivers.
AMD 2,8ghz Dualcore.
4gb RAM.

**Comment by kisak-valve** [comment]
If anyone is still experiencing this issue with an up to date system, please open a new issue report.
