### ISSUE TITLE
HL2 beta: Immediate crash when passing -vulkan or -gamepadui flags

### ISSUE THREAD

**Issue by caseif** [ValveSoftware/Source-1-Games#3837]
This applies to both the base game and the episodes and seems to correspond to the changes pushed in the last day or two. Passing either the `-vulkan` or `-gamepadui` flag (or both) cause the game to crash almost immediately after launching, displaying only a black screen for moment and not reaching the Valve logo.

This is notably distinct from the issue affecting the episodes (and previously the base game as well) in which the game would crash while attempting to load the new UI; that crash only occurs after arriving at the main menu.

I also tested L4D2 and Portal 2 just for fun with the `-vulkan` flag and both were able to successfully launch to the main menu.

**Linux distro:** Arch
**Desktop environment:** Plasma 5.24.1 on KWin
**Graphics card:** Radeon 6700 XT
**Mesa version:** 21.3.6

Let me know if there's any other information that would be useful or if I can provide any further help with narrowing down the issue (e.g. testing different hardware/software configurations).

**Comment by ItsNeverLight** [comment]
same

**Comment by SoMuch1488** [comment]
I'm having the same issue. Everything worked before.

**OS**: Windows 11
**GPU**: NVIDIA GeForce GTX 650
**CPU**: AMD Ryzen 7 3700X

**Comment by SoMuch1488** [comment]
Is it working on your side? Mine HL still crashes.

**Comment by Headofacrab** [comment]
i found launch option for hl1 idk if it works hl2 with vulkan https://www.youtube.com/watch?v=qkM5FYzdAJ0
launch -nofbo
