### ISSUE TITLE
[cs:s]Cannot change the clan tag

### ISSUE THREAD

**Issue by leopoldfitzgithub** [ValveSoftware/Source-1-Games#3840]
when i change the clan tag, and i click the apply, it goes to none again.
![屏幕截图 2022-02-16 122931](https://user-images.githubusercontent.com/39212482/154841125-300fb8d9-51e8-4af9-bc96-221112a200f1.png)
![屏幕截图 2022-02-16 122951](https://user-images.githubusercontent.com/39212482/154841127-3eaddd3b-7be3-4a3d-ab1e-083dd3d9ae10.png)

**Comment by kisak-valve** [comment]
Hello @leopoldfitzgithub, this issue is already being tracked at #2853. Closing as a duplicate.
