### ISSUE TITLE
Need Help with HL2

### ISSUE THREAD

**Issue by Geegy115424** [ValveSoftware/Source-1-Games#3860]
![steam-half-life-2](https://user-images.githubusercontent.com/100605305/156018587-87714297-62f8-453a-a3c4-1f51beeab834.jpg)

Hello, Steam helper send me here, hope you can help.

I just install the update.

This is happen since last 2 update.

What can I do to fix?

Thank you very much.

**Comment by kisak-valve** [comment]
Hello @Geegy115424, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

This may be the issue resolved by `- Fixed corrupted models on OSX` in the [2022-02-28](https://store.steampowered.com/news/app/220/view/3119310025785817142) Half-Life 2 update.

**Comment by Geegy115424** [comment]
Thank you. I think the game is fix now.
