### ISSUE TITLE
It says i beat 2/2 advanced maps yet it is still lock

### ISSUE THREAD

**Issue by MFWhen** [ValveSoftware/Source-1-Games#3873]
![20220315151952_1](https://user-images.githubusercontent.com/101800309/158784700-e2326d74-4649-48d6-aab5-669879181d56.jpg)
and after beating four advanced maps it gave me the fruitcake achievement yet no cupcake achievement
![image](https://user-images.githubusercontent.com/101800309/158784964-6e5ca12b-4e41-45d7-8c7f-a10ddf0d0f56.png)

**Comment by kisak-valve** [comment]
Hello @MFWhen, this issue is already being tracked at #981. Closing in favor of the older issue report.
