### ISSUE TITLE
No More Room In Hell:  Lockup connecting to any server or creating one.

### ISSUE THREAD

**Issue by Git-Forked** [ValveSoftware/Source-1-Games#3878]
steam.sh[31472]: Running Steam on manjarolinux 21.2.5 64-bit
steam.sh[31472]: STEAM_RUNTIME is enabled automatically
setup.sh[31546]: Steam runtime environment up-to-date!
steam.sh[31472]: Steam client's requirements are satisfied

For the last three days, every time I try to play NMRIH it locks up trying to connect to any server (and I've tried many) and also locks up trying to even create my own server.  All of this worked fine prior to a few days ago.  Using Manjaro with all the latest Steam updates installed.

**Comment by Git-Forked** [comment]
How, when their forum page has been shutdown?

**Comment by Yetoo1** [comment]
@Git-Forked You could ask on their discord (link is where the forum page is unavailable and/or on the steam community.
