### ISSUE TITLE
[Portal] Lags on loading sounds during gameplay

### ISSUE THREAD

**Issue by mattyy1hp** [ValveSoftware/Source-1-Games#388]
I have a lags everytime the game is loading sounds, textures etc.
It's very similar to this: http://bugs.winehq.org/show_bug.cgi?id=27453 ( but this is a WINE report - this report has nothing to do with the native Linux version, I'm just having something very similar ).

I've tried several levels/chapters, it's always the same.

---

AMD Catalyst 13.3 Beta3
Gnome Shell

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Mutter
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6520G

```
Driver Version:  4.2.12173 Compatibility Profile Context 12.10.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6760
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3430 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  581188 Mb
    Largest Free Hard Disk Block:  153408 Mb

Installed software:

Recent Failure Reports:
    Fri May  3 11:20:46 2013 GMT: file ''/tmp/dumps/assert_20130503132034_1.dmp'', upload yes: ''CrashID=bp-02b7ed5a-8038-4b1e-a94b-9548b2130503''

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. This kind of render stalling is expected with OpenGL video drivers that do not support an on-disk shader cache.
