### ISSUE TITLE
[TF2] Segfault on launch

### ISSUE THREAD

**Issue by ldaws011** [ValveSoftware/Source-1-Games#3885]
TF2 crashes immediately on launch - citing a segfault. I believe this only started occurring after I updated glibc but I can't confirm this

dmesg prints
`traps: hl2_linux[2858] general protection fault ip:f7d39042 sp:ffcb8fcc error:0 in libc.so.6[f7c58000+170000]`
upon crashing. See link below for system information, Steam output and given dump file

https://gist.github.com/ldaws011/72a0fc11a6ed0202967678506152643f
[dumpzip.zip](https://github.com/ValveSoftware/Source-1-Games/files/8428957/dumpzip.zip)

**Comment by RayOfLight1** [comment]
Today I've encoutered the same problem.

I've solved it by recompiling glibc with "-mstackrealign" CFLAG :)

**Comment by ldaws011** [comment]
> Today I've encoutered the same problem.
> I've solved it by recompiling glibc with "-mstackrealign" CFLAG :)

This fixed the issue for me too
May I ask how you came about finding this solution??

**Comment by RayOfLight1** [comment]
Easy :) (No)

I found this bug on google, and I also found via google this about my OS: [Gentoo wiki](https://wiki.gentoo.org/wiki/Steam/Games_troubleshooting#Half-Life_2)

**Comment by scandalouss** [comment]
> Today I've encoutered the same problem.
> 
> I've solved it by recompiling glibc with "-mstackrealign" CFLAG :)

This solved it for me!

**Comment by BluCobalt** [comment]
I had the same `[61611.831003] traps: hl2_linux[27627] general protection fault ip:f7dfe3d6 sp:fff0668c error:0 in libc.so.6[f7d1b000+174000]` in dmesg and adding "sys-libs/glibc -mstackrealign" to my package.use fixed the crash

**Comment by Boszacta-Emil** [comment]
This fixed the issue for me. how should I enforce this next time I update glibc, all-ah package.use?

**Comment by BluCobalt** [comment]
Yeah, I just added it to package.use/glibc

**Comment by Boszacta-Emil** [comment]
an injection of `sys-libs/glibc CFLAGS="-wstackrealign" ` in `/etc/portage/package.use/glibc` Prefix or suffix, and as a raw use flag fails to supply it:

` *          CFLAGS:   -march=native -pipe -O2`

I can just inject it into CFLAGS in make.conf, but this isn't a good idea.

**Comment by BluCobalt** [comment]
It's -mstackrealign, not -wstackrealign

**Comment by kisak-valve** [comment]
Hello, https://github.com/ValveSoftware/Source-1-Games/issues/3727#issuecomment-978001491 is an alternative system config to do the same thing.

**Comment by Boszacta-Emil** [comment]
> Try `-mstackrealign` instead of `-wstackrealign`

sorry, I typed that into GitHub, I hadn't made that mistake in the injection.

**Comment by thesamesam** [comment]
FWIW, Gentoo users can now set USE=stack-realign on sys-libs/glibc if they wish to achieve the same goal.

**Comment by Tiagoquix** [comment]
OP, can you retest with the new 64-bit binaries + Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
