### ISSUE TITLE
[TF2][Feature Request] Make the Flamethrower's Flames Less Bright/Cluttered

### ISSUE THREAD

**Issue by VirtualSoda** [ValveSoftware/Source-1-Games#3895]
It is hard to see the Pyro behind the cluttered and bright flames. This makes him hard to shoot because you can not see him.

Secondly, it is also hard for the Pyro to see anything behind the flames. Making it harder to track targets. This is counter-intuitive  considering that you need to track enemies with your flamethrower to get maximum damage output. On top of this, it becomes harder to see incoming projectiles.

**Comment by kisak-valve** [comment]
Hello @VirtualSoda, this issue is already being tracked at #2424. Closing in favor of the older issue report.
