### ISSUE TITLE
[L4D2] Weapon HUD causes stutter

### ISSUE THREAD

**Issue by Nihille** [ValveSoftware/Source-1-Games#3899]
Description:
The weapon HUD in Left 4 Dead 2 causes a stutter every few seconds. Here is a video example:
https://www.youtube.com/watch?v=Do0lKwupXHs

I have tried re-installing the game, removing mods, changing video settings, and unsubscribing from all workshop content to no avail.

The stutter only stops when "hidehud 1" is used in the console, hiding the weapon HUD as shown in the video. After using "hidehud 0" to show the weapon HUD again, the stutter came back.

This issue does not seem to affect many people, and I have only found one discussion topic in the Steam Discussions regarding this issue. If anyone can help look into this matter, it would be greatly appreciated.

[System Information](https://gist.github.com/Nihille/b4ffcc8d188e0a1dc08c09d0056bb7ae)

**Comment by s10055072** [comment]
Addition note:
I didn't have this issue until the last Steam client update, maybe it has something to do with Steam Client?

**Comment by Nihille** [comment]
> Addition note: I didn't have this issue until the last Steam client update, maybe it has something to do with Steam Client?

Yeap seems like the latest Steam Client update borked it, whereas previously it was only a Steam Beta Participation issue.

**Comment by vlad54rus** [comment]
Do you guys still have lag issue? I had it after said beta Steam update went live on May 13, but May 14 another update happened that seem to have it resolved.

**Comment by s10055072** [comment]
The issues have been resolved a few days after I made the comment, likely also some new Steam client update.

I can personally say this issue have being resolved.

**Comment by Nihille** [comment]
Can confirm, issue was fixed.
