### ISSUE TITLE
[TF2] [URGENT] [Trading Vulnerability] - Keys can be used to unbox for a brief period after being traded away

### ISSUE THREAD

**Issue by AzureAzel** [ValveSoftware/Source-1-Games#3910]
Mann Co. Supply Crate Keys are used as the main currency for trading. A vulnerability was discovered earlier today that allows bad actors to use a key on a crate to unbox it immediately after receiving items from a trade that includes the key being used. This will remove the key from the other player's inventory.

Needless to say, this is bad.

**Comment by Yetoo1** [comment]
Can you give more details on who reported this?

**Comment by AzureAzel** [comment]
> Can you give more details on who reported this?

I'm unsure of who first reported this where, but this is where I first saw it: [https://forums.backpack.tf/topic/80628-urgent-trading-not-currently-safe/](https://forums.backpack.tf/topic/80628-urgent-trading-not-currently-safe/)
This needs to get to as many places as possible so it can be patched swiftly.

**Comment by jh34ghu43gu** [comment]
https://www.youtube.com/watch?v=PZURR5UeZE4
Video example since it's a pain to replicate.

**Comment by AzureAzel** [comment]
The issue hasn't occurred since. Whatever caused this to happen is gone. However, this still could be a problem in the future if Steam simply having high enough traffic is what caused this. Closing for now.
