### ISSUE TITLE
[HL2:EP2] Barn Advisor sound effects not being triggered

### ISSUE THREAD

**Issue by EddsNotDedd** [ValveSoftware/Source-1-Games#3921]
This is an error in the level `ep2_outland_07`. The error has been present since at least October 2013, meaning that it was probably broken by ~~SteamPipe~~ actually Source 2013.

There is a cutscene in this map with a Combine Advisor inside of a barn. The cutscene with this advisor has lots of sound effects, presumably activated by choreo or I/O logic. In the current version of the game, however, a number of these, such as Gordon's ears ringing, the Advisor making a vocalization after poking the rebel with it's tongue, or sounds that go with the Rebel corpse spraying blood and crumpling, are missing.

Most obviously, the second half of the loud noise of the barn ripping apart is _entirely gone_, with only the first half playing. As a whole, these errors leave the cutscene feeling unfinished and harm the end user's experience.

As evidence, I have these three videos below; the first two were posted by other parties and the third was recorded and uploaded by myself.

Video 1 is only a few months after the release of the game, in January 2008, with the scene working as intended.
Video 2 was posted in 2013, and shows the bug.
Video 3, my own footage, shows the same bug as I have recorded it today, within the current Steam build of Episode Two.

[2008 footage, without bug.](https://youtu.be/SJR96XPU6G4?t=109)

[2013 footage, with bug.](https://youtu.be/0YUA92dTW8M?t=734)

[My own video.](https://www.youtube.com/watch?v=NjKNQSK2Tik)

**Comment by EddsNotDedd** [comment]
As it turns out--the bug is indeed caused by Source 2013, and has been known for a while as cited by #1003.

**Comment by kisak-valve** [comment]
Hello @EddsNotDedd, let's continue tracking this issue in the older issue report. Closing in favor of #1003.
