### ISSUE TITLE
[DOD:S] 4k UHD: font to small in main menu

### ISSUE THREAD

**Issue by Speciesx** [ValveSoftware/Source-1-Games#3922]
This is how it looks like on a 27" screen with 3840x2160 aka. 4k UHD resolution.

PS: console font size was changed by me.

![hl2_2022_06_12_14_37_04_507](https://user-images.githubusercontent.com/1196375/173233942-d463eef9-ef0a-44e5-b287-257d9583c3ee.png)
![hl2_2022_06_12_14_37_26_459](https://user-images.githubusercontent.com/1196375/173233943-2a0fce27-b076-4f8d-9c8c-60e656d48d49.png)
![hl2_2022_06_12_14_38_15_476](https://user-images.githubusercontent.com/1196375/173233944-7b0b31c0-d8f8-49e5-aa58-af4aa67f1c8e.png)

**Comment by kisak-valve** [comment]
Hello @Speciesx, this issue is already being tracked at #2510. Closing as a duplicate.
