### ISSUE TITLE
[TF2] Feature Request: 'item_open_holiday_crate.wav' for Winter Holiday Case opening sequence

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#3932]
I was wondering if there was any chance that the game could be updated to utilize the unused 'ui/item_open_holiday_crate.wav' sound when opening Winter Cases. The game already seems to have cases for different crate types (i.e. RoboCrate), so this code can be expanded to accommodate the new scenario.

This could be implemented by adding a new 'CrateType' value for cases with Winter in their schema name:
_if ( V_strstr( pCrate->GetItemDefinition()->GetDefinitionName(), "Winter" ) )_

Video was taken from a (mostly) vanilla client. The only major change here was swapping the current case open sound with the (unaltered) 'ui/item_open_holiday_crate.wav' sound via soundmod:
https://user-images.githubusercontent.com/108029512/175143027-bfc2819d-0fcc-4ad2-bdd3-28f1f39eb3c7.mp4

**Comment by agrastiOs** [comment]
Implemented in the latest patch.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
