### ISSUE TITLE
[TF2] Players cannot cast votes they've initiated via keyboard

### ISSUE THREAD

**Issue by nosoop** [ValveSoftware/Source-1-Games#3934]
Regression introduced in 2022-06-22 update.

On an unmodified server, players cannot use F1-F5 on issues they've created if `sv_vote_holder_may_vote_no` is set.  (If the ConVar is unset, the automatic vote cast by the player is applied.)

Players can still cast votes by manually invoking `vote <vote_index> <option>` in the client console, and they are ~~reportedly~~ able to vote via keyboard on issues that the server or other players have initiated.

This causes issues with server plugins that provide custom voting options.

**Comment by Joshua-Ashton** [comment]
Thanks for reporting! This should be fixed in the next update :smile:

**Comment by agrastiOs** [comment]
@nosoop Fixed per latest update.

**Comment by nosoop** [comment]
Confirmed that the fix that was rolled out today resolves this if `sv_vote_holder_may_vote_no` is set.  Kind of an awkward constraint to need that enabled for NativeVotes, but it'll do.

Thanks for the fix!
