### ISSUE TITLE
[TF2] Feature Request: Rename 'Misc Items' to 'Cosmetics' in Mann Co Catalog

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#3940]
Hi!

I was wondering if there was any chance that the 'Misc Items' category could be renamed to 'Cosmetics' to more accurately fit the change from the 6/21/22 patch:
![image](https://user-images.githubusercontent.com/108029512/175366691-4de9a268-a02b-4bfa-8d53-a4c3f98397df.png)
![image](https://user-images.githubusercontent.com/108029512/175366730-ce54a46e-8ea6-4738-aead-02f81f0ab947.png)

**Comment by Ashetf2** [comment]
Fixed in the August 11 Patch.
![image](https://user-images.githubusercontent.com/63692647/184282305-0888c2a0-d204-4b64-9cc1-36f2bff10ce8.png)

**Comment by rabscootle** [comment]
Closing!
