### ISSUE TITLE
[TF2] Party chat disappears when closing and opening again in certain resolutions

### ISSUE THREAD

**Issue by Procustes** [ValveSoftware/Source-1-Games#3949]
Since a long time, closing and opening Party Chat in certain resolutions, it just disappears (until you change to another resolution).

![PartyChat](https://user-images.githubusercontent.com/45585078/175446068-1cf3769d-b4cf-4193-a692-9f3083904cec.gif)

Broken tested resolutions:

- 1152 x 872 (4:3)
- 1600 x 900 (16:9)
- 1440 x 900 (16:10)

**Comment by kisak-valve** [comment]
Hello @Procustes, this issue is already being tracked at #3774. Closing as a duplicate.
