### ISSUE TITLE
[TF2] Support `embed.nav`-style files for other map-unique files

### ISSUE THREAD

**Issue by nosoop** [ValveSoftware/Source-1-Games#3954]
This is a feature request related, but somewhat separate to, #2701.

For convenience to map authors, I'm aware of the following files that should be looked up within the BSP if they exist:

- `${mapname}_level_sounds.txt`
- `soundscapes_${mapname}.txt`

There are possibly others that I'm not aware of, and others whose names I'm not aware of [here](https://github.com/ValveSoftware/Source-1-Games/issues/2701#issuecomment-610897133).

There should be documented, embedded variations of each and / or an additional lookup for the display version of `${mapname}` (without the `workshop/` prefix and `.ugc${ugcid}` suffix).

**Comment by nosoop** [comment]
Might be addressed in [today's update](https://www.teamfortress.com/post.php?id=144345); will recheck and close once confirmed.

> - Added support for custom sounds, soundscripts, soundscapes, navmeshes and particles in workshop maps

**Comment by nosoop** [comment]
Today's update introduces a `GetCleanMapName` function to load the custom assets listed in the changes, which should allow existing maps to just work even if they're on the Workshop.
It's not exactly the `embed.nav` support I was interested in (which would help with renamed maps), but since the end result is practically the same, I'll go ahead and close this.

**Comment by FlaminSarge** [comment]
I'd argue this is still useful to support.
