### ISSUE TITLE
[TF2] Feature Request: Remove development-only flag from r_ropes_holiday_lights_allowed

### ISSUE THREAD

**Issue by osyu** [ValveSoftware/Source-1-Games#3955]
The client ConVar r_ropes_holiday_lights_allowed toggles festive lights being rendered on ropes during the winter holiday; however, it's flagged development-only so clients can't change it from the default value 1. There doesn't seem to be any good reason for this, and another command related to holiday lights (r_ropes_holiday_light_color) is already non-devonly, so it'd be nice if that flag could be removed.

**Comment by kisak-valve** [comment]
Hello @osyu, there doesn't seem to be any practical value in this feature request.

If a ConVar is doing no benefit or harm, then it doesn't matter if it exists or not and it isn't worth having a Team Fortress 2 dev spend time looking into this.

**Comment by osyu** [comment]
As it turns out this request is already tracked under #3029, so I'll just mention this convar there.
