### ISSUE TITLE
[TF2] official server timeout

### ISSUE THREAD

**Issue by Slashury** [ValveSoftware/Source-1-Games#3956]
Hi! Recently I found a very gamebreaking bug, which causes an official team fortress 2 server to timeout, and drop players out. With some  players around 6-7~ using Huo-Long Heater and shooting the ground, it causes the server to timeout, it was tested in plr_hightower, based on their profiles and behaivours they might be bots, and they tried to crash servers, it was done with the latest update on 2022/06/24
![unknown](https://user-images.githubusercontent.com/98124197/175645647-e7a32b37-ea50-457d-81de-f4ec565ebaec.png)

**Comment by kisak-valve** [comment]
Closing per the last comment.
