### ISSUE TITLE
[TF2] Mann Vs. Machine loading screen does not appear when joining game via Matchmaking

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#3963]
The loading screen made specifically for Mann Vs. Machine mode does not appear when a user connects to a game through official matchmaking (Mann Up, Boot Camp). This is probably an oversight in the code that handles swapping between the default load screen and the one used for Competitive mode.

Loading screen user sees when joining through matchmaking:
![image](https://user-images.githubusercontent.com/108029512/175748621-d4880745-034d-4318-9b70-28eb615291fd.png)

Loading screen user sees when joining through any other means:
![image](https://user-images.githubusercontent.com/108029512/175728249-732c8f1d-f1ae-4398-bc94-2420f6d56beb.png)

**Comment by kisak-valve** [comment]
Hello, per "Fixed the loading screen backgrounds on Valve servers" in the [2022-07-07](https://www.teamfortress.com/post.php?id=140004) Team Fortress 2 update, please retest this issue.

**Comment by rabscootle** [comment]
Can confirm it's been fixed, thanks!
![hl2_qQdsP0b7by](https://user-images.githubusercontent.com/108029512/178095094-c1863803-0324-43df-a654-ec30994f80a3.png)
