### ISSUE TITLE
[TF2] mvm_rottenburg barricade entity frequently fails to appear (+ repro steps)

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#3966]
REPRO STEPS
----------------------------------------------------
1. Load into mvm_rottenburg and begin a wave with tanks ("tf_mvm_jump_to_wave" can be used)
2. After tank has destroyed barrier, reload map ("map mvm_rottenburg")
Repro video: https://www.youtube.com/watch?v=ybvyD-z8CRk
----------------------------------------------------
The barricade entity in mvm_rottenburg has an issue where the barricade's model can be invisible for the entirety of the match. The collisions and other logic continue to function like normal, however, which can confusion for players.

![hl2_BnpfjkOCiE](https://user-images.githubusercontent.com/108029512/175784289-981b04e5-66ff-4e90-a738-5f2f3da23475.jpg)

![hl2_QzliGuL2gO](https://user-images.githubusercontent.com/108029512/175784292-b08e8eb1-068c-427e-9777-d213e981580b.png)

**Comment by kisak-valve** [comment]
Hello @rabscootle, this issue is already being tracked at #3699. Closing as a duplicate.
