### ISSUE TITLE
[TF2] net_disconnect_reason is 0 by default.

### ISSUE THREAD

**Issue by minesettimi** [ValveSoftware/Source-1-Games#3971]
Even though the disconnect reason has been re-enabled the convar net_disconnect_reason is defaulted to 0 making players still see _"Disconnect: Client Disconnect."_. Players wont mess with the convar as its not something to directly benefit them. This makes it unreliable for server owners to provide a necessary kick message for example a warning or ban message specifying what the player did wrong gets through to the player. Getting this message through can prevent misunderstandings about why exactly the player got kicked/banned and also inform what the player did so they will know that they shouldn't repeat the same action. I'm requesting the convar should default to 1 so that players who haven't purposely disabled it should get the disconnect reason.

**Comment by AzureAzel** [comment]
I fully agree with this sentiment, however, I believe the convar should stay the same specifically for Valve matchmaking servers only, as the main intention for the rehaul of this system was to stop bad actors from spoofing disconnect messages to say offensive stuff.

**Comment by minesettimi** [comment]
I didn't know that this convar also affected the messages you see in chat whenever _someone else_ gets kicked I wrote this under the impression that it was only about the popup box you see when _you_ get kicked. The only reasonable way I can see this working out for both community and valve matchmaking is to have the popup box and the chat message separated.

**Comment by kisak-valve** [comment]
Hello, per "Fixed net_disconnect_reason affecting disconnect messages on the client" in the [2022-07-07](https://www.teamfortress.com/post.php?id=140004) Team Fortress 2 update, please retest this issue.

**Comment by minesettimi** [comment]
just checked kicked reason now shows even when the client has net_disconnect_reason to 0. it is fixed
