### ISSUE TITLE
[TF2] Killcam "weapon info" element placement issues

### ISSUE THREAD

**Issue by NonhumanFromSteam** [ValveSoftware/Source-1-Games#3977]
### The weapon info element's placement is very inconsitent.

**Here it appears under the killer name, a lot of info can't be read:**
![image](https://user-images.githubusercontent.com/25296372/175955958-f92437ae-b19f-41a3-b46b-4d7b9c22466f.png)

**Here it appears on top the killer name, info is visible but killer name is blocked:**
![image](https://user-images.githubusercontent.com/25296372/175955997-9d578602-7d25-48ef-bdd8-63fd974c91de.png)

### I thought it might be related to weapons with too much info on them, but it happens a lot with short info weapons too:
**On top of the killer name:**
![image](https://user-images.githubusercontent.com/25296372/175956688-3c34594c-f6d7-4a93-8ab0-9170e9580429.png)
![image](https://user-images.githubusercontent.com/25296372/175960524-78862446-c124-4a2f-8e11-4c82db8bc20b.png)

**Under the killer name:**
![image](https://user-images.githubusercontent.com/25296372/175956838-19cd8e7f-2c64-442b-9963-b23480bdae0c.png)
![image](https://user-images.githubusercontent.com/25296372/175957458-eee6165c-f577-42b1-a375-08933804362e.png)

**And sometimes it is placed somewhat on the right spot, odd:**
![image](https://user-images.githubusercontent.com/25296372/175960937-0aea3be4-b56d-4f50-b43d-b9588d649231.png)
![image](https://user-images.githubusercontent.com/25296372/175959821-f2cd6b64-208b-43a1-a24a-8ef5d32fdafb.png)

**Comment by ajsignoret** [comment]
Adding onto this,

Whatever code handles the in-game screenshots (when you press f12 by default) also seems to be repositioning the boxes in the proper places. Not sure if it can be looked at for a fix.

![E3403A31-BA59-40A3-B189-73AB8389D57E](https://user-images.githubusercontent.com/58406587/175976264-88b11211-6556-4c1b-a1a6-2e58dca4f532.png)
![0638F837-0BD0-4921-A644-AC5A0A33FFA9](https://user-images.githubusercontent.com/58406587/175976272-ad1857c8-bee4-4ce8-99ac-18ce61f246ee.png)

**Comment by kisak-valve** [comment]
Hello @NonhumanFromSteam, this issue is already being tracked at #2785. Closing as a duplicate.
