### ISSUE TITLE
[TF2] Buying projectile penetration in MvM and being ubered breaks arrow type projectiles

### ISSUE THREAD

**Issue by amagnemite** [ValveSoftware/Source-1-Games#3984]
Buying projectile penetration on an arrow type projectile weapon (Huntsman, Crusader's Crossbow, Rescue Ranger, their reskins) works fine in most situations (projectile is fired, pierces enemies, etc). However, when a player is ubered, the projectile stops working, possibly breaking on the player. Once the uber ends, the projectile is fired normally again.

In the attached clip, I've bought projectile penetration. When not ubered, projectiles are fired as expected. When I use an uber can, the projectile stops functioning.
https://user-images.githubusercontent.com/41340875/176382119-608051aa-6c51-40ec-b84d-04b56c702d29.mp4

**Comment by hkva** [comment]
Here's a video illustrating how penetrating huntsman arrows will collide with the local player if the player has `TF_COND_INVULNERABLE`:

https://user-images.githubusercontent.com/91440203/207964367-2a6a45b9-c8c3-4fcc-bef0-2553141c8a99.mp4

**Comment by Whurrhurr** [comment]
fixed from today's update.

**Comment by kisak-valve** [comment]
Closing per "Fixed arrows instantly breaking when being fired by an invulnerable player with the projectile penetration upgrade in Mann vs. Machine (community fix from Marxvee)" in the [2024-08-13](https://www.teamfortress.com/post.php?id=227323) Team Fortress 2 update.
