### ISSUE TITLE
[TF2] [Hammer] func_respawnroomvisualizer shrunks 0.5 HU when compiling the map

### ISSUE THREAD

**Issue by Ashe-tf** [ValveSoftware/Source-1-Games#4003]
![image](https://user-images.githubusercontent.com/63692647/177345013-c882e128-c03d-4f1e-b2f9-1e939a919dda.png)
![image](https://user-images.githubusercontent.com/63692647/177345052-5c1d5383-6a52-40ce-91d3-1502997cdbd2.png)

**Comment by Pinsplash** [comment]
They don't move, brush entities have their collisions shrunk by half a unit on all sides. I know this is intentional because I remember seeing the comment block that explained it, but I don't remember where.
