### ISSUE TITLE
[TF2] Jiggleboned items in the War Paint viewer are broken

### ISSUE THREAD

**Issue by renimg** [ValveSoftware/Source-1-Games#4010]
The patch that fixed jigglebones in the loadout and item previews seems to have broken jiggleboned items in the War Paint viewer.
Breaks on both custom and default HUDs.
![440_20220707224307_1](https://user-images.githubusercontent.com/48497753/177925896-0e1e3d59-6a74-442b-9419-9301c06fc5d2.png)
![440_20220707224926_1](https://user-images.githubusercontent.com/48497753/177925915-e8131522-8037-4a91-b43b-c1f20535e74e.png)

**Comment by rabscootle** [comment]
This may be ready to retest as per "Fixed jiggle bones on the inspect screen" in the [July 8, 2022 patch](https://www.teamfortress.com/post.php?id=140398)

**Comment by renimg** [comment]
As of jule 8, 2022 this has indeed been fixed!

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.
