### ISSUE TITLE
[TF2] Payload rollback zones do not function

### ISSUE THREAD

**Issue by nosoop** [ValveSoftware/Source-1-Games#4011]
Regression introduced in the 2022-07-07 update.

The change that moved `path_track` to server-only entities no longer causes payload carts to roll back immediately in certain areas when no attacker is pushing it.

This can be easily observed on the rollback zones before the first / third captures on `pl_barnblitz`, or the second stage of `plr_nightfall`.

**Comment by ldesgoui** [comment]
It appears the update from July 8th fixed this

> Fixed payload cart not rolling back
