### ISSUE TITLE
[Feature Request] [All games] Unlock mat_picmip to allow values lower than -1

### ISSUE THREAD

**Issue by chipsnapper** [ValveSoftware/Source-1-Games#4017]
As of the 7/7/22 TF2 update, the console command mat_picmip has been unclamped, allowing values lower than -1.
This command controls texture quality, and setting it lower than -1 (The 'Very High' option in graphics settings) makes a big difference for prop models.
![image](https://user-images.githubusercontent.com/3721368/178077363-c13e87e6-8db3-4e31-9fab-27f38b4eb46b.png)
Would it be possible to unclamp this in all other Source games? It was originally clamped in 2010 for causing performance issues on Macs, but Macs haven't been able to run Source games for years now.

**Comment by kisak-valve** [comment]
Hello @chipsnapper, this request is already being tracked at #699. Closing as a duplicate.
