### ISSUE TITLE
[TF2] Gunslinger punch combo isn't lag compensated. (Bug)

### ISSUE THREAD

**Issue by Marxvee** [ValveSoftware/Source-1-Games#4023]
The Gunslinger's 3-hit combo is not compensated for lag when registering for consecutive successful hits. The player can successfully hit their target on their end and damage will be dealt, but the server will think the player missed and break their combo due to the combo chain code only searching for the target's non-lag compensated hitbox for registering combo hits. The inverse can also happen where the player misses on their client but the server thinks the player hit the target, continuing the player's combo instead of breaking it. This behavior currently makes it incredibly difficult to do the critical hit finisher attack on anyone not standing still, especially on high latency or interpolation.

Here's an example video demonstrating this behavior, showing that the combo does not work as intended when hitting the victim 3 times in a row, and then punching the air in front of the victim to make the server think the player is making successful consecutive hits on the victim to execute critical hit finishers despite not actually landing a single hit beforehand: https://www.youtube.com/watch?v=jM0C-Hyq2Es

**Comment by Marxvee** [comment]
Here's a follow-up to this post suggesting what could potentially be done to fix this bug:
In **game/shared/tf/tf_weapon_wrench.cpp**, first add `#include "ilagcompensationmanager.h"` under the server-specific includes. Then in the function `void CTFRobotArm::Smack( void )`, add
```
#if !defined (CLIENT_DLL)
	lagcompensation->StartLagCompensation( pPlayer, pPlayer->GetCurrentCommand() );
#endif
``` 
before the swing trace, and then 
```
#if !defined (CLIENT_DLL)	
	lagcompensation->FinishLagCompensation( pPlayer );
#endif
``` 
after the swing trace.

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed Gunslinger punch combo not being lag compensated (community fix from Marxvee) 

This needs to be retested.

**Comment by kisak-valve** [comment]
Closing per the last comment.
