### ISSUE TITLE
[TF2] [BUG] gas-passer/vaccinator condition does not work if applied via trigger_add_tf_player_condition

### ISSUE THREAD

**Issue by zythetf2** [ValveSoftware/Source-1-Games#4045]
If the gas passer condition (123) is applied to a player via a trigger_add_tf_player_condition, they get doused in gas as intended, however if shot by another player they do not ignite whatsoever.

My guess as to why this happens is as follows:
when the trigger adds the condition it omits a "provider" which is where the condition comes from, but then the ignition only applies if the provider is a player. given that the condition is being applied via a trigger, it causes the player to be doused but not ignited if shot.

the vaccinator resistances share the same issue, because the damage reduction needs to check "medigun bullet resist deployed" on whoever is providing the condition, in this case it would be a medic, i bring this up because i don't know what the gas passer needs to check in order to apply its effect. this issue might occur with more conditions than just these two but these are the only ones i encountered so far

reason i'm submitting this report is because i'm trying to use these conditions in maps. as it stands now they are applied but have no effect, in turn limiting what i can do. i hope a solution can be found, have a good day.

**Comment by Ashetf2** [comment]
I think the Gas Passer cond was fixed in the Sep 29 Patch.

**Comment by zythetf2** [comment]
> I think the Gas Passer cond was fixed in the Sep 26 Patch.

yes it was. i sent an email to EricS a few months ago but nothing happened so i decided to make another thread here, then he sent me a response later, the only thing missing is the vac condition not working, but i didnt include the vac in my original email to eric.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.

**Comment by Ashetf2** [comment]
@zythetf2 you may open another issue specifying only the Vaccinator cond problem

**Comment by Ashetf2** [comment]
Indeed, vaccinator conds were not fixed

TF_COND_MEDIGUN_UBER_BLAST_RESIST

https://user-images.githubusercontent.com/63692647/201364314-24b7435a-cd9b-4ac4-9f31-a1b7f45bc9ed.mp4

TF_COND_MEDIGUN_SMALL_BULLET_RESIST

https://user-images.githubusercontent.com/63692647/201364320-f14d8b63-3668-465e-85d0-3f8151fa312b.mp4
