### ISSUE TITLE
Left4 Dead 2 dont want steam os 3.2

### ISSUE THREAD

**Issue by ptibedo** [ValveSoftware/Source-1-Games#4050]
Hello ! I tried much time to start Left 4 dead 2 but he dont work.
I am to SteamOS 3.2 I installed to my pc desktop.

**Comment by Munoida** [comment]
Try opening Left 4 Dead 2 through the terminal, there are various ways but the easiest is to just write `steam` in the terminal and launch it like normal. When you have tried that, just paste everything from the terminal into here.

**Comment by ptibedo** [comment]
Here : steam.sh[158286]: Running Steam on steamos rolling 64-bit
steam.sh[158286]: STEAM_RUNTIME is enabled automatically
setup.sh[158390]: Steam runtime environment up-to-date!
steam.sh[158286]: Steam client's requirements are satisfied
[2022-07-18 16:43:09] Startup - updater built Jun 29 2022 07:46:36
[2022-07-18 16:43:09] Opted in to client beta 'steamdeck_stable' via beta file
You are in the 'steamdeck_stable' client beta.
Installing breakpad exception handler for appid(steam)/version(1656536422)
[2022-07-18 16:43:09] Loading cached metrics from disk (/home/childebert/.local/share/Steam/package/steam_client_metrics.bin)
[2022-07-18 16:43:09] Using the following download hosts for Public, Realm steamglobal
[2022-07-18 16:43:09] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-07-18 16:43:09] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-07-18 16:43:09] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1656536422)
[2022-07-18 16:43:09] Vérification de l'installation...
[2022-07-18 16:43:09] Verification complete
Loaded SDL version 2.23.0-7281309
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'

(steam:158461): Gtk-WARNING **: 16:43:10.899: Impossible de trouver le moteur de thème dans module_path : « adwaita »
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
ComputeStartupMode: found registry default startup mode: 0steamwebhelper.sh[158520]: Runtime for steamwebhelper: defaulting to /home/childebert/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[158520]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
CAppInfoCacheReadFromDiskThread took 114 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1656536422)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)

(steam:158461): Gtk-WARNING **: 16:43:12.300: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 3302 bytes.
*** MESA_GLSL_CACHE_DIR is deprecated; use MESA_SHADER_CACHE_DIR instead ***
*** MESA_GLSL_CACHE_MAX_SIZE is deprecated; use MESA_SHADER_CACHE_MAX_SIZE instead ***
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
Installing breakpad exception handler for appid(steam)/version(1656536422)
roaming config store loaded successfully - 3302 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 47ms
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/childebert/.local/share/Steam/ubuntu12_32/steam' '-steamdeck'"
System startup time: 6.24 seconds
BuildCompleteAppOverviewChange: 463
RegisterForAppOverview 1: 51ms
RegisterForAppOverview 2: 52ms
GameAction [AppID 550, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 550, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 550, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 550, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 550, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 550, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/childebert/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=550 -- '/home/childebert/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/run/media/childebert/stockage/SteamLibrary/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/childebert/.local/share/Steam/steamapps/common/Left 4 Dead 2/./hl2.sh' -game left4dead2 -steam\0
Game process added : AppID 550 "/home/childebert/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=550 -- '/home/childebert/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/run/media/childebert/stockage/SteamLibrary/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/childebert/.local/share/Steam/steamapps/common/Left 4 Dead 2/./hl2.sh' -game left4dead2 -steam", ProcID 159160, IP 0.0.0.0:0
chdir /home/childebert/.local/share/Steam/steamapps/common/Left 4 Dead 2
ERROR: ld.so: object '/home/childebert/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 550, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/childebert/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/childebert/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/childebert/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/childebert/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 550, ActionID 1] : LaunchApp changed task to Completed with ""
pid 159166 != 159161, skipping destruction (fork without exec?)
Installing breakpad exception handler for appid(steam)/version(1656536422)
pid 159496 != 159490, skipping destruction (fork without exec?)
pid 159501 != 159490, skipping destruction (fork without exec?)
pid 159545 != 159490, skipping destruction (fork without exec?)
SDL video target is 'x11'
SDL video target is 'x11'
Using shader api: shaderapivk
info:  Game: hl2_linux
info:  DXVK: v1.9.2-32-ga2dc99c
info:  Built-in extension providers:
info:    SDL2 WSI
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_xlib_surface
terminate called after throwing an instance of 'dxvk::DxvkError'
/home/childebert/.local/share/Steam/steamapps/common/Left 4 Dead 2/./hl2.sh: line 72: 159549 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game process removed: AppID 550 "/home/childebert/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=550 -- '/home/childebert/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/run/media/childebert/stockage/SteamLibrary/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/childebert/.local/share/Steam/steamapps/common/Left 4 Dead 2/./hl2.sh' -game left4dead2 -steam", ProcID 159160 
ThreadGetProcessExitCode: no such process 159549
ThreadGetProcessExitCode: no such process 159546
ThreadGetProcessExitCode: no such process 159490
ThreadGetProcessExitCode: no such process 159163
ThreadGetProcessExitCode: no such process 159161
Uploaded AppInterfaceStats to Steam
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)
Installing breakpad exception handler for appid(steam)/version(1656536422)

**Comment by Munoida** [comment]
So, 2 possible solutions

Have you installed the proper drivers for your Graphics Card? _(This is especially important for NVIDIA users)_

And if you did/already did and it doesn't work, try clearing any launch options if you have any and put `-vulkan` into your launch options if your GPU is Vulkan compatible, which, most "gaming" GPU's are.

**Comment by ptibedo** [comment]
I puted -vulkan and dont work. I have nvidia driver 515.57. Dota 2,Street fighter V, and other game work but dont L4D2.

**Comment by ptibedo** [comment]
Yes. for some time SteamOS Holo  supports nvidia series 9 cards.

**Comment by kisak-valve** [comment]
Hello @ptibedo, the missing video driver support should be reported and evaluated by the package maintainer of the third party fork of SteamOS.

Closing because this is a system config issue instead of a game issue.
