### ISSUE TITLE
[TF2] [Feature Request] Change the default values of fov_desired to 90 and viewmodel_fov to 75

### ISSUE THREAD

**Issue by NotSoCommonSense** [ValveSoftware/Source-1-Games#4059]
TF2's default settings have been a talking point for some time now. Notably, the default FOV values, which are too low to be playable. 

fov_desired 75 creates a very limited field of vision making it harder to see enemies in one's peripheral vision.

viewmodel_fov 54 sometimes covers a massive portion of the screen with certain weapons (for example, the grenade launcher).

I propose these values be changed to 90 and 75, respectively.

**Comment by kisak-valve** [comment]
Hello @NotSoCommonSense, this request is already being tracked at #2163. Closing as a duplicate.
