### ISSUE TITLE
[TF2]"mat_monitorgamma" Reseting at random times during games

### ISSUE THREAD

**Issue by NiahmaS** [ValveSoftware/Source-1-Games#4077]
When playing on valve servers my monitor gamma / ingame brightness levels keeps changing for no reason, i've maxed it out in both my cfg and autoexec.

**Comment by Tiagoquix** [comment]
OP, does this still happen?

Use `mat_savechanges;host_writeconfig` to properly save your new value for the `mat_monitorgamma` CVar.

**Comment by kisak-valve** [comment]
Closing pending feedback.
