### ISSUE TITLE
[TF2] Lasers on rd_asteroid are broken

### ISSUE THREAD

**Issue by mrtino** [ValveSoftware/Source-1-Games#4085]
On rd_asteroid, env_laser entities are used at both sides of the map and rely on path_track as endpoints of the lasers so they can be displayed. However, since the 7/7/2022 update, path_track entities are now server-side and as such, can't be used as endpoints for env_lasers. Lasers on rd_asteroid are now rendered like this:

![image](https://user-images.githubusercontent.com/7429496/179955138-b55c93c0-e29b-470d-982c-e8e28664ce4d.png)

**Comment by Ashetf2** [comment]
This is related to #4024

I think an issue focused on the main issue (server-side entities not being networked) should be created

**Comment by nosoop** [comment]
Issue appears to be resolved in the 2022-07-29 update.

**Comment by agrastiOs** [comment]
@mrtino Can confirm, latest update resolved this. 
![paveikslas](https://user-images.githubusercontent.com/15906773/182025614-cdafa5e1-f193-481c-9228-ef915e0d4338.png)
