### ISSUE TITLE
[TF2] Getting kicked out of the upgrade station

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#4105]
When one of your strange weapons (such as the PDA or the Soul Gargoyle) changes any of its numbers or when the party changes (someone gets invited/asks to join), you will be kicked out of the upgrade station. 

While this is intentional, it is unnecessary and can be used by people to stop people from being able to upgrade. It can be abused by, for example, taking an Engineer's teleporter constantly or by people (from outside your friends list) continuously inviting themselves to the party (mainly targeting streamers playing MvM).

This should be easily fixed by going into c_tf_upgrades.cpp, at line 478-487 and commenting out the block of code there. Credit goes to [Trix](https://github.com/TrickyTrix935) for finding this solution.

**Comment by kisak-valve** [comment]
Hello @JoriKos, this issue is already being tracked at #3398. Closing as a duplicate.
