### ISSUE TITLE
[TF2] Unused Text Chat Icon on players

### ISSUE THREAD

**Issue by JonaMake** [ValveSoftware/Source-1-Games#4107]
Add an icon above the player when he writes something to the chat
![image](https://user-images.githubusercontent.com/73250357/181056226-27b04d1e-0a25-4ed1-95ce-53094df52d00.png)
in game:
![Screenshot_1](https://user-images.githubusercontent.com/73250357/181056718-0a8134f5-aacd-4fae-ade9-9057e932c7a2.png)

**Comment by rabscootle** [comment]
Chat bubble would maybe need a new asset to fit the new style used for 'MEDIC!' call (as of Two Cities Update):
![image](https://user-images.githubusercontent.com/108029512/181144740-3ec7b87d-e0ed-49ca-9ec2-8abb4fc438f7.png)

**Comment by condor00fr** [comment]
good idea, tf2c did it, so why not in live?

**Comment by Ashetf2** [comment]
Duplicate of #2052?

**Comment by kisak-valve** [comment]
Indeed, closing in favor of the older feature request.
