### ISSUE TITLE
[Portal Beta- Linux] Not so fluid gameplay

### ISSUE THREAD

**Issue by Lord-Avallon** [ValveSoftware/Source-1-Games#412]
(This bug was here #409 and was reopen as a single issue)

Gameplay issue:

It´s not fluid, there are some little jumps on the frames, nothing that makes the game unplayable, I lowered the settings to fit my graphics card and got some improvement, it is nearly normal, but it´s not as fluid as when I played it on Windows.

My specs: https://gist.github.com/Lord-Avallon/4521727

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. This type of render stalling is expected with OpenGL video drivers that do not support an on-disk shader cache.
