### ISSUE TITLE
[TF2] MvM Mission Selection sometimes draws under the Category Controls

### ISSUE THREAD

**Issue by mtxfellen** [ValveSoftware/Source-1-Games#4125]
The bug is caused by `MVMModeSelect` and `MVMCriteria` using the same `"zpos"` value, so the fix is fairly trivial; simply change the `"zpos"` value of `"MVMCriteria"` in `resource/ui/matchmakingdashboardmvmcriteria.res` to a value of `"1003"` or higher.

Demonstration of the bug (present in stock hud also):
![](https://i.imgur.com/z8drj1i.png)

**Comment by condor00fr** [comment]
yes pls fix ty

**Comment by FrozenDragon0** [comment]
Oh yes, had this issue occur a few times myself, extremely annoying having to restart the game when your trying to do Mann up and selecting the missions for the tours.

**Comment by mtxfellen** [comment]
Closing as completed (proposed fix was applied on [August 11, 2022](https://www.teamfortress.com/post.php?id=141793)).
