### ISSUE TITLE
[TF2] Add new cvar command: sv_infinite_ammo 0/1

### ISSUE THREAD

**Issue by JonaMake** [ValveSoftware/Source-1-Games#4130]
Impulse 101 is a disgusting command to bind, it's better to add a new command that will be useful and convenient as in CSGO or L4D2.

**Comment by thejaviertc** [comment]
Duplicated of #3828

**Comment by kisak-valve** [comment]
Indeed, closing as a duplicate.

**Comment by JonaMake** [comment]
> Indeed, closing as a duplicate.

Sorry, I didn't notice
