### ISSUE TITLE
pendejo

### ISSUE THREAD

**Issue by TKW905** [ValveSoftware/Source-1-Games#4158]

**Comment by condor00fr** [comment]
Good idea, it makes the gun more unique and will give us more info during gameplay, I like it:)

**Comment by TF2CutContentWiki** [comment]
If needed, I can also provide the old d_images and dneg_images VTFs from before the Pyro Update, that have the Dart killicon in them, if those PNGs of the icons I attached aren't good enough @kisak-valve
