### ISSUE TITLE
[TF2] [Linux] Character rotation speed in loadout menu

### ISSUE THREAD

**Issue by Doclic** [ValveSoftware/Source-1-Games#4166]
When in the loadout menu, if you try to click your character to rotate it, the character will rotate way too fast.
Example taken from a video I recorded (GitHub won't allow me to upload it)

Frame 1:
![image](https://user-images.githubusercontent.com/30270428/184406470-e4152b08-8314-4ddc-a06c-2a1e8c2a77c7.png)

Frame 2:
![image](https://user-images.githubusercontent.com/30270428/184406485-972b0e48-4006-4d11-a114-2f7281fd4f98.png)

Frame 3:
![image](https://user-images.githubusercontent.com/30270428/184406630-998a56fd-dbc6-4591-a371-a5bf4225d069.png)

**Comment by kisak-valve** [comment]
Hello @Doclic, this issue is already being tracked at #2790. Closing as a duplicate.
