### ISSUE TITLE
[TF2 Linux] Decals set incorrectly on 2Fort glass

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/Source-1-Games#4172]
yeah 
![image](https://user-images.githubusercontent.com/84733553/184475673-c81d9f96-8e49-43e4-9775-0b9225744613.png)

**Comment by Munoida** [comment]
Decals on TF2 seem to be set incorrectly all together, whilst some work as expected, there are some really obvious outliers, like all of the mercenaries. It seems to be a texture issue (meaning most likely EVERY decal has generic concrete bullet hole texture) and not an error with correctly applying decals.

I mean, this is the only thing in the decals folder in the tf2_textures vpk 
![image](https://user-images.githubusercontent.com/84733553/187099485-765ebbea-aff0-4696-8912-9e0a2d87349d.png)

**Comment by Munoida** [comment]
https://streamable.com/cumiwe

I forgot to show some mercenaries decals but all of them have the same decal issue.

**Comment by mastercoms** [comment]
you sure you don't have a mod which messes with surface properties?

**Comment by Munoida** [comment]
Yeah I checked, nothing messes with the decal textures in my custom folder, considering validating my games integrity.

**Comment by mastercoms** [comment]
Not decal fextures, surfaceproperties.txt. What do you have in your custom folder?

**Comment by Munoida** [comment]
Only thing that changes any kind of textures is my Crit icon. and it, only changed the crit icon, i'll probably clear out my custom folder, verify integrity and try again. I'm not able to do it right now though

**Comment by Munoida** [comment]
![image](https://user-images.githubusercontent.com/84733553/206531846-0519ddd1-c440-444e-b62e-12cacb8072c8.png)
This is now fixed. Don't know how long how it's been fixed, if it was fixed by me using Wayland instead of X11 which would be completely unrelated but could be possible, or fixed manually by VALVe.
