### ISSUE TITLE
[TF2] Crashing in casual mode when using custom weapon models

### ISSUE THREAD

**Issue by Doclic** [ValveSoftware/Source-1-Games#4173]
When joining a casual match, my game always crashes if I played on a community server that allows custom weapon models before.
I assume this is because my game loaded the models, but casual doesn't allow them (even if it really should!)

This happens on Linux & Windows and maybe MacOS, but I don't own a Mac to test it.

**Comment by FrozenDragon0** [comment]
This issue seriously needs a fix as it's extremely frustrating wanting to play a casual server after being on a community one only for the game to crash because of custom content being blocked by sv_pure.

**Comment by Ashetf2** [comment]
Probably fixed in today's update: "Fixed a crash when going between two sv_pure servers with maps packing custom content". It says maps but I've been playing with a mod that changes sounds, and it usually crashed the game when trying to join Casual. It doesn't seem to happen anymore

**Comment by kisak-valve** [comment]
Closing per the last comment.
