### ISSUE TITLE
[TF2] SetCustomModel input doesn't apply animations properly

### ISSUE THREAD

**Issue by SpookyToad2** [ValveSoftware/Source-1-Games#4182]
### SetCustomModel animation issue
Input sets the "m_bUseClassAnimations" player property to false, preventing set player model from doing any animations at all, creating a new input that sets it to true will allow the matching animations to play normally. Check the 2 links I send on the bottom for how it should behave.

This input was added for the Prop Hunt gamemode and it can be used to set the model of the player.

I want to use this input for my map but the problem is, this input doesn't make the set model use player's current animations, resulting in not using any animations at all and use T pose of the set model, regardless of whether model had matching animations with the player or not.

This prevents me from replacing player's model with the one that fits the theme of the map.

This is caused by the input setting "m_bUseClassAnimations" property of the player to false by default, setting it to true using a plugin fixes the issue. As a mapper, there is no way to change this on your own.

If the backwards compatibility wants to be kept, a new input with the name SetCustomModelWithAnimations can be added which sets "m_bUseClassAnimations" to true along with setting the speficied model.

I have linked 2 gifs demonstrating the behaviors, first one is using the default behavior, "m_bUseClassAnimations" being set to false, model uses T pose, second one having "m_bUseClassAnimations" set to true, model animations work as they supposed to be.

Broken
![U6ZP1gI](https://user-images.githubusercontent.com/74873411/184685570-1912c0f6-3225-4700-ae4b-82aa48b950f5.gif)

Working
![v98ham7](https://user-images.githubusercontent.com/74873411/184685649-031d7082-9098-49bc-935b-9c7357256c2d.gif)

**Comment by R60D** [comment]
I'm currently creating a deathrun map that would require this solution.
Currently we have to do some abstract workaround with bonemerging which is very unstable and unpredictable.

**Comment by Berke111** [comment]
This is a fix that would be really helpful for us, currently we have no way of using player models with custom animations as mappers and it really hurts the themeing of my maps.

**Comment by arctic-dino** [comment]
Map makers who have model swapping in their maps would gladly appreciate this, me included. Also custom game modes like Vs. Saxton Hale and Freak Fortress 2 would greatly benefit from this with all the model placements that occur.

**Comment by Coronarena** [comment]
I would've liked this for my old map. It'd be nice if I could see newer maps use this as a feature.

**Comment by JonathanPR-Github** [comment]
I have a CustomModel i intend to use as a secret in my map, however without it's custom animations it won't work properly. It would really helpful to all mappers and that of myself with CustomModels to have this feature that would fix the animations for the CustomModels.

**Comment by 111112oo** [comment]
would be cool

**Comment by FlaminSarge** [comment]
> If the backwards compatibility wants to be kept, a new input with the name SetCustomModelWithAnimations can be added which sets "m_bUseClassAnimations" to true along with setting the speficied model.

In the same way that "SetCustomModelRotates" exists, this should probably be a new input "SetCustomModelUsesClassAnimations" that solely sets the `m_bUseClassAnimations` property, instead of your proposed "SetCustomModelWithAnimations" that sets both the model and property.

**Comment by SpookyToad2** [comment]
Fixed in latest update. Closing

**Comment by FlaminSarge** [comment]
It may still be useful to be able to toggle `m_bUseClassAnimations` via input, rather than being forced to use `SetCustomModel`/`SetCustomModelWithClassAnimations` to perform that toggle. It's a bit surprising that it was implemented with solely the one input.
