### ISSUE TITLE
[TF2] YouTube Integration Nonfunctional; Breaks Achievements

### ISSUE THREAD

**Issue by wertercatt** [ValveSoftware/Source-1-Games#4187]
The YouTube API used by the Replay system has been deprecated and is no longer functional. This prevents the achievements Home Movie, Local Cinema Star, Indie Film Sensation, and Blockbuster from being legitimately obtained. I believe YouTube Data API v2 was in use, so this [documentation on migrating to the current YouTube Data API v3](https://developers.google.com/youtube/v3/getting-started) may be of use.

**Comment by kisak-valve** [comment]
Hello @wertercatt, this issue is already being tracked at #2277. Closing as a duplicate.
