### ISSUE TITLE
[TF2] [Feature Request] Update War Paint name syntax to be similar to CS:GO

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#4205]
The syntax for war paints doesn't make sense in other languages. For example, in spanish, "Dragon Slayer Rocket Launcher" is "**Matadragones Lanzacohetes**", and it is incorrect, since it should say "**Lanzacohetes Matadragones**"
![image](https://user-images.githubusercontent.com/63692647/186033540-63e65df0-386b-4b28-9102-c05a705c19b5.png)

However, since war paint names are no longer a description of the weapon, like with Gun Mettle and Tough Break skins, in some cases they don't make sense even in English. (for example, "Haunted Ghosts Rocket Launcher". ??? ) So, I suggest to change the syntax to be **NAME_OF_ITEM | NAME_OF_WAR_PAINT**, like in CS:GO.

![image](https://user-images.githubusercontent.com/63692647/186034359-c0cb868b-ce80-485b-b716-564e2057a65c.png)

Examples of how it would look:
![image](https://user-images.githubusercontent.com/63692647/186034749-9507785f-538a-4fbb-8763-8e2bccec43f8.png)
And if #3741 is fixed:
![image](https://user-images.githubusercontent.com/63692647/186034796-79a9532e-57fa-4f9f-a05a-0f388f0d1ec9.png)

Edit: Minor corrections

**Comment by condor00fr** [comment]
another thig that is worth mensionning, in French, the market Garden as renamed "The gardener" while it should have been: 
"Le Market Garden"

**Comment by Ashetf2** [comment]
> another thig that is worth mensionning, in French, the market Garden as renamed "The gardener" while it should have been: "Le Market Garden"

That's a different issue

**Comment by condor00fr** [comment]
I kown, but it's sill a translation issue, wich you also adressed in a way:)

**Comment by Ashetf2** [comment]
> I kown, but it's sill a translation issue, wich you also adressed in a way:)

You can suggest changes in Crowdin, though I don't see an issue with the translation. This problem requires some code change I believe.

**Comment by Ashetf2** [comment]
A string was added in the July 18 Patch, "ToolPaintKit_ItemDescFormat"	"%s1 %s2", which allows to change the order of the syntax in other languages. Thanks Valve!

![imagen](https://github.com/user-attachments/assets/0773b342-cf3d-405a-a643-c474a53cfdb6)
