### ISSUE TITLE
[L4D2 Beta/Linux/Suggestion] Please add a FOV slider

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#421]
Because L4D2 has such a low field of view, I'm getting a lot of eye strain.

I know it's possible to modify the fov with the console but please add a slider to the options menu.

**Comment by Yetoo1** [comment]
Latest update added FOV slider in the multiplayer options. I ran the latest build and it's there. This seems like it can be closed @kisak-valve.

**Comment by kisak-valve** [comment]
Closing per "- Added an FOV slider to the Multiplayer settings." in the [2021-06-15](https://steamcommunity.com/games/L4D2/announcements/detail/4625740823862061052) Left 4 Dead 2 update.
