### ISSUE TITLE
[TF2] The word "Maps" isn't translated in the Steam Workshop for TF2

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#4215]
![image](https://user-images.githubusercontent.com/63692647/186694051-81cc28cd-d20f-4b95-923a-51e0baffcbf0.png)
![image](https://user-images.githubusercontent.com/63692647/186694272-0e6db47e-f115-4489-b72d-b3a5908fc7b3.png)
This doesn't happen in the Workshop for CS:GO, for example.
![image](https://user-images.githubusercontent.com/63692647/186694557-27d4c8b1-520f-4feb-a261-32e676ab80d2.png)

**Comment by kisak-valve** [comment]
Hello @Ashetf2, this issue is part of Steam's website and not the game. Please report this issue to [Steam Support](https://help.steampowered.com/) so that the feedback can reach the relevant devs.

**Comment by gaelcoral** [comment]
it is now fixed
![image](https://user-images.githubusercontent.com/63524243/226709311-5e1f43b0-c3f4-4b99-b0a9-6ccc2ee94b53.png)

**Comment by Ashetf2** [comment]
Nice
![steam_NZs8V5UIII](https://user-images.githubusercontent.com/63692647/226734828-a5d28d8b-f49a-44ee-a7b8-bd17580602d7.png)
