### ISSUE TITLE
[TF2] Game crashing whole computer after July 29th update?

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4217]
So ever since the recent cosmetic update came out, I've noticed that the game will start crashing way more than it has before. Now I'm not talking about the game stops responding and then closes, I'm talking about my **whole** computer completely shutting off when I have the game open. Sometimes it does this after an hour of having it open, sometimes only a half hour, and sometimes it almost immediately crashes at the beginning of the match. This sounds to me like an extension of that bug where the game would lag when getting killed that "got fixed". Let me assure you that this has **never** happened to me before this update, and that I've been using the same computer for the past 2 years to play this. I can't provide any screenshots on this at all and I've checked my computer's logging, which does say there was some kind of issue at hand. But this didn't get to the bottom of why the game is causing this.

**Comment by kisak-valve** [comment]
Hello @ShadowMan44, in general, no OpenGL application including Team Fortress 2 should be capable of taking down the entire system. This reads like a video driver or kernel issue. Are you able to ssh into the system after the issue appears and check `dmesg` or the system logs for any hints?

**Comment by RicochetYT** [comment]
TF2 is only running in OpenGL (translated from DX9) on Linux or MacOS, this person did not specify whether they were on Windows or Unix, so it's probably best to assume(?) that they are running Windows, meaning TF2 is running in DX9, not OpenGL.
Does this mean DX9 will take down the whole system? Beyond me.

**Comment by ShadowMan44** [comment]
I am on Win10, I apologize for not specifying.

I went into the Event Viewer on Windows 10 and while I'm not entirely sure where the crash happened, I can definitively tell you this problem didn't start until the Summer cosmetic update dropped. I'm not saying that those silly hats are the reason, but it's so strange to me that this has literally never happened before until now.

**Comment by ShadowMan44** [comment]
Update: It happened again, right as soon as the round was over no less

The event logs said something vague about like audio drivers? I don't know why Team Fortress 2 specifically causes these to fail because no other program does this.

**Comment by Marioiscool246** [comment]
@ShadowMan44 are you by any change using a nvidia gpu?

**Comment by ShadowMan44** [comment]
No, from the looks of the GPU it's like some intel HD graphics thingy.

**Comment by ShadowMan44** [comment]
Here's an update
I'm reading more errors on the event viewers (because it's still happening) and 2 of them catch my eye
The are
"Session "NT Kernel Logger" failed to start with the following error: 0xC0000035" and "Faulting application name: sttray64.exe, version: 1.0.6289.0, time stamp: 0x4c1ad9c0".
What do these have to do with TF2? TF2 is the only game on my computer that does this, no other game (Valve game mind you) has this incredibly serious issue going on. I don't know what's happening!

**Comment by ShadowMan44** [comment]
Okay, so after months of silence I actually managed to fix the issue.

It turned out there was a bit of dust in my laptop's fan :/
Unless it happens again, the issue has been resolved.
