### ISSUE TITLE
[TF2] The Vaccinator's tier 1 charge sound is wrong

### ISSUE THREAD

**Issue by Fattyton** [ValveSoftware/Source-1-Games#4226]
The Vaccinator's current in-game tier 1 charge sound is the default Medigun charged sound (medigun_charged.wav), but in the game files there is an audio file called "vaccinator_charge_tier_01.wav" and is clearly supposed to be the Vaccinator's actual tier 1 charge sound. I'm working on a mod that replaces the Vaccinator sounds which is how I noticed this oddity. Could you please change the current in-game Vaccinator's tier 1 charge sound from "medigun_charged.wav" to "vaccinator_charge_tier_01.wav"?

**Comment by kisak-valve** [comment]
Hello @Fattyton, this issue is already being tracked at #4016. Closing as a duplicate.
