### ISSUE TITLE
Object depth rendering incorrectly

### ISSUE THREAD

**Issue by matthewharvey** [ValveSoftware/Source-1-Games#425]
This happens at several points throughout the game. An object that should be in the forefront is rendered in the background of some object that should be in the background. Images attached.

![2013-05-03_00018](https://f.cloud.github.com/assets/1594441/462004/66aea7f2-b45d-11e2-8748-4f9c56c97f63.jpg)
![2013-05-03_00019](https://f.cloud.github.com/assets/1594441/462005/76263862-b45d-11e2-9e6c-9c1077c8f7e4.jpg)
![2013-05-03_00001](https://f.cloud.github.com/assets/1594441/462006/7e9e4674-b45d-11e2-9ee8-c3ea05b7ff8b.jpg)
![2013-05-03_00002](https://f.cloud.github.com/assets/1594441/462007/879ffa92-b45d-11e2-92c4-140e4efd4697.jpg)
![2013-05-03_00007](https://f.cloud.github.com/assets/1594441/462008/96d2024e-b45d-11e2-881e-f9cac69f8139.jpg)
![2013-05-03_00010](https://f.cloud.github.com/assets/1594441/462009/b24b4d28-b45d-11e2-9f07-06306dadd32f.jpg)
![2013-05-03_00011](https://f.cloud.github.com/assets/1594441/462010/b8eb2874-b45d-11e2-974f-5d1ef16491a1.jpg)

System: glxinfo | grep Open
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL version string: 3.0 Mesa 9.0.3
OpenGL shading language version string: 1.30
 i5-3230M
64 bit

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date version of Mesa, please open a new issue report.
