### ISSUE TITLE
[TF2] Loadout UI does not properly support ConTracker/action item style overrides

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#4255]
Hi! The Loadout UI doesn't seem to support displaying the correct ConTracker style. I assume this is because proper support for style overrides was never added for the action slot:
![image](https://user-images.githubusercontent.com/108029512/189470032-195bf427-4c06-43ce-ba22-a7234a7de543.png)

Strangely enough, weapons with similar behavior (Botkiller weapons, Australium weapons) will affect which style displays on the ConTracker based on the skin index # of the weapon drawn out in the UI (Blood Botkiller and Bronze Contracker displayed in proceeding pic are skin no. 6 in their respective models):
![image](https://user-images.githubusercontent.com/108029512/189470064-215a53c0-9c03-48cf-b864-381938870042.png)

**Comment by rabscootle** [comment]
Issue probably also affects 3D HUD elements! I know other loadout-related issues seem to trickle into there too (ie. #3518)

**Comment by kisak-valve** [comment]
Hello @rabscootle, this issue is already being tracked at #4167. Closing as a duplicate.
