### ISSUE TITLE
[Portal Linux] Test chamber 12, no "WEEEEEEEEEEEEEEEEEEEEEEEE"

### ISSUE THREAD

**Issue by randomweej** [ValveSoftware/Source-1-Games#426]
on test chamber 12 when launching from the third level up to the fourth the glados sound effect "weeeeeeeeeeeeeeeeeeeee" is missing,
unsure if an update has removed it or if it's a bug/missing.

**Comment by kisak-valve** [comment]
Closing pending a reproduction case that does not involve alt-tabbing.
