### ISSUE TITLE
Team Versus / Team Scavenge search is broken in L4D2

### ISSUE THREAD

**Issue by JayBoom** [ValveSoftware/Source-1-Games#4264]
1. You can't cancel search, you have to leave the lobby in order to, cancel search does nothing
2. If someone leaves, it doesn't cancel search, then you can't cancel search (see 1.)
3. It seems you can not find a game at all, I tried for hours in both modes (Team versus and team scavenge) with a full lobby on all 4 search modes (official dedicated, best avaliable dedicated, local server, steam group server), no match, **EVEN when I tried to do it searching against another lobby of 4. We both waited an hour in the queue and never matched.**

**Comment by kisak-valve** [comment]
Hello @JayBoom, you previously reported this issue at #4112. Closing as a duplicate.
