### ISSUE TITLE
[TF2] Steam workshop is confusing and counterintuitive

### ISSUE THREAD

**Issue by Thespikedballofdoom** [ValveSoftware/Source-1-Games#4283]
It just doesn't make sense to the average user, even one who understands the console, that to use workshop maps you have to type the exact workshop id of the map in this command: `workshop/<workshopID>`.

For instance, I subscribed to a map called ctf_giants_rc3. Server launch dialog:
![cap_22-09-2022_06 04 10AM_370x480](https://user-images.githubusercontent.com/43627353/191732229-0bae7ab8-5da6-4f22-9a62-ae133a644932.png)

Given that server operators can point clients to download maps via the workshop "Updating steam resources...", I don't get why this irritating hurdle is left for users. In L4D2 subscribed maps are presented both in the menu and auto-completed in the console.

**Comment by Ashetf2** [comment]
I would say that this issue is similar to [#210](https://github.com/ValveSoftware/Source-1-Games/issues/2100)

**Comment by kisak-valve** [comment]
Hello @Thespikedballofdoom, per "Updated the Create Server menu to show workshop maps" in the [2022-10-12](https://www.teamfortress.com/post.php?id=144345) Team Fortress 2 update, please retest this issue.

**Comment by Thespikedballofdoom** [comment]
I wish there was a way to preview the map names in the console like in L4D2, but since map_workshop commands work now, it's not at all hard to launch a server quickly. This is absolutely usable.
