### ISSUE TITLE
[TF2] [Feature Request] Change the default settings

### ISSUE THREAD

**Issue by melon-mann** [ValveSoftware/Source-1-Games#4286]
With TF2's competitive playerbase and popularity growing, there's bound to be some discussion of configurations and mods. One of the most popular is that, **TF2's default settings are absolutely horrid**..

I, and many others have requested that the default should be changed, I am making this issue in hopes that they do, so every time I reinstall TF2 I don't have to install a config and test it, instead of actually playing the game.

For the settings, turn off V-Sync and turn on multicore rendering. V-Sync has been surpassed greatly by Freesync (AMD) and G-Sync (NVidia)

For commands, these are all courtesy of the [TF2 Essentials](https://aarmastah.xyz/misc/tf2e/) config by Aar, though some could debate that there is better settings.

<hr>

<details>
  <summary>Networking Command Defaults</summary>

  fps_max 300
  rate 97000
  cl_cmdrate 66
  cl_updaterate 66
  cl_interp 0
  cl_interp_npcs 0.1
  cl_interp_ratio 2
  sv_allowdownload 1
  sv_allowupload 1
  net_queued_packet_thread 1
  net_compresspackets 0
  net_splitrate 2
  cl_pred_optimize 1
  cl_lagcompensation 1
  cl_predictweapons 1
  cl_smooth 1
  cl_smoothtime 0.1
</details>

<details>
  <summary>Gameplay Command Defaults</summary>

  viewmodel_fov 70
  fov_desired 90
  viewmodel_fov_demo 70
  demo_fov_override 90
  glow_outline_effect_enable 1
  hud_fastswitch 1
  cl_autoreload 1
  sv_lan 1
  tf_mvm_min_players_to_start 1
  cl_mvm_wave_status_visible_during_wave 1
  cl_use_tournament_specgui 1
  hud_combattext 1
  hud_combattext_batching 1
  hud_combattext_batching_window 2
  hud_combattext_doesnt_block_overhead_text 1
  tf_medigun_autoheal 1
  hud_medichealtargetmarker 1
  hud_medicautocallers 1
  hud_medicautocallersthreshold "60"
  tf_hud_target_id_disable_floating_health 1
  tf_dingalingaling 1
  tf_dingalingaling_lasthit 1
  tf_scoreboard_mouse_mode 2
  engine_no_focus_sleep 0
</details>

<details>
  <summary>Input Command Defaults</summary>

  m_customaccel 0
  m_mouseaccel1 0
  m_mouseaccel2 0
  m_rawinput 1
</details>

<details>
  <summary>Misc. Command Defaults</summary>
  
  // This is debatable. Disables tutorial popups, in my opinion, these only confuse the player more. You should learn at your own pace.
  cl_ask_blacklist_opt_out "1"
  cl_ask_favorite_opt_out "1"
  sb_dontshow_maxplayer_warning "1"
  tf_explanations_backpackpanel "1"
  tf_explanations_charinfo_armory_panel "1"
  tf_explanations_charinfopanel "1"
  tf_explanations_craftingpanel "1"
  tf_explanations_discardpanel "1"
  tf_explanations_store "1"
  tf_training_has_prompted_for_forums "1"
  tf_training_has_prompted_for_loadout "1"
  tf_training_has_prompted_for_offline_practice "1"
  tf_training_has_prompted_for_options "1"
  tf_training_has_prompted_for_training "1"
  cl_showhelp 0
  tf_taunt_always_show_hint 0
  sb_dontshow_maxplayer_warning 1
  tf_coach_request_nevershowagain 1
  tf_show_maps_details_explanation_count 0
  tf_show_taunt_explanation_in_class_loadout 0
  tf_show_preset_explanation_in_class_loadout 0
  cl_hud_playerclass_playermodel_showed_confirm_dialog 1
  tf_find_a_match_hint_viewed 1
  tf_quest_map_intro_viewed 1
  tf_warpaint_explanation_viewed 1
  // Unbindall should be removed, too. Useless.
  alias unbindall "echo Blocked unbindall attempt"
</details>

<details>
  <summary>Optimization Command Defaults</summary>

  r_queued_decals 0 
  r_threaded_particles 1
  r_threaded_renderables 1
  net_queue_trace 0
  studio_queue_mode 1
  cl_threaded_client_leaf_system 0
  r_threaded_renderables 1
  r_threaded_particles 1
  r_queued_ropes 1
  r_queued_post_processing 1
  r_threaded_client_shadow_manager 1
  snd_mix_async 1
  snd_async_fullyasync 1
  cl_new_impact_effects 0
  mat_alphacoverage 0
  rope_averagelight 0
  hud_achievement_glowtime 0
  r_decals 50
  mp_decals 50
  r_maxmodeldecal 9
  r_queued_post_processing 0
  sys_minidumpspewlines 500
  studio_queue_mode 1
  mat_queue_mode 2
  r_entityclips 1
  r_frustumcullworld 1
  r_worldlistcache 1
  r_occludermincount 1
  tf_hud_target_id_show_avatars 0
  tf_time_loading_item_panels 0.0001
  tf_backpack_page_button_delay 0.25
  lzma_persistent_buffer 1
  filesystem_buffer_size 262144
  filesystem_max_stdio_read 256
  filesystem_native 1
  filesystem_unbuffered_io 1
  mod_load_anims_async 1
  mod_load_mesh_async 1
  mod_load_vcollide_async 1
  mod_touchalldata 0
  mod_forcedata 0
  mod_forcetouchdata 1
  snd_async_fullyasync 1
  snd_cull_duplicates 0
  voice_steal 2
  snd_noextraupdate 1
  snd_defer_trace 1
  phonemefilter 0.1
  phonemesnap 63
  phonemedelay 0
  in_usekeyboardsampletime 1
  r_particle_sim_spike_threshold_ms 0
</details>

<hr>

Final note, this problem is very popular as mentioned earlier, so I'm not sure if there's already an issue on this exact subject. If there is, I hope to add additional information.

**Comment by kisak-valve** [comment]
Hello @melon-mann, in general, multi-issue issue reports are bad for any issue tracker, and this a request to change the default of a bunch of unrelated things with no explanation behind the adjustments. This should be requested on a much finer granularity than this issue report with the reasoning behind the specific changes to persuade the Team Fortress 2 devs.

Closing because this broad of a feature request can't be tracked properly.
