### ISSUE TITLE
[TF2] Cosmetics that should be able to be combined are 'conflicting'

### ISSUE THREAD

**Issue by Thespikedballofdoom** [ValveSoftware/Source-1-Games#4287]
https://user-images.githubusercontent.com/43627353/192370007-edae5391-bfde-4997-929e-592222fdee11.mp4

I didn't use some sort of quickswitch bug to get these cosmetics together, but now the system is dequipping them for me. This is clearly not intended as they're still selectable in the loadout screen.

**Comment by agrastiOs** [comment]
Will be fixed soon.

**Comment by Whurrhurr** [comment]
fixing this should possibly fix #4213, but in that issue's case, it seems to be the other way around (bots can't wear items with the "hat" equip region if they're wearing an item with the "glasses" equip region i also think "face" equip region and "hat" equip region also conflict, as you can't have bots wearing the full "Mad Doktor" set from halloween 2011)

**Comment by kisak-valve** [comment]
Hello @Thespikedballofdoom, per "Fixed being unable to equip certain valid cosmetic combinations" in the second [2022-09-26](https://www.teamfortress.com/post.php?id=143577) Team Fortress 2 update, please retest this issue.

**Comment by jh34ghu43gu** [comment]
I don't have the same items but I can equip pyrovision and hats at the same time, so fixed.

**Comment by Thespikedballofdoom** [comment]
I forgot to comment, it's been fixed since the update.
