### ISSUE TITLE
[TF2] Recent bug fix update made glasses unable to be wearable with normal head items.

### ISSUE THREAD

**Issue by Rottennuggetcode** [ValveSoftware/Source-1-Games#4289]
[TF2] So today on 9.26.2022, a bug fix patch has been released to Team Fortress 2. Many bugs and features got fixed but one of the main core mechanics got broken. You are unable to wear glasses with hats, the same goes for some facial hair items.

**Comment by kisak-valve** [comment]
Hello @Rottennuggetcode, this issue is already being tracked at #4287. Closing as a duplicate.
