### ISSUE TITLE
[TF2] [Feature Request] Add designated setting to ignore equip regions like old quickswitch behavior

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#4290]
The recent [9.26.2022](https://www.teamfortress.com/post.php?id=143572) update removes the ability for quickswitch to bypass equip regions of certain items. I agree with the fix on the basis that it is unintended, given the paradigm presented with the other equip menus, but it should have only gone through if there were a new client setting to bypass the equip region as an alternative/workaround as it is used by and relied on by too many players. There is now no way to bypass equip regions as the result of this fix. Some potential ways to rectify are: 
- Have a setting in advanced settings to disable region restrictions.
- Have an advanced button in the individual class loadout screens to quickly toggle the restriction to easily customize based on cosmetic creator intentions or what looks cool if restrictions disabled. 

There just needs to be something that will allow the same equip region conflicts as the old quickswitch behavior.

**Comment by rabscootle** [comment]
There's no reason this behavior needs to be added. The main equip UI had already indicated the affected items as conflicting.

**Comment by kisak-valve** [comment]
Hello @Yetoo1, this request directly contradicts the intent of the most recent update.

**Comment by Yetoo1** [comment]
@kisak-valve Why should that matter for this to be closed and can you direct me somewhere that shows that the intent includes removing all potential future alternative methods that include a part of the interface that isn't a weapon selection dialog.

**Comment by jh34ghu43gu** [comment]
Item equips are a global event handled by the GC, you can't have a client option to allow them without some sort of fundamental rewrite of the item system, which frankly would be terrifying to even attempt at all the crap that could go wrong.

**Comment by Yetoo1** [comment]
@jh34ghu43gu What I was trying to say was the only thing that could block an equip for the certain items would be on the client, but absent that block the cosmetics would display to other users. The idea is that since all it took was for there to be a lack of block for the old quickswitch functionality to work, then there is possibility for other more obvious means to allow equipping items that would otherwise be blocked in other parts of the interface.
