### ISSUE TITLE
puta madre

### ISSUE THREAD

**Issue by TKW905** [ValveSoftware/Source-1-Games#4299]

**Comment by TF2CutContentWiki** [comment]
Wait, the Sydney Sleeper doesn't use a projectile, does it? Isn't it hitscan?

**Comment by Ismaciodismorphus** [comment]
could have it visibly stick onto impact locations like needles and arrows

**Comment by condor00fr** [comment]
It could give it more personnality, noice

**Comment by Arbitz** [comment]
Honestly if the Sleeper used a super fast rescue ranger/crossbow style projectile it could work.

**Comment by condor00fr** [comment]
Make them work like tracers maybe? Like super super fast? I dunno but I think it would be nice to see them.
