### ISSUE TITLE
[L4D2][Linux] Slow mouse - no fps_max command - input lag

### ISSUE THREAD

**Issue by mattyy1hp** [ValveSoftware/Source-1-Games#431]
There is an issue in all Source games on Linux. I guess it has something to do with AMD drivers - mouse is very slow. It's a delay between real mouse move and the game reaction.
This happens on an older HW where is not possible to achieve 100+ FPS and FPS are more dynamic (50-80 for example).

The solution I use in TF2, HL2:DM, CSS etc. is "fps_max 60" command. After this command I have stable 60 fps and everything is smooth.
This command is not in L4D2 anymore.

Impossible to aim with a weapon.

---

I tried:
- turning off vSync - it's the same
- turning on vSync - it's the same
- high and low graphics settings - no difference
- turning off Catalyst A.I. - it's the same
- AMD 13.4 - it's the same + much worse performance I'm switching back to 13.3 Beta3
- windowed mode - did not help

[EDIT]
- disabling Steam community - no difference

---

AMD 13.3 Beta3
Gnome Shell

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Mutter
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6520G

```
Driver Version:  4.2.12173 Compatibility Profile Context 12.10.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6760
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3430 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  581188 Mb
    Largest Free Hard Disk Block:  134395 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
