### ISSUE TITLE
[TF2] Fix the broken models in the backpack's inspect menu

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4311]
Darwin's Danger Shield, Razorback, Holiday Punch, Hot Hand, Gass Passer, Ali Baba's Wee Booties, Bootlegger, Gunboats, and Mantreads are all unviewable in the item inspect menu. If there's any of them that I missed please tell me so I can add it later.

Also I think the Red-Tape Recorder should also be inspectable, just because it feels like a waste.

**Comment by kisak-valve** [comment]
Hello @ShadowMan44, this issue is already being tracked at #2341. Closing as a duplicate.
