### ISSUE TITLE
[TF2] Blu Scout's pants have incorrect belt loop colors

### ISSUE THREAD

**Issue by Chickenman456** [ValveSoftware/Source-1-Games#4312]
![image](https://user-images.githubusercontent.com/87006112/192648896-c1490b97-4e74-4d0a-8be0-e3bcc43022df.png)

Ever since release, Blu Scout's pants have had inconsistent coloring on his belt loops. This is leftover from when Blu scout originally had blue pants.

**Comment by TF2CutContentWiki** [comment]
Or just fix the pants so they're blue like in my report #3981

**Comment by condor00fr** [comment]
Fix the pants pls

**Comment by MikhailaTF** [comment]
> Or just fix the pants so they're blue like in my report #3981

There's quite a lot of evidence to believe that the rest of scout's pants were supposed to be blue indeed. I believe in the form of beta content, consistency with other classes and some (old?) HUD elements. I will dig up my sources later as I'm not able to do so right now.

**Comment by condor00fr** [comment]
the pants are blue in the ps3 version of th orange box, wich mind you has never been updated and still has old gameplay features like demo actually having a 6 pill clip for his grenade laucher, as for the icons today, aside from the player hud in game, every other instance is in BLU

**Comment by TF2CutContentWiki** [comment]
> > Or just fix the pants so they're blue like in my report #3981
> 
> There's quite a lot of evidence to believe that the rest of scout's pants were supposed to be blue indeed. I believe in the form of beta content, consistency with other classes and some (old?) HUD elements. I will dig up my sources later as I'm not able to do so right now.

The evidence of blue pants is right in that issue report I linked to. Here's the image in question showing the official PC version blue pants Scout from the leaked June 25th, 2007 build.
![176371621-bebcfe29-dcc5-47df-a125-6f8f8c9ce3e2(1)](https://user-images.githubusercontent.com/5123258/192992512-675cfa89-869e-4112-b96d-f1d5708d7cb6.jpg)

**Comment by Chickenman456** [comment]
Here's a workshop submission that fixes multiple texture problems, such as demoman's ambient occlusion on his vest.

https://steamcommunity.com/sharedfiles/filedetails/?id=1600180077

The reason why I link this is because it also includes fixed to numerous workshop items so they match scout's "new" blue pants.

**Comment by MikhailaTF** [comment]
> Here's a workshop submission that fixes multiple texture problems, such as demoman's ambient occlusion on his vest.
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=1600180077
> 
> The reason why I link this is because it also includes fixed to numerous workshop items so they match scout's "new" blue pants.

I genuinely wonder what whoever is working on TF2's stance towards such pretty self-contained and well-defined community-made "fixes/fix packs" are. Steam itself, but also outside of it such as here on github, is full of high quality fixes that would greatly benefit the game. I'm not a programmer myself either but it seems like almost all of the work has already been done.

**Comment by TF2CutContentWiki** [comment]
> > Here's a workshop submission that fixes multiple texture problems, such as demoman's ambient occlusion on his vest.
> > https://steamcommunity.com/sharedfiles/filedetails/?id=1600180077
> > The reason why I link this is because it also includes fixed to numerous workshop items so they match scout's "new" blue pants.
> 
> I genuinely wonder what whoever is working on TF2's stance towards such pretty self-contained and well-defined community-made "fixes/fix packs" are. Steam itself, but also outside of it such as here on github, is full of high quality fixes that would greatly benefit the game. I'm not a programmer myself either but it seems like almost all of the work has already been done.

They've accepted community fixes in the past. It just depends on what the fix *is* and what it fixes. I'd love for them to update the pants for the blue Scout, but then the few existing Scout pants-based cosmetics that sampled the beige pants color would all have to be updated to add a proper team colored blue version. And idk if they would accept a fix for those cosmetics made by someone who *isn't* the person who created those cosmetics. At the very least, this belt loop issue can be easily resolved without needing to modify those cosmetics. This is a pretty safe fix to add IMHO.

**Comment by Chickenman456** [comment]
I have created and submitted a fix to this on the workshop.

https://steamcommunity.com/sharedfiles/filedetails/?id=2880323729

**Comment by MikhailaTF** [comment]
Personally still a bigger fan of changing the pants to be consistent with the belt loops rather than the other way around, but let's see where this goes.

**Comment by kisak-valve** [comment]
Closing as a duplicate of #2289.

**Comment by Chickenman456** [comment]
> Closing as a duplicate of #2289.

Hi kisak. I personally disagree that this is a duplicate... This issue is more for calling the fix of the belt loop rather than fixing the entire pants.
