### ISSUE TITLE
[L4D2] [Linux] Freeze after few minutes

### ISSUE THREAD

**Issue by kozec** [ValveSoftware/Source-1-Games#432]
It's pretty simple - game works great, then suddenly freezes. No errors reported, console shows nothing unusual, sound doesn't loops, it just stops responding.

**Steps to reproduce:**
Play for some time. For example, I get freeze in half of 2nd level of No Mercy (while alarm rings)

**System Info:**
https://gist.github.com/kozec/5516843

**Console Log**
https://gist.github.com/kozec/5516873

**Crash dump**
https://dl.dropboxusercontent.com/u/134520/.nemaz_ma/crash_20130504102327_1.dmp

**Comment by kozec** [comment]
Considering that I opened this almost 3 years ago and considering I played several hundred hours after few updates, I'm fairly sure that issue is already fixed :)

**Comment by steamlinux** [comment]
I have freezes now(
