### ISSUE TITLE
[TF2] Add a feature to disable unusual effects

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4322]
This is lifted from FUNKe's video but I think it should be said here
Unusual effects are one of the biggest factors to TF2's rather poor performance on most machines. It's no surprise that as more unusuals get added, the more laggy the game gets with lower-end machines. Plus, since there's that rumor that they're upping the particle effect limit, there's no better time than now to suggest this.

How about a way to simply "toggle" all unusual effects, including cosmetic, taunt, and weapon effects.
This might sound really controversial to hear, but it really really needs to be addressed. I don't know if Valve is willing to add a feature as bold as this, but sometimes it doesn't hurt to just ask.

**Comment by kisak-valve** [comment]
Hello @ShadowMan44, this feature request is already being tracked at #4053. Closing as a duplicate.
