### ISSUE TITLE
[TF2][Feature Request] Allow halloween restricted cosmetics to be weared at night time

### ISSUE THREAD

**Issue by Wasmanr2** [ValveSoftware/Source-1-Games#4326]
_(If it wasn't obvoius, this request is directed towards valve casual servers and community servers)_

Allowing users to wear halloween restricted cosmetics whenever the **local server clock** hits 8 p.m. 
_(or whatever time is considered to be night time)_

Reasoning for that would be, that there is a decent amount of nice halloween cosmetics that _atleast I'm pretty sure of_  just lay around in everyones inventory only to be used when it's full moon _(1 day)_  or halloween _(1 month)_. 
_(excluding community servers)_

If we however be able to use those cosmetics whenever night time comes, that would as a side effect also increase the value of those cosmetics automatically.

If this request gets accepted it would be nice to have a console command to enable or to disable it 
_(something like tf_halloween_allow_night_time or whatever fits the name)_
_(And having the command enabled for valve casual servers and disabling it for community servers to let the server operators decide for themselfs)_

**Comment by Chickenman456** [comment]
How does this work with timezones?

**Comment by Wasmanr2** [comment]
Well i stated in my request that it should take the local server time, so timezones wouldnt matter at all.
A valve server that is located in the US will just use that clock, and a valve server located in EU for example would use that time.
Well unless all of the valve servers use UTC, then this probably wouldnt work out i guess, or would need extra work _(im not a programmer, im just making a request)_.

I belive, with a naive thought _(again im not a programmer)_ simply to tell the code to read what time it is on the current server and then just call to disable the halloween restriction until its morning and then enable the restrictions again.

**Comment by worMatty** [comment]
I think Hallowe'en cosmetics are meant to be a bit special so wearing them so often takes away that specialness. I think roughly once per month and one month per year is good enough, and it makes the full moon a more special event, like a micro Hallowe'en.

**Comment by Wasmanr2** [comment]
hmm fair enough
