### ISSUE TITLE
[TF2] Flamethrower ramp-up/"flame density" system bugs/issues

### ISSUE THREAD

**Issue by houseofgit** [ValveSoftware/Source-1-Games#4347]
Unlike most weapons, the Flamethrower's base damage is **scaled based on the oldest touching flame particle** instead of distance from the target. As well as this, a second caveat was added in a patch released on March 28, 2018, known to the community as the "Blue Moon Update" named after the cosmetic case released alongside the patch. This caveat makes it so **"Flame damage per second now ramps up based on density of flame encountered, up to 200%", with "Initial flame damage per second reduced by 50%, resulting in the max damage being unchanged".** As this system lacks an official name, I will refer to it as the "flame density" system. 

Both systems have multiple issues.

Despite the ramp-up system being technically based on particle lifetime, **it can practically always be considered to be linked to range.** With this in mind, it is strange that the damage of the flamethrower is **significantly dropped specifically at point-blank range**, where, in theory, it should be at it's apex. As well as this, the decision to base damage-per-tick scaling on the **oldest flame particle** leads to an issue where enemies being attacked with the flamethrower whilst pinned to the wall will only ever face **the minimum damage ramp-up.** This is because the flame particles become **stuck within the victim's hitbox,** preventing new particles from affecting damage ramp-up, as the oldest particle is **stuck in the victim' body until it expires,** at which point damage scaling is reassigned to another old particle that was once young, but o**nly began to effect damage much later due to the previous particle being stuck, thusly not ramping up the damage.** As stated in a developer commentary, the pyro is designed so that it forces it's players "to seek out enclosed areas and doorways" to be effective, thusly, rewarding players pinned against walls and trapped in corners by pyros makes little sense and thusly can be reasonably considered a bug. **This could possibly be solved by basing damage on the youngest particle in contact instead of the oldest.**

The "flame density" system, similar to the ramp-up system, claims to be based on "density of flame encountered" but is **undeniably linked to the time the enemy is being burnt more than anything.** With damage ticks being so frequent, the damage quantum's value being so low and the nature of the flamethrower particles, missed damage ticks are **practically always inevitable on moving targets.** Missed ticks naturally lead to lower damage output, as misses deal no damage, however, the "flame density" system **fully resets it's damage ramp-up on any miss,** discouraging missing even further, with players needing to consecutively hit particles to rebuild their damage ramp-up after a miss. 

To paraphrase, imagine a soldier's rocket launcher having a base damage of 50. Each hit will increase its base damage, peaking at 112. **However, this ramp-up will reset if you release the primary fire key at any point or you miss any of your shots.** This punishing design makes the flamethrower outstandingly weak in the face of other weapons even in close range, when again, as stated in the developer commentaries, "The Pyro is designed to be the best short-range combat class".

Alongside these issues, similar to ramp-up, the "flame density" system has many bugs, with it taking much longer than it should to ramp-up damage and at times resetting despite no missed ticks. These issues are, again, **most prevalent at point-blank range.** There also seems to be a hidden condition related to the edges of damage hitboxes where the ramp-up is reset. This extra caveat may be a further measure against unfocused fire in favour of tracking, however, it is also triggered by focus fire, only further discouraging it. Combine this with strange collision registration and this may be what causes the point-blank range bugs. **It could also possibly be the cause of hidden true damage scaling systems based on density,** however, this is impossible to confirm.

All flamethrowers also face the issue of **much higher self-damage being dealt by reflected projectiles on the pyro than should be applied,** however, a thread on this issue has already been made, so I won't go over it here.

https://github.com/ValveSoftware/Source-1-Games/issues/4298

Practically all bugs/issues discussed are put on display/better examined in this video.

https://www.youtube.com/watch?v=JqaI5LhNalk&t=111s

**Comment by kisak-valve** [comment]
Hello @houseofgit, these issues are already being tracked at #3631 / #3720 / #3722. In general it's better to track the various aspects of the flamethrower that seem off separately instead of creating a multi-issue issue report. Feel free to add your experience to the existing issue reports.

Closing as a duplicate.

**Comment by houseofgit** [comment]
oh, sorry- thanks for the heads up
