### ISSUE TITLE
[L4D2 Beta/Linux] Huge CPU utilization

### ISSUE THREAD

**Issue by thevintik** [ValveSoftware/Source-1-Games#435]
Even in main menu I got almost 100% CPU utilization on both cores by hl2_linux process. And it's not reducing when I start playing. In game it results not only in frequent FPS drops and freezes, but also after freeze it looks like vast "input lag" due to the input buffering. And maybe also there is a little constant "input lag". Graphics are fine, when I stay still in game, and nothing happens, FPS reaches values of 100+.

---

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6670 (AMD Catalyst™ 13.4 Proprietary)

```
Driver Version:  4.2.12217 Compatibility Profile Context 12.104
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6758
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,91" x 11,73"  (23,94" diag)
                                        53,1cm x 29,8cm  (60,8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  3953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  44884 Mb
    Largest Free Hard Disk Block:  13139 Mb

**Comment by kisak-valve** [comment]
This report is within expectations for CPU utilization of the game on Linux. Closing.
