### ISSUE TITLE
[TF2] Add in the "render target" stuff that Gmod has?

### ISSUE THREAD

**Issue by TF2CutContentWiki** [ValveSoftware/Source-1-Games#4353]
This is a wish list thing I've been hoping for for years as it would allow for some neat things in TF2 community servers.

Garry's Mod already has this feature and it allows for some really neat stuff to be done like those gmod Cinema servers.

I'm not 100% certain on this but there *could* be some potential security concerns when it comes to displaying web content through render targets. I've not heard of any issues of that sort arising from Gmod's version of the setup though.

**Comment by kisak-valve** [comment]
Hello @TF2CutContentWiki, please describe in detail what you'd like added to Team Fortress 2 under the assumption that the game developer who reads this has never seen this before, then give me a ping and I'll re-open this feature request.

**Comment by TF2CutContentWiki** [comment]
> Hello @TF2CutContentWiki, please describe in detail what you'd like added to Team Fortress 2 under the assumption that the game developer who reads this has never seen this before, then give me a ping and I'll re-open this feature request.

It's kind of tricky to explain as well as to find extended information on, but there are a few links I can provide on the topic:

- https://developer.valvesoftware.com/wiki/Adding_a_Dynamic_Scope - this has some cpp code for rendertargets
- https://wiki.facepunch.com/gmod/Global.GetRenderTarget
- https://wiki.facepunch.com/gmod/render.PushRenderTarget

And for what this can accomplish, if you were to check out this video;

https://youtu.be/PpVYU7PiBwc

Whenever you can see a YouTube video playing in the map, that's done through the RenderTarget system.

**Comment by TF2CutContentWiki** [comment]
@kisak-valve It is indeed a bit confusing to explain, but I found another video that shows off RTCamera and RenderTarget functionality in Source Filmmaker: https://youtu.be/VOeHkZsIJs4

Basically, you're pointing a "camera" at something and displaying what that camera sees on a surface. It's the same thing as the camera tool in Garry's mod.

If I'm not mistaken, I believe HL2 may also use RTCamera stuff for showing Dr. Breen on those displays in many levels. I'm not 100% certain though.

TF2 does not support this type of entity as it is. Having this entity added would allow for some neat map making opportunities as well as potentially allow for the creation of a GMOD Cinema-style server plugin for TF2 to be made.

The thing is, I don't know how the Gmod Cinema server add on handles the displaying of a webpage through the rendertarget texture. I probably should have looked into that before writing this suggestion.

Regardless of if it can display web content or not, it would be neat to have proper RTCamera/rendertarget support in TF2. We could do proper security cameras in maps with it.

**Comment by Ashetf2** [comment]
Security cameras can be done now that func_monitor works in TF2

**Comment by TF2CutContentWiki** [comment]
Feature was added in the December 1st update
