### ISSUE TITLE
[TF2] Add in point_worldtext entity from CSGO

### ISSUE THREAD

**Issue by TF2CutContentWiki** [ValveSoftware/Source-1-Games#4354]
The [point_worldtext](https://developer.valvesoftware.com/wiki/Point_worldtext) entity that CSGO has is pretty neat. Why can't Team Fortress 2 have nice things like that too? Please add this entity to TF2.

**Comment by Ashetf2** [comment]
I think this would require some changes that are related to Panorama, the new Source 2 UI for the CS:GO HUD, which isn't easy to do.

**Comment by Ashetf2** [comment]
There is a similar entity in HL2, `point_message`, that is oriented to the player, but it doens't work in TF2 (and CS:S). Maybe it can be ported? fixed?

**Comment by Ashetf2** [comment]
Update: It seems that in the vscript beta, point_worldtext has been backported.

**Comment by TF2CutContentWiki** [comment]
> Update: It seems that in the vscript beta, point_worldtext has been backported.

![archer-stop-my-penis-can-only-get-so-erect](https://user-images.githubusercontent.com/5123258/200100024-5e0c09ff-207f-47b4-9b57-1a2b6616690a.gif)

**Comment by Ashetf2** [comment]
Indeed, it was added. You can close this issue once the beta fully releases into the game

![hammerplusplus_wEkWFOm4cB](https://user-images.githubusercontent.com/63692647/200199536-5239cfce-e62a-498f-99c9-44fd896eae40.png)

**Comment by TF2CutContentWiki** [comment]
Closed as the feature has been added as of the msot recent update.
