### ISSUE TITLE
[TF2] Miami Rooster & Batter's Beak have inconsistent item types.

### ISSUE THREAD

**Issue by Chickenman456** [ValveSoftware/Source-1-Games#4356]
This is a simple (and relatively trivial) issue.

Every single bird head added prior to Scream Fortress 2021 has been labelled under "Bird Head" in the description. 

![image](https://user-images.githubusercontent.com/87006112/193631639-b8af779c-7bbe-4c22-905e-721e19b382ce.png)
![image](https://user-images.githubusercontent.com/87006112/193631696-463066b8-8455-49ea-bd39-c71f0758e168.png)
![image](https://user-images.githubusercontent.com/87006112/193631770-c76a8bc0-0ac0-4350-bea0-ff6239f0aafd.png)

However, the last two of these bird heads that were added were labelled under "Costume Piece"

![image](https://user-images.githubusercontent.com/87006112/193631978-97876b60-3f9f-4234-82ca-9567474558ca.png)
![image](https://user-images.githubusercontent.com/87006112/193632054-21e47e4f-0537-4060-a71d-8f7573e83fb4.png)

This creates an annoyance when auto-sorting a backpack, as those two heads don't get grouped next to the other heads.

**Comment by Chickenman456** [comment]
Hey, as of the October 11th patch - this has been fixed! @kisak-valve

**Comment by kisak-valve** [comment]
Closing per the last comment.
