### ISSUE TITLE
L4D2β crashes far into missions

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/Source-1-Games#436]
Haven’t found anything that seems to reproduce these crashes, game plays very well until it, er, doesn’t - instant crashes to desktop.

Had this in the shopping centre with the petrol cans in the first story.
response: CrashID=bp-f3e782e8-2ea1-4157-9423-006522130504
Got this during chapter 2 of ‘the passing’?
response: CrashID=bp-2882b56c-0f4a-4f46-9c5c-beaa62130504

sysinfo https://gist.github.com/johndrinkwater/4721913

**Comment by kisak-valve** [comment]
If anyone is still encountering crashes like these, please open a new issue report.
