### ISSUE TITLE
[TF2] Casual mapvote broken after scream fortress

### ISSUE THREAD

**Issue by SirBlockles** [ValveSoftware/Source-1-Games#4365]
![image](https://user-images.githubusercontent.com/3620019/194159443-82927453-efa0-4589-a02f-6862e3ff0e52.png)

after my last casual game from the scream fortress update, the mapvote came up with "map not found" entries. all players in the lobby mentioned seeing this, and once the first map was voted for, the server immediately disconnected all of us and told us the match was over.

this happened on cp_spookeyridge.

**Comment by MikhailaTF** [comment]
confirmed to be fixed since treacherousfiend's last comment, ticket can be closed

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
