### ISSUE TITLE
[TF2] Feature Request: Implement an internal tf_forced_holiday for Summer.

### ISSUE THREAD

**Issue by popnz** [ValveSoftware/Source-1-Games#4367]
Heya! I was wondering if there was a chance for us to have a new internal holiday set up for the Summer update. 

This would allow Summer to develop as an update and behave similarly to the Halloween and Smissmas updates, allowing the opportunity for the following features:

- Summer Effects becoming available across cases within Holiday, just like Halloween/Smissmas.
- Summer Taunt Effects being added
- Summer Maps, which can lead into adding new maps into the universal map pool like some picks have during Smissmas.
- Summer War Paint case, although an event isn't needed for this, we are yet to get a Summer War Paint case despite it suiting this update better than any other. 

This could also give a warranted deadline for the Summer case, starting on the 1st of July and ending on the 7th of August, giving creators something to work towards instead of guessing when the Summer update will come.

**Comment by AzureAzel** [comment]
This would be nice. There are a ton of War Paints and Cosmetics that don't fall within the Winter / Halloween aesthetic, so this would give the community a chance to get some extra variety out of accepted workshop submissions.

**Comment by shadlamppost** [comment]
I would love to see summer themed main menu backgrounds as well.

**Comment by AwesomeCoder412412** [comment]
Well I guess out of all the things in this issue tracker, this feature actually got added. Mark it as solved?

@kisak-valve

**Comment by kisak-valve** [comment]
Closing per the last comment.
