### ISSUE TITLE
[TF2] Scream Fortress 2022 Map Stamps all say "Capture The Flag Map"

### ISSUE THREAD

**Issue by treacherousfiend** [ValveSoftware/Source-1-Games#4368]
All of the Map Stamps for the new maps added in Scream Fortress 2022 say that the maps are CTF maps, when only two of the maps (Crasher and Helltrain) are
![image](https://user-images.githubusercontent.com/46549454/194193255-e1d42a33-ea2f-42ea-aab0-6d9732595f45.png)
![image](https://user-images.githubusercontent.com/46549454/194193261-61ac2776-5396-46c1-9d11-149ba4931ab7.png)
![image](https://user-images.githubusercontent.com/46549454/194193264-7b3ec225-503b-468c-bb9c-9e75f97d6f8d.png)
![image](https://user-images.githubusercontent.com/46549454/194193274-542b85b1-ba9c-4533-90e9-709cafb8965a.png)

**Comment by Ashetf2** [comment]
Helltrain is CTF too

**Comment by treacherousfiend** [comment]
oh my bad, updating the issue post with that

**Comment by treacherousfiend** [comment]
Fixed in the 10/6/22 Update
