### ISSUE TITLE
[TF2] Add in a new special event cosmetic item to mark a recent special occasion

### ISSUE THREAD

**Issue by TF2CutContentWiki** [ValveSoftware/Source-1-Games#4373]
To commemorate the first-ever occasion of a cosmetic item being ***completely*** broken on release, I think you should add a new special cosmetic that is given to every player, consisting of a miniature ERROR model, attached to a jiggleboned spring, attached to a hard hat.

Here is my incredibly good mockup of what it should look like. It took me a thousand hours in Photoshop, and didn't take me 3 seconds with my finger on my phone's Gallery app.

![Screenshot_20221006-050120_Discord](https://user-images.githubusercontent.com/5123258/194433581-f5c6771d-951b-4301-a96e-ca4ac0b0cd14.jpg)

*seriously though, I think this would be a fun little wink at the broken cosmetic item that was just fixed*

**Edit:** I'll flesh it out a bit more even;
- Item name: "404: Hat Not Found"
- Item level: 404 (cmonnnn do it)
- Item description: "I don't even know what happened. Someone get Gabe on the phone, ***NOW***"

**Comment by kisak-valve** [comment]
Hello @TF2CutContentWiki, this reads more like a needless jab and the Team Fortress 2 team than a serious suggestion.

**Comment by TF2CutContentWiki** [comment]
Legitimately wasn't intended as a jab 😔 These types of issues happen to every programmer, even me. Apologies.
