### ISSUE TITLE
[TF2] Download stuck at 89%

### ISSUE THREAD

**Issue by Wosheereal** [ValveSoftware/Source-1-Games#4378]
As title says, download is stuck 89% and is telling me that it's gonna take a very long time to finish.

**Comment by Wosheereal** [comment]
This clearly not a network issue as I am running on a ethernet connection.

**Comment by Razoldon** [comment]
Everyone is encountering this issue. Your concern is valid, hopefully it will be fixed soon.

**Comment by crowodough** [comment]
same issue here, hope it gets fixed

**Comment by Wosheereal** [comment]
UPDATE: My download is at 97%

**Comment by Wosheereal** [comment]
UPDATE: I think this is fixed?
