### ISSUE TITLE
[All Platforms] English only

### ISSUE THREAD

**Issue by OliverSwift** [ValveSoftware/Source-1-Games#438]
I have Portal on my Mac and I'm not testing the Beta on it. There was a recent update and I use to have it in french. My hunch is that it is related to current port (sorry if it is not).
This seems to be same issue as I reported #396 but it's not, please do not consider it as duplicate.
(See discussions on hub, others have reported same issue: http://steamcommunity.com/app/400/discussions/0/828937979207436733/ ).

 -Thx

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
