### ISSUE TITLE
[TF2] Mann Co Store halloween case preview bug

### ISSUE THREAD

**Issue by me1053** [ValveSoftware/Source-1-Games#4380]
Hovering over any of the halloween cosmetic cases appears to show appears to show the first skin of that model regardless. I noticed this when hovering over the new case that it was showing last years with the red candles. This isn't happening with war paints or smissmas cases as far as I can tell. All the spider cases from 2016-2020 show the 2016 red spider as well.
![20221008101639_1](https://user-images.githubusercontent.com/46284242/194700137-f6417d98-2171-404f-bd7d-5cabe70ca215.jpg)
![20221008101646_1](https://user-images.githubusercontent.com/46284242/194700141-fa7edc38-eccb-4a90-bcde-ba7bb040db9d.jpg)

**Comment by kisak-valve** [comment]
Hello @me1053, per "Fixed some cosmetic cases not showing the correct skins in the Mann Co. Catalog" in the [2022-10-11](https://www.teamfortress.com/post.php?id=144283) Team Fortress 2 update, please retest this issue.

**Comment by me1053** [comment]
Yes, it's been fixed as of the October 11, 2022 update
