### ISSUE TITLE
[TF2] Soulmill ignores red team on hell portal

### ISSUE THREAD

**Issue by Thespikedballofdoom** [ValveSoftware/Source-1-Games#4382]
Only blue can enter the portal, red just gets slightly hovered in the air and healed. koth_sawmill_event

**Comment by kisak-valve** [comment]
Hello @Thespikedballofdoom, per "Updated koth_sawmill_event > Fixed RED team portal to the underworld not enabling" in the [2022-10-11](https://www.teamfortress.com/post.php?id=144283) Team Fortress 2 update, please retest this issue.

**Comment by Thespikedballofdoom** [comment]
All good.
