### ISSUE TITLE
TF2 HHH Burning effect missing

### ISSUE THREAD

**Issue by HHHJrr** [ValveSoftware/Source-1-Games#4383]
Ever since 2015 October in the Invasion or Scream Fortress update(i only noticed it much later but seems around that time) The Horseless Headless Horsemann Halloween boss lost the purple flame effect on it's body.
![HorsemannFlame](https://user-images.githubusercontent.com/114434387/194727697-be572708-5487-4433-a2ff-b44fcb1300ae.png)
I didn't see the change mentioned anywhere or anyone noticing the change, but the image above has a clear difference.

**Comment by MikhailaTF** [comment]
Perhaps this was done to reduce visual clutter and strain on resources? Although the old HHH with the flames present looks so much cooler indeed.

**Comment by Whurrhurr** [comment]
it was an undocumented change and to be frank, i don't get why they did it, monoculus still has purple flaming bits on him. it just makes the horsemann look really plain. now he just looks like a scaled up demoknight with a footstep spell equipped.

**Comment by condor00fr** [comment]
It's probably a bug or an oversite, pls bring it back!

**Comment by condor00fr** [comment]
Documented this on both English and French versions of the Wiki. Listed it as a bug

**Comment by kisak-valve** [comment]
[TF2] Horseless Headless Horseman body fire particle has been broken due a coding mistake.

Issue transferred from https://github.com/ValveSoftware/Source-1-Games/issues/5035.
@FriskTheFallenHuman posted on 2023-07-13T17:52:23:

This issue is kind of related to #4383 but with a solution: after the 2015 update the HHH lost its body flame, it was speculated that it was because of valve removing it, but in reality, is it was by mistake here's a brief [explanation:](https://steamcommunity.com/sharedfiles/filedetails/?id=2997356338)

> For some unknow reason after the invasion updated The Horseless Headless Horseman lost its body
> flame particle, while it was speculated that it was removed because of visibility reasons, in reality this was by
> mistake, since the particles of it do exist albeit it only exists for a fraction of a frame when the entity spawns, the fix
> was from moving it from the clientside's Spawn() function:

> ```CPP
> void C_HeadlessHatman::Spawn( void )
> {
> \t// Some other code
> 
> \tif ( !m_ghostEffect )
> \t{
> \t\tm_ghostEffect = ParticleProp()->Create( "ghost_pumpkin", PATTACH_ABSORIGIN_FOLLOW );
> \t}
> 
> \t// Some other code
> }
> ```

> to ClientThink() since that's how to properly spawn a particle client-side in the engine.

> ```CPP
> void C_HeadlessHatman::ClientThink( void )
> {
> \t// Some other code
> 
> \tif ( !m_ghostEffect )
> \t{
> \t\tm_ghostEffect = ParticleProp()->Create( "ghost_pumpkin", PATTACH_ABSORIGIN_FOLLOW );
> \t}
> 
> \t// Some other code
> }
> ```

This means that at some point the particle mas mistakenly moved from ClientThink() to Spawn() meaning the particle only would be live for a fraction of a frame.

**Comment by HueyCan** [comment]
The latest [Scream Fortress update](teamfortress.com/post.php?id=210366) seems to have fixed HHH's fire particles not showing up
">Fixed ghost_pumpkin effect not playing correctly for the Horseless Headless Horsemann"
Retest needed

**Comment by HHHJrr** [comment]
Yea it seems to be fixed, for me atleast.

**Comment by Whurrhurr** [comment]
can confirm this has been fixed, Burnt Horsemann on plr_hacksaw_event looks a little weird now though, some extra ghost_pumpkin effects are on one of his hands. 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/33162051/e084507f-05ed-436c-8ccc-e1ba2f5bfe13)
