### ISSUE TITLE
[TF2] New voting is not bindable

### ISSUE THREAD

**Issue by LastTalon** [ValveSoftware/Source-1-Games#4388]
The June 21, 2022 update seems to have changed the method of voting. It appears that the new command for this is `vote <vote index> <option>`, however its unclear how one would even attempt to bind this to a key correctly since the voting index is transient (I'm not 100% clear on how to discover the index myself).

**Comment by kisak-valve** [comment]
Hello @LastTalon, this issue is already being tracked at #4251. Closing as a duplicate.

**Comment by LastTalon** [comment]
> its unclear how one would even attempt to bind this to a key correctly

> I'm not 100% clear on how to discover the index

@kisak-valve Specifically these parts of the issue don't seem to be tracked at all.

**Comment by kisak-valve** [comment]
I'm not seeing enough of a separation to warrant fragmenting the discussion of this issue across multiple issue reports. It reads like two perspectives of the same issue. 

Feel free to add your experience to the older issue report.
