### ISSUE TITLE
[L4D2 Beta] Z-sorting is shaky

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Source-1-Games#439]
[screenshot here](http://cloud-2.steampowered.com/ugc/559847901385955865/0E060228757446DA0410C000A9E49AD510A6B1AF/)

This does not occur on any other native Linux source game, and it also did not occur on the Wine-emulated L4D2 (non-beta) as far as I can remember.

<pre>Processor Information:
    Vendor:  GenuineIntel
    Speed: 3400 Mhz
    2 logical processors
    1 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Fedora release 18 (Spherical Cow)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.7-201.fc18.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11303000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD CEDAR

    Driver Version:  2.1 Mesa 9.1
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x68f9
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 13.31" x 10.63"  (17.01" diag)
                                            33.8cm x 27.0cm  (43.2cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: SigmaTel STAC9750,51
    
Memory:
    RAM:  3261 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  688888 Mb
    Largest Free Hard Disk Block:  445387 Mb</pre>

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue on an up to date system, please open a new issue report.
