### ISSUE TITLE
[TF2] Hud match status not hiding during freezecam screenshots

### ISSUE THREAD

**Issue by Thespikedballofdoom** [ValveSoftware/Source-1-Games#4396]
With the option set, all of the hud except the match status, which is the container with the round timer and team class info, is hidden. Going through my own screenshots it seems to have a small chance of actually hiding it. `hud_freezecamhide 1`

![image](https://user-images.githubusercontent.com/43627353/195273117-94037e1c-7f4c-4adb-813f-3ea133c8a21d.png)

**Comment by kisak-valve** [comment]
Hello @Thespikedballofdoom, per "Fixed the match status HUD not being hidden during freezecam screenshots" in the [2022-10-18](https://www.teamfortress.com/post.php?id=154639) Team Fortress 2 update, please retest this issue.

**Comment by Thespikedballofdoom** [comment]
5 tested freezecams hid 5 huds, seems all fixed.
