### ISSUE TITLE
[TF2] Corrupted map names in server browser

### ISSUE THREAD

**Issue by nosoop** [ValveSoftware/Source-1-Games#4397]
#2768 appears to have been implemented in the Team Fortress 2 update on 2022-10-12, but appears to be implemented incorrectly, corrupting map names:

![image](https://user-images.githubusercontent.com/6760398/195500646-e7005114-e9e0-4fac-92ea-2ec70a70d2d4.png)

**Comment by Joshua-Ashton** [comment]
Thanks for the report, will be fixed in the next update.

**Comment by nosoop** [comment]
Confirmed that today's update fixed this issue.
