### ISSUE TITLE
[TF2][Feature Request] sv_allowtextmode cvar 

### ISSUE THREAD

**Issue by SinFour** [ValveSoftware/Source-1-Games#4400]
Many TF2 bots run TF2 in textmode so that they take up less resources, adding a server convar which allows or does not allow users to connect to the server with the -textmode launch option would hopefully make hosting bots far less efficient.
My one worry about this is that I remember a cheater talking about how they can still bypass the sv_cheats command, even after [the patch on June 21st.](https://imgur.com/EYQ9GpJ) I worry that they would be able to get around this easily, but I'm not knowledgable enough to be sure.

**Comment by worMatty** [comment]
Presumably if a cheater is able to modify the client they will be able to prevent it from communicating to the server that it's running in text mode.

**Comment by kisak-valve** [comment]
Hello @SinFour, this feature request is already being tracked at #3901. Closing as a duplicate.

**Comment by Ashetf2** [comment]
> Many TF2 bots run TF2 in textmode so that they take up less resources, adding a server convar which allows or does not allow users to connect to the server with the -textmode launch option would hopefully make hosting bots far less efficient. My one worry about this is that I remember a cheater talking about how they can still bypass the sv_cheats command, even after [the patch on June 21st.](https://imgur.com/EYQ9GpJ) I worry that they would be able to get around this easily, but I'm not knowledgable enough to be sure.

Cheaters have always been able to bypass sv_cheats
