### ISSUE TITLE
[TF2] The "itemtest" map crashes the game when opened

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#4420]
Title. Go into the game and type "map itemtest" into console and it crashes the game. Any other map works fine.

**Comment by Thespikedballofdoom** [comment]
It works fine for me, I tried the itemtest command on another map and it didnt crash me there either.

**Comment by JoriKos** [comment]
I removed my custom files and it looks like something is messing with it, I've asked a friend
