### ISSUE TITLE
[TF2] PLR Bonesaw has broken visibility settings on "Fuel Oil" parts of map 

### ISSUE THREAD

**Issue by Kofiy** [ValveSoftware/Source-1-Games#4422]
Map `plr_hacksaw_event` has broken visibility settings on "Fuel Oil" parts of map (both from the RED and BLU side). Due to that you can be in situations where you can't see what's happening bellow OR you can abuse it to see through walls OR you can be shot by invisible sentry. 
Depending on graphics setting you just see skybox or you see that duplicating effect.

My system Information: https://gist.github.com/Kofiy/8b97a1e41d1fc238e3e4040bbf2c59fe
(First screenshot isn't mine, atm I don't have system information/TF2 settings of user who did that)

![image](https://user-images.githubusercontent.com/37085105/196971109-c10ef5ff-b3fc-47de-b817-07ae86689953.png)
![20221020160303_1](https://user-images.githubusercontent.com/37085105/196971862-e2238c95-fa3a-4fef-960b-0ca338456df4.jpg)
![20221020160305_1](https://user-images.githubusercontent.com/37085105/196971869-2a9f4bfe-8b4d-4640-a3b6-b4a3ae3513ee.jpg)
![20221020160308_1](https://user-images.githubusercontent.com/37085105/196971877-24d28d0d-e6b1-47d6-85d4-6705c157a681.jpg)
![20221020160310_1](https://user-images.githubusercontent.com/37085105/196971885-3fdd24a3-85c5-4dc4-ad3c-862f36e59e9f.jpg)

**Comment by kisak-valve** [comment]
Hello @Kofiy, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.
