### ISSUE TITLE
[TF2] Ghosts on Graveyard aren't using dispenser-ghost model

### ISSUE THREAD

**Issue by Kofiy** [ValveSoftware/Source-1-Games#4431]
From the release of the map until recently ghosts (downed players) were using special dispenser model (screenshot from TF2 wiki). But lately, due to some visual bug, the ghosts are using default (but small) model.

![image](https://wiki.teamfortress.com/w/images/6/6e/Downed_Player.jpg)
![image](https://user-images.githubusercontent.com/37085105/197337147-ae11e093-b857-4248-a5eb-e8bf75eaf149.png)

My system Information: https://gist.github.com/Kofiy/8b97a1e41d1fc238e3e4040bbf2c59fe

**Comment by Ashetf2** [comment]
Do HUD textures also break when this happens?

**Comment by Kofiy** [comment]
I joined graveyard and ghosts were using that model... 
But I also noticed that sometimes ghosts are spawned big, and only after multiple frames they're scaled down.
Both of these bugs need some more looking into why and when it happens, and since it's Graveyard...

**Comment by FlaminSarge** [comment]
@Kofiy it looks like this issue still occurs occasionally, unsure if this should be closed quite yet.

@Ashetf2 HUD textures did in fact break for me when this occured, pretty consistently.

**Comment by Ashetf2** [comment]
@FlaminSarge then this issue is related to (if not a duplicate) #4214
