### ISSUE TITLE
[TF2] Add older uncraftable promo items to the crafting pool

### ISSUE THREAD

**Issue by TF2CutContentWiki** [ValveSoftware/Source-1-Games#4436]
There's a lot of older promo items which are currently uncraftable (and untradable) that could be added to the crafting pool.

The Sam & Max items for example are a good candidate. Stahlhelm and Pikotka. Dadliest Catch. Any genuine items that are no longer available, but that you also cannot craft.

Would be nice to be able to craft them.

Edit: The Batman items! I want a batman cape 😏

**Comment by matty4kek** [comment]
I don't think batman items would slide as craftables, as they're purchasable on Mannco store, which makes Valve a good buck since It's the only way besides trading to obtain them.
The rest however make sense.

**Comment by TF2CutContentWiki** [comment]
Whoops this was suggested before.

**Comment by TF2CutContentWiki** [comment]
This was suggested before. Whoops!
