### ISSUE TITLE
[TF2] syringes guns Visual clipping bug in first prson

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#4439]
Back when the game released, the syringe guns,'s syringes would fire from the muzzle of the gun, ( the syringes only being a visual "effect" so to speak)but now it dosn't anymore (firing under the muzzle) due to a bug wich causes a bunch of client visual only issues, like the syringes not sticking on walls or not rendering at all at certain occasions.

Shounic,s video about the issue and the many viewmodel weirdnesses it caused should do a better way to explain this issue than I could ever do:(
https://www.youtube.com/watch?v=BAs-ph7lqqA

**Comment by Ashetf2** [comment]
Fixed in today's update.

> Fixed syringes triggering false hits on the client when minimal view models are enabled or a custom view model FOV is set

**Comment by kisak-valve** [comment]
Closing per the last comment.
