### ISSUE TITLE
[L4D2][Linux] Invisible water

### ISSUE THREAD

**Issue by mattyy1hp** [ValveSoftware/Source-1-Games#444]
I've found something strange in the map Dark Carnival. It looks like invisible water.
I don't remember if there should be water so please tell me if this is a bug.

---

![2013-05-04_00011](https://f.cloud.github.com/assets/3092320/462871/5c318d50-b4ec-11e2-80ac-6f2a6b2a30bb.jpg)

![2013-05-04_00013](https://f.cloud.github.com/assets/3092320/462872/61928d4e-b4ec-11e2-8f32-f79a325d6718.jpg)

![2013-05-04_00014](https://f.cloud.github.com/assets/3092320/462873/655951e2-b4ec-11e2-87e9-bd45cc5006b1.jpg)

![2013-05-04_00012](https://f.cloud.github.com/assets/3092320/462879/dfb4186e-b4ec-11e2-920b-e88d87615fa1.jpg)

---

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Mutter
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6520G

```
Driver Version:  4.2.12173 Compatibility Profile Context 12.10.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9647
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3430 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  581188 Mb
    Largest Free Hard Disk Block:  134705 Mb

Installed software:

Recent Failure Reports:
    Sat May  4 14:25:27 2013 GMT: file ''/tmp/dumps/assert_20130504162501_1.dmp'', upload yes: ''CrashID=bp-50e52ca9-8337-4ad8-8e4b-560d12130504''

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
