### ISSUE TITLE
[TF2] Players can use the "extendfreeze" command to watch their killer play the game

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#4443]
Title. This allows a gameplay info leak (Medic's position, for example) to the enemy team.

https://user-images.githubusercontent.com/63692647/197449923-ae90019c-30d1-49d6-ab47-54d7a315be16.mp4

**Comment by Wasmanr2** [comment]
If this command gets patched, that would prevent us from watching potential cheaters in our own team.
And yes i use this command to spectate if someone is  cheating from either team.


And i don't think this command matters in a "casual" scene.
If your thought was going towards the 3rd party comp scene then it would be probably better to inform these parties instead.

**Comment by worMatty** [comment]
How does it prevent you spectating your own teammates while dead?

**Comment by Wasmanr2** [comment]
It wouldn't prevent me from spectating, it would make it more tedious.
Since i wouldn't be able to increase my own respawn timer.
And note that some cheaters aren't that obvious, so it takes a bit of time to ensure to not call out someone legit.

It also comes over more convincing when you can tell your own team that you at least spectated the guy for a minute, which may clear any uncertainty that your team would have when calling a votekick.

**Comment by FrozenDragon0** [comment]
I really don't think this is a problem in casual, competitive mode however this command should be blocked.

**Comment by jh34ghu43gu** [comment]
> If this command gets patched, that would prevent us from watching potential cheaters in our own team.
And yes i use this command to spectate if someone is cheating from either team.

I've never seen anyone use this for anything other than this; it would be a W for cheaters if this command got removed. If this is some actual gameplay breaking thing for comp players (I don't think sacrificing your respawn time for positional information is worthwhile /shrug) then maybe just fix it from leaving the freezecam state (the actual freezecam still) if used before you're put into spectate mode. Or blacklist it in comp mode like Dragon said.

**Comment by KiwifruitDev** [comment]
As of the October 27th, 2023 patch, this has been fixed:

> - Fixed using the extendfreeze client command to continue spectating enemy players after being killed

https://www.teamfortress.com/post.php?id=211509

**Comment by rootino** [comment]
You better revert this change.
If cheaters weren't rapid ingame and if we weren't completely reliant on community self-moderation tools removing this from casual wouldn't be a huge issue.
But as it stands now this will only allow cheaters to get away with cheating more. 
Nothing has been fixed.

**Comment by RednotePL** [comment]
Please revert this "fix", it was one of the last reliable ways to check if someone was cheating.

**Comment by Ashetf2** [comment]
Damn I also started to use the command to check players. Valve plz revert and only apply it to Comp and Tournament pls? :(

**Comment by Platina6978** [comment]
Please revert this change. As people stated above, this one was of the only 'methods' we had in casual to more closely inspect suspicious actors.

**Comment by Kruphixx** [comment]
Agree with others. Either this fix should be reverted or simply spectator mode should be added to Casual.

**Comment by TheLivingM3m3** [comment]
I have never seen anybody use or used the command to gain information on the enemy team as there isn't really an incentive in casual play to do so. The loss of this command will just benefit cheaters as the anticheat is nigh useless on its own. The players have to do everything themselves and without being able to spectate their teammates it will be impossible.

**Comment by Nesmoen** [comment]
Patch tools to expose cheaters > Anti cheat efforts

**Comment by shockpast** [comment]
> Damn I also started to use the command to check players. Valve plz revert and only apply it to Comp and Tournament pls? :(

This is hilarious.

**Comment by Nitroxyz** [comment]
This is really bad. Extendframe is the only way to definitively detemine if someone is hacking. This will potentionally allow cheaters to overtake TF2 again

**Comment by KimmyTF2** [comment]
Just allow players to spectate normally again. Meet Your Match and its consequences still haunt us to this day.

**Comment by UntiIted** [comment]
Agreed with everyone else, there is now no way to verify cheaters and there's so many of them in casual lobbies already
