### ISSUE TITLE
[L4D2/Linux] Microphone Doesn't Work

### ISSUE THREAD

**Issue by PyGuy95** [ValveSoftware/Source-1-Games#445]
Hey guys! Great work so far with L4D2! Only a few issues here and there, including this: my microphone works in Team Fortress 2 and other games, but not L4D2.

Here's my system info: http://pastebin.com/raw.php?i=rNTBzg9Z

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/steam-for-linux/issues/2390#issuecomment-25583412. If you are still experiencing this issue, please open a new issue report.
