### ISSUE TITLE
[TF2] Farmageddon voice line "he's closing back up, lookout!" after pumpkin opens

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4450]
I don't know if it's just me, or if on Farmageddon there's a strange issue regarding the voice line. It's not even that bad of an audio issue but it might confuse new players a little.

**Comment by treacherousfiend** [comment]
This should hopefully be fixed after today's [update](https://www.teamfortress.com/post.php?id=155500), if you want to retest
