### ISSUE TITLE
[Portal Beta - Linux] Game minimizes from time to time

### ISSUE THREAD

**Issue by Lord-Avallon** [ValveSoftware/Source-1-Games#447]
This is exactly what happens, I am playing and suddenly the game minimizes, so I have to go to the Unity bar, click on the icon and maximize it again, it happens from time to time as said, it happened 3, 4 or 5 times during my gameplay of around 1 hour.

Here are my specs: https://gist.github.com/Lord-Avallon/4521727

**Comment by kisak-valve** [comment]
Closing per the last comment.
