### ISSUE TITLE
[TF2] Improve moderation for Something Special for Someone Special, Name Tags, Chat

### ISSUE THREAD

**Issue by Chickenman456** [ValveSoftware/Source-1-Games#4474]
I think it's no secret to anyone that's played the game that seeing hate speech is inevitable, maybe even on a daily basis.

Bots and players spam slurs and hateful language via text chat. There is a Steam censor that can be toggled, but otherwise players are allowed to spam slurs as much as they please.

Name tags have always been abused for this since their conception. Weapons and cosmetics with slurs/offensive language in their names, you get the deal. However, Something Special for Someone Special has the capability to project any text the user pleases to _every single player_ that has the game launched. This is often used for nefarious purposes. 

I don't have a specific solution for this issue, but it's something I'd like to see Valve tackle in the future. Whether it be more censoring or something like automatic temp chat bans. I certainly thing the name tag system has been long overdue for an overhaul.

**Comment by kisak-valve** [comment]
Hello @Chickenman456, this issue is already being tracked at #4034. Closing as a duplicate.
