### ISSUE TITLE
[LINUX] Raw Mouse Input seems to make the playermodel go crazy in TF2 Inventory

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/Source-1-Games#4487]
Title says it all, lol.
https://streamable.com/7c2oml
(Streamable link because it is more than 10MB. Video recorded is on the VScript Beta test but this happens in base TF2 as well.)

**Comment by kisak-valve** [comment]
Hello @Munoida, this issue is already being tracked at #95. Closing as a duplicate.
