### ISSUE TITLE
[L4D2] Swamp Fever / Plank Counter: cannot press button on a ferryboat.

### ISSUE THREAD

**Issue by dimgel** [ValveSoftware/Source-1-Games#449]
Gentoo amd64, single player.

**Comment by kisak-valve** [comment]
Hello @dimgel, are you still experiencing this issue?

**Comment by dimgel** [comment]
No idea, haven't played L4D2 since long ago. I suppose this issue can be closed if no one else voted.

**Comment by kisak-valve** [comment]
Thanks for letting me know. Closing.
