### ISSUE TITLE
[TF2] Add "streamer mode"

### ISSUE THREAD

**Issue by Jokaaga** [ValveSoftware/Source-1-Games#4508]
The banal "streamer mode", for streamers and players. Removing avatars and replacing them with the team logo "BLU" and "RED", removing nicknames and replacing them with the type "enemy red spy", removing images from "Conscious Objector", "Photo Badge", "Flair!", "Clan Pride", removing changed names and descriptions of weapons etc. They can also be made separate settings in the advanced settings.

**Comment by Jokaaga** [comment]
> Duplicate of #4249 and #4212 ?

I didn't know, sorry ¯\_(ツ)_/¯

**Comment by kisak-valve** [comment]
Closing in favor of the older feature requests.
