### ISSUE TITLE
[TF2] Please add "Probed" to the King of The Hill maplist in casual

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4527]
So Probed is that one KoTH map that's in the "specialty" section because... of the explosive barrels and the little UFO section that you can go into.

Why do those things make it "special"? I mean, we have Breadspace which is just a Payload map with the exploding objects already in casual! If Breadspace isn't unique enough for specialty with the exploding pustules, neither is Probed.

**Comment by condor00fr** [comment]
Lol true

**Comment by ShadowMan44** [comment]
Request was fulfilled in the Summer 2024 update.
