### ISSUE TITLE
[HL2] Half-Life 2-Based Games crashing upon launch on Linux

### ISSUE THREAD

**Issue by yeenyeenyeen** [ValveSoftware/Source-1-Games#4529]
Half-Life 2, Its episodes, Lost Coast, Deathmatch, Portal and Half-Life Source seem to be crashing when launching via Linux. This is the error message I saw in the terminal:

`/run/media/maxintosh/BitzDrive/SteamLibrary/steamapps/common/Half-Life 2/hl2.sh: line 87: 25340 Illegal instruction (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

The issue is probably that I am running a Pre-AVX CPU, [as this seemed to be an issue with DOTA 2 for a while before it got patched](https://github.com/ValveSoftware/Dota-2/issues/2003), now it seems to affect Half-Life 2-based games.\

System Info gist [here](https://gist.github.com/yeenyeenyeen/74e16553eefc3613642791d770df3808)

UPDATE: Seems to affect Portal 1 as well.

**Comment by kisak-valve** [comment]
Hello @yeenyeenyeen, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

I suspect this is the same issue as #3875 instead of being an AVX cpu instruction.

**Comment by yeenyeenyeen** [comment]
> Hello @yeenyeenyeen, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.
> 
> I suspect this is the same issue as #3875 instead of being an AVX cpu instruction.

Okay, I have included it in the post

**Comment by kisak-valve** [comment]
Thanks, as suspected, this is the same issue as #3875. Feel free to add your experience to the older issue report.

Closing as a duplicate.
