### ISSUE TITLE
Can't open console

### ISSUE THREAD

**Issue by jethrogb** [ValveSoftware/Source-1-Games#453]
I get the following error message when I press the backtick/tilde key:

```
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL mailing list <sdl@libsdl.org> X11 KeyCode 0 (-8), X11 KeySym 0x0 ((null)).
```

My keyboard layout is US international with dead keys. The console does show up when I start with -toconsole. I can then bind another key like so:

```
bind f12 toggleconsole
```

I can confirm that I get the same error message when using other SDL2 programs. I have sent an e-mail to the email address mentioned in the error message: http://lists.libsdl.org/pipermail/sdl-libsdl.org/2013-May/088296.html . There does not seem to be much activity on the SDL front to fix this.

**Comment by kisak-valve** [comment]
Re-assigning to the SDL dev.

**Comment by Yetoo1** [comment]
@kisak-valve I can't reproduce this issue.

**Comment by kisak-valve** [comment]
Closing per the last comment.
