### ISSUE TITLE
[TF2] Feature request to help make Sniper aimbots not as prevalent

### ISSUE THREAD

**Issue by TF2CutContentWiki** [ValveSoftware/Source-1-Games#4530]
Lock the Sniper class behind a paywall and make players have to pay $50 to unlock the class. And that's not a one-time charge either. $50/month to use the Sniper class.

Bot problem solved, you're welcome.

**Comment by kisak-valve** [comment]
Putting a pay wall for a single character class in a free to play game is not a viable solution.

**Comment by TF2CutContentWiki** [comment]
> Putting a pay wall for a single character class in a free to play game is not a viable solution.

Sure it is. You (the royal "you", meaning Valve) paywalled text chat. MvM has some sort of paid aspect to it. Opening crates is paywalled in a sense by needing to buy keys. How would paywalling an OP class in the game not be viable? C'mon, be honest. We all know what Valve is about...
![36c](https://user-images.githubusercontent.com/5123258/203828917-2941ffd5-6c98-4f92-b306-3a7e9228f331.jpg)
