### ISSUE TITLE
custom sound issue in TF2...

### ISSUE THREAD

**Issue by SgtDerp** [ValveSoftware/Source-1-Games#454]
I added some sounds to the correct folders in TF2. But for some reason, some of the sounds are either high pitched or really slow. I added other sounds as well, but they worked fine. I'm not sure what to do. The main problem is coming from some custom vo sounds. Need help

**Comment by Wasmanr2** [comment]
Still having that issue ?
Custom VO sounds have problems with sv_pure 1/2 they wont work properly.

**Comment by Wasmanr2** [comment]
@kisak-valve you may close this since there is no feedback of the user.

Also since this is only happening on sv_pure 1/2 which already got reported.

**Comment by kisak-valve** [comment]
Closing in favor of #1635.
