### ISSUE TITLE
[TF2] F7 (Report abusive game server) button is no longer functioning

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#4542]
Hello,

I join community servers from internet tab and frequently there are servers that spoof ping, shows up as 30/32 players and 30 ping, but once I join the ping is 300 - 400 and that makes game unplayable. Neither me or other people want to spend hour trying to find server with real low ping so I sent report.

![areport2](https://user-images.githubusercontent.com/9932099/204576375-dc240c9b-44fa-426e-88d8-1edb49f17549.png)

I used F7 menu to report server and no action was taken, server still up on same ip after month
I believe the current report system is broken on the valve backend and may need taking a look at

- Thanks

this seems to be relevant to this thread: https://github.com/ValveSoftware/Source-1-Games/issues/4484
and it seems like due to ping spoofing all those servers are in top5 on gametracker
https://www.gametracker.com/search/tf2/?search_by=map

**Comment by Tiagoquix** [comment]
@kisak-valve OP has turned into a ghost, and the abuse report system works for me.
