### ISSUE TITLE
[TF2] [MvM] Major bug causing softlocks in missions after the December 1st, 2022 update.

### ISSUE THREAD

**Issue by jh34ghu43gu** [ValveSoftware/Source-1-Games#4552]
Someone wanted me to make an issue on this, personally I haven't played since the update but it seems enough people are reporting it that I feel it's justified to make the report.

Robots are refusing to spawn on certain waves thus causing a soft lock since there is no way to lose and no way to win. The friend that reported w2 cataclysm claims that no bots could spawn after a restart vote. 

This is happening on valve and community servers.

Waves affected as reported by others:
* w2 cataclysm last 10 heavies
* w3 empire escalation last 3 blast soldier squads (support scouts still spawned)
* w6 metro malice sometime shortly after the giant pyros and before the 2nd round of crit soldiers ( [img](https://steamuserimages-a.akamaihd.net/ugc/1977673131991132787/332A1D92F9127C83B21BEAF2AF3539F9EB053C7E/) ) Edit: forgot to mention support scouts also still spawned
* Unknown waves and missions on bigrock and mannworks

Copy paste from the person who wanted the issue made, did not have time to dig into the claims

> Seems like this issue has existed since Tough Break but I'm willing to bet it's only resurfaced because of the following changes made in yesterday's update:Implemented logic_eventlistener for listening to game events from Hammer logicAdded the ability to pass parameters and delay to MvM populator actions
> There's an old thread on the community discussions where Sigsegv goes into further detail: 
> https://steamcommunity.com/app/440/discussions/1/611696927911238805/?ctp=132#c494632768633582025

[Reddit thread with a video](https://www.reddit.com/r/tf2/comments/zb2swj/mvm_bugged_since_the_last_update/)

**Comment by Joshua-Ashton** [comment]
Hello!

I managed to reproduce this bug, however on a completely different wave.

It seems like it's pretty random, so I have a hunch there is some uninitialized memory somewhere that is now hitting on a different value due to the addition of the ENT_SCRIPTDESC to the CTFBot/CTFPlayer classes.

As a workaround for now, if you lose the wave by letting a Support bot deploy the bomb you should be able to then complete the wave.

I will look into this further, thanks for reporting!

**Comment by wtb10** [comment]
This happened to me two nights ago on Metro Malice last wave. The wave progressed normally except for 7 of the steel fist heavies that are supposed to spawn from the top. We let supports cap three times and the same thing happened on each attempt.

I experienced another bug on Empire Escalation wave 3 a few days ago. Each of the three gates was closed at wave start and the bots spawned behind gate A but were trapped by the door. We were forced to restart the game and then finished without issues. This was the first time this had happened to me in ~500 tours of Two Cities.
![image](https://user-images.githubusercontent.com/114440519/205473076-4ba4bd88-4e44-49ec-8168-ddfca8b10fd2.png)

**Comment by jh34ghu43gu** [comment]
Some corrections and more instances

> The friend that reported w2 cataclysm claims that no bots could spawn after a restart vote.

This was a misunderstanding/miswording on my part, bots did spawn but it stopped again "very quickly" on w1.


W5 Empire also triggered, they did not specify on what bots.


> I experienced another bug on Empire Escalation wave 3 a few days ago.

This is unrelated, happened before the update.


> As a workaround for now, if you lose the wave by letting a Support bot deploy the bomb you should be able to then complete the wave.

While it is the only solution us players have for now, anyone who reads this should know that this is inconsistent since it requires support bots that can carry the bomb, and many players report it fails again on subsequent attempts. It is likely two fails indicates the mission will always get stuck and it would probably be best to find a new server or wait for the fix.

Something I though of but can't look into right now is the bots failing to spawn appear to be gate/push bots? IE not focused on the bomb. Again, I dont have time to investigate that for all these claims but it would appear to hold up for w6 mm and w2 cataclysm (iirc the heavies/soldiers are push bots).

Thanks for the quick response and looking into Joshua.

**Comment by exactsameproblem** [comment]
Hello,
I can confirm that this bug appears randomly, even whith a paid Mann up ticket!
Robots stop spawning and the suggested solution is not working when no robots appear at all, or just Spies and Sentry Busters like we had today (they don't deploy the bomb). 
Also the last remaining robots were 2 Big soldiers, and they were supposed to deploy a bomb.

**Comment by CopCorvette** [comment]
Still happening, tried to do a 2 player vs machine on a private server

Empire escalation w2

Black Box Soldier squad getting stuck at spawn
8 Demoknights remaining does not spawn at all

w3

Robots stop spawning after engineer ambush

**Comment by Joshua-Ashton** [comment]
I believe we have tracked this down and I should be able to get a fix soon.

I am currently away right now though, but I will try to get something shipped soon:tm:

**Comment by FlavioF6799** [comment]
It's happening after 26 days from december 1st

Empire Escalation W5

Giant FnF Scouts stopped spawning after 4 Giant FnF scouts deployed 4 times

**Comment by Joshua-Ashton** [comment]
At this time, while I appreciate it, I dont think more reports of this issue are needed.

It should be fixed in the next update, when that ships (holidays forgiving).

**Comment by kisak-valve** [comment]
Hello, per "Fixed Mann vs. Machine bots failing to spawn" in the [2023-01-05](https://www.teamfortress.com/post.php?id=178064) Team Fortress 2 update, please retest this issue.

**Comment by jh34ghu43gu** [comment]
Hasn't happened to me on 4 different servers and no one else encountering it on my friends list. Thanks for the fix!
