### ISSUE TITLE
[TF2] [Linux] Game crashing before Valve intro on wayland with NVIDIA 525.60.11

### ISSUE THREAD

**Issue by SpidFightFR** [ValveSoftware/Source-1-Games#4553]
The game crashes directly to destkop when loading it on wayland. We can hear the valve intro for barely a few milliseconds before closing.

I tried reinstalling the game, removing my launch arguments... Nothing worked...
Thanks by advance for your help !

**Comment by SpidFightFR** [comment]
I managed to [capture](https://user-images.githubusercontent.com/60798703/206008905-03ba2e12-abfc-4e40-ac59-9641167d41f2.mp4) the error. How can i solve this issue please ?


Sorry for the lack of information, but i lack of information myself. It just stopped working after the update...

**Comment by NotSoMewwo** [comment]
Exact issue has happened to me on KDE Wayland Arch Linux on NVIDIA, TF2 starts up and then immediately crashes after a few seconds of black screen with no error message when I use NVIDIA (Optimus), it does work on the Integrated Intel GPU.

Also just tested it with Portal 1 and it neither launches too on NVIDIA. 

TF2 and Portal 1 is installed in an external drive, and also I use mastercomfig for TF2 but I removed it and it still crashes.

I have the -novid in the launch options and it still causes crashes. 
`prime-run %command% -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime `
I had launched Steam on the console and it gave the output I attached in the file alongside with a dump file on TF2, but I can't neither decipher on the cause.

[SteamLauncherLog.txt](https://github.com/ValveSoftware/Source-1-Games/files/10199161/SteamLauncherLog.txt)
[assert_20221209215430_34.txt](https://github.com/ValveSoftware/Source-1-Games/files/10199162/assert_20221209215430_34.txt)
[crash_20221209215411_2.txt](https://github.com/ValveSoftware/Source-1-Games/files/10199163/crash_20221209215411_2.txt)

Also I  think its the same issue that #4574 just posted.

**Comment by Mihuy1** [comment]
Same here, unable to launch the game just crashes after a few seconds..

**Comment by kisak-valve** [comment]
For reference, @NotSoMewwo's attached minidump is DUMP_REQUESTED in crashhandler.so (uninteresting) and a SIGSEGV in libnvidia-glcore.so.525.60.11, which reads like a video driver issue.

Is anyone seeing this issue with an older NVIDIA driver version?

**Comment by kisak-valve** [comment]
[TF2] crash after nvidia update to 525.60.11 and last tf2 update

Issue transferred from https://github.com/ValveSoftware/Source-1-Games/issues/4574.
@3d0 posted on 2022-12-10T03:33:41:

OS: Arch
Kernel: 6.0.11-zen3-xanmod1-1
Processor: AMD Ryzen 5 5600X 6-Core Processor
Graphics: NVIDIA Corporation GM204 [GeForce GTX 970]
Desktop Manager: Gnome4 over Wayland

After updating TF2 and my Nvidia driver, TF2 started crashing at start, creating a 54~ mb coredump

corectldump output and trace:

```     PID: 3671 (hl2_linux)
           UID: 1000 (<username>)
           GID: 1000 (<username>)
        Signal: 11 (SEGV)
     Timestamp: Sat 2022-12-10 00:04:00 -03 (2min 17s ago)
      Command Line: $'/home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/hl2_linux' -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -windowed -noborder
    Executable: /home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/hl2_linux
    Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-hyper-1957.scope
          Unit: user@1000.service
     User Unit: app-gnome-hyper-1957.scope
         Slice: user-1000.slice
     Owner UID: 1000 (<username>)
       Boot ID: 15866528643040e595180897d925a305
    Machine ID: 076f71673adc408c93e48cfe27ce58f0
      Hostname: iblipvii
       Storage: /var/lib/systemd/coredump/core.hl2_linux.1000.15866528643040e595180897d925a305.3671.1670641440000000.zst (present)
     Size on Disk: 54.9M
       Message: Process 3671 (hl2_linux) of user 1000 dumped core.
                
                Stack trace of thread 3671:
                #0  0x00000000f62d2197 n/a (libnvidia-glcore.so.525.60.11 + 0x14d2197)
                #1  0x00000000f627e8a7 n/a (libnvidia-glcore.so.525.60.11 + 0x147e8a7)
                #2  0x00000000f75e5854 n/a (libGLX_nvidia.so.0 + 0x44854)
                #3  0x00000000f7611980 glXSwapIntervalEXT (libGLX_nvidia.so.0 + 0x70980)
                #4  0x00000000f301bbfc n/a (/home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0 + 0xbabfc)
                ELF object binary architecture: Intel 80386
```

The steam output was

```
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 440, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 440, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\\0/home/<username>/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/<username>/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -windowed -noborder\\0
Game process added : AppID 440 "/home/<username>/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/<username>/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -windowed -noborder", ProcID 3667, IP 0.0.0.0:0
chdir /home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/<username>/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/<username>/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to Completed with ""
pid 3669 != 3668, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/<username>/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/<username>/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system supports the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
OpenGL: NVIDIA GeForce GTX 970/PCIe/SSE2 4.6.0 NVIDIA 525.60.11 (4.6.0)
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_ARB_buffer_storage: AVAILABLE
GL_EXT_texture_sRGB_decode: AVAILABLE
Installing breakpad exception handler for appid(gameoverlayui)/version(20221201223736)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Using Breakpad minidump system. Version: 7708610 AppID: 440
Setting breakpad minidump AppID = 440
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/<username>/.local/share/Steam/linux32/steamclient.so' OK.
Game process updated : AppID 440 "/home/<username>/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/<username>/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -windowed -noborder", ProcID 3671, IP 0.0.0.0:0
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198017689858 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198017689858
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1669935987)
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 4194304, Total Avail: 4194304, Current Avail: 3388416
GL_MAX_SAMPLES_EXT: 32
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 4650 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 4650 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: DISABLED
ERROR: ld.so: object '/home/<username>/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20221210000400_2.dmp[3761]: Uploading dump (out-of-process)
/tmp/dumps/crash_20221210000400_2.dmp
crash_20221210000400_2.dmp[3761]: Finished uploading minidump (out-of-process): success = yes
crash_20221210000400_2.dmp[3761]: response: CrashID=bp-ddc833c9-3b33-4368-8692-6d73a2221209
crash_20221210000400_2.dmp[3761]: file ''/tmp/dumps/crash_20221210000400_2.dmp'', upload yes: ''CrashID=bp-ddc833c9-3b33-4368-8692-6d73a2221209''
pid 3761 != 3758, skipping destruction (fork without exec?)
/home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh: line 72:  3671 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game process removed: AppID 440 "/home/<username>/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/<username>/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/<username>/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -windowed -noborder", ProcID 3671 
ThreadGetProcessExitCode: no such process 3758
ThreadGetProcessExitCode: no such process 3671
ThreadGetProcessExitCode: no such process 3670
ThreadGetProcessExitCode: no such process 3668
```

**Comment by NotSoMewwo** [comment]
I downgraded my NVIDIA drivers to 515.76 in Linux kernel 6.0.12 and it now works.

In the meantime, if you want to play TF2 and you are on Arch Linux, get the [Arch Linux downgrade package from the AUR](https://aur.archlinux.org/packages/downgrade) 
Then `sudo downgrade nvidia-dkms nvidia-utils nvidia-settings lib32-nvidia-utils libxnvctrl` and downgrade every package to 515.76, make sure they are all equal version. Also make sure to use nvidia-dkms instead of nvidia even if you are using the normal kernel.

**Comment by 3d0** [comment]
I confirm that downgrading the nvidia driver to 520.56.60 was enough to make the game run (thanks @NotSoMewwo )

**Comment by SpidFightFR** [comment]
I tried to run the game with the latest nvidia driver (`525.60.11`)  but using zink (`env __GLX_VENDOR_LIBRARY_NAME=mesa MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink MANGOHUD=1 %command%` as a launch argument).

The game started but stops refreshing the screen... I'm starting to think it has something to do with ToGL.

**Comment by Xagoz** [comment]
Issue still occurs.
I would like to note that, on Arch Linux with the latest NVIDIA Drivers in the official repo running under GNOME Wayland (GDM), `env __GLX_VENDOR_LIBRARY_NAME=mesa MESA_LOADER_DRIVER_OVERRIDE=llvmpipe GALLIUM_DRIVER=llvmpipe MANGOHUD=1 %command%` causes the game to function ""FINE"". **In case you are unaware, LLVMPipe is a software renderer, yes the game will boot like normal but 9 fps in the menu isn't very practical.** In my case, using GNOME on Xorg causes TF2 to run just fine. Honestly Valve, please just add DXVK support to TF2 instead of leaving us with _toGL_ and old SDL.

I should also note that launching the game with `XDG_SESSION_TYPE=wayland SDL_VIDEODRIVER=wayland %command%` results in a popup saying that wayland is not available (which is incorrect, I am in a wayland session) followed by the app exiting without showing a window.

**Comment by SpidFightFR** [comment]
The sdl wayland error happens cuz the sdl dot_so file in the gamefiles is largely outdated. If you download lib32_sdl2 using pacman, and make a symlink from /usr/lib32/sdl2.so to the game bin folders, the issue no longer happens but the game insta crashes.

**Comment by SpidFightFR** [comment]
Tho i agree: just adding dxvk and a newer sdl driver in the game files would save all the issues we have. It’s literally a free solution.

**Comment by SpidFightFR** [comment]
That's highly probable, but as long as you don't launch a multiplayer game, you should be fine (must be taken with a grain of salt).

**Comment by 3d0** [comment]
any update on this?

**Comment by SpidFightFR** [comment]
Nope, both valve and nvidia stay silent about this.

**Comment by BluCobalt** [comment]
I have the same issue: KDE, Wayland, 525.60.11, Fedora.
This is the dmesg output:
```
[ 3099.332292] hl2_linux[15779]: segfault at 20 ip 00000000f3cd2197 sp 00000000ff8f09f0 error 4 in libnvidia-glcore.so.525.60.11[f2800000+2663000]
[ 3099.332317] Code: 8b 10 85 d2 0f 84 81 00 00 00 a1 ec 3f e6 f4 65 8b 30 85 f6 74 21 8b 76 48 85 f6 75 0d eb 18 8d 74 26 00 8b 76 44 85 f6 74 0d <3b> 3e 75 f5 83 be a8 00 00 00 13 76 3c 8b 5a 04 85 db 75 0c eb 4b
```
Replacing the game's bundled version of SDL2 by pinning fedora's version and launching with `SDL_VIDEODRIVER=x11 ` makes the window open but no sound is outputted and the game crashes immediately.

**Comment by kinnounko** [comment]
Same issue here, on sway, Wayland, Nvidia 525.78.01-1, Arch.
Also happens for: 
* Garry's Mod: I get "wayland not available."
* Half-Life 2: The game starts, gets past the Valve logo, but crashes at the main menu.

**Comment by SpidFightFR** [comment]
> Garry's Mod: I get "wayland not available."

Because the version of SDL they use for Gmod and TF2 is too old to have wayland support.
On games like splitgate, it barely works with nvidia, but the game launches.

**Comment by 3d0** [comment]
With nvidia 525.85 still crashing with almost the same problem

**Comment by SpidFightFR** [comment]
And still no updates from either nvidia or Valve.

**Comment by getchoo** [comment]
> > The sdl wayland error happens cuz the sdl dot_so file in the gamefiles is largely outdated. If you download lib32_sdl2 using pacman, and make a symlink from /usr/lib32/sdl2.so to the game bin folders, the issue no longer happens but the game insta crashes.
> 
> My concern with that is the potential of VAC tripping because you're effectively replacing one of the game's libs. If anyone has an official insight on whether or not this is an issue let us know.

(obligatory "i'm not official") changing the built in library can be a little messy and is not a great way to go about this. a better alternative would be to use the steam runtime's [library pinning feature](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/ld-library-path-runtime.md#the-scout-runtime) (tutorial [here](https://docs.mastercomfig.com/latest/os/linux/#fixing-bugs-with-newer-sdl2)) as that is a lot less likely to cause any VAC triggers. if you want to play it really safe, you can use the runtimes version instead of the one from your system's package manager by symlinking libSDL2 in `~/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/` to `~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32/`, though you most likely won't run into any issues either way

**Comment by Hasshu** [comment]
I'm experiencing what appears to be the same issue with both Portals, while also getting obscene amounts of SELinux alerts related to `abrt-action-gen`, `gdb`, and `hl2_linux` (the latter trying to pull an `execheap`; #2734?).

That's on Fedora Linux 36, KDE Plasma 5.26.4 (Wayland), NVIDIA RTX 2060 SUPER (driver 525.85.05). Oh, and Steam Flatpak — if that makes any difference.

**Comment by SpidFightFR** [comment]
> I'm experiencing what appears to be the same issue with both Portals, while also getting obscene amounts of SELinux alerts related to `abrt-action-gen`, `gdb`, and `hl2_linux` (the latter trying to pull an `execheap`; #2734?).
> 
> That's on Fedora Linux 36, KDE Plasma 5.26.4 (Wayland), NVIDIA RTX 2060 SUPER (driver 525.85.05). Oh, and Steam Flatpak — if that makes any difference.

In all honesty, i left the boat and went to team red. I just gave up all hope of changes to this situation.

Tho it would be unfair to come here just to say that, so here's a tip:
For portal(s), L4D2 and CSGO, you should use the `-vulkan` launch argument as it solves all the issues with nvidia and wayland.
This whole situation is sad to see, the game used to just work, then anti-aliasing just broke, and then the whole game...

Anyways, it's the end of the line for me. I sincerely hope you all guys will find what you seek.  ❤️

**Comment by Hasshu** [comment]
@SpidFightFR Thanks for the tip and the kind words! The game does work now, though it begins stuttering after a while (fixed by relaunching).

And yeah... Mid-range RDNA 3 can't come out soon enough. Anyhow, back to the NoVideo land for now...

**Comment by JohnFlowerful** [comment]
Before upgrading to 530, note that refresh rates higher than 60Hz aren't working. See https://github.com/NVIDIA/open-gpu-kernel-modules/issues/471

**Comment by SpidFightFR** [comment]
The issue seems to be fixed so i'll close this issue tab. (i switched to AMD anyways so i can't replicate this issue anyways)
