### ISSUE TITLE
ap-sap crashes servers

### ISSUE THREAD

**Issue by sasadsadas** [ValveSoftware/Source-1-Games#4566]
when you sap a mini-sentry with ap-sap game just crashes

**Comment by sasadsadas** [comment]
me is spy here

**Comment by JoriKos** [comment]
This actually doesn't just happen with the Ap-sap, I've so far tested it with the regular Sapper, Ap-sap, and Red-Tape Recorder on a local itemtest server (typing "map itemtest" in console). All of them have crashed my game so far, so I'd say this needs an urgent fix.

**Comment by jh34ghu43gu** [comment]
> Fixed a server crash related to the Spy sapping buildings

From the update just now

**Comment by kisak-valve** [comment]
Closing as fixed in the [2022-12-07](https://www.teamfortress.com/post.php?id=166973) Team Fortress 2 update.
