### ISSUE TITLE
(Portal 1) Ending Credits don't display correctly on 16:10 displays

### ISSUE THREAD

**Issue by CricetoYT** [ValveSoftware/Source-1-Games#4576]
I know Portal 1 isn't listed here but this is the only place that made sense to post this in. Please let me know if there's a better place I can post this issue. 

I was playing Portal on Steam Deck and got to the credits and noticed the ASCII art in particular was noticeably displaced, it was off-screen to the bottom right. Although the whole thing looked pretty off. I assume this is because all the text in the credits are based on resolution and aspect ratio and they only considered 16:9.

**Comment by FrozenDragon0** [comment]
This is the right place for Portal 1 as it is part of the source 1 games so, + there's a label for it.

**Comment by kisak-valve** [comment]
Hello @CricetoYT, this issue is already being tracked at #3867. Closing as a duplicate.
