### ISSUE TITLE
Team Fortress 2 crashing on start

### ISSUE THREAD

**Issue by Mihuy1** [ValveSoftware/Source-1-Games#4577]
Team Fortress 2 (native) crashes after a few seconds. And in the 2 seconds you see a black screen and a small window that's just black on the lop left.

To reproduce this I just have to run the game.

Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  ROG STRIX B550-F GAMING
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 5600X 6-Core Processor             
    CPU Family:  0x19
    CPU Model:  0x21
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4650 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Nobara Linux 36 (Thirty Six) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.0.10-201.fc36.x86_64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12201003
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20221019.0

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 525.60.11
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x10de
    DeviceID:  0x1e84
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 4480 x 1440
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  15899 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Total Hard Disk Space Available:  398976 MB
    Largest Free Hard Disk Block:  363892 MB

Storage:
    Number of SSDs: 3
    SSD sizes: 1000G,512G,250G
    Number of HDDs: 0

**Comment by SpidFightFR** [comment]
Hey, it's the same issue as #4553. If i had to guess, i would say it's because of Nvidia drivers.

**Comment by kisak-valve** [comment]
Hello @Mihuy1, are you using an X based or Wayland based GNOME session?

**Comment by Mihuy1** [comment]
Hey @kisak-valve, I am using Wayland

**Comment by kisak-valve** [comment]
Thanks, that makes your symptoms consistent with #4553. Feel free to add your experience to the older issue report.

Closing as a duplicate.
