### ISSUE TITLE
[TF2 Request] Vulkan Rendering API?

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/Source-1-Games#4585]
Like a lot of other Source 1 games, Portal 2, Left 4 Dead 2, CS:GO, and Half Life 2 and its episodes.

I feel like Team Fortress 2 should also get the Vulkan Rendering API. It would be awesome.

**Comment by kisak-valve** [comment]
Hello @Munoida, this feature request is already being tracked at #2844. Closing as a duplicate.
