### ISSUE TITLE
All Source Games on Linux client with the Valve/Source intro blackscreen and freeze at start

### ISSUE THREAD

**Issue by Brucifer** [ValveSoftware/Source-1-Games#459]
It's a black screen instead of the Valve startup clip, and the "Steam in-game interface" prompt appears but its frames clip over itself. The rest of the game is the black screen, although I can hear the music. It seems I can't click on anything. The Steam in-game interface works to an extent, although somewhat slowly.

Video:
http://www.youtube.com/watch?feature=player_embedded&v=iH7BvaAyNe4

**Comment by kisak-valve** [comment]
Closing due to lack of feedback.
