### ISSUE TITLE
[TF2] Players that are Gassed with the Gas Passer do not count as wet?

### ISSUE THREAD

**Issue by Porkyspal** [ValveSoftware/Source-1-Games#4592]
Gassed players should count as wet in the game.

**Comment by ChrisHansenWithDatelineNBC** [comment]
If it's in regards to working with the Neon Annihilator. It's probably because gasoline is not a good conductor of electricity. AFIK gasoline is made of hydrocarbons like isooctane. Hydrocarbons by themselves don't contain free electrons, nor charges, so it is not conductive.

**Comment by Arbitz** [comment]
> If it's in regards to working with the Neon Annihilator. It's probably because gasoline is not a good conductor of electricity. AFIK gasoline is made of hydrocarbons like isooctane. Hydrocarbons by themselves don't contain free electrons, nor charges, so it is not conductive.

... This is team fortress 2, there are things that make FAR less sense. I feel for gameplay reasons gas players should be considered wet! It's something that should've been done back when the weapon was added 5 years ago.

**Comment by jh34ghu43gu** [comment]
This has been fixed `Fixed the Neon Annihilator not getting crit-attacks when hitting players covered with gas`

**Comment by JoriKos** [comment]
Can confirm, this works now. Issue can be closed.

**Comment by agrastiOs** [comment]
Can confirm as well. :)

**Comment by kisak-valve** [comment]
Closing fixed in the [2024-07-18](https://www.teamfortress.com/post.php?id=223066) Team Fortress 2 update.
