### ISSUE TITLE
Games minimise on losing focus

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/Source-1-Games#462]
Happens with Portal, Left4Dead2, others.

I run the game fullscreen on my primary monitor, and use my secondary for irc, twitter, mumble and the usual crap. If I open the overlay with shift-tab, I expect to be able to leave the first monitor with my cursor, interact with a window on the second screen without the game minimising.

**Comment by l33tlinuxh4x0r** [comment]
> Just to note.
> `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%`
> Works perfectly when putting it in launchoptions

I tried that several times. It still minimizes when alt tabbing for me... must be a gnome setting?
