### ISSUE TITLE
[TF2] Valve, It's time to let Free to play's speak once again. Please

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#4628]
I recently managed to convinced some friends (Overwatch players) to try and play tf2 fro the first time, and while the game was great, the complete inablility to do as much as call for a medic was a bit of turn down for them, and so could be for so many other potential newcomers to the game.

While theses restrictions where put in place when back all thoses years ago when the bots used to be the biggest threat to the game, they aren't as prominent as they used to be, so theses restrictions are no longer needed.

One of the biggest issues with theses is that being unable to talk in a team based multiplayer game is really not great game design, and while it was promised back then that theses changes would be removed once the bot situation was properly handled, this was yet to be adressed.

Free to play players are tf2's future, so it's only natural to help them get setteled in.

Thank you for your time
-A fellow tf2 enjoyer.

**Comment by kisak-valve** [comment]
Hello @condor00fr, this issue is already being tracked at #4177. Closing as a duplicate.

**Comment by condor00fr** [comment]
fair enough
