### ISSUE TITLE
[TF2] Prevent the weapon holster penalty/bonus bypass

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#4630]
Not sure if this is intentional design or not, but it's possible to bypass a weapon's switch speed penalty/bonus entirely by switching to a weapon without a holster penalty/bonus and then switching to another one.

For example, the Gloves of Running Urgently has a 50% holster speed penalty. This is bypassed entirely if you switched to your Secondary and then immediately switch to your Primary (given that your Secondary has no holster speed penalty either), meaning that on every weapon this stat is entirely useless.

It can be unintentionally triggered by simply scrolling instead of using the numbers, but it can also be intentionally done and give an advantage in fights. The same thing applies to the holster speed bonus, which may accidentally remove this benefit from a weapon. I'd suggest making the game check if you fully took out a weapon before removing the holster speed penalty, though I'm not sure if this is the most efficient way or even a realistic way to do it.

**Comment by kisak-valve** [comment]
Hello @JoriKos, this issue is already being tracked at #2125. Closing as a duplicate.
