### ISSUE TITLE
[TF2] [Sort of feature request] Please pay more attention to TF2

### ISSUE THREAD

**Issue by chexo3** [ValveSoftware/Source-1-Games#4631]
Having VScript is huge of course, but it still feels like we’re probably not going to get much help from Valve or the TF Team besides adding community content once in a while around holidays. I’d love to see more active work on TF2, and I feel like the community is raring to go for any new stuff. 

Hell, maybe some Valve employees working on Source 2 projects could tinker with the TF2 codebase a bit to understand how Source 1 worked. Might make porting Source 1 content easier to wrap their head around, and maybe they’ll fix some bugs or make something small for us to have fun with.

**Comment by condor00fr** [comment]
Only time will tell, friend. Only time will tell.

**Comment by kisak-valve** [comment]
Hello @chexo3, this issue report is invalid because it doesn't have a specific, actionable issue to ponder.

**Comment by chexo3** [comment]
That's fair...
