### ISSUE TITLE
[TF2] Add knockback immunity to robots that haven't dropped down yet

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#4654]
It's entirely possible to stop bots from entering the zone where they're killable by continuously airblasting, making it impossible to complete the mission. A simple fix for this could be to add knockback immunity while they haven't dropped down yet.
It's not a bug or anything, but rather a fix to griefing.

I couldn't find anything about this posted before, apologies if it has been.

**Comment by AzureWoof** [comment]
I think I made a post about it a while back, and I also commented about it here: https://github.com/ValveSoftware/Source-1-Games/issues/4620#issuecomment-1367751466

This is an extremely important issue that needs fixing. I'd also suggest for the knockback immunity to stay active for a short amount of time after the robots leave their spawn zone so people can't just immediately airblast them back in once they leave spawn.

**Comment by FrozenDragon0** [comment]
> I think I made a post about it a while back, and I also commented about it here: [#4620 (comment)](https://github.com/ValveSoftware/Source-1-Games/issues/4620#issuecomment-1367751466)
> 
> This is an extremely important issue that needs fixing. I'd also suggest for the knockback immunity to stay active for a short amount of time after the robots leave their spawn zone so people can't just immediately airblast them back in once they leave spawn.

The immunity should last for 5 seconds in my opinion, at least that way the robots can still be killed or a giants case, heavily damaged whilst the griefing player can't do anything temporarily.

**Comment by JoriKos** [comment]
> I think I made a post about it a while back, and I also commented about it here: [#4620 (comment)](https://github.com/ValveSoftware/Source-1-Games/issues/4620#issuecomment-1367751466)
> 
> This is an extremely important issue that needs fixing. I'd also suggest for the knockback immunity to stay active for a short amount of time after the robots leave their spawn zone so people can't just immediately airblast them back in once they leave spawn.

Would it be possible to make barriers one-way? Once they drop down they can't be knocked back into it?

Alternatively, having robots in the pre-dropdown section for too long should automatically kill them (i.e. 2 minutes). Would also solve the linked issue.

**Comment by Ashetf2** [comment]
Today's update: "Added check to make Mann vs. Machine invaders immune to pushback while leaving their spawn". Please retest

**Comment by condor00fr** [comment]
Can confirm it's working properly

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
