### ISSUE TITLE
[TF2] [request] Please make the auto-spin when inspecting items a toggle

### ISSUE THREAD

**Issue by scapegoat4** [ValveSoftware/Source-1-Games#4656]
_IGNORE THIS, I am a very stupid person_

Either that or don't make it spin at all, like CS:GO. It's a tiny difference but it's annoyed me quite a bit over the years trying to take screenshots, etc. I apologize if this has been posted before, I probably missed a relevant search term if so

**Comment by TeutonicTea** [comment]
`tf_item_inspect_model_auto_spin 0`

There is also `tf_item_inspect_model_spin_rate` to control how fast the item spins.

**Comment by scapegoat4** [comment]
> `tf_item_inspect_model_auto_spin 0`
> 
> There is also `tf_item_inspect_model_spin_rate` to control how fast the item spins.

See, this is why I haven't posted anything before. Because I'm 100% stupid. I'm sorry for wasting your time
