### ISSUE TITLE
[TF2] Crash "Xlib: sequence lost"

### ISSUE THREAD

**Issue by reDBo0n** [ValveSoftware/Source-1-Games#4668]
I've noticed after updating my Arch install TF2 crashes after joining a match, regardless of using Casual matchmaking or creating a Local Server.
When starting steam via a Terminal the whole console spams "Xlib: sequence lost (0x10000 > 0x1cf8) in reply type 0xc!", with the latter Hex changing every message, even when not playing TF2, but just hovering the cursor around the Steam window.
Downgrading lib32-libx11 from the newest 1.8.3-1 down to 1.8.2-2 (and a restart of Steam) fixes the problem.

(Shortend) System specs:
```
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 5800X3D 8-Core Processor           

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.1.3-273-tkg-bmq
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20221019.0

Video Card:
    Driver:  AMD AMD Radeon RX 5700 (navi10, LLVM 14.0.6, DRM 3.49, 6.1.3-273-tkg-bmq)
    Driver Version:  4.6 (Compatibility Profile) Mesa 22.3.2
    Primary VRAM: 8192 MB

Memory:
    RAM:  32011 MB
```

**Comment by kisak-valve** [comment]
Hello @reDBo0n, this reads like https://github.com/ValveSoftware/Dota-2/issues/2218. It looks like Arch's `lib32-libx11` package didn't get https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/176 and https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/177 fast tracked into the build like the 64 bit `libx11` package.

Regardless, this is a regression in the upstream libX11 library and needs to resolved upstream.

This is not a game bug.

**Comment by reDBo0n** [comment]
For everyone, who stumbles upon this (closed) issue:

lib32-libx11 1.8.4-1 seems to not have this problem anymore.
