### ISSUE TITLE
[TF2] Syringes no longer create impact models or impact particles, due to no longer colliding with the world.

### ISSUE THREAD

**Issue by BreavyTF2** [ValveSoftware/Source-1-Games#4669]
This issue is related to the latest patch which fixed some issues with the syringe gun. This does not apply to the crusaders crossbow.

**Comment by BreavyTF2** [comment]
Wait it's even worse, syringes no longer collide with the world.

**Comment by AzureWoof** [comment]
I've tested this on both official servers and ones that I've set up myself. I haven't really noticed anything odd with the syringes. They leave impact models and stick into surfaces like normal. Could you possibly specify which syringe gun(s) you used and what map(s) you tested this on?

**Comment by BreavyTF2** [comment]
was just caused by cl_fasttempentcollision being a high number.
