### ISSUE TITLE
[L4D2 Beta] yellow screen and slow game play

### ISSUE THREAD

**Issue by dosas** [ValveSoftware/Source-1-Games#467]
As mentioned in the title game play is extremely slow and the screen turns yellow from time to time.
I'm sorry but I cannot figure out how to add labels.

![2013-05-05_00002](https://f.cloud.github.com/assets/2125774/463596/3bc0b166-b57f-11e2-8abd-0e9046bdd0ab.jpg)

System information:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-40-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6800 Series  

```
Driver Version:  4.2.12217 Compatibility Profile Context 12.104
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6739
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                        53.1cm x 29.9cm  (60.9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7952 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  234550 Mb
    Largest Free Hard Disk Block:  90666 Mb

Installed software:

Recent Failure Reports:
    Sun May  5 12:03:08 2013 GMT: file ''/tmp/dumps/assert_20130505140252_1.dmp'', upload yes: ''CrashID=bp-55ee38d2-d0fe-43cd-b918-cdd342130505
    ''

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.

**Comment by benbk97** [comment]
@kisak-valve I'm having this problem with my copy of LFD2. 
Running it on a 2015-era Macbook Air. 1.6 GHz Intel Core i5 processor, 8 GB RAM, Intel HD Graphics 6000 1536 MB graphics. 

Same yellow screen bug as described above—totally yellow screen that tends to happen when looking in dark areas of the game. Tried all the different video settings and tricks, nothing worked. 

Think you could help me out? Was psyched to play this game.

**Comment by kisak-valve** [comment]
Hello @benbk97, please open a new issue report so that your issue can be tracked properly.
