### ISSUE TITLE
[L4D2 Beta - Linux] Game exits after intro

### ISSUE THREAD

**Issue by TheWounded** [ValveSoftware/Source-1-Games#468]
When starting up the game in steam, the intro shows. When the main menu should appear i get a message box with the title "Engine Error" stating the message "Steam is not running. You must start steam in order to play this game". 

Steam is running.
OS: OpenSuse 12.3
GFX: Nvidia GTX560 driver version 310.44
Steam buildt: May 3 2013
Steam API: V012
Steam package versions: 1367627987 / 13676219...

**Comment by kisak-valve** [comment]
Hello @TheWounded, are you still experiencing this issue with an up to date system?

**Comment by TheWounded** [comment]
Hello kisak, haven't seen this issue in a long time. If I remember
correctly it was fixed with a patch a few months after my last message.

**Comment by kisak-valve** [comment]
Thanks, closing.
