### ISSUE TITLE
[TF2] Skins textures are loading AFTER you pick it

### ISSUE THREAD

**Issue by pikselniy** [ValveSoftware/Source-1-Games#4680]
Make skins load BEFORE you start playing with it, because on bad pc it causes a big lag, so you have to pick all your weapons to load them before you start play on every server you join or game becames completly unplayable. I paid for those and i want to play comfortable with them, or else it becames a pay-to-lose

**Comment by condor00fr** [comment]
Texture streaming dosn't really do anything outside of makkng the game ugly for the most part.

**Comment by pikselniy** [comment]
> Add `-no_texture_stream` to Team Fortress 2's launch options. This will disable texture streaming, which is what's causing the game to load in weapon skin textures after the fact. This might not solve your problem though, since texture streaming was added to prevent this exact scenario. Your computer might unfortunately be too low-spec to support the game without hitches like this, but give that a try and let us know what happens.

It still sometimes loads after you picked a weapon, but it somehow stopped lagging, thanks!
