### ISSUE TITLE
libX11 1.8.3 update completely broke all ToGL games on X11

### ISSUE THREAD

**Issue by Dupiter-AU** [ValveSoftware/Source-1-Games#4686]
I recently updated my Arch Linux system after a small period of not updating, and now all ToGL games freeze upon loading into a map.
Team Fortress 2 and HL2 are the main offenders, I haven't tested L4D2. P2 and CS:GO work fine with Vulkan so this is directly because of ToGL. 

I have deduced that this is likely to be a NVIDIA problem since downgrading Mesa had no effect, and `nvidia-dkms` was the only other real graphical software update. I am currently using `nvidia-dkms` version `525.78.01` on a RTX 2060 Super (Version difference: `525.60.11-1 -> 525.78.01-1`).

I tried turning off Shader Cache in steam to no effect, deleting `libSDL2-2.0.so.0` for TF2 and using native libraries, and the game *always* seems to crash on the class select menu. HL2 seems to crash a few seconds after loading a map.

Tried looking into `-condebug` but no error messages are present.

**Comment by Dupiter-AU** [comment]
Looks like this might be a duplicate of #4668. However my `libx11` version is `1.8.3-5`, which [supposedly fixed this issue](https://github.com/ValveSoftware/Dota-2/issues/2218#issuecomment-1374633854). So I'm going to leave this issue open

**Comment by kisak-valve** [comment]
Hello @Dupiter-AU, https://github.com/ValveSoftware/Source-1-Games/issues/4668#issuecomment-1372737033 is relevant here. Since Team Fortress 2 is 32 bit, the tinkering by your distro's 64 bit libx11 build is not relevant.

This is an upstream regression and not a game bug.

**Comment by Dupiter-AU** [comment]
Fixed by downgrading lib32-x11: `sudo pacman -U file:///var/cache/pacman/pkg/lib32-libx11-1.8.2-2-x86_64.pkg.tar.zst`

**Comment by reDBo0n** [comment]
lib32-libx11 got an update to 1.8.4-1 and seems to not have this problem anymore.
