### ISSUE TITLE
[TF2] Console command to automatically abandon match when disconnecting via console command

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#4691]
Feature request. Currently, there is no way to disconnect from a match via the `disconnect` console command without the "rejoining match in 10 seconds" prompt appearing at the top and requiring manual abandoning. I'd like to request a console command that either toggles this when using the command (e.g. `auto_abandon_on_disconnect 0/1`) or a command to specifically disconnect and instantly abandon (i.e. `disconnect_abandon`).

I currently have an alias for "disconnect" so I can simply type "dc" and be immediately disconnected rather than having to go through an extra "are you sure you want to disconnect" prompt, but it still results in a "rejoining match in 10 seconds" pop-up (which then requires me to click on 2 extra buttons anyways).

**Comment by kisak-valve** [comment]
Hello @JoriKos, this issue is already being tracked at #2821. There's no value in fragmenting the discussion of that issue by presenting the same issue as a feature request.

Closing as a duplicate.
