### ISSUE TITLE
TF2 randomly locking up....

### ISSUE THREAD

**Issue by furycd001** [ValveSoftware/Source-1-Games#4694]
HI Guys..

I'm running TF2 on Arch Linux with kernel 5.15.86. As of around December time TF2 has been randomly locking up when playing on casual servers. I've played on some community servers & have yet to encounter any of the random lockups. The only thing I have installed on TF2 is toonhud & a custom killsound. I have enabled -condebug & **["HERE"](https://termbin.com/88od)** is the last 200 lines of my console.log. The log ends right when TF2 last locked up. I've verified the integrity of TF2's game files & also made sure that I'm using the latest version of toonhud. My system is also fully up to date. I have been running on high'ish setting without any problems until now. Even now when playing, I don't notice any lag or any other problems. The game just randomly decides to lockup, which means I have to force-close & then re-launch again if I want to continue playing. Any help at all will be appreciated, because I want to play TF2 without worrying about it randomly locking up.... 

**COMP SPECS**
**----------------------**
CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
GPU: NVIDIA Corporation GK107 [GeForce GTX 650]
RAM: 16gb
OS: Arch Linux
MONITORS: Dual 1-DVI & 2-VGA (vertical)

**Comment by fotnite-vevo** [comment]
I've also been getting these issues. Since December I've been getting "Out of memory address space" crashes after a couple hours of playing, but now I'm getting the game hanging at random times (anywhere from a couple minutes after joining the server to ~20 minutes after joining) since the update on January 8th. Also running Arch Linux, but with an RTX 3060 Ti.

Though, I get it on community servers too. It seems to mostly happen on the death screen, but it also happens at random times it seems. Makes the game basically unplayable.

**Comment by furycd001** [comment]
I have yet to come across any crashes, and here's hoping that I never do. I don't know the playing time frame before a lockup happens, but I know that it's less than an hour, maybe less than 30 minutes sometimes. Hmmm now that you mention it.. most of my lockups have occurred right after I have been killed. The community servers that I play on are mainly skial - 24/7 dustbowl & skial - payload maps.

**Comment by reDBo0n** [comment]
Sounds like the problem I had (#4668) .
Downgrading lib32-libx11 to 1.8.2-2 or applying both difs of the 64-bit version (1.8.3-5) to the 1.8.3 package fixed the problem for me.

**Comment by reDBo0n** [comment]
I use the tool "downgrade" [AUR](https://aur.archlinux.org/packages/downgrade)

Just run `sudo downgrade lib32-libx11`, then with your arrow keys choose the version you like (probabbly 1.8.2-2)

**Comment by furycd001** [comment]
> I use the tool "downgrade" [AUR](https://aur.archlinux.org/packages/downgrade)
> 
> Just run `sudo downgrade lib32-libx11`, then with your arrow keys choose the version you like (probabbly 1.8.2-2)
> 
> See also: [Downgrading packages - ArchWiki](https://wiki.archlinux.org/title/Downgrading_packages)

Thanks for the help. I installed `downgrade` & downgraded the package. Also added it to the `IgnorePkg` list for now....

**Comment by furycd001** [comment]
Ok, so I played for a bit there on some `cp_mercenarypark` and TF2 never locked-up. Downgrading `lib32-libx11` seems to be the fix here.

**Comment by fotnite-vevo** [comment]
> Sounds like the problem I had (#4668) . Downgrading lib32-libx11 to 1.8.2-2 or applying both difs of the 64-bit version (1.8.3-5) to the 1.8.3 package fixed the problem for me.

I tried this as soon as I got the post notification. Seems to have fixed the issue.

**Comment by reDBo0n** [comment]
lib32-libx11 got an update to 1.8.4-1 and seems to not have this problem anymore.

**Comment by furycd001** [comment]
> lib32-libx11 got an update to 1.8.4-1 and seems to not have this problem anymore.

Thanks for the heads up. I'll probably install the update sometime next week to test it out....
