### ISSUE TITLE
[TF2] Game crashes with scoreboard open while respawning

### ISSUE THREAD

**Issue by little512** [ValveSoftware/Source-1-Games#4698]
Whenever I have the scoreboard open via holding tab after dying, just as my respawn timer starts the game crashes.

Steps to reproduce:
- Join any Valve casual server (does not work on a listen server from my testing)
- Die, whether by being killed or typing `kill` in the console
- Hold tab, or otherwise have `+showscores` active until the respawn timer starts

I see nothing relevant in the command line other than a lot of "sequence lost" (see #4668)

Relevant crash ID: `CrashID=bp-7d3abec5-e546-4532-a8a7-16b372230112`

Relevant system information:
```
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 3600X 6-Core Processor             

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.1.4-2-MANJARO
    X Server Release:  12101006
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime_0.20221019.0

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 525.78.01
    OpenGL Version: 4.6

Memory:
    RAM:  32045 MB
```

**Comment by JoriKos** [comment]
Tried this on Windows 10, doesn't cause any issues for me.

**Comment by kisak-valve** [comment]
Hello @little512, just to remove it as a factor, are you able to test how the game behaves with `lib32-libx11` 1.8.1 or 1.8.2?

**Comment by little512** [comment]
Hey @kisak-valve, thank you for the response. It seems that downgrading does indeed fix the issue. I've tested with 1.8.1-1 and 1.8.2-2 and the crashes have stopped. I didn't realize that the issues were related, I'll close mine now. Thanks again.

**Comment by FlaminSarge** [comment]
(Same as #4686 , right?)

**Comment by reDBo0n** [comment]
lib32-libx11 got an update to 1.8.4-1 and seems to not have this problem anymore.
