### ISSUE TITLE
[L4D2] Huge freezes probably after latest Steam client update

### ISSUE THREAD

**Issue by vitacell** [ValveSoftware/Source-1-Games#4701]
Here is huge freezes the whole gameplay since mid/late December. The game freezes sometimes completelly, and it is not some kind of stuttering or FPS drops. Every freeze accompanies with a good sound in a loop (it also freezes, looping). When the game freezes, just moving mouse or pressing some button of keyboard unfreezes it. When I play the game, I always must to keep moving mouse or pressing some button of the keyboard. Updating to Steam Beta client doesn't help. I also tryed to start the game with those arguments "-novid -skiploadingworkshopaddons -nojoy -nomsaa". Unsuscribed all mods from workshop and removed them manually from folder. This is what done last steam-client bugdate from December. Other games like CS:GO, work fine. This happens only with L4D2. 
Really, is this a good way to treat the GNU/Linux users? I am sure that Windows users have the game working fine. Stop breaking your own software, and ruining Linux experience.

[sys-info.txt](https://github.com/ValveSoftware/Source-1-Games/files/10416292/sys-info.txt)

**Comment by kisak-valve** [comment]
Hello @vitacell, this is the same issue as https://github.com/ValveSoftware/Source-1-Games/issues/4694. Your system installed `lib32-libx11` 1.8.3 has regressions and this issue needs to be resolved in the system package.

See https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/174

Closing as not-our-bug.
