### ISSUE TITLE
[TF2] Linux crashes on death-cam with scoreboard open

### ISSUE THREAD

**Issue by steakelum** [ValveSoftware/Source-1-Games#4707]
Strange issue since the latest update that persists across re-installs with and without custom hud/content loaded. On death, only if killed by character (not kill bind etc) if the scoreboard is open, the game will hang briefly when the camera pans to show who the killer is and crash shortly after. This happens on casual, community, and local servers. Enabling console file debugging does not report anything related to the crash, only normal console events up to the crash.

**Comment by FlaminSarge** [comment]
Duplicate of #4686

**Comment by kisak-valve** [comment]
Hello @steakelum, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please note what version of (32 bit) libX11 is installed on your system.

**Comment by steakelum** [comment]
Downgrading to libX11 1.8.2 instantly fixed the problem. Thanks guys, apologies for the duplicate.
