### ISSUE TITLE
[L4D2][Linux] Broken maps 

### ISSUE THREAD

**Issue by mattyy1hp** [ValveSoftware/Source-1-Games#471]
Sometimes are maps totally broken. It's some kind of rendering issues or something like that, look at my screenshots below. Workaround is exit to the menu and start a new game again.
I haven't seen it in multiplayer yet (I've played ~8hours MP and ~1hour SP).
No specific maps. It's random.

---

![2013-05-05_00014](https://f.cloud.github.com/assets/3092320/463846/faa889a2-b5a5-11e2-86af-ccd7bc00508f.jpg)
![2013-05-05_00017](https://f.cloud.github.com/assets/3092320/463847/00f3d0c8-b5a6-11e2-9d09-2bda0d0d3715.jpg)
![2013-05-05_00004](https://f.cloud.github.com/assets/3092320/463850/511e2238-b5a6-11e2-8a3b-94636d514464.jpg)
![2013-05-05_00018](https://f.cloud.github.com/assets/3092320/463851/5c146918-b5a6-11e2-9c66-5d7250e7ad82.jpg)

---

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Mutter
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6520G

```
Driver Version:  4.2.12173 Compatibility Profile Context 12.10.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9647
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3430 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  581188 Mb
    Largest Free Hard Disk Block:  133429 Mb

Installed software:

Recent Failure Reports:
    Sun May  5 11:44:28 2013 GMT: file ''/tmp/dumps/assert_20130505134410_1.dmp'', upload yes: ''CrashID=bp-b42b145c-22cc-43be-9325-3fd902130505''

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
