### ISSUE TITLE
[L4D2] Client Freezes Intermittently During Loads Unless Steam Overlay is Opened

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/Source-1-Games#4710]
### **Software and Hardware:**
OS / Distro: Arch Linux
Kernel: [Linux 6.0.8-272-tkg-pds](https://github.com/frogging-family/linux-tkg) - (Built with GCC)
Desktop Environment: KDE Plasma 5.26.5
Window Manager: Kwin
GPU: Nvidia RTX 2080 Ti
GPU Driver: 525.60.11
CPU: Ryzen 3700X @ 4.05 GHz
Filesystem in use: BTRFS
Opted into Steam Beta: Yes
Steam Client Version: 1673573268 (Built: Jan 13 2023, at 00:55:04)
[System Info Gist](https://gist.github.com/ThisNekoGuy/bc05f81d563a95b53810331652f0988b)

### **Description:**

- Navigating the online friends menu (frequently) requires that the Steam overlay be opened and closed to properly join lobbies (the process visually freezes)
- **All** loading screens (including the initial main menu load) requires that I press **shift** (for some reason, shift keeps opening the overlay even though I didn't touch any key bindings); it happens regardless of the type of loading event most of the time, the only exception is when navigating menus but even that is inconsistent
<details><summary>Launch Options:</summary>

[gamemoderun](https://github.com/FeralInteractive/gamemode) %command% -novid -nohltv -high -threads 4 -vulkan +mat_motion_blur_enabled 0 +mat_motion_blur_percent_of_screen_max 0
</details>

- Game settings are all set to their lowest values with very few exceptions (note that I even have the game running at 720p to avoid the game hitting a RAM limit): Anisoptric filtering is set to trilinear, Gore is set to high, and Shader Detail is set to medium, and Vsync is set to double-buffer
- I have Kwin set to stop its compositing so that the Game gets full attention from the window-manager without Plasma potentially getting in the way
- This happens regardless if the Steam Linux Runtime compatibility tool is used or not
- Steam Input is enabled for the game
- I do have a (Xbox One Afterglow) controller also plugged in (because I play the game with a controller)

With all of that out of the way: this is a very recent issue; this was never a problem before for me and I don't have any such issues with any other game.
Additionally, this makes playing the game even more cumbersome than it already is because of its 32-bit nature, so it would be great if this gets addressed... Just playing this game shouldn't be difficult in 2023.

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, this is the same issue as #4701 / #4694. Your system installed lib32-libx11 1.8.3 has regressions and this issue needs to be resolved in the system package.

See https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/174

Closing as not-our-bug.
