### ISSUE TITLE
[TF2] Tank has an unused skull layer

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#4713]
The tank has an unused skull layer that Valve presumably forgotten to implement, here's how it's intended to look like:
![FmhPIeGWIAAmSUq jpeg](https://user-images.githubusercontent.com/71549583/212881659-aed75fd0-36a3-450a-9196-9019904eba4c.jpg)

**Comment by Ashetf2** [comment]
Did you got this from the leak?

**Comment by kisak-valve** [comment]
Hello @condor00fr, I'm failing to see how this is an issue. You can't imply developer intent if it didn't actually ship in the game that way.

At best, this is a hypothetical design that was shelved.

Closing as as invalid.

**Comment by condor00fr** [comment]
oh that was from the leak? my bad.
