### ISSUE TITLE
(TF2) (Linux) Entities displaying as white wireframe on Lazarus in Casual.

### ISSUE THREAD

**Issue by torzod** [ValveSoftware/Source-1-Games#4717]
Today I was surfing casual games, got a game of Lazarus, went to 2 other games, and ended up back in a Lazarus lobby, and I am not sure if it was the same one. The doors in both spawns, as well as the rotating globes, appeared as white wireframes. They still behaved as expected though. Additionally, this coincided with the billboarded grass textures appearing as white wireframes, a separate well-documented bug, and I am not sure if the two are related. Passing "retry" to the console did not fix the issue. I have also attached an image of a non-spawn door to demonstrate that the entities shown are the only ones effected. The server reloading the map has no effect, nor does the server changing to another map and back to Lazarus.
![Screenshot from 2023-01-17 07-51-22](https://user-images.githubusercontent.com/29359401/212920720-8aea7623-f02d-4dc7-914a-7f856ff0eec2.png)
![Screenshot from 2023-01-17 07-51-31](https://user-images.githubusercontent.com/29359401/212920755-4a7f7bfc-fb09-4730-845b-c7d4a1bd58cf.png)
![Screenshot from 2023-01-17 07-51-34](https://user-images.githubusercontent.com/29359401/212920781-31fa45a1-f0ea-444d-93c4-65ffb4627623.png)
![Screenshot from 2023-01-17 07-52-10](https://user-images.githubusercontent.com/29359401/212920803-99c51331-7b6e-4358-9e32-e7af69920349.png)
![Screenshot from 2023-01-17 07-52-17](https://user-images.githubusercontent.com/29359401/212920832-84208603-d8a3-43f3-a987-f64bc8ad2056.png)
![Screenshot from 2023-01-17 07-52-38](https://user-images.githubusercontent.com/29359401/212920846-b39b30c1-3729-4855-9208-321d72bce461.png)
![Screenshot from 2023-01-17 07-52-42](https://user-images.githubusercontent.com/29359401/212920870-e7101935-e0ca-4561-8801-598b5410bd0b.png)
![Screenshot from 2023-01-17 08-12-28](https://user-images.githubusercontent.com/29359401/212921052-1c96fb02-a473-48b0-8f10-557feced26b8.png)
![Screenshot from 2023-01-17 07-53-27](https://user-images.githubusercontent.com/29359401/212921076-9eee9f5b-a5b2-40b8-abac-a1802f9d01dd.png)
![Screenshot from 2023-01-17 07-54-12](https://user-images.githubusercontent.com/29359401/212921097-e4881981-3b4f-4648-bc04-a0bfaae623cd.png)
![Screenshot from 2023-01-17 07-55-01](https://user-images.githubusercontent.com/29359401/212921110-0bef6122-b079-437d-b440-aaa45c670070.png)
![Screenshot from 2023-01-17 07-50-27](https://user-images.githubusercontent.com/29359401/212921117-14241787-6c90-4d3c-844f-80415360d60a.png)

**Comment by Tiagoquix** [comment]
OP, can you retest with the new Vulkan render?

**Comment by torzod** [comment]
I am unable to retest this bug as it has only ever happened to me once, and
I was playing casual normally, no unusual circumstances, meaning this may
well be entirely unreproducible.

**Comment by kisak-valve** [comment]
Closing as a fluke.

**Comment by Hex4dec** [comment]
I can run into this glitch once a month randomly, this bug still exists and just needs more testing.

P.S. I have the Radeon RX 6600 XT. This bug may be specific to AMDGPU.

P.P.S. Did a little more research and it seems to be related to the game not finding the detail/billboard's texture. Could be a potential race condition?
