### ISSUE TITLE
counter strike black and purple blocks crash

### ISSUE THREAD

**Issue by semo1999** [ValveSoftware/Source-1-Games#472]
when the loading ends the people look like error and then it crashes and here is a photo of the console
![untitled](https://f.cloud.github.com/assets/4347944/463867/7f84b152-b5a9-11e2-9614-a09787d0ebf4.png)

**Comment by kisak-valve** [comment]
Hello @semo1999, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
