### ISSUE TITLE
(TF2) (Linux) Spawn Gate not rendering

### ISSUE THREAD

**Issue by torzod** [ValveSoftware/Source-1-Games#4726]
Unlike #4717, it is not rendered as wireframe, and is simply gone. I have seen this not only on Snowycoast, but other maps as well.
![Screenshot from 2023-01-18 16-10-45](https://user-images.githubusercontent.com/29359401/213306627-337ca4fd-1c87-4a15-bfe5-bc3d445b8aed.png)

**Comment by kisak-valve** [comment]
Hello @torzod, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by torzod** [comment]
here is the gist: https://gist.github.com/torzod/2a3a007e57c176cc1b774aa1a6f4c78a
i have a hunch this and #4717 might be due tochanging games too rapidly, leaving the game unable to cache certain objects/textures fast enough

**Comment by Tiagoquix** [comment]
OP, can you retest with the new Vulkan render?

**Comment by torzod** [comment]
This bug is extraordinarily rare, as I have only encountered it a
single-digit number of times in my over 1.6 thousand hours playing the
game, so it is not feasible to reproduce in a controlled environment.

**Comment by kisak-valve** [comment]
Closing per the last comment.
