### ISSUE TITLE
[TF2] Differences in SDL2 version causes steam overlay to stop working

### ISSUE THREAD

**Issue by steakelum** [ValveSoftware/Source-1-Games#4741]
This may fall as an invalid issues as it only occurs when using the system's lib32-sdl2 library instead of the game-provided library, however - after switching (in order to fix doubled mouse sensitivity and non-registered clicking) to use the system's version using LD_PRELOAD, the steam overlay (and also mann co store) through using the key combination or opening profiles thru the scoreboard stop working entirely. Switching between the two versions of the libraries will fix one of the issues but re-enable the other unfortunately.

**Comment by reDBo0n** [comment]
I use my system's SDL2 and I don't have these problems.
I use [this](https://docs.mastercomfig.com/latest/os/linux/#fixing-bugs-with-newer-sdl2) method though.

**Comment by steakelum** [comment]
Works fine out of the box, after a fresh re-install of the game. The workaround is no longer needed and appears impossible as the 32-bit libsdl2 and libtcmalloc previously included with the game seem to have been (correctly) removed.
