### ISSUE TITLE
[TF2] Update the Blu soldier, Red and Blu Pyro class HUD icons

### ISSUE THREAD

**Issue by bvvth556epic** [ValveSoftware/Source-1-Games#4746]
Blu soldier, Red and Blu Pyro class HUD icons are not consistent with the current game design. Here are mods that fixed these icons:
Blu soldier
https://gamebanana.com/mods/423069
Red and Blu Pyro
https://gamebanana.com/mods/422936

Valve, please update them

**Comment by condor00fr** [comment]
Theses are yours?

**Comment by condor00fr** [comment]
They are nicely done and fit the old 2007 artstyle. Good work

**Comment by kisak-valve** [comment]
Hello @bvvth556epic, this issue is already being tracked at #4178. Closing as a duplicate.
