### ISSUE TITLE
[TF2] Merasmus's Flame attack dosn't actually set players on fire

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#4754]
Ever since truces were added on Ghost Fort, but not other maps Merasmus appears as a boss on, Merasmus's long-distance attack no longer sets players on fire, but still triggers the voice responses for being put on fire.

**Comment by kisak-valve** [comment]
Hello @condor00fr, this issue is already being tracked at #4162. Closing as a duplicate.
