### ISSUE TITLE
[PORTAL 1] KeyValues Error when playing custom credits

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/Source-1-Games#4759]
Recently I was working on a portal 1 mod of mine and adding custom credits, after changing the lyrics up to a point, the game started to throw this error and stoped showing the custom lyrics after a certian point. The exact error is as follows: "KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file scripts/credits.txt credits.txt OutroSongLyrics". Does anyone know how I can fix this?

**Comment by theOneTrueFunniBoi** [comment]
Here is the Credits.txt File: 
[credits.txt](https://github.com/ValveSoftware/Source-1-Games/files/10531640/credits.txt)

**Comment by Didrole** [comment]
There are incorrect quotation marks on line 291.

**Comment by theOneTrueFunniBoi** [comment]
Thank You!
