### ISSUE TITLE
[Feedback] Create a separate repository specifically for TF2 to track bugs/feature requests 

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#4763]
I know this repository is for reporting bugs or feature requests for Source 1 games in which Team Fortress 2 falls into that category, but I feel it has become more of a Team Fortress 2 repository that Source 1 games, as bugs from Source 1 games end up being forgotten by the immense amount of issues created specifically for TF2.
One way to mitigate this problem is to create a separate repository just for Team Fortress 2, as Dota 2 and CS:GO have had their own repositories for a while now.

**Comment by condor00fr** [comment]
Not a bad idea at all

**Comment by kisak-valve** [comment]
Hello @gaelcoral, how Valve devs would like feedback on the issue trackers categorically split is at their discretion.

My understanding is that there are separate teams working on the examples you have given.
