### ISSUE TITLE
[TF2?] Source Filmmaker website no longer functions

### ISSUE THREAD

**Issue by ljcool2006** [ValveSoftware/Source-1-Games#4773]
I apologize if this isn't the right place to post this but I had to remind Valve about this.

For a couple of months, the SFM website has been giving out a "There was an error communicating with the Steam Network. Please wait a moment and try again." error.

Steps to reproduce:
1. Go to sourcefilmmaker.com
2. See error
![Screenshot_2023-02-10 https www sourcefilmmaker com](https://user-images.githubusercontent.com/51834343/218076488-056ef262-ad21-4c81-abeb-c5380a7b824c.png)

**Comment by JoriKos** [comment]
This seems more like an issue for Steam Support or emailing Steam-related Valve employees.

**Comment by kisak-valve** [comment]
Hello @ljcool2006, https://www.sourcefilmmaker.com/faq/ seems to work, and has project-specific contact information on the right side.

**Comment by EricS-Valve** [comment]
This should be fixed. Thanks for the report.

**Comment by gaelcoral** [comment]
Hi @EricS-Valve the Portal website https://www.thinkwithportals.com/  also has the same error that the Source Filmmaker website had "There was an error communicating with the Steam Network. Please wait a moment and try again.".

**Comment by EricS-Valve** [comment]
@gaelcoral The Portal website should be fixed now, too. Thanks.

**Comment by ljcool2006** [comment]
> This should be fixed. Thanks for the report.

I can confirm that this is fixed.

**Comment by kisak-valve** [comment]
Closing as fixed.
