### ISSUE TITLE
[TF2] [CSS] Games immediately close on launch (nvidia)

### ISSUE THREAD

**Issue by digitalwtf** [ValveSoftware/Source-1-Games#4777]
Display Protocol: Wayland
Graphics Card: Nvidia RTX 3060 ti
Steam: Flatpak
Steam Beta: Opted-Out
WM: Hyprland (wlroots)
OS: Arch Linux

Snippet of my logs
`GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 8388608, Total Avail: 8388608, Current Avail: 7654400
GL_MAX_SAMPLES_EXT: 32
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 4426 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 4426 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: DISABLED
ERROR: ld.so: object '/home/sonny/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20230212123243_2.dmp[817]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230212123243_2.dmp
crash_20230212123243_2.dmp[817]: Finished uploading minidump (out-of-process): success = yes
crash_20230212123243_2.dmp[817]: response: CrashID=bp-85d8b7e8-f4bc-4ae4-8596-f1ca72230212
crash_20230212123243_2.dmp[817]: file ''/tmp/dumps/crash_20230212123243_2.dmp'', upload yes: ''CrashID=bp-85d8b7e8-f4bc-4ae4-8596-f1ca72230212''
pid 817 != 814, skipping destruction (fork without exec?)
/mnt/e0e0f6ab-98b1-44d8-8174-959d07da43f1/sonny/steam/steamapps/common/Team Fortress 2/hl2.sh: line 72:   766 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game process removed: AppID 440 "/home/sonny/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/sonny/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/e0e0f6ab-98b1-44d8-8174-959d07da43f1/sonny/steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime", ProcID 766
ThreadGetProcessExitCode: no such process 814
ThreadGetProcessExitCode: no such process 766
ThreadGetProcessExitCode: no such process 765`

**Comment by kisak-valve** [comment]
Hello @digitalwtf, this issue is already being tracked at #4553. Closing in favor of the older issue report.
