### ISSUE TITLE
[TF2] Sniper Rifle botkiller heads disappear for a second when unscoping after firing.

### ISSUE THREAD

**Issue by PyronutTF2** [ValveSoftware/Source-1-Games#4784]
How to reproduce: Use a botkiller sniper rifle, scope, shoot, and it will disappear during the rifle cock animation
This is hardly noticeable when using autozoom.

**Comment by kisak-valve** [comment]
Hello @PyronutTF2, this issue is already being tracked at #4408. Closing as a duplicate.
