### ISSUE TITLE
[TF2] Game chat can be spammed by consecutive connections and disconnections

### ISSUE THREAD

**Issue by Kofiy** [ValveSoftware/Source-1-Games#4788]
_Basically the title describes most of it._
Bad actors can consecutively join and disconnect from server (I don't really know the exact details and can't tell if they're using some bot-like software, retry command, using parties or other techniques) causing chat to be filled with Player joined and Player leaved messages.

That makes text chat communication between normal players almost impossible, can be used for advertising scams or/and to fill players' screens with profanities. 
It's also impossible (at least using basic GUI capabilities) to mute/kick these users because they disconnect before joining any team.

The user disconnect reasons are mostly: `Connection classing`, `Client disconnected` and `Steam auth ticket has been canceled`

https://user-images.githubusercontent.com/37085105/220463531-d7200e24-3988-4739-a185-3247d1e65d03.mp4

**Comment by kisak-valve** [comment]
Hello @Kofiy, this issue is already being tracked at #3850. Closing as a duplicate.
