### ISSUE TITLE
left 4 dead 2. you can join freinds only games using the server browser

### ISSUE THREAD

**Issue by sylveonsylvia** [ValveSoftware/Source-1-Games#4796]
the console command openserverbrowser opens the standard source engine server browser. using this server browser it is possible to join friends-only lobbies if the host uses the "official dedicated" server option 

this defeats the purpose of the "friends only" option

**Comment by kisak-valve** [comment]
Hello @sylveonsylvia, this issue is already being tracked at #3048. Closing as a duplicate.
