### ISSUE TITLE
[TF2] [Feature Request] New tf_gamerules inputs to change CTF cap limit

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#4800]
I've been working in a mini variation of the CTF gamemode that requires to increase the cap limit, but there's no input in tf_gamerules to do so, only with the command `tf_flag_caps_per_round`, which would require to use `point_servercommand`, which it's not recommended. That's why a new input to set the cap limit would be good (maybe `SetCTFCapLimit`?)

**Comment by Ashetf2** [comment]
Also, changing the value of tf_flag_caps_per_round affects other maps too.

**Comment by worMatty** [comment]
Hello, Ashe.

You can use VScript to do this, as it's on the whitelist of convars that can be changed. Their values are reset to default on map end.

**Comment by Ashetf2** [comment]
I'm closing this because it's too easy to change the cap limit via Vscript.
