### ISSUE TITLE
[HLDMS] Half-Life Deathmatch Source issues with "team-play" (mp_teamlist not enforced, etc.)

### ISSUE THREAD

**Issue by Mecha-Weasel** [ValveSoftware/Source-1-Games#4808]
Was trying to setup a HLDMS team deathmatch server (**mp_teamplay "1"**, but it does not appear to be honoring the **mp_teamlist** CVAR.

Regardless of that it is set to on the server (default says "hgrunt;scientist", as an example I was using "hgrunt;robo"), the player can change to any model (via **cl_playermodel** command) - not just the models specified in **mp_teamlist**.

Also, players with different models all show-up as part of the same team (console message says they are assigned to "team 2", regardless of what model they are using, or if that model is part of **mp_teamlist** or not).

**Comment by Mecha-Weasel** [comment]
Oops maybe related to https://github.com/ValveSoftware/Source-1-Games/issues/1366.
Did not show-up when I searched for mp_teamlist, etc.

**Comment by kisak-valve** [comment]
Hello @Mecha-Weasel, feel free to add your experience to the older issue report.

Closing as a duplicate.
