### ISSUE TITLE
Huntsman with fire arrows sometimes makes strange noises

### ISSUE THREAD

**Issue by powerlord** [ValveSoftware/Source-1-Games#481]
Sometimes when the Huntsman and Festive Huntsman have a lit fire arrow, they will play what sounds like a loud buzzing sound that sounds a bit like a horn.

You can generally guarantee that it will happen by switching weapons immediately after lighting a fire arrow.

[This video](http://www.youtube.com/watch?v=24Fr1o-ORv0) from January, which is of a standard medieval match on Degroot Keep, shows an example of it.  I found it linked from [this thread](http://steamcommunity.com/app/440/discussions/0/846941710515472497/) on the Steam Community for TF2.

I'm not sure how long this bug has existed, but it has become more prevalent due to the Huntsman Hell game mode, where all players are Huntsman Snipers with fire arrows.

**Comment by Wasmanr2** [comment]
Cant confirm i tested it. 
Arrows under fire or cow mangler after switching weapons sounding normal.
No buzzing sounds.
@kisak-valve you may close this

**Comment by kisak-valve** [comment]
Hello @powerlord, if you are still experiencing this on an up to date system, we can re-open this issue report.

Closing per the last comment.
