### ISSUE TITLE
[HL2] [EP1] [EP2] Utter Bug Compendium of Doom

### ISSUE THREAD

**Issue by Hubbenobo** [ValveSoftware/Source-1-Games#4820]
I have basically absolutely 0 information at all to provide in any way, shape, or form at this time. This is due to the fact that I'd have to write an entire novel in order to include only half of them here. Just watch the videos in this playlist and it will all start to make perfect sense.

The only description I can give you about literally anything is that the player uses the Windows 10 OS and has an NVIDIA graphics card. Everything that you need to know about is seen here. The best way to describe the current state of the games is a wooden plank with nails and duct tape placed on a broken window.

Source: [https://www.youtube.com/playlist?list=PLGRg3UhvfFNQisqmpUplI87MZx79OOPWS](url) - It's all listed here.

My only reason that I'm even posting this is because of 1 simple motive; fixing year-old glitches that I've seen countless times in so many playthroughs of mine (some are completely immersion ruining and, at times, to the point of soft locking my saves. Despite the lack of an incentive, I would still like to see these get fixed.

**Comment by Hubbenobo** [comment]
Ignore the facts, of course.

**Comment by JoriKos** [comment]
I'm not sure any devs are too keen to watch a 1 and a half hour+ video of facts and bugs to see if there's anything useful in there especially when a lot of them are very minor bugs that aren't really worth fixing. You're better off taking the major bugs and making separate issues for them (I believe multi-issue posts are also not allowed).

**Comment by kisak-valve** [comment]
Hello @Hubbenobo, as @JoriKos noted, in general multi-issue issue reports are bad for any issue tracker and this feedback can't be tracked properly as you have presented it.

Closing as invalid.
