### ISSUE TITLE
[TF2] [Feature Request] Restore pre-Jungle Inferno Sandman stun to Mann vs Machine bots

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#4828]
Hi!

It's a short ticket, but I was wondering if there was any chance that the old Sandman stun (pre-Jungle Inferno rework) could be reimplemented for Mann vs Machine bots that were coded/balanced around having it (ie. Sandman bots in Mannhattan).

**Comment by kisak-valve** [comment]
Hello @rabscootle, this request appears to be a duplicate of #3471. Closing in favor of the older issue report.
