### ISSUE TITLE
[TF2] [Feature Request] Add advanced option to disable drawings in Competitive Mode results screen

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#4830]
Hi!

I was wondering if there was any chance that an advanced setting could be added that would allow users to hide the drawings from the results screen on their instance of the TF Client.
![image](https://user-images.githubusercontent.com/108029512/223226762-1ede0ec0-1de9-447c-ac82-284caec381fb.png)

**Comment by kisak-valve** [comment]
Duplicate of #3526.
