### ISSUE TITLE
[All Source Games] reimplement mat_picmip -10 on all games

### ISSUE THREAD

**Issue by Wadmodder** [ValveSoftware/Source-1-Games#4877]
The Source engine used to have the ability to met the mat_picmip to -10 from 2004 to 2009, but this was limited to -1 due to the release of the macOS ports of Source Engine games. Given that macOS no longer supports 32-bit Carbon API applications and Valve's lack of staff with the macOS ports of any of their games other than Dota 2 and CS:GO, it would make sense to bring back the option to set the mat_picmip -10 for all official Valve Source 1 engine games.

**Comment by kisak-valve** [comment]
Hello @Wadmodder, this issue is already being tracked at #699. Closing as a duplicate.
