### ISSUE TITLE
Tf2 is very laggy when launched on linux

### ISSUE THREAD

**Issue by frogge539** [ValveSoftware/Source-1-Games#4881]
ive checked the tf2 files and everything seems fine and deleted my custom, this also occurs on hl2 as well, i have nvidia mesa and everything else required update to date, i also have a laptop with linux as well, where this issue seemingly does not occur.

**Comment by slender100** [comment]
> ive checked the tf2 files and everything seems fine and deleted my custom, this also occurs on hl2 as well, i have nvidia mesa and everything else required update to date, i also have a laptop with linux as well, where this issue seemingly does not occur.

usually nvidia cards do not work well with linux, so this could be your issue.

**Comment by frogge539** [comment]
> > ive checked the tf2 files and everything seems fine and deleted my custom, this also occurs on hl2 as well, i have nvidia mesa and everything else required update to date, i also have a laptop with linux as well, where this issue seemingly does not occur.
> 
> usually nvidia cards do not work well with linux, so this could be your issue.

my laptop has an nvidia card and it runs fine, while my pc gets 2 fps, maybe nvidia cards arent the best for linux but i used to get 90-120 fps on windows, from that to 2 is extreme

**Comment by slender100** [comment]
> > > ive checked the tf2 files and everything seems fine and deleted my custom, this also occurs on hl2 as well, i have nvidia mesa and everything else required update to date, i also have a laptop with linux as well, where this issue seemingly does not occur.
> > 
> > 
> > usually nvidia cards do not work well with linux, so this could be your issue.
> 
> my laptop has an nvidia card and it runs fine, while my pc gets 2 fps, maybe nvidia cards arent the best for linux but i used to get 90-120 fps on windows, from that to 2 is extreme

yes, this sounds exactly like a drivers issue with linux. all I can recommend is having some sort of dual boot configuration/separate drive to boot into windows to play tf2.

**Comment by frogge539** [comment]
> > > > ive checked the tf2 files and everything seems fine and deleted my custom, this also occurs on hl2 as well, i have nvidia mesa and everything else required update to date, i also have a laptop with linux as well, where this issue seemingly does not occur.
> > > 
> > > 
> > > usually nvidia cards do not work well with linux, so this could be your issue.
> > 
> > 
> > my laptop has an nvidia card and it runs fine, while my pc gets 2 fps, maybe nvidia cards arent the best for linux but i used to get 90-120 fps on windows, from that to 2 is extreme
> 
> yes, this sounds exactly like a drivers issue with linux. all I can recommend is having some sort of dual boot configuration/separate drive to boot into windows to play tf2.

is it really unfixable though?

**Comment by kisak-valve** [comment]
Hello @frogge539, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by frogge539** [comment]
Update: i fixed the problem, i just had to download corresponding drivers via aur (in my case paru), mine being nvidia-470xx instead of just the regular nvidia drivers. however this resulted in steam apps and steam itself not running because the lib32 did not match the driver number, so i also had to download the corresponding lib32 470xx driver via aur, this has seemingly fixed all problems!

**Comment by kisak-valve** [comment]
The symptoms you've described is that Team Fortress 2 was previously forced to fallback to llvmpipe to render of the CPU because there wasn't a working 32 bit userspace for your NVIDIA driver install before.

Closing per the last comment.
