### ISSUE TITLE
[TF2] Target ID with the changed location will be in a much lower position than it should be

### ISSUE THREAD

**Issue by impale1** [ValveSoftware/Source-1-Games#4906]
I can't reproduce this bug on the local server, so you'll have to do it on casual.

1. Type this in console `tf_spectator_target_location` 2 and 3
2. go to any casual server
2. kill yourself in game
3. done

The target ID will be at the bottom every time where it shouldn't be, for it to be in its proper place, you'll have to change the target (player) every time. Because of this target id overlaps the bottom panels
![1](https://user-images.githubusercontent.com/117596825/232143655-290cc7d4-e06d-4d7e-bf37-ac28f34a5891.png)
![2](https://user-images.githubusercontent.com/117596825/232143648-b64a9fbc-4013-48f1-861c-6e74b7b74fe5.png)

**Comment by kisak-valve** [comment]
Thanks @NonhumanFromSteam, closing as a duplicate.
