### ISSUE TITLE
[TF2] Demo Playback Incompatible with Workshop Maps

### ISSUE THREAD

**Issue by aarmastah** [ValveSoftware/Source-1-Games#4910]
When trying to load a demo file recorded while playing a workshop map directly (using TF2's built-in map workshop support, the demo playback cannot find the map and will fail to load it.

**Replication steps:**
1. Start TF2 via Steam
2. Use command "map workshop/2963374860" in console
3. Use command "record x" in console
4. Use command "stop" in console
5. Use command "playdemo x" in console

**Expected outcome:** Map loads, demo playback begins as normal
**Actual outcome:** Error message "Missing map maps/workshop/cp_outflow_b1.ugc2963374860.bsp, disconnecting" appears, demo does not play back

**Workaround:** find the actual BSP file of the workshop map and rename/move it to match the structure of the error message

**Comment by kisak-valve** [comment]
Hello @aarmastah, this issue is already being tracked at #2863. Closing as a duplicate.
