### ISSUE TITLE
[TF2] [Feature Request] Raise default FPS cap to 400 (from 300)

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#4913]
Like CS:GO, TF2 should have a higher FPS cap to allow monitors with higher refresh rates to benefit from it by default.

CS:GO had a cap of 300, which was raised to 400 a while ago (Valve didn't mention it in any patch notes).

**Comment by condor00fr** [comment]
Pls do, more fps means more fps

**Comment by just-a-github-user** [comment]
Easily workaroundable with fps_max 400

**Comment by gaelcoral** [comment]
It seems that in the "64bit Linux test" depot it has already been increased to 400!
![asss](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/b08ea209-43e7-451b-8fa3-2bcb73eb63fd)

**Comment by gaelcoral** [comment]
I think you should close this issue, since it is in the public branch
