### ISSUE TITLE
[TF2] Strange cosmetic with "Robots Destroyed" part applied does not count singleplayer bot kills.

### ISSUE THREAD

**Issue by Wosheereal** [ValveSoftware/Source-1-Games#4915]
As the title says, strange cosmetics that have the robots destroyed part applied to it does not count single player A.I bot kills [despite the wiki stating it counts singleplayer A.I bot kills](https://wiki.teamfortress.com/wiki/Strange_Part)  I did not have sv_cheats enabled.

**Comment by JoriKos** [comment]
It shouldn't count those, as those are not Robots bot (TF)Bots. The Wiki is incorrect on this (and I've removed it).

**Comment by Wosheereal** [comment]
I've been told by people that it doesn't count on weapons either, and the wiki has removed the note about it, so I am closing this.
