### ISSUE TITLE
[TF2] Disable Custom Decals Option

### ISSUE THREAD

**Issue by phantomboy0** [ValveSoftware/Source-1-Games#4919]
Add a Disable Custom Decals option to the game.

this option allows players to disable Custom Decals so they don't see the other players Custom Decals just like the "disable spray" option

this include Custom Decals in all tf2 items like "conscientious objector" and others.

this will allow the players to hide some sensitive Decals that exist in the game by other players.
![opt](https://user-images.githubusercontent.com/94670323/233984208-6cd50254-ffc9-4976-a446-926fdcfdc7cc.png)

**Comment by kisak-valve** [comment]
Hello @phantomboy0, this issue is already being tracked at #4249. Closing as a duplicate.
