### ISSUE TITLE
[TF2] [Feature Request] ConVar for disabling custom decals

### ISSUE THREAD

**Issue by DudeTheNinja** [ValveSoftware/Source-1-Games#4921]
Hi,

Whilst it is the case that player sprays can be disabled, custom item images (i.e. decals as seen on the Conscientious Objector, Photo Badge, Flair! and the Clan Pride items) are still permanently enabled. This is a problem because the custom decal feature is still used (and abused) by many to display decals that violate the rules of the Steam Subscriber License Agreement, if not straight up illegal imagery in rare cases.

If Valve is not going to moderate the custom images despite claiming to when applying a Decal Tool to an item, at least let us 

Thus, I propose the following feature: a convar/option, both server- and client-side, to disable them. Valve servers could have the server set the command to 0, and have the client command set to 0 by default (set to 1 in the Multiplayer > Advanced settings, like with sprays)

I have written changes to `client/econ/tool_items/custom_texture_cache.cpp` (based on outdated leaked code, so the exact line positions may have changed in due time) that illustrate a real simple implementation of a solution.

```c
// Add to header inclusions:

#include "convar.h"

// Insert at line 26:

// Allows for control over custom decals
ConVar cl_allow_custom_decals( "cl_allow_custom_decals", "0", FCVAR_ARCHIVE, "Opt-in to view custom images on decalable items", true, 0, true, 1 );
ConVar sv_enable_custom_decals( "sv_enable_custom_decals", "0", FCVAR_REPLICATED, "Allow custom images on decalable items. Clients must also set cl_allow_custom_decals to 1.", true, 0, true, 1 );

// Replace lines 782 to 785:

	if ( texture && cl_allow_custom_decals.getInt() == 1 && sv_enable_custom_decals.getInt() == 1 ) // Check if both server enables decals and player opts in
	{
		m_pBaseTextureVar->SetTextureValue( texture );
		
	}
```

**Comment by kisak-valve** [comment]
Hello @DudeTheNinja, this issue is already being tracked at #4249. Since this issue report adds some more detail, I've gone ahead and transferred it to https://github.com/ValveSoftware/Source-1-Games/issues/4249#issuecomment-1520744459.

Closing as a duplicate.
