### ISSUE TITLE
[Portal] Maps missing or locked

### ISSUE THREAD

**Issue by purpleidea** [ValveSoftware/Source-1-Games#493]
Advanced chambers are still locked after finishing game. Challenge maps are missing.

http://steamcommunity.com/id/linuxgaming/screenshot/864966776175771745

Running GNU/Linux.

**Comment by kisak-valve** [comment]
Hello @purpleidea, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
