### ISSUE TITLE
[TF2] Summer unusual effects should be unboxable with previous cases

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4933]
Ever since Valve started adding new unusual effects for the summer, they for some reason only made it so only hats from the case can have the effects applied to. This needs to change coming this summer update, there is no reason for this to be the case as you can get summer hats with Halloween and Christmas effects, Christmas with Halloween effects, Halloween with Christmas effects, so on and so forth. But Halloween and Christmas with summer effects? No dice.

**Comment by rabscootle** [comment]
Judging from the blog post it sounds like they already intend to upgrade the Summer updates to Holiday status (which in turn will make this possible).

**Comment by ShadowMan44** [comment]
> Judging from the blog post it sounds like they already intend to upgrade the Summer updates to Holiday status (which in turn will make this possible).

I'm hoping this turns out to be true (if not then we can all scream and kick at Valve).
