### ISSUE TITLE
[TF2] [Feature Request] Change flag's timer colors to TF2's palette colors

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#4936]
The flag timer ([item_teamflag_return_icon](https://developer.valvesoftware.com/wiki/Item_teamflag_return_icon)) colors for RED and BLU are very inconsistent with TF2's palette for colors. They use pure red (255,0,0) and blue (0,0,255) in RGB (according to the leaked code, in `entity_capture_flag.cpp`). These colors are a bit oversaturated.

![image](https://user-images.githubusercontent.com/63692647/235569246-34f3945f-a2a7-49c0-8250-5b1540331c05.png)

![image](https://user-images.githubusercontent.com/63692647/235569405-45d9966b-1446-479b-86c6-91ac1512e280.png)

In contrast, team-colored outline glows uses TF2's palette: (91,122,140) for BLU and (189,59,59) for RED, which are the main colors in the palette.

![image](https://user-images.githubusercontent.com/63692647/235568554-d89a9b25-b9de-4efe-9486-82f26c1a88bc.png)

So, I suggest to change RED and BLU's RGB colors for the return icon to (91,122,140) and (189,59,59).

**Comment by mtxfellen** [comment]
I am speculating, but it's possible these more saturated colours were chosen specifically to stand out from the game environment palette, similar in practice to how it's common practice for people to use saturated crosshair colours.
