### ISSUE TITLE
[TF2] [Feature Request] Possibility for map makers to create contracts for their maps.

### ISSUE THREAD

**Issue by pr0jesse** [ValveSoftware/Source-1-Games#4938]
Good day,

I think that it would be nice for map makers to upload maps with small contracts already embedded in the map, or the possibility to create these later. 

The contracts api would need to be open for this I think. Example, I created a list of contracts on the workshop ( https://steamcommunity.com/sharedfiles/filedetails/?id=2967566428 ) but these are a just suggestions, if the api would be open for the contracts we could add them to the workshop easier.

Thanks for the consideration,
Jesse

**Comment by kisak-valve** [comment]
Hello @pr0jesse, this feature request is already being tracked at #2720. Closing as a duplicate.

**Comment by pr0jesse** [comment]
@kisak-valve alright, thanks and sorry for the inconvenience!
