### ISSUE TITLE
[Steam] Screenshot uploading fails if game is running a sync.

### ISSUE THREAD

**Issue by purpleidea** [ValveSoftware/Source-1-Games#494]
Uploader fails with an error.
Uploader should either wait, queue, or work simultaneously.

Fairly easy to reproduce.
GNU/Linux.

**Comment by kisak-valve** [comment]
This issue report is out-of-scope for this issue tracker. If you are still experiencing this issue, please open a new issue report at https://github.com/ValveSoftware/steam-for-linux.
