### ISSUE TITLE
[TF2] Fix maps using same model name but different content making all others invisible until the game is restarted

### ISSUE THREAD

**Issue by bottiger1** [ValveSoftware/Source-1-Games#4956]
If you load 2 maps that embed a model of the same name but different contents, you will get a console error message spammed like this.

    Error Vertex File for 'props/someprop.mdl' checksum 1163643726 should be 909957238

This will cause lag and make the model invisible. It is also rumored to cause crashes. This situation occurs when you are using maps from 3rd parties like the workshop. This occurs because the MDL is cached while the vvd is loaded from the disk every time. So if you have the MDL from the first map cached, the 2nd map will load the VVD for 2nd map while using the mdl for the first map. If you load into a 3rd map with the same model name, it will still use the MDL from the first map while using the VVD for the 3rd map.

I would recommend flushing the cache or checking if the MDL changed and reloading. People discussing this bug for Garry's Mod have mentioned r_flushlod as a possible solution.  https://github.com/Facepunch/garrysmod-issues/issues/2650

Materials are also cached but it is not as big as a problem because they will at least be visible and not spam the console as far as I can tell. But you'll probably want to fix them eventually as the more maps are made, the higher the chance of these naming collisions. 

Fixing the models should be a high priority as someone can load a map with changed models and it will ruin any other maps they load, even ones on official servers.

This says TF2 but probably affects other source games. It is supposedly fixed in CSGO but only if you have the map already downloaded. If you need an example I could generate one, but I believe the cause is well understood.

**Comment by Ashetf2** [comment]
Probably related to a fix in today's update; "Fixed packed replacement materials/textures/models in a custom map could leak into other maps or rendering as wireframe"

**Comment by kisak-valve** [comment]
Closing per the last comment.
