### ISSUE TITLE
[All Source Games] remove support for 32-bit CPUs after Windows 10 reached End of Life in 2025 on non-LTSC systems

### ISSUE THREAD

**Issue by Wadmodder** [ValveSoftware/Source-1-Games#4959]
In two years time will be the end of life of Windows 10 on non-LTSC consumer systems, meaning it is the end of 32-bit Windows support for consumer versions of Windows as far as we know. As many operating systems reach end of life so does support for web browsers & digital distribution services (including Steam) from those OSs.

Given that 32-bit processors have never been produced by either AMD or Intel after the 2010s, Valve is the only game developer which only has partial 64-bit software development and support.

However, as drivers for 32-bit Windows systems are almost dead, and the fact that most modern web browsers are Chromium-based, removal of 32-bit processors is very unlikely to ever happen for GoldSrc and Source 1 games, as well as the Steam platform.

In addition, many major web browsers that utilize the Chromium-based Blink engine are getting bloated and resource intensive to the point that 32-bit processors are now struggling to run these web browsers, and many modern HTML5 websites now struggle to run on older Windows XP through Windows 7-era hardware due to new advancements in web browser technology. I wouldn't be surprised that if both HTML 5.4 and HTML 5.5 ever get announced in the future by either the W3C or WHATWG, HTML 5.5 would likely be exclusive to 64-bit and HTML 5.4 would likely be the final version of HTML for 32-bit processors.

Valve might have a few options for transitioning Steam, GoldSrc and Source 1 to 64-bit which would be as follows:

- remove support for 32-bit processors from GoldSrc and Source 1 engines, as well as the Steam client, due to declining uses of 32-bit Windows system by many users
- Port all their Source 1 games from 2004 to 2011 to the more stable and more secure CS:GO source branch, mainly to fix many of the major performance and security vulnerability issues present in the Orange Box/SteamPipe, Left 4 Dead 1 & 2, Alien Swarm and Portal 2 branches of the Source 1 engine
- Update Steam's Chromium-based web browser to the latest 64-bit version of Chromium
- Have the community fix the major performance and security vulnerabilities present in the Orange Box, Left 4 Dead 1 & 2, Alien Swarm and Portal 2 branches of the Source 1 engine
- update the SteamSetup.exe file to only include the latest versions of Steam or update the SteamSetup.exe file to only include the 64-bit client of Steam

Since Valve has only a few options to make a proper transition to 64-bit for the GoldSrc and Source 1 engines, as well as the Steam client, they are often very slow to adopting new standards that are now only used by every other game developer. For example while DirectX 11 has been available since 2009 with Windows 7's release, it would take Valve until the release of Source 2 in 2015 where they would finally adopt the full potential of post-DirectX 9 APIs.

Hopefully Valve comes up with a solution after Windows 10 reaches end of life for non-LTSC systems in 2025 in a couple of years.

**Comment by Yetoo1** [comment]
Windows will support 32-bit applications through x86 compatibility inherent in x86-64 standard as long as Windows keeps shipping 32-bit libraries/c runtime. Valve won't do anything until Microsoft stops shipping 32-bit libraries/c runtime and redistributing or re implementing and embedding a 32-bit emulator into steam becomes cost prohibitive.

**Comment by kisak-valve** [comment]
Hello @Wadmodder, the end of support by Microsoft for 32 bit hardware in their kernel is not the end of support for 32 bit applications in general.

This issue was previously evaluated at https://github.com/ValveSoftware/Source-1-Games/issues/906#issuecomment-19612312.

Closing as a duplicate.
