### ISSUE TITLE
[TF2] Port the world portal point entity (linked_portal_door) from Portal 2 for use by mappers in Team Fortress 2

### ISSUE THREAD

**Issue by chexo3** [ValveSoftware/Source-1-Games#4965]
I'm aware this may be too complex to accommodate, but if not, I'd really appreciate being able to use this in my maps. Imagine what you could do with non-euclidian maps! Could be great for Halloween and Christmas maps especially since those can play more fast and lose with gameplay than regular maps, but I could also see it being useful for say, "moving" spawn rooms where only the portal actually moves.

**Comment by Ashetf2** [comment]
https://github.com/ValveSoftware/Source-1-Games/issues/4729

**Comment by kisak-valve** [comment]
Hello @chexo3, as @Ashetf2 noted, this issue report is a duplicate of #4729. Closing.
