### ISSUE TITLE
[TF2] [Feature Request] Make the gunslinger and other weapons paintable

### ISSUE THREAD

**Issue by chexo3** [ValveSoftware/Source-1-Games#4967]
There’s a cosmetic called the roboot that is paintable, and is styled very similarly to the gunslinger. It would be nice to be able to paint the gunslinger to match. Although I hope some War Paints for the gunslinger get added in the summer update as well. We ought to have both war paints and paint cans usable with more items.

**Comment by kisak-valve** [comment]
Hello @chexo3, this feature request is already being tracked at #4792. Closing in favor of the older feature request.

**Comment by chexo3** [comment]
Sorry I need to start searching before I make these
