### ISSUE TITLE
Portal beta Linux advanced maps 

### ISSUE THREAD

**Issue by Gps2010** [ValveSoftware/Source-1-Games#497]
http://steamcommunity.com/app/400/discussions/0/828937546072800874/

I just escaped and wanted to try out the advanced maps.

There is one thing I noticed.

The game looks for .zip or .bmz files.

When I go with my file-browser to the folder maps, there are only bsp files.
There are 08.09,10 etc advanced files, but bsp, not bmz or zip. 

I doubt the crash report at the end of system info file are related to portal.
I can't remember steam or any game crashing. 

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3210 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "openSUSE 12.3 (x86_64)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.10-1.4-desktop
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 5700 Series 

```
Driver Version:  4.2.12217 Compatibility Profile Context 12.104
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x68be
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 17,05" x 10,67"  (20,08" diag)
                                        43,3cm x 27,1cm  (51,0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  3958 Mb

Miscellaneous:
    UI Language:  English
    LANG:  nl_NL.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  302381 Mb
    Largest Free Hard Disk Block:  243010 Mb

Installed software:

Recent Failure Reports:
    Sun Apr 28 23:41:17 2013 GMT: file ''/tmp/dumps/crash_20130429014116_1.dmp'', upload no: ''HTTP response code said error''
    Fri May  3 00:26:53 2013 GMT: file ''/tmp/dumps/assert_20130503022653_1.dmp'', upload no: ''HTTP response code said error''
    Fri May  3 02:13:58 2013 GMT: file ''/tmp/dumps/assert_20130503041357_1.dmp'', upload no: ''HTTP response code said error''
    Fri May  3 11:46:36 2013 GMT: file ''/tmp/dumps/assert_20130503134626_1.dmp'', upload yes: ''CrashID=bp-c2b365b6-526b-4db1-b8b0-359622130503''
    Fri May  3 20:55:22 2013 GMT: file ''/tmp/dumps/assert_20130503225452_1.dmp'', upload yes: ''CrashID=bp-b1720264-2167-4cfb-a535-007162130503''
    Fri May  3 21:25:40 2013 GMT: file ''/tmp/dumps/assert_20130503232526_1.dmp'', upload yes: ''CrashID=bp-937b3b3c-bcdc-409a-b7e8-319472130503''
    Fri May  3 22:24:04 2013 GMT: file ''/tmp/dumps/assert_20130504002404_2.dmp'', upload no: ''HTTP response code said error''
    Fri May  3 22:48:37 2013 GMT: file ''/tmp/dumps/assert_20130504004837_1.dmp'', upload no: ''HTTP response code said error''
    Sat May  4 00:54:55 2013 GMT: file ''/tmp/dumps/assert_20130504025454_1.dmp'', upload no: ''HTTP response code said error''
    Sat May  4 01:40:45 2013 GMT: file ''/tmp/dumps/assert_20130504034044_1.dmp'', upload no: ''HTTP response code said error''
    Sat May  4 11:38:34 2013 GMT: file ''/tmp/dumps/assert_20130504133828_1.dmp'', upload yes: ''CrashID=bp-85e95e9e-d80d-4410-8413-2dbc62130504''
    Sat May  4 15:19:00 2013 GMT: file ''/tmp/dumps/assert_20130504171846_1.dmp'', upload yes: ''CrashID=bp-7aa5b8ac-7941-4abc-a3c9-968de2130504''
    Sat May  4 20:17:23 2013 GMT: file ''/tmp/dumps/assert_20130504221710_1.dmp'', upload yes: ''CrashID=bp-f949cc80-39b8-4660-9bd0-8457e2130504''
    Sun May  5 14:12:35 2013 GMT: file ''/tmp/dumps/assert_20130505161225_1.dmp'', upload yes: ''CrashID=bp-a87c312f-8b6e-4592-8e1e-b47ea2130505''
    Sun May  5 19:17:26 2013 GMT: file ''/tmp/dumps/assert_20130505211716_1.dmp'', upload yes: ''CrashID=bp-516aad7d-4ebf-4361-955b-0b21d2130505''
    Mon May  6 18:50:40 2013 GMT: file ''/tmp/dumps/assert_20130506205018_1.dmp'', upload yes: ''CrashID=bp-17883ab1-d968-4c6c-8786-7623a2130506''

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
