### ISSUE TITLE
[TF2] [Feature/Bug] Strange cosmetic items don’t track sentry kills as engineer/add a strange part to track specifically sentry or non-sentry kills

### ISSUE THREAD

**Issue by chexo3** [ValveSoftware/Source-1-Games#4970]
Hello! Right now, strange parts for tracking kills on cosmetic items don’t track sentry kills. It would be useful if they did.

It would also be nice to have strange parts that track only sentry and only non-sentry kills too.

Also, I think having a separate part for tracking assists is a bit of a waste. The assist strange part, at least for cosmetics, could be merged with the kills part, turning all existing assist parts into kills parts, and showing both kills and assists in this new part. For weapons I think having them separate still makes sense since weapons track kills by default anyways.

**Comment by kisak-valve** [comment]
Hello @chexo3, this issue is already being tracked at #3558. Closing as a duplicate.

**Comment by chexo3** [comment]
@kisak-valve i swear I searched for an existing issue this time
