### ISSUE TITLE
[TF2] Add The Unused MvM Upgrade Station Song

### ISSUE THREAD

**Issue by phantomboy0** [ValveSoftware/Source-1-Games#4984]
Add The Unused MvM Upgrade Station Song to tf2.
if the real reason it got unusued was play testers got distracted , then only play it between waves.

this is steam workshop submission of it : 
https://steamcommunity.com/sharedfiles/filedetails/?id=2980038601

**Comment by kisak-valve** [comment]
Hello @phantomboy0, this feature request is already being tracked at #4372. Closing as a duplicate.
