### ISSUE TITLE
Half Life 2 on Steam Deck - Unable to Use Console with Virtual Keyboard

### ISSUE THREAD

**Issue by d10sfan** [ValveSoftware/Source-1-Games#4988]
If I open the virtual keyboard in the steam deck when playing Half Life 2, I can hit the tilde (`) key to open the console, and enter key works, but any other characters I type in the virtual keyboard do not actually work as input into the console text field. Since I can click enter and see a new line with "]", the text field appears to be focused correctly, but normal input does not work.

This appears to also happen on some other native games on the deck, but not all, so not sure if it's deck specific or specific to this game for a fix.

**Comment by XLRUUU** [comment]
More precisely the problem happens when playing with the native Linux HL2 build, but when using Proton, the console can be used. The issue may be on the SteamOS side other than on the game side.

**Comment by d10sfan** [comment]
Interesting, for hl2 a bluetooth keyboard also is unable to type. So possible some sort of problem with keyboard input of any kind while using steam input, like the deck's controller? I can click the enter key on both virtual and physical keyboards, but I can't type at all in this console example. Other native games have a similar problem.

**Comment by XLRUUU** [comment]
Strange, how does SteamOS distinguish the keyboard control inputs, and the text inputs, like the game recognize the keypresses for in game binds, but text isn't processed.

**Comment by d10sfan** [comment]
This still happens on 3.5

**Comment by d10sfan** [comment]
Closing in favor of https://github.com/ValveSoftware/SteamOS/issues/1053 since there hasn't been any response here
