### ISSUE TITLE
Winter 2019 War Paint Case missing from the mann co store

### ISSUE THREAD

**Issue by me1053** [ValveSoftware/Source-1-Games#4992]
The Winter 2019 War Paint Case is missing from the mann co store, they key is present as is the Winter 2020 War Paint Case but the Winter 2019 War Paint Case is not. This is fairly self explanatory but I will attach screenshots showing the search results for winter 2019 and winter 2020: 
![20230610141155_1](https://github.com/ValveSoftware/Source-1-Games/assets/46284242/56c9a00b-2096-4ab9-b445-3dc4836af6a4)
![20230610141214_1](https://github.com/ValveSoftware/Source-1-Games/assets/46284242/f76f739c-d445-4a86-b8f2-b7493b6a3e97)

As you can see, only the winter 2019 war paint case is missing.

**Comment by kisak-valve** [comment]
Hello @me1053, per "Fixed the Winter 2019 War Paint Case not being shown in the Mann Co. Store" in the [2023-07-12](https://www.teamfortress.com/post.php?id=206148) Team Fortress 2 update, please retest this issue.
