### ISSUE TITLE
[Feature Request] [TF2] Move ctf_frosty, ctf_haarp, and pl_hacksaw from the smissmas pool to the year-long pool

### ISSUE THREAD

**Issue by RyleiC** [ValveSoftware/Source-1-Games#5000]
ctf_frosty was added in the 2022 Smissmas update, but besides the title of the update, the map has very little festive theming unless being cold counts; The map is very neutral tone wise, with 0 decorations/mechanics that could be really considered as holiday themed, and could very easily pass for a normal map among the casual pool, especially in a category so starved of variety and new content such as Capture the Flag.
I'd also like to bring light to pl_breadspace being a year long map while being significantly more thematically oriented, as well as being another map added on a smissmas update.
Please consider my proposal!

Thank you, Rylei C. 

Update 2024: It seems that maps in a similar situation such as HAARP and Hacksaw are in similar situations to frosty. Seeing how this post was made in advocation for allowing non-themed maps for being added to the year-round mapcycle, I would like to restate that all 3, being frosty, haarp and hacksaw are all not holiday themed and are very well done maps. Putting them in a side list that will only see use roughly one month of the year really undermines the effort and work being put into maps that only similarity with smissmas is having a cold setting.
Thank you again, Rylei C.

**Comment by AzureWoof** [comment]
Can't go wrong with more maps.

**Comment by JoriKos** [comment]
> Can't go wrong with more maps.

Move Wutville to the year-round rotation.

**Comment by AzureWoof** [comment]
> > Can't go wrong with more maps.
> 
> Move Wutville to the year-round rotation.

Maybe not that one. lol
But yeah, if there's any other holiday-locked maps that don't heavily have a holiday theme, I wouldn't mind seeing them added to the regular map rotation.

**Comment by NO-LOAFING** [comment]
Agreed, the map has no actual holiday theming anywhere, and is just a normal non-event map with snow that happened to be added in a Smissmas update. Altitude and Cascade also match that description and fit into the year-long pool just fine, so there's precedent for it!

**Comment by RyleiC** [comment]
> Agreed, the map has no actual holiday theming anywhere, and is just a normal non-event map with snow that happens to be from a Smissmas update. Altitude and Cascade also match that description and fit into the year-long pool just fine, so there's precedent for it!

Aye, my thought process exactly!
Pushing a map to such a niche holiday long pool purely due to coincidence despite being very much just being a cold normal map seems unfortunate

**Comment by Gr4pevine** [comment]
Since the HAARP and Hacksaw requests are getting redirected here I think it's worth reiterating that all three of these maps are fantastic and it'd be great to have them year-round, especially since all three are from some really underappreciated game modes that could always use more maps.

**Comment by RyleiC** [comment]
> Since the HAARP and Hacksaw requests are getting redirected here I think it's worth reiterating that all three of these maps are fantastic and it'd be great to have them year-round, especially since all three are from some really underappreciated game modes that could always use more maps.

I agree, I've added an update

**Comment by JoriKos** [comment]
I think a better solution would be to have a "map request megathread" similar to the VScript issue megathread, have people put their year-round map requests there.

**Comment by RyleiC** [comment]
> I think a better solution would be to have a "map request megathread" similar to the VScript issue megathread, have people put their year-round map requests there.

i'm open to any suggestions

**Comment by Gr4pevine** [comment]
I think it's worth mentioning that Frosty recently became the most popular workshop map of all time. I think this indicates a pretty clear demand for it to return in a more accessible capacity.

**Comment by RyleiC** [comment]
Would we say this is resolved? I'll take a look at the new map pool

**Comment by RyleiC** [comment]
I think we can call this resolved, all maps are now in the casual queue!
thank you everyone who participated in this 🫶
