### ISSUE TITLE
[TF2] [Linux] Game randomly crashes since new steam UI update

### ISSUE THREAD

**Issue by dhalucario** [ValveSoftware/Source-1-Games#5007]
Recently my game started crashing out of nowhere eversince the new steam overlay got pushed. I don't know if it's related to that. I started the game on steam using -console and I got the following error:
`~/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh: line 72: 222339 Bus error               (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

I disabled the new overlay and now it seems to be fine. Also I still have issues with libtcmalloc_minimal not being loaded unless I symlink the version of my system to it in the bin folder.

For the people who also need to do that you can do that using:
`ln -s /usr/lib64/libtcmalloc_minimal.so.4 ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/bin/libtcmalloc_minimal.so.4`

Here is a copy of my steam system information:
https://termbin.com/f3dp

Do you need any of the crashdumps?

**Comment by kisak-valve** [comment]
Hello @dhalucario, this issue is already being tracked at #4976 / https://github.com/ValveSoftware/steam-for-linux/issues/9586. Closing as a duplicate.

**Comment by dhalucario** [comment]
Hello @kisak-valve do you know by any chance if there is also an issue for the libtcmalloc_minimal problem?
