### ISSUE TITLE
Tf2 linux broken cosmetics if you shift tab whilst loading the item

### ISSUE THREAD

**Issue by xellpid** [ValveSoftware/Source-1-Games#5009]
on the loadout menu for heavy if you open the new steam overlay when running tf2 linux and while loading cosmetics the cosmetics will appear to have a broken texture in this example the texture of my steams friends list this bug is purely cosmetic but i thought to report it regardless 
![shot-2023-06-30_00-15-00](https://github.com/ValveSoftware/Source-1-Games/assets/102343489/89660a46-c19f-496c-ae81-2ecd93a13843)

**Comment by CaptainOsaka** [comment]
i should probably add im running the game via flatpak on gentoo

**Comment by Tiagoquix** [comment]
OP, does this still happen with the new Vulkan render?

**Comment by kisak-valve** [comment]
Closing pending feedback.
