### ISSUE TITLE
[TF2] Ubuntu 23.04 - chance to crash on getting an achievement

### ISSUE THREAD

**Issue by DrinkFromTheCup** [ValveSoftware/Source-1-Games#5010]
Open the game.
Start playing.
Get some achievement.
With relatively low chance, game crashes to desktop.
No mods nor CLI options in the game. The only change to Ubuntu - replaced ALL snap packages with non-snaps where possible.
Lenovo IdeaPad L340-15API, SSD-less.

**Comment by kisak-valve** [comment]
Hello @DrinkFromTheCup, this is the same issue as #4976. Closing as a duplicate.
