### ISSUE TITLE
[Linux] All Source 1 games have recently started freezing for 5 seconds every 10-20 minutes of gameplay

### ISSUE THREAD

**Issue by DaneelaArt** [ValveSoftware/Source-1-Games#5011]
OS: Arch Linux
KERNEL: 6.3.9-arch1-1
CPU: 11th Gen Intel Core i5-11400 @ 2.60GHz
GPU: AMD Radeon RX 6500 XT (navi24, LLVM 15.0.7, DRM 3.52, 6.3.9-arch1-1)
GPU DRIVER: 4.6 Mesa 23.1.3
RAM: 16 GB

My only clue as to why this could be happening is mesa, but i haven't found anyone on Arch or otherwise who shares my issue and i haven't received any leads from my report in two weeks, so i don't think they have much of a clue either. I've tested TF2, L4D2 (both ogl and vulkan), and Portal 2 and i always get these sound looping freezes, so it's safe to say all Source 1 games are affected.

**Comment by IsaccBarker** [comment]
Not a developer, but had this problem a while ago. I ended up downgrading my kernel to 5.9. Do the kernel logs say anything useful (run `sudo dmesg` after a freeze)?

**Comment by DaneelaArt** [comment]
> Not a developer, but had this problem a while ago. I ended up downgrading my kernel to 5.9. Do the kernel logs say anything useful (run `sudo dmesg` after a freeze)?

i have run dmesg already before and after the freeze, nothing gets added to it

**Comment by DaneelaArt** [comment]
updating to kernel 6.4.2 today seems to have fixed it, played a full session of tf2 and l4d2 and didn't get a single freeze

**Comment by kisak-valve** [comment]
Closing per the last comment.
