### ISSUE TITLE
[TF2 on Linux] The main menu is not displayed at all

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#5013]
Distro: Linux Mint 19 Xfce

When starting the native version of the game, the main menu is not displayed at all. There are only sounds when hovering over and clicking on invisible buttons.

It feels like a full-screen image pops out on top of everything else in the game window. Watch the video on YouTube: https://www.youtube.com/watch?v=Gi5ZAwDuHiE

**Comment by kisak-valve** [comment]
Hello @AdamFreemen, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by AdamFreemen** [comment]
@kisak-valve Hello. Here: https://gist.github.com/AdamFreemen/61e6c820c3366b22b32efa4d6599f1f9
