### ISSUE TITLE
[TF2] Neon Annihilator doesn't interact with players doused with gas from Gas Passer

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#5014]
### Description
If you douse a player with gas using the Gas Passer, hitting them with the Neon Annihilator while the gas condition is active, doesn't perform a guaranteed critical hit on them.
This definitely seems to be a bug or oversight, as the Pyro having both weapons available opens a fun synergy for these two weapons. The description for the Neon Annihilator notes that it 100% crits wet players.

### Reproduction
Throw the Gas Passer on an enemy player.
Hit them with the Neon Annihilator.
Note that the player isn't critically hit, even though you can observe the gas particles dripping from the player.

[Example Video \(uploaded with author's permission\)](https://youtu.be/zMvhPmD1nOA)

### Suggested fix
Set the Gas Passer condition to crit on hit with the Neon Annihilator, just like with the Jarate/Mad Milk conditions.

Thanks for reading the report.

**Comment by kisak-valve** [comment]
Hello @agrastiOs, this issue is already being tracked at #4592. Feel free to add a comment on the older issue report.

Closing as a duplicate.
