### ISSUE TITLE
[TF2] Opening the in-game Achievement menu crashes the game

### ISSUE THREAD

**Issue by mtxfellen** [ValveSoftware/Source-1-Games#5023]
Trivial to reproduce, as the title describes.
Console outputs `LoadControlSettings failed! Invalid resource filename!` before crashing.

**Comment by Ashetf2** [comment]
Still not fixed in the latest patch

**Comment by AwesomeCoder412412** [comment]
Needs a retest as of latest patch

https://www.teamfortress.com/post.php?id=206293

@kisak-valve

**Comment by Ashetf2** [comment]
It has been fixed. Closing.

**Comment by FindTheBorealis** [comment]
This has been fixed for me.

**Comment by mtxfellen** [comment]
Closing given that I can no longer find any reports that this issue is still occurring.
