### ISSUE TITLE
[TF2] VSH maps crashes the server in Casual

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#5025]
Title. Please fix asap

**Comment by Ashetf2** [comment]
supposedly due to Vscript being disabled in casual servers

**Comment by Joaquel** [comment]
Apparently, the public servers already had VScript enabled, they even tested them in Valve's Private servers before they added them and they worked fine.

**Comment by HueyCan** [comment]
The crashing has been fixed but now the game is unable to randomly select a player as Hale and the game softlocks even when all of RED is dead.

**Comment by kisak-valve** [comment]
Hello @HueyCan, please open a new issue report so that your follow up issue can be tracked properly.
