### ISSUE TITLE
Entering first BLU spawn on RED in pl_cashworks

### ISSUE THREAD

**Issue by Farkoz** [ValveSoftware/Source-1-Games#5026]
So yeah.
You can enter the first BLU spawn while on RED
thats it.

**Comment by kisak-valve** [comment]
Hello @Farkoz, per "Fixed Red being able to enter the Blu spawn room on pl_cashworks" in the second [2023-07-12](https://www.teamfortress.com/post.php?id=206198) Team Fortress 2 update, please retest this issue.

**Comment by aarmastah** [comment]
Issue is resolved.
