### ISSUE TITLE
Pelican peak VSH glitch

### ISSUE THREAD

**Issue by Turbogrease** [ValveSoftware/Source-1-Games#5029]
When you load of a map of pelican peak or any of the new maps it has the ready up system of the VSH Gamemode

![image_2023-07-12_224310703](https://github.com/ValveSoftware/Source-1-Games/assets/139408805/aaf2472b-fc9a-4806-94f5-a7c6829515dd)

**Comment by rabscootle** [comment]
Duplicate of #5027 

Bug is normal behavior after user has played a match on official servers. It's a side effect from their use of tournament mode features.

**Comment by kisak-valve** [comment]
Closing as a duplicate.
