### ISSUE TITLE
Visable No-Draw in pl_venice.bsp [TF2]

### ISSUE THREAD

**Issue by RyleiC** [ValveSoftware/Source-1-Games#5031]
![afbeelding](https://github.com/ValveSoftware/Source-1-Games/assets/78452008/49f8e28d-2706-472f-8122-b593b9e6d8e8)
An open noclip brush can be seen in the playfield.
This is at
"setpos 6933.061523 5959.249023 2229.980225;setang -15.052433 14.122795 0.000000"

**Comment by NULLYUKI** [comment]
With patch [207059](https://www.teamfortress.com/post.php?id=207059) this issue should be fixed now and requires retesting.
I'm not sure which one of these fixes/changes could be stating this issue, but retesting it should make it clear if its fixed now or not.

**Comment by NULLYUKI** [comment]
> With update [207059](https://www.teamfortress.com/post.php?id=207059) this issue should be fixed now and requires retesting. I'm not sure which one of these fixes/changes could be stating this issue, but retesting it should make it clear if its fixed now or not.

This issue has now been fixed and this issue can now be closed.
![20230729195048_1](https://github.com/ValveSoftware/Source-1-Games/assets/42326194/97cf26ae-8b9c-4db5-95ca-af8cbcabfd57)
