### ISSUE TITLE
Counter Strike Source game fails on startup

### ISSUE THREAD

**Issue by foxandr** [ValveSoftware/Source-1-Games#5033]
#### Your system information

* Steam client version (build number or date): 1689034492 (2023-07-11)
* Distribution (e.g. Ubuntu): Debian Testing
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12036010/steam-logs.tar.gz)
* GPU: AMD AMD Radeon RX 5600 XT (navi10, LLVM 16.0.3, DRM 3.53, 6.1.0-9-amd64)
* Video driver: 4.6 (Compatibility Profile) Mesa 23.2.0-devel
* OpenGL: 4.6

#### Please describe your issue in as much detail as possible:
Steam was update to the latest version two days ago. I'm not able to launch Counter Strike Source anymore after this update. The game crashes immediately after start without any message. But it worked well, because I launched successfully the game at the same day before update. Other games launch well after update - Counter Strike Global Offensive or Worms Clan Wars for example.

#### Steps for reproducing this issue:

1. Open updated to 1689034492 version stream app
2. Go to the game library
3. Try to launch Counter Strike Source
4. The game crashed immediately

I found in the logs this:
> /home/fox/.steam/steamapps/common/Counter-Strike Source/hl2.exe: 1: Syntax error: **Unterminated quoted string**

I attached two more files: 
[steam output after the launching from console](https://github.com/ValveSoftware/steam-for-linux/files/12036105/steam_ccs_launch.log) & [info about my system](https://github.com/ValveSoftware/steam-for-linux/files/12036145/system_info.txt)

**Comment by ViNi-Arco** [comment]
Hi, yeah, I went to open the native CS:Source here and it closes with this warning:
`src/tcmalloc.cc:278] Attempt to free invalid pointer 0xa717ad0`

**<details><summary>Click here to see part of Stack trace of thread</summary>**
<p>

#0  0x00000000f7f9e509 __kernel_vsyscall (linux-gate.so.1 + 0x509)
                #1  0x00000000f7d5ba17 n/a (libc.so.6 + 0x8ea17)
                #2  0x00000000f7d08317 raise (libc.so.6 + 0x3b317)
                #3  0x00000000f7cef121 abort (libc.so.6 + 0x22121)
                #4  0x00000000f7f0de8a _ZN8tcmalloc3LogENS_7LogModeEPKciNS_7LogItemES3_S3_S3_ (libtcmalloc_minimal.so.4 + 0xfe8a)
                #5  0x00000000f7f0935d InvalidFree (libtcmalloc_minimal.so.4 + 0xb35d)
                #6  0x00000000f7f1a762 free_null_or_invalid (libtcmalloc_minimal.so.4 + 0x1c762)
                #7  0x00000000eae34bd0 _ZN4llvm17deallocate_bufferEPvjj (libLLVM-16.so + 0x836bd0)
                #8  0x00000000eb10a8de _ZN4llvm12PassRegistry12registerPassERKNS_8PassInfoEb (libLLVM-16.so + 0xb0c8de)
                #9  0x00000000ede71338 n/a (libLLVM-16.so + 0x3873338)
                #10 0x00000000eb016a77 _ZZNSt9once_flag18_Prepare_executionC4IZSt9call_onceIRFPvRN4llvm12PassRegistryEEJSt17reference_wrapperIS5_EEEvRS_OT_DpOT0_EUlvE_EERSC_ENUlvE_4_FUNEv (li
bLLVM-16.so + 0xa18a77)
                #11 0x00000000f7d5ecda n/a (libc.so.6 + 0x91cda)                                                                                                                               
                #12 0x00000000ede765eb n/a (libLLVM-16.so + 0x38785eb)                                                                                                                         
                #13 0x00000000edcade64 LLVMInitializeAMDGPUTarget (libLLVM-16.so + 0x36afe64)                                                                                                  
                #14 0x00000000f3b9d1d7 n/a (radeonsi_dri.so + 0x79c1d7)                                                                                                                        
                #15 0x00000000f7d5ecda n/a (libc.so.6 + 0x91cda)                                                                                                                               
                #16 0x00000000f3ba6ac2 ac_init_shared_llvm_once (radeonsi_dri.so + 0x7a5ac2)                                                                                                   
                #17 0x00000000f345cf9e n/a (radeonsi_dri.so + 0x5bf9e)                                                                                                                         
                #18 0x00000000f3a2bb21 n/a (radeonsi_dri.so + 0x62ab21)
                #19 0x00000000f3453ca4 n/a (radeonsi_dri.so + 0x52ca4)
                #20 0x00000000f3454204 n/a (radeonsi_dri.so + 0x53204)
                #21 0x00000000f5195af9 n/a (libGLX_mesa.so.0 + 0x4faf9)
                #22 0x00000000f51790b8 n/a (libGLX_mesa.so.0 + 0x330b8)
                #23 0x00000000f5179652 n/a (libGLX_mesa.so.0 + 0x33652)
                #24 0x00000000f5179794 n/a (libGLX_mesa.so.0 + 0x33794)
                #25 0x00000000f5bb8fd6 n/a (libSDL2-2.0.so.0 + 0xb9fd6)
                #26 0x00000000f5bb9205 n/a (libSDL2-2.0.so.0 + 0xba205)
                #27 0x00000000f5bac769 n/a (libSDL2-2.0.so.0 + 0xad769)
                #28 0x00000000f5bae271 n/a (libSDL2-2.0.so.0 + 0xaf271)
                #29 0x00000000f5badf7e n/a (libSDL2-2.0.so.0 + 0xaef7e)
                #30 0x00000000f5b0b4f9 n/a (libSDL2-2.0.so.0 + 0xc4f9)
                #31 0x00000000f5b3a808 SDL_Init (libSDL2-2.0.so.0 + 0x3b808)
                #32 0x00000000f62c851c n/a (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0x3251c)
                #33 0x00000000f62c8b5f n/a (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0x32b5f)
                #34 0x00000000f62c8bd6 n/a (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0x32bd6)
                #35 0x00000000f62a46ea n/a (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0xe6ea)
                #36 0x00000000f62c431e n/a (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0x2e31e)
                #37 0x00000000f62c45c8 n/a (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0x2e5c8)
                #38 0x00000000f62c45e0 n/a (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0x2e5e0)
                #39 0x00000000f62a5dbd LauncherMain (/SteamLibrary/steamapps/common/Counter-Strike Source/bin/launcher.so + 0xfdbd)
                #40 0x000000000804877b main (hl2_linux + 0x77b)
                #41 0x00000000f7cf0af9 n/a (libc.so.6 + 0x23af9)
                #42 0x00000000f7cf0bbd __libc_start_main (libc.so.6 + 0x23bbd)
                #43 0x00000000080488bd _start (hl2_linux + 0x8bd)
                ELF object binary architecture: Intel 80386

</p>
</details>

So, had the idea to replace the libtcmalloc that comes with CS:Source, build the latest [gperftools](https://github.com/gperftools/gperftools/releases/tag/gperftools-2.13) now, then replace the `libtcmalloc_minimal.so.4`  with what I build locally and the game starts normal..


I used these flags when building gperftools and did not strip, debug build:
  export CFLAGS='-Og -g2 -DDEBUG -march=pentium4 -mtune=haswell'
  export CXXFLAGS='-Og -g2 -DDEBUG -march=pentium4 -mtune=haswell'
  export LDFLAGS='-Wl,--as-needed,--build-id=sha1'

**Comment by kisak-valve** [comment]
Hello @ViNi-Arco, your issue is #5043 instead of this issue report.
