### ISSUE TITLE
[TF2] Horseless Headless Horseman body fire particle has been broken due a coding mistake.

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [ValveSoftware/Source-1-Games#5035]
This issue is kind of related to #4383 but with a solution: after the 2015 update the HHH lost its body flame, it was speculated that it was because of valve removing it, but in reality, is it was by mistake here's a brief [explanation:](https://steamcommunity.com/sharedfiles/filedetails/?id=2997356338)

> For some unknow reason after the invasion updated The Horseless Headless Horseman lost its body
> flame particle, while it was speculated that it was removed because of visibility reasons, in reality this was by
> mistake, since the particles of it do exist albeit it only exists for a fraction of a frame when the entity spawns, the fix
> was from moving it from the clientside's Spawn() function:

> ```CPP
> void C_HeadlessHatman::Spawn( void )
> {
> 	// Some other code
> 
> 	if ( !m_ghostEffect )
> 	{
> 		m_ghostEffect = ParticleProp()->Create( "ghost_pumpkin", PATTACH_ABSORIGIN_FOLLOW );
> 	}
> 
> 	// Some other code
> }
> ```

> to ClientThink() since that's how to properly spawn a particle client-side in the engine.

> ```CPP
> void C_HeadlessHatman::ClientThink( void )
> {
> 	// Some other code
> 
> 	if ( !m_ghostEffect )
> 	{
> 		m_ghostEffect = ParticleProp()->Create( "ghost_pumpkin", PATTACH_ABSORIGIN_FOLLOW );
> 	}
> 
> 	// Some other code
> }
> ```

This means that at some point the particle mas mistakenly moved from ClientThink() to Spawn() meaning the particle only would be live for a fraction of a frame.

**Comment by kisak-valve** [comment]
Hello @FriskTheFallenHuman, as you noted, this issue is already being tracked at #4383. Since this issue report adds some more details for a Source 1 Dev to ponder, I've transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/4383.

Closing as a duplicate.
