### ISSUE TITLE
[TF2] [Feature Request] Revert Original's reload sound change

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#5046]
The "fixed" reload sound is nearly unaudible because of its quality. The previous reload sound of the Rocket Launcher was ok.

**Comment by FriskTheFallenHuman** [comment]
or just increase the volume of the audio

**Comment by Ashetf2** [comment]
> or just increase the volume of the audio

The issue is the sound quality, not the volume, and you can't just turn the volume up without it sounding bad. The old one was fine.

**Comment by Platina6978** [comment]
I personally haven't really noticed quality issues with it and quite like the original sounding different from the default. I'm also not much of an audophile and don't have the best setup sound-wise so there's that.
