### ISSUE TITLE
[TF2] Sound cache corruption with packed audio files in maps

### ISSUE THREAD

**Issue by aarmastah** [ValveSoftware/Source-1-Games#5049]
When maps with packed audio files are updated several times, audio files with the same names (even when identical) eventually fail to play over and over and lead to a memory leak. This is currently occurring on the new VSH maps in the game and previously occurred on cp_gravelpit_snowy, but I was able to work around the issue simply by renaming the folder the sounds were in every time I updated said map.

I have provided a video of me replicating the issue:
https://www.youtube.com/watch?v=OYCWkvUWmIs

Reproduction steps:

1. Decompile vsh_distillery and unpack its assets
2. Rename the vmf file to vsh_distillery_dev.vmf
3. Rename any applicable soundscapes, sound scripts, etc to match the name of the vmf
4. Compile the map (fast is fine) and pack the content afterward
5. Play the map in game
6. Make a minor change to the map and repeat steps 4-5
7. Make a minor change to the map and repeat steps 4-5
8. Make a minor change to the map and repeat steps 4-5 (in the video, this specific step was accomplished with a simple **bspzip.exe -repack -compress**)
If done correctly, the sounds will eventually fail to play altogether and the game will crash due to being out of memory.

LizardOfOz (one of the developers of VSH) has been notified of the workaround.

**Comment by kisak-valve** [comment]
Hello @aarmastah, this reads like the issue being tracked at #4813. Closing in favor of the older issue report.
