### ISSUE TITLE
[TF2] Valve Tokyo srcds1154 servers take so many server lags

### ISSUE THREAD

**Issue by hamnTF2** [ValveSoftware/Source-1-Games#5051]
Since 2022(or 2021), server lag has come to the Tokyo srcds1154 server and players have suffered from it. At least there is less lag on casual or competitive server but on MvM server, players can't continue mission and be disconnected due to Lost Connection timer.

Tokyo servers are the only Valve official server that Japanese and Korean can play on, so it needs to fix.

(Strangely enough, Tokyo srcds2154 server doesn't lack)

![20230717225440_1](https://github.com/ValveSoftware/Source-1-Games/assets/110222364/d7874bc2-1bd5-42a5-85d5-67c28542a1cc)

![20230717232008_1](https://github.com/ValveSoftware/Source-1-Games/assets/110222364/fbff1852-1dbe-4865-8e87-b5d0fa4046e5)

**Comment by gaelcoral** [comment]
This!
And also this issue happens even when I'm the only one on the server.

https://github.com/ValveSoftware/Source-1-Games/assets/63524243/d9d92d55-9cca-46cc-a3df-5f21122a83f5

https://github.com/ValveSoftware/Source-1-Games/assets/63524243/51245695-096c-4278-9989-21efd69dc473

**Comment by LandmineSoldier** [comment]
![20230722235732_1](https://github.com/ValveSoftware/Source-1-Games/assets/61589535/bb441de6-fec2-44c1-b70f-4a9afb0f2e13)
Tokyo 1154 server stopping can appear in mvm too. It can make disconnect players by timeout.

**Comment by Estima779** [comment]
![スクリーンショット 2023-11-10 010215](https://github.com/ValveSoftware/Source-1-Games/assets/147479114/e7bd3df4-a129-451e-b9ae-5e04b3dd9b9e)
![スクリーンショット 2023-11-10 010231](https://github.com/ValveSoftware/Source-1-Games/assets/147479114/f9b1d68f-966f-49bf-a614-a7af729ed8ec)

Good news, guys.
Today, I've noticed that Valve has replaced both "Tokyo srcds1154" and "Tokyo srcds2154" servers with 
new servers "Tokyo srcds1011" and "Tokyo srcds2011" without any public announcement.
I actually have played a few casual matches and both servers seem to be stable so far.
It is a great day for TF2 players in Asia! Thanks Valve.

**Comment by LandmineSoldier** [comment]
> ![スクリーンショット 2023-11-10 010215](https://user-images.githubusercontent.com/147479114/281793276-e7bd3df4-a129-451e-b9ae-5e04b3dd9b9e.png) ![スクリーンショット 2023-11-10 010231](https://user-images.githubusercontent.com/147479114/281793350-f9b1d68f-966f-49bf-a614-a7af729ed8ec.png)
> 
> Good news, guys. Today, I've noticed that Valve has replaced both "Tokyo srcds1154" and "Tokyo srcds2154" servers with new servers "Tokyo srcds1011" and "Tokyo srcds2011" without any public announcement. I actually have played a few casual matches and both servers seem to be stable so far. It is a great day for TF2 players in Asia! Thanks Valve.

Holy mary mother of Joseph

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/Source-1-Games/issues/5051#issuecomment-1804131789.
