### ISSUE TITLE
[TF2] [VSH] Diamondback does not give user crits after backstabbing Saxton Hale

### ISSUE THREAD

**Issue by slender100** [ValveSoftware/Source-1-Games#5059]
Same as https://github.com/ValveSoftware/Source-1-Games/issues/5058 except its with the Diamondback not giving the user it's on-kill effect.

**Comment by Chdata** [comment]
Fixed as of the latest update!

**Comment by slender100** [comment]
> Fixed as of the latest update!

Issue is now fixed, closing.
