### ISSUE TITLE
[L4D2] Mouse Grab Issue in Linux

### ISSUE THREAD

**Issue by xebectux** [ValveSoftware/Source-1-Games#506]
On rare occasion, when I complete a level and continue on the next one, the level starts without the mouse captured.  I can see the WM cursor, and movement is still registered in game, but minimally so.  I can look about 30 degrees in any direction.  If I hit ESC twice, the mouse is recaptured and play continues normally.

I am running LFD2 in fullscreen mode with one monitor.

I am running Arch Linux AMD64.

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.11-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11401000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660/PCIe/SSE2
    Driver Version:  4.3.0 NVIDIA 313.30

**Comment by kisak-valve** [comment]
Closing as fixed.
