### ISSUE TITLE
[TF2] VSH Mode assigns you to the opposing team when you shouldn't be there on Casual Mode 

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#5061]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/fb190b93-237e-4068-868c-f8377b1dfea2)
![2023-07-20 (18)](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/f267701f-e4c1-4c8d-b349-001e712a7151)

**Comment by AzureWoof** [comment]
Yup, worked fine for a few rounds. But then this happened. Saxton Hale can also be assigned as a RED team member, in which case the game will last forever until RED team's Saxton Hale somehow dies. If the entirety of BLU team dies in this instance, the game will not end.

**Comment by Ashetf2** [comment]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63692647/62091c99-37b6-4b0d-986a-44c9a9416216)

This appears before the bug occurs

**Comment by gaelcoral** [comment]
Still broken on this map (Distillery)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/ead196bd-42ef-464f-a91c-382b87700804)

**Comment by Ashetf2** [comment]
Now that there's no timelimit it doesn't seem to happen anymore
