### ISSUE TITLE
[TF2] Community VSH (Casual mode) seems to be infinite

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#5067]
Judging by the configuration files, there is no limit imposed on any of these ConVars:
```
mp_maxrounds
mp_timelimit
mp_windifference
mp_windifference_min
mp_winlimit
```
I didn't test it, but I think this makes the matches infinite, causing players not to receive XP and map switching not to occur.

I would suggest `mp_maxrounds 10` to fix this possible issue.

**Comment by FindTheBorealis** [comment]
This is likely a temporary fix to address issues with the game coordinator and VSH mode.
