### ISSUE TITLE
[TF2] [Feature Request] Add strangifiers to the case bonus unbox pool

### ISSUE THREAD

**Issue by renimg** [ValveSoftware/Source-1-Games#5068]
With the discontinuation of the crate system in 2016 with Meet your Match, stranges, by proxy have also been discontinued for weapons outside of War Paints. And with not every item being War Paintable, there are a number of items that haven't exist in strange since as early as 2011. If strangifiers for almost every weapon were added into the bonus unbox pool, it would allow for all previously existing strange weapons to continue to be unboxable, while also introducing items that don't have strange variants alongside allowing for people to strangify their existing vintage/genuine/collector's items.

All that would really need to be done is a copy-paste of the killstreaker template in items_game but with a replacement of text to point to the strangifier template, except for the exclusion of the case specific items (batsaber, shooting star, giger counter) and the bread/festive weapons. While also adding in the items that are missing killstreak sets.

There have been a few requests in the past to add JI items to the unbox pool, or to make a new set of strangifiers that use metal, but I feel like just adding all items to the strangifier tool makes the most sense just due to all the old crates being discontinued.

**Comment by kisak-valve** [comment]
Hello @renimg, this feature request is already being tracked at #4284. Closing as a duplicate.

**Comment by renimg** [comment]
Hello @kisak-valve, that submission is slightly different from this one. That one is specifically requesting the jungle inferno items be added to the strangifiers/bonus unbox pool, this one is for every item to be added to the strangifier bonus unbox pool.

**Comment by kisak-valve** [comment]
My understanding of the discussion on #4284 is that it immediately moved to broaden the scope of the request to cover several other strangifier compatible items as well.
