### ISSUE TITLE
[TF2] Custom map particles that replace vanilla particles do not work in sv_pure 1

### ISSUE THREAD

**Issue by HueyCan** [ValveSoftware/Source-1-Games#5069]
Despite the fact that BSP-packed content can override vanilla game content, this doesn't seem to be the case for custom particle effects that replace vanilla particle effects when running an sv_pure 1 server. The most notable example is in VScript VSH where there's custom particle effects for getting jarated and marked for death intended for better visibility. Since those custom particle effects aren't there, debuffs much harder to notice.

Marked for death effect in sv_pure 0
![vsh_skirmish0010](https://github.com/ValveSoftware/Source-1-Games/assets/31521545/b9db28ad-8568-4a4c-838f-50534f1cfa48)

Marked for death effect in sv_pure 1
![vsh_skirmish0016](https://github.com/ValveSoftware/Source-1-Games/assets/31521545/eaecd05c-4cac-4c77-9c4a-3ce5fa51bc33)

Jarate effect in sv_pure 0
![vsh_skirmish0018](https://github.com/ValveSoftware/Source-1-Games/assets/31521545/72460c66-718d-4057-aea5-25523dc66609)

Jarate effect in sv_pure 1
![vsh_skirmish0017](https://github.com/ValveSoftware/Source-1-Games/assets/31521545/88f78d31-422d-46ed-96aa-6633b3422f7e)

**Comment by Ashetf2** [comment]
Probably fixed in today's update: "Fixed packed replacement materials/textures/models in a custom map could leak into other maps or rendering as wireframe". Please retest

**Comment by HueyCan** [comment]
@Ashetf2 Can
