### ISSUE TITLE
[TF2] Descriptions of the Saxton control buttons are not displayed in the casual

### ISSUE THREAD

**Issue by impale1** [ValveSoftware/Source-1-Games#5075]
Casual
![vshhudbug2](https://github.com/ValveSoftware/Source-1-Games/assets/117596825/8642b7da-6208-45c7-9ca8-a64549758ef2)
Local server
![vshhudbug](https://github.com/ValveSoftware/Source-1-Games/assets/117596825/c2c4d4f9-d00c-4bf9-9bf7-ca09bebe1208)

**Comment by AzureWoof** [comment]
I was wondering why it seemed like certain people weren't understanding the controls. I guess I just didn't notice them being missing in Casual.

**Comment by kisak-valve** [comment]
Closing per the last comment.
