### ISSUE TITLE
Can't Start TF2 or Garry's Mod

### ISSUE THREAD

**Issue by T0m0ko** [ValveSoftware/Source-1-Games#5079]
I would press "Play" and then it will *attempt to start* but then instantly shut down. I'm confused as to why this is going on.

Apologies for the lack specification, for some reason I can't add a distro label on mobile but I'm using Gentoo

**Comment by kisak-valve** [comment]
Hello @T0m0ko, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by T0m0ko** [comment]
https://gist.github.com/T0m0ko/ca6b3efcb7347b218e9b1566052ebf0b

@kisak-valve

**Comment by kisak-valve** [comment]
Thanks, LLVM 16 is the key detail here `Driver: AMD AMD Radeon RX 6600 XT (navi23, LLVM 16.0.6, DRM 3.49, 6.1.38-gentoo-dist)`.

There's an issue between the game bundled libtcmalloc and drivers which are linked against llvm 16. This issue is already being tracked at #5043.

Closing as a duplicate.
