### ISSUE TITLE
[TF2] Ubuntu 23.04 - can't buy anything, Steam overlay crash

### ISSUE THREAD

**Issue by DrinkFromTheCup** [ValveSoftware/Source-1-Games#5080]
https://gist.github.com/DrinkFromTheCup/18eb859599753431d461574d2a434925

I enable Steam Overlay.
I restart the game.
I try to buy, let's say, Bread Space Map Stamp.
I attempt a checkout.

ER:
cash deducted, items invoiced

AR:
the game hangs at checkout attmept pop-in, presumably waiting for Steam overlay proc
Steam overlay presumably crashes (attempts to show overlay browser screen or something then disappears quickly)
Attempt to open Steam overlay opens Steam itself (shift+tab works like alt+tab or something)

TF2: today's latest
Steam Beta opted-in
No mods, no BS
CLI options tried:
`-32bit -fullscreen -nodev -noff -novid`

P. S. I can't believe that purchase blocking bug made it into release client.

**Comment by kisak-valve** [comment]
Hello @DrinkFromTheCup, this issue is already being tracked at #4976. Closing as a duplicate.

You might be able to avoid this issue by switching the Steam client to Big Picture mode before starting the game.

**Comment by DrinkFromTheCup** [comment]
My, that's antique (given the effect it causes).
Well, at least this particular consequence is search'able now.
So be it.
