### ISSUE TITLE
[TF2] [Feature request] Extend the number of rounds on VSH

### ISSUE THREAD

**Issue by HueyCan** [ValveSoftware/Source-1-Games#5089]
Currently, there's a maximum of 3 rounds that can be played in Casual VSH (2 if either team gets another win after the first round) and it's way too short since games in VSH go by fairly quickly compared to other gamemodes like payload. It should possibly be around 5 rounds for each team making up a maximum of 9 potential rounds to be played in VSH.

**Comment by okamiterasu** [comment]
I feel like this could be turned into a larger feature request for allowing casual servers to continue uninterrupted on a map until a different map is voted for.

**Comment by JoriKos** [comment]
> I feel like this could be turned into a larger feature request for allowing casual servers to continue uninterrupted on a map until a different map is voted for.

There used to be an "extend current map" vote IIRC, that can be brought back as a global vote.

**Comment by NULLYUKI** [comment]
> > I feel like this could be turned into a larger feature request for allowing casual servers to continue uninterrupted on a map until a different map is voted for.
> 
> There used to be an "extend current map" vote IIRC, that can be brought back as a global vote.

Yes, there is a "Extend current map" vote feature. 
I was able to find it mentioned in the Wiki "[Voting](https://wiki.teamfortress.com/wiki/Voting)" and in the patch notes "[18553](https://www.teamfortress.com/post.php?id=18553)"

**Comment by Ashetf2** [comment]
> > > I feel like this could be turned into a larger feature request for allowing casual servers to continue uninterrupted on a map until a different map is voted for.
> > 
> > 
> > There used to be an "extend current map" vote IIRC, that can be brought back as a global vote.
> 
> Yes, there is a "Extend current map" vote feature. I was able to find it mentioned in the Wiki "[Voting](https://wiki.teamfortress.com/wiki/Voting)" and in the patch notes "[18553](https://www.teamfortress.com/post.php?id=18553)"
> 
> However I was not able to find the reason, why it is no longer available in the game.

Because Valve added Casual and limited payload to 1 attack and 1 defense, similarly to Overwatch back in 2016

**Comment by okamiterasu** [comment]
> However I was not able to find the reason, why it is no longer available in the game.

TF2 was trying to be an "E-sport" at one point, and the standard "E-sport format" is people get matched into a server, they play either one full game or best of three, and then everyone leaves to get matched again.

**Comment by Thespikedballofdoom** [comment]
It would be nice to have a timer on the payload just to know which side wins rather than who gets blue last, but extending maps is a lot better and more important IMO

**Comment by HueyCan** [comment]
The [July 27, 2023](https://www.teamfortress.com/post.php?id=207059) Patch supposedly had VSH use maxrounds (which is 25 by default) instead of winlimit but VSH still uses winlimit
![patch](https://github.com/ValveSoftware/Source-1-Games/assets/31521545/782293c2-0174-4dc1-bb5b-fce8d079112e)

**Comment by NULLYUKI** [comment]
> The [July 27, 2023](https://www.teamfortress.com/post.php?id=207059) Patch supposedly had VSH use maxrounds (which is 25 by default) instead of winlimit but VSH in Casual still uses winlimit ![patch](https://user-images.githubusercontent.com/31521545/256693305-782293c2-0174-4dc1-bb5b-fce8d079112e.png)

For better tracking, I think this should be posted as a separate issue.

**Comment by slender100** [comment]
> > The [July 27, 2023](https://www.teamfortress.com/post.php?id=207059) Patch supposedly had VSH use maxrounds (which is 25 by default) instead of winlimit but VSH in Casual still uses winlimit ![patch](https://user-images.githubusercontent.com/31521545/256693305-782293c2-0174-4dc1-bb5b-fce8d079112e.png)
> 
> For better tracking, I think this should be created as a separate issue.

I've created this as a separate issue [here,](https://github.com/ValveSoftware/Source-1-Games/issues/5095) which is open for discussion as to how long `maxrounds` should be when/if it gets implemented.

**Comment by slender100** [comment]
As of the most recent update with the change `Fixed VSH Casual servers using "mp_winlimit 2" instead of "mp_maxrounds 25" `, the limit is even longer than the proposed one, which is more reasonable due to the fact that it gives everyone in a full server a chance to play as Saxton in VSH! 😊

**Comment by HueyCan** [comment]
Casual now uses `mp_maxrounds 25`
Closing as the request has been made
