### ISSUE TITLE
[Counter-Strike: Source] Master Server is filled with fake servers

### ISSUE THREAD

**Issue by tyabus** [ValveSoftware/Source-1-Games#5127]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/19637128/9507e144-a0fd-469e-a30c-4fe30acad2d3)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/19637128/88191113-903e-4ab4-a380-838d0ad864ac)

**Comment by tyabus** [comment]
Two of the servers:

![image](https://github.com/ValveSoftware/Source-1-Games/assets/19637128/6fb6bc46-15e0-44f4-9e2d-45ab80a55878)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/19637128/c9d5d663-9e9b-4a23-98ab-e47c7d23d522)

**Comment by kisak-valve** [comment]
Hello @tyabus, this issue is already being tracked at #5101. Closing as a duplicate.
