### ISSUE TITLE
[TF2] Scoreboard fails to assign Assist for certain Pyroland Cosmetics

### ISSUE THREAD

**Issue by ArtKitCat** [ValveSoftware/Source-1-Games#5129]
Seven parasite-themed Pyroland cosmetics ([Larval Lid](https://wiki.teamfortress.com/wiki/Larval_Lid), [Triboniophorus Tyrannus](https://wiki.teamfortress.com/wiki/Triboniophorus_Tyrannus), [Metal Slug](https://wiki.teamfortress.com/wiki/Metal_Slug), [Nabler](https://wiki.teamfortress.com/wiki/Nabler), [Sucker Slug](https://wiki.teamfortress.com/wiki/Sucker_Slug), [Alien Swarm Parasite](https://wiki.teamfortress.com/wiki/Alien_Swarm_Parasite), and [Breadcrab](https://wiki.teamfortress.com/wiki/Breadcrab)) get credit for the kill while the player receives the assist, **_this itself is not a bug_**, but rather the scoreboard fails to count the kill as an assist unlike what is seen in the kill feed.

I'm not entirely sure if this can be fixed (considering its only visible in Pyroland), but the easier solution would be reverting the value to 1 just like the rest of the Pyroland cosmetics.
```
"attributes"
{
	"counts as assister is some kind of pet this update is going to be awesome"
	{
		"attribute_class"	"counts_as_assister"
		"value"				"2"
	}
}
```
![20230805164338_1](https://github.com/ValveSoftware/Source-1-Games/assets/140918299/a82821e3-8e2d-4f34-85bf-b09fa2d0f7ef)

**Comment by ArtKitCat** [comment]
Also, wearing the Nabler and the Parasite Swarm reverts `"value" "2"` even though both cosmetics are not set to be the assistant. Taking off one of the cosmetics fixes the issue.
![20230805190123_1](https://github.com/ValveSoftware/Source-1-Games/assets/140918299/124127b8-256c-4d02-8402-8aabc3f1419a)
![20230805190256_1](https://github.com/ValveSoftware/Source-1-Games/assets/140918299/fdaaed8c-1f77-44f3-bf03-fba1ad34d0ed)

**Comment by JoriKos** [comment]
This is probably not a bug, but rather intentional. The parasite thing is only meant to be a gag of some sort, rather than actually being the one who does an assist.

**Comment by Platina6978** [comment]
> This is probably not a bug, but rather intentional. The parasite thing is only meant to be a gag of some sort, rather than actually being the one who gets the kill.

This is how I always thought of it as well.
