### ISSUE TITLE
[TF2] Add a timer to VSH maps to prevent griefing

### ISSUE THREAD

**Issue by AzureWoof** [ValveSoftware/Source-1-Games#5135]
Bots are queuing for VSH in order to get at least one bot as Saxton Hale, and one as a RED team member. Once the point becomes cappable, both bots just walk around and do nothing, making the match last forever. If there are enough bots on RED, you can't kick any of them, since all of them vote no.

My suggestion is to add a timer to the maps that lasts about 2 minutes once the center point becomes cappable, resulting in a stalemate if nobody ends up capping.

**Comment by aarmastah** [comment]
Can confirm this is a real issue; just got into a Casual match where the issue occurred. It is not possible to kick the bot player from the RED team unless you had previously played in the round, which is highly unlikely.

![image](https://github.com/ValveSoftware/Source-1-Games/assets/1887380/b28270b4-c1a4-4778-9fe9-f1b14d6afd3f)

**Comment by Whurrhurr** [comment]
unless this 2 minute timer bypasses overtime completely, the bots on both teams will just sit on the point and hold the entire server hostage due to how overtime works, though i am unsure if Sudden Death even uses Overtime when the timer runs out. so not only will you have to implement this 2 minute timer, but you will also have to make it end the round the moment it runs out.

**Comment by KimmyTF2** [comment]
I've found once a similiar match where Hale was a bot stuck in his spawn, and like 3/4 Sniper bots in their spawn, and the only player, RED Pyro, was micspamming some music and refusing to kill Hale, who had like 1000 HP or something.

**Comment by NULLYUKI** [comment]
According to Patch [208726](https://www.teamfortress.com/post.php?id=208726)
**Updated vsh_distillery, vsh_nucleus, vsh_skirmish, and vsh_tinyrock**
- **Failing to capture the point in 3 minutes after it opens results in Stalemate**

The requested feature should now be properly added.

**Comment by kisak-valve** [comment]
Closing per the last comment.
