### ISSUE TITLE
[TF2] Upside down Strange Stat Clock on certain weapons.

### ISSUE THREAD

**Issue by ArtKitCat** [ValveSoftware/Source-1-Games#5138]
Heavy's Miniguns (Tomislav, Brass Beast, & Minigun) all have upside down Strange Stat Clocks.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/140918299/db8fae82-bc71-4a23-8c16-65956c3f9712)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/140918299/3f9570a5-513d-4262-8854-6db809f19e87)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/140918299/cf5e28f7-a340-4187-a90b-a2fb7e31f1ba)

**Comment by FrozenDragon0** [comment]
Why'd you close this?
