### ISSUE TITLE
Casual loads really slow compared to community servers

### ISSUE THREAD

**Issue by AmadeusTomboy** [ValveSoftware/Source-1-Games#5149]
Hello, i've been having this issue for almost a month were casual matches load extremely slow, to the point that half the time i time out and i have to join again, meanwhile i tried community servers and it loaded a match at a normal speed.

I would love to be able to keep playing casual, but i have no clue what it's causing the issue, i tried lowering my graphics, but i feel like is not an issue on my end.

**Comment by NULLYUKI** [comment]
This issue is already being tracked in #5094

**Comment by kisak-valve** [comment]
Closing as a duplicate.
