### ISSUE TITLE
[TF2] Increment the killstreak counter in VSH when dealing X amount of damage

### ISSUE THREAD

**Issue by AzureWoof** [ValveSoftware/Source-1-Games#5152]
Since VSH is a mode where you can only get 1 kill while playing as one of the mercenaries, and that kill instantly ends the round, I think it'd be a cool change to automatically increment the killstreak counter when dealing a certain amount of damage to Saxton Hale so killstreak items have a role in the mode. I'm not sure if it's possible to alter or remove the killstreak message that's displayed on the screen, but if it is, those would certainly be good ways to make it make more sense.

**Comment by kisak-valve** [comment]
Hello @AzureWoof, the meaning of the counter is baked into the name. There isn't any wiggle room there to reinterpret it in the way you're requesting.
