### ISSUE TITLE
[HL2: EP1] Alyx's VCD doesn't play when Lowlife starts as she ducks under debris

### ISSUE THREAD

**Issue by BreakinBenny** [ValveSoftware/Source-1-Games#5153]
This is what ep1_c17_00.pat reads, and from the looks of the VCD's contents Alyx isn't happy about the situation (not the bug):

```
"Entities"
{
	"replace_entity"
	{
	"origin" "4930.31 -5905.47 -108"
	"targetname" "lcs_duckdown"
	"SceneFile" "scenes/episode_1/c17/al_tunnel_01a .vcd"
	"busyactor" "1"
	"classname" "logic_choreographed_scene"
	"hammerid" "1843024"
	"OnCompletion" "al_c17_00_fieldhack,Start,,0,-1"
	"OnTrigger1" "ss_alyx_walllean,BeginSequence,,0,-1"
	}
}


```
If I want to manually fix this myself, I have to use `ent_fire lcs_duckdown addoutput "scenefile scenes/episode_1/c17/al_tunnel_01a.vcd"`

**Comment by kisak-valve** [comment]
Hello @BreakinBenny, you've already reported this issue at #3747. Closing as a duplicate.

**Comment by BreakinBenny** [comment]
I'm just hopeful this isn't (and hasn't been) forgotten…
