### ISSUE TITLE
[TF2] Administrator "Captured Intelligence" voice lines for MannPower, all official Dubs supported (Provided assets)

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#5161]
While linked to #4238, This new post has much more content, with an actual display of the proposed additions, as well as better acuracy to the original vo voicelines:

While Official Dubs for French, German, Russian and Spanish, do exist for the Administrator, they were unfortunatly discontinued shortly after the Sniper vs Spy Uptate, back in 2009, That includes the MannPower gamemode. However, seeing as theses gamemode specific voice lines where heavily modified versions of the original vo, I took it upon Myself to do the same for other languages, first for French, then later all other available dubs:

https://github.com/ValveSoftware/Source-1-Games/assets/71549583/5e1ee9b8-99c0-4a6d-a77c-dcc4404845a9
(I appologise for the bad visual quality, however I had no other choice but to compress the file size)

Here they are for your consideration, implementation only requires to add them into theirs respective dubs. Thank you for your time.

[Mannpower Announcer voice pack fix.zip](https://github.com/ValveSoftware/Source-1-Games/files/12433480/Mannpower.Announcer.voice.pack.fix.zip)

**Comment by kisak-valve** [comment]
Hello @condor00fr, looking this over, I don't think it makes sense to track this separately from your previous issue report. They functionally overlap for issue tracking purposes, so I've transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/4238#issue-1355771228.

**Comment by condor00fr** [comment]
Alright then, Thanks:)
