### ISSUE TITLE
Can't run TF2 with upgraded SDL version

### ISSUE THREAD

**Issue by SetOfAllSets** [ValveSoftware/Source-1-Games#5163]
Game: TF2
Distro: Gentoo linux
Desktop: Sway compositor (wayland)
GPU: nvidia 2070 max-q with nouveau drivers
When running with the bundled version of SDL2 replaced with a version I compiled and the hl2.sh file modified to contain "export SDL_VIDEODRIVER=wayland" I get the error "Fatal Error: Unable to get window info from SDL.". The game runs fine on BSPWM (X11) and with Xwayland.

**Comment by kisak-valve** [comment]
Hello @SetOfAllSets, replacing game bundled libraries can't really be supported, but in any case, this issue is already being tracked at #5150.

Closing as a duplicate.

**Comment by SetOfAllSets** [comment]
> Hello @SetOfAllSets, replacing game bundled libraries can't really be supported, but in any case, this issue is already being tracked at #5150.
> 
> Closing as a duplicate.

I'm not sure, my game launches fine, just not on Wayland
