### ISSUE TITLE
[TF2][Request] Increase MAXSTUDIOBONES to 256

### ISSUE THREAD

**Issue by bottiger1** [ValveSoftware/Source-1-Games#5167]
Increase MAXSTUDIOBONES to 256. It is set to this number in csgo so I believe it wouldn't take many other changes, if any at all.

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/studio.h#L82

**Comment by kisak-valve** [comment]
Hello @bottiger1, this feature request is already being tracked at #3822. Closing as a duplicate.
