### ISSUE TITLE
[L4D2 Beta] Several labels in loading screens are placeholders

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Source-1-Games#518]
When loading an EMS mutation: 
![image](https://f.cloud.github.com/assets/4257305/478919/723a9100-b807-11e2-87ff-ed62e82409dd.png)

Level change when all survivors are in the saferoom on a custom campaign (in this case, Suicide Blitz, but I've seen the placeholder on every single custom campaign I've played): 
![image](https://f.cloud.github.com/assets/4257305/478993/cbfea586-b808-11e2-8de9-72f84c9503a2.png)

**Comment by kisak-valve** [comment]
Closing as there is nothing actionable in this issue report. If you are still experiencing this issue, please open a new issue report.
