### ISSUE TITLE
[TF2] Game does not launch, no window or anything. 

### ISSUE THREAD

**Issue by asdfghjkl403622** [ValveSoftware/Source-1-Games#5180]
Hello! I am on arch linux with a amd 6800xt graphics card, and I cannot play this game after a recent update. 
launching the game using the command `%command% 2> ~/Documents/log.txt`
I get: 
`ERROR: ld.so: object '/home/samy/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/samy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/samy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 35885 != 35884, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/samy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/samy/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
src/tcmalloc.cc:278] Attempt to free invalid pointer 0xaa61ad0 
/run/media/samy/musical beast/SteamLibrary/steamapps/common/Team Fortress 2/hl2.sh: line 72: 35887 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

running the game under proton works fine, it just opens in insecure mode and I can't join official servers afaik. 
please let me know if there is anything else I can add that would help.

**Comment by asdfghjkl403622** [comment]
I should also mention I am on KDE on wayland

**Comment by kisak-valve** [comment]
Hello @asdfghjkl403622, this issue is already being tracked at #5043. Closing as a duplicate.

**Comment by asdfghjkl403622** [comment]
> Hello @asdfghjkl403622, this issue is already being tracked at #5043. Closing as a duplicate.

sorry, thanks for the quick response!
