### ISSUE TITLE
[TF2] stops responding/freezes when "retrieving server info" 

### ISSUE THREAD

**Issue by dandure9** [ValveSoftware/Source-1-Games#5186]
I can enter the first game in tf2, but the second game crashes when the message "Retrieving server information" appears, so the game simply closes. I already reset the settings to default and deleted my custom folder and checked the integrity of the files but none of that helped.

Here's my specs
OS: Linux Mint
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
RAM: 8GB
GPU: HD Graphics 620
STORAGE: SSD 128 GB

**Comment by dandure9** [comment]
I did a complete reinstall and followed this [guide](https://docs.mastercomfig.com/page/setup/clean_up/) for a complete clean up and none of this works

**Comment by dandure9** [comment]
I found the solution! Just add "+mat_autoload_glshaders 0" to your launch options.

**Comment by souxd** [comment]
> I found the solution! Just add "+mat_autoload_glshaders 0" to your launch options.
@dandure9 can you elaborate on why that would cause the problem?
