### ISSUE TITLE
Cannot matchmaker to summer update servers in the team Fortress 2 linux cliënt.

### ISSUE THREAD

**Issue by yaktoma2007** [ValveSoftware/Source-1-Games#5189]
Simply as the title says. The summer update matchmaking does not appear to be an option on linux.
![PXL_20230916_160923683](https://github.com/ValveSoftware/Source-1-Games/assets/83469060/e0d7b371-225f-4905-ac65-717dcadd57dd)

**Comment by yaktoma2007** [comment]
My excuse, this also seems to affect windows

**Comment by NULLYUKI** [comment]
This is not a issue. As the summer update has officially ended.
According to patch [206148](https://www.teamfortress.com/post.php?id=206148)
> The Summer event runs through September 15th, 2023

This issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
