### ISSUE TITLE
L4D2 crashes X.org on Linux (Nvidia)

### ISSUE THREAD

**Issue by darkargon** [ValveSoftware/Source-1-Games#519]
Starting the first level in single player crashes the X.org Server. The intro runs fine @ ~120FPS but after the game gives me the ability to control my char the game freezes and my audio starts to loop. After 1-2 Minutes i get weird rendering artifacts and finally my 2 screens turn black (no signal).

syslog & system information: https://gist.github.com/darkargon/1e98b533db2a7bd60934

Linux Kernel: 3.9.0 (also happes with 3.8)
Nvidia Driver: 319.17 (did also happen with older versions)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant. If anyone is still experiencing this issue with an up to date system, please open a new issue report.
