### ISSUE TITLE
[CS:S][MAC] full screen 3D garbage when looking at hostages

### ISSUE THREAD

**Issue by hankyuller** [ValveSoftware/Source-1-Games#5190]
Fill the screen with glitched 3D when looking at hostages. Being in the next room while looking in the direction of hostages also triggers the glitch. Runs perfect otherwise.

![20230917062924_1](https://github.com/ValveSoftware/Source-1-Games/assets/22340786/2f8e8693-e57d-41b0-906b-c574f8686555)
![20230917062933_1](https://github.com/ValveSoftware/Source-1-Games/assets/22340786/de7a5593-e9dc-407a-b91e-8779933aab31)
![20230917063000_1](https://github.com/ValveSoftware/Source-1-Games/assets/22340786/62fcb01d-a699-4187-b2a1-357766132d73)

MacOS 10.13 High Sierra 
AMD HD6970m
imac 2011

**Comment by kisak-valve** [comment]
Hello @hankyuller, this issue is already being tracked at #1930. Closing as a duplicate.

**Comment by hankyuller** [comment]
Thanks, also there is a fix in [https://github.com/ValveSoftware/Source-1-Games/issues/1930](url) that worked for me ! (custom hostages skin)
