### ISSUE TITLE
[TF2] [Feature Request] Give VSH its own game mode category

### ISSUE THREAD

**Issue by HueyCan** [ValveSoftware/Source-1-Games#5192]
Because VSH has as much maps as Mannpower with the possibility of more year-round VSH maps to be added, why not give VSH its own category under the Alternate Game Modes section? Reusing "gametype_featured_campaign3" would be fine if new artwork isn't able to be made at the moment, leaving a description for the game mode the only thing needed for a category.

**Comment by kisak-valve** [comment]
Hello @HueyCan, this is functionally the same feature request as #5050. Closing as a duplicate.
