### ISSUE TITLE
[TF2] Spy buildings fail to load full string in player outline UI

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#5200]
Spy buildings (Sappers) fail to display their name when displaying player outlines to the player (ie. Spectate, Spawning)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/108029512/f4158a4d-524f-4d2d-976c-242774e1b6e5)

**Comment by kisak-valve** [comment]
Hello @rabscootle, this issue is already being tracked at #4517. Closing as a duplicate.
