### ISSUE TITLE
[TF2] [Linux] Game doesn't start

### ISSUE THREAD

**Issue by avlec** [ValveSoftware/Source-1-Games#5205]
I had the game working a while ago however after an update on either steams end or on my system I cannot launch the game from my NFS drive like I used to. However, I can still launch it from Windows 11.

I am on a Arch Linux VM with GPU passthrough on an AMD graphics card. That information doesn't seem relevant though from the following errors.

The error I'm getting is the following from steam-runtime
```
/bin/sh\0-c\0/home/avlec/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/avlec/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/games/SteamLibrary/steamapps/common/Team Fortress 2/hl2.exe' -steam -game tf -novid -nojoy\0
chdir "/mnt/games/SteamLibrary/steamapps/common/Team Fortress 2"
ERROR: ld.so: object '/home/avlec/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/avlec/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/avlec/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/avlec/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/games/SteamLibrary/steamapps/common/Team Fortress 2/hl2.exe: /mnt/games/SteamLibrary/steamapps/common/Team Fortress 2/hl2.exe: cannot execute binary file
```

The error I get when invoking tf2.exe manually is below and the file information. It looks like it's installing for the wrong platform?
```
.../steamapps/common/Team\ Fortress\ 2/hl2.exe
bash: /mnt/games/SteamLibrary/steamapps/common/Team Fortress 2/hl2.exe: cannot execute binary file: Exec format error
/steamapps/common/Team\ Fortress\ 2/hl2.exe
bash: /mnt/games/SteamLibrary/steamapps/common/Team Fortress 2/hl2.exe: cannot execute binary file: Exec format error
```

 I see .dll files when I would assume to see .so files in the bin directory. This is even after reinstalling

**Comment by taulantxhakli** [comment]
This might be completely useless, but have you checked if your ext4 drive is mounted? You would need to put in the `/etc/fstab` to be mounted on boot.
If this only pertains to TF2, then we are in the same boat. TF2 does not work properly on Arch Linux for some. Some have mentioned to do [this](https://steamcommunity.com/app/420530/discussions/1/1639794468037255621/#c1644304412660813822).

**Comment by avlec** [comment]
> This might be completely useless, but have you checked if your ext4 drive is mounted?

I have manually mounted the drive over the command line so the drive is mounted. It's also a network file system (nfs) drive so not quite ext4. 

> If this only pertains to TF2, then we are in the same boat.

I have just tried if CS:GO works and it does.

> Some have mentioned to do [this](https://steamcommunity.com/app/420530/discussions/1/1639794468037255621/#c1644304412660813822).

I don't seem to have any of those files mentioned in my TF2 install location. They also seem to be encountering a different issue as the logs are different. It seems their program starts and then encounters a problem whereas mine can not begin to execute.

**Comment by taulantxhakli** [comment]
https://bbs.archlinux.org/viewtopic.php?id=267629

> I tried making less heavy handed package changes and switched from linux511-nvidia390xx to linux511-nvidia fixed all of my issues.
> Steam now works.
> 
> The issue was that vulkan no longer supports such old drivers.

**Comment by avlec** [comment]
It just looks like it's installing the game for the wrong platform. It seems to be just downloading the Windows version. I see no shared object files, just windows dynamic library files in the installation directory.

**Comment by kisak-valve** [comment]
Hello @avlec, https://github.com/ValveSoftware/Source-1-Games/issues/5205#issue-1910075138 this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9875.

https://github.com/ValveSoftware/Source-1-Games/issues/5205#issuecomment-1732474274 this is the issue being tracked at #5043.

Closing in favor of the older issue reports.
