### ISSUE TITLE
[Feature Request] [L4D2 Beta] interact with weapons from a mutation

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Source-1-Games#522]
VScripts have no way of modifying the amount of ammunition in a weapon, so (for example) the GibFest mutation would be impossible to implement using the new system. I wanted to make a mutation where the survivors each had a one-bullet-per-clip magnum pistol and all other weapons were removed, but I guess that'll have to wait (for now).

**Comment by alexiscoutinho** [comment]
All this can be done with vscript now. Can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
