### ISSUE TITLE
[Feature request] Map Voting Command for community servers

### ISSUE THREAD

**Issue by RFrappe** [ValveSoftware/Source-1-Games#5222]
I mean like a map command used in the AutoExec,cfg for the servers. This would enable the default TF2 map voting screen used in Valve server to let people vote for the next map.
I think this should be a map command similar to something like
`sv_postmapvoting`
Enabling this would tell the game to show the map voting dialog and show the spectator screen or the casual door while players vote.

**Comment by kisak-valve** [comment]
Hello @RFrappe, this feature request is already being tracked at #2721. Closing in favor of the older feature request.
