### ISSUE TITLE
[TF2] Profile Pictures (avatars) are not loading on the Scoreboard

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#5228]
I have this issue since yesterday and browsing through the forum I also see that other people have the same issue.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/cebede44-6f25-431f-af25-b564967d4020)

**Comment by Thespikedballofdoom** [comment]
This is caused by the current steam beta: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3877093932382687124/

**Comment by NULLYUKI** [comment]
According to [Steam Client Beta - October 24th](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3731854112036071904)

>**General**
- Fixed missing player avatars in game scoreboards.

This issue requires retesting to see if the issue is properly fixed when using the Steam Beta Client.

**Comment by Thespikedballofdoom** [comment]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/43627353/0935a7cc-8471-4d69-b3ad-efc1a3dd5f4d)
Works, finally.

**Comment by gaelcoral** [comment]
Fixed!
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/d632e427-b5a4-4337-9f1e-df8cdf08a75d)
