### ISSUE TITLE
[TF2] [Bug] TF2 won't open due to libtcmalloc_minimal.so.4

### ISSUE THREAD

**Issue by Ruskki** [ValveSoftware/Source-1-Games#5229]
TF2 won't open if libtcmalloc_minimal.so.4 is present in the game files

`./hl2_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: cannot open shared object file: No such file or directory`

Removing the file worked however I could not play on servers due to  "An issue with your computer is blocking the VAC system. You cannot play on secure servers".

I managed to circumvent this by adding the file gain and opening with Proton however it was in insecure mode and I couldn't play. Another solution was going to the launch options and adding `LD_PRELOAD=/usr/lib32/libtcmalloc.so %command%` . While this does let me play in training mode, everytime I try queuing it stops after a while. Haven't been able to join a casual server by queuing

System Information: 
OS: Arch Linux
Kernel: 6.5.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:54:46 +0000 x86_64 GNU/Linux
Desktop: Qtile
CPU: AMD Ryzen 5 5600G
Video: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

**Comment by kisak-valve** [comment]
Hello @Ruskki, this issue is already being tracked at #5043. Closing as a duplicate.
