### ISSUE TITLE
[L4D2 Beta] Fallen survivors and explicitly placed items do not obey mutation item restrictions

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Source-1-Games#523]
Fallen survivors can, for example, drop a health kit during a mutation that converts all health kits to pills. CEDA workers, security officers, and other uncommon common infected should also check with the director if it's okay to drop bile/batons/etc.

Also, mappers might put weapon spawns other than the generic one into their maps, making weapons available when they should not be (such as in the Lone Gunman mutation).

**Comment by alexiscoutinho** [comment]
There are callbacks and cvars to prevent all those items from appearing. This isn't an issue anymore (can be closed). Also, Death's Door will soon have an update to fix Fallens being able to drop medkits.

**Comment by kisak-valve** [comment]
Closing per the last comment.
