### ISSUE TITLE
[TF2] zi_atoll does not have it's cubemaps packed into the BSP

### ISSUE THREAD

**Issue by Whurrhurr** [ValveSoftware/Source-1-Games#5238]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/33162051/7585b622-9bc1-4dcc-811d-edca3278478f)

this is the default HDR cubemap, used only when a map doesn't override the default cubemap textures from building cubemaps.

**Comment by aarmastah** [comment]
Issue still present after tonight's update. I've contacted the map author about it as well so that they're aware.

**Comment by NULLYUKI** [comment]
> Issue still present after tonight's update. I've contacted zi_atoll's author about it as well so that they're aware.
> 
> EDIT: Can confirm pl_spineyard does not have cubemaps packed either.

According to patch [211041](https://www.teamfortress.com/post.php?id=211041)
- Updated pl_spineyard
  - Fixed missing cubemaps

> ![image](https://user-images.githubusercontent.com/33162051/273783150-7585b622-9bc1-4dcc-811d-edca3278478f.png)
> 
> this is the default HDR cubemap, used only when a map doesn't override the default cubemap textures from building cubemaps.

According to patch [211041](https://www.teamfortress.com/post.php?id=211041)
- Updated zi_atoll (additional changes)
  - Fixed cubemap reflection issues
 
This issue requires retesting.

**Comment by aarmastah** [comment]
That was a patch note I wrote and after testing in the game, I can confirm the issue was resolved.

**Comment by aarmastah** [comment]
Additional screenshots showing both zi_atoll and pl_spineyard both have the issue resolved:
![image](https://github.com/ValveSoftware/Source-1-Games/assets/1887380/833179d5-2d42-438a-aaa7-1973aa098f83)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/1887380/2d1334d1-9b4f-496f-9c89-e492abe5a087)

**Comment by kisak-valve** [comment]
Closing per the last several comments.
