### ISSUE TITLE
[TF2] Community Fix for the Arena Player Count HUD

### ISSUE THREAD

**Issue by GrassyTrams** [ValveSoftware/Source-1-Games#5243]
Arena Mode has had an unusable player count UI since 2016, the linked steam workshop community fix can fix this issue.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/120645510/268e943e-6025-4aee-8bb4-bacfcff1755e)
[Steam Workshop Link](https://steamcommunity.com/sharedfiles/filedetails/?id=3049413665)

**Comment by kisak-valve** [comment]
Hello @GrassyTrams, this issue is already being tracked at #3967. Since this issue report adds a bit more insight, I've transferred the issue report to https://github.com/ValveSoftware/Source-1-Games/issues/3967#issuecomment-1759537614.

Closing in favor of the older issue report.
