### ISSUE TITLE
[TF2] [Feature Request] Allow players to redeem contracts without need to finish the round first

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#5246]
Forcing players to finish the round to finish their contracts really quickly kills servers. If a player could finish their contract at any time, a new player would fill their slot after they left. Currently servers die very quickly once the round ends and matchmaking is very slow in filling empty slots, often having a few players on both teams for +10 minutes.

**Comment by kisak-valve** [comment]
Hello @KimmyTF2, this is functionally the same feature request as #4403. Feel free to add a comment to the older request.

Closing in favor of the older feature request.
