### ISSUE TITLE
[Steam and All GoldSrc, Source 1 & Source 2 Games] Discontinue Mac Support altogether due to low Mac userbase

### ISSUE THREAD

**Issue by Wadmodder** [ValveSoftware/Source-1-Games#5247]
In recent years, the macOS platform has been a more stagnated walled garden between Apple and gamers alike.

In fact, macOS since Catalina has a more aggressive "Walled Garden" of software policies by Apple than what Windows and Linux has on offer. Apple's new policies of macOS software include lack of 32-bit software support, deprecation of OpenGL, lack of official Vulkan support and trying to kill Wine/Crossover support on macOS in favor of the Game Porting Toolkit. In fact, it would be nice for Valve to drop support not only for GoldSrc, Source 1 and Source 2, but also for Steam altogether due to the new Apple Walled Garden for macOS being more aggressive than what Microsoft's Windows walled garden has to offer.

With Valve no longrr providing an official macOS version of Counter-Strike 2, Steam (and not just GoldSrc, Source 1 and Source 2) should just drop support for macOS altogether, as the macOS userbase since the release of atalina isn't even large to begin with. So the question remains, is it likely that Valve is planning to discontinue all support for not just GoldSrc, Source 1 and Source 2, but for Steam on macOS, due to the declining macOS userbase and Apple's more aggressive Walled Garden, which Valve doesn't want to extend the time or resources altogether trying to follow the rules of Apple's macOS ecosystem.

In otherwords, Valve should just stop macOS development altogether, not just with Steam but also all their GoldSrc, Source 1 and Source 2 games completely, because the company doens't have any official resources to migrate to Apple Silicon whatsoever.

**Comment by kisak-valve** [comment]
Hello @Wadmodder, this is a request for an anti-feature. Closing as invalid.
