### ISSUE TITLE
[TF2] Versus Saxton Hale Should Get Its Own Gametype Tab

### ISSUE THREAD

**Issue by GrassyTrams** [ValveSoftware/Source-1-Games#5248]
Versus Saxton Hale should get its own Gametype tab instead of being put into Misc.
![gametype](https://github.com/ValveSoftware/Source-1-Games/assets/120645510/121c7164-d1a9-4024-b822-56b1324409d7)
Image made by modeler of Saxton Hale, permission permitted.

**Comment by kisak-valve** [comment]
Hello @GrassyTrams, this issue is already being tracked at #5050. Closing as a duplicate.
