### ISSUE TITLE
[TF2] Decrease mp_maxrounds for Zombie Infection maps

### ISSUE THREAD

**Issue by Kruphixx** [ValveSoftware/Source-1-Games#5249]
Currently mp_maxrounds is set to 25 on ZI maps, similiar to VSH. I don't think that many rounds are needed for a gamemode like this, considering most of the rounds can already last a while. 

Also by the time the match ends, majority of players leave since they mostly just play for contracts. Some people like to play till the end of matches to get XP, and having to play 25 rounds just to get it is a bit tiresome. Perhaps **reducing maxrounds to 10-15** could work better.

**Comment by ZeroYamaoka** [comment]
Well i think 13 rounds should be just right

**Comment by Kruphixx** [comment]
It seems this has been adjusted with the halloween update, mp_maxrounds is now set to 15 on ZI maps.

![20241025174028_1](https://github.com/user-attachments/assets/cf55c0a3-5fed-493a-9821-3db4ebfde123)
