### ISSUE TITLE
[TF2] The newspaper in the main menu no longer works when switching languages

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#5259]
However, if I change the game to English, the newspaper works as normal. 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/c3d4fde1-1a1f-4abb-bc92-a74fdf9f2fec)

**Comment by kisak-valve** [comment]
Possibly related to #4267.

**Comment by gaelcoral** [comment]
Actually my bad, I had a command that caused this bug
