### ISSUE TITLE
[TF2] Re-Distribute or Mark Halloween Spells as Decorative

### ISSUE THREAD

**Issue by BreavyTF2** [ValveSoftware/Source-1-Games#5262]
It's been 9 years since the last distribution, reimplement them as rare drops from Halloween Cases (like festivizers) or make the item a decorative momento like limited crates and the pyromania ashes.

**Comment by kisak-valve** [comment]
Hello @BreavyTF2, this request is already being tracked at #2788. Closing in favor of the older issue report.
