### ISSUE TITLE
[TF2 - Linux] semi-consistent crashing

### ISSUE THREAD

**Issue by SirBlockles** [ValveSoftware/Source-1-Games#5263]
When running the game for a while, it will freeze up and after about 20 seconds, crash. Launching steam through a terminal window shows the game output a crash dump into `/tmp/dumps/`, and two samples of the crash dumps have been attached. On some maps the crash will happen quickly and consistently (zi_murky is an example, and a dmp from a crash there is included), other times the game can run for hours at a time before it happens (the other crash on los muertos is the other crash and is an example of this case).

This freezing problem has been consistent for a few months now, back around the time when #5043 became an issue for Arch users. As a result, I have `LD_PRELOAD=/usr/lib32/libtcmalloc_minimal.so.4:$LD_PRELOAD` included in my launch options. This was also around the time, though, that i switched from an Nvidia GPU to an AMD GPU, so I'm not sure if the issue has something to do with the video drivers or if it's a side effect of the tcmalloc workaround.

I don't really know how to open or read these crash dumps, but i hope they provide any kind of useful information: [crash dumps](https://github.com/ValveSoftware/Source-1-Games/files/13037197/crashdmp.zip)

**Comment by kisak-valve** [comment]
Hello @SirBlockles, the crash dumps are in Breakpad's minidump format if you want to look into inspecting those files yourself.

For reference, the attached minidumps are SIGSEGV in engine.so.

**Comment by notkiniro** [comment]
Hello
You mentioned switching to an AMD GPU recently, maybe you're missing some drivers?

Could you post the result of running `pacman -Qs vulkan`?
Make sure you have [lib32-vulkan-radeon](https://archlinux.org/packages/multilib/x86_64/lib32-vulkan-radeon/)

**Comment by SirBlockles** [comment]
yes, this has been fixed. forgot to close it.
