### ISSUE TITLE
[TF2] (Zombie Infection) You can turn into survivor after dying as zombie

### ISSUE THREAD

**Issue by ailurophilly** [ValveSoftware/Source-1-Games#5264]
https://github.com/ValveSoftware/Source-1-Games/assets/147918554/e9cd991e-1b4c-4d6a-98c3-30c4aac1f358

After winning as a zombie and then dying you can change teams by changing classes.

**Comment by ailurophilly** [comment]
Fixed in new update

**Comment by Hedwig7s** [comment]
> Fixed in new update

Spoil sport
