### ISSUE TITLE
Steam support sent me here to ask ( for real ) Is DXVK compatible On windows with CSS ? no vac bans ?

### ISSUE THREAD

**Issue by Evonos** [ValveSoftware/Source-1-Games#5270]
Source on Steam support sending me here https://i.imgur.com/SpinvtS.png
Ticket 
HT-KCPJ-DJNV-NKQB

**Comment by kisak-valve** [comment]
Hello @Evonos, this feature request is already being tracked at #2844. Closing in favor of the older issue report.
