### ISSUE TITLE
[TF2] Extendfreeze unusable

### ISSUE THREAD

**Issue by jh34ghu43gu** [ValveSoftware/Source-1-Games#5275]
> Fixed using the extendfreeze client command to continue spectating enemy players after being killed

This change has completely removed all functionality of the command even when spectating your own teammates. This is a terrible change and a major victory for closet cheaters who only have to toggle off for a few seconds now while waiting for spectators to respawn and leaves us legit players no reliable way to discern a good player from a cheater in the same match (replay demos could technically show you but you can only view those after the match which is kind of useless). 

#4443 comments seem to agree with this sentiment although the patch note would suggest this is a new issue since the language would suggest the intent was only to fix that specific issue and not neuter the command completely. 

Rumor has it this was done to combat abusers on the new zombie mode, if this is the case please revert this change after the event ends :pray:

**Comment by jh34ghu43gu** [comment]
As an aside, I have a [playlist](https://www.youtube.com/playlist?list=PLpZkbXUxLt1cn7cvhZhebw1t8qtJ1b_iz) of cheaters I have caught largely from this command as an example of how I assume most people used this command before zombie infection was added.

**Comment by rootino** [comment]
Guess the second best alternative is using a hud with a blank character select screen.
Not nearly as intuitive as extend_freeze but it works i suppose.

**Comment by NULLYUKI** [comment]
As much I can agree with the possibility of this command being used to get extra information about the enemy team, which can be useful/unfair for competitive matches. 

I also can very much agree how the fix by Valve:
> Fixed using the extendfreeze client command to continue spectating enemy players after being killed.
Now removes the possibility to identify possible cheaters who are trying to play less obvious aka doing legit cheating.
So I'm also on the side and hope that they will revert the current fix and work on a better solution with the community.

**Comment by TheLivingM3m3** [comment]
I have never seen anybody use or used the command to gain information on the enemy team as there isn't really an incentive in casual play to do so. The loss of this command will just benefit cheaters as the anticheat is nigh useless on its own. The players have to do everything themselves and without being able to spectate their teammates it will be impossible.

**Comment by ChampionCynthia** [comment]
On the other hand, bots could be modified to abuse this command to remain dead forever and waste player slots, so it's not necessarily such a bad preventive measure.

**Comment by jh34ghu43gu** [comment]
> On the other hand, bots could be modified to abuse this command to remain dead forever and waste player slots, so it's not necessarily such a bad preventive measure.

This did not stop you from being kicked, their mere existence is a waste of a slot, spectating would be less harmful than cheating, it's been 5+ years and they haven't bothered doing this for a reason.

**Comment by ChampionCynthia** [comment]
> > On the other hand, bots could be modified to abuse this command to remain dead forever and waste player slots, so it's not necessarily such a bad preventive measure.
> 
> This did not stop you from being kicked, their mere existence is a waste of a slot, spectating would be less harmful than cheating, it's been 5+ years and they haven't bothered doing this for a reason.

I get what you are saying, I'm just mentioning that it could be abused as well.

It's more likely that Valve fixed it for the fact you can watch your killer play the game (and ZI as you mentioned). It would make sense for it to still work to spectate teammates, I agree.

**Comment by Thespikedballofdoom** [comment]
It really should be brought back.
For now since I don't wanna mod my hud I'm gonna hit class select bind and some different number as fast as I can. What a chore

**Comment by talesPGrechi** [comment]
> It really should be brought back. For now since I don't wanna mod my hud I'm gonna hit class select bind and some different number as fast as I can. What a chore

Excuse me, but how changing your hud and/or hit class select bind + a number would help you to spectate a teammate for more time?

**Comment by Thespikedballofdoom** [comment]
I don't know. I thought changing it was the same as extendfreeze somehow, but it doesn't seem to do anything, I'm not sure what the thing people are talking about here is

**Comment by Sawaumi** [comment]
If not reverted at least provide some alt for spectating own teammates

**Comment by talesPGrechi** [comment]
> You can also open class select then open the pause menu by pressing escape and that also counts as "in the class menu" but lets you see the game with the default hud

Oh... you're right, I didn't knew you could do that. I've tested it and I could even "unpause" in the demo to see the person's crosshair! I'll try that the next time I face a cheater..

**Comment by Kruphixx** [comment]
Really the simplest solution would just be enabling spectator mode in Casual.

No idea why it's disabled in the first place, personally I don't see any cons to enabling it.

**Comment by JoriKos** [comment]
> Really the simplest solution would just be enabling spectator mode in Casual.
> 
> No idea why it's disabled in the first place, personally I don't see any cons to enabling it.

This would mean you'd have to block people from switching to the other team. If not, people will just do what they used to do: sit in Spectator until they can join the winning team or join the winning team when they're losing.

**Comment by Kruphixx** [comment]
> > Really the simplest solution would just be enabling spectator mode in Casual.
> > No idea why it's disabled in the first place, personally I don't see any cons to enabling it.
> 
> This would mean you'd have to block people from switching to the other team. If not, people will just do what they used to do: sit in Spectator until they can join the winning team or join the winning team when they're losing.

Yeah obviously, that would have to be changed too.

**Comment by among-us-official** [comment]
You can use the 'menuopen' and 'menuclosed' commands to tell the server that you have the class selection menu open (or not). This does not enable you to spectate enemies.

**Comment by Ashetf2** [comment]
> You can use the 'menuopen' and 'menuclosed' commands to tell the server that you have the class selection menu open (or not). This does not enable you to spectate enemies.

This makes this issue invalid then
