### ISSUE TITLE
[TF2; Feature Request] Make players invulnerable on spawn in regular Casual modes and maps

### ISSUE THREAD

**Issue by tariqmudallal** [ValveSoftware/Source-1-Games#5280]
We would like to see players (re)spawn with an Über effect every time, just like in Mannpower. Very useful in Casual (especially in 2Fort), and Competitive, as an enemy team sometimes likes to spawn trap the player's team and basically make it "impossible" for their team to leave the spawn room. Giving the mini Über on spawn enables their team to counter and distract the enemy team with ease and enable them to keep the flow going. I also would like to make it so that NOT A SINGLE thing, including projectiles, stickybombs and bullets can make their way into the spawn room (they should end up hitting on the invisible wall to the enemy team who tries to shoot into the player's team's spawn room), which could after all make it the SAFEST place for a teammate to be, and therefore produce NO hitsound, if any, and cause any damage. This would mean that if a RED Engineer puts up a Lvl. 3 Sentry atop the roof near BLU's spawn room in Dustbowl, the Sentry's bullets and/or rockets wouldn't go through the skip sign, making spawn trapping impossible. As for BLU, the Über effect on respawn allows them to easily take down that Sentry, and therefore counter the spawn trap set up by that RED Engie.

**Comment by mtxfellen** [comment]
Duplicate of your own post #3367.
