### ISSUE TITLE
[TF2; Feature Request] Bring TF2 to Source 2

### ISSUE THREAD

**Issue by tariqmudallal** [ValveSoftware/Source-1-Games#5282]
I know this may or may not happen anytime soon, but I think it's time we bring TF2 to the newer Source 2 engine that is only being popularly used in Dota 2 (and as of Sep. 2023, Counter Strike 2). Doing so could mean many advantages. In addition to nice looking graphics, we also would have better security, better compatibility, and the ability to work directly with modern day x64 PCs and modern graphics APIs like DX11 & Vulkan. If I am right, due to Source 2 being newer, and therefore Valve constantly updating the engine itself with newer bugfixes and patches, aimbotters would be out more quickly than they think they would be.

**Comment by kisak-valve** [comment]
Hello @tariqmudallal, given the massive amount of work that's required to rebase a game on a different game engine, the Team Fortress 2 team would need to decide to take on this undertaking through a Valve internal decision and this isn't open to public influence.
