### ISSUE TITLE
[Left 4 Dead 2 Beta - Linux] prop lighting flicker

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#529]
For some reason, when I move and look around, certain props "flicker" from being fullbright to being correctly lit. It seems to mainly affect ragdolls and physics props, but I've caught glimpses of it happening with live zombies as well. Here are some samples, including one of a barrier that I'm pretty sure isn't a physics prop (the only static prop I've seen affected by this so far).

![2013-05-09_00005](https://f.cloud.github.com/assets/3085348/483976/05ce672c-b8ce-11e2-8b49-d5221bf2c262.jpg)
![2013-05-09_00004](https://f.cloud.github.com/assets/3085348/483978/07224abc-b8ce-11e2-8b24-fb5207de8e9f.jpg)
![2013-05-09_00006](https://f.cloud.github.com/assets/3085348/483992/29d8a592-b8ce-11e2-949e-86e692e1853a.jpg)

This is similar to a bug TF2 used to have with the torches in cp_egypt, which was apparently fixed at some point.

Relevant info:

Intel Core 2 Quad 2.4 GHz (multicore rendering on)
4 GB RAM
ATI Radeon HD 4850
fglrx 13.1 legacy driver
No VRAM detected (see [issue #1311](https://github.com/ValveSoftware/steam-for-linux/issues/1311) in Steam client)
Shaders set to Very High
Kubuntu 12.04 LTS, 64-bit
Kernel 3.2.0-29-generic
X-Server 11103000

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
