### ISSUE TITLE
[TF2; Feature Request] Introduce chat bans for users who rapidly flood the chat themselves

### ISSUE THREAD

**Issue by tariqmudallal** [ValveSoftware/Source-1-Games#5292]
When it comes to chatting, there should be a chat ban for those who keep spamming a lot or using kill/uber/death chat binds, especially when bots flood the whole chat, they should be banned from using chat or be put on "cooldown" to protect the server from flooding.

**Comment by Thespikedballofdoom** [comment]
They already are, valve servers use this. https://wiki.teamfortress.com/wiki/Text_chat#Chat_filter_and_restrictions

**Comment by JoriKos** [comment]
I'm not sure what the harm in Über binds is, they're literally proper use of communication in TF2. If you really are annoyed by someone's chat spam, you can always mute said person.

**Comment by Chickenman456** [comment]
there should be a chat ban for hate speech as well. filter/censoring is only a band aid solution. Why allow it at all?

**Comment by JoriKos** [comment]
> there should be a chat ban for hate speech as well. filter/censoring is only a band aid solution. Why allow it at all?

There is no realistic way to enforce this, Valve would have to hire ppl specifically to sit through these reports.

**Comment by Chickenman456** [comment]
> > there should be a chat ban for hate speech as well. filter/censoring is only a band aid solution. Why allow it at all?
> 
> There is no realistic way to enforce this, Valve would have to hire ppl specifically to sit through these reports.

it's pretty easy... say a slur, get banned. For general toxicity I agree, but there's no reason why players are even given the option to write and send slurs

**Comment by JoriKos** [comment]
> > > there should be a chat ban for hate speech as well. filter/censoring is only a band aid solution. Why allow it at all?
> > 
> > 
> > There is no realistic way to enforce this, Valve would have to hire ppl specifically to sit through these reports.
> 
> it's pretty easy... say a slur, get banned. For general toxicity I agree, but there's no reason why players are even given the option to write and send slurs

A very English-centric view, what if there's another language community whose language has a word that's a slur in English (famously, Spanish)? Spanish person says black -> banned.

It would be an easily bypassed filter unless you make it also detect wildcards/substrings. In that case, Montenegrins mention their own country -> banned.

If you only ban English slurs, you'll run into the problem I mentioned above. Ban slurs in other languages and you'll run the risk of the same happening between other languages or that translations of slurs are not used in said language as a slur at all. For example, the Dutch version of the F slur has way more non-slur uses than it does slur uses.

Automatic banning systems based on text chat filters are a horrible idea, especially in a game that's supported with several different localisations and is played worldwide. If you finally _do_ make a system that is able to 100% know the context/language behind every conversation, never make a false ban, and be entirely accurate, players will simply open their mic and say it over voice chat.

**Comment by kisak-valve** [comment]
Closing per @Thespikedballofdoom's comment.
