### ISSUE TITLE
[TF2; Feature Request] Add team Auto Scrambling to Casual mode

### ISSUE THREAD

**Issue by tariqmudallal** [ValveSoftware/Source-1-Games#5293]
There is a solution should we need to balance out the teams in Casual. We can add a vote option to "Auto Scramble" teams, just like in community servers. At the same time, we also need to take into account the other users in the player's party, as a deciding factor as to whether to move the others with them or not, so there'd be no frustration when users are separated from their party members.

**Comment by kisak-valve** [comment]
Hello @tariqmudallal, this feature request is already being tracked at #4253. Closing as a duplicate.
