### ISSUE TITLE
Half-life source and other source games wont open/run

### ISSUE THREAD

**Issue by steblaa** [ValveSoftware/Source-1-Games#5296]
[Half-life source] Hello, I've recently installed Linux mint 21.2 Victoria on my laptop and have been trying to fix the error ¨error while loading shared libraries: libtcmalloc_minimal.so.4: wrong ELF class: ELFCLASS64" 

Before that error message I had a pointer invalid error and had to replace the libtcmalloc_minimal.so.4 with my distro's libtcmalloc_minimal.so.4 file and now I'm getting ELFCLASS64 everything I've tried failed like for example forcing .deb 32 files to become 64 bit or something like that and tried reinstalling game and also tried to install 32 bit respositories. If someone would be kind to help me with this issue it'll be appreciated.

My specs:
AMD Wrestler [Radeon HD 6310]  (GPU)
AMD E-300 APU with Radeon(tm) HD Graphics (CPU) 2 cores.
4 gigs of ram 3.7 available.

**Comment by kisak-valve** [comment]
Hello @steblaa, modifying game bundled libraries is not supportable.

Having written that, the error message you've shared is because you've replaced a 32 bit library with a 64 bit library and the different architectures are incompatible. You would need to keep libtcmalloc_minimal 32 bit to match the game.

**Comment by steblaa** [comment]
But when I have the original libtcmalloc_minimal 32 bit file in there it just gives me a invalid point error with code like 0x848x39 or something related to that. Do you know any ways to resolve  this issue?

**Comment by ohhai** [comment]
@steblaa  it's #5043 and it has workarounds there
