### ISSUE TITLE
[TF2] pl_cashworks: RED 2nd spawn can teleport BLU players into the red last spawn

### ISSUE THREAD

**Issue by fd314** [ValveSoftware/Source-1-Games#5306]
RED players inside the 2nd spawn are teleported to the final spawn when BLU captures the 2nd point.
Jumping under the RED 2nd spawn floor and crouching will teleport both RED and BLU player into RED final spawn.

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Updated pl_cashworks

This needs to be retested.

**Comment by kisak-valve** [comment]
Closing per the last comment.
