### ISSUE TITLE
[Left 4 Dead 2 Beta] broken texture or something

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#531]
Found a prop that appears to have something broken in the material. Might be an unbuilt cubemap, might be a missing texture, can't tell for sure. But I'd know that shade of fuchsia anywhere:

![2013-05-09_00013](https://f.cloud.github.com/assets/3085348/484878/25e152ca-b8e4-11e2-9289-6e7e051cfa2d.jpg)

It's in the last map of The Passing (c6m3_port.bsp), right near the beginning, off to the right when you go up the steps. Just look for the nearly-pitch-black room blocked by boxes. Can anyone else confirm this?

**Comment by kisak-valve** [comment]
Hello @stevethepocket, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
