### ISSUE TITLE
[TF2] Option to enable/disable all images uploaded by players (sprays, objectors, clan prides, etc etc)

### ISSUE THREAD

**Issue by xCommandoBoocex** [ValveSoftware/Source-1-Games#5320]
Would be a very good option, Valve, how have you not added this yet

Also while we are at it, why not also re-enable sprays in Casual servers?

**Comment by kisak-valve** [comment]
Hello @xCommandoBoocex, this feature request is already being tracked at #4249. Closing as a duplicate.
