### ISSUE TITLE
[Left 4 Dead 2 Beta - Linux] Sluggish performance during first minute of campaign

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#533]
First of all, I wanted to say that I am quite impressed by this port so far. After the abysmal performance in _Team Fortress 2_, I almost didn't bother downloading this game because I figured it would be even worse, given that it's two years newer and more resource-intensive and all. But wow. Even with my crappy AMD legacy driver, it runs great so far, at least in single player. When you said you were able to get the game to run faster in Linux than Windows, I believe it. Why couldn't TF2 have been ported to this engine build?

The only major issue I'm having is when I first start a campaign. The framerate is a slideshow, and even the audio stutters. After the first thirty seconds or so, though, it's gotten up to speed and I can actually play. It's almost as if it's still trying to load in data for graphics or sound files after the map starts. Subsequent maps in the campaign don't cause problems either.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Operating System Version:
    Ubuntu 12.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-29-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 4800 Series    

```
Driver Version:  3.3.11672 Compatibility Profile Context
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x944a
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                        53.1cm x 29.9cm  (60.9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  487728 Mb
    Largest Free Hard Disk Block:  394646 Mb

Playing with all settings on High, shaders on Extra High, filtering on Trilinear. Native resolution. Hard drive is 7200 RPM, I believe.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. This type of render stalling is expected with OpenGL video drivers that do not support an on-disk shader cache.
