### ISSUE TITLE
[HL2-Linux] No FOV changing

### ISSUE THREAD

**Issue by MortimerMcMire315** [ValveSoftware/Source-1-Games#534]
Greetings,
It is currently impossible to change the FOV in Half-Life 2 (Beta). The FOV slider changes nothing, and 'fov_desired ##' changes nothing.

If it matters, I am currently running Arch Linux x86-64 with Awesome Window Manager and using a Radeon HD 7850 graphics card.

Thank you for helping to establish Linux as a gaming platform!

**Comment by kisak-valve** [comment]
Hello @MortimerMcMire315, we'll need a way to reproduce this issue to investigate further. Closing pending steps to reproduce.
