### ISSUE TITLE
[ALL] February 15th 2024: Steam EOL on macOS 10.14: x64 Source Engine required for 10.15+

### ISSUE THREAD

**Issue by ChampionCynthia** [ValveSoftware/Source-1-Games#5340]
Steam on macOS 10.14 Mojave now displays an end-of-life banner regarding [Steam's End-of-Life on macOS 10.13 High Sierra and 10.14 Mojave on February 15th, 2024](https://help.steampowered.com/faqs/view/743F-2E0E-C9A5-C375).

[As the English page states:](https://help.steampowered.com/en/faqs/view/743F-2E0E-C9A5-C375)

> Unfortunately, macOS 10.14 was the last version to support running 32-bit games on macOS. Apple chose to drop support for 32-bit applications in macOS 10.15 (released 2019), and since many developers have not updated their games to support 64-bit executables, some games will effectively stop functioning on macOS. The Steam store will stop considering games that offer only 32-bit macOS binaries to be Mac compatible at the end of 2023. 98%+ of Steam customers on Mac are already running macOS 10.15 or newer. This means 32-bit only games and applications no longer run on your current operating system.

With the exception of Counter-Strike: Global Offensive, all first-party Source Engine games remain 32-bit only on macOS systems.

The page also states:

> After February 15th, 2024, we will no longer support macOS 10.14 or earlier and we are unable to guarantee continued functionality of 32-bit macOS games after that date.

Unless ALL Source Engine games on macOS are updated to a 64-bit branch of the engine, the macOS compatibility of Valve's titles will definitely end.

As a 64-bit Source Engine is very unlikely to happen for any game by that date, this issue mostly exists to remind Valve to remove all indications of macOS compatibility from non-Steam websites they own:

* [Half-Life 2's page at www.half-life.com](https://www.half-life.com/halflife2)
* [Half-Life 2 Episode One's page at www.half-life.com](https://www.half-life.com/episode1)
* [Half-Life 2 Episode Two's page at www.half-life.com](https://www.half-life.com/episode2)
* [Team Fortress's website at www.teamfortress.com](https://www.teamfortress.com/)

Godspeed.

**Comment by kisak-valve** [comment]
Hello @ChampionCynthia, this issue is already being tracked at #2847. Closing as a duplicate.
