### ISSUE TITLE
VAC issue?

### ISSUE THREAD

**Issue by shrubbo** [ValveSoftware/Source-1-Games#5344]
I am unable to join public tf2 matches. I start the search for a match and jjthe "Queued for Casual" message disappears after 20-30sec.
No log entries in steam/debian_installation/logs. I think this problem might be related to the VAC error I get when I try to play CSGO "VAC was unable to verify your game session".

**Comment by kisak-valve** [comment]
Hello @shrubbo, this reads like the issue being tracked at #2820. Closing in favor of the older issue report.

**Comment by shrubbo** [comment]
My list of games is shrinking quickly on Steam. I can not play Garry's mod, Team Fortress, and CS2. Are these bugs being addressed, or should I give up and buy other games elsewhere? Very disappointed I don't have much pocket money and the very little money I have spent feels like it has been wasted on these games.
