### ISSUE TITLE
[TF2] [Bug] The Sleuth Suit cosmetic's "Graveyard" style incorrectly uses a copy of the "Overtime" style

### ISSUE THREAD

**Issue by AzureWoof** [ValveSoftware/Source-1-Games#5350]
The Sleuth Suit is a cosmetic item for the Engineer that was added in the Smissmas 2023 patch. It has 4 styles: Dayshift, Off Duty, Overtime, and Graveyard.

The Dayshift and Off Duty style have a lighter overcoat, and the only difference between the two is that one has a tie, and the other doesn't.

For the Overtime and Graveyard styles, the overcoat is darker, and Overtime has a tie while Graveyard is supposed to remove it. However, the Graveyard style is currently broken and uses the same exact style as Overtime, keeping the tie while it should be removing it.

**Comment by gabrielwoj** [comment]
Was fixed in the [December 18, 2023 Patch](https://store.steampowered.com/news/app/440/view/3872596847170779919).

**Comment by gabrielwoj** [comment]
Was labeled as "Need Retest", so here you go. Four screenshots taken today, on December 26, 2023, showing that the Overtime and Graveyard styles are now properly being used in the game, as shown via the "Inspect in Game..." screen.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/13741779/3ea40c70-790e-4019-88cb-47ac65250f15)

![image](https://github.com/ValveSoftware/Source-1-Games/assets/13741779/949cd8f0-97e2-4e21-a2d4-ef79bc7c88d3)

![image](https://github.com/ValveSoftware/Source-1-Games/assets/13741779/60448269-c308-4ae7-8c88-73d563b9224c)

![image](https://github.com/ValveSoftware/Source-1-Games/assets/13741779/4729aad0-4030-496b-8a2e-34de606e821a)

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
