### ISSUE TITLE
[All] February 15th 2024: Drop support for 32-bit macOS games after Steam support for High Sierra and Mojave is dropped.

### ISSUE THREAD

**Issue by Wadmodder** [ValveSoftware/Source-1-Games#5351]
Given that Valve has announced that it will no longer support Steam on macOS High Sierra and Mojave, it would officially make sense for Valve to drop support for the macOS clients of their First-Party titles due to their reliance on the now-discontinued Carbon APIs that were 32-bit.

Since Valve never took the time or resources to upgrading their game clients to 64-bit for anything other than CSGO Legacy and Dota 2 it would make sense to Delist the macOS versions of their first-party titles that never made the transition to 64-bit.

**Comment by kisak-valve** [comment]
Hello @Wadmodder, this is functionally the same as #2847. Closing as a duplicate.
