### ISSUE TITLE
[TF2] How to fix broken lightning and missing sounds in class selection screen

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#5354]
Note: This discovery was made by "DistantPeak" and was only posted here for the purpose of better visibility, I take no credits in this, and if theses fixes where to be implemented in the near future, does not wish to be credited, for this isn't my work and only it's creator should deserve it.

Link to the fix https://gamebanana.com/mods/483548

The class selection screen currently has two major issues:
-Broken Lightning
-Missing sound effect

as it turns out, the code for theses is completely absent from the "classselect.res" files and, according to "DistantPeak" should look like this: (This was directly taken from his own explanation, for they acknoledge this fix with custom huds in mind)

This mod restores the 2007 class selection lighting and sound effects. It doesn't support 4:3

//paste this in your classselect.res below if you use a custom hud

"lights"
        {
            "spotlight"
            {
                "name"                    "spot"
                "color"                 "0.85 0.85 0.85"
                "attenuation"            "0.9"
                "origin"                "0 0 200"
                "direction"                "320 10 0"
                "inner_cone_angle"        "5"
                "outer_cone_angle"        "200"
                "maxDistance"            "0"
                "exponent"                "5"
            }
        }

//Here's Where You Paste It

"TFPlayerModel"
    {
        "ControlName"    "CTFPlayerModelPanel"
        "fieldName"        "TFPlayerModel"
       
        "xpos"            "122"
        "ypos"            "0"
        "zpos"            "6"       
        "wide"            "450"
        "tall"            "480"
       
        "autoResize"    "0"
        "pinCorner"        "0"
        "visible"        "1"
        "enabled"        "1"
       
        "render_texture"    "0"
        "fov"            "25"
        "allow_rot"        "0"

        "paintbackground" "1"       
        "paintbackgroundenabled" "1"
        "bgcolor_override" "255 255 255 0"

        "lights"
        {
            "spotlight"
            {
                "name"                    "spot"
                "color"                 "0.85 0.85 0.85"
                "attenuation"            "0.9"
                "origin"                "0 0 200"
                "direction"                "320 10 0"
                "inner_cone_angle"        "5"
                "outer_cone_angle"        "200"
                "maxDistance"            "0"
                "exponent"                "5"
            }
        }
       
        "model"
        {
            "force_pos"    "1"

            "angles_x" "0"
            "angles_y" "180"
            "angles_z" "0"
            "origin_x" "320"
            "origin_y" "10"
            "origin_z" "-49"
            "frame_origin_x"    "0"
            "frame_origin_y"    "0"
            "frame_origin_z"    "0"
            "spotlight" "1"
       
            "modelname"        ""
            "vcd"        "class_select.vcd"       
           
            "animation"
            {
                "name"        "PRIMARY"
                "activity"    "ACT_MP_STAND_PRIMARY"
                "default"    "1"
            }
            "animation"
            {
                "name"        "SECONDARY"
                "activity"    "ACT_MP_STAND_SECONDARY"
            }
            "animation"
            {
                "name"        "MELEE"
                "activity"    "ACT_MP_STAND_MELEE"
            }
            "animation"
            {
                "name"        "BUILDING"
                "activity"    "ACT_MP_STAND_BUILDING"
            }
            "animation"
            {
                "name"        "PDA"
                "activity"    "ACT_MP_STAND_PDA"
            }
            "animation"
            {
                "name"        "ITEM1"
                "activity"    "ACT_MP_STAND_ITEM1"
            }                       
            "animation"
            {
                "name"        "ITEM2"
                "activity"    "ACT_MP_STAND_ITEM2"
            }   
            "animation"
            {
                "name"        "MELEE_ALLCLASS"
                "activity"    "ACT_MP_STAND_MELEE_ALLCLASS"
            }                               
        }
    }

**Comment by kisak-valve** [comment]
Hello @condor00fr, you've already reported this issue at #4121. Since this adds a bit more detail, I've transferred this issue report to the opening post.

Closing as a duplicate.

**Comment by condor00fr** [comment]
ty
