### ISSUE TITLE
[TF2] Class Selection Needs Fixing

### ISSUE THREAD

**Issue by AtomicTEM** [ValveSoftware/Source-1-Games#5358]
https://steamcommunity.com/sharedfiles/filedetails/?id=2153744818

Class Selection Issues
1) The lighting on the models is awkward due to a removed spotlight.
2) All animation sounds, such as the ground impact sound when the Soldier slams his Rocket Launcher on the floor, or do not play at all.
3) The facial animations don't get reset when the class model changes.
4) The class animations are jittery, skip frames or have delayed playback.

**Comment by kisak-valve** [comment]
Hello @AtomicTEM, this issue is already being tracked at #4121. Closing as a duplicate.
