### ISSUE TITLE
F.e.a.r 2005 controls reset

### ISSUE THREAD

**Issue by Drgham-iuuo** [ValveSoftware/Source-1-Games#5361]
I have no idea why is this happening, but always in F.e.a.r 2005 , part of configured controls reset to unassigned (most of movement controls and half of the rest). Does anyone have this issue? And most importantly, does anyone know how to stop this from happening? My os is Windows 7

**Comment by kisak-valve** [comment]
Hello @Drgham-iuuo, this game is not developed by Valve. Report this issue to the game's developers.
