### ISSUE TITLE
[TF2] Bypass building limitations in Engineer training

### ISSUE THREAD

**Issue by MN-Discord** [ValveSoftware/Source-1-Games#5368]
**Description**
You can bypass the selected building limitations when you start the engineer training map by using the commands "build #"

**Reproduction steps**
Start up the Engineer training mode, open the console, type in any of the build commands for example "Build 3" then place it

_(how to vid below)_

**Additional files**
https://youtu.be/2CcX2a_76SM
https://github.com/ValveSoftware/Source-1-Games/assets/96924240/b1bf9092-9bb7-4bc8-8434-fa1a58d446ac

**Comment by kisak-valve** [comment]
Hello @MN-Discord, while mildly amusing, I'm not seeing a functional problem here that needs to be corrected because the training mode is single player.

If this happens on a multiplayer game mode, that's worth pondering further.
