### ISSUE TITLE
[TF2] mvm_bigrock projectile blocking props 

### ISSUE THREAD

**Issue by MN-Discord** [ValveSoftware/Source-1-Games#5369]
**Description**
Some "props" in mvm_bigrock will block energy projectiles (bison shots, short circuit energy balls, and pomson 6000 shots)

**Reproduction steps**
Stand close to the outside of the front windows and try firing - stand next to the fences in the big open area to the right of the cave entrance 

_(how to vid below)_

**Additional files**
https://youtu.be/UqXl2bfSGT8
https://github.com/ValveSoftware/Source-1-Games/assets/96924240/bb38a799-55f4-4faf-a7ed-e6518c4dbc01

**Comment by JoriKos** [comment]
Issue already tracked here #4869

Also seems like you may have added the wrong github link there, as it links to a video of the Engineer building during the tutorial.
