### ISSUE TITLE
[TF2] Inconsistent damage to buildings and players from the same weapon

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#5382]
Damage to buildings appears to be rounded down rather than up. The Axtinguisher (for example) does 43.55 damage per swing, on players this results in 44 damage, but on buildings this does 43 damage. It's not a major issue, but it seems like it would be a simple change from round down to round up for building damage. As far as I know this would not effect the Jag or Neon Annihilator.

**Comment by kisak-valve** [comment]
Hello @JoriKos, this issue is already being tracked at #4364. Closing as a duplicate.
