### ISSUE TITLE
[TF2] Windows build is shipped to Linux

### ISSUE THREAD

**Issue by idoleat** [ValveSoftware/Source-1-Games#5383]
Today After I updated the game, I found I could not launch the game and in the game file directory the executable is a .exe file. Seems the Windows build is shipped to Linux?
My system:  
`6.6.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000 x86_64 GNU/Linux`
My tf2log.txt
```
ERROR: ld.so: object '/home/idoleat/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/idoleat/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/idoleat/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/M.2_1/SteamLibrary/steamapps/common/Team Fortress 2/hl2.exe: /mnt/M.2_1/SteamLibrary/steamapps/common/Team Fortress 2/hl2.exe: cannot execute binary file
```

**Comment by kisak-valve** [comment]
Hello @idoleat, you've described the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9875.

Opt into Steam's client beta, then toggle the per-game Steam Play setting on and off to nudge the Steam client out of the misconfiguration.

Closing in favor of the older issue report.
