### ISSUE TITLE
[TF2] Simple way to crash PASS time games (requires sv_cheats)

### ISSUE THREAD

**Issue by MN-Discord** [ValveSoftware/Source-1-Games#5397]
**Description**
It's possible to crash the game on any pass time map by disabling the timer

**Reproduction steps**
load up any pass time map, pick up the JACK, wait till the time rounds out, put in the command "sv_cheats 1", the use the command "ent_fire team_round_timer disable", finally throw down the JACK and let the timer run out... this will crash the game instantly.

**Additional files**
https://youtu.be/BWGIhw5Sfg4

**Comment by MN-Discord** [comment]
@kisak-valve was fixed in the [recent update!](https://store.steampowered.com/news/app/440/view/3972804306501016270)

**Comment by MN-Discord** [comment]
Was fixed in the [recent update!](https://store.steampowered.com/news/app/440/view/3972804306501016270)

**Comment by kumfc** [comment]
You accidentially reported a bug that can occur on some non-stock community servers or vscript-modified PASS Time, but that's not how you can intentionally crash the server.
With sv_cheats enabled you can do many destructive things including changing server's RCON password (if point_servercommand is not disabled yet), but the easiest one is just "ent_remove worldspawn". You're going by the hard path :)
