### ISSUE TITLE
Half life Deathmatch Source Valve news

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#5404]
In light of the new statement from Valve (listed below) Maybe Git hub should just delete all issue posts and any other info about Hldms
and help them with their new goal. It has been over ten years and not one single thing that they broke has been fixed.

https://www.half-life.com/en/halflife25

"We now consider this anniversary version of Half Life to be the definitive version, and the one we'll continue to support going forward. Therefore, we'll be reducing the visibility of Half Life: Source on the Steam Store. We know Half-Life: Source's assets are still being used by the Source engine community, so it'll remain available, but we'll be encouraging new Half-Life players to play this version instead".

**Comment by kisak-valve** [comment]
Hello @1157, emphasis on the refresh of the original game does not void past feedback on different games. This is a request for an anti-feature.

**Comment by 1157** [comment]
" the one we'll continue to support going forward" They wont support any other versions.
No support "going forward" means all these Issues that have been posted are just a waste of time and effort and never will be looked at. What they have done is not cool.
