### ISSUE TITLE
[TF2] Item Servers have been down for almost 2 days

### ISSUE THREAD

**Issue by AzureWoof** [ValveSoftware/Source-1-Games#5411]
The item servers for TF2 seem to have been having major issues as of late for almost 2 entire days now. It's extremely rare for it to actually let you use your loadout, especially on official servers. Posting this here because this is abnormal behavior.

**Comment by kisak-valve** [comment]
Possible duplicate of #5405.

**Comment by BreavyTF2** [comment]
Items are back online.

**Comment by gaelcoral** [comment]
I can confirm that the item servers are now working!
![2024-01-11 (10)](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/a3452289-3944-4362-beb4-92412de2dd93)

**Comment by AwesomeCoder412412** [comment]
Definitely want to close this, as it's fixed @kisak-valve

**Comment by kisak-valve** [comment]
Closing per the handful of comments.
