### ISSUE TITLE
portal

### ISSUE THREAD

**Issue by OzanAkpinarIFL** [ValveSoftware/Source-1-Games#5416]
achievments
I got all the achievments but the "cupcake" achievment is not shown at steam page. precisely this is a bug because I got the "vanilla crazy cake" and the "fruitcake" achievments
system:
RAM: 32506 Mb
Windows 11 (64 bit
CPU Brand: 12th Gen Intel(R) Core(TM) i5-12450H
Driver: Intel(R) UHD Graphics
Driver Version: 31.0.101.3688
files:
![Screenshot 2024-01-12 161325](https://github.com/ValveSoftware/Source-1-Games/assets/147243373/60843ed5-30e2-4525-b5de-7425b3c5c228)
![Screenshot 2024-01-12 161310](https://github.com/ValveSoftware/Source-1-Games/assets/147243373/9954ccf3-c541-48ea-a23f-c7e1e10f7de7)

**Comment by kisak-valve** [comment]
Hello @OzanAkpinarIFL, this issue is already being tracked at #981. Closing as a duplicate.

**Comment by OzanAkpinarIFL** [comment]
> Hello @OzanAkpinarIFL, this issue is already being tracked at #981. Closing as a duplicate.

dude... it has been 11 years...

**Comment by JoriKos** [comment]
> > Hello @OzanAkpinarIFL, this issue is already being tracked at #981. Closing as a duplicate.
> 
> dude... it has been 11 years...

Kisak's only here to moderate the github, they can't control what Valve does and doesn't fix.
