### ISSUE TITLE
Audio Stutter in Half Life 2 (But not in episodes)

### ISSUE THREAD

**Issue by AnOpenSauceDev** [ValveSoftware/Source-1-Games#5429]
On both my Linux PC and my Steam Deck (running stock SteamOS), opening Half-Life 2 both natively and on Proton Experimental causes a weird audio stutter after the intro video. Re-Installing/deleting saves/verifying integrity hasn't fixed anything for me. This does not happen in Episode 2.

Video

https://github.com/ValveSoftware/Source-1-Games/assets/119765865/07885020-e901-4f7a-a4b4-8fa66c4b6da0

This is on my Steam Deck, in Desktop Mode (Gaming mode is the same)

**Comment by Joshua-Ashton** [comment]
Is the value of snd_mixahead different between the games?

**Comment by AnOpenSauceDev** [comment]
> Is the value of snd_mixahead different between the games?

I'll go check, but when i was messing with `snd_mixahead` on Half-Life 2 before posting this issue, nothing seemed to change at all.
