### ISSUE TITLE
[TF2] [Gameplay Hindering] Broken Particles on Incinerator Killstreak Particle - Fix Included

### ISSUE THREAD

**Issue by Sir-Dapper** [ValveSoftware/Source-1-Games#5430]
**Description:**
A bug with all Incinerator Professional Killstreak Effects causes the particles to appear larger at a distance. This could affect gameplay and be considered "pay-to-win" as it causes visibility issues for the head. This is caused by a scaling problem with the effects base particle. No other killstreak effect has this problem.

**Fix:**
I contacted community creator Cheesypuff to assist in this fix and we located the source of the issue, provided below is a folder that contains a .vmt and a .pcf that will rectify this problem.

Change "particle_glow_05.vmt" "killstreak_t6_lvl1.vmt" and "klillstreak_t6_lvl2.vmt" to the new .vmt provided in the folder.

Hopefully, this is simple enough to fix! For any complications or questions please reach out to my email!
![combined](https://github.com/ValveSoftware/Source-1-Games/assets/89852963/d3449f87-fbaa-4e14-98b6-6bd0d4a59a36)

[particle_glow_fix.zip](https://github.com/ValveSoftware/Source-1-Games/files/14030917/particle_glow_fix.zip)
**Changelog:**
1/23/24 - Re-Uploaded Fix to increase glow to represent more of the original stylization

**Comment by eray5800** [comment]
Great Work 👍 Fixed version looks much better and you can actually see the face

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed Incinerator killstreak effect not scaling properly when viewed from a distance (community fix from SirDapper and CheesyPuff) 

This needs to be retested.

**Comment by kisak-valve** [comment]
Closing per the last comment.
