### ISSUE TITLE
[TF2][x64_linux_test] Rocket model not aligned with direction of travel

### ISSUE THREAD

**Issue by laurirasanen** [ValveSoftware/Source-1-Games#5431]
In the new x64_linux_test branch, rocket models can be rotated slightly off the direction of travel.

Repro steps:
- Aim as far down as you can (89.0 pitch)
- Fire a rocket
- The rocket model has a slightly lower pitch than it should

![image](https://github.com/ValveSoftware/Source-1-Games/assets/26773737/a9821992-7c3e-4eaa-9e2b-7feebd69c098)

**Comment by Joshua-Ashton** [comment]
Are you testing on Windows or Linux?

**Comment by Marioiscool246** [comment]
Fairly certain this always existed with rockets but I could be wrong.

**Comment by JoriKos** [comment]
> Fairly certain this always existed with rockets but I could be wrong.

I thought so too, they start off sideways because of the viewmodel. Perhaps test this on the Original?

**Comment by Marioiscool246** [comment]
Yeah, I just tested on the main branch of TF2. The rocket projectile angle stays straight forward from your eye angles while having slight movement to the left from the stock's projectile fire offset. This doesn't seem to happen with the original from my testing due to the centerfire projectile attribute.

**Comment by laurirasanen** [comment]
@Joshua-Ashton Testing on Linux. Running a listen server with `map` command.

I know the stock launcher shoots from an offset position but that's not what I'm talking about. The rocket model itself is rotated away from the direction of travel.

Here's a quick video showcasing the difference between beta branch and main: https://www.youtube.com/watch?v=NjK7UFsMA0I

Hopefully you can see what I mean with the pitch being off (the nose of the rocket pointing upwards a bit too much). Works shooting horizontally as well.

**Comment by JoriKos** [comment]
> Hopefully you can see what I mean with the pitch being off (the nose of the rocket pointing upwards a bit too much). Works shooting horizontally as well.

Ah it's the rocket model itself that's tilted the wrong way, not the trajectory?

**Comment by Joshua-Ashton** [comment]
Is this still an issue on the latest update to the branch?

**Comment by laurirasanen** [comment]
Still happens on build id 13273769.

**Comment by Joshua-Ashton** [comment]
I think *maybe* this is fixed in the next update?

![image](https://github.com/ValveSoftware/Source-1-Games/assets/21316711/346b42c5-3f44-436f-ab83-eea1943b6982)

**Comment by laurirasanen** [comment]
Re-tested in build 13284853 and seems to be fixed now, thanks.
