### ISSUE TITLE
[x64_linux_test] TF2 not launching

### ISSUE THREAD

**Issue by goober-183** [ValveSoftware/Source-1-Games#5435]
OS: Linux
Distro: Ubuntu 22.04.3 LTS
GPU info: Intel HD Graphics 4000, "4.2 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1"
Extra Info: late 2012 mac mini running linux

Whenever you Press the launch button, No window appears, and then a few seconds later, The Button goes back to saying launch
Going back to the main branch shows that the game runs just fine, But going back to "x64_linux_test" Shows the same problems.

**Comment by Joshua-Ashton** [comment]
Hello, can you please try launching with `-gl`?

**Comment by Marioiscool246** [comment]
I am currently having this issue on steam deck as well.

**Comment by Joshua-Ashton** [comment]
> I am currently having this issue on steam deck as well.

This is unrelated. That's just the runtime launching in the wrong config there right now.

**Comment by Marioiscool246** [comment]
> > I am currently having this issue on steam deck as well.
> 
> This is unrelated. That's just the runtime launching in the wrong config there right now.

Ah okay thanks.

**Comment by naydef** [comment]
I had the same issue before, but it got fixed by unchecking "Force the use of a specific Steam Play compatibility tool" in Properties

**Comment by goober-183** [comment]
> Hello, can you please try launching with `-gl`?

Adding -gl worked! Thanks
