### ISSUE TITLE
[TF2] (x64_beta_linux) The Medic syringes are Scottish Resistances

### ISSUE THREAD

**Issue by Eerorri** [ValveSoftware/Source-1-Games#5443]
Not visible in firstperson, only in thirdperson or if other Medics are using the Syringe Gun
https://www.youtube.com/watch?v=bJOYaFf58vk

**Comment by JoriKos** [comment]
I think this is a feature

**Comment by 5225225** [comment]
This seems fixed now, cannot reproduce anymore.

**Comment by Eerorri** [comment]
Yea seems to be fixed
https://youtu.be/nGA257P-puQ
