### ISSUE TITLE
[TF2] [x64_linux_test] command execution order different from 32-bit build

### ISSUE THREAD

**Issue by ReplayCoding** [ValveSoftware/Source-1-Games#5444]
The new 64-bit branch has different behaviour relating to commands and what order they are executed in when using the `exec` command

#### how to reproduce
```
# autoexec.cfg
exec test.cfg;echo main1
echo main2  

# test.cfg
echo test1
echo test2
echo test3
```
when the autoexec is run, it will result in the following console output:
```
test1 
main1 
test2 
test3 
main2 
```
whereas on the 32bit public branch `main1` is printed after `test3`.

this is not a console output bug, but a command execution order bug, as the following scripts will result in `Unknown command "test2"`:
```
# autoexec.cfg
exec test.cfg;test2

# test.cfg
alias test"echo blah"
alias test2"echo blah2"
```

**Comment by Joshua-Ashton** [comment]
This will be fixed in the next update. Thanks for the very clear report. I appreciate it greatly :smile:

**Comment by ReplayCoding** [comment]
Fixed in the latest update
