### ISSUE TITLE
[TF2] [x64_linux_test] Passtime crash when match is started

### ISSUE THREAD

**Issue by sekalengrengginang** [ValveSoftware/Source-1-Games#5448]
Passtime gamemode crash on x64_linux_test branch

How to reproduce
1.Load Passtime map like pass_timbertown
2.Wait until match is started
3.When match is started game is freeze and crash

**Comment by Joshua-Ashton** [comment]
Will be fixed in the next update.

**Comment by sekalengrengginang** [comment]
can't reproduce it anymore on local server since last  64 bit update
