### ISSUE TITLE
[TF2] [x64_linux_test] DRI_PRIME envvar is not honored 

### ISSUE THREAD

**Issue by yiitbrak** [ValveSoftware/Source-1-Games#5450]
Tf2 doesn't seem to honor DRI_PRIME envvar, which is used to hint applications about which gpu to use with computers with hybrid graphics. In my case Tf2 uses my discrete GPU regardless of envvar value, unless I virtually remove it from my system with `nvidia-smi drain -p 0000:XX:00.0 -m 1`, then it uses my integrated GPU. This happens with both wayland and xwayland.
Usually it would make sense to use discrete GPU for gaming but with nvidia drivers randomly breaking it's nice to have the option.

**Distro**: Fedora 39 Workstation
**dGPU**: NVIDIA GeForce MX550
**iGPU**: Intel Xe (via 12th Gen Intel Core i7-1255U)

**Comment by kisak-valve** [comment]
Hello @yiitbrak, this reads more like a video driver / general Linux graphics ecosystem issue than a game issue. As far as I know, the NVIDIA proprietary driver is not expected to respond to DRI_PRIME.

I'd test how it behaves with the game's launch options set to `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=non_NVIDIA_only %command%` (from https://download.nvidia.com/XFree86/Linux-x86_64/545.29.06/README/primerenderoffload.html).

**Comment by yiitbrak** [comment]
After a bit more reading, yeah you're right.
Except
> `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=non_NVIDIA_only`  

Doesn't seem to do anything, using `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json` instead seems to do the trick. Closing as this is not related to Tf2.
