### ISSUE TITLE
[TF2] [x64_linux_test] several different projectiles collide with friendlies

### ISSUE THREAD

**Issue by MeatwadMeatwad** [ValveSoftware/Source-1-Games#5456]
![20240129022857_1](https://github.com/ValveSoftware/Source-1-Games/assets/14251041/f2650511-9c71-4e46-bf5d-34fabf6a19ef)
When a teammate is shot from a distance and at a low enough power (velocity), The huntsman arrow collides and the appropriate visuals appear as if they were an enemy. This is not a visual bug, it actually stops the projectile.

This seems to be dependent on the arrow's speed, with slower arrows impacting friendlies and faster ones not.
I recorded a video documenting this.
https://www.youtube.com/watch?v=txIGi_Cegyw

**Comment by MeatwadMeatwad** [comment]
NOTE:
after further testing, the

**Comment by MeatwadMeatwad** [comment]
disregard the last close, it was an error.
What I meant to say was that after further testing, it appears SEVERAL different projectiles suffer from this issue.
Of these projectiles i've tested, all arcing projectiles collide with teammates. below are some examples, done in a similar manner to the huntsman video
flying guillotine
sandman
flaregun
manmelter
scorch shot
gas passer
rescue ranger
pomson 6000
syringe gun
blutsauger
overdose
huntsman (seen above)

my assumption about speed is likely wrong. I assume that the projectile has to arc downward enough for it to detect as a hit. Not sure about the specifics, though.

**Comment by MeatwadMeatwad** [comment]
forgot to open

**Comment by MeatwadMeatwad** [comment]
nvm. some examples are not bugs (apparently).

**Comment by ldesgoui** [comment]
For what it's worth, the majority of projectiles start hitting teammates after they are 250 milliseconds old (or maybe 200, I can't fully remember), so yeah it's an expected behavior

**Comment by MeatwadMeatwad** [comment]
Yeah that's why I closed it.
