### ISSUE TITLE
[TF2] [VScript] Increase max movement speed 

### ISSUE THREAD

**Issue by Lizard-Of-Oz** [ValveSoftware/Source-1-Games#5458]
Player movement speed is hard-limited at 520hu/s, and no speed boost can bypass this limit.
A raised speed limit would be welcome, as it's the only way to change the player's velocity without "lag" seen when using other methods such as VScript or trigger_catapult.
Workaround methods (like forcing the player entity think it's mid-air while it isn't) have drawbacks, namely, again, lag.

**Comment by kisak-valve** [comment]
Hello @Lizard-Of-Oz, this request is already being tracked at #4572. Closing as a duplicate.
