### ISSUE TITLE
[TF2] [x64_linux_test] Crash when using snd_restart

### ISSUE THREAD

**Issue by 5225225** [ValveSoftware/Source-1-Games#5465]
To reproduce: just run `snd_restart` while in a game (connected to a dedicated server or a listen server, doesn't seem to make a difference). The game freezes and crashes 10 or so seconds afterwards.

I can send over a core dump if it's needed, but I assume the bug is simple enough to reproduce locally.

**Comment by Joshua-Ashton** [comment]
Should be fixed next update, let me know if you still have issues then.

**Comment by 5225225** [comment]
Can confirm this is fixed now, thank you! :3

Closing since this was a beta-only issue anyways, it's not in stable
