### ISSUE TITLE
[TF2] Proposed Improvements/fixes to French Localization files + class selection screen uptate

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#5467]
Ah... The good old Localization files... we love them, don't we? Well, we certainlely would love them more if they didn't suffer from issues, The French files specifically are.... not so great to say the least, there's a lot of inconistancies, translation errors or items and objects that never received a translation at all and are still unsing theirs american english names unlike most others. Let's fix this shall we?

[Localisation Fixes.zip](https://github.com/ValveSoftware/Source-1-Games/files/14115185/Localisation.Fixes.zip)

This Proposition aims to provide small quality of life improvements to the game by fixing a lot of errors that have been in this game for years, such as:

For French language only:

-Various Items where given a proper name (The Direct hit for instance is still called as such in French, wich makes no sense at all.) Along side numerous small fixes.
 
exemple of the proposed fixes;
 "Equilizer" = "L'Égaliseur"
 "Buff Banner" = "La bannière de prépondérance"
 "Direct Hit" = "Le Coup fatal"
 "Pain Train" = "L'Affliction"
 "Brainiac Googles"= Lunettes de l'Ecervelé"
 "Sniper Rifle" = Fusil à lunettes" (Préviously "Fusil de sniper")
 "Wrench" = Clé à molettes" (Préviously "Clé")

And many, many more!

-I would also like to propose an improvement to the class selection screen tips, thoses aven't been uptated since release and lack many features, here's a bunch of proposed new ideas available in Both French and English:

Pyro: 
"Use your flamethrower's Airbast to reflect any incoming projectiles !" (New)

Engie: 
"Collect metal from ammo boxes to build with!"  (Reworked existing tip, used to say we gained metal from falled weapons, wich is a removed feature)
"Build dispensers of health, metal and ammo! Upgrade them to level 3!"  (New)
"Build and upgrade teleporters to help teammates get to the front lines!" (Reworked existing tip, didn't specified teleporters could be upgraded" 

Medic:
"You have a slow, passive self healing boost!" (New)

Demo:
"(If equiped) Use your sheilds to charge head on into the ennemy ranks!" (New)

Soldier: 
"(If equiped) Your banners can grant your and your teamates various bonuses!" (New)

Heavy:
"Spin your minigun without firing to be ready to maximise damage!" (Previously existing tip, it didn't really told players much, so I improved it)
"(If equiped) Use your lunchbox Item to regain health, share it with friends!!" (New)

All proposed changes are simple drag and drops that can be added indepently from one another based around Valve's personnal headtake, wich you all best of luck, Thank you.

**Comment by kisak-valve** [comment]
Hello @condor00fr, this is functionally the same issue report as #4234. Refresh your older issue report instead of fragmenting the issue across multiple issue reports.

Closing in favor of the older issue report.

**Comment by gaelcoral** [comment]
Hi @condor00fr,

When it comes to localization issues, this can be solved through [Valve's Crowdin](https://valve.crowdin.com/) page. In this case, I strongly recommend you to reach out by [private message (PM)](https://valve.crowdin.com/u/messages/create) to the French localization team. The people whose username ends in `_FRA` are in charge of the French localization. It would be helpful if you could explain to them the situation of the weapons, since, in the [PDF of the French quick reference style sheet](https://www.dropbox.com/s/887i9d9os5jbswl/French%20Quick%20Reference%20Style%20Sheet.pdf?dl=0), I don't see that the translation of the weapons in the game is explicitly prohibited.

As I say, I recommend you to get in touch by PM. 

Good luck!

**Comment by condor00fr** [comment]
Hello, I tried as proposed to try and contact via Valve's Crowding page, however I am confused as certain links and pages gave me an error almost as they seemed to no longer exist. I had encounter similar issues upon having created an older issue for localization improvements when being redirected to the Crowding page. 

I assume that, either Valve no longer support theirs pages, or I simply fail to understand how it exactly work, wich is most likely going to be the later, but you can never trully tell.

Thank you for your time with all of this.

**Comment by gaelcoral** [comment]
> Hello, I tried as proposed to try and contact via Valve's Crowding page, however I am confused as certain links and pages gave me an error almost as they seemed to no longer exist. I had encounter similar issues upon having created an older issue for localization improvements when being redirected to the Crowding page.
> 
> I assume that, either Valve no longer support theirs pages, or I simply fail to understand how it exactly work, wich is most likely going to be the later, but you can never trully tell.
> 
> Thank you for your time with all of this.

Mmm that's strange, the links I gave you works fine for me, you should try it in another web browser but in case you get the same error, try creating a new account.
