### ISSUE TITLE
[CSS] FPS Issue in X86 source games after update of mesa driver

### ISSUE THREAD

**Issue by LaggerIsME** [ValveSoftware/Source-1-Games#5471]
I have problems with x86 source engine games at Fedora Linux 39. The problem same at Flatpak and native versions of Steam. I can run x86 source games, but I have many freezes and unstable framerate in this games. However, if I try to play Garry's mod x64 or Left 4 Dead 2, games work fine without any problems. I have the problem during 2 months.
![Screenshot from 2024-02-02 22-49-13](https://github.com/ValveSoftware/Source-1-Games/assets/98150971/8a62b68b-9ff2-4256-b537-ec4733db8c77)

![Screenshot from 2024-02-02 22-52-06](https://github.com/ValveSoftware/Source-1-Games/assets/98150971/ff1d9e1f-7dab-465d-a46d-9013cc0f6066)

**Comment by kisak-valve** [comment]
Hello @LaggerIsME, if an update to your video driver introduced a performance regression, then that's something to be reported to your video driver vendor.

**Comment by LaggerIsME** [comment]
Nowadays the problem was fixed, but I didn't understand how¯\_(ツ)_/¯
