### ISSUE TITLE
[TF2][Windows 64bit Beta Test] crash on startup

### ISSUE THREAD

**Issue by okamiterasu** [ValveSoftware/Source-1-Games#5476]
Attempting to launch the Windows 64bit beta causes the game to instantly crash with the following error message
![image](https://github.com/ValveSoftware/Source-1-Games/assets/6588251/b33248e1-7a69-49fc-bf03-6cc352994ada)

**Comment by brokenphilip** [comment]
From what I've heard, the VPK loader is currently broken on x64 - you will need to unpack them for now, or wait until it is fixed.

**Comment by Joshua-Ashton** [comment]
Will be fixed next update.

**Comment by okamiterasu** [comment]
Issue resolved
