### ISSUE TITLE
[TF2] [Windows 64 bit] Screen turns black when the game loses or gains focus

### ISSUE THREAD

**Issue by WereTech** [ValveSoftware/Source-1-Games#5480]
Don't know what's causing it, but only an issue on 64 bit branch. It doesn't seem to happen with dx9 but it does with Vulkan. My launch options if they're relevant.

`-console -windowed -noborder -w 1920 -h1080 -novid -nostartupsound -nosteamcontroller -nojoy -noquicktime -condebug -conclearlog -vulkan -snoforceformat -noqueuedload`

**Comment by Joshua-Ashton** [comment]
This is the way your driver implements flipping for fullscreen in Vulkan. There is nothing for us to solve here. It will probably fix itself if your driver vendor ever implements Vulkan swapchains with DXGI under the hood.

**Comment by WereTech** [comment]
Ah ok, I'll just see if a later driver update for Nvidia will fix this sometime later.

**Comment by treacherousfiend** [comment]
I'm not particularly familiar with the inner workings of rendering, but the Nvidia control panel already has a setting for this and it doesn't seem to work? the setting is labelled "Vulkan/OpenGL Present Method" and it has the option "Prefer layered on DXGI Swapchain".
I also decided to follow a guide from the PC Gaming Wiki for setting up layering Vulkan on the DXGI swapchain, which claims to work for DXVK, that suggests setting that option in the control panel as well as recommending changing a hidden profile byte named OGL_DX_PRESENT_DEBUG.

Neither of these settings, as well as messing with a setting labelled "Vulkan/OpenGL Present method" fixes the issue.
I hope you don't mind me pinging you @Joshua-Ashton, but is what you're referring to regarding handling it "under the hood" different from these settings?
Granted there aren't any official settings for the new TF2 exes from Nvidia yet, and they certainly know how this works better than I do, so its possible that they have to do more to fix this, but I'm mostly just curious at this point.
