### ISSUE TITLE
[TF2] (64-Bit) Missing game executable on Linux

### ISSUE THREAD

**Issue by Eerorri** [ValveSoftware/Source-1-Games#5481]
The tf.sh exist, but not tf_linux64, so it can't boot
`/home/---/.local/share/Steam/steamapps/common/Team Fortress 2/tf.sh: line 80: /home/---/.local/share/Steam/steamapps/common/Team Fortress 2/tf_linux64: No such file or directory`

**Comment by sylveonsylvia** [comment]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/78629289/9bf56ee7-fc26-48ad-b9e7-878787c9f6c2)
image proof of the executable being missing

**Comment by Eerorri** [comment]
Fixed
