### ISSUE TITLE
No music in Half-Life 2 due to SELinux conflict.

### ISSUE THREAD

**Issue by coffeehorrors** [ValveSoftware/Source-1-Games#5483]
Hello,

I am attempting to run Half-Life 2 on Fedora Linux. The game runs natively but the music is missing and there are several graphical glitches due to SELinux conflicts. There was an unsafe recommendation to weaken SELinux's security, but I am posting the bug here for visibility.

Thank you.

**Comment by kisak-valve** [comment]
Hello @coffeehorrors, this is the same issue as #2734. Closing in favor of the older issue report.
