### ISSUE TITLE
[TF2] [x64_test] [Linux] Missing "normal" executable

### ISSUE THREAD

**Issue by reDBo0n** [ValveSoftware/Source-1-Games#5485]
The new combined (Windows/Linux) x64 beta for TF2 has now different launch options:
- Play Team Fortress 2
- 64bit Beta Test

I think the idea is to be able to play the "normal" game while inside the beta, so you don't have to switch the beta branch the whole time (which is nice).

But the option "Play Team Fortress 2" doesn't work, because the executable "hl2.sh" is missing.

You either have to add the "normal" version to the beta branch or remove the Launch Option entirely.

**Comment by Joshua-Ashton** [comment]
This is known and not really a bug. The x64 beta only has the x64 beta. This will obviously be resolved when its promoted to stable.
