### ISSUE TITLE
[TF2] [x64_test] Executable name inconsistent with other Source and Valve titles.

### ISSUE THREAD

**Issue by AtomicTEM** [ValveSoftware/Source-1-Games#5486]
Super happy with TF2 finally having its executable be uniquely named and have a unique icon. However, the name of Team Fortress 2's execuatbles, tf.exe and tf_win64.exe is inconsistent with the name of the game Team Fortress 2. Furthermore it is inconsistent in comparison to other Source/Valve games that have 2 in their title, who include the 2 in the executable's name. For example Half-Life 2's executable is named hl2.exe, Counter-Strike 2's executable is named cs2.exe.

Thus the Team Fortres2/TF2 executables' should be named tf2.exe and tf2_win64.exe respectively.

**Comment by Ashetf2** [comment]
probably because the game mod is "tf"

**Comment by Joshua-Ashton** [comment]
The folder is "tf' and the executable name determines the default mod dir.

**Comment by AtomicTEM** [comment]
Oh right I forgot about the "tf" folder.Then change the name of the "tf" folder to "tf2"

**Comment by AtomicTEM** [comment]
> The folder is "tf' and the executable name determines the default mod dir.

Oh right I forgot about the "tf" folder. Then I also suggest changing the name of the "tf" folder to "tf2."
Also why would the name of a folder affect the name of the executable? Previously, the executable was hl2.exe, but the folder was still "tf". What changed, where the name of the executable must absolutely match the main folder in terms of programming/coding?

**Comment by AtomicTEM** [comment]
> We are not changing the name of the game folder after 17 years of it existing as-is. That would break so much for no reason.

Understandable, I hoped that it might changing couldn't break anything, thank you for confirming my delusion. So I guess the executable will remain as being named "tf.exe" and not be changed to "tf2,exe" ?

**Comment by Joshua-Ashton** [comment]
Correct

**Comment by AtomicTEM** [comment]
> Correct

Shame, but its better then hl2.exe :)

Still, respectfully, R.I.P hl2.exe, you made no sense.

**Comment by Ashetf2** [comment]
Close then
