### ISSUE TITLE
Models are displaying missing textures in 2d grids in hammer

### ISSUE THREAD

**Issue by Jacka18l** [ValveSoftware/Source-1-Games#549]
I have gone to opt-in to the sdk_toolsbeta.
Setup the gameconfig and run hammer directly. all works ok.

But the 2d grids now display missing textures on all models, stock or custom it doesnt matter.
this shouldnt be the case and makes working in hammer very untidy.

note: it is only when the prop_ is unselected that it occurs.

![stockmodelnotrendering](https://f.cloud.github.com/assets/4139913/486311/8b987d1a-b91a-11e2-9dc3-fe3560fe5244.jpg)

**Comment by kisak-valve** [comment]
Hello, is this issue still occurring?

**Comment by kisak-valve** [comment]
Closing pending feedback.
