### ISSUE TITLE
[TF2] 64-bit beta bug, not launching

### ISSUE THREAD

**Issue by RunDomRun** [ValveSoftware/Source-1-Games#5499]
When I installed the beta and clicked launch, the game wouldn't open and it looked like it stopped itself. When I try to launch it through a desktop shortcut, it tells me that "hl.exe does not exist", probably because that's where the shortcut points. When I launch it straight from the TF2.exe file, it launches, and then tells me that I can't join any servers because I'm in "insecure mode" and need to restart. Restarting does not fix this issue. I am on Windows 11, and can give more information if needed.

**Comment by illixion** [comment]
Current 64-bit beta doesn't allow joining matchmaking or public servers, and the executable was renamed from hl.exe, hence the shortcut error

**Comment by RunDomRun** [comment]
I wasn't joining casual, I was in the server browser. My bad, shoulda mentioned that.

**Comment by JoriKos** [comment]
> When I installed the beta and clicked launch, the game wouldn't open and it looked like it stopped itself. When I try to launch it through a desktop shortcut, it tells me that "hl.exe does not exist", probably because that's where the shortcut points. When I launch it straight from the TF2.exe file, it launches, and then tells me that I can't join any servers because I'm in "insecure mode" and need to restart. Restarting does not fix this issue. I am on Windows 11, and can give more information if needed.

You can't join servers with it enabled (matchmaking or public servers, only servers you create through the "map" command or "create a server" UI), that is intentional. The shortcut doesn't work because of what illixion mentioned, executable was renamed from hl2.exe to tf.exe.
