### ISSUE TITLE
[HL2} -on linux -  Weapons list for number keys not appearing

### ISSUE THREAD

**Issue by tamccullough** [ValveSoftware/Source-1-Games#550]
Ubuntu 13.04 64 bit with Unity Desktop. Pretty much Vanilla. Except I did an upgrade on this system instead of opting for a complete reinstall of the OS.

For me the weapon list at the top of the screen is not appearing when I press either the keys or scroll with the mouse button. I can select the weapon from memory and cycle through them, but I am not getting no any visual reference icons, just animations beginng the switch,

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
