### ISSUE TITLE
[x64_linux_test] [TF2] after click play and choosing x64 beta closes nothing hapened

### ISSUE THREAD

**Issue by AlexTanuki** [ValveSoftware/Source-1-Games#5503]
OS: Linux Mint 21.2 x86_64
 Kernel: 5.15.0-76-generic
CPU: AMD A4-9120
 GPU: AMD Radeon R3Grap 
 Memory: 8gb one slot
just decided to try x64 beta
after 5 seconds my nickname became blue again

**Comment by kisak-valve** [comment]
Hello @AlexTanuki, this issue is already being tracked at #5491. Closing as a duplicate.
