### ISSUE TITLE
[TF2] [x64_test] SIGSEGV After Changing Levels

### ISSUE THREAD

**Issue by aarmastah** [ValveSoftware/Source-1-Games#5515]
I'm running a dedicated server for Team Fortress 2 on the x64_test beta branch without any addons. My server runs Ubuntu Server 22.04 LTS.

After every couple of level changes (sometimes every level change), the server seems to crash and reload. The debug.log is pretty much empty and does not give me anything useful. Here's the output from the error in gdb:

![image](https://github.com/ValveSoftware/Source-1-Games/assets/1887380/93d8e8ee-f185-4c3c-960a-09417c14c4b8)
`Thread 1 "srcds_linux64" received signal SIGSEGV, Segmentation fault. 0x00007f4d1303f44e in GetContainingEntity (edict_t*) () from /shared/hlserver_64/tf2/tf/bin/linux64/server_srv.so`

When Metamod:Source and SourceMod are installed, the error does not persist, though these addons have their own problems.

**Comment by Joshua-Ashton** [comment]
Should be fixed in the next update

**Comment by kisak-valve** [comment]
Closing per the last comment.
