### ISSUE TITLE
Cannot launch the tf2 x64 beta

### ISSUE THREAD

**Issue by SetOfAllSets** [ValveSoftware/Source-1-Games#5516]
Upon launching with launch options set to ``__GLX_VENDOR_LIBRARY_NAME=nvidia SDL_VIDEODRIVER=wayland %command% -vulkan`` I get the error ``D3D9SwapChainEx: Failed to recreate swap chain: VK_ERROR_INITIALIZATION_FAILED`` and the game does not launch

EDIT:
    OS: Gentoo Linux with kernel version 6.6.16
    WM/COMP: Hyprland wayland with xwayland support
    GPU: Nvidia 2070 mobile max-q refresh with proprietary drivers

**Comment by sekalengrengginang** [comment]
TF2 use DXVK 2.3 that required vulkan 1.3
you can fallback to OpenGL by using `-gl` launch option

**Comment by SetOfAllSets** [comment]
> TF2 use DXVK 2.3 that required vulkan 1.3 you can fallback to OpenGL by using `-gl` launch option

I can launch with vulkan on the 32 bit version and have dxvk installed with d3d9 support.

**Comment by SetOfAllSets** [comment]
I should mention that I cannot launch it on xwayland and must use SDL_VIDEODRIVER=wayland in order to get farther because otherwise I get the error ``Failed to create SDL window: Installed Vulkan doesn't implement either the VK_KHR_xcb_surfaceextension or the VK_KHR_xlib_surface extension``

**Comment by SetOfAllSets** [comment]
> > TF2 use DXVK 2.3 that required vulkan 1.3 you can fallback to OpenGL by using `-gl` launch option
> 
> I can launch with vulkan on the 32 bit version and have dxvk installed with d3d9 support.

Upon trying this, I found it works, both with wayland and (once I enabled X support in the nvidia drivers) Xwayland. I will try to get to the bottom of why vulkan does not work.

**Comment by Tiagoquix** [comment]
OP, does the original issue still persist?

**Comment by vdualb** [comment]
I'm getting this error:
`Failed to create SDL window: Installed Vulkan doesn't implement the VE_KHR surface extension.`
in GNOME wayland session on intel laptop. Steam from flathub 

I was getting some SDL error message (dont remember if it's the same one) before, but restarting steam was helping. Today it doesn't help.

**Comment by SetOfAllSets** [comment]
> OP, does the original issue still persist?

nope, it was started working a while back and now that it's no longer in beta it still works
