### ISSUE TITLE
[X64_Test] [Windows 10] [Team Fortress 2 Dedicated Sever] srcds_win64.exe won't run!

### ISSUE THREAD

**Issue by Wolfcl0ck** [ValveSoftware/Source-1-Games#5523]
### Software Specifications
**Exe Build Date:** Friday, February 9th, 2024, 18:39:25 UTC
**OS:** Windows 10 Home 64-bit
**OS build:** 19045.3570
### Hardware Specifications
**CPU:** AMD Ryzen 9 3900X 12-Core Processor 3.80 GHz
**GPU:** Should be unnecessary, but 4095MB NVIDIA GeForce RTX 2070 (EVGA)
**RAM:** 32 GB DDR4 RAM, 2x 16 GB Corsair, exact model unknown
### Bug
**Summary:** srcds_win64.exe will not run. When attempting to run it, a window appears immediately that says the following:
"Launcher Error
Failed to load the launcher DLL:
%1 is not a valid Win32 application."
**Reproducibility**: Happens every time
**Steps to reproduce:**
1. install Team Fortress 2 Dedicated Server under the branch "x64_test"
2. Attempt to launch srcds_win64.exe in any way   

**Expected outcome:** Source Dedicated Server should launch without issue
**Actual outcome:** Source Dedicated Server fails to launch, giving a launcher error that fails to provide any actual information
**Additional Potential factors:**
My installation is on a separate drive as Steam (but it *is* on the same drive as SteamCMD, from which I installed the application)
I've modified some configuration files for the server.
**Other notes:**
32-bit dedicated sever does *not* cause this error.
I have attempted reinstalling once already to no avail.

**Comment by Joshua-Ashton** [comment]
Should be fixed in the next update

**Comment by Wolfcl0ck** [comment]
can confirm
