### ISSUE TITLE
[Half Life 2] Pipe is being culled improperly

### ISSUE THREAD

**Issue by matthewharvey** [ValveSoftware/Source-1-Games#553]
This one part of the pipe seems as though it is being culled the wrong way. This is a nit-pick, but it might indicate something deeper wrong with the way the engine is culling objects.
Here are some screenshots.
This was in Route Kanal (part 2 I think). Its where you need to raise the water level in order to continue.

![screenshot from 2013-05-09 22 32 27](https://f.cloud.github.com/assets/1594441/486505/5416c00c-b926-11e2-8d13-5e4e4f0eacef.png)
![screenshot from 2013-05-09 22 30 40](https://f.cloud.github.com/assets/1594441/486506/56db733c-b926-11e2-98c1-bbc7f05d70d4.png)

Ubuntu 12.10 Gnome3
Processor Information:
    Vendor:  GenuineIntel
    Speed: 2601 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-28-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 9.0.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x166
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  7690 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  931038 Mb
    Largest Free Hard Disk Block:  787976 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
