### ISSUE TITLE
[HL2] Missing texture in d3_c17_12b

### ISSUE THREAD

**Issue by thatcakepiece** [ValveSoftware/Source-1-Games#5536]
The exact cause of this is unknown. It most likely is a texture that has either been removed or renamed.

| Current  |![texture-new](https://github.com/ValveSoftware/Source-1-Games/assets/98796426/4d5fb020-73a7-4185-8fea-f4d7706ef2ea)|
|----------|---|
| Original |![texture-old](https://github.com/ValveSoftware/Source-1-Games/assets/98796426/992f2ab1-2381-49b9-9e2e-3668f5e7e35e)|

**Comment by kisak-valve** [comment]
Hello @thatcakepiece, this issue is already being tracked at #1184. Closing as a duplicate.
