### ISSUE TITLE
[L4D2] Game crashes with CUtlLinkedList overflow! (exhausted index range)

### ISSUE THREAD

**Issue by vitacell** [ValveSoftware/Source-1-Games#5544]
OS: ArchLinux
Kernel: 6.7.5-arch1-1
CPU: Intel Core i5-2500k
GPU: AMD RX 570 4gb
Memory: 16gb (8+8)

Running ArchLinux, no beta Steam. Having this problem since some years ago. Which appears almost every-time I play the game. Did not replace game files, and no addons installed. Playing on third party servers, before the error, map's objects start to disappear (become invisible) from the map (cars, buildings, boxes...), and some playable characters start to blink. And seconds after that, the game just crashes. In the console it spams this before the crash:

CUtlLinkedList overflow! (exhausted index range)

I also play CS:S and no problems playing the game with replaced "libtcmalloc_minimal.so.4" (Because Valve still didn't fix that).
Portal 1 works fine.
Half-Life 2 Deathmatch also works.

**Comment by kisak-valve** [comment]
Hello @vitacell, this issue is already being tracked at #4461. Closing as a duplicate.
