### ISSUE TITLE
[X64_Test] [Windows 10] [Team Fortress 2] Players cannot connect to Port-Forwarded Listen Server

### ISSUE THREAD

**Issue by Wolfcl0ck** [ValveSoftware/Source-1-Games#5545]
### Software Specifications
**Exe Build Date:** Friday, February 9th, 2024, 18:39:25 UTC
**OS:** Windows 10 Home 64-bit
**OS build:** 19045.3570
### Hardware Specifications
**CPU:** AMD Ryzen 9 3900X 12-Core Processor 3.80 GHz
**GPU:** 4095MB NVIDIA GeForce RTX 2070 (EVGA)
**RAM:** 32 GB DDR4 RAM, 2x 16 GB Corsair
### Bug
**Summary:** When launching a Team Fortress 2 game, players cannot connect using either my personal IP or the steam public IP despite the ports being forwarded to support Team Fortress 2 servers. Steam reports the server as being "Secure," meaning that the proper ports are being forwarded.
**Reproducibility**: Happens every time
**Steps to reproduce:**
1. Launch x64 Team Fortress 2
2. Load into a map, making sure that sv_lan is set to "0" and the expected ports are forwarded (TCP 27014:27050, UDP 3478:4380,27000:27030)
3. Attempt to have a friend join
**Expected outcome:** The friend should be able to connect with one of the IPs given via the "status" command in the console
**Actual outcome:**  The friend is unable to connect, with the "failed after 4 retries" error appearing on their end.
**Additional Potential factors:**
None come to mind.
**Other notes:**
Friend was playing on a completely fresh installation of Team Fortress 2 set to the x64_test beta.
Issue does not happen on standard 32 bit Team Fortress 2

**Comment by Joshua-Ashton** [comment]
This is probably a Windows firewall issue?

**Comment by NULLYUKI** [comment]
This is most likely a issue on the user side. The user might need to change some settings in their Windows Firewall, Router or anti-virus software, as something might be blocking the connection.

**Comment by Wolfcl0ck** [comment]
Went and checked. Looks like this probably _was_ the case. I had apparently turned my firewall back on at some point and since the executable for the 64 branch is named differently, it wasn't on my firewall whitelist. I'm going to confirm it for certain with a friend, and if it works then, we'll know for certain and I can close this one up.

**Comment by Wolfcl0ck** [comment]
confirmed the issue was on my end. Closin now.
