### ISSUE TITLE
[X64_Test] [Windows 10] [Team Fortress 2] Borderless-Windowed does not work as intended

### ISSUE THREAD

**Issue by Wolfcl0ck** [ValveSoftware/Source-1-Games#5546]
### Software Specifications
**Exe Build Date:** Friday, February 9th, 2024, 18:39:25 UTC
**OS:** Windows 10 Home 64-bit
**OS build:** 19045.3570
### Hardware Specifications
**CPU:** AMD Ryzen 9 3900X 12-Core Processor 3.80 GHz
**GPU:** 4095MB NVIDIA GeForce RTX 2070 (EVGA)
**RAM:** 32 GB DDR4 RAM, 2x 16 GB Corsair
### Bug
**Summary:** When launching the game with "-windowed -noborder," the game still treats itself as fullscreen, meaning that, when the game is not responding (such as when loading into maps) it will refuse to move from the front of the screen.
**Reproducibility**: Happens every time
**Steps to reproduce:**
1. Launch x64 Team Fortress 2 with -windowed and -noborder
**Expected outcome:** The game will launch as a window without a border
**Actual outcome:**  The game launches as if it is in fullscreen

**Comment by Ashetf2** [comment]
Are you launching the game with -vulkan?
