### ISSUE TITLE
[X64_Test][Linux][TF2] Game crashing randomly in CLinuxFont::GetCharRGBA

### ISSUE THREAD

**Issue by naydef** [ValveSoftware/Source-1-Games#5553]
Playing with the 64-bit TF2 client, the game will crash from time to time, sometimes crashing minutes from joining a server, other times in about 30-40min. I've attached a debugger and took the [following screenshots](https://imgur.com/a/JvH2Rxj).

The function that is crashing is [CLinuxFont::GetCharRGBA](https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/vgui2/vgui_surfacelib/linuxfont.cpp#L450), however the crashing code seems to be a new check, which is not present in leaked source. (Note ESI is the `ch` variable and its value is rather big) The crashes seems like a out of bounds access of some kind. (but cannot be too sure)

Those crashes occur while playing with live players in FF2 server, so I guess it could be related to the player names containing unusual symbols (emojis or similar), but not sure. Sadly, it's inconsistent and cannot reproduce it on purpose,

**Comment by Joshua-Ashton** [comment]
Will be fixed in the next update

**Comment by naydef** [comment]
I haven't experienced client crashes for some time now, so I guess this specific issue is now resolved.

Closing.
