### ISSUE TITLE
[L4D1] Corrupt font on Linux

### ISSUE THREAD

**Issue by Diggingwolf2605** [ValveSoftware/Source-1-Games#5559]
Left 4 Dead seems to be missing fonts related to Closed Captioning, some in-game chat text has some issues as well. Console text appears to be missing regular Linux fonts as well.

**Comment by kisak-valve** [comment]
Hello @Diggingwolf2605, there's no Linux variant of the Left for Dead (1) client (#1812). This reads like #3917 or #165.

If you've configured Steam to run the game with Proton, then feel free to discuss how the Windows variant of the game behaves on the compatibility report for the game at https://github.com/ValveSoftware/Proton/issues/406.

**Comment by Diggingwolf2605** [comment]
@kisak-valve 

I'm already aware that there is no native support for Linux for the original Left 4 Dead but this issue shouldn't be closed. If there is no support planned for L4D1, then it should be removed from the store page. You are closing issues related to this game but not providing enough details especially since there is no label for this game on here. I currently do not know of any workarounds or any solutions to fix the missing corrupt font for Linux. Valve would need to add proper Linux support to fix the broken fonts.
