### ISSUE TITLE
[L4D1] [Linux] Vertical Sync doesn't work

### ISSUE THREAD

**Issue by Diggingwolf2605** [ValveSoftware/Source-1-Games#5560]
There is a known issue which seems to be related to 'Vertical Sync' being enabled on Linux. When it is enabled, there is screen tearing that results. I've tried both 'Double Buffered' and 'Triple Buffered' which made no difference.

**Comment by kisak-valve** [comment]
Hello again @Diggingwolf2605, same as #5559, there is no Linux variant of the Left for Dead (1) client.
