### ISSUE TITLE
[TF2] [Feature Request] Remove surveys from Casual

### ISSUE THREAD

**Issue by Kruphixx** [ValveSoftware/Source-1-Games#5561]
![Screenshot 2024-03-07 182845](https://github.com/ValveSoftware/Source-1-Games/assets/50501742/2fb9169c-c6a9-4517-b36c-d4867b4f48f1)

At this point I think we can all agree that these surveys are completely unneeded, it's just an annoying pop up. 

I'm sure when Casual was first added Valve used to do something with the data but after all those years there's no point in still having them. They also prevent you from using the chat or voting while they're open.

**Comment by condor00fr** [comment]
I assume that, the data would have determined wherever a map was good enough for competitive, yet if even if I where correct, comp has been pretty much untouched since Blue moon so....

**Comment by JoriKos** [comment]
Better option would be a ConVar to turn them off, but enabling them by default.

**Comment by Kruphixx** [comment]
> Better option would be a ConVar to turn them off, but enabling them by default.

A huge waste of time just to add a convar for this. I don't see why you would want to see the survey if at this point it's completely obsolete? 

Like I said in the original post, it was probably used by Valve to actually collect data back when Casual was first added. Do you think it's still necessary for them to collect data, after almost 8 years, when it's clear that nothing will be done with the data?
