### ISSUE TITLE
[TF2] Fix for CTF HUD being visible when no flags are present

### ISSUE THREAD

**Issue by mtxfellen** [ValveSoftware/Source-1-Games#5576]
The bug in question looks like this:

![](https://i.imgur.com/kH3d6aU.png)

It can be reproduced reliably on ctf_haarp, a map added in Smissmass 2023; join BLU and capture the first flag. Until the second flag spawns, the HUD will incorrectly display as shown above.

This bug is not just limited to ctf_haarp, and can also occur in MvM gatebot maps such as mvm_mannhattan whenever the bomb resets. It will also *always* occur on any MvM mission that does not feature a bomb.

With the addition of VScript allowing for more complex hybrid gamemodes, it's likely that the occurences of this bug on official servers will increase over time.

Fortunately, the fix is trivial; simply add an `if_no_flags` block to the offending HUD elements in `resource/ui/hudobjectiveflagpanel.res`.

The block is structured like so in order to correctly hide the respective elements:

```Valve-Data-Format
Element
{
	[...]

	"if_no_flags"
	{
		"visible"	"0"
	}
}
```

The elements in question are: `LeftSideBG`, `RightSideBG`, `OutlineBG`, `BlueScore`, `BlueScoreShadow`, `RedScore`, `RedScoreShadow`, `PlayingTo` and `PlayingToBG`.

Application of this fix will cause the CTF hud to be correctly hidden like so:

![](https://i.imgur.com/j5gUzAc.png)

This fix does not otherwise impact regular CTF mode maps.

`hudobjectiveflagpanel.res` with the fix applied looks like [this](https://gist.github.com/mtxfellen/75105c1471e5960a5430f0e05326a393). No additional changes were made after sourcing the file from `tf_misc_dir.vpk`; formatting is also kept consistent with the original file.

**Comment by EricS-Valve** [comment]
Should be fixed in the next update. Thanks for the report.

**Comment by mtxfellen** [comment]
>Is it okay to credit you as "fellen" in the update notes?

That's fine by me 👍

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed CTF HUD being visible when no flags are present (Community fix from fellen) 

This needs to be retested.

**Comment by mtxfellen** [comment]
Closing after confirming the changes to hudobjectiveflagpanel.res were applied, and also being unable to reproduce the original test case on ctf_haarp.
