### ISSUE TITLE
[TF2] [x64_test] The game crashes by pressing F7 "the reporting system"

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#5578]
Title

https://github.com/ValveSoftware/Source-1-Games/assets/63524243/285aa85f-5584-44f0-b240-5d8b96703c19

**Comment by DoctorNut** [comment]
I was able to replicate this crash on Windows 11 Home version 23H2 build 22631.3296

**Comment by gaelcoral** [comment]
Fixed!
