### ISSUE TITLE
[TF2] Top Duel Wins no longer appears when loading an official map 

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#5599]
Since some time ago, Top Duel Wins no longer appears when loading an official map
![2024-04-09 (10)](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/9c4114a9-2d27-41f7-97bd-65d1224ebf61)
I also tried it on an alt account in Geforce Now and same issue.
![2024-04-09 (8)](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/fa889f1f-0c42-4d98-97db-1069dde1cd2a)

**This is how it is supposed to look like** 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/eac68220-261f-4614-9b61-b7f1ee080e99)

**Comment by gaelcoral** [comment]
It is now fixed after a long time
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/9a02987e-f9d9-497d-9655-3e5597d1a557)

**Comment by kisak-valve** [comment]
Closing per the last comment.
