### ISSUE TITLE
HDR causing long loading / crashes

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#56]
Issue transferred from ValveSoftware/steam-for-linux#452
@amarildojr posted at 2012-12-29T12:59:01Z:

Hello everyone.

I'm playing TF2 on Ubuntu 12.04 LTS **\* EDIT (64bit) **\* and I'm having the issues bellow:
(Notice: most of these issues do NOT happen on a 100% base)
- After changing the resolution while in-game server, the game freezes and auto-closes;
- When joining a server, the game auto-closes itself;
- Sometimes the FPS rate is good when launching the game via Steam library (+200fps), sometimes it's not (10-20 fps). But it's 100% sure the FPS is going to be good when launching it via Desktop.
- Sometimes after hitting ALT+TAB the game freezes and closes itself.

---
- After first install, trying to join a SERVER via Library makes the game to freeze:

IMG: http://img259.imageshack.us/img259/4150/capturadetelade20121228.png
## Solution: Start an offlline practice server, then go to an online one
- When someone starts a chat with me, notification appears at the bottom of the screen, but once it disappears you can't open the chat window, once it does not exist. Interesting is, the chat stays saved, you just have to start a chat with the person who talked to you, but that's the problem, sometimes it's impossible to see who started and going through every friend starting a chat, is very time-consumable.

Explanation 1 - http://img4.imageshack.us/img4/5950/capturadetelade20121229.png
## Explanation 2 - http://imageshack.us/a/img84/5162/steam2f.png

UPDATE: 12/30 After a few minutes without touching the keyboard and mouse, TF2 closed itself.

That's all for the moment

**Comment by kisak-valve** [comment]
If anyone is still experiencing this issue, please open a new issue report.
In the issue report, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. Additionally, any CrashIDs or minidump (.dmp) files related to the issue would be helpful. You can also optionally reference this issue report.
