### ISSUE TITLE
[TF2] cant open with ubuntu 22.04

### ISSUE THREAD

**Issue by Tira-tw** [ValveSoftware/Source-1-Games#5600]
hello i try open tf2, but fall
how fix?

**Comment by AwesomeCoder412412** [comment]
Could you provide some crash logs?

**Comment by Tira-tw** [comment]
> Could you provide some crash logs?

![image](https://github.com/ValveSoftware/Source-1-Games/assets/64715639/96f1cc1d-de35-4b2b-8fb3-cf8ff5f85c30)

**Comment by Tira-tw** [comment]
> > Could you provide some crash logs?
> 
> ![image](https://private-user-images.githubusercontent.com/64715639/321653416-96f1cc1d-de35-4b2b-8fb3-cf8ff5f85c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDM4ODksIm5iZiI6MTcxMjg0MzU4OSwicGF0aCI6Ii82NDcxNTYzOS8zMjE2NTM0MTYtOTZmMWNjMWQtZGUzNS00YjJiLThmYjMtY2Y4ZmY1Zjg1YzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEzNTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYzc3ZTA0ZGE5YmIwM2I1ZjVhNTA3ZDdlOTEwZGE2OWI2ZDJlNGVjMmY2ODliMTY4NTE3NWQ1MDQyMzc2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.viu4Ysw5oMb5_75ENOJ60HgDZKgnWxlCUjAWGqtwB5Q)

is this?

**Comment by kisak-valve** [comment]
Hello @Tira-tw, `[...]/hl2.exe` this is the Windows variant of the game. Steam for Linux trying to use it without a compatibility layer is an issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9875. Opt into Steam's client beta and if needed, toggle the `Force the use of a specific Steam Play compatibility tool` compatibility setting in the per-game properties to `Steam Linux Runtime`, and then toggle the same setting off.

If this doesn't help, then please add a note to the steam-for-linux issue report.

Closing in favor of the older issue report.
