### ISSUE TITLE
The item "Tux" was promoted as tradeable but isnt'?

### ISSUE THREAD

**Issue by MN-Discord** [ValveSoftware/Source-1-Games#5601]
The item [Tux](https://wiki.teamfortress.com/wiki/Tux) was promoted as tradeable but isn't? I'm assuming this was a coding mistake since we havnt got any news for it being untradeable?

"Team Fortress 2, the Free to Play game, is also now available on Steam for Linux. For a limited time, Steam users who play the game on Linux will automatically receive a free, exclusive in-game item: **Tux, the Linux mascot, can be carried by any of the game’s classes and traded between players**. Additional Valve titles available on Steam for Linux include Half-Life, Counter-Strike 1.6, and Counter-Strike: Source." - [Source](https://store.steampowered.com/oldnews/9943)

**Comment by kisak-valve** [comment]
Hello @MN-Discord, this issue is already being tracked at #2204. Closing in favor of the older issue report.
