### ISSUE TITLE
Casual/MVM Matchmaking Queue automatically cancels itself after cancelling Competitive Matchmaking Queue

### ISSUE THREAD

**Issue by Eshyyyyy** [ValveSoftware/Source-1-Games#5610]
Last night I attempted to queue for TF2 Competitive for a few minutes. I didn't find a lobby so I canceled out of the queue by hitting the X on the queue popout. Today I boot up TF2 and find that Casual and Mann vs Machine both auto boot me from the queue after under a minute. I try queuing up for Competitive again and I am still queued as I am typing this. 
I am unsure if this was the direct cause but I believe this isn't a coincidence. 
I attempted to fix my issue by restarting TF2, relogging into Steam, restarting my PC, and using the console command "tf_party_leave" as I had heard these were common fixes online. None of these worked. 
Looking at tf_party_debug I get this:
![image](https://github.com/ValveSoftware/Source-1-Games/assets/33994713/669d4acc-0c24-4a8a-a159-d5740ca2a1c3)

**Comment by kisak-valve** [comment]
Hello @Eshyyyyy, you've described the issue being tracked at #2820. Feel free to add your experience to the older issue report.

Closing as a duplicate.
