### ISSUE TITLE
TF2 - Major bug for workshop creators (-tools)

### ISSUE THREAD

**Issue by CrimsonLightning10** [ValveSoftware/Source-1-Games#5613]
Due to the new x64 bit update having the -tools in your launch options is no longer possible. What happens is the game will load like normal, it will load the menu as if you didn't do -tools but you can't click on anything. So it still registers you have done -tools however nothing loads. Pressing f9 does nothing and f10 just gives a prompt to exit the game (I couldn't remember if it was f9 and f10 or f10 and f11. However none of them work either way).

This is major for workshop item creators as it is impossible to test items/create unusuals effects until this is fixed.

**Comment by CrimsonLightning10** [comment]
Just adding that im only aware of this for windows. I'm not sure with it on linux.

**Comment by kisak-valve** [comment]
Hello @CrimsonLightning10, this issue is already being tracked at #5513. Closing as a duplicate.
