### ISSUE TITLE
TF2 x64 bit animation bugged

### ISSUE THREAD

**Issue by perkoz323** [ValveSoftware/Source-1-Games#5619]
64 bit version fixed syringe gun animation but demo greanade launcher reloading animation is still broken. It didn't move when demo put grenades inside

**Comment by sylveonsylvia** [comment]
if you're talking about the grenade launchers barrels not rotating when reloading this has never been a thing since the c_ model update back in 2014 iirc, not related to the 64bit branch

**Comment by perkoz323** [comment]
Why did they added syringe gun animation back while demo animation is still broken?

**Comment by kisak-valve** [comment]
Hello @perkoz323, this issue is already being tracked at #2130. Closing as a duplicate.

**Comment by perkoz323** [comment]
okay thx i'm sure u can fix that ❤️
