### ISSUE TITLE
Anti virus detects two files as infected

### ISSUE THREAD

**Issue by Abhishek-Patwal** [ValveSoftware/Source-1-Games#5620]
Upon installation two files have been detected to be infected, please take it up on priority. It leads to the game not being installed.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/48221183/a4c7d82c-f30f-48ff-ace7-095d9e9f7e81)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/48221183/d0147808-b68b-45ae-8341-5230f7090ddb)

**Comment by Koi-TF2** [comment]
+1, Virustotal link for shadercompile.exe here: https://www.virustotal.com/gui/file/83fb94ef1accdc0071ef6221f8e5acf870a1df31ff26e04a8d58116402793911/detection

**Comment by AwesomeCoder412412** [comment]
I've seen this issue quite a lot on Reddit. Here's some more details from one user in particular:

"Bitdefender is detecting the following when I update TF2 and moved these files to quarantine:
The file D:\Steam\steamapps\downloading\440\bin\shadercompile.exe is infected with Gen:Variant.Lazy.390042

The file D:\Steam\steamapps\downloading\440\bin\vrad.exe is infected with Gen:Variant.Lazy.390042

At this time, personally, I am uninstalling TF2 until such a time that I know that these files are safe."

I am not this person, but I figured that this might be helpful.

**Comment by Abhishek-Patwal** [comment]
should i ignore the threat and proceed to install the game, too ecsited to play it

**Comment by Koi-TF2** [comment]
> should i ignore the threat and proceed to install the game, too ecsited to play it

Assuming you are using BitDefender as your AV, which is what it looks like from your screenshots, then in order to download the game you would likely need to ensure that TF2's game directory folder location (user dependent) is added manually into the AV Exclusions list. Doing so should prevent the AV from repeatedly flagging these "infected" files, and allow you to correctly download and launch the game. These files are most likely completely safe and this is likely a case of false positive detection

**Comment by Abhishek-Patwal** [comment]
yeah it worked after  i did it :D

**Comment by Joshua-Ashton** [comment]
The issue with the TF2 x64 Update getting false-positived is really just there were a few SDK tools in there that are not signed like the main game.

Building *anything* with modern MSVC triggers AV these days...

The vast majority of the false-positives go away when these tools are signed, as they are in the next update:
https://www.virustotal.com/gui/file/a1323b34aae07605d572a496ecbfe3f50943e851f3d99441680dccee8ab65e3c/details

So hopefully that fixes the problem for you, when it drops.

**Comment by Spewkwagen** [comment]
> @kisak-valve This has probably been fixed and can be closed since the latest update:
> 
> > Fixed an issue where the game would be falsely detected as malware by some anti-viruses
> 
> https://www.teamfortress.com/post.php?id=220446

Just got hit with my Windows Defender flagging vrad.exe during Steam downloading the update. Identified as 'Trojan:Win32/Acll'.

**Comment by NULLYUKI** [comment]
>Just got hit with my Windows Defender flagging vrad.exe during Steam downloading the update. Identified as 'Trojan:Win32/Acll'.

@Spewkwagen Can you upload the file to [Virustotal](https://www.virustotal.com/gui/) and share the result here?

**Comment by NULLYUKI** [comment]
>Uploaded my download of it to [Virustotal](https://www.virustotal.com/gui/file/8ee6c74151d330e22eb310577ff5f0196a2c9f089af949ae5e9025c77fcdb1ac)

Thank you! I'm quite confused why it has 11 flags while on my end it only received 1 flag.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where the game would be falsely detected as malware by some anti-viruses" in the [2024-04-18](https://www.teamfortress.com/post.php?id=220446) Team Fortress 2 update.
