### ISSUE TITLE
TF2 64 bit Steam deck 

### ISSUE THREAD

**Issue by perkoz323** [ValveSoftware/Source-1-Games#5621]
The game immediately shuts down upon attempting to launch, regardless of the selected launch option on Steam Deck OLED.

**Comment by m0rtykai** [comment]
it's a general linux problem

**Comment by AwesomeCoder412412** [comment]
Perhaps mention the fact that it immediately shuts down in your title? It's a little unclear what this issue is about initially :).

**Comment by perkoz323** [comment]
It works fine with proton experimental

**Comment by AwesomeCoder412412** [comment]
Is it still happening for you after the patch?

**Comment by catdotjs** [comment]
> It works fine with proton experimental EDIT: It works on Proton Experimental, the game launches to the menu but it's not possible to join servers. A message pops up saying 'You are in insecure mode. Restart the game to connect to secure servers.

It works with proton because proton runs the windows version. There is an issue with linux in general right now. Only real way to play native linux is to follow this guide.
https://github.com/ValveSoftware/Source-1-Games/issues/5611#issuecomment-2065521343

**Comment by amuprocode645** [comment]
> > It works fine with proton experimental EDIT: It works on Proton Experimental, the game launches to the menu but it's not possible to join servers. A message pops up saying 'You are in insecure mode. Restart the game to connect to secure servers.
> 
> It works with proton because proton runs the windows version. There is an issue with linux in general right now. Only real way to play native linux is to follow this guide. [#5611 (comment)](https://github.com/ValveSoftware/Source-1-Games/issues/5611#issuecomment-2065521343)

following https://github.com/ValveSoftware/Source-1-Games/issues/5611#issuecomment-2065521343 did make the game launch, however i could not join vac servers (insecure mode?), but the game did work, including steam input. however by running the game in desktop mode using that command you dont get the steam overlay stuff (like my steam input radical menus), so need to figure out how to run the game using that command but within steam

**Comment by doonv** [comment]
> however i could not join vac servers (insecure mode?)

I updated the guide with additional launch options that fixes that (`-secure -steam`)

**Comment by doonv** [comment]
> running the game in Proton is a very bandaid-y solution

Wdym? My guide runs the game natively.

**Comment by TheBucketWasTaken** [comment]
The problem with proton is that it makes the game 10 times more fucking laggy lmao

**Comment by ethanholt1** [comment]
> Wdym? My guide runs the game natively.

Proton is not native, it’s emulation.

**Comment by doonv** [comment]
> Proton is not native, it’s emulation.

Without proton...

**Comment by ethanholt1** [comment]
> > Proton is not native, it’s emulation.
> 
> Without proton... (Steam Runtime isn't Proton)

Huh, maybe I just read your post wrong. Sorry

**Comment by TheBucketWasTaken** [comment]
Is this issue currently being worked on?

**Comment by NightShr00m** [comment]
Try setting your Steam Client to Beta. Worked for me when I tried it on my steam deck.

**Comment by TheBucketWasTaken** [comment]
It works now. I just set my launch thing to the other thing

**Comment by GleammerRay** [comment]
> Proton is not native, it’s emulation.
Proton is not emulation, it's a compatibility layer. Proton isn't meant to be slow as it is utilizing DXVK.

**Comment by AwesomeCoder412412** [comment]
Do not use proton. TF2 through proton is not officially supported, and you will not be able to join official servers through proton. When you use proton, you are running the windows version of tf2 through a compatibility layer. TF2 has a native Linux version. Use that, and if that's broken, the best solution is to report as much info about the bug as you can here so it can hopefully be fixed.

**Comment by ethanholt1** [comment]
> > Proton is not native, it’s emulation.
> 
> Proton is not emulation, it's a compatibility layer. Proton isn't meant to be slow as it is utilizing DXVK.

Could we please not bring semantics here? It’s not native, and that’s what’s important.


> Do not use proton. TF2 through proton is not officially supported, and you will not be able to join official servers through proton. When you use proton, you are running the windows version of tf2 through a compatibility layer. TF2 has a native Linux version. Use that, and if that's broken, the best solution is to report as much info about the bug as you can here so it can hopefully be fixed.

I second this, but as of right now there’s no way to use the native Linux binary on Steam Deck, as well as several distros of Linux. So until this is fixed, you can play with bots under Proton Experimental just fine.

**Comment by doonv** [comment]
> there’s no way to use the native Linux binary on Steam Deck

Have you not seen https://github.com/ValveSoftware/Source-1-Games/issues/5611#issuecomment-2065521343 ?

**Comment by ethanholt1** [comment]
> > there’s no way to use the native Linux binary on Steam Deck
> 
> Have you not seen [#5611 (comment)](https://github.com/ValveSoftware/Source-1-Games/issues/5611#issuecomment-2065521343) ?

I actually haven’t. I guess that does work at least for now. Disregard last post; sorry.

**Comment by AwesomeCoder412412** [comment]
With the latest patch, is it working on the deck now?

**Comment by perkoz323** [comment]
UPDATE: with fix it works but i have to reinstall the game

**Comment by Genera1-Dynamics** [comment]
Does it work fine now on the Steam Deck, and I don't have do to any of the fix mentioned, like it runs natively now?

**Comment by TheBucketWasTaken** [comment]
Yeah dont worry. It was fixed

**Comment by ethanholt1** [comment]
+1, seems to run fine now.
