### ISSUE TITLE
[TF2] Antivirus detects latest update files as false positives

### ISSUE THREAD

**Issue by JacobJenness** [ValveSoftware/Source-1-Games#5623]
**Description:** While downloading the April 18th, 2024 update for Team Fortress 2, my antivirus interrupted the installation by quarantining two files related to the update. Bitdefender prevented `shadercompile.exe` and `vrad.exe` from being downloaded, and detected that both of these files were infected with `Gen:Variant.Lazy.390042`. I've submitted a support case with Bitdefender alerting them that these files are being detected as false positives. 

![Screenshot 2024-04-18 183806](https://github.com/ValveSoftware/Source-1-Games/assets/70217817/53716a8e-fbd5-4464-ad68-e90e0131b06d)
> The file C:\Program Files (x86)\Steam\steamapps\downloading\440\bin\vrad.exe is infected with Gen:Variant.Lazy.390042 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

![Screenshot 2024-04-18 183747](https://github.com/ValveSoftware/Source-1-Games/assets/70217817/de179558-4580-4111-8169-346d53f443f8)
> The file C:\Program Files (x86)\Steam\steamapps\downloading\440\bin\shadercompile.exe is infected with Gen:Variant.Lazy.390042 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Steps to reproduce:** 
1. Install the latest version of Steam on the latest version of Windows 11.
2. Have the latest version of Bitdefender Total Security installed on your machine.
3. Attempt to install Team Fortress 2.
4. The `shadercompile.exe` and `vrad.exe` will be detected as false positives and will be quarantined by Bitdefender.

**Technical Information**
Edition	Windows 11 Home
Version	23H2
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by kisak-valve** [comment]
Hello @JacobJenness, this issue is already being tracked at #5620. Closing as a duplicate.
