### ISSUE TITLE
[TF2][64bit][Windows] New .exe files get flagged by antivirus

### ISSUE THREAD

**Issue by mota-with-a-lambda** [ValveSoftware/Source-1-Games#5626]
When downloading the 64 bit update for TF2 today, my antivirus intecepted the files **shadercompile.exe** and **vrad.exe** and sent them to Quarantine, believing them to be infected by a Trojan. This caused the update to fail the first time (missing files error); on a second attempt, I restored the files from Quarantine and added an exception for them before Steam finished updating the game, and this time it succeeded.

The supposed malware detection name was `Win32:MalwareX-gen [Trj]`. Note that the antivirus intercepted the files while they were still in the download bin, before they could be installed.

If it helps, here are the VirusTotal analyses for [shadercompile.exe](https://www.virustotal.com/gui/file/83fb94ef1accdc0071ef6221f8e5acf870a1df31ff26e04a8d58116402793911) and [vrad.exe](https://www.virustotal.com/gui/file/a81fa5d05d7c680c4b23a5e3d678bd90c3c8b654c7664e044a00e9ab81a0b4ef).

**Comment by kisak-valve** [comment]
Hello @mota-with-a-lambda, this issue is already being tracked at #5620. Closing as a duplicate.

**Comment by AwesomeCoder412412** [comment]
I've seen this issue quite a lot on Reddit. Here's some more details from one user in particular:

"Bitdefender is detecting the following when I update TF2 and moved these files to quarantine:
The file D:\Steam\steamapps\downloading\440\bin\shadercompile.exe is infected with Gen:Variant.Lazy.390042

The file D:\Steam\steamapps\downloading\440\bin\vrad.exe is infected with Gen:Variant.Lazy.390042

At this time, personally, I am uninstalling TF2 until such a time that I know that these files are safe."

I am not this person, but I figured that this might be helpful.
