### ISSUE TITLE
[hl2] Not started

### ISSUE THREAD

**Issue by ClanMax** [ValveSoftware/Source-1-Games#563]
Gentoo linux
Using breakpad crash handler
Setting breakpad minidump AppID = 220
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198082511812 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198082511812
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
AL lib: pulseaudio.c:612: Context did not connect: Access denied
Did not detect any valid joysticks.
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 1
[0510/154920:ERROR:resource_bundle.cc(411)] Failed to load /home/vladan/.local/share/Steam/SteamApps/common/Half-Life 2/cef_gtk.pak
Some features may not be available.
[0510/154920:ERROR:bus.cc(261)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0510/154920:ERROR:bus.cc(261)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0510/154920:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2533 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 2099249152
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2533 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 2099249152
IDirect3DDevice9::Create: BackBufWidth: 1280, BackBufHeight: 1024, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO
LLVM ERROR: Program used external function '' which could not be resolved!
/home/vladan/.local/share/Steam/SteamApps/common/Half-Life 2/hl2.sh: line 67: 16762 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 220 "Half-Life 2 (Beta)", ProcID 16762 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

**Comment by kisak-valve** [comment]
Hello @ClanMax, are you still experiencing this issue with an up to date system?

**Comment by ClanMax** [comment]
Hi. I solved this problem 2 years ago. Everything works fine.

**Comment by kisak-valve** [comment]
Thanks, closing.
