### ISSUE TITLE
[TF2] [Linux] - Weird Dropping and Stuttering of Frames In OpenGL and DXVK

### ISSUE THREAD

**Issue by HurricanePootis** [ValveSoftware/Source-1-Games#5630]
# System Information
Arch Linux
Radeon RX 6800
AMD Ryzen 5 5600X
mesa 24.0.5
144hz Monitor with FreeSync
KDE 6.0.4 Wayland
Latest Steam Runtime
Running game with: `~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh /run/media/hurricane/superssd/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/run -- ./tf.sh -game tf`

# Problem
Whenever I first launched the game without mangohud attached to it, I could immediately tell that there was something wrong with the game. The smoothness was gone, and it was as if I was "dropping" frames, or experiencing micro stutters. I recorded videos at 144hz, sent to the my friends, and they see the issue too. This happens both on the OpenGL and DXVK renderers.

[vulkan2.webm](https://github.com/ValveSoftware/Source-1-Games/assets/53066639/63d440d7-0481-4198-95bb-665873c0dfb2)

[vulkan.webm](https://github.com/ValveSoftware/Source-1-Games/assets/53066639/f7f9464b-f53c-4cd5-940a-1488bc8902de)

[opengl.webm](https://github.com/ValveSoftware/Source-1-Games/assets/53066639/44254f08-5e09-4be4-9d2e-8ac30155654c)

**Comment by DonKatsu** [comment]
This looks like what I'm experiencing as well.
With TF2 set to fullscreen, I get that stutter with mangohud's reported FPS rapidly switching between 0 and the set FPS limit. My monitor OSD shows the refresh rate rapidly switching between 72Hz and 144Hz when Adaptive sync is enabled. Setting Adaptive sync to Never doesn't help. The first time I launched after the update had a hard freeze while on a map after about 30 seconds. Nothing about it in the journal.
With TF2 set to windowed, it runs without issue. But this is not ideal as the -noborder launch option ignores Plasma's panel causing the window to be offset. And Adaptive sync has to be set to Always to work.

CachyOS
Radeon RX 6700 XT
AMD Ryzen 9 5900X
Mesa 24.0.5
144Hz Monitor with FreeSync
KDE 6.0.4 Wayland
Steam Beta (Runtime) 1713317598
Launch options: `mangohud %command% -novid`

**Comment by polluxau** [comment]
this seems to be a xwayland problem with the game, i switched to x11 and there are no fps stutters, buttery smooth, also my mangohud didnt work properly under the game on wayland, but on x11 it works properly

rlly annoying as the majority of the linux desktop users are trying to move to wayland but we have these types of issues that appear

hopefully this gets fixed.

also running arch, plasma 6.0.4, mesa 23.0.5, kernel 6.8.7

**Comment by polluxau** [comment]
seems to be fixed with latest update, no weird fps problems on kde wayland

**Comment by HurricanePootis** [comment]
I just tested TF2 on X11 with the modesetting driver, and the stuttering was gone. This is either an Xwayland issue or a KDE issue. I have attached a video of me on X11 below.

[vulkan5_2fort_x11.webm](https://github.com/ValveSoftware/Source-1-Games/assets/53066639/3e001177-e962-4a30-adaa-395fac1391ec)

**Comment by polluxau** [comment]
interesting, i dont get these little frame spikes under kde wayland, im not using that env tho, only mangohud %command%

**Comment by DonKatsu** [comment]
@HurricanePootis Did you try downgrading kwin to 6.0.3.1? I tried kwin 6.0.4 again (arch core and cachyos-v3 to rule out the latter for me) and it's still stuttering, but 6.0.3.1 is fine.

**Comment by HurricanePootis** [comment]
> @HurricanePootis Did you try downgrading kwin to 6.0.3.1? I tried kwin 6.0.4 again (arch extra and cachyos-v3 to rule out the latter for me) and it's still stuttering, but 6.0.3.1 is fine.

Yes, I just tested it with kwin 6.0.3.1 on Arch, and the stuttering did go away with on wayland. I am going to see if I can somehow bisect which commit caused this between kwin 6.0.3.1 and kwin 6.0.4 and to see if the KDE people are aware of this issue. If not, I'll open a bug thing on whatever system KDE uses as well.

**Comment by awillinger** [comment]
Can confirm adding -windowed -noborder to the launch option both fixes the game not starting and the stutter issues.

Running with Vulkan on Manjaro.

**Comment by HurricanePootis** [comment]
I have narrowed it down to commit `9720ef2e23cf9e2747d493185163f0dfeb36de3e backends/drm: signal dmabuf feedback if an unsupported modifier is used`, I will go build kwin from HEAD and see if it is still broken. If it is, I will open up a issue on their gitlab for kwin.

**Comment by HurricanePootis** [comment]
Actually, I just thought of something. Did something TF2 change cause this problem? Or, did something kwin changed that caused this problem. I haven't played tf2 recently, so I never ran the old game on kde 6.0.4

**Comment by DonKatsu** [comment]
I think it's just bad timing on kwin 6.0.4 releasing around the same time as the TF2 update. As I get the same issues outside of TF2 with kwin 6.0.4.
Looks like it's already [getting addressed](https://invent.kde.org/plasma/kwin/-/merge_requests/5626)?

**Comment by Soup-64** [comment]
> I think it's just bad timing on kwin 6.0.4 releasing around the same time as the TF2 update. As I get the same issues outside of TF2 with kwin 6.0.4. Looks like it's already [getting addressed](https://invent.kde.org/plasma/kwin/-/merge_requests/5626)?

for arch users at least the fix mentioned here has been cherrypicked and the kwin package has been rebuilt [(see here)](https://gitlab.archlinux.org/archlinux/packaging/packages/kwin/-/commit/7ee442803be3a0a3f405e03a714a024a8460005f)!

**Comment by HurricanePootis** [comment]
On ArchLinux, the following [patch](https://invent.kde.org/plasma/kwin/-/commit/fbd78018.patch) has been added to its version of kwin, and it has solve my issue. Therefore, I am closing this issue.

However, if anyone here is on a distro that isn't shipping the patch now, as kde 6.0.5 is a few weeks away (to my understanding), downgrade to kde 6.0.3.1 in the meantime.

**Comment by Zamundaaa** [comment]
> However, if anyone here is on a distro that isn't shipping the patch now, as kde 6.0.5 is a few weeks away (to my understanding), downgrade to kde 6.0.3.1 in the meantime.

FTR we've released KWin 6.0.4.1 to fix this, distros should update to it soon enough
