### ISSUE TITLE
[TF2] 64 bit version not connecting to servers

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#5638]
The game opens fine on the 64 bit version, but trying to connect to a server gives me 

> You are in an insecure mode. You must restart before you can connect to secure servers.

Are they talking about restarting the game or restarting my computer? Because the former of which hasn't worked.

**Comment by MeatwadMeatwad** [comment]
so disable insecure in launch options by removing the line in launch option.

**Comment by ShadowMan44** [comment]
> so disable insecure in launch options by removing the line in launch option.

_What_ launch options? The game automatically launches when I click on it, there isn't a special launcher box that you see in older games.

**Comment by gabrielwoj** [comment]
Right-Click "Team Fortress 2" on Steam, go to "Properties...", and remove "-insecure" on your Launch Options.

**Comment by ShadowMan44** [comment]
Apparently "-insecure" was never in the launch options, it's always been blank
![image_2024-04-18_180414879](https://github.com/ValveSoftware/Source-1-Games/assets/42453370/e4655434-31da-4809-838f-5da8080f2949)

**Comment by Nocrex** [comment]
I also had this issue but it went away after I verified my game files
Not too sure it's gone for good tho

**Comment by ShadowMan44** [comment]
Nope, didn't work either.

**Comment by AwesomeCoder412412** [comment]
You're not launching the game from proton, right?

**Comment by ShadowMan44** [comment]
Proton? I'm launching it in Windows 10.

**Comment by dandongus** [comment]
Verify game files (in case the binaries have become corrupted), remove any addon dlls (P-REC, HLAE, mm/sm, etc) found in the addons folder of any search path, and make sure to launch with the -steam flag (if you launch normally through Steam, this is added automatically and you don't need to manually add it).

**Comment by ShadowMan44** [comment]
Okay I forgot this was still open so I might as well close it now.

The reason why I was having this issue was because I wasn't launching it directly from the desktop shortcut, I was launching it from the uh steam folder which has both the x64 and the legacy x32 and both of them would not let me connect to servers. I hope this helps with anyone else's issue.

**Comment by Titanic-is-number-one** [comment]
it is still happening for me

**Comment by Titanic-is-number-one** [comment]
plz help
