### ISSUE TITLE
[L4D2][Linux] Latest update crashes a lot

### ISSUE THREAD

**Issue by OliverSwift** [ValveSoftware/Source-1-Games#564]
So far I had only one crash but this morning update just crashes quite often, I'm unable to complete a level (Single Player mode), whatever level I chose.

Apparently all crash dumps have been uploaded.

Config here:
https://gist.github.com/OliverSwift/4426711

**Comment by kisak-valve** [comment]
If anyone is still experiencing this issue on an up to date system, please open a new issue report.
