### ISSUE TITLE
[SDK / TF2] hlmv.exe no longer works

### ISSUE THREAD

**Issue by gabrielwoj** [ValveSoftware/Source-1-Games#5643]
With today's 64bits update ([https://store.steampowered.com/oldnews/220436](https://store.steampowered.com/oldnews/220436)), Half-Life Model Viewer (also known as HLMV), has stopped working.

Attempting to opening it do nothing. If checking the Task Manager, it does launch, then it closes after a few seconds.

HLMV is used for a lot of things on the TF2 community. Item creators use to show proper loadout screenshots as how it would look in-game (as it has proper shaders and everything), alongside painted variants on their submitted items.

On the Official TF2 Wiki, image creators use HLMV to create all sorts of imagery, ranging from painted variants, to cosmetic previews, and so on.

Thanks.

**Comment by caw-caw-robinjay** [comment]
Can confirm this issue on my machine as well. Does anyone know a way to at least revert the update so I can use HLMV while we wait for a fix?

**Comment by caw-caw-robinjay** [comment]
Another update on a solutions:
If you need HLMV, HLMV++ has already pushed out an update that works with TF2 64x. This is a permanent solution to this, unless you specifically need the base version of HLMV.
If you're looking to use TFMV, things get trickier. You'll need to download manifest 3545034868290892873 of TF2 (I did it through DepotDownloader), make a copy of your bin, hl2, and tf folders, and then copy all the files from the manifest over the bin, hl2, and tf folders. This does restore TFMV to near full functionality, but as far as I'm aware this solution won't allow you to view any items added after the 64x update. So, we do still need a solution to this, but we can at least manage until the next cosmetic case is added.

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Added missing 64-bit versions of HLMV and HLFaceposer 

This needs to be retested.

**Comment by JoriKos** [comment]
Can confirm HLMV works again after last update

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
