### ISSUE TITLE
I can't open the game with dx81

### ISSUE THREAD

**Issue by gustindiaz01** [ValveSoftware/Source-1-Games#5646]
Before the update, I used -dxlevel 81 in my launch options, after that, my game no longer opens with the command. I decided to create a shortcut from the .exe that the game has, but neither of them opened either. I used -game tf and tested with the commands bellow:

-game tf -dxlevel 81 -w 1280 -h 600 -full -noborder -high -novid -console -nohltv -precachefontchars -noquicktime

however, neither tf.exe nor tf_win64.exe opened with the commands, except when I removed -dxlevel 81 from the target. The problem is that I can't play without -dxlevel 81, as it causes my game to have blurry textures, and my PC isn't the best for playing on a dxlevel other than 81. Anyway, I kindly ask you to tell me what to do, because I have no idea myself :/ 

ps: my game don't open from steam

**Comment by kisak-valve** [comment]
Hello @gustindiaz01, this issue is already being tracked at #5631. Closing as a duplicate.

**Comment by gustindiaz01** [comment]
> Hello @gustindiaz01, this issue is already being tracked at #5631. Closing as a duplicate.

**Comment by gustindiaz01** [comment]
hello @kisak-valve, i read the #5641, and i can tell you that the problem isn't the same, as much as both are about dx81, they are not the same problem. so please, let my issue open and give me a chance to get a solution for the same.
