### ISSUE TITLE
Disk Error on Steam Can't Update TF2

### ISSUE THREAD

**Issue by gnome4040** [ValveSoftware/Source-1-Games#5651]
I'm having problems with the steam disk error and I can't update it please help me how this problem is solved I don't know if it's because of the 64 bits before I was doing fine now it doesn't allow me to update it

**Comment by AwesomeCoder412412** [comment]
Your antivirus is causing this, disable it entirely and restart steam and try again.

**Comment by Titanic-is-number-one** [comment]
ok thank you so much i will try

**Comment by xFacJoe** [comment]
> Su antivirus está causando esto, desactívelo por completo, reinicie Steam e intente nuevamente.

how to disable the antivirus?

**Comment by xFacJoe** [comment]
> Your antivirus is causing this, disable it entirely and restart steam and try again.

how to disable the antivirus?

**Comment by xFacJoe** [comment]
> Your antivirus is causing this, disable it entirely and restart steam and try again.

Thank you very much, it worked for me. :D

**Comment by AwesomeCoder412412** [comment]
> > Your antivirus is causing this, disable it entirely and restart steam and try again.
> 
> 
> 
> Thank you very much, it worked for me. :D

No problem! Glad I could help. You might want to close this issue now that it's fixed.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where the game would be falsely detected as malware by some anti-viruses" in the [2024-04-18](https://www.teamfortress.com/post.php?id=220446) Team Fortress 2 update.
