### ISSUE TITLE
After the 64 bits update the game crashes joining to servers (Windows 8.1 - 64 bits)

### ISSUE THREAD

**Issue by GlitchyShock** [ValveSoftware/Source-1-Games#5662]
Its that, i was playing minutes before the update and i could play perfectly then i close the game and open it again to update and after that i cannot play on any server, casual, comunity or mad by myself it crashes trying connect.

**Comment by ebonavt** [comment]
Update to Windows 10  ¯\_(ツ)_/¯

**Comment by ArtKitCat** [comment]
Steam no longer supports Windows 8.1 as of January 1 2024. Just upgrade your PC.

**Comment by Jeffonehundred** [comment]
Wow, @ArtKitCat @ebonavt is GitHub filled with unhelpful people like yourselves? Im now around here, I cam surprised people don't help others here, and only insult them with passive aggressive speech.

**Comment by Jeffonehundred** [comment]
@GlitchyShock I am on windows 7, and I am having the exact same issue. I was using the 64 bit build earlier and it was working just fine. But now this this update, I can not longer join game. I am going to make my own thread talking about this issues. Also, can you opens the options menu at the main screen? I have heard that some people can't do that with the same issues, such as myself.

**Comment by metapea** [comment]
No. Why should i update for a 2006 windows xp game.

**Comment by IgLocoXD** [comment]
Bro if your PC runs Windows 8.1 you could easily update to a custom Windows 10 ISO, isn't that hard, even 1gb ram PCs can run custom Windows 10

**Comment by wgetJane** [comment]
try the OpenGL version, it lets you choose on startup

**Comment by Lysithea-ciel** [comment]
> try the OpenGL version, it lets you choose on startup

Adding -r_emulate_gl to the launch options seems to have no effect

**Comment by Buggy123** [comment]
Agreed, and furthermore, it appears that people on _supported_ Windows versions are also getting this issue. So people are jumping the gun, and dismissing a legitimate issue because the user reporting it happens to be on a perfectly modern, if "unsupported", operating system which is newer than the very game that is being run on it.

**Comment by Jeffonehundred** [comment]
@goodusername123 Yes, these people are crazy when it comes to windows 10. They have nothing better to say then just "downgrade". No idea why this would be happening. I thought it might be something with VAC. Tired joining a Non VAC server, and I still crash.

**Comment by amykatname** [comment]
This unfortunately doesn't work

**Comment by amykatname** [comment]
> Something that might function as workaround is going to the install folder and running the 32-bit version of the game "tf.exe" with -steam as a launch parameter (I'm not in a position to test this myself sadly).
Can confirm this works like a charm

**Comment by Jeffonehundred** [comment]
@Tiagoquix The "-vulkan" does not work at all. The game does not even start. I have tired.

**Comment by Jeffonehundred** [comment]
> It seems your card does not support Vulkan then.
It does, its a 1070. I have tested this with other games that use Vulkan.
Does anyone who uses windows 7 have any luck with the "-vulkan" start command?

**Comment by Jeffonehundred** [comment]
> Maybe it's a software issue. I do not know if Windows 7 has the required libraries for proper Vulkan support.

Yes, you are right, as @ChampionCynthia mentioned, windows 7 gpu drivers do not support the Vulkan 2.0. As the Tf2 Vulkan is just dxvk, an emulator using direct x. 

Here is the reply "https://github.com/ValveSoftware/Source-1-Games/issues/5782#issuecomment-2067344038"

**Comment by metapea** [comment]
> Referen

You can update vulkan runtime as long you have a supported GPU for Version 1.3 here:
https://vulkan.lunarg.com/sdk/home
and look up info here:
https://vulkan.gpuinfo.org/
but it does nothing.

**Comment by ChampionCynthia** [comment]
> > > Maybe it's a software issue. I do not know if Windows 7 has the required libraries for proper Vulkan support.
> > 
> > 
> > Yes, you are right, as @ChampionCynthia mentioned, windows 7 gpu drivers do not support the Vulkan 1.3. As the Tf2 Vulkan is just dxvk, an emulator using direct x.
> > Here is the reply "[#5782 (comment)](https://github.com/ValveSoftware/Source-1-Games/issues/5782#issuecomment-2067344038)"
> 
> You can update vulkan runtime as long you have a supported GPU for Version 1.3 here: https://vulkan.lunarg.com/sdk/home and look up info here: https://vulkan.gpuinfo.org/ If it's runs version 1.3 on windows 10 then it can run on windows 7 to 8.1, you just need to install vulkan 1.3 runtime, but it does nothing for joining servers on/doesn't fix tf2.

The card supporting Vulkan 1.3 on Windows 10 doesn't mean it supports it on Windows 7 and 8.1. This is tied to the graphics driver. Although Vulkan 1.3 support was technically added around version 473 of the drivers for Windows 10/11 and that Windows 7 has 474 drivers for many NVIDIA cards, Vulkan 1.3 support is not available with it.

**Comment by metapea** [comment]
Reposting:
>Vulkan support on a given system is tied to the graphics driver, not VulkanRT.

That's ashamed, it would've been a good work around. Maybe some else can make a redirect for VulkanRT and see if that works because Vulkan 1.3 can be installed.

**Comment by Jeffonehundred** [comment]
@metapea I personally would rather a native vulken executable.

**Comment by metapea** [comment]
> @metapea I personally would rather a native vulken executable.
"Then a redirect?"
In that case then that's understandably.
I'm sure VulkanRT is native vulken but can't be used for tf2 as of now.

**Comment by Jeffonehundred** [comment]
Thank you for your help to the Vulken installer above, ill download this and see if I can get Tf2 to work with it.

**Comment by Jeffonehundred** [comment]
Update, installing the New 1.3 vulken update did let the "-vulken" startup command work, but it still has the same bugs as the "tf_win64.exe" causes on its own. As in, I crash every time I open the options menu, and when I join a server.

**Comment by metapea** [comment]
> Update, installing the New 1.3 vulken update did let the "-vulken" startup command work

Cool

> but it still has the same bugs as the "tf_win64.exe" causes on its own. As in, I crash every time I open the options menu, and when I join a server.
Same bug on dx9 like with the rest of pre-windows 10 user.
So it's something

**Comment by ChampionCynthia** [comment]
> Update, installing the New 1.3 vulken update did let the "-vulken" startup command work, but it still has the same bugs as the "tf_win64.exe" causes on its own. As in, I crash every time I open the options menu, and when I join a server.

If you used `-vulken` instead of `-vulkan`, it will still boot using DirectX 9.

**Comment by NULLYUKI** [comment]
According to patch [220641](https://www.teamfortress.com/post.php?id=220641)
`Fixed a crash when opening options/going into game (mostly affecting Windows 7 users)`

This issue requires retesting.

**Comment by Jeffonehundred** [comment]
I am on windows 7, the issue seems to be have resolved. But as the thread mentions, this person is on windows 8.1.

**Comment by ethanholt1** [comment]
> I am on windows 7, the issue seems to be have resolved. But as the thread mentions, this person is on windows 8.1.

As of Jan 1st, 2024, Steam no longer supports anything below Win 10. I don't know if this disqualifies this issue from being fixed on the older Windows versions, but I wouldn't count on it.

**Comment by GlitchyShock** [comment]
The problem got solved with the update thx to everyone who trying helping (:
