### ISSUE TITLE
[TF2] Mouse sensitivity is lower than normal

### ISSUE THREAD

**Issue by ramzialhaddad** [ValveSoftware/Source-1-Games#5666]
After the new update I felt my mouse sensitivity was noticeably lower. I checked the in-game settings and it was set to my regular 1.7 (I played earlier in the day too so nothing changed). However, "Raw Input" is missing in the Linux version - though checking with the console and command it was enabled.

I booted into Windows and felt the same lower sensitivity, and the "Raw Input" setting was present.

On Linux I tried both the Vulkan and Legacy OpenGL launch options (Vulkan doesn't work but I followed [this](https://github.com/ValveSoftware/Source-1-Games/issues/5611#issuecomment-2065521343) to get the vulkan running even if I couldn't join casual and the lower sensitivity was still present.) and both have the same lower sensitivity.

If you need anymore information I'd be happy to share.

**Comment by Joshua-Ashton** [comment]
m_rawinput is enabled by default, and on Linux, the option is hidden from the UI on purpose as not enabling it totally breaks on Wayland/XWayland as it tries to do cursor warping. m_rawinput is also just better.

There is a second part to this, and that SDL got upgraded which fixed the fact that sensitivity was being double/half of what it should be before.

**Comment by ramzialhaddad** [comment]
> m_rawinput is enabled by default, and on Linux, the option is hidden from the UI on purpose as not enabling it totally breaks on Wayland/XWayland as it tries to do cursor warping. m_rawinput is also just better.
> 
> There is a second part to this, and that SDL got upgraded which fixed the fact that sensitivity was being double/half of what it should be before.

Cheers for the explanations, I tried doubling my in-game sens and it felt more closer to what it was before. I still cannot tell if its teeny bit faster or slower due to placebo but playing normally it feels like what I am used to.

Thanks for the help and explanation!

**Comment by Joshua-Ashton** [comment]
It is

**Comment by Joshua-Ashton** [comment]
You can change it on startup if you care enough, but it always gets reset back to 1 on startup.
