### ISSUE TITLE
[TF2] Custom intros do not play audio after 64-bit update

### ISSUE THREAD

**Issue by As0mn** [ValveSoftware/Source-1-Games#5668]
After the 64-bit update, TF2 now uses .webm files to play videos. The Valve intro is located in Team Fortress 2/hl2/media/valve.webm

When trying to add a custom intro by using a different .webm file however, the audio does not play back. Here is an example (normally it is meant to play audio):

https://github.com/ValveSoftware/Source-1-Games/assets/109611240/093cbb62-b4ee-4ea1-8d80-6023fb7c1911

**Comment by Joshua-Ashton** [comment]
You should ensure the audio codec of your webm matches what we ship, otherwise it won't work.

**Comment by wgetJane** [comment]
can you send the webm file? afaik, if it uses vorbis then it should work

**Comment by megakarlach** [comment]
At the moment, WebM in TF2 only support Vorbis audio, not Opus.
https://developer.valvesoftware.com/wiki/WebM

**Comment by As0mn** [comment]
> At the moment, WebM in TF2 only support Vorbis audio, not Opus. https://developer.valvesoftware.com/wiki/WebM

This was the problem, thank you!
