### ISSUE TITLE
TF2 on Mac uses old executive...which doesn't exist anymore.

### ISSUE THREAD

**Issue by Hiiepicsohipeeps2** [ValveSoftware/Source-1-Games#5669]
![Screenshot 2024-04-18 at 9 33 29 PM](https://github.com/ValveSoftware/Source-1-Games/assets/167492844/216fa86e-e1c8-44b7-8d2d-38b66563244a)
Yeah...'nuff said.

**Comment by Hiiepicsohipeeps2** [comment]
A

**Comment by ethanholt1** [comment]
More of #5625

**Comment by kisak-valve** [comment]
Hello @Hiiepicsohipeeps2, as @ethanholt1 noted, this issue is already being tracked at #5625. Closing as a duplicate.
