### ISSUE TITLE
Team Fortress 2 not running on steam deck/linux 

### ISSUE THREAD

**Issue by Glubbulusmcgee** [ValveSoftware/Source-1-Games#5670]
I try running the normal tf2 game after uodsting and it just crashes even after restartingthe system, any tips? Cause all i did was click Launch tf2, was i supposed to launch Legacy Open GL?

**Comment by Joshua-Ashton** [comment]
You may need to restart Steam to get the update for it to switch to the right runtime.

**Comment by Glubbulusmcgee** [comment]
> You may need to restart Steam to get the update for it to switch to the right runtime.

I tried turning off the deck along for 20 mins and still no response

**Comment by Glubbulusmcgee** [comment]
Uploading 20240418_200347.mp4…

**Comment by Glubbulusmcgee** [comment]
https://github.com/ValveSoftware/Source-1-Games/assets/167493355/be7a644f-cb0e-4ffe-a5fa-f2ea4842c538

**Comment by antrmn** [comment]
As pointed in an earlier issue ( https://github.com/ValveSoftware/Source-1-Games/issues/5617 ) it may be a matter of wrong Steam runtime used. 

I'm using Nobara Linux and this is what I get in the terminal when attempting to run TF2:

```
/bin/sh\0-c\0LD_PRELOAD=/lib/libtcmalloc_minimal.so.4 /home/antonio/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/antonio/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/antonio/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/antonio/.local/share/Steam/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/antonio/.local/share/Steam/steamapps/common/Team Fortress 2/tf.sh' -steam\0
chdir "/home/antonio/.local/share/Steam/steamapps/common/Team Fortress 2"
ERROR: ld.so: object '/usr/lib/steam/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/antonio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/steam/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/steam/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/run/host/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/run/host/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
ERROR: ld.so: object '/run/host/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/run/host/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
ERROR: ld.so: object '/run/host/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/run/host/lib/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

FATAL: It appears tf was not launched within the Steam for Linux sniper runtime environment.
FATAL: Please consult documentation to ensure correct configuration, aborting.
```
Given this substring on the first line: `/home/antonio/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/antonio/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/antonio/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/antonio/.local/share/Steam/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/antonio/.local/share/Steam/steamapps/common/Team Fortress 2/tf.sh' -steam` it can be seen that it tries to use the soldier runtime instead of the sniper runtime, so I just opened a terminal and executed this line:

```
 `/home/antonio/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/antonio/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/antonio/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/antonio/.local/share/Steam/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/antonio/.local/share/Steam/steamapps/common/Team Fortress 2/tf.sh'
```

And the game launched.

**Comment by Glubbulusmcgee** [comment]
> As pointed in an earlier issue ( #5617 ) it may be a matter of wrong Steam runtime used.
There a way i can change the steam runtime soldier to sniper without having to do stuff with code? I dont really understand anything about codes and scripts and stuff like that, i dont understand the sacred tech language lol

**Comment by Glubbulusmcgee** [comment]
I dont know how to do that i cant open terminals on the deck for some reason, i try forcing the tool to work on a different runtime but it only shows the scout one, i cant find sniper and i dont understand anything about codes and terminals and files and stuff :<

**Comment by kisak-valve** [comment]
Hello @Glubbulusmcgee, this issue is already being tracked at #5621. Closing as a duplicate.

As a side note, putting the Steam Deck to sleep and restarting Steam aren't functionally the same thing. You can restart Steam from the power menu by going into Desktop mode and back to Game mode, or telling the Steam Deck to restart from the same power menu. If that helps, feel free to add a note to the older issue report.

**Comment by Glubbulusmcgee** [comment]
> Hello @Glubbulusmcgee, this issue is already being tracked at #5621. Closing as a duplicate.
> 
> As a side note, putting the Steam Deck to sleep and restarting Steam aren't functionally the same thing. You can restart Steam from the power menu by going into Desktop mode and back to Game mode, or telling the Steam Deck to restart from the same power menu. If that helps, feel free to add a note to the older issue report.

There a way i can switch the steam run times in an easier way somehow?
