### ISSUE TITLE
[TF2] [Linux] literally unplayable on steam deck

### ISSUE THREAD

**Issue by sapphicgoddessorwhatever** [ValveSoftware/Source-1-Games#5671]
the game wont launch. I heard someone say that yall forgot to switch compatibility mode to sniper (tf2 is on scout)

this is genuinely upsetting, its broken on all of linux.

**Comment by ethanholt1** [comment]
I was able to run the game fine after the update
I had to restart for it to work however

**Comment by Joshua-Ashton** [comment]
You may need to restart Steam to get the update for it to switch to the right runtime.

**Comment by sapphicgoddessorwhatever** [comment]
restarted twice. nothing. tf2 still wont launch. still broken on steam deck/linux

**Comment by kisak-valve** [comment]
Hello @sapphicgoddessorwhatever, this issue is already being tracked at #5621.

Closing as a duplicate.
