### ISSUE TITLE
[TF2 64-bit] VPKs include a poorly formatted file

### ISSUE THREAD

**Issue by StShAzzy** [ValveSoftware/Source-1-Games#5672]
*** Invalid sample rate (0) for sound 'vo\null.mp3'.

**Comment by groovyvs** [comment]
u could fix this by just making an mp3 that has no audio and putting it in tf/custom/<your folder for hitsounds>/sound/vo/<your file here> and make sure the sample-rate is 44100.

only do this if that file is causing crashes or some other problem

**Comment by StShAzzy** [comment]
it's still a game bug... like the several missing particles and some audios missing

**Comment by StShAzzy** [comment]
+ i like it better that i don't have to do something myself

**Comment by StShAzzy** [comment]
[vo.zip](https://github.com/ValveSoftware/Source-1-Games/files/15032370/vo.zip)
for whoever needs it

**Comment by naydef** [comment]
Related (and possibly duplicate): https://github.com/ValveSoftware/Source-1-Games/issues/5502

**Comment by StShAzzy** [comment]
duplicate of #5502
