### ISSUE TITLE
cant update the game

### ISSUE THREAD

**Issue by octohunter69** [ValveSoftware/Source-1-Games#5676]
when I tryed to update the game my anti vires said it had malware and now I cant update the game it just keeps saying disk write error 
![image_2024-04-18_223454846](https://github.com/ValveSoftware/Source-1-Games/assets/167494440/515e1058-79ef-46ce-a8db-cf04d4218970)

**Comment by AwesomeCoder412412** [comment]
Completely turn off your antivirus, restart your computer, and try again. It's a false positive and has been reported.

**Comment by kisak-valve** [comment]
Hello @octohunter69, this issue is already being tracked at #5620. Closing as a duplicate.
