### ISSUE TITLE
Tf2 Does not open on steam deck

### ISSUE THREAD

**Issue by XrazeX** [ValveSoftware/Source-1-Games#5679]
I've had a problem lately and it's that team fortress doesn't work on steam deck, it doesn't open and it just crashes. I had to use proton to be able to play normally and not crash or something like that, but at the same time having fps drops And I can't play multiplayer thanks to that. I forgot to mention that "start Legacy OpenGL" appears when I try to open the game, after that it doesn't open. Thank you for reading

**Comment by kisak-valve** [comment]
Hello @XrazeX, this issue is already being tracked at #5621. Closing as a duplicate.
