### ISSUE TITLE
[TF2] [Windows] [64-bit] Constant stuttering in menus and in-game

### ISSUE THREAD

**Issue by mstilw577** [ValveSoftware/Source-1-Games#5681]
The game is constantly stuttering in the menus and in-game. I have everything on the highest settings on DirectX 9. It does not give me a choice to use Vulkan. The game did not stutter when it was running on 32-bit. My PC specs are - CPU: Ryzen 5 4500 - GPU: Radeon RX 6600 - RAM: 16 GB @ 3200 MHz

**Comment by KaelaSavia** [comment]
Same here. RTX 4090, i9-13900k. Microstutters no matter what I do settings or frame lock wise.

This is unacceptable

**Comment by Ashetf2** [comment]
The stuttering should be the same as before the update. It is just more noticeable because now the sound doesn't crash for a few seconds, but instead it's muted

**Comment by treacherousfiend** [comment]
as a side note, there is no option on startup to launch with vulkan currently, you have to add `-vulkan` to your launch options

**Comment by mstilw577** [comment]
The latest update seems to have resolved the issue for me. It is no longer stuttering.
