### ISSUE TITLE
Cant update the game because Avast thinks the shader files are viruses

### ISSUE THREAD

**Issue by 11deadpoets** [ValveSoftware/Source-1-Games#5688]
yeah, just as the title says, my antivirus thinks that the shader files were trojan virus and now i cant play the game. is there any workaround for this?

![Capture](https://github.com/ValveSoftware/Source-1-Games/assets/167498661/9f9f7a8b-b614-4dda-8867-ba6cf333fd41)

**Comment by wgetJane** [comment]
try uninstalling avast

**Comment by treacherousfiend** [comment]
New update just released which supposedly fixes this issue.

**Comment by kisak-valve** [comment]
Hello @11deadpoets, this issue is already being tracked at #5620. Closing as a duplicate.
