### ISSUE TITLE
Can´t search for other matches

### ISSUE THREAD

**Issue by Momardoz** [ValveSoftware/Source-1-Games#5693]
Every time i press on the ¨START SEARCH¨ button, it cancels automaticaly 

video proof:

https://github.com/ValveSoftware/Source-1-Games/assets/167499853/727da3d3-2ff2-44cd-9038-568a47e1138c

**Comment by Stabbyson** [comment]
A patch happened shortly after the update, restart and update your game to fix it

**Comment by kisak-valve** [comment]
Closing pending feedback.
