### ISSUE TITLE
[TF2] [Windows] [x64] Tools mode doesn't work after the update

### ISSUE THREAD

**Issue by lowcrafty** [ValveSoftware/Source-1-Games#5698]
Can't access particle editor no more :(

**Comment by treacherousfiend** [comment]
it works on the x32 client, if you create a bat file in your TF2 folder with `tf.exe -tools` then you should be able to run it through that

**Comment by p0sixpwnn** [comment]
this method is broken, now the only way you can access particle editor that actually properly works is by creating a txt file and putting tf.exe -tools in it the saving it as a BAT file

**Comment by p0sixpwnn** [comment]
and have it in your tf2 folder

**Comment by treacherousfiend** [comment]
this issue has already been closed, and I already gave that solution anyway...

**Comment by p0sixpwnn** [comment]
<img width="207" alt="Снимок экрана 2023-12-30 020539" src="https://github.com/ValveSoftware/Source-1-Games/assets/108231456/c22eb216-f6b2-4174-9515-32fbc12a6c52">
