### ISSUE TITLE
[TF2] There is a glitch with a hat in game with unusual effect Hellspawned Horns on Head Hedge. It is on this hat that the effect is displayed not as it should, but backwards.

### ISSUE THREAD

**Issue by RedheadPumpkin** [ValveSoftware/Source-1-Games#5702]
![image (1)](https://github.com/ValveSoftware/Source-1-Games/assets/167506639/d8df027e-d5a0-4374-9c81-0070d72a81e4)

**Comment by ArtKitCat** [comment]
This is a common glitch on certain hats. Its unknown why this happens. [Here's a Guide explaining it.](https://steamcommunity.com/sharedfiles/filedetails/?id=2887940583)

**Comment by kisak-valve** [comment]
Hello @RedheadPumpkin, this issue is already being tracked at #4390.

Closing as a duplicate.
