### ISSUE TITLE
Objector option

### ISSUE THREAD

**Issue by zzDeathGodzz** [ValveSoftware/Source-1-Games#5716]
Could we have a setting to disable/enable seeing custom conscientious objector signs?

I don't want to be forced seeing non-TOS content on signs, especially as a streamer.

**Comment by JoriKos** [comment]
Duplicate of #4249

**Comment by gdfsgdfg** [comment]
Yes please, we really need an option to hide decals.

**Comment by kisak-valve** [comment]
Hello @zzDeathGodzz, as @JoriKos noted, this issue is already being tracked at #4249.

Closing as a duplicate.
