### ISSUE TITLE
TF2 64-bit effecting other games?

### ISSUE THREAD

**Issue by ToastGhoster** [ValveSoftware/Source-1-Games#5727]
So i updated TF2 so it uses the new update and then garrys mod started dying everytime i do something slightly advanced im not saying that its TF2 but its very convineint that it happened at the same time i did the update

**Comment by Partydonut214** [comment]
Try Unmounting TF2 from your Game List on the Gmod Home Screen and see if that does anything!

**Comment by kisak-valve** [comment]
Hello @ToastGhoster, issues with Garry's Mod need to be evaluated by that game's developer(s).
