### ISSUE TITLE
tf2 has crashes when i click in options

### ISSUE THREAD

**Issue by Felixir32** [ValveSoftware/Source-1-Games#5728]
After updating the game to 64 bits I wanted to see the settings to make some changes but when I did so it crashed and closed automatically

**Comment by kisak-valve** [comment]
Hello @Felixir32, per "Fixed a crash when opening options/going into game (mostly affecting Windows 7 users)" in the [2024-04-22](https://www.teamfortress.com/post.php?id=220641) Team Fortress 2 update, please retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed.
