### ISSUE TITLE
[Half-Life 2 Linux] Several graphical issues

### ISSUE THREAD

**Issue by pfannkuchengesicht** [ValveSoftware/Source-1-Games#573]
Hello there I have some issues to report for Half-Life 2(Beta) for Linux.
first off my System:

> HW<
> AMD Phenom II X4 955(3.2GHz)
> 2x 4GB DDR3-1333(7-7-7-20) G.Skill RAM
> MSI 790FX-GD70
> ASUS EAH5870(AMD HD5870, 1GB VRAM)
> ASUS Xonar DX
> 
> SW<
> Arch linux(3.8.10-1)
> Xfce DE
> Catalyst 13.4
> Xorg 1.13(thanks AMD!)
> xrandr 1.4

Sometimes I'm getting texture corruptions when objects are close to the screens edge, it happens rarely, hard to reproduce.

Particle color issues is now bug #646

Also some normal maps seem to cause a moire effect, I don't think that was the case on Windows:
![02](http://cloud-2.steampowered.com/ugc/559848462363559442/14E4FDEE90431EDC486BA50681DE14C9CD8E3D5D/)

There are also issues with alpha mapped materials:
![03](http://cloud-2.steampowered.com/ugc/559848462376648601/FE37808FD7A3A04181405D8E05046A6CBDFC2BEE/)
![04](http://cloud.steampowered.com/ugc/559848462376667010/50D0E9409A835CB2F1F72312576A6B0A8375B073/)
![05](http://cloud-2.steampowered.com/ugc/559848462376660132/0B2C3EA2EC7436D6F5CC0456E7A1FE8FAE3FAB16/)
![06](http://cloud-2.steampowered.com/ugc/559848462376763278/ED0C62C9AA07F82042DE755B657E5A176E040C1A/)
![07](http://cloud-2.steampowered.com/ugc/559848462376777248/FE91B6E00589F5C4FEBFB98E4F36F57EFBFA3D77/)
it flickers between buggy and normal when you're close enough.

Also the motorboats flashlight shadow is corrupted:
![10](http://cloud-2.steampowered.com/ugc/559848462376674964/C2631490A5933708244AD07088D7EF622850CC3A/)
![11](http://cloud-2.steampowered.com/ugc/559848462376680747/2D053E150F2744150B586E651501D7E2D52ADD23/)
![12](http://cloud-2.steampowered.com/ugc/559848462376695677/FE99ED4BC5EC7DD598130B5C92C2B9F96D0E8206/)

the refractions also have color banding:
![14](http://cloud-2.steampowered.com/ugc/559848462376720506/7ED9A101F695511EC4AF8731304C76D54F38D6B1/)
![15](http://cloud-2.steampowered.com/ugc/559848462376715082/B1E21334CAA3BDA2D0D167806147E9E034162827/)

I also periodically experience some strange slow-down speed-up effect, it basically feels like lag.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If anyone is still experiencing these issues with an up to date system, please open a new issue report.
