### ISSUE TITLE
[TF2] sounds not working after 64bit update (windows 10)

### ISSUE THREAD

**Issue by sauli01** [ValveSoftware/Source-1-Games#5730]
after playing for a while (3-4 games) console gets spammed with "total_channels == MAX_CHANNELS" and most of the audio doesn't play in game.

**Comment by KEDI103** [comment]
It locked to 2 speakers even you change it won't also when you reopen game back to 2 speakers...
![resim](https://github.com/ValveSoftware/Source-1-Games/assets/52115509/abf8a815-f93c-423a-88a6-c47a15148104)

**Comment by sauli01** [comment]
also more info about that. 

the sounds that disappear are not the same sounds all the time. sometimes the sound plays and then like 3 seconds later when the same sound should play it does not. (reload sound being a good example of it.) 

also seems to be at around 1 hour mark when the sounds start to disappear. starts off with just few sounds not playing but around 10 minutes after noticing a sound not playing like 80+% of the sounds just don't play 

tried changing in game sound quality to high (from low that i used to have) and no change.

**Comment by sauli01** [comment]
oh yeah specific system information and launch options and such i have:

too lazy to get the files of my hit/killsounds as i doubt they really matter as it is basically all the audio that disappears instead of only hit/kill (that some of my friends have been saying that their hit/killsounds dont work). if needed can get them

tf2 hud (doubt this matters) https://wiki.teamfortress.com/wiki/User:Eniere/Improved_Default_HUD

mastercomfig medium preset ( https://mastercomfig.com/app/ ) with customizations of 
decals_models=low
sprays=on
ragdolls=medium
3dsky=on
hud_player_model=on
outlines=high
decals=medium


steam launch options:  -console -noborder +cl_spraydisable 0 -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime

from sound settings: tried with 16bit 44100 Hz and with 24bit 192000 Hz (keeping it at the 24bit one by default)

too lazy to figure what is needed, just everything from system information copy-pasted (yes like half of this could be cut out):
OS Name	Microsoft Windows 10 Pro N
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-S0QR9F5
System Manufacturer	Micro-Star International Co., Ltd.
System Model	MS-7B47
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 6 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 1.B2, 20.04.2021
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	Z370 TOMAHAWK (MS-7B47)
BaseBoard Version	1.0
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.3636"
Installed Physical Memory (RAM)	32,0 GB
Total Physical Memory	31,9 GB
Available Physical Memory	23,1 GB
Total Virtual Memory	36,7 GB
Available Virtual Memory	23,7 GB
Page File Space	4,75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

gpu: gigabyte AORUS RTX 3080 GAMING BOX (rev. 1.0) (gpu removed from the egpu enclosure and is used as a normal gpu in pcie slot.

**Comment by sauli01** [comment]
still not fixed after the latest update (didn't play for few days so couldn't test earlier). took around 25 minutes for sounds to die this time so the time window is not consistant at all

**Comment by KEDI103** [comment]
For me 2 channel locked problem gone. 
Now I can play 5+1 for hours no bug appeared on sound.
Thank you Valve for fixing it

**Comment by sauli01** [comment]
forgot to close the issue as it was fixed (atleast for me) with one of the sounds updates of august if i remember correctly.
(might have been october 24th update aswell if i am somehow misremembering it but whatever
