### ISSUE TITLE
Every time I try to join a server, it crashes and close by itself

### ISSUE THREAD

**Issue by PyrodosBandeclay** [ValveSoftware/Source-1-Games#5736]

**Comment by kisak-valve** [comment]
Hello @PyrodosBandeclay, this issue is already being tracked at #5674. Closing as a duplicate.

**Comment by PyrodosBandeclay** [comment]
the strange that this thing happened one day before the update and after the update, so i don't know is because I used a mod that broke my game, or was the update that broke my game or is something else, the first try appeared a timed out message and the second try the game crashed, when I tested the beta the game crashed too
