### ISSUE TITLE
Dolby atmos virtual surround sound not working on 64 bit

### ISSUE THREAD

**Issue by DiZzytf** [ValveSoftware/Source-1-Games#5739]
Dolby atmos is not working on a 64 version but it did on 32 bit

**Comment by KEDI103** [comment]
no game locked at 2 speakers mode at x64 you can't change it even it says change it won't and when you restart the game it still 2 speakers mode.

**Comment by kisak-valve** [comment]
Hello @DiZzytf, this issue is already being tracked at #5618.

Closing as a duplicate.
