### ISSUE TITLE
Team fortress 2 x64 locked 2 spearkers can't change to 5+1 or anything else. Sound hurting ears.

### ISSUE THREAD

**Issue by KEDI103** [ValveSoftware/Source-1-Games#5740]
When x64 update come sound system broken to 2 speakers locked mode even you change it to 5+1 it won't apply anything. And when you restart game it still back to 2 speakers.

My ears getting hurt please Valve fix it.
![resim](https://github.com/ValveSoftware/Source-1-Games/assets/52115509/aab1656d-d282-46ea-986a-b0b287426b26)

**Comment by kisak-valve** [comment]
Hello @KEDI103, this issue is already being tracked at #5618.

Closing as a duplicate.
