### ISSUE TITLE
Tf2 not working on steam deck

### ISSUE THREAD

**Issue by TheBucketWasTaken** [ValveSoftware/Source-1-Games#5744]
It won't allow me to open tf2 on my deck. Whenever I launch it, a few seconds later it will cancel launch. I have tried using proton experimental, and that works but its 10 times laggier and it won't let me join servers. Any way to solve this issue?

**Comment by kisak-valve** [comment]
Hello @TheBucketWasTaken, this issue is already being tracked at #5621.

Closing as a duplicate.
