### ISSUE TITLE
Avast users having false positives with installing update 

### ISSUE THREAD

**Issue by Section009** [ValveSoftware/Source-1-Games#5747]
Avast antivirus will register vrad.exe and ShaderCompiler as viruses and place them under quarantine.

**Comment by NULLYUKI** [comment]
Also can you upload these files to [Virustotal](https://www.virustotal.com/gui/home/upload) and send the results here. This way it is possible to check which other Anti-virus software might be false flagging these files.

**Comment by kisak-valve** [comment]
Hello @Section009, this issue is already being tracked at #5620. Closing as a duplicate.
