### ISSUE TITLE
TF2 64bit crash on Windows 7 (.dmp file provided)

### ISSUE THREAD

**Issue by uTa4u** [ValveSoftware/Source-1-Games#5751]
[crash_tf_win64.exe_20240419184510_1.dmp](https://github.com/ValveSoftware/Source-1-Games/files/15042754/crash_tf_win64.exe_20240419184510_1.dmp)

**Comment by NULLYUKI** [comment]
Related to https://github.com/ValveSoftware/Source-1-Games/issues/5743

**Comment by uTa4u** [comment]
Happens on opening options menu and on community server join

**Comment by PyrodosBandeclay** [comment]
where do i put this dmp file?

**Comment by JoriKos** [comment]
> where do i put this dmp file?

As in how to open it? Visual Studio opened it by default for me. Otherwise, this is mostly for the devs.

**Comment by NULLYUKI** [comment]
I'm not sure if [WinDbg](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/) works for Windows 7 and for this case.

**Comment by Jeffonehundred** [comment]
How can I create my own dmp file for publishing here? Could you please tell me how? I would assume suing task manager, but the game crashes and closes before you could select it to do so.

**Comment by uTa4u** [comment]
> How can I create my own dmp file for publishing here? Could you please tell me how? I would assume suing task manager, but the game crashes and closes before you could select it to do so.

I got mine from .../steam/dumps

**Comment by Jeffonehundred** [comment]
I see your dmp file in vs 2019, "The thread tried to read from or write to a virtual address for which it does not have the appropriate access.". I don't think running the exe in admin would be a easy fix. I'll try to look around and see if I can find anything about this error.

**Comment by Jeffonehundred** [comment]
No luck with this fix.

**Comment by ChampionCynthia** [comment]
The in-game chat in the Windows build of TF2 wasn't updated for emoji support. It isn't the issue.

**Comment by Peomarder** [comment]
try running -nosound

**Comment by kisak-valve** [comment]
Hello @uTa4u, this issue is being tracked at #5674 and #5728. Closing as a duplicate.
