### ISSUE TITLE
Pyro Airblast visual bug

### ISSUE THREAD

**Issue by SirSmokeAl0t** [ValveSoftware/Source-1-Games#5762]
Yes, this problem has been seen in casual/community servers and makes some people get a low fps when getting close on pyro while doing this bug

**Comment by Nocrex** [comment]
Duplicate of  #4071

**Comment by kisak-valve** [comment]
Hello @SirSmokeAl0t, there's not enough detail here to determine if this is a distinctly different issue from the issue report @Nocrex linked.

If #4071 isn't the same issue you're describing, please explain in detail how it is different.

Closing in favor of the older issue report.
