### ISSUE TITLE
[HL2] With HDR set to "none" some levels lack all lighting/shadows. Additionaly after playing such a level, previously good looking levels exhibit the same behaviour.

### ISSUE THREAD

**Issue by d00m3d** [ValveSoftware/Source-1-Games#577]
Bare with me as I explain how to reproduce this and what causes this.

The steps:

Start HL2.
Set HDR to None or Bloom (if available).

New Game -> Point Insertion. Everything looks fine.
Esc.
New Game -> A Red Letter Day. Everything looks fine.
Esc.
New Game -> Route Kanal. Everything looks fine.
Esc.
New Game -> Water Hazard. Everything looks fine.
Esc.

New Game -> Black Mesa East. Looks horrible.

![1](https://f.cloud.github.com/assets/4396120/490115/a972921c-b9b0-11e2-8d92-3e3bc61edd5a.jpg)
![2](https://f.cloud.github.com/assets/4396120/490116/aeb49dba-b9b0-11e2-9104-45f5bbd75520.jpg)

Esc.
New Game -> Try the maps that previously looked fine; Point Insertion or A Red Letter Day or Route Kanal or Water Hazard. Suddenly they look horrible too!

The issue: With HDR turned off in some levels the lighting / shadows are missing. The levels in question; the first maps of Black Mesa East, Highway 17, Sandtraps, Nova Prospekt, Entaglement. There are probably more maps, I only checked the first one of each chapter. After loading such levels, if one attempts to load one of the normal looking levels, the lighting / shadows will be missing from those as well.

The reason: I believe these levels have not been compiled with LDR. Only HDR. Currently HL2 has some levels compiled with HDR that cause this issue and others with LDR that cause issue #572

The solution: I have a solution for fixing the lighting on the levels that DID look ok, until you launched a map that has this issue. Open the console and type: mat_fullbright 0

The plea: Ideally Valve should compile both LDR and HDR versions of the maps, so that they both look great in HDR without messed up skyboxes (#572) and be playable in LDR. Alternatively remove LDR altogether?

Win7 x64, GTX 460 user.

**Comment by cruizba** [comment]
This error happens to me in January 2018 :(

**Comment by SpiffyJUNIOR** [comment]
Still present as of the latest update. Use this fix until the game is patched: 
https://gamebanana.com/maps/165807

**Comment by stevethepocket** [comment]
It can also be fixed by just playing _Half-Life: Update_ instead. Valve really dropped the ball by accepting that mod onto Steam instead of just pushing it out as an actual update to the game.

**Comment by rataje** [comment]
God really, with Filip Victor's Update version everything is fine but using normal hl2 destroys my game in d2_coast_01 completely! Ridiculous!

**Comment by GiovanH** [comment]
Experiencing the same issue.

**Comment by severthesestrings** [comment]
Ugh, I can't believe this has been a bug this long.

Anyways, here is a list of all maps in HL2 stuck at full bright with HDR off
d1_eli_01
d1_town_05
d2_coast_01
d2_coast_03
d2_coast_04
d2_coast_05
d2_coast_06
d2_coast_07
d2_coast_09
d2_coast_11
d2_prison_01
d2_prison_02
d2_prison_03
d2_prison_05
d2_prison_06
d2_prison_07

**Comment by niobium93** [comment]
@LidiCryz-Liam what DXVK beta branch? I don't see that in the betas section of the games properties?

**Comment by megakarlach** [comment]
![d1_eli_010001](https://github.com/ValveSoftware/Source-1-Games/assets/60382442/89e05d53-220b-44e2-9bfa-988b49c04171)
![d2_coast_010000](https://github.com/ValveSoftware/Source-1-Games/assets/60382442/669ea040-160c-4065-b350-16ae9b7494c7)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/60382442/6c48e451-8119-45a6-8d48-ad33bc147630)
As of 2024, this was after the Steam Deck update was released. Still not fixed. HL2 was last updated in Nov 17, 2023.

**Comment by PsychoCoffee** [comment]
Hello, sorry if I respond too late,
I was able to somehow fix this for my own system. Here's what I did:
(Build Label: 8491853, Network PatchVersion: 8491853, Protocol version: 24)

1.) Quit out of Half-Life 2
2.) Open up properties of Half-Life 2 and enter "-dxlevel 95" as the launch option
3.) Launch Half-Life 2, once it has launched close it
4.) Open up properties of Half-Life 2 and remove the "-dxlevel 95" from the launch option
5.) Launch Half-Life 2, and go to Options -> Video -> Advanced
6.) Set every option to the lowest (texture, shaders, models, shadows, hdr, detail, everything)
7.) Apply the changes in the options
8.) Quit out of options and open them again
9.) Set every option to the highest (texture, shaders, models, shadows, hdr, detail, everything)
10.) Apply the changes
11.) Open up console, write as follows:
                 1. mat_dxlevel 95 
                 2. mat_hdr_level 2
                 3. mat_fullbright 0

After doing all that, for me it disabled the visual glitch and made it possible to play the game with shadows and perfect lighting ;)

![20240727144850_1](https://github.com/user-attachments/assets/d10eca37-1d0e-4e21-bbfd-c3dbb1fc077c)

**Comment by megakarlach** [comment]
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/577#issuecomment-2254141429

This basically just enables HDR and dxlevel set to 95. Users wanting to use LDR (or None), for some reasons like having low end PC/GPU or didn't want bloom/exposure will still get fullbright lighting.

**Comment by Skazzy3** [comment]
Fixed after 11 years!

**Comment by cruizba** [comment]
Time to close the issue... Mr Freeman... It is time... to close 💼

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
