### ISSUE TITLE
[TF2] [64] Segmentation fault on startup.

### ISSUE THREAD

**Issue by TailsFanLOL** [ValveSoftware/Source-1-Games#5771]
[Here's the coredump (gz compressed).](https://github.com/ValveSoftware/Source-1-Games/files/15044747/tf2.zst.gz) And here's the log:
```text
alex@alex-Inspiron-5748:/opt/Steam/steamapps/common/Team Fortress 2$ ~/.steam/steam/ubuntu12_64/steam-runtime-sniper/run /opt/Steam/steamapps/common/Team\ Fortress\ 2/tf.sh "+exec autoexec.cfg -useallavailablecores -lv -noipx -nohltv -high -threads 4 -opengl"
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-ml.so.1 not found, ignoring: Missing dependencies: Could not find "libnvidia-ml.so.390.157" in LD_LIBRARY_PATH (unset), ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-ml.so.1 not found, ignoring: Missing dependencies: Could not find "libnvidia-ml.so.390.157" in LD_LIBRARY_PATH (unset), ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-ml.so.1 not found, ignoring: Missing dependencies: Could not find "libnvidia-ml.so.390.157" in LD_LIBRARY_PATH (unset), ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
SDL video target is 'x11'
SDL video target is 'x11'
AppFramework : Unable to load module sourcevr.so!
Using shader api: shaderapivk
info:  Game: tf_linux64
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in libvulkan.so.1 @ 0x7f3e46d27770
info:  Built-in extension providers:
info:    SDL2 WSI
info:  Enabled instance extensions:
info:    VK_EXT_surface_maintenance1
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_xlib_surface
MESA-INTEL: warning: Haswell Vulkan support is incomplete
warn:  Skipping Vulkan 1.2 adapter: Intel(R) HD Graphics 4400 (HSW GT2)
warn:  Skipping CPU adapter: llvmpipe (LLVM 15.0.7, 256 bits)
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required.
Convar sdl_displayindex has multiple different change callbacks
Using Breakpad minidump system. Version: 8830351 AppID: 440
Setting breakpad minidump AppID = 440
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/alex/.local/share/Steam/linux64/steamclient.so' OK.
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
04/19 22:06:12 minidumps folder is set to /tmp/dumps
04/19 22:06:12 Init: Installing breakpad exception handler for appid(440)/version(8830351)/tid(75377)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198812264711 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198812264711
Did not detect any valid joysticks.
crash_20240419220616_2.dmp[75402]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240419220616_2.dmp
crash_20240419220616_2.dmp[75402]: Finished uploading minidump (out-of-process): success = yes
crash_20240419220616_2.dmp[75402]: response: CrashID=bp-3db7287e-ddc5-41b3-80f5-05e872240419
crash_20240419220616_2.dmp[75402]: file ''/tmp/dumps/crash_20240419220616_2.dmp'', upload yes: ''CrashID=bp-3db7287e-ddc5-41b3-80f5-05e872240419''
/opt/Steam/steamapps/common/Team Fortress 2/tf.sh: line 83: 75377 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```
This is stupid tbh.

**Comment by TailsFanLOL** [comment]
Shouldn't we have a branch with the legacy game?

**Comment by Loomeh** [comment]
What are your hardware specs?
DXVK is trying to run on your CPU's integrated GPU but it fails because your iGPU doesn't have full Vulkan support.

Try selecting "Legacy OpenGL" when launching the game through Steam.

**Comment by kisak-valve** [comment]
Hello @TailsFanLOL, `warn:  Skipping Vulkan 1.2 adapter: Intel(R) HD Graphics 4400 (HSW GT2)` is the key detail here. The Vulkan drivers for your Haswell generation GPU lack hardware features to support Vulkan 1.3, which DXVK requires. You might be able to lie about what features your Intel GPU exposes, but crashes and/or misrendering is expected as a side effect.

Additionally `libnvidia-ml.so.390.157` tells us that you're using the NVIDIA 390 series video driver. This video driver series is expected to encounter an issue being tracked at https://github.com/ValveSoftware/steam-runtime/issues/420. It's likely your Haswell GPU is paired with a Fermi or maybe a Kepler generation NVIDIA GPU. Neither of which have drivers that support Vulkan 1.3 (Fermi never had a Vulkan driver and the last driver series to support Kepler only supported Vulkan 1.2.)

The Legacy OpenGL launch option should be equivalent to running the game with `-steam -gl`, but it's unlikely to avoid steam-runtime#420.

Sorry, but your hardware is unlikely to be supportable going forward.

**Comment by TailsFanLOL** [comment]
@kisak-valve, -gl produces this exact output (nothing changes). Before the update this exact GPU worked fine. Yes, this is a Fermi gen. But it did work, tho.

**Comment by TailsFanLOL** [comment]
Can you just get an engineer to look through the core dump or at least provide a way to get the legacy version? I would appreciate that.

**Comment by Loomeh** [comment]
> Also, the issue you referenced appears to be Proton related. Yes, Proton is (and was) broken for me, but TF2 kept running up until the 64 update.

@TailsFanLOL  Judging by your logs, It really doesn't look like TF2 is the issue here. Your iGPU is too old to support DXVK. OpenGL not running is likely caused something wrong with your OS configuration.

I think if you want to keep playing TF2 on your hardware, you should install Windows 10. Either on a separate partition or a separate drive. TF2 on Windows runs natively with DirectX 9 which your hardware supports.

**Comment by TailsFanLOL** [comment]
@Loomeh, apologies. It seems as if the stem runtime thingy that I was running the game with before is ignoring cmd arguements, and uses the default which is using vulkan. Upon closer inspection, it seems that I can get the game to run normally while producing logs by using "alacritty -T debugger -e %command% -opengl", and that reveals a 
[different core dump (gz compressed)](https://github.com/ValveSoftware/Source-1-Games/files/15047599/tf2_but_right_this_time.zst.gz). The logs now are:
```text
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 12231 != 12228, skipping destruction (fork without exec?)
*** stack smashing detected ***: terminated
```
. No mention of Vulkan here now. I tried running a different source1 game (Portal 2) this way, it works, but as soon as I replace "-opengl" with "-vulkan" it crashes on startup the same way as before. I will now edit this issue. Please reopen this.

**Comment by kisak-valve** [comment]
`*** stack smashing detected ***: terminated` is a primary indicator of https://github.com/ValveSoftware/steam-runtime/issues/420. Your issue is being tracked there.

**Comment by TailsFanLOL** [comment]
@kisak-valve, oh. Well, the stack smashing thing appears to be coming from tf2 and not from an nvidia related lib/bin, so just maybe ¯\_(ツ)_/¯
Also, why would this Proton issue affect TF2 tho?

**Comment by kisak-valve** [comment]
With the 64 bit update of Team Fortress 2, the game is now run inside the Steam Linux Runtime - Sniper container environment, and the issue is between the NVIDIA 390 series and the container, not Proton specifically.

**Comment by TailsFanLOL** [comment]
Oh, alright then 😭
