### ISSUE TITLE
Question on when a bug will be fixed

### ISSUE THREAD

**Issue by TheBucketWasTaken** [ValveSoftware/Source-1-Games#5772]
When will the bug not allowing steam deck players to play tf2 be fixed?

**Comment by kisak-valve** [comment]
Hello @TheBucketWasTaken, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5621.

**Comment by JoriKos** [comment]
This is not a general forum, posts should only be made for bug reports or feature requests.

**Comment by TheBucketWasTaken** [comment]
Alright sorry for the misunderstanding
