### ISSUE TITLE
WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5. on 64 bit server

### ISSUE THREAD

**Issue by Gnomesenpai** [ValveSoftware/Source-1-Games#5775]
Documentation seems to be outdated for x64 servers. the same install worked with the 32 bit server so seems to be an issue isolated to the x64 linux installation.

WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.
  Please install (lib32tinfo5 / ncurses-libs.i686 / equivalent) to enable readline.

followed by

 failed to dlopen /home/steam/tf-dedicated/bin/replay_srv.so error=/home/steam/tf-dedicated/bin/replay_srv.so: wrong ELF class: ELFCLASS32
Could not load: replay_srv.so
FATAL ERROR: Could not load: replay_srv.so

Dockerfile has the following:

`apt-get install -y --no-install-recommends --no-install-suggests \
                wget \
                ca-certificates \
                lib32z1 \
                libncurses5:i386 \
                libbz2-1.0:i386 \
                libtinfo5:i386 \
                libcurl3-gnutls:i386 \
                libc6 \
                libc6-dev \
                libc6-dbg \
                autoconf \
                libtool \
                pip \
                nasm \
                libiberty-dev:i386 libelf-dev:i386 libboost-dev:i386 libbsd-dev:i386 libunwind-dev:i386 lib32z1-dev libc6-dev-i386 linux-libc-dev:i386 g++-multilib \
                curl file  bsdmainutils python3 util-linux binutils bc jq lib32gcc-s1 lib32stdc++6 libcurl4-gnutls-dev:i386 libsdl2-2.0-0:i386 libncurses5-dev libncursesw5-dev lib32ncurses-dev libncurses5:i386 \
`

**Comment by Tiagoquix** [comment]
OP, does this still happen after the [April 22, 2024 patch](https://www.teamfortress.com/post.php?id=220641)?

**Comment by Tiagoquix** [comment]
By the way, seems to be a duplicate of #5737.

**Comment by kisak-valve** [comment]
Closing pending feedback.
