### ISSUE TITLE
[TF2] [Urgent] [Bug] Creating a shortcut of tf.exe with -steam in the targets section allows you to connect to official servers with the 32bit client

### ISSUE THREAD

**Issue by AzureWoof** [ValveSoftware/Source-1-Games#5777]
You can connect to Official/VAC secured servers with TF2's 32bit client by creating a shortcut of tf.exe in the game's directory, adding "-steam" to the targets section of the shortcut, and then launching it. This is how botting software is getting past the 64bit update.

It needs to be set up like so:

![5N3GusW](https://github.com/ValveSoftware/Source-1-Games/assets/39247293/6b57d254-39db-4398-9485-3c5842cb188c)

Please fix this ASAP. This is being abused to bring bots back way quicker. The intended functionality is for the 32bit client to reject connections to VAC secured servers.

**Comment by Niterux** [comment]
it works fine

**Comment by Jeffonehundred** [comment]
> it works fine for me

Does not work with windows 7. Tried oping the options menu, and the game crashed. Same thing with trying to join a game. I can not get the 32 bit mode to work with this command.

**Comment by Niterux** [comment]
Windows 7 is no longer supported by Valve.

**Comment by Niterux** [comment]
> @Niterux How is my reply off topic? How does it not correlate to the topic here?

Your reply is off topic because it doesn't have to do with the -steam launch argument causing the game to launch the 32 bit executable.

**Comment by Jeffonehundred** [comment]
@Niterux Oh, I am sorry, I forgot to mention I was using that command. The 32 bit vision does not load after using on windows 7. I forgot to mention that part.

**Comment by digivorix** [comment]
I've got Windows 7 (Professional, 64-bit) and can confirm these things happen to me, with or without the -steam launch option. The game launches just fine, but as soon as I try to join a server or offline game it just crashes. I know Valve doesn't support Windows 7 anymore, but I find it weird that starting an offline game or joining a server is what causes a crash, as opposed to just having the entire application being incompatible with Windows 7 now.

**Comment by Jeffonehundred** [comment]
@digivorix Yes, its completely strange. The 64 bit build was working just 2 days ago. I still have a backup of the exe file that can play it. I think im going to fiddle around with it and see if I can get it to work. You would not think that the person who pushed this update sabotaged the files so widows 7 users would migrate to lenix do you? Not saying this is what happens. But its something to take note of just in case.

**Comment by Niterux** [comment]
Are you sure you're using tf_win64.exe instead of tf.exe? tf.exe launches the 32 bit version, launching tf_win64.exe with -steam and -game tf shows it as running the 64 bit version of Team Fortress 2 for me. Cannot reproduce your issue.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/110568869/4e74bee6-a530-4cbb-bc51-fe1590cfca3d)

**Comment by Jeffonehundred** [comment]
@Niterux Yes,after looking again, using -steam does nothing. It simply launch tf_win64.exe with not differences. Launching the tf.exe the 32 bit vision, creating your own server works using "tf.exe", but does not work with tf_win64.exe. Attempting to join a sever with "tf.exe" causes a error message to appear. The error "You are in an insecure mode. You must restart before you can connect to secure servers."

**Comment by AzureWoof** [comment]
> Are you sure you're using tf_win64.exe instead of tf.exe? tf.exe launches the 32 bit version, launching tf_win64.exe with -steam and -game tf shows it as running the 64 bit version of Team Fortress 2 for me. Cannot reproduce your issue. ![image](https://private-user-images.githubusercontent.com/110568869/324196301-4e74bee6-a530-4cbb-bc51-fe1590cfca3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDI1MjMsIm5iZiI6MTcxMzY0MjIyMywicGF0aCI6Ii8xMTA1Njg4NjkvMzI0MTk2MzAxLTRlNzRiZWU2LWE1MzAtNGNiYi1iYzUxLWZlMTU5MGNmY2EzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxOTQzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmNkOWM2Y2I0OGUxOTVlY2EyMGM5NjhmYWQ2YTM0MjRkZDI0NTlhNzdjZWY2NjA1YTg0YWFlMmQ4ZGI5OTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wyq7uwmrx3jUEAHe1h6N0vEPOuaOydoretMzspdILqw)
> 
>     * Steam already launches TF2 with -steam by default, if it launched the 32 bit version then there would be no access to 64 bit TF2.

Launching tf.exe in your game directory after putting -steam in your launch options allows you to connect to official servers, I believe. I'll edit the post to clarify.

**Comment by Jeffonehundred** [comment]
@AzureWoof I just tried that, it does not work on vac secured servers, only on non vac serves can I join. And that is with "tf.exe" not "tf_win64.exe"

**Comment by AzureWoof** [comment]
> @AzureWoof I just tried that, it does not work on vac secured servers, only on non vac serves can I join. And that is with "tf.exe" not "tf_win64.exe"

Wait, I got confused. Create a shortcut of tf.exe, and in the properties, add -steam to the targets section. Now you'll be able to connect to VAC secured servers. Editing the post to reflect this now.

**Comment by AzureWoof** [comment]
Apologies for all of the confusion. I had conflicting information. Updated the post to include accurate information. This is an urgent issue, and I hope this gets fixed ASAP.

**Comment by Joshua-Ashton** [comment]
We are still supporting the 32-bit client on Windows for a few tools people were using that exist. We'll probably drop the 32-bit client totally on Windows at some point in the future.

**Comment by kisak-valve** [comment]
Hello @AzureWoof, directly calling the 32 bit variant of the game

**Comment by kisak-valve** [comment]
Hello @AzureWoof, as @Joshua-Ashton noted, the 32 bit variant of the game existing is not a bug by mere existence.

**Comment by AzureWoof** [comment]
@kisak-valve @Joshua-Ashton My apologies if I'm causing a lot of confusion. My main reasoning for creating this post is because the 32bit client seemingly isn't supposed to allow you to connect to secure servers while in use. Launching tf.exe (32bit) by itself makes it launch in insecure mode, which still allows you to use all of the tools included with the game, but stops you from connecting to secure servers. But by making a shortcut out of it with "-steam" in the targets section of the properties, it allows you to bypass this and connect to secure servers.

Do any of the tools that are still being supported on the 32bit client require connecting to VAC secured servers for them to function?

**Comment by kisak-valve** [comment]
Running the Windows 32 bit client of Team Fortress 2 from the Steam client will start the game with the `-steam` argument included. If there is any confusion here, it's from starting the game outside of the Steam client and building an assumption starting from there.

**Comment by AzureWoof** [comment]
> Running the Windows 32 bit client of Team Fortress 2 from the Steam client will start the game with the `-steam` argument included. If there is any confusion here, it's from starting the game outside of the Steam client and building an assumption starting from there.

As of the latest update to the game, the 32bit client for TF2 was replaced with the 64bit client. I don't believe there's a way to launch 32bit TF2 from the steam client anymore. But like Joshua said, it seems like it's being kept around in the game's directory as "tf.exe" so that players can still utilize it for its tools. The 64bit client, which is the new default client that's launched from steam when launching the game is "tf_win64.exe".

So, the only way to launch the 32bit client to my knowledge is to launch tf.exe from the game's directory. By default, doing so will automatically launch it in insecure mode, which is why I'm assuming that it's not intended for players to be able to connect to VAC secured servers with that executable at all, as the 64bit version of the game has replaced it for the purposes of joining matchmaking.

I originally mistook the process of launching the 32bit client in this way as a steam client launch option, but I was incorrect. The following process is how players are bypassing the now default insecure mode on the 32bit client:

1. Go to the Team Fortress 2 main directory
2. Find "tf.exe"
3. Create a shortcut of "tf.exe"
4. Open the properties of the shortcut
5. Find targets and add -steam
6. Launch "tf.exe" via the Shortcut

You can now join VAC secure servers with the 32-bit version of Team Fortress 2 after the 64-bit update.

I also made a video to showcase and explain the process: [Link](https://www.youtube.com/watch?v=KIErgC2-ojs)

**Comment by Niterux** [comment]
The 64 bit update isn't a security update. It's designed to be a maintenance update, the presence of a 32 bit client that is able to join multiplayer is fully intentional unless it's been stated otherwise.

**Comment by AzureWoof** [comment]
> The 64 bit update isn't a anti-cheat update. It's designed to be a maintenance update, the presence of a 32 bit client that is able to join multiplayer is fully intentional unless it's been stated otherwise. And there's nothing wrong with it! I'm sure cheaters have already updated their cheats to work on the 64 bit executable anyways!

I'm well aware of that fact. As I have previously stated, launching the 32bit client unaltered does not allow you to connect to VAC secure servers. That is where my assumption lies that this tweak that bypasses that is unintentional.

**Comment by Niterux** [comment]
> > The 64 bit update isn't a anti-cheat update. It's designed to be a maintenance update, the presence of a 32 bit client that is able to join multiplayer is fully intentional unless it's been stated otherwise. And there's nothing wrong with it! I'm sure cheaters have already updated their cheats to work on the 64 bit executable anyways!
> 
> I'm well aware of that fact. As I have previously stated, launching the 32bit client unaltered does not allow you to connect to VAC secure servers. That is where my assumption lies that this tweak that bypasses that is unintentional.

You cannot connect to VAC secured servers on the 64 bit client without the -steam argument.

**Comment by AzureWoof** [comment]
> You cannot connect to VAC secured servers on the 64 bit client without the -steam argument.

Correct, which is why launching the 64bit client through steam allows connectivity. The 32bit client seemingly has no way to launch through steam, and launching the 32bit executable without the shortcut method will not allow you to join any VAC secure servers either, and there is no officially supported option to launch the 32bit version of the game to connect to VAC secure servers. That is where the confusion lies. It's unclear if this method of doing so is intentional or not.

**Comment by Niterux** [comment]
> > You cannot connect to VAC secured servers on the 64 bit client without the -steam argument.
> 
> Correct, which is why launching the 64bit client through steam allows connectivity. The 32bit client seemingly has no way to launch through steam, and launching the 32bit executable without the shortcut method will not allow you to join any VAC secure servers either, and there is no officially supported option to launch the 32bit version of the game to connect to VAC secure servers. That is where the confusion lies. It's unclear if this method of doing so is intentional or not.

That's because the 32 bit client is niche and will be removed in the future. If connecting to servers on the 32 bit client was unintentional then the functionality would have been removed.

**Comment by Jeffonehundred** [comment]
> > Running the Windows 32 bit client of Team Fortress 2 from the Steam client will start the game with the `-steam` argument included. If there is any confusion here, it's from starting the game outside of the Steam client and building an assumption starting from there.
> 
> As of the latest update to the game, the 32bit client for TF2 was replaced with the 64bit client. I don't believe there's a way to launch 32bit TF2 from the steam client anymore. But like Joshua said, it seems like it's being kept around in the game's directory as "tf.exe" so that players can still utilize it for its tools. The 64bit client, which is the new default client that's launched from steam when launching the game is "tf_win64.exe".
> 
> So, the only way to launch the 32bit client to my knowledge is to launch tf.exe from the game's directory. By default, doing so will automatically launch it in insecure mode, which is why I'm assuming that it's not intended for players to be able to connect to VAC secured servers with that executable at all, as the 64bit version of the game has replaced it for the purposes of joining matchmaking.
> 
> I originally mistook the process of launching the 32bit client in this way as a steam client launch option, but I was incorrect. The following process is how players are bypassing the now default insecure mode on the 32bit client:
> 
> 1. Go to the Team Fortress 2 main directory
> 2. Find "tf.exe"
> 3. Create a shortcut of "tf.exe"
> 4. Open the properties of the shortcut
> 5. Find targets and add -steam
> 6. Launch "tf.exe" via the Shortcut
> 
> You can now join VAC secure servers with the 32-bit version of Team Fortress 2 after the 64-bit update.
> 
> I also made a video to showcase and explain the process: [Link](https://www.youtube.com/watch?v=KIErgC2-ojs)

I just tried this on Windows 7, it does not work. I still can only connect to non-VAC servers. I have followed your instructions, and they do nothing for windows 7.

**Comment by AzureWoof** [comment]
> That's because the 32 bit client is niche and will be removed in the future. If connecting to servers on the 32 bit client was unintentional then the functionality would have been removed.

If the ability to join VAC secure servers on the 32bit client was an intentional choice, (which I feel isn't very likely considering that it takes altering a shortcut to get it to function) then I'm pretty sure that launching the game through Steam would allow you to pick between either the 32bit version of the game or the 64bit version of the game via a popup dialog like most other titles on Steam that give you that choice.

**Comment by AzureWoof** [comment]
> I just tried this on Windows 7, it does not work. I still can only connect to non-VAC servers. I have followed your instructions, and they do nothing for windows 7.

I'm personally on Windows 11. If you're absolutely sure you've followed everything correctly, it's entirely possible that this is operating-system-specific.

**Comment by Jeffonehundred** [comment]
@AzureWoof May I ask why you are trying to run the 32 bit vision of the exe? Something to do with mods right? I am just trying to find a state that the game can run.

**Comment by AzureWoof** [comment]
> @AzureWoof May I ask why you are trying to run the 32 bit vision of the exe? Something to do with mods right? I am just trying to find a state that the game can run.

No, I was just pointing out the strange interaction that the 32bit client has with those shortcut parameters, since I'm assuming that being able to join secure servers with that method is unintentional. I always run the 64bit client whenever I want to play.

**Comment by slender100** [comment]
> We are still supporting the 32-bit client on Windows for a few tools people were using that exist. We'll probably drop the 32-bit client totally on Windows at some point in the future.

This issue wasn't created about postponing 32 bit support because it is needed for various tools, this issue was opened to address a method of opening the 32 bit client which circumvents the 32 bit client normally putting the user into insecure mode upon launching the game. Will reopen this as a separate issue if I get no response.

**Comment by Niterux** [comment]
> > We are still supporting the 32-bit client on Windows for a few tools people were using that exist. We'll probably drop the 32-bit client totally on Windows at some point in the future.
> 
> This issue wasn't created about postponing the discontinuation of 32 bit support because it is needed for various tools, this issue was opened to address a method of opening the 32 bit client which circumvents the 32 bit client normally putting the user into insecure mode upon launching the game. Will reopen this as a separate issue if I get no response.

All clients usually put the game into insecure mode, -steam enables Steam support which includes enabling VAC since VAC is a part of Steam. There is nothing out of the ordinary here, please don't open another issue.

**Comment by slender100** [comment]
> > > We are still supporting the 32-bit client on Windows for a few tools people were using that exist. We'll probably drop the 32-bit client totally on Windows at some point in the future.
> > 
> > 
> > This issue wasn't created about postponing the discontinuation of 32 bit support because it is needed for various tools, this issue was opened to address a method of opening the 32 bit client which circumvents the 32 bit client normally putting the user into insecure mode upon launching the game. Will reopen this as a separate issue if I get no response.
> 
> All clients usually put the game into insecure mode, -steam enables Steam support which includes enabling VAC since VAC is a part of Steam. There is nothing out of the ordinary here, please don't open another issue.

So users on the 32 bit client should still be able to joined official VAC servers?

**Comment by Niterux** [comment]
> So users on the 32 bit client should still be able to joined official VAC servers?
yep

**Comment by slender100** [comment]
> > So users on the 32 bit client should still be able to joined official VAC servers?
> 
> I mean I'm not a developer of this game but I don't see why Valve wouldn't allow that.

The reason why is because the current 64 bit client is the client that everyone uses for joining games, yet attempting to use the 32 bit client to join a game results in an insecure message when attempting to join VAC servers.

**Comment by Niterux** [comment]
> The reason why is because the current 64 bit client is the client that everyone uses for joining games, yet attempting to use the 32 bit client to join a game results in an insecure message when attempting to join VAC servers.

Only without the -steam launch argument, the 64 bit client behaves the same, this is fully intentional behavior. As VAC is a component of Steam, so enabling Steam is required for VAC to be present.

**Comment by slender100** [comment]
> > The reason why is because the current 64 bit client is the client that everyone uses for joining games, yet attempting to use the 32 bit client to join a game results in an insecure message when attempting to join VAC servers.
> 
> Only without the -steam launch argument, the 64 bit client behaves the same, this is fully intentional behavior. As VAC is a component of Steam, so enabling Steam is required for VAC to be present.

By this logic, if the only reason the 32 bit client is still supported is due to certain tools that are reliant on it, then there is no reason why the 32 bit client should be able to connect to VAC secured servers due to the planned discontinuation of 32 bit in the future.

**Comment by Niterux** [comment]
> By this logic, if the only reason the 32 bit client is still supported is due to certain tools that are reliant on it, then there is no reason why the 32 bit client should be able to connect to VAC secured servers due to the planned discontinuation of 32 bit in the future.

Competitive players use old plugins to record demos better.

**Comment by slender100** [comment]
> > By this logic, if the only reason the 32 bit client is still supported is due to certain tools that are reliant on it, then there is no reason why the 32 bit client should be able to connect to VAC secured servers due to the planned discontinuation of 32 bit in the future.
> 
> Competitive players use old plugins to record demos better.

The game has an in-built feature for recording demos automatically, without the need for these old plugins as shown at the end of this video: https://www.youtube.com/watch?v=LX7Ef7bM4t8

**Comment by sapphonie** [comment]
If this is actually intended behavior, it's hilariously incompetent. Why in god's name would you create the opportunity to functionally brick all old cheats and just not take it? Keep the binaries, allow people to use them and play old demos + use old plugins, but x86 clients should not be allowed to connect to VAC protected servers. There is no functional reason why this should be allowed. Valve, do better.
