### ISSUE TITLE
[TF2] [SERIOUS] TF2 crashed my PC when trying to install the update

### ISSUE THREAD

**Issue by Sketchgaming** [ValveSoftware/Source-1-Games#5778]
I tried to install the Team Fortress 2 64bit update on Steam, it got to 25% and then my Windows 11 had a blue screen. I tried to reopen my PC multiple times but it's just stuck on the first loading screen every time.

I know it's not that much related to TF2 but it was visibly caused by TF2. I would appreciate any help on that matter.

**Comment by ethanholt1** [comment]
This is probably an issue with your storage medium or Steam than it is TF2. Most likely your hard drive is failing.

**Comment by kisak-valve** [comment]
Hello @Sketchgaming, the download and update of game content is handled by the Steam client, not the game itself. You might get lucky reporting this issue to [Steam Support](https://help.steampowered.com) for the larger Steam team to ponder, but it's more likely an OS or hardware issue occurred with coincidental timing.
