### ISSUE TITLE
Pyro's compression blast inconsistency after recent 64-bit update

### ISSUE THREAD

**Issue by nomorempz** [ValveSoftware/Source-1-Games#5786]
After recent (64-bit update) there's now an issue where Pyro is sometimes unable to push enemies upwards even after meeting all conditions to do so (as shown here https://www.youtube.com/watch?v=S5v1MIw59PQ . The footage is labeled as "Beta" but is still relevant to current build as of 20.04.2024). There aren't any mentions about this in patch notes, so it is believed to be a bug. This current issue is accompanied by a long-standing flamethrowers' damage ramp up system bug (as described here https://github.com/ValveSoftware/Source-1-Games/issues/4347). Both these issues currently make the class barely playable.

**Comment by kisak-valve** [comment]
Hello @nomorempz, this issue is already being tracked at #5522. Closing as a duplicate.
