### ISSUE TITLE
[TF2][Windows][x64] Emojii doesn't show up in game

### ISSUE THREAD

**Issue by JonJust** [ValveSoftware/Source-1-Games#5790]
I am unsure whether to tag this as a Linux or Windows issue

I play on Linux, where Emojii is supported. I can put emojii in the chat, see it on weapon names, etc. However, Windows users are unable to see Emojii. Can make communication asymmetrical in the text chat.

**Comment by kisak-valve** [comment]
Hello @JonJust, this issue is already being tracked at #5642. Closing as a duplicate.
