### ISSUE TITLE
no more dxlevel 81

### ISSUE THREAD

**Issue by hoodsom** [ValveSoftware/Source-1-Games#5792]
i'm not too phased switching to dx9 but..
i can no longer play sniper (my main class for last 12 years) - the dx9+ scope is absolutely horrible. it's fishbowl-y, fuzzy, and has a tint? 

I just want to have dx8 scope - no mods or file-fiddling does me any good either.

**Comment by kisak-valve** [comment]
Hello @hoodsom, this issue is already being tracked at #5631. Closing as a duplicate.
