### ISSUE TITLE
BUG: 6 Years of Rampant Bot Hosting Hackers

### ISSUE THREAD

**Issue by compromisable** [ValveSoftware/Source-1-Games#5796]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/e384e736-e375-4046-a054-bcf7e942d856)

What's the plan, guys?  
After 6 years, I think we should make a single attempt here. Let's turn this into a thinktank!

**Comment by erickoid** [comment]
Im Sad.........................

**Comment by kisak-valve** [comment]
Hello @compromisable, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5686.
