### ISSUE TITLE
[TF2] [Linux] DirectX level on Vulkan

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#5797]
On Windows, `mat_dxlevel` can go up to `95` without any problems (even with Vulkan).
However, on the Linux build, it only goes up to `92`.

Can we have DirectX version 9.5 on Linux too?

**Comment by sylveonsylvia** [comment]
92 is identical to 95 
https://developer.valvesoftware.com/wiki/DirectX_Versions#.22dxlevel_92.22.2C_.22dxlevel_97.22

**Comment by jolty1** [comment]
Dxlevel seems to default to 100 for me on Vulkan dxvk-native. I would like to try lower dxlevels for even more performance gains.

Tried launch options `-dxlevel 90` & `+mat_dxlevel 90`. Setting mat_dxlevel 90 in the console doesn't work either.

**Comment by Tiagoquix** [comment]
Going to close this as solved since `mat_dxlevel` is now default at `100` (use maximum hardware capabilities, which is basically the same as `95` since it's the best available).

![image](https://github.com/user-attachments/assets/cbb66955-ad69-4557-adc0-6755f311c41b)
