### ISSUE TITLE
[TF2] [Linux] Fonts are too small

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#5798]
First of all, thanks for fixing chat and console fonts on the TF2 Linux build.

However, even with the changes, the font is too small (at least for PC users; not sure about Steam Deck).
Compared with the Windows version of the game, they're small.

Some examples: chat text, console text is somewhat OK (but still a little tiny, could be larger), scoreboard etc.

net_graph font is also hard to read (the issue is more visible when seeing it by yourself in the game):
![image](https://github.com/ValveSoftware/Source-1-Games/assets/30274161/037c997e-6522-4ee5-b19d-b29452444124)

**Comment by kisak-valve** [comment]
Hello @Tiagoquix, this issue is already being tracked at #1883. Closing as a duplicate.
