### ISSUE TITLE
[TF2 64 bit] [Windows] Game requires a restart to change audio output device

### ISSUE THREAD

**Issue by dio260** [ValveSoftware/Source-1-Games#5800]
Before the 64 bit update, TF2's audio would properly output to the speakers/headphones I select in Windows while in-game. After the update, TF2's audio only outputs to the device that was selected at launch and requires a restart to change.

**Comment by kisak-valve** [comment]
Hello @dio260, as @dandongus noted, this issue is already being tracked at #5694.

Closing as a duplicate.

**Comment by SamLeatherdale** [comment]
Apparently #5694 doesn't exist anymore, it just 404s. This is still very much an issue though.

**Comment by DanProudfoot** [comment]
This is an issue, as I regularly swap between the audio output for my TV and headset/mic.
