### ISSUE TITLE
[TF2 64 bit] [Windows] Game always launches in insecure mode

### ISSUE THREAD

**Issue by maxisreal** [ValveSoftware/Source-1-Games#5801]
Since insecure mode means I can't join any VAC secured servers (aka all of them), I currently can't play the game.

**Comment by NULLYUKI** [comment]
Do you have any launch options or config that uses the `-insecure` launch argument?

**Comment by Jeffonehundred** [comment]
@maxisreal Are you on windows 7 or 8.1? This is impotent to know, as other people are having this issues on these visions of windows. There are 2 different exe files, tf_win64.exe and tf.exe. What one are you using?

**Comment by kisak-valve** [comment]
Hello @maxisreal, this issue is already being tracked at #5638. Closing as a duplicate.
