### ISSUE TITLE
[TF2 64 BIT] I cant join Casual/Community Servers

### ISSUE THREAD

**Issue by pajarogarca** [ValveSoftware/Source-1-Games#5802]
when ever I try to join casual it pops up a message it says "You arent secured. You need to restart the game" (something like that) I have been trying for like 1 hour straight. A friend told me to put -safe or -sfe on launch parametters and still not working, I have the antivirus disabled and checked if the game files got installed correctly and still nothing
HELP PLEASE!!! :((((((

**Comment by ethanholt1** [comment]
Are you running the game under Proton? If so, you won’t be able to connect to community servers. 
Additionally, this isn’t a help forum, this is an issues page. Please don’t ask us for help.

**Comment by pajarogarca** [comment]
what do you mean with that? what´s Proton?

**Comment by kisak-valve** [comment]
Hello @pajarogarca, this issue is already being tracked at #5638. Closing as a duplicate.
