### ISSUE TITLE
tf2 will close itself upon opening settings or trying to start a match

### ISSUE THREAD

**Issue by parapeito** [ValveSoftware/Source-1-Games#5807]
tf2 will open like normal, but once a match is found and finishes loading it will simply crash the game and cause to close, same thing happens if i try to open settings. my only guess is that it has something to do with windows version, as other repports of people with the same issue have pointed out to be using windows 7 (which i`m using too). I have already unninstalled and installed the game, tried using different dx_levels and tried entering offline training mode matches, and none of theses worked.

**Comment by NULLYUKI** [comment]
Related to https://github.com/ValveSoftware/Source-1-Games/issues/5743

**Comment by kisak-valve** [comment]
Hello @parapeito, this issue is already being tracked at #5728 and #5674. Closing in favor of the older issue reports.
