### ISSUE TITLE
TF2 saying that im in insecure mode

### ISSUE THREAD

**Issue by Some2-Idk** [ValveSoftware/Source-1-Games#5813]
I don't know what the froot loops is happening here but **BEFORE** the 64 BIT update I was connecting to servers just fine, but now I'm insecure or something.

**Comment by JoriKos** [comment]
What OS are you on?

**Comment by san0c** [comment]
on win7 i got same message
using tf.exe
tf_win64 crash after i try connect to any server or open options

**Comment by kisak-valve** [comment]
Hello @Some2-Idk, this issue is already being tracked at #5638. Closing as a duplicate.
