### ISSUE TITLE
[TF2] VALVE ANTI-CHEAT

### ISSUE THREAD

**Issue by Skardium** [ValveSoftware/Source-1-Games#5823]
Please can you update the Anti cheat Valve becuz too much cheater Megatronic and Omegatronic, Luna BOT cheating on the game.. reset all level ?

**Comment by Skardium** [comment]
too many cheater on Capture the flag in 2Fort map.

**Comment by Skardium** [comment]
Put Easy Anti Cheat and Valve Anti cheat cooperation its good

**Comment by JoriKos** [comment]
Duplicate of #5686

This is also for Source 1 games, not for VAC

**Comment by kisak-valve** [comment]
Closing as a duplicate of #5686.
