### ISSUE TITLE
tf2 crashed when join a server 

### ISSUE THREAD

**Issue by 2xCelebrations** [ValveSoftware/Source-1-Games#5826]
[crash_tf_win64.exe_20240420220050_1.dmp](https://github.com/ValveSoftware/Source-1-Games/files/15048635/crash_tf_win64.exe_20240420220050_1.dmp)

**Comment by NULLYUKI** [comment]
Which Windows version are you running?
Might be related to https://github.com/ValveSoftware/Source-1-Games/issues/5674

**Comment by 2xCelebrations** [comment]
> Which Windows version are you running? Might be related to #5674

windows 7,seems like a lot of people have this problem too

**Comment by kisak-valve** [comment]
Hello @2xCelebrations, this issue is already being tracked at #5674. Since the minidump adds a bit more detail, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/5674#issuecomment-2067699009.

Closing as a duplicate.
