### ISSUE TITLE
[TF2][X64] I can´t enter any single game and my game crashes when i click the options button

### ISSUE THREAD

**Issue by Bateficticio2** [ValveSoftware/Source-1-Games#5831]
After the actualization X64bits .I cant play casual,practice or launch a server cause game´s crashes instantly or if i click the option button the game crashes.Even when I have a x64 bits system.Pls i need help to fix this problems

**Comment by DragShot** [comment]
Same problem here. Does anybody know of any new launch parameters we can use in the 64-bit build?

**Comment by kisak-valve** [comment]
Hello @Bateficticio2, this issue is already being tracked at #5728 and #5674. Closing as a duplicate.

**Comment by Bateficticio2** [comment]
Ok i see. @kisak-valve thanks

**Comment by Bateficticio2** [comment]
@NULLYUKI  my operation sistem is windows
