### ISSUE TITLE
[TF2] [Linux] Starting Tf2 64bit turns of second monitor and crashes

### ISSUE THREAD

**Issue by gmBlahaj** [ValveSoftware/Source-1-Games#5836]
When starting TF2 in 64bit mode while having 2 Monitors attached, it will 
1. Proceed to the loading screen
2. Turn off monitor it was launched on
3. Crash

But when launching it with only one monitor attached it works fine

Specs:
GPU: Nvidia RTX 3070 Ti
CPU: 12th gen  Intel i5-12600
Distro: Gentoo

**Comment by kisak-valve** [comment]
Hello @gmBlahaj, this issue is already being tracked at #5704. Closing as a duplicate.
