### ISSUE TITLE
[TF2 x64] Connection Issues 

### ISSUE THREAD

**Issue by Stattek** [ValveSoftware/Source-1-Games#5839]
Since the new 64 bit update, I have been experiencing weird connection problems on servers. It doesn't matter what server it is on, it happens on every one, even casual servers when it never happened before. I have good ping, but it will just randomly do this. I use the launch options `-dxlevel 98 -novid -nojoy -w 1920 -h 1080 +exec "autoexec.cfg"`. For this clip, I removed all of the files in my `cfg` and `custom` folders, and it was still happening. I have even tried running tf2 with Vulkan, and it still happened.

I am running with these specs:
Windows 11
I7-9700k
64 GB RAM
GTX 1080Ti

https://github.com/ValveSoftware/Source-1-Games/assets/107233826/a7b7a276-99e8-41b5-9f6c-91c564da1cf3

**Comment by Stattek** [comment]
This seemed to have been happening because of my VPN. Never had this problem before, but I can't play the game at all with it anymore.

**Comment by Joshua-Ashton** [comment]
You probably just had hl2.exe allowlisted before or something, none of the networking code has changed at all.

**Comment by Tiagoquix** [comment]
Hi OP, is this still relevant?

**Comment by Stattek** [comment]
> Hi OP, is this still relevant?

I have since switched to Linux and have not had this issue.
