### ISSUE TITLE
[TF2] The group chat window glitches and shrinks everytime you open and close it

### ISSUE THREAD

**Issue by StShAzzy** [ValveSoftware/Source-1-Games#5844]
eventually, i'll get like this
![image](https://github.com/ValveSoftware/Source-1-Games/assets/90798128/4853ed0a-b405-4caa-8d1f-2de43c629b68)

**Comment by slender100** [comment]
this sounds like issue #3774

**Comment by kisak-valve** [comment]
Hello @StShAzzy, the game resolution is close enough to match the older issue report.

Closing as a duplicate of #3774.
