### ISSUE TITLE
Team Fortress 2 can't find casual match and it cant be loaded when pressed f9 in hammer editor

### ISSUE THREAD

**Issue by Anerrete** [ValveSoftware/Source-1-Games#5849]
When the 64 bit update released i could play casual but later the same day when i tried to find a match the text saying im searching for a casual match dissapeared and it still does not work.
I can't compile and test a map on hammer.

**Comment by JoriKos** [comment]
First issue is probably #2820
Second issue is #5834

Please also keep posts to 1 issue and not multiple

**Comment by kisak-valve** [comment]
Hello @Anerrete, as @JoriKos noted, these issues are already being tracked at #2820 and #5834. Closing in favor of the older issue reports.
