### ISSUE TITLE
[HL2] Crash On Start

### ISSUE THREAD

**Issue by ComputerDruid** [ValveSoftware/Source-1-Games#585]
The crash happens before anything plays.
A window appears, it goes fullscreen, but stays black, but no intro video, loading bar, or menu screen appears. It then crashes with:

Game update: AppID 220 "Half-Life 2 (Beta)", ProcID 4706, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
SDL video target is 'x11'
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20130503151021_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
[0511/011414:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0511/011414:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 220
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197996882819 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197996882819
Did not detect any valid joysticks.
[0511/011417:ERROR:resource_bundle.cc(411)] Failed to load /home/cdruid/.local/share/Steam/SteamApps/common/Half-Life 2/cef_gtk.pak
Some features may not be available.
[0511/011417:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0511/011417:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Could not load program cache file glshaders.cfg
Could not find user GL shader cache file
Precache: Took 0 ms, Vertex 0, Pixel 0
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game.so loaded for "Half-Life 2"
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20130511011422_1.dmp
/home/cdruid/.local/share/Steam/SteamApps/common/Half-Life 2/hl2.sh: line 67:  4709 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 220 "Half-Life 2 (Beta)", ProcID 4709 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Finished uploading minidump (out-of-process): success = no
error: HTTP response code said error

**Comment by kisak-valve** [comment]
Hello @ComputerDruid, this was a steam runtime compatibility issue. If you are still experiencing this issue with an up to date system, please take a look at https://github.com/ValveSoftware/steam-for-linux/issues/4768, and if that does not help, then see if your package maintainer for steam has some insight.
