### ISSUE TITLE
Get rid of the bots

### ISSUE THREAD

**Issue by ramonava909** [ValveSoftware/Source-1-Games#5853]
Is there any way Valve can get rid of the bots in Team fortress 2 at all ? Its a stupid bug that a lot of people hate.

**Comment by wgetJane** [comment]
this doesn't seem to fit the purpose of this repo, i feel like this would belong more in the following places:

- https://www.reddit.com/r/tf2/submit?selftext=true
- https://steamcommunity.com/app/440/discussions/

**Comment by jh34ghu43gu** [comment]
Probably duplicate of #3477

**Comment by kisak-valve** [comment]
Hello @ramonava909, this issue is already being tracked at #3477.

Closing as a duplicate.
