### ISSUE TITLE
[TF2] `snd_cull_duplicates` No longer works properly in the 64 bit build

### ISSUE THREAD

**Issue by Marioiscool246** [ValveSoftware/Source-1-Games#5858]
The 32 bit client works fine with it however.

Win64
Version: 8830351
Build ID: 14104688

**Comment by Joshua-Ashton** [comment]
Will be fixed in the next update

**Comment by NULLYUKI** [comment]
According to patch [220641](https://www.teamfortress.com/post.php?id=220641)
`Fixed the snd_cull_duplicates command not working`

This issue requires retesting.

**Comment by NotNihilanth** [comment]
Tested on Win64 just now, the command works properly after the fix

**Comment by Marioiscool246** [comment]
I can confirm that the command is working correctly again the win64 version of the game (game version 8835751).
