### ISSUE TITLE
[TF2] [Windows] Xbox Game Bar doesn't work properly with Vulkan

### ISSUE THREAD

**Issue by NotHyper-474** [ValveSoftware/Source-1-Games#5869]
Only when in Exclusive Fullscreen. Pinned widgets disappear and trying to open it with Win+G seems to "freeze" the game. I'm not sure if it's freezing, maybe the game thinks it's unfocused because when I press Win+G again and then Alt+Tab it goes back to normal.
Doesn't happen in D3D9

Specs:
Windows 11 Pro 23H2
AMD Ryzen 5 4600G
Using integrated GPU

**Comment by slender100** [comment]
Try using the windowed borderless launch options `-noborder` & `-windowed`, and setting your resolution with `-w` & `-h` (example: `-noborder -windowed -w 1600 -h 900`) as source games tend to not like going into fullscreen & interacting with anything else.

**Comment by NotHyper-474** [comment]
> Try using the windowed borderless launch options `-noborder` & `-windowed`, and setting your resolution with `-w` & `-h` (example: `-noborder -windowed -w 1600 -h 900`) as source games tend to not like going into fullscreen & interacting with anything else.

Yeah I know that workaround, and I'm actually not really affected by this issue as I mainly use the XGB in L4D2. I just posted this hoping it's a bug that can be fixed to other players that might run into the same problem.

However maybe it's more of a DXVK issue than a TF2 one? I read [here](https://github.com/doitsujin/dxvk/issues/2123) that they don't intend to add support for Game Bar, but that was three years ago so perhaps things have changed. And also [this](https://github.com/doitsujin/dxvk/wiki/Windows#third-party-software) says overlays are not really compatible

**Comment by NotHyper-474** [comment]
I'll be closing this issue as it's possibly a DXVK "problem" and they don't seem to be looking forward to adding support for Game Bar overlay.
