### ISSUE TITLE
[TF2] Keep party members on the same team [still not enabled]

### ISSUE THREAD

**Issue by kierohere** [ValveSoftware/Source-1-Games#5876]
The option has been disabled since its introduction. I still encounter an issue today when my teammate is transferred to the opposite team. Please enable or fix this option. Thank you from the bottom of my heart.

![20240422192632_1](https://github.com/ValveSoftware/Source-1-Games/assets/159793778/a7e2e907-be80-403a-9de9-577391b884b6)

**Comment by JoriKos** [comment]
This is intentional, it clearly says coming soon (meaning it's not fixed) so there's nothing to enable or fix
