### ISSUE TITLE
[TF2] -tools launch option is not existing anymore in 64 bits

### ISSUE THREAD

**Issue by pitbullnamed1** [ValveSoftware/Source-1-Games#5891]
If you have -tools in launch options of Team Fortress 2, main menu doesn't work at all, because there is a whole chunk of the game missing, aka particle editor, commentary editor, material editor

**Comment by kisak-valve** [comment]
Hello @pitbullnamed1, this issue is already being tracked at #5513. Closing as a duplicate.
