### ISSUE TITLE
IDK how to name this 

### ISSUE THREAD

**Issue by notAXEN** [ValveSoftware/Source-1-Games#5897]
so just playing banana bay 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/167555476/1c145c7e-c718-4e84-b80b-887f335ac79c)

**Comment by notAXEN** [comment]
![image](https://github.com/ValveSoftware/Source-1-Games/assets/167555476/7db87a4d-5556-4339-a650-dab81a9ed729)

**Comment by notAXEN** [comment]
bro idk what are you talking about

**Comment by JoriKos** [comment]
This is a bug from the pre-64-bit days, apparently caused by some prop detail issues IIRC. Also happens on Mossrock. Safe to assume that it at least affects whatever was used in the 32-bit version.

**Comment by notAXEN** [comment]
oh i have win 11

ShaderAPI: shaderapidx9
Shader API Driver Info:
