### ISSUE TITLE
[TF2] Missing dev tools on Linux

### ISSUE THREAD

**Issue by halamix2** [ValveSoftware/Source-1-Games#5898]
Tools that were accessible in `Team Fortress 2/bin` (e.g. vtf or BSPZIP) directory are gone on Linux

**Comment by JoriKos** [comment]
They're here on Windows, but some, like HLMV, are not usable.

Related: #5513

**Comment by kisak-valve** [comment]
Hello @halamix2, this is a duplicate of https://github.com/ValveSoftware/source-sdk-2013/issues/141, which was effectively answered at https://github.com/ValveSoftware/source-sdk-2013/issues/141#issuecomment-22062601.
