### ISSUE TITLE
[TF2] [64 Bit] [Windows] Game has progressively become more and more impossible to play on. 

### ISSUE THREAD

**Issue by IzzyisEC** [ValveSoftware/Source-1-Games#5911]
Ever since the launch of the 64 bit update, my game has started to progressively stutter more and more. At first it took me having to remove some launch settings to even have it work, and as of today, I was only able to launch Tr_walkway, because whenever I tried loading up an actual server, it would lose frames into oblivion. Even then, there was the stuttering of the game itself still. 
Running on the 32 bit version of the game didn't do any favors either as I had an error message. 
If there's some way around this I'd like to know before I start digging into how to improve my situation. 

My specs:
Processor	11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz
Installed RAM	8.00 GB (7.77 GB usable)
System type	64-bit operating system, x64-based processor
I've also run my game off a Seagate Portable 2Tb drive without issues before this

**Comment by IzzyisEC** [comment]
Forgot to add as well, I run the game with the low masterconfig set.

**Comment by wgetJane** [comment]
> Running on the 32 bit version of the game didn't do any favors either as I had an error message

did you run it with the `-steam -game tf` launch options

**Comment by IzzyisEC** [comment]
> > Running on the 32 bit version of the game didn't do any favors either as I had an error message
> 
> did you run it with the `-steam -game tf` launch options

No I didn't, but trying it out fixed my issue, thanks!
