### ISSUE TITLE
Tf2 crashing after map change at random

### ISSUE THREAD

**Issue by indirectmondor** [ValveSoftware/Source-1-Games#5914]
My game crash after map change at random. Alot of other people that I know that have configs also crash. I have the CFG.tf config personally. I am not sure what the problem is.

**Comment by NULLYUKI** [comment]
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/5885

**Comment by indirectmondor** [comment]
lol my bad forgot he made one will close this one
