### ISSUE TITLE
[WIN 11] [64 BIT] [TF2] Stutters when typing server tags into Server Browser

### ISSUE THREAD

**Issue by Eshyyyyy** [ValveSoftware/Source-1-Games#5916]
After the 64 bit update, typing tags into the server browser will cause the game to noticeably stutter. This happens both in the main menu and in a server.

**Comment by NULLYUKI** [comment]
Related to https://github.com/ValveSoftware/Source-1-Games/issues/5908

**Comment by kisak-valve** [comment]
Hello @Eshyyyyy, as @NULLYUKI noted, this issue is already being tracked at #5908.

Closing as a duplicate.
