### ISSUE TITLE
[TF2] [Linux] "é" key no longer recognised

### ISSUE THREAD

**Issue by calculatortamer** [ValveSoftware/Source-1-Games#5931]
help i play tf2 with french keyboard (azerty) and the "é" key (2 on qwerty, above Z) no longer works

i use it as "slot2" but now heavy cant eat chocolate :'((((((

im on debian testing (cinnamon de) and i updated yesterday

edit: same for "è" (7), "ç" (9), "à" (0), "²" (tilde)

as a workaround i have to run these commands to invert the key layout (to input "2" without shift and "é" with shift) :

xmodmap -e "keycode 11 = 2 eacute"
xmodmap -e "keycode  16 = 7 egrave"
xmodmap -e "keycode  18 = 9 ccedilla"
xmodmap -e "keycode  19 = 0 agrave"

**Comment by tupo2** [comment]
Yes, since the 64-bit upgrade, the default layout is in QWERTY for controls, bu not for the box chat and the console.
IMO, it's much better like this, some keys were not recognized in AZERTY, in my case.

@calculatortamer, you can just rebind it in Options > Keyboard or in autoexec.cfg: `bind "2" "slot2"`.

**Comment by calculatortamer** [comment]
> Yes, since the 64-bit upgrade, the default layout is in QWERTY for controls, bu not for the box chat and the console. IMO, it's much better like this, some keys were not recognized in AZERTY, in my case.
> 
> @calculatortamer, you can just rebind it in Options > Keyboard or in autoexec.cfg: `bind "2" "slot2"`.

thanks for your answer! "2" is already bound to "slot2", it used to work even after the 64-bit update but now it no longer works

i can rebind other keys like & (1 in qwerty) and double quote (3 in qwerty) and it'll register as "1" and "3" in the options, but for some reason keys with accents like é (2 in qwerty) don't work

**Comment by tupo2** [comment]
All those keys work for me under Debian Sid.
You can verify in the console (by default key: **`**), if it's correctly bound:
```
bind 2
bind 7
bind 9
bind 0
```
Also don't forget to reverse your keymaps with `xmodmap`.

**Comment by calculatortamer** [comment]
i think i found the problem, it was ibus being a F- NUISANCE!!

those keys work again without needing to rebind with xmodmap after killing/uninstalling ibus (and it even solved sticky keys in other games!)
