### ISSUE TITLE
[TF2] how can i play the x32 version without having the insecure mode issue?

### ISSUE THREAD

**Issue by PyrodosBandeclay** [ValveSoftware/Source-1-Games#5934]

**Comment by NULLYUKI** [comment]
This is not a general forum to ask questions. 
> Please use this repository to report bugs and feature requests for Team Fortress 2, Counter-Strike: Source, Left4Dead2, and the Source 1 Engine.

https://github.com/ValveSoftware/Source-1-Games/blob/master/README.md
