### ISSUE TITLE
[TF2] Feature Request: Suggestions to reduce bot farming

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#5953]
As many have speculated for years already, bots (not cheating bots) are being massively used to farm items, especially during Scream Fortress and Smissmas. To make them as unprofitable to run as possible, here are a few suggestions:
1. Rework the drop system. In Dota 2 this problem was also big, until Valve just straight up made all random drops untradable. This obviously won't work in TF2, as crafting and trading are directly connected, but something similar to the CS2 drop system could work, where players need to actually play and earn XP to receive rewards instead of idling. There are many ways to do it. Like adding daily challenges that reward players with a weapon or case (maybe even let them pick the reward they want). 7 weapons, 1 cosmetic and 1 war paint case in 7 days is similar to the current drop rate of items.
2. Change how cases drop. Giving F2P accounts cases doesn't make much sense. They are not able to trade them and most likely won't ever open them. For normal players who are not interested in spending money in TF2 they only clutter their already limited backpacks. However, bots can collect them, even on F2P accounts (also in the main menu), and if needed, $5 can be spent to let it move farmed cases to another account, flooding the market.
3. Giftapults. This is the most serious issue. Giftapults have no restrictions on who can receive the package. It can even be a F2P account idling in the main menu. There is no easy way to deal with it. Either straight up disable this item, as Secret Saxton exists, and we know that a player playing on the same server will receive our present instead of some bot, or only allow Premium accounts to send and receive presents.
4. Secret Saxtons. This is less of an issue than the others above, but Premium accounts are being used to farm Secret Saxtons given during Smissmas. The easiest way would be to make them untradable so only their owners can use them. (Not directly related to the issue, but Noise Maker - Winter Holiday has no 'Not Tradable or Marketable' attribute attached to it, like Noise Maker - TF Birthday, which every year generates only more and more items. Please make them untradable too.)

**Comment by kisak-valve** [comment]
Hello @KimmyTF2, this general topic is being tracked at #3477. Since this issue report adds some more details, I've transferred it to https://github.com/ValveSoftware/Source-1-Games/issues/3477#issuecomment-2087457072.

**Comment by KimmyTF2** [comment]
@kisak-valve Can you please reopen this post? It's not about cheating bots but idling bots (afk accounts).
