### ISSUE TITLE
[TF2] Master's Yellow Belt and the Hillbilly Speed Bump cannot be equipped together

### ISSUE THREAD

**Issue by Silver8753** [ValveSoftware/Source-1-Games#5959]
Hello.

I noticed something odd when I booted up TF2 today. Two Sniper cosmetics, those being the Master's Yellow Belt and the Hillbilly Speed Bump, cannot be worn together. They do not have the same equip regions (MYB is considered a Headband and HSB a Pocket Accessory) nor do they come anywhere near each other on the character so it is not as though they clip into one another. Attached is a video showing what I mean, and also showing that the HSB is the only pocket cosmetic (that I know of) that does this since I can equip another pocket cosmetic just fine. I presume this is just a bug but if it's not I'm interested in knowing why they cannot be equipped together.

https://github.com/ValveSoftware/Source-1-Games/assets/168769197/6df1d005-7ba7-4ea8-b019-532094bdf85f

**Comment by ArtKitCat** [comment]
This seems to be an issue with multi-class pocket cosmetics that share the `engineer_pocket` equip region. 

Cosmetics affected are: Deadliest Duckling, Dual-Core Devil Doll, Hillbilly Speed Bump, Itsy Bitsy Spyer, Pocket Raiders, Pocket Saxton and Pocket Yeti.

**Comment by DiskIntegrity** [comment]
This seems to be a bug with the `engineer_pocket` region, as certain multi-class pocket cosmetics cant be equipped when wearing the Master's Yellow Belt first.

The ones affected are Deadliest Duckling, Dual-Core Devil Doll, Hillbilly Speed Bump, Itsy Bitsy Spyer, Pocket Raiders, Pocket Saxton and Pocket Yeti

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed not being able to equip the Master's Yellow Belt and the Hillbilly Speed Bump at the same time 

This needs to be retested.

**Comment by Silver8753** [comment]
![image](https://github.com/user-attachments/assets/add34a0e-227b-4b04-aad2-2b2581c9b9e2)
It has been fixed. This issue is now resolved.
