### ISSUE TITLE
[TF2] HDR/Outline bug

### ISSUE THREAD

**Issue by MortimerMcMire315** [ValveSoftware/Source-1-Games#596]
Greetings,

When I play on a game mode that uses outlines (e.g. the outline around the cart on Payload or the outline around the intel carrier on CTF), I get a pretty magnificent graphical glitch. It seems to start and go away at random times. If I'm playing like HDR turned on, it looks like this:
![2013-05-11_00001](https://f.cloud.github.com/assets/2511878/491220/d937a6e0-b9fb-11e2-9b70-40237146f153.jpg)
![2013-05-11_00002](https://f.cloud.github.com/assets/2511878/491222/f2435c9c-b9fb-11e2-93c6-cfb1b9da4b36.jpg)
![2013-05-11_00003](https://f.cloud.github.com/assets/2511878/491223/f642c044-b9fb-11e2-932d-5fdacf03dfe3.jpg)

If HDR is turned off, it looks like this:
![2013-05-11_00004](https://f.cloud.github.com/assets/2511878/491224/fd9c3ce4-b9fb-11e2-9b66-616e899ce189.jpg)
![2013-05-11_00005](https://f.cloud.github.com/assets/2511878/491225/ff26cfa2-b9fb-11e2-89b2-adcdfb4d850a.jpg)
![2013-05-11_00006](https://f.cloud.github.com/assets/2511878/491226/00ac0766-b9fc-11e2-8540-c9b1a7013d78.jpg)

Obviously it has something to do with the outline, but it is unclear, as it turns on and off at random intervals.

I'm playing on Arch Linux x86-64 (I know it's unsupported, but in this case the distro should have nothing to do with it), using the latest Catalyst drivers for my Radeon HD 7850 graphics card.

Thanks!

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
