### ISSUE TITLE
[TF2] Reset achievements should also reset achievement items

### ISSUE THREAD

**Issue by GolfinhoVoador** [ValveSoftware/Source-1-Games#5966]
It would work by deleting previous achievement items (all items marked as achievement items) and then resetting achievements too, this would probably require some changes in the back-end so you can re-obtain the items by completing achievements again.

Right now the reset achievements button just resets achievements and doesn't remove achievement items and also doesn't give you the ability to re-obtain items previously deleted by yourself. (Support wont recover these items since ~2020)

**Comment by GolfinhoVoador** [comment]
I cant add labels, but its a feature suggestion

**Comment by JoriKos** [comment]
This is not the right solution to the problem you want to solve, as this would just leave players who accidentally (and yes, that does happen sometimes) reset their achievements without weapons they earned before.

**Comment by GolfinhoVoador** [comment]
We should discuss a better solution to this problem somewhere then.

I will start by another suggestion, how about checking if the player already has the item from the achievement every time they earn that achievement?
(This might create some stress in the item servers)

**Comment by GolfinhoVoador** [comment]
I accidentally closed this as resolved, but I meant to close it as wont-fix since nobody wants to discuss a better solution here, just reply to this and I'll reopen it
