### ISSUE TITLE
[TF2] [64 Bit] [Windows] Game runs much slower than before.

### ISSUE THREAD

**Issue by IzzyisEC** [ValveSoftware/Source-1-Games#5967]
Previously made another issue post about how my game was chugging along through the menu and took even longer to even load up at all, and made an adjustment to my launch settings that gave a temporary fix. However now the same issues continue once more.
I think it might be the result of my launch settings, since that seemed to improve things previously, so this is essentially me asking what to get rid of or if it could be something else. 

My launch settings:
-noborder -particles 1 -noquicktime -reuse -steam -game tf

My specs:
Processor 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz 2.69 GHz
Installed RAM 8.00 GB (7.77 GB usable)
System type 64-bit operating system, x64-based processor
I also run my game off a Seagate Portable 2Tb drive without issues before this, with the low masterconfig (Though I'm not sure if I should re install it at this point _if_ that even has some significance).

**Comment by treacherousfiend** [comment]
mastercomfig just released a new version today which should work a bit better on the 64bit version of the game, so it probably would be worth at the very least updating from the version you already have to see if it helps.
as a side note, `-noquicktime` no longer exists in tf2 as of the 64bit update, `-reuse` is essentially useless, and `-steam -game tf` is not required if you are launching the game through steam. Although your current launch options (aside from `-particles 1`) should have no effect on performance at all
Full disclosure, I do work on mastercomfig a bit and am pretty heavily active in their support channels, so y'know, bias. But we do have a recommended set of launch options of `-novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars`.
`-nojoy -nosteamcontroller` in specific should improve your game startup load times a bit.
