### ISSUE TITLE
[HL2]Combine APC wheels "sink" in a street

### ISSUE THREAD

**Issue by kwahoo2** [ValveSoftware/Source-1-Games#597]
![2013-05-11_00001](https://f.cloud.github.com/assets/3474114/491266/8fe6e92e-ba0a-11e2-93c8-3bb1c92c4602.jpg)

```

Wersja systemu operacyjnego:
    Ubuntu 13.04 (64 bitów)
    Nazwa kernela: Linux
    Wersja kernela: 3.9.0-030900-generic
    Dostawca serwera X: The X.Org Foundation
    Wydanie serwera X: 11303000
    Menedżer okien X: Compiz
    Wersja biblioteki Steam: steam-runtime-release-i386_2013-05-08
```

**Comment by FindTheBorealis** [comment]
Fixed as of the 2024 Anniversary update. 

![image](https://github.com/user-attachments/assets/4465db3d-c01e-4dd5-97e7-0f69b1c06772)

**Comment by kwahoo2** [comment]
Thanks @FindTheBorealis This was the first thing I checked running the update, but I completely forgot about the issue I created! Closing.
