### ISSUE TITLE
[TF2] [Linux 6.8.9] Crash when loading into online or offline match at 'Loading Resources'

### ISSUE THREAD

**Issue by podit** [ValveSoftware/Source-1-Games#5973]
Starting today following a system update I have been unable to load into a online or offline game due to a crash during the loading process. I have been testing with a practice match on dustbowl, it appears to happen right before an image for the map being loaded is typically displayed, reported as 'Loading Resources'.

**Description:**
I started by vertifying the cache, which did nothing to resolve it. I then gathered some logs to see of any libraries were missing, which one was from the core dumping process called `libunwind`, I linked this and the error went away with no affect on my issue. I then went about testing, first I removed custom content which changed nothing, second I removed my launch options which also didn't help (though it did cause a separate known issue to appear, which I will discuss in a moment) and finally I verified the cache in this base state, which miraculously resolved my issue and I was greeted by dustbowl. Pleased I went back through the process described testing sucessfully at each step, though in poor practice I took the opportunity to change the launch option '-freq 144' to '-refresh 144 +fps_max 144'.

I restarted my machine to fix an issue caused by the 64bit/Vulkan update where my monitor (144hz) has its refresh rate forcibly set to an unknown low number, previously I had solved this with the launch option '-freq 144'. I forgot I could clear this by power cycling the monitor, but the restart also allows me to make sure the fix has stuck. But it hadn't and the crash had returned, repeating the same process again didn't help, though the refresh rate issue caused by clearing my launch options was gone. Who knows how or why, I just think it worth mentioning.

**System:**
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.8.9-zen1-1-zen
X Server Vendor: The X.Org Foundation
X Server Release: 12101013
X Window Manager: dwm
Steam Runtime Version: steam-runtime_0.20240304.79797

CPU: AMD Ryzen 7 5800X 8-Core Processor
GPU: AMD Radeon RX 6800 XT

**Logs:**
So in this clean state I have compiled logs along with the crash dump using `%command% -condebug >& ~/tf.log`:
- [tf.log](https://github.com/ValveSoftware/Source-1-Games/files/15211157/tf.log)
- [console.log](https://github.com/ValveSoftware/Source-1-Games/files/15211158/console.log)
- [crash_20240504233100_15.dmp.zip](https://github.com/ValveSoftware/Source-1-Games/files/15211160/crash_20240504233100_15.dmp.zip)

I'll keep updating my system in hope of a resolution and report any changes, thanks

**Comment by kisak-valve** [comment]
Hello @podit, can you check if https://gitlab.freedesktop.org/drm/amd/-/issues/3343 is relevant to your system? A quick test would be to check how the game behaves with an older kernel.

**Comment by podit** [comment]
yes, using the 6.8.7 linux kernel resolves this issue, with the issue being present on the 6.8.9 kernel.

however the issue is present on both versions of the zen kernel I use, this means that the 6.8.7 zen kernel i have been using for the last 2 weeks had this problem present without issue, which probably implicates the radeon driver also?

holy moly that was fast, thanks!

**Comment by podit** [comment]
there's no change with the 6.8.9 kernel, but i have now tested the 6.8.8 kernel which is also fine. from now on i'll watch for updates to the radeon driver as well

**Comment by podit** [comment]
sweet, as of kernel version 6.9.1 the issue appears to be fixed, for both the standard and zen linux kernel

**Comment by podit** [comment]
linux kernel 6.9.1 has fixed the issue
