### ISSUE TITLE
[TF2] GeForce Experience Folders are broken 

### ISSUE THREAD

**Issue by BoyOHBoy123** [ValveSoftware/Source-1-Games#5980]
Ever since the 64-bit update my TF2 clips have been saving to the 'Desktop' folder instead of the 'Team Fortress 2' folder.

Before Update:
![Before Update](https://github.com/ValveSoftware/Source-1-Games/assets/75350507/cca75ef1-09ed-4864-8959-0e59fe5e73f1)

After Update:
![After Update](https://github.com/ValveSoftware/Source-1-Games/assets/75350507/bdaf7c72-b303-49ae-a29c-4f2a2ec0b8d2)

**Comment by sylveonsylvia** [comment]
this would be an issue on nvidias end. the devs have no control over what directory geforce expirence saves videos in afaik

**Comment by JoriKos** [comment]
My Team Fortress 2 clips have been saving in the correct folder, perhaps your GeForce is outdated and it doesn't recognise TF2 as its own thing?

**Comment by kisak-valve** [comment]
Hello @BoyOHBoy123, as @sylveonsylvia noted, this isn't a subcomponent of the game.

Closing as out of scope for this issue tracker.
