### ISSUE TITLE
TF2 MvM: Sentries do not benefit from the third level of +10% Sentry Firing Speed [upping a request]

### ISSUE THREAD

**Issue by Darol23** [ValveSoftware/Source-1-Games#5981]
The third level for +10% Sentry Firing Speed does nothing. Is it possible to fix it, or remove that third upgrade that acts as a money trap?

This request is referring to #3182

Thank you in advance

**Comment by kisak-valve** [comment]
Hello @Darol23, please do not intentionally open duplicate issue reports.
