### ISSUE TITLE
[TF2] Skating Scorcher taunt searches for sound file with wrong path (fix included)

### ISSUE THREAD

**Issue by flurbury** [ValveSoftware/Source-1-Games#5988]
The Skating Scorcher's `Taunt.skating_scorcher_trick` sound entry has an error where it tries to look for a non-existent sound file, as seen by this console warning when loading in a map:
![image](https://github.com/ValveSoftware/Source-1-Games/assets/21269703/e49364b7-57af-4dfc-8d4b-1ca851b74bf6)
There are many other sound entries that give similar warnings (as their sounds are completely missing from the game), but in this case this can be fixed by correcting the path in `scripts\game_sounds_taunt_workshop.txt`:

```diff
"Taunt.skating_scorcher_trick"
{
	"channel" 			"CHAN_VOICE"
	"volume" 			"VOL_NORM"
	"pitch" 			"PITCH_NORM"
	"soundlevel" 			"SNDLVL_95dB"
	"rndwave"
	{
  		"wave"			"vo/pyro_positivevocalization01.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_cong_fun_08.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_cong_fun_11.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_cong_fun_14.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_dosi_fun_02.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_dosi_fun_05.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_cong_fun_05.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_cong_fun_11.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_flip_exert_05.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_flip_exert_06.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_flip_fun_06.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_flip_fun_09.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_flip_fun_10.mp3"
		"wave"			"vo/taunts/pyro/pyro_taunt_flip_int_05.mp3"
-		"wave"			"vo/taunts/pyro/pyro_highfive_success03.mp3"
+		"wave"			"vo/taunts/pyro_highfive_success03.mp3"
	}
}
``` 

Note: For anyone wanting to fix this on their client, console warnings on map load will still persist (except on local servers) as [soundscripts are loaded on the server only](https://developer.valvesoftware.com/wiki/Soundscripts#:~:text=Soundscripts%20are%20loaded%20on%20the%20server%20only). However, playing the sound entry would play the fixed path as expected (as can be verified by playing the taunt or inputting `playgamesound Taunt.skating_scorcher_trick` in the console).

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed missing sound for the Taunt: The Skating Scorcher 

This needs to be retested.

**Comment by flurbury** [comment]
This fix was successfully applied in the July 18, 2024 update.
