### ISSUE TITLE
[Request] TF2 Backpack max size increase to 5000 slots (100 total pages)

### ISSUE THREAD

**Issue by JAHMCR** [ValveSoftware/Source-1-Games#5991]
As a TF2 item collector with very ambitious goals my backpack is now almost full of items (without counting trade currency items like keys and metal), really need more space in my inventory.

I think 5000 slots would be nice for at least 2-5 more years of new TF2 content, there is just enough space at the bottom of the inventory to fit the extra pages, that even looks like you (Valve) did that on purpose for adding exactly 2 more rows some day in the future.

There is no need to modify the UI structure, probably just a matter of changing some properties to increase the max slots from 3000 to 5000.

Hope you implement this soon, thanks!

**Comment by kisak-valve** [comment]
Hello @JAHMCR, this request is already being tracked at #3464. Closing in favor of the older issue report.

**Comment by SuperIsakSwahn** [comment]
> Hello [@JAHMCR](https://github.com/JAHMCR), this request is already being tracked at [#3464](https://github.com/ValveSoftware/Source-1-Games/issues/3464). Closing in favor of the older issue report.

That one was for increasing to 4000 and got closed after it happened though
