### ISSUE TITLE
[TF2] F2P account

### ISSUE THREAD

**Issue by perkoz323** [ValveSoftware/Source-1-Games#5996]
Please add again posibility for F2P to use chat and voice commands

**Comment by kisak-valve** [comment]
Hello @perkoz323, this issue is already being tracked at #4177. Closing as a duplicate.

**Comment by perkoz323** [comment]
> Hello @perkoz323, this issue is already being tracked at #4177. Closing as a duplicate.

Okay it is being tracked but did you do  or any developer with this anything?
