### ISSUE TITLE
[TF2] Restoring the replay function *feature request*

### ISSUE THREAD

**Issue by perkoz323** [ValveSoftware/Source-1-Games#5998]
I have an idea for a useful feature in combating bots, namely the restoration of replay functions that will be saved and stored on Valve servers for up to 14 days, and users will have the ability to review the replay to verify if a particular person is not cheating.
EDIT: Requirements to use this feature: minimum of 200 hours played, account exists for longer than 30 days, account is not an F2P account. 
If you have better ideas, please write them in the comments. Developers, do something about the bot crisis because the game is unplayable when I enter the game in casual mode, I am immediately get kicked out by bots.

**Comment by JoriKos** [comment]
IIRC suggestions about bots are on #3477 and restoring replay is on #4724

**Comment by perkoz323** [comment]
> IIRC suggestions about bots are on #3477 and restoring replay is on #4724

Still they do nothing with it

**Comment by kisak-valve** [comment]
Hello @perkoz323, as @JoriKos noted, these topics are already being tracked at #4724 and #3477.

Closing as a duplicate.
