### ISSUE TITLE
[TF2] Streaming mode *Feature request*

### ISSUE THREAD

**Issue by perkoz323** [ValveSoftware/Source-1-Games#5999]
Please add a streaming mode to TF2 that would change the following things: hide chat, blur avatars, and not display full usernames.

**Comment by NULLYUKI** [comment]
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/4212

**Comment by kisak-valve** [comment]
Hello @perkoz323, as @NULLYUKI noted, this request is already being tracked at #4212.

Closing as a duplicate.
