### ISSUE TITLE
Icons are not loading

### ISSUE THREAD

**Issue by OHsit** [ValveSoftware/Source-1-Games#6000]
![20240513073612_1](https://github.com/ValveSoftware/Source-1-Games/assets/79926004/250af9e1-43dc-4728-b7e4-86a320cdbcd8)
Icons for items are not loading

**Comment by NULLYUKI** [comment]
Can you check if this issue occurs with the default HUD?

**Comment by Tiagoquix** [comment]
Make sure the value of the ConVar `tf_time_loading_item_panels` is set to `0.0005` (the default value).
