### ISSUE TITLE
[TF2] Game crashes on "retrieveing Server Info"

### ISSUE THREAD

**Issue by AMcilraith** [ValveSoftware/Source-1-Games#6003]
Exactly as described

``pid 23339 != 23338, skipping destruction (fork without exec?)
/home/addi/.local/share/Steam/steamapps/common/Team Fortress 2/tf.sh: line 83: 23156 Bus error               (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
``
on
``Fedora 40 RHEL``

**Comment by kisak-valve** [comment]
Hello @AMcilraith, this issue is already being tracked at #5986. Closing as a duplicate.
