### ISSUE TITLE
MetaMod:Source will not load on a Linux DoD:s Listen Server. (Fix included)

### ISSUE THREAD

**Issue by dodbits** [ValveSoftware/Source-1-Games#6005]
### Issue:
MetaMod:Source will not load on a Linux Day of Defeat Source Listen Server. 

MetaMod:Source does load on a Windows Listen server.

The main aim here was RCBot2 (a MetaMod bot plugin for day of defeat:source) requires MetaMod:Source to load.

On a windows listen server, MetaMod:Source and RCBot2 loads fine.

This issue was tested on multiple Linux OS distros, the results are the same and the findings indicate it is only related to the Linux Day of Defeat Source/bin folder files missing two files. 
libvstdlib_srv.so and libtier0_srv.so.

The issue is also present in other (Linux only) source 1 games, CS:S, HL2:DM and TF2.
The RCBot2 MetaMod plugin also supports bots for HL2:DM and TF2.

This usage of running MetaMod:source on a Listen server is not common, however RCBot2 for dod:s and HL2:DM it is the only way to add bots to the game.

The issue results in Linux (native) dod:s, HL2:DM and TF2 cannot load MetaMod:Source on a Linux listen server where a windows listen server, you can.

### To reproduce this issue.
1. Use Linux only not windows.
2. Install MetaMod:Source (Linux any version stable or development) to the Day of Defeat Source/dod/addons folder as normal.
3. Run the game with the “-insecure” launch option.
4. Run a map.
5. Type in console **“meta version”** and **do include the double quotations**, as this command has a space.

Result in console: 
```
] "meta version"
Unknown command: meta
```

Now add two files **libtier0_srv.so** and **libvstdlib_srv.so** to the “Day of Defeat Source/bin” folder.

The files can be obtained from a steamcmd dods install “steamcmd/Your_game_folder/bin/” folder or another game folders like the free HL2 mod “Synergy” in the “Synergy/bin/” folder.

Run through steps 1-5 again.

Result in console:
```
] "meta version"
    Metamod:Source version 2.0.0-dev+1289
 Metamod:Source Version Information
    Plugin interface version: 16:14
    Loaded As: Valve Server Plugin
    SourceHook version: 5:5
    Compiled on: Apr  6 2024 09:38:22
    Built from: https://github.com/alliedmodders/metamod-source/commit/b4aa055
    Build ID: 1289:b4aa055
    http://www.metamodsource.net/

```

MetaMod:Source is loaded, other plugins like RCBot2 and Sourcemod will now also work normally as they do on a Windows listen server.

### Findings from testing:
The first hint as to why MetaMod:Source was not loading on Linux was found in the developer console…

```
failed to dlopen /home/kim/.local/share/Steam/steamapps/common/Day of Defeat Source/dod/addons/metamod/bin/linux64/server.so error=/home/kim/.local/share/Steam/steamapps/common/Day of Defeat Source/dod/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
Unable to load plugin "addons/metamod/bin/linux64/server"
```

But that is often an error you can ignore.

Going to the metamod-fatal.log file (Day of Defeat Source/dod/addons/metamod/bin/) you get another hint with this entry…
`Detected engine 14 but could not load: libvstdlib_srv.so: cannot open shared object file: No such file or directory`

That file is not in the Day of Defeat Source directory.
However, you can find that file in the steamcmd server install. 

It’s in “steamcmd/Your_game_folder/bin/” folder along with 24 others that are not in the Day of Defeat Source/bin folder.

### Solution:
Adding **libvstdlib_srv.so** to the Day of Defeat Source/bin folder doesn’t fix the issue alone.

Adding one more file **libtier0_srv.so** MetaMod:Source will now load, the plugins RCBot2 and Sourcemod will also load and operate as it does on a windows Listen Server.

After these files are added, MetaMod:Source loads. The RCBot2 and SourceMod plugins also load and function correctly as they do on a Windows listen server. 

### Other notes (Linux Native) Mods and these two files.
Another note is the free HL2 mod Synergy has these two “missing” files in the “Synergy/bin” folder. These also work OK.

Left 4 dead 2 also has these files in the “Left 4 Dead 2/bin/” folder _but using libvstdlib_srv.so and libtier0_srv.so from there results in a crash._

**Comment by kisak-valve** [comment]
Hello @dodbits, these files are in the Counter-Strike: Source Dedicated Server Linux depot 232336, Half-Life 2: Deathmatch Dedicated Server Linux depot 232376, and Team Fortress 2 Dedicated Server Linux depot 232256. It reads like a mod issue with the mod not being tested with a Linux native listen server configuration.

Report this issue to the mod devs.

**Comment by dodbits** [comment]
> Hello @dodbits, these files are in the Counter-Strike: Source Dedicated Server Linux depot 232336, Half-Life 2: Deathmatch Dedicated Server Linux depot 232376, and Team Fortress 2 Dedicated Server Linux depot 232256. It reads like a mod issue with the mod not being tested with a Linux native listen server configuration.
> 
> Report this issue to the mod devs.

I don't think you understood fully. This is a Valve software issue.

Firstly, **This isn't about dedicated servers at all**.  
1. The only mention of them is that two missing files can be obtained from dedicated server files and fix the two missing files in the Linux ...client.
2. This is about Linux client files and running a local listenserver with plugins.

The files that make metamod and other plugins work in LINUX client files (like left 4 dead 2) are not in the client file set of the games reported.

The two "missing" files are libtier0_srv.so and libvstdlib_srv.so

Those two files are in  Depot 554 for [Left 4 Dead 2](https://steamdb.info/app/550/depots/)
Because libtier0_srv.so and libvstdlib_srv.so are in left 4 dead 2 /bin folder... you can load plugins like metamod:source.
They are also a common file in dedicated server "game"/bin folder

The libtier0_srv.so and libvstdlib_srv.so files are not in...  "game"/bin folder
Depot 232293 for [Day of Defeat: Source](https://steamdb.info/app/300/depots/)  
Depot 232373 for [Half-Life 2: Deathmatch](https://steamdb.info/app/320/depots/)
Depot 232333 for [Counter-Strike: Source](https://steamdb.info/app/240/depots/)
Depot 232253 for [Team Fortress 2](https://steamdb.info/app/440/depots/)  _In that case due to a recent upgrade they should be in bin/linux64/_

However, if  libtier0_srv.so and libvstdlib_srv.so are placed in the above linux client "game"/bin folder plugins now function.

Plugins work in a Left 4 dead 2 Linux client.

Plugins don't work in a dod:s, HL2:DM CSS and TF2 LINUX client because libtier0_srv.so and libvstdlib_srv.so files are missing.

The WINDOWS client files (dods, HL:DM, CSS and TF2) have the capability to run plugins.

The LINUX client files (dods, HL:DM, CSS and TF2) cannot run plugins.

Its not a mod related issue.
There are missing files in the Linux client files (bin folder) as my tests prove its not the mod files.

Running the MetaMod:Source plugin on a LINUX CLIENT "listen server" (insecure mode locally) is a big deal for DoD:s and HL2:DM. It's the ONLY way to have offline bots.

I have a set of files that can be added and tested on Depot 232293 for [Day of Defeat: Source] 
https://www.dodbits.com/downloads/bots/rcbot/rcbot2_dods_linux_guide.zip

You will note the two files libtier0_srv.so and libvstdlib_srv.so in the download... Day of Defeat Source/bin/

Without the two missing files, metamod:source will not load on a Linux client as it can on a windows client or a Left 4 dead Linux or windows client.

Please reconsider closing this issue, it would also affect the Steamdeck I would say?

Thanks.
