### ISSUE TITLE
[TF2] gameui_ file is outdated in other languages

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#6009]
The `gameui_` file is outdated in non-English languages, causing some strings, such as `GameUI_vote_failed_vote_spam_min`, to be outdated.
For example, in Spanish it says: **Has solicitado una votación recientemente y no puedes solicitar otra hasta dentro de %s1 minuto.**
English: You called a vote recently and can not call another for %s1 minute.
And this happens in Portuguese, French and so on.

However, the updated string in `gameui_english` file is displayed as, "You cannot call a vote for %s1 minute."

This is a problem, because when playing in non-English languages and when trying to kick a player in a game you have recently joined, the previously mentioned outdated message will appear, which can lead to confusion.

**Comment by JoriKos** [comment]
Seems like they're missing from the Crowdin page in general, which would be the actual issue here rather than being outdated (as a lot of strings can be outdated/missing)

**Comment by Ashetf2** [comment]
The localized gameui_ files have been updated in the recent patch

**Comment by kisak-valve** [comment]
Closing per the last comment.
