### ISSUE TITLE
Game crashes on second match / connection

### ISSUE THREAD

**Issue by Repurify** [ValveSoftware/Source-1-Games#6021]
i know this has already been said but it still hasn't been fixed. this has been happening since the game updated to 64x. please fix it, I have to restart the game after every match, it just crashes. it really annoying

**Comment by JoriKos** [comment]
Opening a duplicate issue is useless because they'll just be closed and not looked at.

**Comment by kisak-valve** [comment]
Hello @Repurify, this issue is already being tracked at #5885. Closing as a duplicate.
