### ISSUE TITLE
TF2 is unplayable multiple times a week with bots

### ISSUE THREAD

**Issue by Theslutch** [ValveSoftware/Source-1-Games#6025]
We aren’t kidding when we say the game itself is unable to be played most of the time. I try to hop on casual and truly cannot find a game with real people. Tf2 might as well not be running anymore. I have to beg the chat to prove they are real if I happen to find a server with people, only on weekends or days many people might play. Other than that, like on week mornings, game is unplayable, servers are over half sniper bots. 

What bigger issue could you want fixed than this?

**Comment by kisak-valve** [comment]
Hello @Theslutch, this issue is already being tracked at #3477.

Closing in favor of the older issue report.
