### ISSUE TITLE
[TF2] [Windows 11 x64] Game freezes and crashes on DXVK on AMD Radeon Drivers Version 24.5.1

### ISSUE THREAD

**Issue by DS-00** [ValveSoftware/Source-1-Games#6026]
Summary of the issue:
- When you're just about to joining a game, if you enable DXVK using the -vulkan parameter on the launch options, the game will freeze and then crash, and you are forced to do a driver reboot (Windows + Ctrl + Shift + B).

CPU: AMD Ryzen 5 5600X
GPU: AMD Radeon RX 7800 XT
OS: Windows 11 Pro 23H2

Additional information:
- This issue happened after the 24.5.1 update. It was working properly on the 24.4.1 driver. I've also sent a crash report to AMD in addition of reporting the issue here;
- The freezing and subsequent crashing typically happens just at the end of "Sending client info", when someone's about to join the game;
- In the rare times where it does not freeze and crash in that moment, there are obvious visual glitches, and the game will eventually freeze and crash if you play for around a minute at best;
- This issue does not seem to be on AMD's Vulkan Implementation itself (tested Vulkan using the Steel Nomad 3DMark Benchmark and choose the Vulkan option, and there were no issues) nor it does affect other Valve Games (tested with -vulkan parameter on launch option on Left 4 Dead 2 at it's working fine after the usual rough initial launch when it's performing shader compiling);
- If the -vulkan parameter is removed and you run the game on DX9, the game is able to run without freezing and crashing or with visual glitches, so disabling -vulkan can be a temporary fix for this issue. Rolling back to the previous version may also temporarily fix the issue.

**Comment by bullsquid11** [comment]
same here. 
Ryzen 7 7840HS + LPDDR5 6400
Radeon 780M
Windows 11 24H2

24.4.1 works, 
24.5.1 is crash during join the game

**Comment by DS-00** [comment]
I downgraded my drivers to version 24.4.1 and i can run the game with the -vulkan parameter on without any issues, so it much be a issue with the driver version 24.5.1. I'll stay on this driver version and wait for the 24.6.1 version and see if the issues remain.

**Comment by DS-00** [comment]
AMD Driver 24.6.1 has been released. Upgrading to the newest driver and test it to check if issue persists.

**Comment by DS-00** [comment]
Tested the game on the new driver version remotely. Seems that the crashing issue has been fixed. Will test it further to make sure it's in fact fixed. Will also wait for other people to confirm before closing.

**Comment by DS-00** [comment]
@bullsquid11 if you can, could you try tf2 in this new driver version?

**Comment by bullsquid11** [comment]
tested on 24.6.1.
now it works well!

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
