### ISSUE TITLE
[TF2] Medic loses ÜberCharge early when activated while already being ÜberCharged by another medic

### ISSUE THREAD

**Issue by doclic** [ValveSoftware/Source-1-Games#6029]
[video.webm](https://github.com/ValveSoftware/Source-1-Games/assets/30270428/918a96f7-5eba-4a22-87d5-a1c89b04b3e8)

As seen in the video, when the bot activates ÜberCharge while flashing from me disconnecting my beam, it stops flashing, but it still loses ÜberCharge at the same my charge ended, instead of when the its charge ended.

Tested on:
Valve casual servers
Self-hosted Arch Linux dedicated server
Arch Linux client's integrated server (where the video was taken)

**Comment by JoriKos** [comment]
Duplicate of #5993

**Comment by doclic** [comment]
> Duplicate of #5993

Woops, thanks for noticing.
