### ISSUE TITLE
HL2: Scene loading and glitches -> nearly unplayable

### ISSUE THREAD

**Issue by dromer** [ValveSoftware/Source-1-Games#603]
Loading, the game itself, save-games and new scenes takes nearly 5-10 minutes before being ready.

When running, the game regularly glitches so hard (audio and video) that it's basically unplayable.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2001 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8-6.dmz.1-liquorix-686
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Fluxbox
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  NVIDIA Corporation GeForce 8600M GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.30
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x407
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1920 x 2130
Primary Display Size: 13.03" x 8.15"  (15.35" diag)
                                        33.1cm x 20.7cm  (39.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 256 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: SigmaTel STAC9228

Memory:
    RAM:  4050 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  103129 Mb
    Largest Free Hard Disk Block:  5686 Mb

Installed software:

Recent Failure Reports:
    Fri May  3 08:58:32 2013 GMT: file ''/tmp/dumps/assert_20130503105811_1.dmp'', upload yes: ''CrashID=bp-9cbc91e8-f4f6-4b8c-b8f2-cbc272130503''
    Fri May  3 08:58:33 2013 GMT: file ''/tmp/dumps/crash_20130503105750_1.dmp'', upload yes: ''CrashID=bp-dec9cd3f-2758-4a02-ae3f-2fd2b2130503''
    Fri May  3 09:28:08 2013 GMT: file ''/tmp/dumps/assert_20130503112733_1.dmp'', upload yes: ''CrashID=bp-2528c082-0d9e-4274-b44e-d0bcb2130503''
    Fri May  3 10:47:11 2013 GMT: file ''/tmp/dumps/assert_20130503124654_1.dmp'', upload yes: ''CrashID=bp-fd7f5c99-9ee5-46e7-a293-e18892130503''
    Fri May  3 21:37:46 2013 GMT: file ''/tmp/dumps/assert_20130503233736_1.dmp'', upload yes: ''CrashID=bp-5efa14e4-ed3a-4d16-a9ec-1a9952130503''
    Fri May  3 21:39:43 2013 GMT: file ''/tmp/dumps/assert_20130503233934_1.dmp'', upload yes: ''CrashID=bp-5f23a84a-8027-4b69-9434-512542130503''
    Fri May  3 21:54:23 2013 GMT: file ''/tmp/dumps/assert_20130503235421_1.dmp'', upload no: ''HTTP response code said error''
    Sat May  4 09:30:48 2013 GMT: file ''/tmp/dumps/assert_20130504113037_1.dmp'', upload yes: ''CrashID=bp-fe27b817-65c7-42a6-8d1e-039b52130504''
    Sat May  4 11:55:20 2013 GMT: file ''/tmp/dumps/assert_20130504135456_1.dmp'', upload yes: ''CrashID=bp-35594ac3-e045-4439-a4a6-f16b62130504''
    Thu May  9 11:18:56 2013 GMT: file ''/tmp/dumps/assert_20130509131843_1.dmp'', upload yes: ''CrashID=bp-c531cf66-0e25-4aca-87a7-5feaf2130509''
    Fri May 10 06:49:51 2013 GMT: file ''/tmp/dumps/assert_20130510084950_1.dmp'', upload no: ''HTTP response code said error''
    Fri May 10 06:55:50 2013 GMT: file ''/tmp/dumps/assert_20130510085549_1.dmp'', upload no: ''HTTP response code said error''
    Sat May 11 09:10:30 2013 GMT: file ''/tmp/dumps/assert_20130511110954_1.dmp'', upload yes: ''CrashID=bp-efb00cbd-2676-4ea0-abf6-df5292130511''
    Sat May 11 09:11:54 2013 GMT: file ''/tmp/dumps/assert_20130511111130_2.dmp'', upload yes: ''CrashID=bp-262ae98d-d9d4-45d8-9b36-0a3862130511''

**Comment by kisak-valve** [comment]
Closing as there is nothing actionable in this issue report. Your best bet is lower your video settings as far as possible, but no promises this will resolve the performance disparity.
