### ISSUE TITLE
[HL2:DM & HLDM:S] add the "fix player model change" files to HL2DM & HLDMS

### ISSUE THREAD

**Issue by Wadmodder** [ValveSoftware/Source-1-Games#6036]
It seems that nobody at Valve is interested in fixing the bug that prevents players from changing the player model for Half-Life 2 Deathmatch and Half-Life Deathmatch Source in-house, so it would be nice to implement these bug fixes into a future update.

https://gamebanana.com/mods/35036
https://gamebanana.com/mods/346145

Hopefully these can be implemented as fixed so that way players of both HL2DM and HLDMS can changed player models in-game.

**Comment by kisak-valve** [comment]
Hello @Wadmodder, this issue is already being tracked at #1427.

Closing as a duplicate.
