### ISSUE TITLE
[TF2] Put the Valve servers in "Permanent Maintenance Mode"

### ISSUE THREAD

**Issue by Wadmodder** [ValveSoftware/Source-1-Games#6049]
Now the Team Fortress 2 casual mode is now riddled with bot accounts who are now using DDos attacks, and even illegal Swatting tactics against any Steam user who dares to take criticism against them. In otherwords, the bot accounts are being directly linked to Terrorism, Money Laundering, Security Fraud and even Child Pornography.

I wish for Valve to temperately close both Casual and Competitive modes in TF2 and put them into a "Permanent Maintenance Mode", to fix all the Valve Anti-Cheat security issues and to fix all the security issues in TF2 itself.

**Comment by ethanholt1** [comment]
They aren't under maintenance. They still function fine, it's just they are being abused. Putting them in maintenance mode would be overkill, and would likely cause even more community outcry than there currently is. 
I have been able to find functional matches without bots (although it is quite rare.)

**Comment by kisak-valve** [comment]
This is a request for an anti-feature.
