### ISSUE TITLE
[L4D2] Suggestion: Increase a "rate" CVARs limits

### ISSUE THREAD

**Issue by V3nilla** [ValveSoftware/Source-1-Games#6054]
On many unofficial(custom), competitive servers, the servers tickrate is 100, as well as the servers rates have been changed to 100000 using the plugin, but on the client side they are still limited to 30000, which affects on hitreg and synchronization between the client and the server. Please increase the "sv_minrate", "sv_maxrate", "net_splitpacket_maxrate" and "rate" limits on the client's side

Example: T1 100 Tick, 100k rate server. Here is a screenshot:
![image](https://github.com/ValveSoftware/Source-1-Games/assets/48512277/c2126bc0-539e-4482-bee4-4af0f2855d0a)
Rates are limited on client-side to 30k

**Comment by kisak-valve** [comment]
Hello @V3nilla, this request is already being tracked at #1907. Closing as a duplicate.
