### ISSUE TITLE
Camera Shy achievement is not coming.

### ISSUE THREAD

**Issue by yenilmezwoltran** [ValveSoftware/Source-1-Games#6064]
![IMG_20240609_131106](https://github.com/ValveSoftware/Source-1-Games/assets/149178281/879705bb-abf6-4888-bc79-b1708b89c7a0)
I have only one achievement left in the game. Even though I tried 10 times, shy camera success does not come. What should I do?

**Comment by Tiagoquix** [comment]
Did you destroy all 33 cameras?

**Comment by JoriKos** [comment]
It's possible that you haven't properly destroyed all the cameras, try counting them yourself or 1:1 following a guide on the Steam Community as to verify it's not an issue on your end

**Comment by yenilmezwoltran** [comment]
@JoriKos I broke all 33 cameras and attempted this feat 10 times and I have the video recording.

**Comment by TotallyARussian** [comment]
i think i remember hearing somewhere that you actually have to listen to each glados "broken camera" line from start to finish for each individual camera, and you gotta make sure nothing cuts off those lines

**Comment by JoriKos** [comment]
> i think i remember hearing somewhere that you actually have to listen to each glados "broken camera" line from start to finish for each individual camera, and you gotta make sure nothing cuts off those lines

Yeah I read the same thing and remember doing this when I did the achievement

**Comment by Tiagoquix** [comment]
> you actually have to listen to each glados "broken camera" line

If that's the case, this video may help you: https://youtu.be/niYKpbICJus

**Comment by yenilmezwoltran** [comment]
@TotallyARussian @JoriKos @Tiagoquix 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/149178281/3e0c0cb9-0198-4031-89ef-926db0f1fa83)
It worked as you said, thank you all very much, my success has come thanks to your help.
