### ISSUE TITLE
[TF2] Natascha's slowdown is bypassed when healed

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#6069]
Like title says, when getting healed, the Natascha's slowdown does not get applied at all. Though seeing as how annoying slowdowns are in TF2, not sure anyone would mind it if this didn't get fixed.

**Comment by JoriKos** [comment]
This is apparently intentional. Though questionable, I do not wish to see this removed if it was intentional

**Comment by Tiagoquix** [comment]
How do you know this is intentional?

**Comment by JoriKos** [comment]
game/shared/tf/tf_weaponbase.cpp at line 4992
