### ISSUE TITLE
counter strike sourse/automatic weapons stop shooting.

### ISSUE THREAD

**Issue by spawnsalot** [ValveSoftware/Source-1-Games#6075]
I have this problem. When I'm shooting at someone with an automatic weapon it will stop shooting, but only when the crosshair are on the guy I'm shooting at.

**Comment by NULLYUKI** [comment]
What mouse do you have? Might be an hardware issue.

**Comment by spawnsalot** [comment]
I have a "Blue tooth G602" and a 'USB G910' keyboard, I use them with the G-hub app. I'm not happy with them but every new mouse I buy is worse.

**Comment by spawnsalot** [comment]
I found 2 similar post in steam help from 2016 and 2017 both were unresolved.

**Comment by NULLYUKI** [comment]
> I found 2 similar post in steam help from 2016 and 2017 both were unresolved.

Can you please send the posts that you have found and check if the issue also occurs when using a wired connected mouse.

**Comment by ethanholt1** [comment]
There are several factors that could cause this. The server you're playing on may have some sort of anti-cheat in place, or some other plugin causing this. Can you see if this issue still occurs on a listen server (main menu > create server)?

**Comment by spawnsalot** [comment]
I have set the enabled the "wait for vertical sink" and sat the filtering mode to 'anisotropic x2' tropic and set the antialiasing to 2xMSAA. It helped a little bit but slowly came back. So I  ordered a new graphics card. When it gets here I'll let you know if it helped. But the problem seems to happen only on the same players. is it possible that they are hacking?

**Comment by spawnsalot** [comment]
Thank you for your time. I am grateful.

**Comment by spawnsalot** [comment]
I have solved this issue. It seems to be an issue with the blue tooth mouse.  After switching to a wired mouse I haven't noticed any stutter in the game.
