### ISSUE TITLE
RIP Mac Support for TF2

### ISSUE THREAD

**Issue by motherofdragons96** [ValveSoftware/Source-1-Games#6076]
News! For those you didn't know, Valve is removing Mac support for Tf2. Hopfully this ends the bot crisis soon, because 32-bit still uses bot compatablility.

Finally Valve did something!

**Comment by NULLYUKI** [comment]
> This is an unproductive and false comment. TF2 hasn't worked on Mac for almost 5 years, this is them simply updating the store pages (of not just TF2, but the other Orange Box games too see [HL2:E2](https://steamdb.info/app/420/history/) and [Portal](https://steamdb.info/app/400/history/)). These are 32-bit apps (with the exception of TF2, but only recently, so it still doesn't have support).

https://github.com/ValveSoftware/Source-1-Games/issues/3477#issuecomment-2164028764

Also this issue does not include a feature request nor does it describe an issue with one of the Source-1-Games

**Comment by kisak-valve** [comment]
Hello @motherofdragons96, this issue is already being tracked at #5625. Closing as a duplicate.

**Comment by wgetJane** [comment]
why do you people insist on using this repo as a forum, there are many other places for this

**Comment by voidplayer** [comment]
if i had to guess is because kisak has valve attached to his name and thats a sweet and uncommon interaction with valve, even if minimal

**Comment by motherofdragons96** [comment]
I may found another reason why we get so many bots. Maybe Casual do not have an anti-cheat at this moment.Sent from my iPhoneOn Jun 13, 2024, at 1:56 AM, voidplayer ***@***.***> wrote:﻿
if i had to guess is because kisak has valve attached to his name and thats a sweet and uncommon interaction with valve, even if minimal
