### ISSUE TITLE
[TF2]cant Queue for casual 

### ISSUE THREAD

**Issue by demopan-gaming** [ValveSoftware/Source-1-Games#6079]
i have this issue recently that evry time i try to queue for casual it just stops after sometime it does not put me in a server and just stops queueing after about 30 seconds

**Comment by NULLYUKI** [comment]
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2820

**Comment by kisak-valve** [comment]
Hello @demopan-gaming, as @NULLYUKI noted, this issue is already being tracked at #2820.

Closing as a duplicate.

**Comment by demopan-gaming** [comment]
why is this not fixed yet ?
