### ISSUE TITLE
[L4D2][Linux] Alpha mapping issue

### ISSUE THREAD

**Issue by pfannkuchengesicht** [ValveSoftware/Source-1-Games#608]
-HW-
AMD Phenom II X4 955(3.2GHz)
2x 4GB DDR3-1333(7-7-7-20) G.Skill RAM
MSI 790FX-GD70
ASUS EAH5870(AMD HD5870, 1GB VRAM)
ASUS Xonar DX

-SW-
Arch linux(3.8.10-1)
Xfce DE
Catalyst 13.4
Xorg 1.13(thanks AMD!)
xrandr 1.4

I have some issues with alpha mapped materials, where as particle effects behind them get corrupted and the transitions from visible to invisible are corrupted as well.
![01](http://cloud.steampowered.com/ugc/559848462399414843/A0944342F6A3616968291AB49606675F54290C8E/)
![02](http://cloud-2.steampowered.com/ugc/559848462399429204/3D6BC8F4F1C216414F35B87B4C7227BDF3202BA3/)
![03](http://cloud-2.steampowered.com/ugc/559848462399437896/232F8526881CD64F120828378F14BA8F04AAD1B0/)
![04](http://cloud.steampowered.com/ugc/559848462399452258/65EC8996F0CDDE542E7485342AB99704921F256D/)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
