### ISSUE TITLE
[Tf2] [x86_64 Vulkan] Game starts stuttering after awhile of playing

### ISSUE THREAD

**Issue by 0CCULTIST** [ValveSoftware/Source-1-Games#6087]
Debian 12.5
Mesa 22.3.6
Ryzen 5000 Series CPU
Navi 23 GPU
After awhile of gameplay (have not timed it, but typically after ~2 full matches of A/D, so maybe ~15-30 minutes) the game will start experiencing massive stuttering issues despite the framerate (as displayed by cl_showfps 1) seemingly not reflecting what's appearing on screen.
The stuttering gets worse when moving your mouse/turning the camera. When not moving your mouse, the gameplay is smoother, but still noticeably hitches.
This issue does not occur on OpenGL. 
As the in-game FPS display seems to believe nothing is wrong I made sure it wasn't an issue with my Xorg session. Turning off "TearFree" or disabling "VRR" doesn't via Xrandr help, and I'm not using a compositor so that isn't the issue.
Tested without any launch options and I have no mods installed. 

Will edit this post to display the terminal output if there's anything of note.

**Comment by NULLYUKI** [comment]
Possible duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/5767 ?

**Comment by 0CCULTIST** [comment]
> Possible duplicate of #5767 ?

Appears so. Closing as dupe.
