### ISSUE TITLE
Last Portal 2 patch

### ISSUE THREAD

**Issue by alph312a** [ValveSoftware/Source-1-Games#6093]
the last patch of the game make vscript making for coop impossible simple commands like "sv_cheats 1", "sv_cheats 0", "ent_setpos", "ent_setang", "ent_setname", "ent_remove", "ent_remove_all", "mat_ambient_light_r/g/b ", "SendToConsole", "say" now not work by use mapspawn.nut file (as host).
these basic lines not work:
EntFire("example_trigger", "AddOutput", "OnTrigger @ command:command:sv_cheats 1::");
SendToConsole("say blah")
EntFire("trigger1", "AddOutput", "OnStartTouch @ command:command:say blah")
SendToConsole("ent_remove_all block_boxes");
EntFire("trigger1", "AddOutput", "OnStartTouch @ command:command:ent_remove_all block_boxes");
(output was add but when trigger was activated its not running the output)
error on console
FCVAR_SERVER_CAN_EXECUTE prevented server running command:sv_cheats

some elements has a standard name like "trigger_once" and so i cant remove then or set some different pos or add outputs. by use script line like so:
SendToConsole("ent_setpos 23 -2 -4 60");
EntFire("@ command:command:ent_setpos 23 -2 -4 60");
these commands work fine:
EntFire("prop_name1", "enable", 1)
EntFire("prop_name1", "setlocalorigin", "x y z");

![errorsaa](https://github.com/ValveSoftware/Source-1-Games/assets/36051807/87bb88f2-ce73-44eb-ba8a-cc2be4701ed5)

**Comment by kisak-valve** [comment]
Hello @alph312a, this issue is already being tracked at https://github.com/ValveSoftware/portal2/issues/436. Closing as a duplicate.
