### ISSUE TITLE
#fixtf2

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [ValveSoftware/Source-1-Games#6102]
For the past 5+ years, Team Fortress 2 has been the victim of bots that join servers to spam extreme hate speech, use aim-bot to headshot anyone in sight, and even kick real players!

**Comment by NULLYUKI** [comment]
Issue is being already tracked at https://github.com/ValveSoftware/Source-1-Games/issues/3477

**Comment by kisak-valve** [comment]
Hello @GuestSneezeOSDev, as @NULLYUKI noted, this issue is already being tracked at #3477.

Closing as a duplicate.
