### ISSUE TITLE
[L4D2] [Linux] Survivors are silent

### ISSUE THREAD

**Issue by drakon64** [ValveSoftware/Source-1-Games#6103]
When running Left 4 Dead 2 on Linux, the Survivors have no dialogue. Subtitles do not show them talking either.

Infected 'talk' as normal.

I have reproduced this with all Workshop add-ons disabled.

This does not occur when running the game in Proton Experimental.

OS: NixOS 24.05

**Comment by NULLYUKI** [comment]
Possible duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/3263 ?

**Comment by drakon64** [comment]
Closing as duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/3263

**Comment by NULLYUKI** [comment]
You can share your own provided information to the other issue, as you shared on which Linux distribution it occurs for you.
