### ISSUE TITLE
Error Starting Counter Strike 2 from Steam

### ISSUE THREAD

**Issue by ravirajbasis** [ValveSoftware/Source-1-Games#6117]
Hi

Visual C++ Runtime Error pops-up when i try to run Counter Strike2(see Screen shot below): 
 
![Screenshot_2024-06-29_08-20-54](https://github.com/ValveSoftware/Source-1-Games/assets/17876388/41add12d-f58e-4bb7-9a04-80f0143c1b6a)
Updated to Legacy CS Go from beta option in Steam, but running it also throws error pop-up as shown in screen shot below: 
![Screenshot_2024-07-01_11-39-47](https://github.com/ValveSoftware/Source-1-Games/assets/17876388/6e3d23c9-869d-4641-af83-f1f868f2ad38)
 Tried installing VC++ redistribution for x86 & x64, but to no avail.

Web-search does not yield any solution for this. How to fix it?

My Specs:
OS: FreeBSD 14.1 (XFCE4), 500 GB Hard Drive, 4 GB RAM
Graphics Card: Intel

Thanks 
rraj

**Comment by kisak-valve** [comment]
Hello @ravirajbasis, running the Windows variant of Steam (in general) and this game with wine is not supported. If you want to pursue this issue, then report it to the maintainers of the relevant compatibility tool.
