### ISSUE TITLE
[TF2] [Feature Request] MvM: TF_MVM_INVADERS_TEAM_SIZE should be raised above 22 

### ISSUE THREAD

**Issue by StardustSpie** [ValveSoftware/Source-1-Games#6122]
As with the update that added 100 player servers, MvM is left behind and still only allows up to 22 bots at once. If this limit (currently) exceeds, the bots are "queued" and will immediately spawn after the next bot dies which may cause unwanted behavior. It would be nice if this restriction could be lifted to higher then 22 players on servers that run "maxplayers 100". This restriction is quite strange, because if an MvM server is running 100 players, and robots from the BLU team are set to the RED team (with help from VScript to make them function) you can go above 22 active bots. 

I would also suggest a cvar to control this limit, perhaps "tf_mvm_robot_max_team_size". This feature would be especially helpful for community servers that run community gamemodes such as x10 bots or whatever and would make running those servers much easier.

**Comment by kisak-valve** [comment]
Hello @StardustSpie, this request is already being tracked at #5473. Closing as a duplicate.
