### ISSUE TITLE
[TF2] Missing Hit Feedback

### ISSUE THREAD

**Issue by reDBo0n** [ValveSoftware/Source-1-Games#6123]
I was playing some (Community) MvM.
Randomly hit sounds, damage numbers and the kill feed stops working for a moment.
After some time all the hit sounds are played simultaneously and the kill feed gets instantly populated with all my frags.
Also the Wave result screen with the money collected lags behind

I've recorded some clips of it in action:
[Clip 1](https://youtu.be/kUsiBzuUFnU?si=F3QVsg52pP-v2mHe)
[Clip 2](https://youtu.be/obfrwP-_Bx4?si=qKhowwNAihMFfU3l)

System Specs:
```
Manufacturer: ASUSTeK COMPUTER INC.
Model: PRIME X370-PRO
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 5800X3D 8-Core Processor
Operating System Version:
"Arch Linux" (64 bit)
Kernel Version: 6.9.7-arch1-1
X Server Vendor: The X.Org Foundation
X Server Release: 12401000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20240610.91380
Video Card:
Driver: AMD AMD Radeon RX 5700 (radeonsi, navi10, LLVM 17.0.6, DRM 3.57, 6.9.7-arch1-1)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.1.2-arch1.1
Memory:
RAM: 32007 Mb
```

**Comment by JoriKos** [comment]
This feels like an issue with the community content rather than MvM itself, I've experienced a bug before where the hitsound will only play periodically instead of constantly on a rapid-fire weapon like the Minigun, though this seems tied to the wave ending/victory screen happening.

**Comment by mtxfellen** [comment]
> This feels like an issue with the community content rather than MvM itself

This is correct, the issue described was/is caused by Potato.tf's LateDL SM plugin and is not a bug with the base game.
