### ISSUE TITLE
tf2 crashing on startup

### ISSUE THREAD

**Issue by Andru115** [ValveSoftware/Source-1-Games#6124]
Hello, I have been trying to run tf2 for the last 5 days and it still refuses to work. I have reinstalled directx and vcredist but the issue still presists, I have reinstalled steam 3 times and reset windows 2 times but the game refuses to work, any help?

Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: MS-7C96
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 5600G with Radeon Graphics
CPU Family: 0x19
CPU Model: 0x50
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 3893 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Windows 11 (64 bit)
NTFS: Supported
Crypto Provider Codes: Supported 311 0x0 0x0 0x0
Video Card:
Driver: Parsec Virtual Display Adapter
DirectX Driver Name: aticfx32.dll
Driver Version: 0.45.0.0
DirectX Driver Version: 31.0.12027.9001
Driver Date: 1 25 2024
OpenGL Version: 4.6
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 59 Hz
DirectX Card: AMD Radeon(TM) Graphics
VendorID: 0x1002
DeviceID: 0x1638
Revision: 0xc9
Number of Monitors: 1
Number of Logical Video Cards: 1
No SLI or Crossfire Detected
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.86" x 10.24" (21.46" diag), 47.9cm x 26.0cm (54.5cm diag)
Primary Bus Type Not Detected
Primary VRAM: 0 MB
Supported MSAA Modes: 2x 4x 8x
Sound card:
Audio device: Speakers (2- Realtek(R) Audio)
Memory:
RAM: 6037 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: Undetermined
Total Hard Disk Space Available: 1562436 MB
Largest Free Hard Disk Block: 228393 MB
OS Install Date: Jul 01 2024
Game Controller: None detected
Storage:
Disk serial number hash: 7dec07b0
Number of SSDs: 1
SSD sizes: 256G
Number of HDDs: 3
HDD sizes: 1000G,500G,16G
Number of removable drives: 0

TF2 crashes on startup, it first makes a black screen then exists. I have tried running it with OpenGL, Vulkan, dxlevel 7, dxlevel 8 and dxlevel 9. I also used -autoconfig and -safe but the issue still presists.

Steam Content [log](https://pastebin.com/rG4guWvj)
And content [log](https://pastebin.com/EBzmndkB)

**Comment by NULLYUKI** [comment]
For such help I would recommend using the [Steam discussions](https://steamcommunity.com/app/440/discussions/) instead of creating an issue in this repo, as this is used to track bugs or suggestions regarding Source 1 games.

**Comment by Andru115** [comment]
I have tried to use steam discussions but they were of no use, every single thing i have tried to fix this game hasnt helped, steam support couldnt help and unfortunately steam discussions did'nt help in the slightest

**Comment by JoriKos** [comment]
The title is a bit misleading, as it implies if you reset Windows twice, TF2 won't work anymore. Though you need to be more specific if you want this issue to be of any use.

**Comment by Andru115** [comment]
oh sorry im a bit new to bug reports, I'll add more detail to this report now

**Comment by Andru115** [comment]
The fix was to install a non corrupted version of windows 11
