### ISSUE TITLE
source games on linux don't like capitalized letters in custom content

### ISSUE THREAD

**Issue by felinegirl** [ValveSoftware/Source-1-Games#6125]
For games like tf2's custom huds; custom portal content; or for the most part any thing in the custom folder.
On linux there is an issue of having to go through the files and rename them to all lowercase file names instead, of what most custom content uses, Camel Case. Just a wee bit of an inconvenience. lol

**Comment by kisak-valve** [comment]
Hello @LunaLeTuna, this issue is already being tracked at #607. Closing in favor of the older issue report.
