### ISSUE TITLE
Softlock in HL2:E1

### ISSUE THREAD

**Issue by AverageFree2Play** [ValveSoftware/Source-1-Games#6126]
I was playing through the chapter LowLife, got into the first zombine encounter. I saw the zombine wasn't holding a grenade and when it ran up to the wall, an explosion struck and I can't progress through the chapter.

![image](https://github.com/ValveSoftware/Source-1-Games/assets/124472904/c19cadcd-264a-44fe-8219-cd50c10f849e)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/124472904/b9e3bfe6-a5b8-4ee7-ac34-c3eca41427d9)

![video](https://cdn.discordapp.com/attachments/1004615479912042517/1258037841515253771/2024-07-03_19-32-25.mp4)

**Comment by ljcool2006** [comment]
@AverageFree2Play why did you close this?

**Comment by AverageFree2Play** [comment]
> [@AverageFree2Play](https://github.com/AverageFree2Play) why did you close this?

Well, I resolved it myself by adjusting the difficulty to either normal or hard.
