### ISSUE TITLE
[TF2] [Linux] [Feature Request] Use Noto fonts instead of other free fonts

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#6133]
According to the diff present in https://steamdb.info/patchnotes/14098740/, TF2 is using DejaVu Sans, Fira Sans, and Liberation Mono and Sans on Linux.

I would like to request for the game to use Noto fonts instead. Purely by personal preference.

While DejaVu fonts are the default on GNOME (as far as I am aware), Noto fonts are the default on KDE Plasma, which is the DE used by the Steam Deck.

KDE Plasma is also increasingly becoming a very powerful DE every day, and I imagine that in the future it will become the standard for Linux distributions, replacing GNOME as the primary option.

I believe that, in the long run, Noto fonts will be more up to date, cover more languages, and I also simply find them prettier overall because they also look more like Windows fonts, making the transition from Windows to Linux smoother and simpler.

Noto fonts also provide emoji support and Arabic/Chinese/Japanese/Korean, symbols etc. They are really complete.

Noto fonts are licensed under the [SIL Open Font License](https://en.wikipedia.org/wiki/SIL_Open_Font_License) and the [Apache License](https://en.wikipedia.org/wiki/Apache_License).

Noto fonts website: https://notofonts.github.io/
Additional information on Wikipedia: https://en.wikipedia.org/wiki/Noto_fonts

See also: https://fedoraproject.org/wiki/Changes/DefaultToNotoFonts.

**Comment by JoriKos** [comment]
The real issue is when are we getting font customisation options

**Comment by kisak-valve** [comment]
Hello @Tiagoquix, font aesthetics are at the discretion of the Source 1 game devs and this issue report is closer to a subjective art critique than an actionable issue.

The functional part of your request was already covered by https://github.com/ValveSoftware/Source-1-Games/issues/6058#issuecomment-2155372167.
