### ISSUE TITLE
[HL:DMS] Unlist Half-Life: Deathmatch Source - Half-Life: Source's companion game

### ISSUE THREAD

**Issue by Wadmodder** [ValveSoftware/Source-1-Games#6136]
As part of the Half-Life 25th anniversary update, Valve added four new deathmatch maps and added in three maps , two player models and a couple of sprays from the old Further Data addon CDs. As part of that update Valve unlisted Half-Life: Source by recommending players by the original instead. Yet, that hasn't stop modders trying to fix Half-Life: Source since the SteamPipe update in 2013, with the "Fixed" mod by ModDb user BloodyMuffin being the most famous of the efforts to fix Half-Life 1's broken Source port. The official end-of-life of Half-Life: Source just proves that an outdated software patching law funded by the ESA, SIIA & BSA isn't feasible for Valve for their unmaintained PC games.

But back on topic, Valve forgot to do something during the 25th anniversary update, that was to unlist Half-Life: Source's companion game, that being Half-Life: Deathmatch Source which was the Deathmatch multiplayer mode from Half-Life 1 ported to the Source engine. Like Half-Life: Source this one also suffers from the same bugs introduced in the 2013 SteamPipe update, but with an additional bug where all the entities of the Deathmatch maps are now duplicated. Half-Life: Deathmatch Source also didn't get the four new maps from the 25th anniversary update, the Further Data content, the Gasworks map or even the Recon player model. Heck, even the modding community doesn't even know how to fix it either, nor do they know how the duplication bug works. And that's not all, remember the bugs in Half-Life: Source's campaign being noticeable, well if you play those campaign maps in Half-Life: Deathmatch Source, those entities get duplicated as well. I've learned this after watching Pinsplash's video "THE Worst Way to Play Half-Life", which shows that Half-Life: Deathmatch Source is even more buggy than Half-Life: Source itself.

https://youtu.be/XVa9EjwRiXM?si=9OQe7_iiRLS8Q_xz

In otherwords, why support two different versions of Half-Life 1's Deathmatch multiplayer mode (one on GoldSrc and one on Source) when Valve now considers the original version the definitive version since the 25th anniversary update. Why not just unlist Half-Life Deathmatch Source as well?

**Comment by kisak-valve** [comment]
Hello @Wadmodder, this is a request for an anti-feature and more of a marketing decision which is not open to public debate.
