### ISSUE TITLE
[TF2] Freezecam item model doesn't update position until it is seen

### ISSUE THREAD

**Issue by Lucifixion** [ValveSoftware/Source-1-Games#6138]
The freezecam item panel is hardcoded to set its position to the bottom of the screen - 12, but this only occurs after it has been seen, so the next weapon seen in the killcam will always use the previous weapons panel position.

**Comment by kisak-valve** [comment]
Hello @Lucifixion, this issue is already being tracked at #3997. Closing as a duplicate.
