### ISSUE TITLE
[Linux] Unable to run L4D2 or HL2 suddenly - 1 FPS in main menu

### ISSUE THREAD

**Issue by CBBosman** [ValveSoftware/Source-1-Games#6145]
I thought it was an issue with Codename Cure but then I tried Left4Dead 2 and HL2 - same issue - they run at 1fps. I'm unable to click through menus when it finally loads. It does not crash or freeze totally, but crawls at 1 fps.  I don't have the best hardware, but these games used to never be an issue. All other games are working fine, too. Those running via wine/proton as well, no issues. Only these suddenly became unusable.

HL2 is new install and I ran L4D2 with -autoconfig -default.

I have tried kernels: 6.1.99, 6.6.40 and 6.9.7.
OS: Linux (Artix)
Nvidia Drivers: 555.58.02
vulkaninfo attached...
[vulkaninfo.txt](https://github.com/user-attachments/files/16270529/vulkaninfo.txt)

**Comment by kisak-valve** [comment]
Hello @CBBosman, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by CBBosman** [comment]
[Steam Runtime Diagnostics](https://gist.github.com/CBBosman/adc2af27adc270c041bcd32289bb418a)

**Comment by kisak-valve** [comment]
Thanks, it's fairly clear from the runtime diagnostics that you're missing the video driver's 32 bit userspace libraries in your NVIDIA driver install and Steam along with those games are being forced to render on your CPU with llvmpipe.

**Comment by CBBosman** [comment]
> Thanks, it's fairly clear from the runtime diagnostics that you're missing the video driver's 32 bit userspace libraries in your NVIDIA driver install and Steam along with those games are being forced to render on your CPU with llvmpipe.

Oops! all good now, thanks!
