### ISSUE TITLE
[Portal] Linux beta some levels become impossible

### ISSUE THREAD

**Issue by jim-edwards** [ValveSoftware/Source-1-Games#615]
Twice while trying to play through portal 1 I got the game into a state where parts of the level were not functional any more. This happened on at least 2 different levels. In Test chamber 4, The ball firing device stopped firing balls, I waited 10 minutes for a new ball to show up, but it never did (it was working when the level started). On Test chamber 2 (I think that is the one), where you need to use 2 companion cubes to hold red floor switches to open a door, having both switches pressed would not open the door (running over one of the switches did not help). Restarting each level and it worked correctly.

For the record, I am on Gentoo x64 with ATI graphics drivers 13.4.

**Comment by kisak-valve** [comment]
Hello @jim-edwards, are you still experiencing this issue with an up to date system?

**Comment by jim-edwards** [comment]
Unfortunately, the PC that was showing the problem is now dead and so I am unable to re-test the issue with the latest builds.  I suspect it has been fixed by now, or many people would be complaining anyways.  Especially since it was like 4 years ago, I am sure the behavior has at least changed.
