### ISSUE TITLE
[TF2] Crash on executing custom Engineer bind for Teleporter Exit

### ISSUE THREAD

**Issue by NearNihil** [ValveSoftware/Source-1-Games#6151]
The recent update made me crash to desktop (without a log in the Event Viewer) every time I try to build a teleporter exit with my custom bind setup. It doesn't trigger when I manually execute the commands, nor does it crash when using the Construction PDA, it only crashes with the bind.

My engineer.cfg:
```
alias sentry		"destroy 2 0; build 2 0";
alias dispenser		"destroy 0 0; build 0 0";
alias entrance		"destroy 1 0; build 1 0";
alias exit			"destroy 1 1; build 1 1";
alias setbuildmode	"bind 1 sentry; bind 2 dispenser; bind 3 entrance; bind 4 exit; unbind alt;";
alias exitbuildmode "bind 1 slot1; bind 2 slot2; bind 3 slot3; bind 4 slot4; bind alt +eurekamode;";

alias +eurekamode "slot3; bind 1 eurekagotospawn; bind 2 eurekagototeleexit; unbind mouse4;"
alias -eurekamode "lastinv; bind 1 slot1; bind 2 slot2; bind mouse4 +buildmode;"

alias +buildmode setbuildmode;
alias -buildmode exitbuildmode;

alias eurekagotospawn "eureka_teleport 0"
alias eurekagototeleexit "eureka_teleport 1"

bind alt +eurekamode;
bind mouse4 +buildmode;
```

This worked fine yesterday but stopped working with the latest patch.

**Comment by JoriKos** [comment]
It may have to do with the new update:
"Disallow aliasing any existing convars that are not movement commands"

**Comment by tmob03** [comment]
My own custom bind doesn't crash, and I haven't seen any of my scripts break yet, but I don't understand the purpose of limiting aliases. No reason IMO.

**Comment by JoriKos** [comment]
Agreed, or at least have the reasoning explained, as I'm sure there's a valid reason for it.

Edit: Nvm I'm stupid lol I read the patch note wrong

**Comment by Ashetf2** [comment]
Change the "exit" alias to "exitt" or something else. "Exit" is an already existing cvar. That's why it is causing crashes

**Comment by tmob03** [comment]
Oh, that's what that means by the patch note. Still wouldn't want that ability restricted, cause for example in singleplayer games you can alias autosave and have it do something in a script when it would autosave. Not sure what events tf2 has, but I guess it's so people don't accidentally bork their cvars in a session

**Comment by NULLYUKI** [comment]
Would probably a better solution if they added a cvar that is enabled on default, where the player can enable/disable the alias protection.

**Comment by NearNihil** [comment]
> It may have to do with the new update: "Disallow aliasing any existing convars that are not movement commands"

> Change the "exit" alias to "exitt" or something else. "Exit" is an already existing cvar. That's why it is causing crashes

These two were the clues and solution. "Exit" seems to do the same as "quit". Renamed it to teleporter_exit and it worked as expected.
