### ISSUE TITLE
[TF2] In the Steam Store it shows that TF2 doesn't have Latin American Spanish, but the game already does

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#6154]
![image](https://github.com/user-attachments/assets/57229b8a-f15e-4039-8888-89fe1ea05242)
![image](https://github.com/user-attachments/assets/cc26e475-99f1-497c-a73c-c3d99beb048a)

**Comment by JoriKos** [comment]
https://steamdb.info/app/440/history/?changeid=24463927 Should be fixed now

**Comment by gaelcoral** [comment]
Nice!
