### ISSUE TITLE
[TF2] Using a steam client from last year (June 15th, 2023) no longer allows me to load maps

### ISSUE THREAD

**Issue by Touhou2006** [ValveSoftware/Source-1-Games#6158]
Hi, I recently got the new tf2 update and I can no longer load any maps.

Loading any map would result in an instant crash.

However loading maps on games like Counter-Strike: Source still work.

Whats up? What changed?

**Comment by velsignetsjel** [comment]
yeah, same problem

**Comment by Tiagoquix** [comment]
Out of curiosity, why are you using an outdated version of the Steam Client?

**Comment by velsignetsjel** [comment]
> Out of curiosity, why are you using an outdated version of the Steam Client?

i'm using it because i have low-end pc, it's faster than the current version of steam and it eats less memory

**Comment by NULLYUKI** [comment]
What are the specs and OS of your PC?

**Comment by kisak-valve** [comment]
Hello @Touhou2006, outdated versions of the Steam client can't be sanely supported.

**Comment by Touhou2006** [comment]
> Out of curiosity, why are you using an outdated version of the Steam Client?

Because the UI is just better thats why

**Comment by Touhou2006** [comment]
> Hello @Touhou2006, outdated versions of the Steam client can't be sanely supported.

I see
