### ISSUE TITLE
[TF2] add missing blutsauger killicon

### ISSUE THREAD

**Issue by NenorocitulDeNenorocit** [ValveSoftware/Source-1-Games#6160]
someone found this icon in an old build of tf2 prior to the first pyro update

it was supposed to be used with the blutsauger if it had used that custom syringe model for it in the game

i guess it ended up being drawn over by the axtinguisher killicon in the pyro update so it would need to be re-added to the killicon vtf first

![TF2-Dneg_blutsauger](https://github.com/user-attachments/assets/3fe73f27-8ecf-448e-b03e-cc2ff7949429)
![TF2-D_blutsauger](https://github.com/user-attachments/assets/fba52afd-b800-46d9-84c6-3bdf3705baf7)

**Comment by JoriKos** [comment]
This would only make sense if they added the unused model too

**Comment by kisak-valve** [comment]
Hello @NenorocitulDeNenorocit, this reads like it should be paired with #5307 instead of being a separate feature request.
