### ISSUE TITLE
[TF2] Unleashed rage frame count isn't properly set for 8/9 classes and is assigned to end at frame 144 universally 

### ISSUE THREAD

**Issue by shot12guys** [ValveSoftware/Source-1-Games#6162]
Scout 134 - 144
Soldier 135 - 144
Pyro 144 - 144
Demoman 130 - 144
Heavy 137 - 144
Engineer 137 - 144
Medic 135 - 144 
Sniper 120 - 144
Spy 136 - 144

**Comment by NULLYUKI** [comment]
According to patch [227323](https://www.teamfortress.com/post.php?id=227323)
>Updated Taunt: Unleashed Rage to fix incorrect outro timing

Please retest this issue.

**Comment by shot12guys** [comment]
Changes are correctly assigned for each class, pyro is also the same, functions just as it would in-game.
![ragetauntframes](https://github.com/user-attachments/assets/82dc3f09-2d23-4e12-abff-f313bc83e132)

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
