### ISSUE TITLE
Cp_Canaversal: you can leave the map by the top roof/windows

### ISSUE THREAD

**Issue by AceLombic** [ValveSoftware/Source-1-Games#6163]
https://youtu.be/c70PHT7cu-A?si=Y2h2ho4Z_PyDl0fg
1. Cp_Canaversal: you can leave the map by the top roof/windows and can go into the parking lot because it’s not solid. Engineers can also build there in the parking lot.

<details><summary>Screenshots</summary>

![IMG_8821](https://github.com/user-attachments/assets/5f663d82-50e4-4230-91e5-fdd6b65163f3)
![IMG_8822](https://github.com/user-attachments/assets/21fc5ce9-694f-46c8-8557-06f5a5ec6201)
![IMG_8823](https://github.com/user-attachments/assets/3bd55c6e-036b-4f73-9138-032b75df0457)
![IMG_8824](https://github.com/user-attachments/assets/cc7d6364-3419-4dd2-a167-862f0d51a6c3)
![IMG_8825](https://github.com/user-attachments/assets/b5c43ae4-2a8b-434b-a185-e821edb4b96c)
![IMG_8826](https://github.com/user-attachments/assets/1e0d77c9-edfb-4a61-9c58-3c48fd55955b)
![IMG_8827](https://github.com/user-attachments/assets/e6f7b692-4b87-46eb-b30b-c34802e788e7)
![IMG_8828](https://github.com/user-attachments/assets/9f844317-af5d-4e23-a3bc-3883943831ca)
![IMG_8829](https://github.com/user-attachments/assets/8b61d69a-b41c-49b0-a82a-b96f01c87c93)
![IMG_8833](https://github.com/user-attachments/assets/cc339715-bf0c-4e1e-8c38-1eb785b25057)
![IMG_8832](https://github.com/user-attachments/assets/cb4fdae2-9f28-49d3-a42f-4fe0b50e315d)
![IMG_8831](https://github.com/user-attachments/assets/e3394bb3-8e67-4c09-8ea2-d90e844e9478)
![IMG_8830](https://github.com/user-attachments/assets/e77ed560-93be-466b-9071-ae4231aeebb0)

</details>

**Comment by JoriKos** [comment]
You should make separate reports for each issues, as multi-issue reports are generally not allowed here. Valve doesn't really touch community-made maps, so it's better to notify them.

As for the anti-cheat thing, this seems like smth already covered by #3477.

**Comment by kisak-valve** [comment]
Hello @AceLombic, as @JoriKos noted, in general multi-issue issue reports bad for any issue tracker. For tracking purposes, only your first issue will be tracked in this issue report.

**Comment by NotHyper-474** [comment]
As of July 19th this seems to have been fixed: https://www.teamfortress.com/post.php?id=225689
