### ISSUE TITLE
[TF2] [Windows 11] Game crashes when loading into a server. 

### ISSUE THREAD

**Issue by PsVitaBoy** [ValveSoftware/Source-1-Games#6166]
As of the latest update, game crashes upon trying to connect to a community, Valve or self-hosted server.
Reinstalling or verifying game files does not fix issue.
Mods have been installed but all have worked in the past.
The video below is an example of the issue, be patient as the recording starts a few seconds in.

https://github.com/user-attachments/assets/fe6eb2c4-b55e-4f22-bd30-95c8fa4fa355

**Comment by PsVitaBoy** [comment]
It appears that the video is not working, at least for me; I will try to reupload it later.

**Comment by starwarswii** [comment]
same issue, though on windows 10
tried verifying game files, resetting `custom` and `cfg` folders, and re-installing the game

game crashes instantly when:
- clicking 'join game' on a casual pop up
- clicking 'abandon', and then 'abandon' on the casual re-connect pop up (a strange one, not connect-to-server related?)
- clicking 'connect' to a community server
- clicking 'start' on the create server pop up

when performing these actions, the game hangs for half a second, with the mouse spinning, and then fully closes. you don't see any of the 'you're on your way to...' screen or anything

**Comment by starwarswii** [comment]
after trying a bunch of stuff, i think i fixed it
i had to ensure my steam client was fully up to date:
- delete the `C:\Program Files (x86)\Steam\steam.cfg` file if you put it there (e.g. containing `BootStrapperInhibitAll=enable`)
- restart steam
- click steam > check for steam client updates
- apply any updates and restart steam

after doing this, it now works

sources:
https://steamcommunity.com/app/440/discussions/0/4526764378251259938/#c4526764378251377968
https://steamcommunity.com/app/440/discussions/0/4526764378252128345/#c4526764378252534497

**Comment by PsVitaBoy** [comment]
Thanks man, I completely forgot that I had modified my client ages ago.

**Comment by kisak-valve** [comment]
Hello @PsVitaBoy, using an outdated Steam client isn't something that can be supported sanely.

Closing per the last couple comments.
