### ISSUE TITLE
[TF2] Door on Embargo trapped player after Blu captured a point.

### ISSUE THREAD

**Issue by ADuckWithASmokingThingy** [ValveSoftware/Source-1-Games#6172]
I was on red team, leaving one of the spawns, when Blu capped a point, and as a part of the point capturing sequence, the door right after the spawn room closed off. Because I was walking under it at the time, it trapped me, and I was unable to move until someone on Blu killed me.

Hopefully the issue can be solved easily by just copying the code that stops this scenario on doors like the shortcut doors at the last point of Badwater, or just making the door push players out via changing their coordinates directly depending on what side they are on if this is a different kind of issue.

**Comment by Tiagoquix** [comment]
Hi there, I have notified the creator of the map (he's a friend of mine).

**Comment by Tiagoquix** [comment]
Creator said he has fixed the issue. Now it's up to Valve to update the map to reflect the change.

**Comment by Tiagoquix** [comment]
The map has been updated. Could you retest to see if the issue persists?

**Comment by kisak-valve** [comment]
Closing per the last comment.
