### ISSUE TITLE
[TF2] not being able to play

### ISSUE THREAD

**Issue by Leepik28** [ValveSoftware/Source-1-Games#6178]
I have a problem where I can't play the game, and I will be stuck on the loading screen forever. If I actually get to the main menu and want to join a server, it will get stuck loading on "downloading server info" until it times out. I tried verifying the integrity of game files, reinstalling the game, and reinstalling Steam. I had this problem before the 64-bit update.

**Comment by kisak-valve** [comment]
Hello @Leepik28, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5951.
