### ISSUE TITLE
Koth_Cachoeira: Missing Texture

### ISSUE THREAD

**Issue by AceLombic** [ValveSoftware/Source-1-Games#6180]
![image_2024-07-20_143033223](https://github.com/user-attachments/assets/29563f56-d8b0-41d2-a8fe-e2fda5af38a2)

**Comment by NULLYUKI** [comment]
According to patch [227323](https://www.teamfortress.com/post.php?id=227323)
>Fixed missing door texture (Thanks Hoppkins!)

Please retest this issue.

**Comment by kisak-valve** [comment]
Closing per the last comment.
