### ISSUE TITLE
Out-of-Bound Sentry placement on CTF_Applejack [TF2]

### ISSUE THREAD

**Issue by CupOfCoffi** [ValveSoftware/Source-1-Games#6182]
![20240720202044_1](https://github.com/user-attachments/assets/cf5c3b53-ab16-4889-ac21-b1031f71df0f)
This spot on the main area of the map "ctf_Applejack" on TF2 has no No-build mesh allowing engineers to be able to place sentries that are able to shoot toward enemy players. Making it nearly impossible to get destroy.
![20240720202533_1](https://github.com/user-attachments/assets/e6a8a1d0-96d7-4535-8ebe-747b14cdf53c)
I'm hoping this would be fixed quickly before players start abusing it.

**Comment by JoriKos** [comment]
If you want it urgently fixed, I recommend telling the community creators about it, as they might not check here and Valve doesn't edit these maps.

**Comment by Tiagoquix** [comment]
The map has been updated. Could you retest to see if the issue persists?

**Comment by kisak-valve** [comment]
Closing per the last comment.
