### ISSUE TITLE
[TF2] [Feature Request] ipv6 support/NAT traversal/steam multiplayer integration for servers

### ISSUE THREAD

**Issue by refrogerator** [ValveSoftware/Source-1-Games#6184]
I've been placed behind a CGNAT by my ISP recently and am now unable to port forward and host a server for my friends.
IPv6 support or better integration with steam multiplayer (being able to join someone who used the create server button in the main menu) would fix the issue.

**Comment by JoriKos** [comment]
If you want a fast server that people can connect to, IIRC you can just use `-enablefakeip` in the launch options, type `map mapname` in the console (replacing "mapname" with your desired map), then look in the console for the server's IP, and then tell your friends to join off of that + port.

**Comment by kisak-valve** [comment]
Hello @refrogerator, this is functionally the same issue as #6081. Closing in favor of the older issue report.
