### ISSUE TITLE
Queue Isn't working, just stops

### ISSUE THREAD

**Issue by motherofdragons96** [ValveSoftware/Source-1-Games#6195]
Did everyone know why the queue Isn't working, the community servers are fine, but something must of happened. I really want to play Casual right now

**Comment by JoriKos** [comment]
Seems like this was fixed already according to the in-game message

**Comment by JoriKos** [comment]
May also be a duplicate of #2820, was the queue starting, then stopping entirely without you doing anything?

**Comment by ethanholt1** [comment]
Retested on Windows X64. Seems to be fixed (queued for 10 different games, issue didn't happen.) I would wait for another person to retest, preferably on Linux before this can be safely closed.

**Comment by kisak-valve** [comment]
Closing per the last several comments.
