### ISSUE TITLE
[TF2] Crash to desktop when loading any map, connecting to server, etc

### ISSUE THREAD

**Issue by misternebula** [ValveSoftware/Source-1-Games#6197]
PC Specs :
- Intel i7-6700
- GeForce GTX 1060 3gb
- 16gb ram
- Windows 10

Game loads into menu fine, but running `map ctf_2fort` or clicking "Join Now" in a casual queue instantly closes the game.

Attempted fixes :
- Fresh install of TF2
- Deleting the `custom` folder (there was only a custom hitsound in there anyway)
- Clean install of graphics card drivers
- Running `con_logfile` and trying to load a map produces no output file
- Happens on both `tf_win64.exe` and `tf.exe`

TF2 used to work fine on this computer, but at some point broke.

**Comment by kisak-valve** [comment]
Hello @misternebula, please verify that your Steam client install is up to date.

**Comment by misternebula** [comment]
Yep, that was it. Thanks! (No idea how the client was that out of date...)
