### ISSUE TITLE
[TF2] x64 version have a random chance to get audio working (Ubuntu 22.04)

### ISSUE THREAD

**Issue by ysob64** [ValveSoftware/Source-1-Games#6203]
**What did a try** :

- snd_restart : freeze the game immediately (no error in logs)(even if audio was working)
-  A certain time ago, changing the game to windowed mode was fixing the audio, not working anymore
- Checked for some libs missing (?)

There is no errors at all in the console or in the logs.
I precise that i'm currently using [comfig](https://comfig.app/app/).
One last thing, the game seems to play the audio correctly even when I hear nothing according to the `snd_dumpclientsounds` command. I'm using pulseaudio.

**Comment by Tiagoquix** [comment]
Does the same problem occur in the x32 (OpenGL) version?

Could you update to latest Ubuntu LTS to see if it fixes the problem?
Starting from Ubuntu 22.10 (non-LTS version, but 24.04 is LTS), PipeWire is the default.

**Comment by ysob64** [comment]
It does occur in x32 opengl, strangely, since the bug only occurred when tf2 got the x64 update. I will test soon to see if it fix while installing pipwire or upgrading to 22.10. I also forgot to mention that when I quit the game when the audio is not working, the game also freeze instantly.

**Comment by ysob64** [comment]
Sorry for the very very late response but the bug seems to be gone, didn't see anything that could be related to this issue in recent tf2 update.
