### ISSUE TITLE
[TF2] After last update the game crashes joining to servers (Windows 11 - 64bit)

### ISSUE THREAD

**Issue by oknehsayli** [ValveSoftware/Source-1-Games#6206]
TF2 crashes exactly when it finds a server and starts loading map.  I use Windows 11

**Comment by kisak-valve** [comment]
Hello @llyashenko, please verify that your Steam client install is up to date.

**Comment by oknehsayli** [comment]
> Привет@llyashenko, пожалуйста, проверьте, обновлена ​​ли ваша версия клиента Steam.

No, why? It suits me, less load on my PC. It turns out that they specifically removed the ability to play in the old Steam client?

**Comment by JackBIack** [comment]
> TF2 crashes exactly when it finds a server and starts loading map. I use Windows 11

Did you find a fix yet?

**Comment by kisak-valve** [comment]
Hello @llyashenko, @JackBIack, it's not possible to sanely support outdated Steam clients.

**Comment by JackBIack** [comment]
Tried updating the client again and worked (Windows 8.1).

**Comment by oknehsayli** [comment]
> Попробовал обновить клиент еще раз и это сработало (Windows 8.1).

The latest version steam (16 Jul 2024)?
