### ISSUE TITLE
[TF2] Game crashes when joining server after the "Summer Update".

### ISSUE THREAD

**Issue by JackBIack** [ValveSoftware/Source-1-Games#6209]
Since the game was updated, I have been **unable to play TF2**. The game loads the main menu fine, but as soon as I join a server the game **instantly crashes** and closes itself immediately. Both casual and community servers crash. Even hosting your own server crashes it aswell. **The game worked perfectly fine before the update**, I do not have any custom configurations or anything of the sort, perhaps the summer update **broke something**. I am currently on **Windows 8.1** but as far as I'm concerned, there are others having the same issue since the update, ranging from Windows 7 to Windows 11.

**Comment by NULLYUKI** [comment]
If I'm correct, the crashes were fixed by updating their Steam clients to the latest version.

**Comment by JackBIack** [comment]
> If I'm correct, the crashes were fixed by updating their Steam clients to the latest version.

Unfortunately, that does not seem to fix it for me.

**Comment by NULLYUKI** [comment]
Because the support for Windows versions older then Windows 10/11 has ended.

**Comment by JackBIack** [comment]
> Because the support for Windows versions older then Windows 10/11 has ended.

There must be a fix for older versions, I doubt they would purposely update TF2 so it would not be able to join servers on older versions, or would they?

**Comment by NULLYUKI** [comment]
As reference in https://github.com/ValveSoftware/Source-1-Games/issues/6166 and https://github.com/ValveSoftware/Source-1-Games/issues/6197 the same issue was described and both of the issues were resolved by updating the Steam client to the latest version.

**Comment by kisak-valve** [comment]
Hello @JackBIack, it's not possible to sanely support outdated Steam client installs.

**Comment by JackBIack** [comment]
Tried updating the client again and it fixed the crashes.
