### ISSUE TITLE
TF2 | Replay system on official casual matchmaking 

### ISSUE THREAD

**Issue by melodyjkah** [ValveSoftware/Source-1-Games#6212]
replays were added in 2011, which are now useless and disabled. My suggestion is to restore them to official casual matchmaking. i heard that they were deactivated because they caused “fps drops” but how can a serverside thing take fps bruh. With replays you can make a lot of cool clips but they are now dead and useless. bring them back 🙏

**Comment by melodyjkah** [comment]
oh wait i saw actually similar issues

**Comment by JoriKos** [comment]
Duplicate of #4724

**Comment by kisak-valve** [comment]
Hello @melodyjkah, as @JoriKos noted, this issue is already being tracked at #4724. Closing as a duplicate.
