### ISSUE TITLE
Got False gamebanned in the game Team Fortress 2 

### ISSUE THREAD

**Issue by AdamisTF2** [ValveSoftware/Source-1-Games#6224]
I never used any cheats or any third party software to gain advantage in team fortress 2.
I use cl_interp 0.5 in the game and got reported a lot for "suspicious play" (as they say they reported me)
I have 60+ clips to show my legit gameplay with interp and i can show you how to do backstabs with interp.
Here is my account : https://steamcommunity.com/id/adamicensigara/
I am gamebanned which shows this is a manual-ban. 
I hope to get in contact someone from the team fortress 2 team.
I will show anything possible to prove I am innocent.

**Comment by chocochocotorta** [comment]
Game-bans are not appealable in this Github, this is only for Source 1 Games errors, bugs, etc.
Only way to get in contact with TF2Team of a Valve employee is through Steam Support.

**Comment by AdamisTF2** [comment]
Hello. I tried to contact steam support but in the site game bans are unappealable and i am sure that i can prove i am innocent.

**Comment by kisak-valve** [comment]
Hello @AdamisTF2, in general, account issues including game bans are not handled on GitHub in any capacity.

Closing as out of scope for this issue tracker.
