### ISSUE TITLE
[TF2/FEATURE REQUEST] enable use of casual next map vote system for community servers

### ISSUE THREAD

**Issue by melodyjkah** [ValveSoftware/Source-1-Games#6226]
enable use of casual next map vote system for community servers, because uhh... community servers need lousy plugins for that + it will be cool.
![image](https://github.com/user-attachments/assets/dc38f0a4-23bf-46b6-973f-2a80781ea6b3)

**Comment by kisak-valve** [comment]
Hello @melodyjkah, please search for preexisting issues before opening another duplicate issue report. This request is already being tracked at #2721.

Closing as a duplicate.
