### ISSUE TITLE
TF2 Performance Degradation....

### ISSUE THREAD

**Issue by furycd001** [ValveSoftware/Source-1-Games#6228]
## Issue..
TF2 launches and runs perfectly fine initially. However after a short period of gameplay, the game becomes significantly slower and feels sluggish, with noticeable frame drops & stutters. Despite this performance issue, my CPU, RAM, and GPU usage levels appear to be normal. Upon closing TF2, the computer remains slow and sluggish for about a minute or so before normal performance resumes. This makes it difficult to do anything immediately after closing TF2.

## Steps to Reproduce..
1. Launch TF2.
2. Play for a short period (exact duration may vary).
3. Observe the game becoming slower with dropping frame rates.
4. Close TF2.
5. Notice that the computer runs really slow and sluggish for a moment after closing TF2.

## System Information..
- **CPU:** Intel i5-3470
- **RAM:** 16GB
- **GPU:** Sapphire Radeon RX570 4GB
- **OS:** Arch Linux (fully up-to-date)
- **DE:** XFCE running on X11

## Additional Information..
- **Console Log**: [View Log](https://termbin.com/vrx7)
- **I use *[lighthud](https://github.com/Hypnootize/lighthud)* & a custom killsound.**
- **No mods, skins or anything custom installed..**

Thank you very much for your help !!

**Comment by kisak-valve** [comment]
Hello @furycd001, please give a #5785 a read and check if that matches the issue you're seeing.

**Comment by furycd001** [comment]
Yes that appears to match my issue. I had overlay disabled, but have now enabled it. Will report back later, when I have next played the game....

**Comment by furycd001** [comment]
Can confirm that enabling overlay seems to have fixed the issues I was having. Closing....
