### ISSUE TITLE
[Team Fortress 2] Since the summer update, several clients have reported the game crashing immediately when connecting to a server

### ISSUE THREAD

**Issue by QuantumToasted** [ValveSoftware/Source-1-Games#6232]
*Hi there. I manage a very large [TF2 Discord server](discord.gg/tf2), and we have a dedicated forum channel for people asking for help and advice for the game. As many of these people reporting these issues do not have GitHub accounts (or explaining them how to open an issue themselves might prove complicated), I'm making this post on their collective behalf. I'm not directly experiencing this issue, but others might chime in with their experience and steps to reproduce.*

Several (5-10) players have reported that at some point since the summer update on the 18th, their TF2 client refuses to connect to casual or community servers without immediately closing or crashing without a reliable cause or error. Some have reported the issue starting since the day of the update, some have mentioned it has only started within the past week, it's inconsistent but it seems to be a recent issue.

An example video someone sent to me, where as soon as they double-click a community server to connect, the game freezes/closes.
![video](https://github.com/user-attachments/assets/e9750d3e-6f5b-4e7e-abd0-c53c67cc32a9)

Our general support guidelines when people are mentioning game crashes is to verify/validate game files, remove mods and other custom content, and even a more nuclear option of completely resetting the game via `-autoconfig` and removing all Steam Cloud files. For some, this has fixed the issue apparently, but for others, the issue persists.

I will be asking all the people who reported this issue for more information to see if it is consistent between clients or just a pure coincidence.

**Comment by kisak-valve** [comment]
Hello @QuantumToasted, we've seen several user report the same here, and in each case, the players are Windows users with an outdated Steam client. (#6158 #6166 #6206 #6209). As noted in those issue reports, it's not possible to sanely support outdated Steam client installs.

If there's more subtle crashes happening, that can't be generalized and reported second hand and will need to be evaluated on a per-case basis.
