### ISSUE TITLE
[L4D2] "Beat the Rush" achievement not working 

### ISSUE THREAD

**Issue by BaronPoKli4keXep** [ValveSoftware/Source-1-Games#6237]
Hello my dear comrades from valve. Me and my friend have an issue with achievement named Beat the Rush. We have completed all the requirements for this achievment, unfortunately it seems to be bugged out and won't award us.
![image](https://github.com/user-attachments/assets/3f1096b2-910a-484c-af99-f35199b02eb0)
![image](https://github.com/user-attachments/assets/3c34d2b9-d683-4c96-880a-6c6fbe799485)

On the internet people also complain that achievement doesn't work after Last Stand update.

I’m going to attach a link on a video where I completed all the conditions for this achievement
https://youtu.be/1RWLOgXlNFo

System info
Информация о компьютере:
Производитель: ASUS
Модель: All Series
Тип: настольный
Сенсорный ввод не поддерживается
Процессор:
Производитель процессора: GenuineIntel
Бренд процессора: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Семейство процессора: 0x6
Модель процессора: 0x3c
Степпинг процессора: 0x3
Тип процессора: 0x0
Тактовая частота: 3492 МГц
Логических процессоров: 4
Физических процессоров: 4
Hyper-Threading: Не поддерживается
FCMOV: Поддерживается
SSE2: Поддерживается
SSE3: Поддерживается
SSSE3: Поддерживается
SSE4a: Не поддерживается
SSE41: Поддерживается
SSE42: Поддерживается
AES: Поддерживается
AVX: Поддерживается
AVX2: Поддерживается
AVX512F: Не поддерживается
AVX512PF: Не поддерживается
AVX512ER: Не поддерживается
AVX512CD: Не поддерживается
AVX512VNNI: Не поддерживается
SHA: Не поддерживается
CMPXCHG16B: Поддерживается
LAHF/SAHF: Поддерживается
PrefetchW: Не поддерживается
Версия ОС:
Windows 10 (64-разрядная)
NTFS: Поддерживается
Предоставленные криптокоды: Поддерживается 311 0x0 0x0 0x0
Видеокарта:
Драйвер: NVIDIA GeForce GTX 1650
Драйвер DirectX: nvldumd.dll
Версия драйвера: 31.0.15.3623
Версия драйвера DirectX: 31.0.15.3623
Дата выпуска драйвера: 8 6 2023
Версия OpenGL: 4.6
Глубина цвета: 32 бит/пиксель
Частота обновления: 59 Гц
Карта DirectX: NVIDIA GeForce GTX 1650
ID производителя: 0x10de
ID карты: 0x1f82
Ревизия: 0xa1
Число экранов: 1
Количество логических видеокарт: 1
SLI или Crossfire не обнаружены
Разрешение осн. экрана: 2560 x 1440
Разрешение рабочего стола: 2560 x 1440
Размер осн. экрана: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Осн. шина: PCI Express 16x
Осн. видеопамять: 4095 МБ
Поддерживаемые режимы сглаживания: 2x 4x 8x
Звуковая карта:
Аудиоустройство: Динамики (High Definition Audio
Память:
Оперативная память: 18365 МБ
Устройства виртуальной реальности:
Шлем виртуальной реальности: не обнаружен
Разное:
Язык интерфейса: Русский
Тип носителя: Не определено
Суммарное место на диске: 457287 МБ
Наиболее свободный диск: 84374 Мб
Дата установки ОС: ��� 13 2022
Игровой контроллер: None
Хэш MAC-адреса: f3a10b884c8292568e52a620ac6f6cdd996fb862
Место на диске:
Хэш серийного номера диска: 3f859fdc
Число SSD: 1
Размеры SSD: 480G
Число жёстких дисков: 0
Число съёмных носителей: 0

**Comment by kisak-valve** [comment]
Hello @BaronPoKli4keXep, this issue is already being tracked at #5146. Closing as a duplicate.
