### ISSUE TITLE
[TF2] Crashing after second load into casual/community servers consistantly.

### ISSUE THREAD

**Issue by SlayerIsTheCoolest** [ValveSoftware/Source-1-Games#6238]
Hi, I've been dealing with consistant crashes (in Fullscreen or windowed mode) and TF2 doesn't show any signs of issue as far as I can tell when it actually happens. I've compiled the crash log here and am hoping someone can help and diagnose exactly what my issue is. At most I believe it has something to do with the error code which can be found in the crash log dump attached : Access violation - code c0000005 (first/second chance not available) but I can not find anything online about it relating to TF2 at all.

This happens in no other games, this only started happening 2 weeks ago. 

(I have just found out this also causes all demo files to crash as well.)

My Specs: 
GPU: RTX 4080 Super
CPU: Ryzen 9 7900x 
RAM: Corsair Vengeance 32 x 2 DDR5
MB: MSI B650 GAMING PLUS WIFI

My autoexec is also added.

Things I have tried: 
Deleting custom folder 
Verifying game files multiple times
Reinstalling multiple times
Factory resetting tf2
Different resolutions
No launch options
Specific launch options (None of which work)
Deleting configs
Resetting configs
Disabling overclocking
Reinstalling / Updating drivers
Using the commands mod_load_anims_async 0, mod_load_mesh_async 0, mod_load_vcollide_async 0, cl_always_flush_models 1.
Verifying steam version (Up to date)
Reinstalling older steam version

Attachments: 

[crash_tf_win64.exe_20240802122319_1.dmp](https://github.com/user-attachments/files/16473713/crash_tf_win64.exe_20240802122319_1.dmp)
[console.log](https://github.com/user-attachments/files/16473715/console.log)
[New Text Document.txt](https://github.com/user-attachments/files/16473731/New.Text.Document.txt)  < - (autoexec)

**Comment by NULLYUKI** [comment]
While this is a duplicate from https://github.com/ValveSoftware/Source-1-Games/issues/6110 It still provides lots of information about the already tried possible solutions, logs and a crash dmp, so it would be preferred if you @kisak-valve could move this information as a comment into https://github.com/ValveSoftware/Source-1-Games/issues/6110

**Comment by SlayerIsTheCoolest** [comment]
Update: I have fixed this issue upon factory resetting tf2 for a second time. The issue stemmed from a preloader I was using that has become outdated. I Hope this will help someone.
