### ISSUE TITLE
[TF2 Linux] "TF2 is not responding" but the game works well

### ISSUE THREAD

**Issue by DiegoArmando-27** [ValveSoftware/Source-1-Games#6251]
After every launch of TF2, I am getting this
![2024-08-06_12-06](https://github.com/user-attachments/assets/2ca8f849-85ec-4ce0-895f-e61c35fe5d5e)
If I click on `Wait` or just wait for the loading, this message goes away

[My PC specs](https://gist.github.com/DiegoArmando-27/07473d148d28221a4346eaf449cd8844)
[Steam Runtime System Information](https://gist.github.com/DiegoArmando-27/f57bf8f0171ef0f394be59a4d11647f3)

**Comment by NULLYUKI** [comment]
Copy the contents of Steam Runtime Diagnostics from Steam (Steam -> Help -> Steam Runtime Diagnostics) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by DiegoArmando-27** [comment]
> Copy the contents of Steam Runtime Diagnostics from Steam (Steam -> Help -> Steam Runtime Diagnostics) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Done

**Comment by kisak-valve** [comment]
Hello @DiegoArmando-27, this is a message from your window manager because it hasn't been handed any updates from the game while it loads into the main menu.

**Comment by DiegoArmando-27** [comment]
Closing as non-source related issue
