### ISSUE TITLE
[L4D2] Linux version is downloading files from Windows version

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#6254]
For some reason, the native Linux version is downloading "left4dead2.exe" to the "steamapps/common/Left 4 Dead 2/" folder.

Trying to force Steam Linux Runtime Scout (1.0) or Sniper (3.0) makes no difference.

I believe this is related to problems fixed previously this year in the Steam Client:

https://store.steampowered.com/news/app/593110/view/3901870710035098052

"Fixed situations causing the Steam client to only download the Windows version of a title and later attempting to run it without Proton."

https://store.steampowered.com/news/app/593110/view/4182231197207095612

"Fixed a situation where Steam would attempt to execute the Windows version of a title without using Steam Play"

In this case, it's downloading both Linux and Windows files, and running the native version.

My system is up-to-date, and Steam is on the Stable branch, version `1721173382`.

---------------------------

EDIT:

Digging a little deeper, the problem seems to be due to the fact that Left 4 Dead 2 does not have a separate Windows client depot configured.

Using information provided by SteamDB, in several other Valve games there is clearly a rule of four depots (and possibly additional ones for other things): a "common" one, which shares multiple files, and one for each supported operating system (Windows, Linux, and macOS) that contain relevant files for the specific platform (`.exe` files for Windows, `.sh` for Linux etc.).

Links to check:

Counter-Strike - https://steamdb.info/app/10/depots/
Half-Life - https://steamdb.info/app/70/depots/
Counter-Strike: Condition Zero - https://steamdb.info/app/80/depots/
Counter-Strike: Condition Zero Deleted Scenes - https://steamdb.info/app/100/depots/
Half-Life 2 - https://steamdb.info/app/220/depots/
Counter-Strike: Source - https://steamdb.info/app/240/depots/
Portal - https://steamdb.info/app/400/depots/
Team Fortress 2 - https://steamdb.info/app/440/depots/
Left 4 Dead - https://steamdb.info/app/500/depots/ (no support for Linux, but has support for macOS)
Dota 2 - https://steamdb.info/app/570/depots/
Portal 2 - https://steamdb.info/app/620/depots/
Counter-Strike: Global Offensive and 2 - https://steamdb.info/app/730/depots/

However, this rule does not apply to Left 4 Dead 2 (https://steamdb.info/app/550/depots/): it only has two client depots, which are for Linux and macOS, while the rest of the Windows client files are included with the common files used by all platforms. This is why it's probably causing to download files from the Windows client. In theory, this problem is also present on macOS, but I'm unable to confirm on that OS.

There are some files on the common depot of L4D2 that are unnecessary for other operating systems. For example, there is `addoninstaller.exe` and `addoninstaller_osx`. Why would a Windows user, for example, need to have an add-on installer for macOS? And why would a Linux user need to have both of them too?

**Comment by kisak-valve** [comment]
Hello @Tiagoquix, this issue is already being tracked at #1146. Closing as a duplicate.
