### ISSUE TITLE
[TF2] DXVK render does not properly synchronize with monitor's refresh rate

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#6258]
First of all, this is not an issue I'm able to reproduce since my monitor is 60 Hz and everything works fine for me.

However, it seems that for some users the refresh rate doesn't properly sync. with the monitor's refresh rate, causing sttuters and crashes. Specifying `-windowed` (which forces V-Sync) or `-freq X` (where `X` is the refresh rate of the monitor (such as `75`)), the issue seems to fix itself.

This seems to only happen on Linux as far as I can tell, but the issue may be present on Windows devices too.

See https://github.com/ValveSoftware/Source-1-Games/issues/6086#issuecomment-2212350537 and https://github.com/ValveSoftware/Source-1-Games/issues?q=is%3Aopen+is%3Aissue+label%3A%22Team+Fortress+2%22+label%3ALinux+windowed for a more general view.

This issue may be present on other Source 1 games too, but I'm unable to confirm.

**Comment by kisak-valve** [comment]
Hello @Tiagoquix, this issue is already being tracked at #5704. Also, an issue of this nature shouldn't be proxy reported as you're not able to test if a change had any effect.

Closing as a duplicate.
