### ISSUE TITLE
Half Life ( appid: 70 ) hardcapped to 100 fps

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/Source-1-Games#6263]
Disabling vsync in game settings doesn't change the outcome, fixed 100 hz.

On a system with 165 hz monitor and 7900 XTX, Arch Linux.

**Comment by kisak-valve** [comment]
Hello @Leopard1907, this issue is already being tracked at https://github.com/ValveSoftware/halflife/issues/2338 and some others in that issue tracker.

Closing as a duplicate.
