### ISSUE TITLE
[TF2] MvM Boot Camp ignores SDR address on client connect for community servers

### ISSUE THREAD

**Issue by programmedsun** [ValveSoftware/Source-1-Games#6267]
There is a bug with Boot Camp Matchmaking handling the community server that runs under SDR. For some reason when a Boot Camp finds a community server that runs SDR it will reveal its real IP address before reconnecting to the SDR IP address.

Here's Boot Camp connecting to my server which has SDR enabled and doesn't expose itself to the master server.
![Screenshot_2024-08-10_21-13-56](https://github.com/user-attachments/assets/dcd3e073-e248-43a4-9e43-e19ad06ea664)

The matchmaker seems to ignore that the server has SDR enabled but acknowledges that SDR is enabled and clients would see the SDR address instead of the real IP address. (old screenshot but the issue still persists in version `9087997`)
![Screenshot_2024-08-10_21-19-24](https://github.com/user-attachments/assets/458aeea5-7aa9-4887-8863-7e4017b95c4f)

This isn't the case for a Valve Boot Camp server though as the server IP address remains consistent with the SDR IP address.
![Screenshot_2024-08-10_21-07-48](https://github.com/user-attachments/assets/6e4adcfd-697b-4d2f-9e40-f5d792e268d4)

**Comment by kisak-valve** [comment]
Hello @coredesu, this issue is already being tracked at #5941. Closing as a duplicate.
