### ISSUE TITLE
[TF2] "Winterized" sound not playing when opening Smissmas 2016 cases

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#6273]
Recently, I opened an _Unlocked Winter 2016 Cosmetic Case_, and I didn't hear the "winterized" sound that all winter cases were updated with in 2022. Seems like this specific case wasn't affected by that update due to an oversight?

**Comment by NULLYUKI** [comment]
According to patch [230553](https://www.teamfortress.com/post.php?id=230553)

> Fixed Keyless Winter 2016 Case not playing the special winter case sound 

Please retest this issue.

**Comment by ShadowMan44** [comment]
Anyone got an unlocked winter 2016 case to spare? Lmfao

**Comment by gaelcoral** [comment]
It is now fixed

https://github.com/user-attachments/assets/9e78c3f4-9a81-4d61-a11d-ae8f01d3595f
