### ISSUE TITLE
[TF2] [Feature Request] Whitelist cosmetic mods for casual.

### ISSUE THREAD

**Issue by CheddarSniffer** [ValveSoftware/Source-1-Games#6285]
As we know very few mods work in casual, (HUDs only) I was hoping that cosmetic mods could be added to a whitelist so they can be altered, so mods that change cosmetics items are allowed, these being; mods that may remove paintability from cosmetics, mods that remove some/all cosmetics and mods that may remove/add parts to an existing cosmetic.

**Comment by kisak-valve** [comment]
Hello @CheddarSniffer, this request is already being tracked at #4689. Closing as a duplicate.
