### ISSUE TITLE
[TF2, Linux] Recent update might have broken symbolic links

### ISSUE THREAD

**Issue by some-username-here1** [ValveSoftware/Source-1-Games#6286]
I'm not sure if it was an update past the recent summer update or the update itself, but the symbolic links that I have been using as my "custom" folder has been broken since the summer update, maybe even a while before, and would crash tf2 while it's loading. I can confirm it is the symbolic links since I have tried creating a new one from the terminal, only to get the same outcome, then tried copying over the folders from where the links where pointing at into my "tf" folder. This stops the crashing altogether, as well as significantly speeding up the game's loading time.

If anyone can dive into this very specific issue even further, I welcome such efforts!

**EDIT:** I also wanted to add, using a symbolic link for the "custom" folder also increases the startup loading time to about a minute or more compared to the usual ~5 seconds, I'm not sure why this happens.

**Comment by kisak-valve** [comment]
Hello @some-username-here1, Team Fortress 2 for Linux is now run inside the Steam Linux Runtime 3.0 (sniper) runtime container. It does not give unlimited access to the the host filesystem and does not comprehensively walk the game's folders to make symlinks sane inside the container.

You could try setting the game's launch options to `STEAM_COMPAT_MOUNTS=/path/to/unexpected/folder %command%` or convert symlinks to bind mounts.

**Comment by some-username-here1** [comment]
Thanks for letting me know about the changes made to the runtime! Although there is another issue I've been having that I'm creating a new thread for that may be related to switched the runtime.
