### ISSUE TITLE
[TF2] Clicking outside the queue menu while it is open results in console showing "unknown command" twice

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#6287]
As title says, clicking something outside of the queue menu (doesn't have to be Casual's map selection) will put "unknown console command: dimmer_clicked" or something of that variety in the console twice, despite the menu closing just fine.

**Comment by kisak-valve** [comment]
Hello @JoriKos, this is harmless.

**Comment by JoriKos** [comment]
> Hello @JoriKos, this is harmless.

It is, but so was #5579 but that was fixed. I thought maybe these were similar issues
