### ISSUE TITLE
[TF2] Viewmodel offsets that are inconsistent with min viewmodels enabled.

### ISSUE THREAD

**Issue by Xilekai** [ValveSoftware/Source-1-Games#6288]
I'm sure you've seen the shounic video before but I'd never noticed how jarring it is between the stock shotgun and strange shotgun until I decided to equip stock to check it. I'm sure it's a thing on many weapons, as well as the ones that don't change position when in min mode. All of that seems worth fixing to me, both for consistency and more space on the screen.

**Comment by kisak-valve** [comment]
Hello @Xilekai, this issue is already being tracked at #3584. Closing as a duplicate.

**Comment by Xilekai** [comment]
Huh, I had searched offset and that didn't come up.
