### ISSUE TITLE
[TF2] casual stuck in spectator glitch

### ISSUE THREAD

**Issue by o-ddt** [ValveSoftware/Source-1-Games#6290]
After the 64-bit update, sometimes when joining casual matches, if I join right when the game starts or 5 seconds before, I will be stuck in spectator and wont be able to play the match until it ends or I requeue.

demo file:
https://www.mediafire.com/file/se7v226tnw01tap/casualglitch.dem/file

**Comment by ethanholt1** [comment]
Same thing also happens in Mann vs. Machine. Seems to be related to not being automatically assigned to a team after joining the game. Switch team bind does not work, switch class bind does not work, nothing works. The only solution is retry (reconnect via the console,) which seems to assign me to a team properly.

**Comment by JoriKos** [comment]
Yeah, `retry` in console fixes it. I encountered this bug once and it seems like it was when I was selecting a class just as the 150 second countdown ended.

**Comment by some-username-here1** [comment]
What about `autoteam` or `spectate` in console (I think those are the right commands, but I'm not too sure)? I've been having an issue like this in one specific server, and those commands can help circumvent this weird bug on there

**Comment by gdfsgdfg** [comment]
As far as I know this happens if two people try to join a team at the same time I've never seen it in mvm though.

**Comment by gaelcoral** [comment]
You can replicate it if you watch the intro and then skip it, which leaves you in spectator mode

https://github.com/user-attachments/assets/fe85f41d-6680-4fb1-84e0-1dd99459ee78

**Comment by ghost** [comment]
I had this bug for a few times way way before the 64 bit uptate. However at some point it just stopped, nowadays I do too happen to stumble upon it so prehaps something was fixed and then later unfixed at some point? I cannot really tell because I ain't really competent in source.

**Comment by KimmyTF2** [comment]
It appears to be fixed https://github.com/ValveSoftware/Source-1-Games/issues/6365#issuecomment-2424839503

**Comment by kisak-valve** [comment]
Closing per the last comment.
