### ISSUE TITLE
[TF2, Linux] Pipewire restarts and hardware sources gets disabled if game crashes during loading screen

### ISSUE THREAD

**Issue by some-username-here1** [ValveSoftware/Source-1-Games#6301]
I'm not sure what exactly is going on and why this happens, but this issue has been persisting since the move to linux runtime 3.0. Relating to custom ugc as I have a lot in my "custom" folder, most of which is for developing maps of mine. As such, this issue can be entirely avoided if the "custom" folder is empty.

I'm not sure why tf2 messes with pipewire when it shouldn't be happening in the first place, on top of temporarily "removing" any hardware playback devices before manually restarting pipewire. Even after restarting pipewire, tf2 has no sound output nor does running `snd_restart` in console do anything to bring the sound back.

**Comment by some-username-here1** [comment]
**Update:** It turns out that it may be a sound cache issue instead, as deleting a sound.cache file located under one of my folders with a bunch of custom sounds in "custom" got rid of the problem altogether.

If anyone can chip in on this and can replicate this issue on their computer, I welcome such efforts!

**Comment by kisak-valve** [comment]
Hello @some-username-here1, the odd pipewire behavior should also be mentioned to the pipewire dev(s). I wouldn't expect any game to make an audio subsystem to trip over itself like that.

**Comment by some-username-here1** [comment]
I'm not sure what exactly happened or where it came from, but this issue was stemming from an unknown cause. It may have to do with adding files from the windows-only install of tf2 to a linux install (such as merging `bin/` and `tf/bin/`). After a doing a fresh install, it now seemed to have been cured of the bug that was plaguing it.

If it ever manages to come back up, I will re-open this issue or create a new one depending on what will then be causing it.
