### ISSUE TITLE
[HL2] fps come down

### ISSUE THREAD

**Issue by kerby1804** [ValveSoftware/Source-1-Games#631]
my conf:

AMD Athlon 4000+ (2.0GHz)
3x 1GB DDR2-667Mhz RAM
Palit nvidia g-force 8600GT 256Mb Ram

my os:
Arch linux(3.8.11-1)
Xfce DE
nvidia 313.30  
xorg-server 1.14.1-1
xorg-xrandr 1.4.0-1

my settings:
screen 1280x1024, and all in max setting, without smoothing and texture filtering.

I do not know how to enable show fps, but it seems that fps "in normal" - is 80-90, but then "something happens" fps down to 20-30.

The first time it happened when I moved from location to location, accompanied by Alyx. I get out from  the game and load it again - fps is up to 80-90.
The second time it happened when I put all the settings to the maximum available (the FPS has dropped slightly to 70), but after saving the game, fps is down to 20-30 again, and again helped out of the game, and  re-runs.

**Comment by kisak-valve** [comment]
This is the expected outcome when VRAM is maxed out and part of the hot path for rendering is bumped over to system ram. In general, lowering video settings may mitigate the issue. Your mileage may vary.

Closing as there is nothing actionable in this issue report.
