### ISSUE TITLE
FastDL L4D

### ISSUE THREAD

**Issue by RaptorRU** [ValveSoftware/Source-1-Games#6311]
Hello, can someone explain why the game client ignores loading bsp, nav files, namely maps from the web hosting? Although as far as I understand everything should work. Was Valve blocked or broken?
https://developer.valvesoftware.com/wiki/FastDL

**Comment by kisak-valve** [comment]
Hello @RaptorRU, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5099.
