### ISSUE TITLE
Portal 2 Pirate screen even after buying it

### ISSUE THREAD

**Issue by Nexio1212** [ValveSoftware/Source-1-Games#6315]
So I just opened my spplice save file in original portal 2, and the screen turned red and then I got a message "hey, don't pirate portal 2, it's very cheap, ans if Ur a kid (something I don't remember) don't pirate video games, it's not cool I was at the same part of life as you, believe me dont pirate" it's from memory so 99% of the message is different but the same point, and now I can't move, I mean, I binded the keys, now I can move but when I look up, it looks down, and even when i change it, it switches back, and i can't look right or left, only down and up (y axis is good but x isn't) I tried raw input too, and doesn't work, I switched the y axis to normal, and it switches back every time I close the settings tab

**Comment by JoriKos** [comment]
I don't think Portal 2 has this feature

**Comment by NULLYUKI** [comment]
I would suggest that you might share a video or screenshot of that screen.

Update: After doing a bit of research I found a reddit account with the same username, which has been posting some comments in piracy related threads, which is why I assume that the user did not bought the game and installed a fake crack. If nothing new is getting posted from the user, I would assume that Kisak could then just close this issue.

**Comment by Nexio1212** [comment]
> I would suggest that you might share a video or screenshot of that screen.
> 
> Update: After doing a bit of research I found a reddit account with the same username, which has been posting some comments in piracy related threads, which is why I assume that the user did not bought the game and installed a fake crack. If nothing new is getting posted from the user, I would assume that Kisak could then just close this issue.

I did not pirate it, it's literally on my steam account bruh, no one's helping

**Comment by Nexio1212** [comment]
> I would suggest that you might share a video or screenshot of that screen.
> 
> Update: After doing a bit of research I found a reddit account with the same username, which has been posting some comments in piracy related threads, which is why I assume that the user did not bought the game and installed a fake crack. If nothing new is getting posted from the user, I would assume that Kisak could then just close this issue.

And yes I do pirate some games, but never valve games

**Comment by NULLYUKI** [comment]
> Please use this repository to report bugs and feature requests for Team Fortress 2, Counter-Strike: Source, Left4Dead2, and the Source 1 Engine.

https://github.com/ValveSoftware/Source-1-Games/blob/master/README.md

If you need help, the steam discussions page for Portal 2 would be the right place.

**Comment by Nexio1212** [comment]
imma just show you the footage from the game, okay? thats a link to the vid
i uploaded https://youtu.be/1EVeS9ReL5Y

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Nie
zawiera wirusów.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

pt., 30 sie 2024 o 21:58 NULLYUKI ***@***.***> napisał(a):

**Comment by JoriKos** [comment]
"Even after buying it" means you probably pirated it before, which is why it's giving issues now.

**Comment by Nexio1212** [comment]
Bruh I had family sharing with my friend and didn't have spplice and p2r3
helped me fix it so ye

pt., 6 wrz 2024, 18:01 użytkownik Jori Kos ***@***.***>
napisał:
