### ISSUE TITLE
[TF2] The Data Centers in India (Mumbai and Chennai) are not properly configured in Matchmaking

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#6316]
I’ve observed for some time that the data centers in India have no players, regardless of the time, while less popular regions like South Africa or Dubai do have players. When queuing with a VPN on a server located in India, matchmaking always redirects you to a nearby server, but not to India. Because of this, I decided to gather evidence.

### Evidence:

1. Queue in MVM Bootcamp (as sometimes matchmaking connects you to a server with a Bogon IP, which I explain in more detail below).
2. The Coordinator will try to connect you to a Bogon IP (it will always fail, and you’ll see the message “failed after 4 retries”).
![image](https://github.com/user-attachments/assets/98b9057a-978d-420c-92c5-d88fdf2d5bdf)
3. In the server browser (using the SteamAPI), a new server in India appears with the map I queued for.
4. Copy the fake IP of the server that appeared in the server browser.
5. By using the command “connect IP FAKE matchmaking” the game allows you to connect because you’re in the server’s lobby.
![image](https://github.com/user-attachments/assets/53606f14-66b1-4f95-ab17-24d1156034c4)
6. My theory was correct: the servers in India are not properly configured.
![image](https://github.com/user-attachments/assets/de1174c8-643c-467d-882a-b5aef00507ae)

### Observations:

In the "Match History" of "Team Fortress 2 - Personal Game Data," the server will appear without any associated data center.
![image](https://github.com/user-attachments/assets/bc7a857f-1ce2-4a7c-b400-7534602b570d)
Additionally, in TF2, the Mumbai and Chennai data centers do not appear in the server selection.
![image](https://github.com/user-attachments/assets/5fadd0e6-7aa8-4053-8d95-249f231a1442)
_Speculation: It’s possible these servers haven’t been working properly since the implementation of SDR in TF2 or even earlier (though I have no proof at the moment)._

### Additional Information and How I Discovered This: 
While queuing in MVM Boot Camp, I noticed that sometimes the coordinator would connect you to a server with a Bogon IP (100.x.x.x). This seemed curious because the 100.x.x.x format is the same used in some Valve servers
![image](https://github.com/user-attachments/assets/8ae8106c-047c-442e-846d-bdf04bf76e1c)

This led me to suspect that these were the data centers in India, but I had no proof since the "match history" didn’t provide the data center either. So, I decided to gather evidence as I explained above.

Here’s a video of me following the mentioned procedures (there are some cuts to avoid showing personal information and to speed up the video)

https://github.com/user-attachments/assets/216ce126-7e49-419d-b487-e732db74ae6f

I hope this can be fixed 🙏 because having approximately 800 servers in India without players is a waste of resources

**Comment by programmedsun** [comment]
how did a CS2 SDR IP address end up in the MvM Boot Camp?

**Comment by gaelcoral** [comment]
![image](https://github.com/user-attachments/assets/f6d36601-e986-4494-baa5-e0d0b3efaff8)
Fixed?

**Comment by gaelcoral** [comment]
Fixed!
![image](https://github.com/user-attachments/assets/4a67c197-103e-4362-ba20-7148a6e0d232)
