### ISSUE TITLE
[TF2] Ethan's tf2 requests

### ISSUE THREAD

**Issue by EthanTheCool** [ValveSoftware/Source-1-Games#6340]
updates: we want more major updates. the last one was the jungle inferno. its been years since a major update. please make more major updates.  (major updates include at least 2 new weapons, 7 new maps, 10 new cosmetics, and can all be made by the community or valve..)

security: you are doing good at accepting reports and getting rid of cheaters. keep it up!

overall: game is good. but we want major updates back.

**Comment by JoriKos** [comment]
You should probably specify what "major updates" are, because the only thing missing from updates are balance changes and maybe contracts (which are present in SF). I would count the updates we're currently getting as major updates.

**Comment by kisak-valve** [comment]
Hello @EthanTheCool, there's no functional value in tracking a generalized, broad spectrum request to add more content to the game. I expect the Team Fortress 2 dev team is including new content and community contributions as they are able.

Closing as not a specific, actionable issue report.
