### ISSUE TITLE
People on tacobot are worse than bots, they need to be banned

### ISSUE THREAD

**Issue by wolfsmith520-github** [ValveSoftware/Source-1-Games#6341]
Ban all of these accounts on this website please https://tacobot.tf
They are even worse than any kind of bots !

**Comment by wolfsmith520-github** [comment]
Also, they can kick anyone in mann up without using the votemenu. Valve can you explain why?

**Comment by JoriKos** [comment]
I'm not sure this kind of request is in the scope of this github.

**Comment by wolfsmith520-github** [comment]
> I'm not sure this kind of request is in the scope of this github.

The main issue is that they know a bug to kick who ever they want without using the votemenu, I saw that many times, this need to be fixed

**Comment by JoriKos** [comment]
Is there any actual proof they don't use the voting menu? You should also edit the title and body of the issue to reflect this bug report, rather than it being about banning these people.

**Comment by kisak-valve** [comment]
Hello @wolfsmith520-github, account issues are not handled in any capacity on GitHub.

If you find usable details for a Team Fortress 2 dev to ponder regarding the follow up issue you mentioned, then feel free to open a new issue report focusing on that.
