### ISSUE TITLE
(Team Fortress 2) Dragon's Fury projectile doesn't flip with flipped viewmodels

### ISSUE THREAD

**Issue by WayThatWasLoving** [ValveSoftware/Source-1-Games#6348]
Found a video demonstrating this issue while trying to look for confirmation on a different set of issues. According to the video, no other weapon with projectiles has this issue when flipped
https://www.youtube.com/watch?v=g-rhYjPf9SM

**Comment by JoriKos** [comment]
The video is wrong, the Short Circuit's secondary fire also fires from the right regardless of viewmodel setting. Also worth nothing that the Machina's tracer always comes from the right, and fairly certain the Classic's air distortion does as well.

**Comment by kisak-valve** [comment]
Hello @WayThatWasLoving, this issue is already being tracked at #4004. Closing as a duplicate.
