### ISSUE TITLE
[TF2] Graveyard is still broken.

### ISSUE THREAD

**Issue by gdfsgdfg** [ValveSoftware/Source-1-Games#6388]
Current issues in casual is error texture in hud, ghosts aren't replaced by the custom ones and people can't seem to be able to spawn into the map being stuck in spectator mode.

![Untitled](https://github.com/user-attachments/assets/4662b827-95da-467a-8971-6bfc02dff2c5)

**Comment by JoriKos** [comment]
Duplicate of #5257
