### ISSUE TITLE
[TF2] Some people can't find matches in Casual mode

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#6389]
While this hasn't happened to me, I've noticed that some people have been having trouble finding matches in Casual Mode for several weeks now
https://new.reddit.com/r/tf2/search/?q=casual&restrict_sr=1&sort=new

The only solution these people have found is to increase the ping limit to 350 in order to get into a match

Another thing I've noticed is that some data centers have stopped appearing in the matchmaking settings for the past two weeks. I'm not sure if this is related
![image](https://github.com/user-attachments/assets/702eccef-f9f3-4e78-98a6-7c9ef213f117)

**Comment by presario42** [comment]
halloween is gonna be wild this year

**Comment by Thespikedballofdoom** [comment]
My friend from Turkey is getting this problem

**Comment by gaelcoral** [comment]
now I have this problem

**Comment by presario42** [comment]
im being fr here, suffering from this problem too
increasing or decreasing ping doesnr change much tho for me as i end up in south america servers anyway

**Comment by Nephyrin** [comment]
If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.

**Comment by presario42** [comment]
for me it prints:
````
[SDR Ping] Ping data is current as of Tue Oct 15 19:07:09 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 235ms, status 1
    atl: 149ms, status 1
    bom: 0ms, status 2
   bom2: 403ms, status 3
    dfw: 163ms, status 1
    dxb: 400ms, status 1
    eat: 191ms, status 3
    eze: 6ms, status 1
    fra: 229ms, status 1
    gru: 33ms, status 1
    hel: 257ms, status 1
    hkg: 394ms, status 1
    iad: 145ms, status 1
    jfk: 0ms, status 2
    jnb: 383ms, status 1
    lax: 388ms, status 1
    lhr: 217ms, status 1
    lim: 63ms, status 1
    maa: 0ms, status 2
   maa2: 385ms, status 1
    mad: 208ms, status 1
    ord: 160ms, status 1
    par: 225ms, status 3
    scl: 29ms, status 1
    sea: 706ms, status 1
    seo: 431ms, status 3
    sgp: 374ms, status 1
    sto: 236ms, status 1
   sto2: 241ms, status 1
    syd: 344ms, status 1
    tyo: 467ms, status 3
    vie: 251ms, status 1
    waw: 251ms, status 1
```

**Comment by echaskaris** [comment]
Output of tf_datacenter_ping_dump for me. I can't get into casual except with a friend in the party. Ping limit with the friend was 150. When alone the lowest (40 Frankfurt).

https://gist.github.com/echaskaris/07719cedb6831ab3c77be4e4cb57f848

**Comment by echaskaris** [comment]
Setting limit to 350 gave me a match instantly in Stockholm. Same with the setting at the limit of Stockholm. Can't get matched in a Frankfurt server at all (unless in a party, even with me the leader).

Edit: Nvm, got into a Frankfurt server alone, but with ping limit raised

**Comment by presario42** [comment]
as much as i increase the ping limit i always get put into latin american servers
and these tend to have stupid lag spikes randomly

**Comment by echaskaris** [comment]
Try setting ping to 5 above the lowest ping server

**Comment by gaelcoral** [comment]
> as much as i increase the ping limit i always get put into latin american servers and these tend to have stupid lag spikes randomly

Well, seeing that you have 6 ping in the Buenos Aires relay, it makes sense that it puts you in servers in Santiago, Chile, and São Paulo, Brazil, because unlike other Valve games (Dota 2 and CS2), TF2 doesn’t have servers in Buenos Aires

**Comment by presario42** [comment]
it should not take this stupid amount of time for specific maps though

**Comment by elainguill** [comment]
Me (Singapore area) and a friend (East Coast, USA) has been stuck in infinite queues when matchmaking together and we're at a lost what to do. Previously we were able to play just fine together albeit I have a high ping but I don't mind it

Here's the ping data when we're queuing together

Mine (Singapore)
`nectedToMatchServer: 0 HasLobby: 0 AssignedMatchEnded: 1
] tf_datacenter_ping_dump
[SDR Ping] Ping data is current as of Thu Oct 17 02:01:16 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 214ms, status 1
    atl: 244ms, status 1
    bom: 0ms, status 2
   bom2: 84ms, status 1
    dfw: 260ms, status 1
    dxb: 125ms, status 1
    eat: 203ms, status 3
    eze: 439ms, status 1
    fra: 221ms, status 1
    gru: 402ms, status 1
    hel: 245ms, status 1
    hkg: 78ms, status 1
    iad: 263ms, status 1
    jfk: 0ms, status 2
    jnb: 359ms, status 1
    lax: 212ms, status 1
    lhr: 211ms, status 1
    lim: 411ms, status 1
    maa: 0ms, status 2
   maa2: 61ms, status 1
    mad: 206ms, status 1
    ord: 249ms, status 1
    par: 180ms, status 1
    scl: 425ms, status 1
    sea: 189ms, status 1
    seo: 115ms, status 1
    sgp: 42ms, status 1
    sto: 224ms, status 1
   sto2: 232ms, status 1
    syd: 351ms, status 1
    tyo: 102ms, status 1
    vie: 225ms, status 1
    waw: 219ms, status 1
`

Friend (East Coast, USA)
`ams: 119ms, status 1
    atl: 12ms, status 1
    bom: 0ms, status 2
   bom2: 246ms, status 3
    dfw: 32ms, status 1
    dxb: 218ms, status 1
    eat: 73ms, status 3
    eze: 133ms, status 1
    fra: 117ms, status 1
    gru: 114ms, status 1
    hel: 141ms, status 1
    hkg: 215ms, status 1
    iad: 24ms, status 1
    jfk: 0ms, status 2
    jnb: 268ms, status 1
    lax: 63ms, status 1
    lhr: 103ms, status 1
    lim: 85ms, status 1
    maa: 0ms, status 2
   maa2: 268ms, status 3
    mad: 130ms, status 1
    ord: 38ms, status 1
    par: 111ms, status 1
    scl: 113ms, status 1
    sea: 71ms, status 1
    seo: 194ms, status 3
    sgp: 236ms, status 1
    sto: 130ms, status 1
   sto2: 131ms, status 1
    syd: 198ms, status 1
    tyo: 164ms, status 3
    vie: 125ms, status 1
    waw: 133ms, status 1`

**Comment by WildWomble** [comment]
[SDR Ping] Ping data is current as of Wed Oct 16 23:36:35 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 54ms, status 1
    atl: 134ms, status 1
    bom: 0ms, status 2
   bom2: 163ms, status 1
    dfw: 149ms, status 1
    dxb: 172ms, status 1
    eat: 177ms, status 3
    eze: 263ms, status 3
    fra: 35ms, status 1
    gru: 225ms, status 1
    hel: 55ms, status 1
    hkg: 212ms, status 1
    iad: 123ms, status 1
    jfk: 0ms, status 2
    jnb: 211ms, status 1
    lax: 178ms, status 1
    lhr: 48ms, status 1
    lim: 209ms, status 1
    maa: 0ms, status 2
   maa2: 185ms, status 1
    mad: 64ms, status 1
    ord: 135ms, status 1
    par: 52ms, status 1
    scl: 278ms, status 3
    sea: 180ms, status 1
    seo: 249ms, status 3
    sgp: 208ms, status 1
    sto: 65ms, status 1
   sto2: 63ms, status 1
    syd: 336ms, status 1
    tyo: 273ms, status 3
    vie: 21ms, status 1
    waw: 47ms, status 1

**Comment by gaelcoral** [comment]
> If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.


Hello, I noticed that new servers were added for TF2, which is great, but I tried queuing in Warsaw "WAW" (using a VPN) and realized it was impossible to find a match even with all maps selected (I should mention that I used to use a VPN to check the behavior of each region, and I was able to connect in those regions)

![image](https://github.com/user-attachments/assets/513017b1-3f16-4adb-8f0a-3f9871e5f30d)


```
[SDR Ping] Ping data is current as of Fri Oct 18 16:57:58 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 291ms, status 1
    bom: 0ms, status 2
   bom2: 413ms, status 1
    dfw: 308ms, status 1
    dxb: 440ms, status 1
    eat: 330ms, status 1
    eze: 420ms, status 1
    fra: 193ms, status 1
    gru: 398ms, status 1
    hel: 211ms, status 1
    hkg: 382ms, status 1
    iad: 276ms, status 1
    jfk: 0ms, status 2
    jnb: 361ms, status 1
    lax: 338ms, status 1
    lhr: 201ms, status 1
    lim: 392ms, status 1
    maa: 0ms, status 2
   maa2: 396ms, status 1
    mad: 221ms, status 1
    ord: 286ms, status 1
    par: 199ms, status 1
    scl: 422ms, status 1
    sea: 339ms, status 1
    seo: 419ms, status 1
    sgp: 364ms, status 1
    sto: 194ms, status 1
   sto2: 194ms, status 1
    syd: 456ms, status 1
    tyo: 429ms, status 1
    vie: 184ms, status 1
    waw: 174ms, status 1
```

```
TFParty: ID:000253c845b200c3  1 member(s)  LeaderID: [U:1:164059993]
  In 1 queues:
    MatchGroup: 7  Started matchmaking: Fri Oct 18 16:46:21 2024 (1051 seconds ago, now is Fri Oct 18 17:03:52 2024)

party_id: 655069581279427
leader_id: 76561198124325721
member_ids: 76561198124325721
members {
  owns_ticket: true
  competitive_access: true
  player_criteria {
  }
  activity {
    online: true
    client_version: 9270737
  }
}
group_criteria {
  casual_criteria {
    selected_maps_bits: 4294967294
    selected_maps_bits: 4026531839
    selected_maps_bits: 32504832
    selected_maps_bits: 4236247036
    selected_maps_bits: 4294889434
    selected_maps_bits: 4294504447
    selected_maps_bits: 63
  }
  custom_ping_tolerance: 25
}
```

**Comment by Thespikedballofdoom** [comment]
Yeah, vpns specifically are being blocked and I don't understand. We need these tools to play cross-continentally with the preferred server, otherwise one guy can force 5 other people to bad pings even if he's used to playing with high ping

**Comment by RandomBunnie** [comment]
for me, is print like this:
Me (Vietnam): 
[SDR Ping] Ping data is current as of Sat Oct 19 08:00:20 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 229ms, status 1
    bom: 0ms, status 2
   bom2: 87ms, status 1
    dfw: 211ms, status 1
    dxb: 114ms, status 1
    eat: 172ms, status 1
    eze: 423ms, status 1
    fra: 195ms, status 1
    gru: 432ms, status 1
    hel: 217ms, status 1
    hkg: 27ms, status 1
    iad: 229ms, status 1
    jfk: 0ms, status 2
    jnb: 277ms, status 1
    lax: 187ms, status 1
    lhr: 209ms, status 1
    lim: 287ms, status 1
    maa: 0ms, status 2
   maa2: 70ms, status 1
    mad: 223ms, status 1
    ord: 211ms, status 1
    par: 204ms, status 1
    scl: 317ms, status 1
    sea: 163ms, status 1
    seo: 64ms, status 1
    sgp: 39ms, status 1
    sto: 228ms, status 1
   sto2: 227ms, status 1
    syd: 130ms, status 1
    tyo: 75ms, status 1
    vie: 206ms, status 1
    waw: 217ms, status 1

My friend (Chile):
[SDR Ping] Ping data is current as of Fri Oct 18 22:03:14 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 176ms, status 1
    bom: 0ms, status 2
   bom2: 457ms, status 1
    dfw: 159ms, status 1
    dxb: 430ms, status 1
    eat: 215ms, status 1
    eze: 74ms, status 1
    fra: 243ms, status 1
    gru: 102ms, status 1
    hel: 265ms, status 1
    hkg: 438ms, status 1
    iad: 197ms, status 1
    jfk: 0ms, status 2
    jnb: 489ms, status 1
    lax: 192ms, status 1
    lhr: 257ms, status 1
    lim: 124ms, status 1
    maa: 0ms, status 2
   maa2: 440ms, status 1
    mad: 271ms, status 1
    ord: 180ms, status 1
    par: 252ms, status 1
    scl: 94ms, status 1
    sea: 207ms, status 1
    seo: 341ms, status 1
    sgp: 409ms, status 1
    sto: 276ms, status 1
   sto2: 275ms, status 1
    syd: 406ms, status 1
    tyo: 311ms, status 1
    vie: 254ms, status 1
    waw: 265ms, status 1

**Comment by twilightofsun** [comment]
> If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.

hi John,

me and a friend from (both of us from two different regions) have been trying to play Halloween together with no luck. i'm OCE and they're EU, we get stuck in an infinite queue with ALL maps selected with our ping limit set to 350. we've also tried VPN which worked before but now doesn't find any match.. below is our ping dump;

mine (OCE)
> [SDR Ping] Ping data is current as of Sun Oct 20 00:33:36 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 224ms, status 1
    bom: 0ms, status 2
   bom2: 125ms, status 1
    dfw: 229ms, status 1
    dxb: 152ms, status 1
    eat: 191ms, status 1
    eze: 319ms, status 1
    fra: 308ms, status 1
    gru: 324ms, status 1
    hel: 276ms, status 1
    hkg: 109ms, status 1
    iad: 225ms, status 1
    jfk: 0ms, status 2
    jnb: 504ms, status 1
    lax: 197ms, status 1
    lhr: 298ms, status 1
    lim: 282ms, status 1
    maa: 0ms, status 2
   maa2: 108ms, status 1
    mad: 323ms, status 1
    ord: 207ms, status 1
    par: 301ms, status 1
    scl: 299ms, status 1
    sea: 183ms, status 1
    seo: 143ms, status 1
    sgp: 77ms, status 1
    sto: 313ms, status 1
   sto2: 313ms, status 1
    syd: 20ms, status 1
    tyo: 136ms, status 1
    vie: 309ms, status 1
    waw: 314ms, status 1
   
Theirs (EU)
> [SDR Ping] Ping data is current as of Sat Oct 19 16:02:57 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 107ms, status 1
    bom: 0ms, status 2
   bom2: 166ms, status 1
    dfw: 122ms, status 1
    dxb: 153ms, status 1
    eat: 153ms, status 1
    eze: 241ms, status 1
    fra: 35ms, status 1
    gru: 213ms, status 1
    hel: 21ms, status 1
    hkg: 187ms, status 1
    iad: 105ms, status 1
    jfk: 0ms, status 2
    jnb: 192ms, status 1
    lax: 154ms, status 1
    lhr: 31ms, status 1
    lim: 287ms, status 1
    maa: 0ms, status 2
   maa2: 183ms, status 1
    mad: 58ms, status 1
    ord: 108ms, status 1
    par: 38ms, status 1
    scl: 265ms, status 1
    sea: 155ms, status 1
    seo: 224ms, status 1
    sgp: 186ms, status 1
    sto: 14ms, status 1
   sto2: 14ms, status 1
    syd: 278ms, status 1
    tyo: 235ms, status 1
    vie: 37ms, status 1
    waw: 34ms, status 1

**Comment by Orbman2nd** [comment]
> If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.

I have been attempting to que with my friends (NA), Im from Turkey but without the vpn the ques extremely long and it puts all of us into EU servers no matter how many NA party members there are and with the VPN on I cannot solo que into a game at all nor que into a game with my friends

VPN on
[SDR Ping] Ping data is current as of Sat Oct 19 23:52:36 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 160ms, status 1
    bom: 0ms, status 2
   bom2: 412ms, status 1
    dfw: 175ms, status 1
    dxb: 390ms, status 1
    eat: 202ms, status 1
    eze: 270ms, status 1
    fra: 221ms, status 1
    gru: 248ms, status 1
    hel: 230ms, status 1
    hkg: 356ms, status 1
    iad: 144ms, status 1
    jfk: 0ms, status 2
    jnb: 372ms, status 1
    lax: 203ms, status 1
    lhr: 219ms, status 1
    lim: 227ms, status 1
    maa: 0ms, status 2
   maa2: 395ms, status 1
    mad: 237ms, status 1
    ord: 157ms, status 1
    par: 221ms, status 1
    scl: 250ms, status 1
    sea: 206ms, status 1
    seo: 324ms, status 1
    sgp: 364ms, status 1
    sto: 223ms, status 1
   sto2: 223ms, status 1
    syd: 375ms, status 1
    tyo: 294ms, status 1
    vie: 230ms, status 1
    waw: 235ms, status 1

VPN off
[SDR Ping] Ping data is current as of Sun Oct 20 00:05:15 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 150ms, status 1
    bom: 0ms, status 2
   bom2: 170ms, status 1
    dfw: 169ms, status 1
    dxb: 169ms, status 1
    eat: 193ms, status 1
    eze: 276ms, status 1
    fra: 48ms, status 1
    gru: 246ms, status 1
    hel: 71ms, status 1
    hkg: 208ms, status 1
    iad: 134ms, status 1
    jfk: 0ms, status 2
    jnb: 229ms, status 1
    lax: 194ms, status 1
    lhr: 62ms, status 1
    lim: 300ms, status 1
    maa: 0ms, status 2
   maa2: 187ms, status 1
    mad: 77ms, status 1
    ord: 149ms, status 1
    par: 57ms, status 1
    scl: 299ms, status 1
    sea: 196ms, status 1
    seo: 245ms, status 1
    sgp: 211ms, status 1
    sto: 71ms, status 1
   sto2: 71ms, status 1
    syd: 302ms, status 1
    tyo: 255ms, status 1
    vie: 49ms, status 1
    waw: 60ms, status 1

**Comment by Facu-Quaino** [comment]
> If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.

Hi, I've collected data from me and some of my friends, one of them is from Germany, while the rest of us are South American

	winker (germany)

[SDR Ping] Ping data is current as of Sun Oct 20 01:09:43 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 111ms, status 1
    bom: 0ms, status 2
   bom2: 150ms, status 1
    dfw: 126ms, status 1
    dxb: 137ms, status 1
    eat: 153ms, status 1
    eze: 237ms, status 1
    fra: 10ms, status 1
    gru: 213ms, status 1
    hel: 32ms, status 1
    hkg: 230ms, status 1
    iad: 95ms, status 1
    jfk: 0ms, status 2
    jnb: 174ms, status 1
    lax: 155ms, status 1
    lhr: 20ms, status 1
    lim: 208ms, status 1
    maa: 0ms, status 2
   maa2: 167ms, status 1
    mad: 40ms, status 1
    ord: 105ms, status 1
    par: 18ms, status 1
    scl: 238ms, status 1
    sea: 150ms, status 1
    seo: 275ms, status 1
    sgp: 198ms, status 1
    sto: 28ms, status 1
   sto2: 29ms, status 1
    syd: 290ms, status 1
    tyo: 250ms, status 1
    vie: 20ms, status 1
    waw: 25ms, status 1



	sava (Brazil)

[SDR Ping] Ping data is current as of Sat Oct 19 20:39:08 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 130ms, status 1
    gru: 13ms, status 1
    bom: 0ms, status 2
    hel: 203ms, status 1
   bom2: 398ms, status 1
    hkg: 368ms, status 1
    dfw: 148ms, status 1
    iad: 128ms, status 1
    dxb: 371ms, status 1
    jfk: 0ms, status 2
    eat: 190ms, status 1
    jnb: 367ms, status 1
    eze: 41ms, status 1
    lax: 191ms, status 1
    fra: 182ms, status 1
    lhr: 179ms, status 1
    lim: 95ms, status 1
    maa: 0ms, status 2
    sto: 204ms, status 1
   maa2: 407ms, status 1
   sto2: 203ms, status 1
    mad: 153ms, status 1
    syd: 356ms, status 1
    ord: 146ms, status 1
    tyo: 281ms, status 1
    par: 172ms, status 1
    vie: 195ms, status 1
    scl: 66ms, status 1
    waw: 201ms, status 1
    sea: 188ms, status 1
    seo: 311ms, status 1
    sgp: 376ms, status 1



	faqu (argentina)

bom2: 376ms, status 1
[SDR Ping] Ping data is current as of Sat Oct 19 20:09:53 2024. Pending refresh: 0, Sent initial fix: 1
    dfw: 167ms, status 1
    ams: 0ms, status 2
    dxb: 349ms, status 1
    atl: 158ms, status 1
    eat: 194ms, status 1
    bom: 0ms, status 2
    eze: 19ms, status 1
    fra: 239ms, status 1
    gru: 42ms, status 1
    hel: 261ms, status 1
    hkg: 332ms, status 1
    iad: 157ms, status 1
    jfk: 0ms, status 2
    jnb: 396ms, status 1
    lax: 166ms, status 1
    lhr: 241ms, status 1
    lim: 65ms, status 1
    maa: 0ms, status 2
   maa2: 385ms, status 1
    mad: 253ms, status 1
    ord: 179ms, status 1
    par: 234ms, status 1
    scl: 35ms, status 1
    sea: 189ms, status 1
    seo: 321ms, status 1
    sgp: 353ms, status 1
    sto: 262ms, status 1
   sto2: 254ms, status 1
    syd: 318ms, status 1
    tyo: 289ms, status 1
    vie: 253ms, status 1
    waw: 258ms, status 1



	ivany (Argentina)

[SDR Ping] Ping data is current as of Sat Oct 19 20:11:56 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 180ms, status 1
    bom: 0ms, status 2
   bom2: 457ms, status 1
    dfw: 184ms, status 1
    dxb: 430ms, status 1
    eat: 195ms, status 1
    eze: 22ms, status 1
    fra: 252ms, status 1
    gru: 50ms, status 1
    hel: 272ms, status 1
    hkg: 397ms, status 1
    iad: 165ms, status 1
    jfk: 0ms, status 2
    jnb: 407ms, status 1
    lax: 167ms, status 1
    lhr: 252ms, status 1
    lim: 66ms, status 1
    maa: 0ms, status 2
   maa2: 452ms, status 1
    mad: 264ms, status 1
    ord: 182ms, status 1
    par: 241ms, status 1
    scl: 42ms, status 1
    sea: 191ms, status 1
    seo: 335ms, status 1
    sgp: 421ms, status 1
    sto: 273ms, status 1
   sto2: 275ms, status 1
    syd: 328ms, status 1
    tyo: 305ms, status 1
    vie: 265ms, status 1
    waw: 269ms, status 1


	hayley (Uruguay)

[SDR Ping] Ping data is current as of Sat Oct 19 20:18:44 2024. Pending refresh: 0, Sent initial fix: 1
    dfw: 159ms, status 1
    ams: 0ms, status 2
    dxb: 325ms, status 1
    atl: 149ms, status 1
    eat: 204ms, status 1
    bom: 0ms, status 2
    eze: 19ms, status 1
   bom2: 352ms, status 1
    fra: 168ms, status 1
    gru: 32ms, status 1
    hel: 191ms, status 1
    hkg: 344ms, status 1
    iad: 147ms, status 1
    jfk: 0ms, status 2
    jnb: 339ms, status 1
    lax: 170ms, status 1
    lhr: 170ms, status 1
    lim: 69ms, status 1
    maa: 0ms, status 2
   maa2: 369ms, status 1
    mad: 144ms, status 1
    ord: 156ms, status 1
    par: 163ms, status 1
    scl: 39ms, status 1
    sea: 193ms, status 1
    seo: 331ms, status 1
    sgp: 377ms, status 1
    sto: 195ms, status 1
   sto2: 195ms, status 1
    syd: 371ms, status 1
    tyo: 301ms, status 1
    vie: 179ms, status 1
    waw: 190ms, status 1

**Comment by gaelcoral** [comment]
btw @Nephyrin It seems that the new servers in London (LHR), Buenos Aires (EZE), and Warsaw (WAW) have the same issue as the [servers in India](https://github.com/ValveSoftware/Source-1-Games/issues/6316), that is, they are not properly configured, as they always appear empty regardless of the time of day and only display the classic maps (except for some servers that switch to MVM maps, probably boot camp). I’m not sure if it's intentional and they are meant to be launched later

**Comment by Potato-Man5** [comment]
> If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.

] tf_datacenter_ping_dump 
[SDR Ping] Ping data is current as of Sun Oct 20 15:25:04 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 193ms, status 1
    bom: 0ms, status 2
   bom2: 107ms, status 1
    dfw: 177ms, status 1
    dxb: 134ms, status 1
    eat: 151ms, status 1
    eze: 310ms, status 1
    fra: 211ms, status 1
    gru: 311ms, status 1
    hel: 216ms, status 1
    hkg: 60ms, status 1
    iad: 209ms, status 1
    jfk: 0ms, status 2
    jnb: 375ms, status 1
    lax: 170ms, status 1
    lhr: 206ms, status 1
    lim: 271ms, status 1
    maa: 0ms, status 2
   maa2: 90ms, status 1
    mad: 232ms, status 1
    ord: 193ms, status 1
    par: 213ms, status 1
    scl: 290ms, status 1
    sea: 146ms, status 1
    seo: 93ms, status 1
    sgp: 59ms, status 1
    sto: 223ms, status 1
   sto2: 223ms, status 1
    syd: 141ms, status 1
    tyo: 63ms, status 1
    vie: 208ms, status 1
    waw: 218ms, status 1

**Comment by SparkSan** [comment]
> If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.

I'd like to mention that I've been having what seems like a similar issue way before this blew up with the latest updates. I decided to take a look here since it looks similar, but idk if it's actually related. Hopefully you can help me.

The issue I've been having is that ever since South Africa servers were added, I've been **exclusively** matching SA servers in casual. Don't get me wrong, it's good to play with low ping, but it's not always populated, so sometimes I'd like to trade a better ping for the ability to play with more people... 

Anyways, here's the results when I run the command:

heavyweapons.cfg' not present; not executing.
] tf_datacenter_ping_dump
    ams: 0ms, status 2
[SDR Ping] Ping data is current as of Mon Oct 21 00:20:27 2024. Pending refresh: 0, Sent initial fix: 1
    atl: 243ms, status 1
    bom: 0ms, status 2
   bom2: 252ms, status 1
    dfw: 266ms, status 1
    eze: 365ms, status 1
    dxb: 273ms, status 1
    fra: 159ms, status 1
    eat: 288ms, status 1
    gru: 339ms, status 1
    hkg: 235ms, status 1
    hel: 182ms, status 1
    iad: 228ms, status 1
    lax: 289ms, status 1
    jfk: 0ms, status 2
    lhr: 157ms, status 1
    jnb: 43ms, status 1
    lim: 375ms, status 1
    maa: 0ms, status 2
   maa2: 235ms, status 1
    mad: 171ms, status 1
    ord: 245ms, status 1
    par: 151ms, status 1
    scl: 345ms, status 1
    sea: 288ms, status 1
    seo: 270ms, status 1
    sgp: 204ms, status 1
    sto: 180ms, status 1
   sto2: 180ms, status 1
    syd: 295ms, status 1
    tyo: 284ms, status 1
    vie: 170ms, status 1
    waw: 176ms, status 1

**Comment by ottooooooooo** [comment]
> If you are encountering this issue, it would be helpful if you could have every member of your party run `tf_datacenter_ping_dump` and include the results here.

Mine (Australia)
[SDR Ping] Ping data is current as of Wed Oct 23 03:31:48 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 269ms, status 1
    bom: 0ms, status 2
   bom2: 108ms, status 1
    dfw: 249ms, status 1
    dxb: 135ms, status 1
    eat: 244ms, status 1
    eze: 358ms, status 1
    fra: 361ms, status 1
    gru: 401ms, status 1
    hel: 261ms, status 1
    hkg: 92ms, status 1
    iad: 279ms, status 1
    jfk: 0ms, status 2
    jnb: 512ms, status 1
    lax: 216ms, status 1
    lhr: 375ms, status 1
    lim: 317ms, status 1
    maa: 0ms, status 2
   maa2: 91ms, status 1
    mad: 386ms, status 1
    ord: 262ms, status 1
    par: 366ms, status 1
    scl: 339ms, status 1
    sea: 239ms, status 1
    seo: 126ms, status 1
    sgp: 60ms, status 1
    sto: 383ms, status 1
   sto2: 363ms, status 1
    syd: 60ms, status 1
    tyo: 137ms, status 1
    vie: 381ms, status 1
    waw: 387ms, status 1

Friends (Switzerland)
[SDR Ping] Ping data is current as of Tue Oct 22 21:33:00 2024. Pending refresh: 0, Sent initial fix: 1
    ams: 0ms, status 2
    atl: 111ms, status 1
    bom: 0ms, status 2
   bom2: 134ms, status 1
    dfw: 122ms, status 1
    dxb: 154ms, status 1
    eat: 157ms, status 1
    eze: 245ms, status 1
    fra: 18ms, status 1
    gru: 225ms, status 1
    hel: 40ms, status 1
    hkg: 199ms, status 1
    iad: 95ms, status 1
    jfk: 0ms, status 2
    jnb: 175ms, status 1
    lax: 158ms, status 1
    lhr: 23ms, status 1
    lim: 263ms, status 1
    maa: 0ms, status 2
   maa2: 152ms, status 1
    mad: 37ms, status 1
    ord: 112ms, status 1
    par: 18ms, status 1
    scl: 278ms, status 1
    sea: 159ms, status 1
    seo: 236ms, status 1
    sgp: 184ms, status 1
    sto: 37ms, status 1
   sto2: 40ms, status 1
    syd: 276ms, status 1
    tyo: 253ms, status 1
    vie: 28ms, status 1
    waw: 33ms, status 1

**Comment by gaelcoral** [comment]
> btw @Nephyrin It seems that the new servers in London (LHR), Buenos Aires (EZE), and Warsaw (WAW) have the same issue as the [servers in India](https://github.com/ValveSoftware/Source-1-Games/issues/6316), that is, they are not properly configured, as they always appear empty regardless of the time of day and only display the classic maps (except for some servers that switch to MVM maps, probably boot camp). I’m not sure if it's intentional and they are meant to be launched later

Fixed!
![image](https://github.com/user-attachments/assets/8ada3c0f-9ed7-4738-86de-62adf9024a63)

**Comment by gaelcoral** [comment]
For the past few days, there have been no LA servers in TF2. This means that if you have a low ping limit, matchmaking won’t find a match. If you increase the ping to include the next region, then matchmaking will find a match. If I remember correctly, when a region  was unavailable, matchmaking would connect you to a nearby region, but in this case, matchmaking no longer does that

https://github.com/user-attachments/assets/c9e56343-2c46-450e-963e-dd7b56d956c4

In CS2, the LA servers are working fine
![image](https://github.com/user-attachments/assets/cf406b45-1438-4ff0-ba1b-0b3e7caf7866)

**Comment by echaskaris** [comment]
@kisak-valve An update was released and my issues were resolved, though I didn't experience them while in a party.

**Comment by Nephyrin** [comment]
We have deployed several backend fixes for issues around ping and matchmaker performance, including an issue misclassifying player pings that was likely the culprit here.
