### ISSUE TITLE
[TF2] Karting bug on a Carnival of Carnage 

### ISSUE THREAD

**Issue by DizzyArch** [ValveSoftware/Source-1-Games#6402]
I would like to report a bug on a map Carnival of Carnage, on a falling platforms event. One of my teammates flew over the map and hang on a top of it, meaning that game endlesslycontinued, please fix thig bug.
![20241007214153_1](https://github.com/user-attachments/assets/a189b564-1b4f-4f01-87c6-0afaf7fde4cc)

**Comment by kisak-valve** [comment]
Hello @DizzyArch, this issue is already being tracked at #5250. Feel free to add a note to that issue report.

Closing in favor of the older issue report.
