### ISSUE TITLE
[DOD:S] game_text entity is non-functional

### ISSUE THREAD

**Issue by sonoma-hyenaz** [ValveSoftware/Source-1-Games#6406]
Hello, I'm reporting a bug with the `game_text` entity with Day of Defeat: Source.

Here I have a `game_text` entity set up to display a message to players
![image](https://github.com/user-attachments/assets/9382aee6-ef1b-48c8-a542-539b794e050f)

It gets activated by a `trigger_multiple` with an `OnTouching` input
![image](https://github.com/user-attachments/assets/6fc5a95b-b87d-492a-8a8d-9db5d72905bc)

However in-game it does not display the message, even though the player touches this trigger, I also tried to see if any other channels worked but they did not, Channels 1-4 are non-functional. I even tried setting the spawnflag "All Players" just to check and it still does not display the message

I also tried using `ent_fire` on the `game_text` entity and it still would not display the message

**Comment by kisak-valve** [comment]
Hello @sonoma-hyenaz, this issue is already being tracked at #5422. Since this issue report adds some more detail, I've gone ahead and transferred it to https://github.com/ValveSoftware/Source-1-Games/issues/5422#issuecomment-2400605742.
