### ISSUE TITLE
Portal Achievements Do Not Pop Up When Disconnected

### ISSUE THREAD

**Issue by Fedmonger** [ValveSoftware/Source-1-Games#6412]
Multiple people have said that they did not complete a certain achievement (Vanilla Cake Crazy, Aperture Science, etc.) only because they disconnect from the network. The only way to fix this is to delete all data- obviously not viable. Please help!

**Comment by kisak-valve** [comment]
Hello @Fedmonger, this issue is already being tracked in a handful of issue reports (#981 #3502 #3593 #5570). Closing as a duplicate.
