### ISSUE TITLE
[TF2] The Community_maps_5 node is not connected to Scream Fortress contract

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#6414]
![image](https://github.com/user-attachments/assets/fddf587a-6fca-4d72-884d-160280db8191)

**Comment by NO-LOAFING** [comment]
for the record, this isn't a visual bug, it's actually impossible to start any of the contracts in that category right now

**Comment by PapaTurby** [comment]
Attached video file showing the issue. This entire branch is inaccessible.

https://github.com/user-attachments/assets/d668fe6d-0128-4d46-a0b3-e886054d47cb

**Comment by mtxfellen** [comment]
This has been rectified and the new contracts can now be completed.
![image](https://github.com/user-attachments/assets/64c46f5a-e8fc-4a11-b3db-8f50b94d0724)

**Comment by KimmyTF2** [comment]
Fixed

https://github.com/user-attachments/assets/c70c9013-2d5d-4764-9874-c54817e12137

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
