### ISSUE TITLE
Major Missing Texture on zi_blazehattan

### ISSUE THREAD

**Issue by PapaTurby** [ValveSoftware/Source-1-Games#6416]
Self-explanatory.

![Screenshot_220](https://github.com/user-attachments/assets/f6548d79-06c0-4f4f-8e0c-1ef4293db352)

**Comment by NULLYUKI** [comment]
According to patch [230932](https://www.teamfortress.com/post.php?id=230932)

>Updated zi_blazehattan (additional changes)
> - Fixed missing textures behind the windows of the warehouse building 

Please retest this issue.

**Comment by KimmyTF2** [comment]
Fixed
![blaze](https://github.com/user-attachments/assets/4fc95849-af1e-4a73-9510-d49d7ad53e81)

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
