### ISSUE TITLE
[TF2] UI Scaling has messed up the scoreboard and other UI elements

### ISSUE THREAD

**Issue by MrConeMan** [ValveSoftware/Source-1-Games#6427]
My Monitor Resolution is 1920x1080 and Ive experienced the following issues

Scoreboard is not displaying casual ranks
![Scorebaord](https://github.com/user-attachments/assets/ad61c413-e437-44f9-b46a-a0ca250e0dd9)

Some UI Menus are Ridiculously large
![image](https://github.com/user-attachments/assets/da535549-6c0e-4800-885f-5127dd83be29)
![image](https://github.com/user-attachments/assets/a05438b9-cb8c-4440-81cd-924dc2077d23)

**Comment by JoriKos** [comment]
Duplicate of #6418
