### ISSUE TITLE
[TF2] [Bug] Multiplied heal on zombie medic

### ISSUE THREAD

**Issue by Kakamaka35** [ValveSoftware/Source-1-Games#6428]
if in zi map use console comand "load_itempreset" on zombie medic you **multiplied** your passive heal teammates. Also this save if you dead. here proof and steps ->  https://youtu.be/qh8UHxndQ20
(sorry for my bad englisch)

**Comment by Squid-Eevee** [comment]
seems this also persist across class changes.

edit: looks like you can also heal people while spectating. oops!
it's also _really_ loud if you stack it enough times. it literally cuts all other audio.
