### ISSUE TITLE
[TF2] Broken Scoreboard

### ISSUE THREAD

**Issue by presario42** [ValveSoftware/Source-1-Games#6429]
not much to describe, all icons are gone and there is no spacing, on Gorge Event it's worse
![cp_gorge_event0000](https://github.com/user-attachments/assets/6f5c0399-3e5d-457b-b76f-368507fc6338)
![koth_toxic0005](https://github.com/user-attachments/assets/8c2c8cd8-4e21-4758-9a50-cd0e509fdef9)

**Comment by JoriKos** [comment]
Are you using a custom hud?

**Comment by TorutheRedFox** [comment]
my scoreboard name labels are for some reason no longer aligned to the left and the player's avatar is missing from the freezecam

the context menu when mouse mode is enabled is also gigantic

**Comment by presario42** [comment]
> Are you using a custom hud?

toonhud but default hud is also suffering from this problem

**Comment by presario42** [comment]
> the context menu when mouse mode is enabled is also gigantic

suffering this too

**Comment by Ashetf2** [comment]
probably not an issue with the game. Wait for your hud to update

**Comment by TorutheRedFox** [comment]
default hud suffers from this too

something with the new scaling code is broken

**Comment by SanAntonio2** [comment]
Same issue
![tf_win64 2024-10-13 20-43-07-184](https://github.com/user-attachments/assets/c670deed-c1d5-4b50-8e57-9bcac028c883)

**Comment by presario42** [comment]
genuinely wondering who is thumbing down all the issues

**Comment by presario42** [comment]
also the bug affects some specific maps, in some the scoreboard works correctly, on others some icons appear but its still broke and on othwrs straight up that scaling vomit

**Comment by TorutheRedFox** [comment]
> genuinely wondering who is thumbing down all the issues

you can hover over the reaction to see who left it (psst it's @ImAllowedToDoThis)

**Comment by hvhlord** [comment]
i also got this issue hope toonhub fixes it soon

**Comment by presario42** [comment]
doubt it's the hud since i recently switched to HexHUD and it also suffers from this problem

**Comment by TorutheRedFox** [comment]
yeah it's definitely not the HUDs themselves, it's the code overriding their sizing attributes for the new DPI scaling feature

**Comment by JoriKos** [comment]
You mean UI scaling? I don't think there's DPI scaling. The custom HUDs are probably outdated, because no one has confirmed this with the default HUD yet, so this wouldn't be appropriate to report here.

**Comment by MooZonkey** [comment]
I had this same exact issue. I deleted my HUD folder and that fixed it. The new scream fortress update has been causing a lot of random issues for people, especially linux users.

**Comment by JoriKos** [comment]
> The new scream fortress update has been causing a lot of random issues for people, especially linux users.

They pushed the ui scaling, which was to fix an issue with the UI not being properly scaled (shocker). This messed up a lot of custom HUDs.

**Comment by gdfsgdfg** [comment]
UI scaling has slightly broken my score board as well, ping and score are extremely close to each other now.

**Comment by SanAntonio2** [comment]
> Same issue 


I updated the hud and the problem disappeared.
I'm not quite sure if updating the hud helped, there have been several updates to the game in the meantime.
![tf_win64 2024-10-20 15-51-50-886](https://github.com/user-attachments/assets/84940caa-f5e8-4f97-a625-ce2990301f77)

**Comment by TorutheRedFox** [comment]
HUDs updated to work around the issues

**Comment by CriticalFlaw** [comment]
This ticket should be closed because the issue concerns only custom HUDs which will be fixed by their respective authors over time. There's no issue with the default HUD.

**Comment by presario42** [comment]
issue seems to now be fixed, closing
