### ISSUE TITLE
[TF2 Feature Required] Auto change headphone

### ISSUE THREAD

**Issue by wolfsmith520-github** [ValveSoftware/Source-1-Games#6431]
I am not sure if this is my issue, but every time I started TF2, then connect my headphones to my pc, TF2 won't change it automatically. Instead, I need to restart the game or change the speaker configuration in the audio settings. 

This is a small issue, but it focsed me restart the game before I know the settings. Hope can get this feature. Or just add a headphone switch menu

**Comment by kisak-valve** [comment]
Hello @wolfsmith520-github, this issue is already being tracked at #5694. Closing as a duplicate.
