### ISSUE TITLE
[TF2] Missing string for TF_Wearable_Wound

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#6434]
The Defaced Detonator received a new item type, 'Wound', but it's missing from localization files, which results in it displaying as '(null)'.
![face](https://github.com/user-attachments/assets/1ccd112f-9704-4fce-b509-5f71edb7ac2d)

**Comment by JoriKos** [comment]
Should be fixed with newest update

**Comment by KimmyTF2** [comment]
It's fixed
![WOUND](https://github.com/user-attachments/assets/5fbc26fc-bd45-4da7-b613-aa60282f037a)

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
