### ISSUE TITLE
[TF2] The Crook Combatant hides the Scout's dogtags

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#6440]
Copied from the Wiki:
When equipped, the [Crook Combatant](https://wiki.teamfortress.com/wiki/Crook_Combatant) will cause the Scout's dogtags to disappear.
This item is a pair of gloves. Obviously they shouldn't hide the Scout's dogtags.

![Crook_Combatant](https://github.com/user-attachments/assets/fd228d46-eb45-4ba6-b612-8396d31587b7)
![tags](https://github.com/user-attachments/assets/a50a3570-5ce9-4035-83eb-bdcfecbc6618)

**Comment by kisak-valve** [comment]
Hello @KimmyTF2, per "Fixed the Crook Combatant hiding the Scout's dog tags" in the [2024-10-24](https://www.teamfortress.com/post.php?id=231496) Team Fortress 2 update, please retest this issue.

**Comment by KimmyTF2** [comment]
> Hello @KimmyTF2, per "Fixed the Crook Combatant hiding the Scout's dog tags" in the [2024-10-24](https://www.teamfortress.com/post.php?id=231496) Team Fortress 2 update, please retest this issue.

It's fixed.
![440_1](https://github.com/user-attachments/assets/5b6d4f80-731e-425c-89a8-cc4424f40252)
