### ISSUE TITLE
[TF2] The Hound's Hood and the Thrilling Tracksuit refer to non-existent bodygroups

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#6444]
Copied from the Wiki:
* The item schema is configured to disable the Scout's "beard" bodygroup, however, Scout has no beard on his model or a bodygroup associated with it; neither does the [Hound's Hood](https://wiki.teamfortress.com/wiki/Hound%27s_Hood) itself.
* The item schema is configured to disable the Scout's "head" bodygroup, however, such bodygroup does not exist for either the Scout or the [Thrilling Tracksuit](https://wiki.teamfortress.com/wiki/Thrilling_Tracksuit).

I'm adding both items into one issue because this is not affecting them visually; it's only a mistake in the items_game text file. Neither "beard" nor "head" bodygroups exist. They were most likely mistakenly added instead of equip regions. If this was actually the case, then "beard" should be moved to "equip_region" for the Hound's Hood as it covers the Scout's chin.

![hood](https://github.com/user-attachments/assets/dd73aa63-65bf-4c68-ac1e-e56a00f67905)
![track](https://github.com/user-attachments/assets/c77e1376-1652-4858-8432-32cab984cca3)

**Comment by kisak-valve** [comment]
Hello, per "Updated the schema entries for The Hound's Hood and the Thrilling Tracksuit to remove unused settings" in the [2024-10-24](https://www.teamfortress.com/post.php?id=231496) Team Fortress 2 update, please retest this issue.

**Comment by KimmyTF2** [comment]
> Hello, per "Updated the schema entries for The Hound's Hood and the Thrilling Tracksuit to remove unused settings" in the [2024-10-24](https://www.teamfortress.com/post.php?id=231496) Team Fortress 2 update, please retest this issue.

Yes, they were removed. Moving the "beard" to "equip_region" wasn't implemented, but I guess Valve doesn't want to touch equip regions for now. You can close this issue as completed.
