### ISSUE TITLE
[TF2] Mute menu was reverted to older version

### ISSUE THREAD

**Issue by As0mn** [ValveSoftware/Source-1-Games#6449]
Read title, Scream Fortress 2024 somehow reverted the mute menu back to the old one. 
![Screenshot 2024-10-15 194646](https://github.com/user-attachments/assets/83f49098-6d77-48df-950c-758116fb3b86)

**Comment by jh34ghu43gu** [comment]
What is different? This looks the same as the example on the wiki but it was uploaded in 2021 so any changes made since then aren't reflected https://wiki.teamfortress.com/wiki/File:Mute_Player.png

**Comment by As0mn** [comment]
Ah, you're right. The UI scaling made it appear so much smaller that I thought it was different, it used to take up most of the screen.
