### ISSUE TITLE
[HL2] Murky water from a fresh play-through

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/Source-1-Games#645]
I cant seem to reproduce this, but posting in case others or me can in future.
Launched the game, adjusted some options and started a fresh play-through, the first time I saw water it looked like the Thames:
![2013-05-10_00057](https://f.cloud.github.com/assets/7708/495018/4d8f29d4-bbb2-11e2-9253-e9d058637e71.jpg)

And further on in route canal,
![2013-05-10_00070](https://f.cloud.github.com/assets/7708/495021/6e9b5b66-bbb2-11e2-8221-9c477c3eefd2.jpg)
![2013-05-10_00081](https://f.cloud.github.com/assets/7708/495029/8a1958ca-bbb2-11e2-8ed8-cefd27c87884.jpg)

Then it was lunch, so quit to the menu and it had changed the menu level
![2013-05-10_00084](https://f.cloud.github.com/assets/7708/495032/b7c09f40-bbb2-11e2-876f-b2755089c9b2.jpg)
and the water was back to normal ingame…
![2013-05-10_00086](https://f.cloud.github.com/assets/7708/495033/c1f41fdc-bbb2-11e2-8c65-151d9e0515cc.jpg)

System info https://gist.github.com/johndrinkwater/4721913

**Comment by kisak-valve** [comment]
Hello @johndrinkwater, since there hasn't been any other reports of this issue, I'm assuming it was a rare quirk or driver bug. Closing pending feedback that this is still occurring.
