### ISSUE TITLE
[TF2] Reduce the crate drop rate for players in the Netherlands/Belgium

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#6457]
As the title says, Netherlands/Belgium-based players have no use for these crates, except to sell them on the market for 1 cent (which almost never sells). It may also take the place for an actual item from the system, especially with the limited backpack space F2P users have.

**Comment by kisak-valve** [comment]
Hello @JoriKos, this is a request for an anti-feature.

**Comment by JoriKos** [comment]
Only the removal of the drops entirely (which I have removed now), but I think reducing the rate at which they drop isn't necessarily an anti-feature.
