### ISSUE TITLE
[TF2] Freaky Fair's pumpkin bomb kills bonus objective not possible  

### ISSUE THREAD

**Issue by Trash-Bandit-Mina** [ValveSoftware/Source-1-Games#6460]
On `cp_freaky_fair` the second bonus objective of getting 6 pumpkin bomb kills is not completable because there is no pumpkin bombs on the map.

**Comment by IronFoxGaming** [comment]
Can confirm, there aren't any pumpkin bombs set on the map. It would be nice if instead the contract was for using some of the one-shot canteen abilities, like the pumpkin buster and ghost transformation, as that would encourage people to try those more often.

**Comment by kisak-valve** [comment]
Hello, per `Updated Freaky Fair's expert contract to be "Win a round on Freaky Fair"`in the [2024-10-24](https://www.teamfortress.com/post.php?id=231496) Team Fortress 2 update, please retest this issue.

**Comment by Trash-Bandit-Mina** [comment]
Yup, i was able complete the new bonus objective. TYSM
