### ISSUE TITLE
[TF2] Can't join Casual match with ping slider all the way to the left

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/Source-1-Games#6463]
Used to work before the scream fortress update. Though, matchmaking issues were reported shortly before scream fortress launched and I had not played TF2 for some time.

**Comment by kisak-valve** [comment]
Hello @echaskaris, this issue is already being tracked at #6389 / #6441. Closing as a duplicate.

**Comment by echaskaris** [comment]
Okay, but I haven't seen anyone report this specifically there.

To add more info, I'm in EU and lowest ping is Frankfurt servers. I can get a match in Frankfurt, but I have to set the ping limit above the ping reported for Frankfurt.
