### ISSUE TITLE
[TF2] [Feature Request] Allow players to turn in finished contracts as soon as they are completed

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#6470]
Currently, to turn in a contract, players are forced to first finish a round. Not only is this frustrating as a player could turn in the contract and move on to the next one, they can lose all progress made during the round if they disconnect from the server for any reason, like technical problems or being kicked from it. Additionally, during Halloween, when everyone is doing the same contract, after the round ends and most players are doing the same contract, the server is dead. Matchmaking takes ages to fill empty player slots.

With this change, players could finish their contract, disconnect from the server at any time without losing progress, and move on to the next contract, and their slot could be filled faster by a new player.

**Comment by kisak-valve** [comment]
Hello @KimmyTF2, this is functionally the same feature request as #4403. Closing as in favor of the older issue report.
