### ISSUE TITLE
HL2 & Others - Weapon Categories Swapped

### ISSUE THREAD

**Issue by d10sfan** [ValveSoftware/Source-1-Games#648]
After using a 360 controller with HL2 (used big picture mode to start it), the weapon categories on keyboard are swapped. For example, 3 is the crowbar, 1 is the pistol, and 2 is the smg. I checked and my slots are set correctly in the keybindings.

**Comment by chriscatwhovian** [comment]
try this? https://steamcommunity.com/app/220/discussions/0/613957600523278765/
