### ISSUE TITLE
Scout has wrong colors on the BLU team with specific cosmetic

### ISSUE THREAD

**Issue by sabaani** [ValveSoftware/Source-1-Games#6486]
Scout's pants were updated to display the true color of the pants but some cosmetics were not updated to be consistent.
![loadout (1)](https://github.com/user-attachments/assets/9d298b26-b2a0-44c7-b152-404ca69fb8c1)
![loadout (2)](https://github.com/user-attachments/assets/17e8668d-69e8-4c1a-aadd-c274eb0cb8fd)
![loadout (3)](https://github.com/user-attachments/assets/01f2b677-1df9-446e-b6e8-b237b7acc0f1)
![loadout (4)](https://github.com/user-attachments/assets/573e109b-31a7-4fa3-a917-accd1dfda0e8)
![loadout (5)](https://github.com/user-attachments/assets/fac74b31-20ee-4ac2-9760-4be1765882f3)

**Comment by KimmyTF2** [comment]
I was about to post this. All pants (and not only) cosmetics are using old RED color variant. All of them need texture changes too. Someone even added a [contribution to the Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=2881498552) for a few of them.
Edit: Please don't be this another "only creators can modify their items" situation. Some of them date back 10 years and idk if they would be able to do it.

**Comment by Chickenman456** [comment]
Just so it's not missed, I would also like the point out the Talon Trotters have been affected as well

![image](https://github.com/user-attachments/assets/02082099-e2c4-4c47-9d37-c19204997395)

**Comment by caw-caw-robinjay** [comment]
not just pants were broken by changing scout's colors! this change also causes issues with the ye olde baker boy,
![image](https://github.com/user-attachments/assets/2a0f1eed-02b9-4524-84a4-ce394559ea68)
ye oiled baker boy,
![image](https://github.com/user-attachments/assets/f0ffb937-abb3-4299-a8e0-73e033dbd9d5)
flapjack,
![image](https://github.com/user-attachments/assets/37fe165e-5f9a-470e-b8fe-c7aa443e13bb)
courtier's collar,
![image](https://github.com/user-attachments/assets/23653266-2aee-494d-b5d4-b3cb9f1cca25)
wipe-out wraps,
![image](https://github.com/user-attachments/assets/f9891e0f-1aa3-4639-b096-cc5a1d3f317d)
and corpse carrier.
![image](https://github.com/user-attachments/assets/5f22c322-8f3e-4c43-8e1f-5f70874d888b)

**Comment by caw-caw-robinjay** [comment]
a few more i forgot to add:
the bootenkhamuns,
![image](https://github.com/user-attachments/assets/219f8c58-1dce-447e-8ce6-a05531fe64e7)
flak jack,
![image](https://github.com/user-attachments/assets/3a7f4a9e-7476-4c6c-8c53-034897f0fc87)
seasonal employee,
![image](https://github.com/user-attachments/assets/f87da4d2-3272-4615-a43d-eaf7eb81467c)
ripped rider (see the buttons),
![image](https://github.com/user-attachments/assets/a6939a6a-0c27-4dca-9a3f-fdeec3fc2c52)
boarder's beanie,
![image](https://github.com/user-attachments/assets/27760e6c-8aa8-41fc-9aed-bbbcd212d558)
and the tanker's top (see the undershirt).
![image](https://github.com/user-attachments/assets/216da84e-c536-4320-be83-aa98d7d100b7)

**Comment by caw-caw-robinjay** [comment]
the scout robot also hasn't been fixed:
![image](https://github.com/user-attachments/assets/573f1a93-44d8-45d3-ba51-9540410b2cda)

**Comment by caw-caw-robinjay** [comment]
the masked fiend's horns also need a color change.
![image](https://github.com/user-attachments/assets/410b7d44-03b1-4ef3-9601-56d392435f6a)

**Comment by caw-caw-robinjay** [comment]
yet more colors that need to be fixed if scout's pants are to stay changed:
the big elfin deal,
![image](https://github.com/user-attachments/assets/4e6d7be8-2788-4547-b440-02d770f3295e)
the bootie time,
![image](https://github.com/user-attachments/assets/108d91bf-a19b-4574-ab33-619bf9399ed7)
the teufort tooth kicker,
![image](https://github.com/user-attachments/assets/65c29e51-baa5-455a-8b69-0d2bd36a70a0)
the flunkywear (see the pocket),
![image](https://github.com/user-attachments/assets/b352a25b-cedb-4173-95bb-604d588f7e9b)
and the poolside polo (see the paintable region),
![image](https://github.com/user-attachments/assets/a768531b-0815-422d-a100-c4d1e5b7ace6)

**Comment by caw-caw-robinjay** [comment]
the scout's default hat also now no longer matches his pants.
![image](https://github.com/user-attachments/assets/c72193d9-f5df-4e3d-9d33-dd621de2f1d2)

**Comment by Chickenman456** [comment]
I highly suggest viewing these items in TFMV/HLMV, not Loadout.Tf

Loadout.tf uses its own rendering engine that looks completely different from what’s in the actual game. The colors aren’t goin to be particularly accurate.

With that being said - the default hat isn’t supposed to match the pants. Some of these other suggestions feel like huge stretches

**Comment by caw-caw-robinjay** [comment]
> I highly suggest viewing these items in TFMV/HLMV, not Loadout.Tf
> 
> Loadout.tf uses its own rendering engine that looks completely different from what’s in the actual game. The colors aren’t goin to be particularly accurate.
> 
> With that being said - the default hat isn’t supposed to match the pants. Some of these other suggestions feel like huge stretches

I feel loadout.tf is sufficient for the purposes of illustrating the issues, if not getting exact colors. Some of these are stretches, certainly, but I figure it's better to show _all_ the potential issues and leave the developers sort out which are relevant enough to fix, rather than leave some out and create issues later.

**Comment by KimmyTF2** [comment]
Please don't post more images. Just link items to the Wiki. Wiki is using images created in HLMV.

**Comment by caw-caw-robinjay** [comment]
> Please don't post more images. Just link items to the Wiki. Wiki is using images created in HLMV.

Can do! Apologies :)

**Comment by gaelcoral** [comment]
:/
The best solution was for BLU Scout to use the old texture for the cosmetics that have conflicts
![image](https://github.com/user-attachments/assets/e2f27400-ac5f-4703-9fc0-6a50a9932225)

**Comment by KimmyTF2** [comment]
Well I expected this. TF2 Team really needs more workpower.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.

**Comment by sabaani** [comment]
We killed it. We killed the BLU pants oh god :C
