### ISSUE TITLE
[TF2] Certain cosmetics involving scouts pants do not have a BLU varient

### ISSUE THREAD

**Issue by HueyCan** [ValveSoftware/Source-1-Games#6487]
The [October 24, 2024](https://www.teamfortress.com/post.php?id=231496) patch of TF2 has fixed BLU scout's pants from not being team colored properly, however this has made certain cosmetics that either are a separate model or connected to scout's model not have a BLU variant
![pants1](https://github.com/user-attachments/assets/fa33aa87-fe81-441f-b542-df35841b55d6)
![pants2](https://github.com/user-attachments/assets/a029eead-5059-4b94-965f-1badda1c3f18)
![pants3](https://github.com/user-attachments/assets/320b9044-0b00-4b6b-9cfe-9cc5d1267665)

**Comment by kisak-valve** [comment]
Hello @HueyCan, this issue is already being tracked at #6486. Closing as a duplicate.
