### ISSUE TITLE
[TF2] You can put on two of the same cosmetic (Hallowed Headcase)

### ISSUE THREAD

**Issue by an-abomination** [ValveSoftware/Source-1-Games#6490]
This bug effects the halloween restricted cosmetic called "Hallowed Headcase" for the sniper.

I've checked the TF2 Wiki to see if this bug has already been found and found this:
"This item is set up to have equip regions for "Hat" and "Face", but does not due to incorrectly using equip_region to define multiple equip regions."

It may have something to do with that but i have no idea.

Not anything crazy but it's still not intended

**Comment by kisak-valve** [comment]
Hello @an-abomination, this issue is already being tracked at #4102. Closing as a duplicate.
