### ISSUE TITLE
[TF2] Scout's belt loops are still BLU

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#6493]
The Scout's belt loops are still BLU, mismatching the rest of the pants. If the BLU pants are reverted forever, I think this should be changed too.

**Comment by kisak-valve** [comment]
Hello @JoriKos, this issue is already being tracked at #2289. Closing as a duplicate.

**Comment by JoriKos** [comment]
That one is about the pants being the RED texture, but this one is about the belt loops being the wrong texture.
