### ISSUE TITLE
(TF2) Game Crashes when changing matches in Casual

### ISSUE THREAD

**Issue by RiseReborn** [ValveSoftware/Source-1-Games#6505]
I will usually crash when I either stay in a lobby for a new match or connect to a different lobby mid match, but less when Im already in que for casual. 

For more detail, the match ends and I stay for the next game or I leave the lobby, see the loading screen, then see where im going for the game, then crash within the second of me seeing this, start the game (again), and then join the game in the pop up like how i would if i suddenly left it and thats how im still able to play games continuously with the crashes.

Other info
It happens in casual on both halloween and regular maps.
It doesn't happen on any of the community servers that I've tried like skial, uncle topia, etc.
I am using master comfig on low settings but that has worked until about the patch on Oct 24 or 25.

Thank you for continuing to work on one of the greatest games in history (GOATed)!

log from code right after crash
``
For FCVAR_REPLICATED, ConVar must be defined in client and game .dlls (sv_use_steam_voice)
Both ConVars must be marked FCVAR_REPLICATED for linkage to work (r_VehicleViewDampen)
[TF Workshop] Got 9 subscribed maps, 9 new
ProtoDefs post data loaded.
ProtoDefs loaded. 43.17 MB used
ProtoDefs post data loaded.
ProtoDefs loaded. 43.17 MB used
maxplayers set to 24
Steam config directory: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\platform\config
CClientSteamContext logged on = 1
Convar tf_impactwatertimeenable has conflicting FCVAR_CHEAT flags (child: FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Parent cvar in server.dll not allowed (tf_mvm_max_connected_players)
Convar cl_particle_retire_cost has conflicting FCVAR_CHEAT flags (child: FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Both ConVars must be marked FCVAR_REPLICATED for linkage to work (r_VehicleViewDampen)
Convar r_drawropes has conflicting FCVAR_CHEAT flags (child: FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
ProtoDefs post data loaded.
ProtoDefs loaded. 43.17 MB used
ProtoDefs post data loaded.
ProtoDefs loaded. 43.17 MB used
Cleaning up unneeded replay block data...
Replay cleanup done.
Loading default settings for high sensitivity
ProtoDefs post data loaded.
ProtoDefs post data loaded.
Connection to game coordinator established.
Current item schema is up-to-date with version 7C556932.
CTFGCClientSystem::PostInitGC
CTFGCClientSystem - adding listener
ProtoDefs post data loaded.
ProtoDefs post data loaded.
'overrides/pre_comfig.cfg' not present; not executing.
Lobby-based matchmaking mode not active
Can't alias "kill" as it's already a ConCommand or ConVar and not an input command (+/-).
Can't alias "explode" as it's already a ConCommand or ConVar and not an input command (+/-).
Can't alias "commentary_finishnode" as it's already a ConCommand or ConVar and not an input command (+/-).
Unknown command "r_shadowlod"
Unknown command "cat_ipc_exec_all"
Unknown command "cat_detach"
Unknown command "block_game_overrides_once"
'overrides/setup_hook.cfg' not present; not executing.
Low preset selected 
Disable Pyroland addon applied 
Flat Mouse addon applied 
'addons/lowmem.cfg' not present; not executing.
'addons/no-footsteps.cfg' not present; not executing.
No Soundscapes addon applied 
No Tutorial addon applied 
'addons/null-canceling-movement.cfg' not present; not executing.
'addons/opengl.cfg' not present; not executing.
Transparent Viewmodels addon applied 
'overrides/modules.cfg' not present; not executing.
Modules applied 
 

Can't alias "mat_antialias" as it's already a ConCommand or ConVar and not an input command (+/-).
Creating fallback sound cache at: c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\sound_workshop
Can't use cheat cvar fog_start in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_end in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_startskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_endskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar r_farz in multiplayer, unless the server has sv_cheats set to 1.
[PartyClient] Joining party 656621177185081
[PartyClient] Became leader of party 656621177185081
Differing lobby received. Lobby: [A:1:1320994827:31613]/Match98960687/Lobby656621091929828 CurrentlyAssigned: [I:0:0]/Match0/Lobby0 ConnectedToMatchServer: 0 HasLobby: 1 AssignedMatchEnded: 0
[TF Workshop] Got updated information for map [ workshop/trimp_devramps.ugc454140755 ]
[TF Workshop] Got updated information for map [ workshop/jump_pyrokinesis_rc1.ugc1621067105 ]
[TF Workshop] Got updated information for map [ workshop/jump_4starters.ugc585573538 ]
[TF Workshop] Got updated information for map [ workshop/trimp_starter.ugc952322926 ]
[TF Workshop] Got updated information for map [ workshop/jump_trimp_b1.ugc2222898995 ]
[TF Workshop] Got updated information for map [ workshop/ctf_2fort_trimp.ugc2823633895 ]
[TF Workshop] Got updated information for map [ workshop/tr_mannedmachines_rc1d.ugc2649883639 ]
[TF Workshop] Got updated information for map [ workshop/trimp_wavy.ugc1577299212 ]
[TF Workshop] Got updated information for map [ workshop/trimp_hops.ugc1167557962 ]
Sending request to abandon current match
Sending request to exit matchmaking, marking assigned match as ended
Lobby destroyed
Differing lobby received. Lobby: [I:0:0]/Match0/Lobby0 CurrentlyAssigned: [A:1:1320994827:31613]/Match98960687/Lobby656621091929828 ConnectedToMatchServer: 0 HasLobby: 0 AssignedMatchEnded: 1

``

System information
OS Name	Microsoft Windows 10 Home
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	ASS-FART69
System Manufacturer	HP
System Model	HP Spectre x360 Convertible 13-ap0xxx
System Type	x64-based PC
System SKU	7YA98UA#ABA
Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1992 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	AMI F.40, 2019-11-29
SMBIOS Version	3.2
Embedded Controller Version	9.72
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	8514
BaseBoard Version	09.72
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.3636"
User Name	(Private info)
Time Zone	Pacific Standard Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.71 GB
Available Physical Memory	1.34 GB
Total Virtual Memory	14.0 GB
Available Virtual Memory	5.14 GB
Page File Space	6.25 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by kisak-valve** [comment]
Hello @RiseReborn, this issue is already being tracked at #5885. Closing in favor of the older issue report.

**Comment by RiseReborn** [comment]
No this is a different issue because it only crashes when I change servers and games, including when its the same map and they cited it as being for community when this is recently in casual only.
