### ISSUE TITLE
Incorrect voice lines used for magic spells Overheal and Swarm of Bats and proposal of missing voice line for spell Bomb Head

### ISSUE THREAD

**Issue by JohanSchuber** [ValveSoftware/Source-1-Games#6506]
Using Overheal magic spells triggers voice line _barpo kabalto_, while using Swarm of Bats uses _deus invictus_. These two voice lines seem to have been mixed up, as invictus mean invincible and should be used when using Overheal spell, which temporarily ÜberCharges player. Thus, _barpo kabalto_ would be then uttered when using Swarm of Bats spell. 
Also, Bomb Head bumper car magic spell does not use any voice line. I would propose to use either _caputus crepitus_, or _pactum diabolus_, as these two are related to explosive magic spells.

**Comment by kisak-valve** [comment]
Hello @JohanSchuber, in general, multi-issue issue reports are bad for any issue tracker.

The main part of this issue report is already being tracked at #4441. Feel free to open a separate issue report focusing on your feature request.

Closing as a duplicate.
