### ISSUE TITLE
[TF2] [Linux] Everytime the map changes, the game crashes

### ISSUE THREAD

**Issue by kugra-al** [ValveSoftware/Source-1-Games#6512]
![image](https://github.com/user-attachments/assets/223954ca-3cff-444c-aee2-3ca1cad3bbc7)

It's really frustating, it happens every time. If it's the same map, it's fine, but if it's a different map, it crashes (not always with an error msg).

![image](https://github.com/user-attachments/assets/d3f30924-ccb8-4f53-bf71-0978a50ae80b)

**Comment by kisak-valve** [comment]
Hello @kugra-al, this issue is already being tracked at #5885. Closing as a duplicate.
