### ISSUE TITLE
[Portal 2] Crash after completing game on arch linux

### ISSUE THREAD

**Issue by TheSillyDoggo** [ValveSoftware/Source-1-Games#6516]
idk how to get the crashlog, it plays after the video of wheatley finishes playing. However i can open the console and see this in the output
![image](https://github.com/user-attachments/assets/76d7b279-f083-4a6f-a097-d311c9fd7c2d)

**Comment by kisak-valve** [comment]
Hello @TheSillyDoggo, this issue is already being tracked at https://github.com/ValveSoftware/portal2/issues/428. Closing as a duplicate.

**Comment by TheSillyDoggo** [comment]
okay, thanks
