### ISSUE TITLE
[TF2] Matchmaking translation fail

### ISSUE THREAD

**Issue by programmedsun** [ValveSoftware/Source-1-Games#6521]
In the English translation of the game, `TF_MM_Queue_Error_Title` appears twice. The new matchmaking queue error messages are yet to appear in other languages.
![Screenshot_2024-11-15_01-34-54](https://github.com/user-attachments/assets/2103b92a-395c-4558-96e8-666d22d516da)

**Comment by Tiagoquix** [comment]
Fixed in the latest update.

<https://github.com/SteamDatabase/GameTracking-TF2/commit/0a51376ab1feed7df35c522a796f85493092b9e0#diff-01ba957b0f0d55d164301650591ac7b823c999924daeb46879eaef57f9646731>

![image](https://github.com/user-attachments/assets/35769c14-2dde-4bfe-b3f0-b487105f0156)
