### ISSUE TITLE
HL2 Update - Achivements aren't copied over from episodes

### ISSUE THREAD

**Issue by d10sfan** [ValveSoftware/Source-1-Games#6531]
Looking at the new update, if I pick one of the episodes, and go to the achivement list, it shows none are unlocked, even though I have unlocked a few in the past. Both of the episodes have been installed since before the update.

Note the release notes:

The achievements for Episode One and Two have been added to Half-Life 2. When launching the game it will attempt to read data from installed standalone Episodes to re-grant those duplicated achievements.

**Comment by JoriKos** [comment]
The achievements were copied over for me once I launched both episodes and then HL2 proper (and selected it from the main menu).

**Comment by d10sfan** [comment]
![20241115195955_1](https://github.com/user-attachments/assets/d80eb1b7-c5fd-49fc-9497-4618a1e45f18)

This shows no achievements, even though if I looked at episode 4 on my steam profile, I show as having 4.

![image](https://github.com/user-attachments/assets/44f3623c-861e-4576-9d1f-2220be5e6159)

**Comment by R4to0** [comment]
Launch both separated versions (not the ones in main HL2) of episodes once, then go back to to main HL2 and select each of them. That's how I got my achievements migrated over.

In your screenshot I see you launched EP1 back in 2023, so you have to launch again first for some reason.

**Comment by d10sfan** [comment]
Interesting looks like that worked, that needs to be described better in the patch notes.

**Comment by d10sfan** [comment]
Closing due to workaround found.
