### ISSUE TITLE
[HL2 Anniversary + Legacy] missing underwater effect

### ISSUE THREAD

**Issue by DDVTomu** [ValveSoftware/Source-1-Games#6543]
In HL2 i'm encounters missing water effect when diving underwater for instance:

Chapter 3 - Route Kanal: during the first run after jumped of the platform before the train comes, the water effect did not show up when I hide myself under water, this also happens during the puzzle where have to open water valve to reach to the other side of the room.

Chapter 4 - Water Hazard: during the first run when i reached at Station 12 red house, i jumped into the water and met the same missing under water effect issue as Chapter 3.

However when i reached at the first puzzle of Chapter 4 and jump into water, the effect starts to show up as it should be.

Here is the link for the video reference + some of images to show the technical issues.

![issue-1](https://github.com/user-attachments/assets/f05a5f72-c2f9-4186-ae4b-6962b57dc549)

![issue-3](https://github.com/user-attachments/assets/6fc6802b-96d5-4163-ae8e-5a6230545574)

![issue-2](https://github.com/user-attachments/assets/ca48f17d-c4ab-4c7e-bfa7-81e3befbda6a)

Video:https://drive.google.com/file/d/139862E-oygFB3Qk2dR31mm1gCK1rXylp/view?usp=sharingw

**Comment by kisak-valve** [comment]
Hello @DDVTomu, this issue is already being tracked at #3789. Closing as a duplicate.
