### ISSUE TITLE
[HL2]update after anniversary  failed

### ISSUE THREAD

**Issue by christian-combine** [ValveSoftware/Source-1-Games#6562]
i have updated my hl2 early morning and after sometime a next update appeared
it said update failed
![image](https://github.com/user-attachments/assets/e22fc7f4-3305-4bcc-9c1a-9040c3e63305)
and after i checked  it said content file blocked
![image](https://github.com/user-attachments/assets/5bf18892-bbe3-480c-b566-04e9de008867)

any fix?

**Comment by kisak-valve** [comment]
Hello @christian-combine, the Steam client is responsible for the management and update of game content instead of the game itself. Report this issue to [Steam Support](https://help.steampowered.com).

**Comment by christian-combine** [comment]
oh i forgot i had hammer on so the update failed sadly
