### ISSUE TITLE
[HL2DM] Weapon selection UI bugs

### ISSUE THREAD

**Issue by Tripperful** [ValveSoftware/Source-1-Games#6566]
On both "public" and "beta" branches:

1. Weapon selection UI sounds are missing
2. Icons for AR2, Shotgun and RPG are missing
3. There's a blank space in the 1st slot for one of the melee weapons (depending on the team), which isn't cycled when I am selecting weapons, but for some reason displayed.

Probably makes sense to close #6529 in favor of this.

![image](https://github.com/user-attachments/assets/a7297f4e-a0a5-47ba-8836-cda8d53516ea)
![image](https://github.com/user-attachments/assets/f3a6aa50-dd21-4f48-94b6-5781586a9d38)
![image](https://github.com/user-attachments/assets/09396103-3beb-4c3e-89a9-94d998e74889)

**Comment by JoriKos** [comment]
> Probably makes sense to close #6529 in favor of this.

Actually, multi-issue reports should generally not be created, and the first issue is always preferred.

**Comment by Tripperful** [comment]
Right, I'll tidy this up
