### ISSUE TITLE
A developer commentary node doesn't have subtitles for it

### ISSUE THREAD

**Issue by Nitestokeh** [ValveSoftware/Source-1-Games#6572]
This one:
![20241117003800_1](https://github.com/user-attachments/assets/7a1bba48-6fe3-42f1-9e0c-86ff469dbe59)

**Comment by kisak-valve** [comment]
Hello @Nitestokeh, please check if this is the same issue reported at #6561.

**Comment by Nitestokeh** [comment]
> Hello @Nitestokeh, please check if this is the same issue reported at #6561.

Yes, that's the one. Thanks for directing me to the proper Git page!

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
