### ISSUE TITLE
[HL2] Number of pickup indicators are incorrect after a workshop item is enabled or disabled

### ISSUE THREAD

**Issue by mhanuszh** [ValveSoftware/Source-1-Games#6574]
- I have a workshop mod installed (I tried multiple, and they all produce the same results), but not enabled (in the in game menu).
- After starting the game and loading a save, there are as many pickup indicators (like the health kit plus sign) as many picked up items.
- Exiting to the main menu, enabling or disabling workshop content and then loading into a save, causes an increasing number of indicators per picked up item.
- Also happens when starting the game with already enabled mods, and loading into a save.

System: Fedora Linux 41

https://github.com/user-attachments/assets/175cbaaa-0c1a-4531-8f4a-e7674e17ee03

**Comment by misyltoad** [comment]
Will be fixed in the next update.

**Comment by mhanuszh** [comment]
It seems fixed! Thanks!
