### ISSUE TITLE
[TF2] UI scaling not working as intended on resolutions higher than 1080p

### ISSUE THREAD

**Issue by KeiranG** [ValveSoftware/Source-1-Games#6575]
_(Running RTX 3060ti with the newest drivers [issue reproduced on multiple] with 1440p monitor on Windows 11 24h2)
(For the images, "Before" is an image taken before the 2024 Scream Fortress update and "After" is an image taken after the 2024 Scream Fortress update)_

Ever since the Scream Fortress 2024 update the entire UI has looked off, and it's only when the game is running a resolution higher than 1080p. (Scroll down)
Image examples:

Before:
![Screenshot 2024-11-16 201941](https://github.com/user-attachments/assets/0e9ffe67-e287-4088-96d5-bfeea9ffb4e9)
After:
![Screenshot 2024-11-16 201934](https://github.com/user-attachments/assets/8de9a6e3-173a-42ce-b969-99aa5c963859)

Before:
![steamworkshop_webupload_previewfile_272233334_preview](https://github.com/user-attachments/assets/d134aa6e-6791-4314-a8cd-8271f60e2cc7)
After:
![Screenshot 2024-11-16 202216](https://github.com/user-attachments/assets/25f1bc7b-0c80-4054-9b96-4679b8fae854)

Before: 
![Screenshot 2024-11-16 205324](https://github.com/user-attachments/assets/24afcec6-0c64-4c30-a932-889f0b6fd7c2)
After:
![Screenshot 2024-11-16 201728](https://github.com/user-attachments/assets/6d4626f7-0af6-4640-882e-b68e3a0850e9)

I and other users over on Reddit have been pointing the finger to this specific change:

     `- Added UI scaling based on resolution for better HiDPI support`

So even if it's technically "not a bug" it's still a major change/over sharpening to the look of the entire UI and it's breaking submenu's and custom HUDs.
This is also evident upon discovering that the vgui_ui_scale width and height in the console were set to 1080p when Windows was running at 1440p. Changing the resolution using both vgui commands actually partially fixes the issue and runs the console at native, but it's only fixed for Source menus and not for the in-game HUD, in-game chat, or the rest of the UI and doesn't entirely fix the issue. (It also resets back to 1080p when the game restarts) Images down below:

Before: 
![Screenshot 2024-11-16 202453](https://github.com/user-attachments/assets/81ae2200-4703-407a-a7a7-9b5f9e297791)
After:
![Screenshot 2024-11-16 202602](https://github.com/user-attachments/assets/78453ae0-b673-4721-b96f-f8a0978605a9)

This issue also completely messes up the scoreboard, resizing icons either too big or too small:
![Screenshot 2024-11-16 210638](https://github.com/user-attachments/assets/00decd22-f6fd-44d6-ac57-ffa03f62410e)

A few Reddit threads with this issue:
https://www.reddit.com/r/tf2/comments/1g1e4n8/anyone_elses_hud_suddenly_got_a_huge_font/
https://www.reddit.com/r/tf2/comments/1g1o3et/why_does_my_game_text_look_like_this_and_how_to/#lightbox
https://www.reddit.com/r/tf2/comments/1g0zlky/huge_font_after_new_update_any_fixes/

There should at best be a UI scaling option available in the advanced options, since my best guess is that the game is probably upscaling the UI from 1080p to whatever native resolution Windows is at. Whatever it is, it is quite bothersome for users like me running the game at a resolution higher than 1080p and having to deal with looking at it every time I open the game. Just want my game to look like what it did before.

**Comment by kisak-valve** [comment]
Hello @KeiranG, this issue is already being tracked at #6418. Closing as a duplicate.

**Comment by KeiranG** [comment]
My apologies, tried my best to find related issues before posting, but alas. Added some of my screenshots to the comments of #6418.
