### ISSUE TITLE
HL2 bundled libfreetype.so.6 needs glibc 2.29

### ISSUE THREAD

**Issue by Hicks79** [ValveSoftware/Source-1-Games#6600]
Hi,

I can't launch HL2 20th anniversary. 
I can't display logs with Proton either, as it is native.
I can't uninstall it to do a clean install either, it tells me there is an error due to shared content.

**Comment by Tiagoquix** [comment]
If you use `-vulkan` launch option, does it help?

**Comment by Hicks79** [comment]
I just tried it, but unfortunately no. But thanks for your time!

Edit: HI @kisak-valve , how can I put here the logs of the game? Maybe its a error of the script of launcher, but I dont know, I have not more information about it.

**Comment by nixRidge** [comment]
> how can I put here the logs of the game? Maybe its a error of the script of launcher, but I dont know, I have not more information about it.

Have you tried launching Steam in a terminal, then launching the game? It should output information in the terminal that way.

**Comment by Hicks79** [comment]
> > how can I put here the logs of the game? Maybe its a error of the script of launcher, but I dont know, I have not more information about it.
> 
> Have you tried launching Steam in a terminal, then launching the game? It should output information in the terminal that way.

Oh thanks so much, right!
I never had problems running HL2 and the episodes and Portal 1 and 2 before.

Here logs:

```
Caching cursor image for , size 24x24, serial 720, cache size = 0
BuildCompleteAppOverviewChange: 223 apps
chdir "/home/Hicks79/.local/share/Steam/steamapps/common/Half-Life 2"
ERROR: ld.so: object '/home/Hicks79/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/Hicks79/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/Hicks79/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/Hicks79/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/Hicks79/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Game Recording - would start recording game 220, but recording for this game is disabled
Adding process 30009 for gameID 220
Adding process 30010 for gameID 220
Adding process 30011 for gameID 220
Adding process 30012 for gameID 220
setlocale "es_ES.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale es_ES.UTF-8 (found in $LC_ADDRESS)
pressure-vessel-locale-gen: Generating locale es_ES.UTF-8...
pressure-vessel-locale-gen: Generated locale es_ES.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[30072]: W: Container startup will be faster if missing locales are created at OS level
pid 30108 != 30104, skipping destruction (fork without exec?)
pid 30113 != 30104, skipping destruction (fork without exec?)
Adding process 30104 for gameID 220
pid 30134 != 30104, skipping destruction (fork without exec?)
SDL video target is 'x11'
SDL video target is 'x11'
Adding process 30135 for gameID 220
Adding process 30136 for gameID 220
 failed to dlopen /home/Hicks79/.local/share/Steam/steamapps/common/Half-Life 2/bin/vguimatsurface.so error=/lib/i386-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/Hicks79/.local/share/Steam/steamapps/common/Half-Life 2/bin/libfreetype.so.6)
 failed to dlopen vguimatsurface.so error=/lib/i386-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/Hicks79/.local/share/Steam/steamapps/common/Half-Life 2/bin/libfreetype.so.6)
AppFramework : Unable to load module vguimatsurface.so!
Unable to load interface VGUI_Surface030 from vguimatsurface.so
Game Recording - game stopped [gameid=220]
Removing process 30136 for gameID 220
Removing process 30135 for gameID 220
Removing process 30104 for gameID 220
Removing process 30012 for gameID 220
Removing process 30011 for gameID 220
Removing process 30010 for gameID 220
Removing process 30009 for gameID 220
```

**Comment by NotHyper-474** [comment]
What's the output of `ldd --version`?

**Comment by Hicks79** [comment]
> What's the output of `ldd --version`?

```
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6+esm3) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
```

**Comment by nixRidge** [comment]
You're using a very old version of glibc, Half-Life 2 expects 2.29 or newer now.
You'll need to update glibc, or possibly your Ubuntu installation.
On Arch Linux, we have version 2.40 and it's working just fine.

**Comment by Hicks79** [comment]
Thanks so much @nixRidge @NotHyper-474 @Tiagoquix for the help.

I will try to update glibc or upgrade finally my ubuntu in the future.

Edit:  it may not be so trivial to update glibc, because of the possibility of breaking the ABI or rendering the system unusable. I think I have only the option for upgrade my ubuntu distro (I use 18.04 with Pro enabled). 

Or wait if there might be an official solution.

**Comment by smcv** [comment]
> I think I have only the option for upgrade my ubuntu distro (I use 18.04 with Pro enabled)

I'd suggest upgrading to a newer version of Ubuntu. https://github.com/ValveSoftware/steam-for-linux/ documents that only the newest short-term release (currently 24.10) and the newest LTS release (currently 24.04) are considered to be fully supported:

> * OS: Latest Ubuntu or Ubuntu LTS with a 64-bit (x86_64, AMD64) Linux kernel
>     * Older Ubuntu LTS branches are not supported and may stop working in a future Steam release, especially the branches in ESM status (Ubuntu 18.04 or older).

That's a statement about what Steam supports, but it applies equally to Steam games.

**Comment by Tiagoquix** [comment]
According to https://repology.org/project/glibc/versions, latest Debian release (Debian 12 ATM) has `glibc` version 2.36, so I believe this issue can be safely closed.

**Comment by Hicks79** [comment]
should I close this ticket? 

it is paradoxical that HL2 from 2004 does not run now (I have never had any problems) and yet a current game from 2024 (Silent Hill for example) has almost no problems.

**Comment by Tiagoquix** [comment]
> should I close this ticket?

Yes. The issue here is that you aren't on an up-to-date system; in other words, not a game issue.

> it is paradoxical that HL2 from 2004 does not run now (I have never had any problems) and yet a current game from 2024 (Silent Hill for example) has almost no problems.

Probably because HL2 uses system libraries due to being a native port, while Silent Hill runs in the Steam Sniper runtime which has newer libraries.

(Weird because I would expect it to use the Steam Scout runtime, which should include `libfreetype` and/or `glibc` with updated versions, but IDK for sure. Either way, just update your system.)

**Comment by nixRidge** [comment]
Silent Hill 2 Remake runs because it is a Windows game that is shipped with all the dependencies bundled in, indeed, the same would be true if you tried running Half-Life 2's Windows version. Wine simply uses those to launch the game.
Whereas the Linux native version of Half-Life 2 has been modernised to such an extent that it simply requires a more modern distro. This remains true if I tried to install the current modern version of Half-Life 2 on period appropriate hardware running Windows XP, which Steam itself doesn't even support. If I were to use that, I would have to install the unpatched DVD copy. In the same vein, older systems may opt to run the legacy version.

Not great, I'll admit, but that's how Valve operates.

**Comment by Hicks79** [comment]
Thanks all for the answers.

I close the ticket.
