### ISSUE TITLE
[HL2] The mechanic where Alyx shields her eyes from the flashlight no longer works.

### ISSUE THREAD

**Issue by Evisneffo** [ValveSoftware/Source-1-Games#6601]
How it looks now: 

https://github.com/user-attachments/assets/22f3584f-90d7-48a8-859b-47166d3d1b7d

How it should look (in the video, beta version Steam Legacy - Pre-20th Anniversary Build): 

https://github.com/user-attachments/assets/ada8a9e3-fac6-4747-a42e-f99c99faca7c

**Comment by misyltoad** [comment]
Will be fixed in the next update and is currently in the "beta" branch.
