### ISSUE TITLE
[HL2] Player can get hardlocked in the teleporter in d2_prison_08

### ISSUE THREAD

**Issue by VanillaSylv** [ValveSoftware/Source-1-Games#6604]
The player is unable to use the teleporter within d2_prison_08, due to alyx refusing to get into the teleporter, and after alyx is in the teleporter, the player is unable to activate the trigger making the teleporter work and the player being unable to transition to the next map.

_This issue can be worked around by letting alyx in, and doing a grenade boost, effectively creating a hardlock for players who don't have any grenades, smg grenades, or rocket launcher ammo, or don't have enough health for the boost.
Then again, this is still not ideal._

**Comment by kisak-valve** [comment]
Hello @VanillaSylv, this issue is already being tracked at #6589. Closing as a duplicate.
