### ISSUE TITLE
[TF2] display freezing on startup 

### ISSUE THREAD

**Issue by kugra-al** [ValveSoftware/Source-1-Games#6605]
For about the last week, TF2 is freezing the display after the game starts up. The game flashes once, then everything freezes and I can't interact with anything on the desktop. The system itself doesn't freeze - audio still plays, and I can switch to a different virtual terminal to kill the process, just everything on the display freezes (videos freeze, alt tab doesn't work, mouse still works, but can't click on anything until the process is terminated).

If I Verify Integrity of game files, it works as expected the next time the game launches. But I have to do it every single time for the game to launch correctly.

[System info](https://gist.github.com/kugra-al/e5f2bcca371370a6e01d183b11af4baf)

**Comment by kisak-valve** [comment]
Hello @kugra-al, can you test if setting the game's launch options to `-window` has an effect?

**Comment by kugra-al** [comment]
> Hello @kugra-al, can you test if setting the game's launch options to `-window` has an effect?

-windowed seems to work.

My previous launch options were: 
`
-dxlevel 95 -fullscreen -w 1920 -h 1080 -console -novid
`
That still freezes.

`
-dxlevel 95 -windowed -w 1920 -h 1080 -console -novid
` 
doesn't freeze and seems to work as expected.

Edit: correct launch option is `-windowed` not `-window`. Though it's worth noting, changing the launch options fixes the game launch sometimes, the same way that verifying game files does

**Comment by kisak-valve** [comment]
Thanks for checking, that makes this the same issue as #5939. Closing in favor of the older issue report.
