### ISSUE TITLE
[HL2] Tiny missing texture square present at the broken sparkling light at the end of d3_c17_12b

### ISSUE THREAD

**Issue by VanillaSylv** [ValveSoftware/Source-1-Games#6614]
Self explanatory, Unsure what texture is missing. ![image](https://github.com/user-attachments/assets/b2980833-6d63-4ab4-b2dd-2fca14af1bfc)

**Comment by kisak-valve** [comment]
Hello @VanillaSylv, this issue is already being tracked at #1184. Closing as a duplicate.
