### ISSUE TITLE
[HL2] [Linux] Audio only supports stereo config

### ISSUE THREAD

**Issue by flibitijibibo** [ValveSoftware/Source-1-Games#6622]
The engine still makes use of Miles Sound System, which is a binary blob that links to OpenAL - whatever MSS does with OpenAL it isn't able to use the full 3D functionality (I guess it just streams a single stereo buffer?), so it's stuck in stereo mode only. Is it possible to replace the OpenAL backend with a custom SDL_audio sink and replicate the DirectSound/WASAPI support to add support for multichannel formats, similar to [FMOD's custom drivers](https://github.com/flibitijibibo/FMOD_SDL)? Or did they require using their backends exclusively?

**Comment by kisak-valve** [comment]
Hello @flibitijibibo, this issue is already being tracked at #1678. Closing as a duplicate.
