### ISSUE TITLE
[HL2] Incorrect Chinese font

### ISSUE THREAD

**Issue by user10124-RS** [ValveSoftware/Source-1-Games#6626]
When the new font displays Chinese, some fonts have incorrect glyphs, most of which are Japanese glyphs.
![220_33](https://github.com/user-attachments/assets/f28ae77b-10ab-4a96-a472-9c6a8af362b4)

**Comment by user10124-RS** [comment]
As mentioned in https://github.com/ValveSoftware/Source-1-Games/issues/6548#issuecomment-2487361041 , it appears that the game failed to load the Noto Sans CJK SC / TC font correctly, but instead used the Noto Sans CJK JP font.

**Comment by misyltoad** [comment]
Thank you for reporting, this should be fixed in the next update.
