### ISSUE TITLE
[HL2] Diving sound effect

### ISSUE THREAD

**Issue by DenAkimov** [ValveSoftware/Source-1-Games#6628]
In older versions of the game and in Half-Life 2: Deathmatch, "sound/ambient/water/underwater.wav" sound effect can be heard when the player is submerged underwater. This is missing in the latest singleplayer builds. 

Deathmatch example:

https://github.com/user-attachments/assets/48f86ce0-a77c-49c0-a5d0-ceaf476eb514

**Comment by kisak-valve** [comment]
Hello @DenAkimov, this issue is already being tracked at #6495. Closing as a duplicate.
