### ISSUE TITLE
[TF2] Closed Captions broke after ui scaling update.

### ISSUE THREAD

**Issue by RiceandBeansTF** [ValveSoftware/Source-1-Games#6636]
Closed captions are broken showing a blank or incomplete text in the dialog box

https://github.com/user-attachments/assets/7cd9bd06-df57-44ed-9d0a-05b1a2031c45

https://github.com/user-attachments/assets/b070b3be-b497-41f1-8737-6c8fbaec4f77

**Comment by kisak-valve** [comment]
Hello @RiceandBeansTF, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/6426.

Closing as a duplicate.
