### ISSUE TITLE
[HL2] Object disappears when viewing it from certain angles.

### ISSUE THREAD

**Issue by jyetcv** [ValveSoftware/Source-1-Games#6638]
https://github.com/user-attachments/assets/af14c083-2332-4ae2-8d7c-a109d70223da

This object located in the house near where Odessa Cubbage is will disappear if you view it from certain angles.

**Comment by kisak-valve** [comment]
Hello @jyetcv, this issue is already being tracked at #609. Feel free to add a note to the older issue report with your findings.

Closing as a duplicate.
