### ISSUE TITLE
[All] Steam Grid artwork gets shuffled around when adding new Sourcemods.

### ISSUE THREAD

**Issue by ColossusSteppes** [ValveSoftware/Source-1-Games#6643]
When adding a new Sourcemod or HL1 Goldsrcmod, all artwork added to previous source/goldsrcmods will be shuffled around. It also shuffles around other information such as the category they were in, and if they were hidden from the library. It seems like the IDs get changed whenever a new one is added?

Someone has made a [workaround](https://github.com/FieryFenX/sourcemods-artworkfix) that fixes Sourcemods, though it doesn't always work, has to be applied with each new mod individually, and adding Goldsrc mods still shuffles around the artwork/details for both Goldsrc AND Sourcemods.

An official fix to this would be appreciated!

**Comment by kisak-valve** [comment]
Hello @ColossusSteppes, this is a general Steam client issue, not a game issue. Report this issue to [Steam Support](https://help.steampowered.com).
