### ISSUE TITLE
[HL2] Water reflection not rendering properly in the Water Hazard chapter

### ISSUE THREAD

**Issue by samdh90** [ValveSoftware/Source-1-Games#6649]
Hi,

I found a weird bug in the water hazard where the water appears to flash real fast in several spots within the Water Hazard maps. Upon first thought, it looks like a quick flash, but after looking at the freeze frame, it appears that reflections are bugging out. Of course, when this happens, it is real fast and then it is gone, but it is noticeable. I was able to reproduce this issue on two different PCs. Here are the specs;

PC1
CPU: AMD Ryzen 5800x3d
Ram: 32GB DDR4 at 3600 M/T
GPU: Nvidia RTX 4070
Motherboard: MSI B550 Gaming Plus
OS: Windows 11 Enterprise 24h2

PC2
CPU: AMD Ryzen 9 3900x
RAM 32GB DDR4 at 3600 M/T
GPU: Nvidia RTX 2070S
Motherboard: MSI B550 Tomahawk Max WIFI
OS: Windows: 11 Enterprise 24h2

I have also tried rolling the nvidia driver back to 551.86, just to see via clean install and remove with DDU, same results. 

Example: This is the most notable spot, others happen but seem to be more sporadic. 
https://streamable.com/4ku022
https://streamable.com/ifild1

I have also tried removing all overlays, same result. This was also something I saw prior to the anniversary update, but wasn't as pronounced as it is now.

Thank you.
-Sam

**Comment by kisak-valve** [comment]
Hello @samdh90, this issue is already being tracked at #3877. Closing as a duplicate.
