### ISSUE TITLE
[HL2 20th Anniversary][Feature Request] Full Deathmatch integration?

### ISSUE THREAD

**Issue by Shockwave508** [ValveSoftware/Source-1-Games#6666]
I noticed there was a leftover "hl2mp" folder in the main game directory; is Deathmatch being integrated into HL2, as was the case for EP1/EP2/LC?

**Comment by henk717** [comment]
Please don't, that may break all the servers again and I also find it questionable to have VAC in singleplayer. A more desirable solution would be to have a button in singleplayer that closes HL2 and then launches HL2DM. This has the benefit of requiring less disk space for those who don't care about either singleplayer or deathmatch, and also helps not break the servers even more.

**Comment by kisak-valve** [comment]
Hello @Shockwave508, this issue is already being tracked at #6527. Closing as a duplicate.
