### ISSUE TITLE
[HL2] Hud pickup and console command response duplication bug not fixed

### ISSUE THREAD

**Issue by Radial36** [ValveSoftware/Source-1-Games#6667]
[The patch on November 18th](https://store.steampowered.com/news/app/220/view/6633333780228604087) reported this:
- Fixed issue where HUD messages for pickups and responses to some console commands would display multiple times after switching between episodes.

This is not true, it is yet to be fixed. Hud pickups still occur multiple times, even on the latest update via the beta branch, and using commands such as god, noclip and notarget that provide a response on usage show said response multiple times rather than just once.

**Comment by kisak-valve** [comment]
Hello @Radial36, this issue is already being tracked at #6581. Closing as a duplicate.
