### ISSUE TITLE
[HL2] Add support of lightmap static props to match the behavior of half life 2 deathmap maps.

### ISSUE THREAD

**Issue by Unusuario2** [ValveSoftware/Source-1-Games#6670]
Lightmap on static props was a feature supported in Half life 2 deathmap before the 20 aniversary also can be found on Source sdk 2013 mp. Since the realiese of the  20 aniversary this was removed from the engine/not ported.

Re add support for Lightmap on static props.
Documentation:
https://developer.valvesoftware.com/wiki/Prop_static
![image](https://github.com/user-attachments/assets/89250ddd-85fb-4aa1-9611-411a0ec570d8)

**Comment by kisak-valve** [comment]
Hello @Unusuario2, this request is already being tracked at #1909. Closing as a duplicate.
