### ISSUE TITLE
[HL2] There is still a missing texture behind the broken lamp on d3_c17_12b

### ISSUE THREAD

**Issue by Reddbr34** [ValveSoftware/Source-1-Games#6676]
![Half-Life 2 Screenshot 2024 11 19 - 13 25 03 97](https://github.com/user-attachments/assets/712ae2b5-3e0b-497a-9411-de377dc017ea)

**Comment by kisak-valve** [comment]
Hello @Reddbr34, this issue is already being tracked at #1184. Closing as a duplicate.
