### ISSUE TITLE
Playing sequence X but there's only X in total?

### ISSUE THREAD

**Issue by wow32134** [ValveSoftware/Source-1-Games#6683]
On HL2DM the console get's furiously spammed Playing sequence X but there's only X in total? on console when an enemy is attacked

Ex:
weapon_smg1[242]: Playing sequence 7 but there's only 3 in total?
weapon_shotgun[460]: Playing sequence 8 but there's only 4 in total?

![image](https://github.com/user-attachments/assets/5c822552-2fe0-40b0-b7ea-c6368dcb7626)

**Comment by kisak-valve** [comment]
Hello @wow32134, this issue is already being tracked at #997. Closing as a duplicate.
