### ISSUE TITLE
Cyrillic letters inconsistency

### ISSUE THREAD

**Issue by Romeevan** [ValveSoftware/Source-1-Games#6691]
Cyrillic letters "**Ё**", "**Ы**" and "**Э**" look out of place with the rest in the new "GorDIN" font.
![3367954466_preview_compare](https://github.com/user-attachments/assets/2024c31d-14c1-4612-b88c-30fc33f6efee)

**Comment by kisak-valve** [comment]
Hello @Romeevan, this issue is already being tracked at #6548. Closing as a duplicate.
