### ISSUE TITLE
[HL2] Ravenholm menu background is has some fog/image banding.

### ISSUE THREAD

**Issue by AridCombine** [ValveSoftware/Source-1-Games#6694]
![20241118204734_1](https://github.com/user-attachments/assets/1a80b74c-c173-45ff-afb9-e656f0a6ca8e)

Noticed that after the anniversary update this menu has this weird effect now.

**Comment by kisak-valve** [comment]
Hello @AridCombine, this issue is already being tracked at #6652. Closing as a duplicate.
