### ISSUE TITLE
[HL2] Achievements completed in Half Life 2 were not counted on Steam, does anyone know what to do?

### ISSUE THREAD

**Issue by Yakob847** [ValveSoftware/Source-1-Games#6699]
To start with, I went into one of my friends' accounts and played Half Life 2 on his account for a while, and then when I bought my own copy of the game, some of the achievements I earned from progressing through the game weren't showing up on Steam, and when I try to do it again , it didn't work and was still counted towards half lfie 2. Does anyone know what to do?
 
![Zrzut ekranu 2024-11-16 130616](https://github.com/user-attachments/assets/101475d7-2cfb-49a5-b06f-0f761b8ccc01)

**Comment by JoriKos** [comment]
This is not really a help forum but if you played it on your friend's account, why would it transfer over to yours?

**Comment by Yakob847** [comment]
> This is not really a help forum but if you played it on your friend's account, why would it transfer over to yours?

Idk, it's just happind
