### ISSUE TITLE
[HL2] Alyx says "Here we go, we did it Gordon!" twice in a row at the end of Episode 1.

### ISSUE THREAD

**Issue by Ethanol-001** [ValveSoftware/Source-1-Games#6701]
At the end of HL2 Episode 1, as the train sets off, Alyx says "Here we go, we did it Gordon!" and then says it again about 5 seconds later. This is a bug that has occurred every time I've played the game.

See it 1 minute into [this](https://youtu.be/d_OKatbz5AU?t=60) gameplay video.

Whereas, [this](https://youtu.be/X0aZZLtCcto) video shows how it's supposed to work in the retail version

**Comment by rjd1922** [comment]
Already reported here: https://github.com/ValveSoftware/Source-1-Games/issues/552

**Comment by kisak-valve** [comment]
Closing as a duplicate.
