### ISSUE TITLE
Night Light on Windows 10 doesn't work with Fullscreen.

### ISSUE THREAD

**Issue by OfflcerSam** [ValveSoftware/Source-1-Games#6704]
When Half Life 2 or other Source games are run in Fullscreen mode, it ignores or turns off night light mode on Windows 10. It's not a major issue, but I've been getting used to night light mode and don't like the harsh blue.

Borderless Window or Window allows Night Light to function correctly, but Fullscreen does not.

**Comment by HaajPaaj** [comment]
I think this has something to do with the gamma manipulation in Fullscreen. I think some element of the brightness is being changed on a system-wide level in Source Engine games.

**Comment by misyltoad** [comment]
This isn't possible to fix. This is a Windows bug with legacy exclusive fullscreen.

**Comment by Tiagoquix** [comment]
If you disable fullscreen optimizations on Windows, does it work?
