### ISSUE TITLE
[HL2][Bug Report]If the number of enabled mods exceeds a certain value, the subtitles in the game will be lost.

### ISSUE THREAD

**Issue by GKLove** [ValveSoftware/Source-1-Games#6708]
After testing, when more than 46 mods are enabled at the same time, the subtitles in the game will begin to be lost. When 47 mods are enabled at the same time, the SFX subtitles in the game will be lost, but the dialogue subtitles will be retained. When 48 or more mods are enabled at the same time, all the subtitles in the game will be lost. When more than 46 mods are enabled to enter the game, you can see a flash of white blocks in the subtitle bar and then disappear.

**Comment by kisak-valve** [comment]
Hello @GKLove, this issue is already being tracked at #6671. Closing as a duplicate.
