### ISSUE TITLE
[HL2] Changing the video settings on the menu scales down the UI.

### ISSUE THREAD

**Issue by Unusuario2** [ValveSoftware/Source-1-Games#6722]
Self expanatory. This only happend when changing video settings.
See the video bellow:

https://github.com/user-attachments/assets/69117d91-9a04-4e2e-b8ff-2bd523f6969c

**Comment by kisak-valve** [comment]
Hello @Unusuario2, this issue is already being tracked at #6536. Closing as a duplicate.
