### ISSUE TITLE
[HL2: EP1] "Lowlife" Alyx not saying certain lines

### ISSUE THREAD

**Issue by man-n-red** [ValveSoftware/Source-1-Games#6724]
In the chapter Lowlife, after getting the pistol and turning on the power, Alyx is supposed to say, "Nice job!" She won't say that but will say the next line, "And hey, you found a gun!" She will, however, say the first line if the player's flashlight is on.

Later, when in the dark areas, Alyx is supposed to make zombie noises and say, "Ha! Gotcha!" but won't make the noises. The captions show the lines but Alyx won't audibly say them.

**Comment by kisak-valve** [comment]
Hello @man-n-red, this issue is already being tracked at #3753.Closing as a duplicate.
