### ISSUE TITLE
[CS:GO] crashes when it reaches CSGO Logo webm after latest steam client update.

### ISSUE THREAD

**Issue by DeformedSAS** [ValveSoftware/Source-1-Games#6728]
## PS THIS IS NOT WINDOWS 7!. Windows 10 skin.

https://github.com/user-attachments/assets/131a5db1-2839-475a-990d-a39af13d7c0c

**Comment by DeformedSAS** [comment]
Seems like the game coordinator from CS2 is actively trying to crash the CSGO client, changing the game appid to 480 (spacewar appid) makes the game work.. Setting it back to 730 causes the game to crash once again

**Comment by kisak-valve** [comment]
Hello again @DeformedSAS, support for CS:GO has ended.

**Comment by DeformedSAS** [comment]
seriously? nobody wants us to play csgo for fun? jesus this makes no sense
