### ISSUE TITLE
[All games] [Linux] Make DXVK part of Steamworks Common Redistributables (or the Steam Runtime used for Linux games)

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#6736]
Hello.

DXVK is used to empower many of the Source 1 games on Linux (and also on Windows, but DXVK is primarily for Linux) to give better performance for those who play on the :penguin: OS.

However, DXVK, as of now, requires manual updates when there are new releases.

That is: it requires manual updates to *each* game to receive the latest version of DXVK (currently, that would be version 2.5.1).

This is fine for games that receive constant updates (such as TF2), but it's horrible for finished games (such as both Portal games, Left 4 Dead 2 etc.) that only receive security fixes here and there.

I suggest that either:
1. the Steamworks Common Redistributables or Steam Runtime used for Linux games contain the relevant DXVK files for Source 1 games,
2. **or** a new common depot between all Source 1 games contain the relevant DXVK files for Source 1 games.

This way, only a single update is required to a specific depot (or to a shared depot such as the Steamworks Common Redistributables) to update DXVK files for all Source 1 games so :penguin: users can have the latest and greatest ~~bugs~~ fixes and improvements from new DXVK releases.

The only problem is that I don't know if this is possible, because the codes from the games are proprietary, but I believe the DXVK-Native `.so` file is separated and doesn't need some kind of game-specific flags and/or code to compile correctly, because they all use HL2 as a base, so compiling against HL2 should be sufficient for the rest. (Of course, this is up to Valve; I'm just speculating here.)

In regards to copyright of distribution, this would be allowed because DXVK uses the zlib license; read more at https://github.com/doitsujin/dxvk/blob/master/LICENSE.

Complementary requests of this request:
- https://github.com/ValveSoftware/Source-1-Games/issues/6204
- https://github.com/ValveSoftware/Source-1-Games/issues/6071
- https://github.com/ValveSoftware/Source-1-Games/issues/6737

Thanks for your attention.

**Comment by kisak-valve** [comment]
Hello @Tiagoquix, this is already available in the Steam Linux Runtime 3.0 (Sniper) container environment.

https://repo.steampowered.com/steamrt-sniper/pool/main/d/dxvk/

**Comment by Tiagoquix** [comment]
@kisak-valve Even though it's available, don't Source 1 games use the Steam Scout Runtime (version 1.0)? If so, being available on the Steam Sniper Runtime probably wouldn't address the main issue, which is that Source 1 games require manual game updates to have DXVK in its latest version.

Source 1 games have native Linux ports and they use DXVK SOs from their `/bin` folder, and not from the runtime they run with (because DXVK is also available on Windows for those same games, which also have DXVK DLLs in their `/bin` folder).

Please consider re-opening the issue. Thanks.
