### ISSUE TITLE
[HL2] Shooting and Grenades Allowed in Black Mesa East Chapter

### ISSUE THREAD

**Issue by Evisneffo** [ValveSoftware/Source-1-Games#6742]
### Issue

https://github.com/user-attachments/assets/ed175701-3323-46d2-8451-446836e2c377

In the **Black Mesa East** chapter of Half-Life 2, players are able to shoot and throw grenades, even though the scenario is designed to be non-combat. This creates awkward situations, as NPCs in this chapter are immortal, making the use of weapons feel out of place in a section where shooting is not intended. It would improve immersion if the use of weapons was restricted in this chapter.

### Game version
Build Label:           9353166   # Uniquely identifies each build
Network PatchVersion:  9353166   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version

**Comment by lostsektor** [comment]
why u want valve to limit more what u can do in game? this is not a issue. u are not forced to waste your ammo there. players are usually immersed in the story listening to the npcs. Valve have real problems to fix in the game.

**Comment by Evisneffo** [comment]
> why u want valve to limit more what u can do in game? this is not a issue. u are not forced to waste your ammo there. players are usually immersed in the story listening to the npcs. Valve have real problems to fix in the game.

@lostsektor, Limiting in what way? There’s already no friendly fire, so the ability to shoot and blow everything up without any reaction from friendly NPCs looks ridiculous and ruins immersion. If shooting is restricted at this point, it won’t take anything away from the players.

**Comment by lostsektor** [comment]
u are not forced to shoot anything, i guess u want cutscenes so u cant control gordon right? cuz the freedom of player have can break any immersion. like do funny things like mess with the props in the scene. hit people with crowbar etc.  so when u have a squad of rebels in next chapters u also want to disable shoot right? cuz u can shoot grenades at ur squad too. 

https://github.com/user-attachments/assets/e867ba87-aaec-4f30-ae44-1fd5648c0e98

**Comment by Evisneffo** [comment]
> u are not forced to shoot anything, i guess u want cutscenes so u cant control gordon right? cuz the freedom of player have can break any immersion. like do funny things like mess with the props in the scene. hit people with crowbar etc. so when u have a squad of rebels in next chapters u also want to disable shoot right? cuz u can shoot grenades at ur squad too.

@lostsektor, I partially agree with you. I would keep the ability to throw items in their faces and hit walls with the crowbar, but being able to shoot and blow everything up seems excessive to me.

**Comment by Evisneffo** [comment]
@lostsektor, Well, I’ve been sitting and thinking, and I came to the conclusion that you’re basically right, and I was too quick with my criticism without considering all the details. Fixing something here would most likely make things worse. Everyone can have their own gameplay experience. We have the choice to create absurd fun or seriously engage with the story. Thanks for convincing me.

**Comment by lostsektor** [comment]
other thing, this would make replay the game more annoying. i already see people that wants to be able to skip black mesa east cuz when is replaying the game is just story and gravity gun tutorial. all we can do is jump around and do silly things waiting the dialogue we already heard other times ends. New players are usually trying to understand the story and. maybe some of they will think oh let me save here and check if i can kill someone. but others will not even try. i think people that decide to shoot are not concerned about this breaking immersion. specially cuz hl2 is a old game. im pretty sure there other worse things like controling the airboat/car without hands, same zombie model with white shirt everywhere, pistol not ejecting shell casings,spas 12 being capable of double barrel shoot despite having only 1 barrel, mp7 with no visible grenade launcher or reload animation for the grenade,etc,etc.  nice u though better about.

> @lostsektor, Well, I’ve been sitting and thinking, and I came to the conclusion that you’re basically right, and I was too quick with my criticism without considering all the details. Fixing something here would most likely make things worse. Everyone can have their own gameplay experience. We have the choice to create absurd fun or seriously engage with the story. Thanks for convincing me.
