### ISSUE TITLE
[HL2] Crash to desktop when Alyx give us the Gravity Gun (French ver)

### ISSUE THREAD

**Issue by Freeman-51** [ValveSoftware/Source-1-Games#676]
Bug title: Crash to desktop when Alyx give us the Gravity Gun

Bug Location - Game Level: The Scrapyard - Black Mesa East
![69928f4b2b77ddcda1fc9eaef64cd](https://f.cloud.github.com/assets/3642053/503202/d9bb2638-bcc5-11e2-833d-914bc556153e.jpg)

Bug Location - Map Location: d1_eli_02

Bug description: After the first sentence Alyx tells something about using the first trigger of the gravity gun, the game crashes with a Windows message "HL2.exe a cessé de fonctionner" ("HL2.exe has stopped working"). Moreover, some keyboard keys go back to default. This bug appears in French version of the game even if we installed it in English (with or without French subtitles). See this thread : http://forums.steampowered.com/forums/showthread.php?t=1285036 . It happens all time we can't do anything. We can't go further in the game. I am running PC version I don't know if it appears in mac version.

http://forums.steampowered.com/forums/showthread.php?t=1286478

**Comment by TheDarkGetsuga** [comment]
Sorry, not quite ''fixed'' since i have experianced the exact same bug after this many years. This time not in french, rather English.

**Comment by kisak-valve** [comment]
Hello @TheDarkGetsuga, please open a new issue report with your system information from Steam and any CrashIDs or minidumps related to the crash you are seeing.
