### ISSUE TITLE
[HL2] Add Half-Life 2 Deathmatch to the menu alongside Half-Life 2 and Episodes (or better yet, merge)

### ISSUE THREAD

**Issue by gsergeantGTHB** [ValveSoftware/Source-1-Games#6765]
HL2DM's 20th Anniversary is also coming, It would be cool if you also add Steam Networking if the game doesn't have it yet. all of these would drive up the player base by a huge margin, and would also be a massive boost for the game's longevity especially with having 1 unified workshop to browse and get content from.

**Comment by kisak-valve** [comment]
Hello @gsergeantGTHB, this issue is already being tracked at #6527. Closing as a duplicate.
