### ISSUE TITLE
Repeated Alyx Voice Line in ep1_c17_06

### ISSUE THREAD

**Issue by resonance-gamedev** [ValveSoftware/Source-1-Games#6768]
In Episode 1, map ep1_c17_06, Alyx's dialogue is doubled when entering the train.

"Here we go; we did it Gordon."

https://github.com/user-attachments/assets/efcf2400-1eb1-4b3b-b1a3-755fccc59836

**Comment by resonance-gamedev** [comment]
https://github.com/user-attachments/assets/c4d4197f-3280-4fcb-85b4-fff15360803c

**Comment by kisak-valve** [comment]
Hello @resonance-gamedev, this issue is already being tracked at #552. Closing as a duplicate.
