### ISSUE TITLE
[TF2] 'echo' Command has race conditions when material system is threaded

### ISSUE THREAD

**Issue by Niterux** [ValveSoftware/Source-1-Games#6772]
### Game:
Team Fortress 2
### Description:
The echo command calls ConMsg multiple times to print all its arguments and a new line to the console. However, ConMsg is threaded, so sometimes, these may be printed out of order, such as the newline being printed before the argument or individual arguments being printed out of order.
The fix is to have the echo command format a string and then call ConMsg once.
There is no command line output to attach
### Reproduction details:
1. Enable multicore rendering in advanced video options.
2. Connect to a server or single-player game.
3. Bind a key to echo something such as "echo This should all on be its own newline!"
4. Mash the key as fast as you can.
5. Open the console and observe that the order of the words and the placement of the newlines aren't consistent.

### Attachments
[System Information](https://gist.github.com/Niterux/32ed350b0322c614158d4fc68d836a56)
[Console.log Example](https://gist.github.com/Niterux/915a1c9122e2ca440df6f9e3fc8b1e7a)

**Comment by mtxfellen** [comment]
Also being tracked at #1985.

**Comment by kisak-valve** [comment]
Closing as a duplicate.
