### ISSUE TITLE
[HL2] Cyrillic font is still broken

### ISSUE THREAD

**Issue by Romeevan** [ValveSoftware/Source-1-Games#6774]
The Cyrillic font is still broken even after the November 26 patch that was supposed to fix the issue.

![Снимок экрана 2024-11-27 235234](https://github.com/user-attachments/assets/d5cdf78a-7303-46fd-a1ac-6c2aa280f5f9)
![Снимок экрана 2024-11-27 235245](https://github.com/user-attachments/assets/f06122c8-c368-429d-8fba-0361ad10f2e2)

**Comment by kisak-valve** [comment]
Hello @Romeevan, this issue is already being tracked at #6548. Closing as a duplicate.
