### ISSUE TITLE
[TF2] The Kritz or Treat Canteen doesn't work in Freaky Fair

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#6791]
Title.

![tf_win64_xvd9c662Ls](https://github.com/user-attachments/assets/f58239b2-115c-4abc-b73e-c8865883b83b)

![tf_win64_G9FydorgXD](https://github.com/user-attachments/assets/196ca24e-246c-4cca-9d15-27899e02f2f7)

**Comment by jh34ghu43gu** [comment]
Server not running halloween mode? Worked for me in local server
![image](https://github.com/user-attachments/assets/2b03f03e-7786-4aee-b105-97759ad2d7e9)

**Comment by Ashetf2** [comment]
oh right

![imagen](https://github.com/user-attachments/assets/cb60c408-8d3c-4f9a-ac02-f891c754e40a)
