### ISSUE TITLE
[L4D2 Beta/Linux] Settings aren't immediately saved -> crashes revert changes

### ISSUE THREAD

**Issue by epitron** [ValveSoftware/Source-1-Games#680]
L4D2 is still crashing fairly regularly for me, which has led me to this discovery: if I make configuration changes before it crashes, they aren't always saved.

I haven't been able to figure out what triggers them to be saved, but if the crash happens while I'm navigating the menus, or while loading a game, the settings get reverted to their previous state.

**Comment by kisak-valve** [comment]
Closing as this is a side-effect of larger issues at the time. If you are still experiencing crashes, please open a new issue report.
