### ISSUE TITLE
[HL2] Commentary disappearing during/after Follow Freeman

### ISSUE THREAD

**Issue by memmam** [ValveSoftware/Source-1-Games#6807]
**System information:**
- Half-Life 2 version 9377891 (Stable)
- OS: Windows 11 23H2 (Build 22631.4460)
- CPU: AMD Ryzen 9 7950X
- GPU: Nvidia GeForce RTX 4090
- Nvidia driver version: 566.14 Game Ready Driver

**Steps to reproduce:**
1. Play Half-Life 2 with Developer Commentary up to the chapter Follow Freeman

**Expected behavior:**
Commentary should be present

**Actual behavior:**
Starting from either Anticitizen One or Follow Freeman, commentary will not be present on maps until either manually toggling commentary in the console, or sometimes when reloading a save. Exact trigger behavior and reproduction steps are unknown, but counting myself I've personally heard at least three independent reports of this issue.

**Comment by kisak-valve** [comment]
Hello @memmam, this issue is already being tracked at #6680 / #6735. Closing as a duplicate.
