### ISSUE TITLE
[HL2] Missing texture in Follow Freeman

### ISSUE THREAD

**Issue by memmam** [ValveSoftware/Source-1-Games#6808]
**System information:**
- Half-Life 2 version 9377890 (Stable)
- OS: Windows 11 23H2 (Build 22631.4460)
- CPU: AMD Ryzen 9 7950X
- GPU: Nvidia GeForce RTX 4090
- Nvidia driver version: 566.14 Game Ready Driver

Missing texture on d3_c17_12b:

![image](https://github.com/user-attachments/assets/be93a4a6-3161-4440-9214-da4edf62e9b2)

Screenshot taken at coords -4291, 266, 160. Verified game files, no change.

**Comment by kisak-valve** [comment]
Hello @memmam, this issue is already being tracked at #1184. Closing as a duplicate.
