### ISSUE TITLE
[HL2]

### ISSUE THREAD

**Issue by SobGAV** [ValveSoftware/Source-1-Games#6820]
Doesn't work blurring in water in all but one place
Не работает размытие в воде во всех местах кроме одного места
![20241129224311_1](https://github.com/user-attachments/assets/5e721776-c2cd-4062-917c-2bc52577ea12)
О
![20241129220508_1](https://github.com/user-attachments/assets/de0e5e16-72b6-46ce-8793-acfe59baab52)
стальное так
![20241129230418_1](https://github.com/user-attachments/assets/bd0808e1-207e-414c-8da9-48c25d43bda6)
![20241129222704_1](https://github.com/user-attachments/assets/b2ccbd21-1164-4d53-ad3d-7668aff6c0ef)

**Comment by kisak-valve** [comment]
Hello @SobGAV, this issue is already being tracked at #3789. Closing as a duplicate.
