### ISSUE TITLE
[TF2] Constant connection issues with the Official Team Fortress Wiki

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#6822]
For the last few months, the Wiki constantly has connection problems. often resulting in errors like "Sorry! This site is experiencing technical difficulties. Try waiting a few minutes and reloading.", "Server Error", error 502, and error 503. It's not directly related to TF2, but the Wiki is a big part of it. If someone who still maintains the servers could take a look at the Wiki's host server to check what's the problem.

**Comment by jh34ghu43gu** [comment]
Doesn't really fit in this repo and I'm 95% sure valve doesn't actually host the servers for the wiki they just have the domain.

**Comment by JoriKos** [comment]
TF Wiki moderator here. Valve can do absolutely nothing about this, they don't host the servers and we have our own people who are capable of accessing the backend.
