### ISSUE TITLE
[HL2] The razor train on the bridge

### ISSUE THREAD

**Issue by SobGAV** [ValveSoftware/Source-1-Games#6838]
Can anyone beat this race with death?
![20241130083106_1](https://github.com/user-attachments/assets/7c6db992-0729-4f53-831b-e260e141325e)
I used to have no problem speeding past a train.
Now, I've barely managed to do it, and then once after dozens of restarts.
Accidentally

**Comment by alexlavua** [comment]
I don't think speeding past a train is the intended solution anyway, as the timing is just too difficult. There's a much more consistent way of surviving which might also might be how this part was intended to be played.
https://youtu.be/1OZzTb-LA-s

**Comment by JoriKos** [comment]
What's the issue being described here? I did this first try last time I played (which was after 20th anniversary)

**Comment by SobGAV** [comment]
> В чем проблема, описанная здесь? Я сделал это в первую попытку в прошлый раз, когда играл (это было после 20-й годовщины)

https://www.youtube.com/watch?v=bBa6377af2w
таким образом? 46.30
that way?

**Comment by JoriKos** [comment]
> that way?

Yeah I just held shift and it worked fine.

**Comment by SobGAV** [comment]
> > таким образом?
> 
> Да, я просто нажал Shift, и все заработало нормально.

It really works! I realized that I didn't press SHIFT long enough.
My mistake
