### ISSUE TITLE
[HL2EP1][20TH ANNIVERSARY] Missing Alyx lines in LowLife

### ISSUE THREAD

**Issue by brunorurz** [ValveSoftware/Source-1-Games#6844]
For some reason, some small dialogue between Alyx and Gordon, like Alyx pretending to be a zombie, calling to him in the dark when losing him and some small generic lines when interacting with her don't play in EP1 when using the 20th Anniversary Update.
The subtitles for those lines show up, but the audio doesn't play at all.

They do work when playing the original standalone version of Episode 1. This problem might be related to other similar audio issues in the update.

**Comment by kisak-valve** [comment]
Hello @brunorurz, this issue is already being tracked at #4693. Closing as a duplicate.
