### ISSUE TITLE
[HL2] DSP Effects Broken after Anniversary Update

### ISSUE THREAD

**Issue by ElDesconocedor345** [ValveSoftware/Source-1-Games#6846]
Noticed the lack of sound effects (or Digital Signal Processer) in certain moments like the intro G-Man speech or Kleiner over the monitor with Barney. Then I realized that somehow, the engine's DSP config variables for certain effects were disabled like water, monitor, spatial effects. It has to be enabled every time the game is now started up.
dsp_water 14
dsp_spatial 40
dsp_speaker 50
I have also verified the integrity of the files and I always get that 34 files cannot be verified, and even then, those files are automatically deleted after reinstalling.
I hope that a patch will fix this error or that they can give me a solution.

https://github.com/user-attachments/assets/9ab4871f-8b2a-4d53-b6d7-8c18cae020da

**Comment by kisak-valve** [comment]
Hello @ElDesconocedor345, this issue is already being tracked at #6840. Closing as a duplicate.
