### ISSUE TITLE
[HL2] HDR on native ultrawide 21:9 is drawn in a small corner

### ISSUE THREAD

**Issue by rhtenhove** [ValveSoftware/Source-1-Games#6847]
This is Half Life 2 on Kubuntu 24.10, using wayland and Plasma 6.1.

### Operating System Version:
Ubuntu 24.10 (64 bit)
Kernel Name: Linux
Kernel Version: 6.11.0-9-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12401002
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20241024.105847

### Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 4050 Laptop GPU/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 560.35.03
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 74 Hz
VendorID: 0x8086
DeviceID: 0xa7a0
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 5160 x 2160
Desktop Resolution: 7320 x 3982
Primary Display Size: 31.50" x 13.19" (34.13" diag), 80.0cm x 33.5cm (86.7cm diag)
Primary VRAM: 6141 MB

## Problem

When playing on the native resolution on my 21:9 - 3440x1440 monitor, with HDR (full or bloom) enabled, the effect is drawn in a small top left corner of the screen.

| HDR | non HDR |
| - | - |
| ![hdr](https://github.com/user-attachments/assets/6759739e-b335-4d3a-8d42-94f54073dde1) | ![nonhdr](https://github.com/user-attachments/assets/2115b69c-702d-47ee-961c-67dc83297a43) |

This native resolution is only listed under 16:9, no 21:9 option in the aspect ratio list, however the aspect ratio is not distorted.

To have HDR render correctly, I have to use any non-native resolution.

I do miss the HDR effect during gameplay! Any solution is highly appreciated :smile:

**Comment by Cosmic-Downpour** [comment]
I'm having this exact same issue!
I'm playing through HL2 on linux mint cinnamon with a 3090 and an ultrawide monitor.
With HDR enabled, I get a sort of ghostly image in the top left, as if it's rendering it, but not scaling it correctly.
It's exactly as you describe.

**Comment by rhtenhove** [comment]
Using Wayland, setting Legacy Applications (X11) under Display Configuration to Scaled by the system resolves this problem. It will change how all X11 applications behave, however that has so far been an improvement overall.

**Comment by Zamundaaa** [comment]
That reduces the resolution of the game, it is not fixed by that but just happens to not trigger the issue

**Comment by rhtenhove** [comment]
It did decrease the _reported_ native resolution to my actual native resolution. There was no visual difference, also not in scaling of UI elements.

So I concluded having the wrong (unsupported) resolution set as native caused the issue, and now the game having (and allowing the selection of) the right resolution, the rendering of HDR also doesn't get messed up.

That also makes sense given that using any other resolution supported by my monitor also removed the problem.

It certainly isn't a fix in the game, but it is a solution to the problem.

**Comment by Zamundaaa** [comment]
Ah. In my case, the native resolution of the monitor (5120x1440) is large enough to trigger this directly

**Comment by rhtenhove** [comment]
I see I had mentioned an incorrect native resolution in the issue. My actual native resolution is 3440 x 1440 while with the previous scaling setting HL2 showed it as 5160 x 2160.

How does the scaling setting lower your resolution? I did notice the in game resolution changes when I enable it, but I am able to select the correct native resolution afterwards.

**Comment by Zamundaaa** [comment]
X11 scaling scales all displays by the same scale factor, so
- with "legacy apps scale themselves", if you have a second screen that has a higher scale factor, it increases the resolution X11 apps see on the first screen
- with "legacy apps scaled by the system", if you have a scale on the display you game on (and no second display with a higher scale), it reduces the resolution X11 apps see by that scale
