### ISSUE TITLE
[Ep 1] Red lighting from nowhere

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#685]
There are a couple of spots in the game where props would be glowing red for no apparnet reason. The first was in the final stabilization chamber in the Citadel core, where you have to power three energy ball columns downstairs. When viewed in commentary mode, the commentary node model is red.

![2013-05-14_00001](https://f.cloud.github.com/assets/3085348/504519/55ffc7fa-bcec-11e2-8b4c-0dddef7a97af.jpg)

The second was in the doorway to the room where the Combine store supplies and you encounter the first door that's rigged to explode and let soldiers in. When you stand in the doorway and aim the gravity gun at the right angle, it looks like this:

![2013-05-14_00004](https://f.cloud.github.com/assets/3085348/504523/af3a7dd8-bcec-11e2-9724-eb94bbb2fa40.jpg)

I assume these are related somehow.

```
Processor Information:
    Vendor:  GenuineIntel
    Speed: 2400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Operating System Version:
    Ubuntu 12.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-29-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 4800 Series

    Driver Version:  3.3.11672 Compatibility Profile Context
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x944a
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                            53.1cm x 29.9cm  (60.9cm diag)
Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  487728 Mb
    Largest Free Hard Disk Block:  385470 Mb
```

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Yetoo1** [comment]
This may be a separate issue, but I found a green light on a fence in ep1_c17_2b. Screenshot:
![20191220142924_1](https://user-images.githubusercontent.com/12403440/71315285-c23a5900-240d-11ea-8470-46be35243ced.jpg)

EP1 Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

System info here:
https://web.archive.org/web/20191207232514/https://pastebin.com/qJ5SPXg3
