### ISSUE TITLE
[TF2] Request - make more rebalances for existing weapons and add more weapons created by the community every major seasonal update.

### ISSUE THREAD

**Issue by EthanTheCool** [ValveSoftware/Source-1-Games#6855]
(THIS IS NOT A DUPLICATE OF THE "Ethan tf2 update: OR SMTH REQUEST. THIS IS A WHOLE NEW SUGGESTION!) the seasonal updates are to be expected and boring... new maps, new taunts, a cosmetic crate and key, and war paints.. its been 7 years and we still have the same weapons.. same stats.. and no changes... but in the workshop, many weapons and ideas for rebalancing are being created.. even today they are still being created.. so I want valve to add new weapons for every community major update starting next year.. please... we want new weapons...

**Comment by kisak-valve** [comment]
Hello again @EthanTheCool, your choice to open repeated requests to make undefined changes to Team Fortress 2 is an abuse of this issue tracker and has resulted in a 1 week timeout.

Without providing actionable details on what to could be changed to positively improve a player's experience with the game, this issue report is reduced yet again to "make undefined changes Team Fortress 2" which is not actionable.

Consider this a warning, if I need to step in again, your timeout will become permanent.

Closing as a unactionable, the same as #6340 and #6767.
