### ISSUE TITLE
[HL2 EP1] the phrase is repeated twice when you get on the train.

### ISSUE THREAD

**Issue by SobGAV** [ValveSoftware/Source-1-Games#6869]
"Here we go."      Поехали
"We did it, Gordon."     Мы сумели, Гордон

first here
![20241215155345_1](https://github.com/user-attachments/assets/c310161b-7806-492f-8787-922f7dcec103)

after here
![20241215155352_1](https://github.com/user-attachments/assets/9b599f1e-f0b6-4e43-bdc6-e0cfdf4b9b6d)

**Comment by kisak-valve** [comment]
Hello @SobGAV, this issue is already being tracked at #552. Closing as a duplicate.
