### ISSUE TITLE
[TF2] High chance of crashing when loading listen servers

### ISSUE THREAD

**Issue by sopranoguitar** [ValveSoftware/Source-1-Games#6872]
This doesn't happen upon loading a game for the first time, but either loading into a listen server after having been in any other server or loading into any server after having been in a listen server tends to crash the game. The chance of crashing may increase based on how long you've been ingame for or how many maps have been loaded, but that's just speculation. 

This may be Windows exclusive as I was able to reproduce this on two devices running Windows (both the 64 bit client and the 32 bit client), however not on an Ubuntu virtual machine. I have also not had this issue before the 64 bit update.

**Comment by kisak-valve** [comment]
Hello @sopranoguitar, this issue is already being tracked at #5885. Closing as a duplicate.
