### ISSUE TITLE
[TF2] Buck Brim & Westcoat issues

### ISSUE THREAD

**Issue by Wosheereal** [ValveSoftware/Source-1-Games#6875]
The "Bad" Style of the Buck Brim is not paintable despite the promos showing that it is and the genteel smoke effect being missing.
![image](https://github.com/user-attachments/assets/74807a59-dc23-41a8-945e-49ef369dd72a)

The "Ugly" style of the Westcoat has a bugged belt buckle and buttons.
![image](https://github.com/user-attachments/assets/2c9de47e-c1e0-4e83-87b2-d236d885c6ab)

Both of these issues are not present in the workshop upload and seems to be errors when VALVe imported the items.

**Comment by DRAG4YOU** [comment]
Hey Woshee, i made a quick fix for both of these issues.

[Buck Brim & Westcoat Fix.zip](https://github.com/user-attachments/files/18224694/Buck.Brim.Westcoat.Fix.zip)

![67678f6be1a91](https://github.com/user-attachments/assets/5f65e4f3-ab05-4cd0-989d-a6ec1702e883)

I'm not the OG creators but hope this example helps out valve to fix it faster.

**Comment by Wosheereal** [comment]
> Hey Woshee, i made a quick fix for both these issues.
> 
> [Buck Brim & Westcoat Fix.zip](https://github.com/user-attachments/files/18224694/Buck.Brim.Westcoat.Fix.zip)
> 
> ![67678f6be1a91](https://private-user-images.githubusercontent.com/16998974/398041827-5f65e4f3-ab05-4cd0-989d-a6ec1702e883.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjQ1MjUsIm5iZiI6MTczNDkyNDIyNSwicGF0aCI6Ii8xNjk5ODk3NC8zOTgwNDE4MjctNWY2NWU0ZjMtYWIwNS00Y2QwLTk4OWQtYTZlYzE3MDJlODgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAzMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzE5MGY0YTc0NzM0ZDRlMzYyMmNkNzdiZjQ4ODA0MTY5ZGRmZTMyMGJmMzAxODhhOTVkNjIxNDM5NWQ3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6c4rQJDc8TW598gP1D1rlQ-N2tMv6F_VJCo9ohbA2Ns)
> 
> I'm not the OG creator but hope this example helps out valve to fix it faster.

It looks like the creators of the item seemed to send a fix to VALVe today at 3:22 PM PST, but thanks for fixing it yourself, you even separated the materials of the buck brim's cigar with the hat so the self-illumination doesn't break where the paint is supposed to apply to.

**Comment by Wosheereal** [comment]
![image](https://github.com/user-attachments/assets/b549b5eb-49c4-435f-a450-7dfef67424aa)
![image](https://github.com/user-attachments/assets/ad2b10ec-3440-43f5-aae1-01a71b897fed)
Can confirm the issues are fixed after the latest update, will close the issue.
