### ISSUE TITLE
Left 4 Dead 2 - L4D campaign AI does not respond to items consistently

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#688]
While playing the No Mercy campaign the AI does not always pick up secondary health items when they have an empty slot and was not picking up ammo mods when deployed in a hero closet. This occurred during a game on a third party dedicated server.

**Comment by alexiscoutinho** [comment]
There are several mods that improve the bots' AI, i.e. Left 4 Bots. Although, I'm pretty sure the base AI does all those tasks completely fine.

**Comment by kisak-valve** [comment]
Closing per the last comment and because the reporting user has turned into a ghost.
