### ISSUE TITLE
[Half-Life 2] Highway 17 battery puzzle contingency failure

### ISSUE THREAD

**Issue by keifersisawesome** [ValveSoftware/Source-1-Games#6884]
This is what I believe is a bug, which is funnily enough related to the contingency I heard about in the dev commentary for the junkyard battery puzzle.

There is a commentary node there that described a fail safe put in place in the event players lost all of the batteries in the fight there. The node recommended throwing all the batteries off the edge of the cliff to see what happens. I did so, and found that two of the batteries were successfully teleported back to their starting points, except for the one that starts on the counter.

That one remained visible, floating in the water beneath the cliff, and I needed to turn on noclip and god mode to maneuver it back to the junk yard area. So I can only assume that the failsafe for this particular battery is broken.

**Comment by mhanuszh** [comment]
There are 5 batteries on the map. But the already plugged-in one wont respawn.

**Comment by keifersisawesome** [comment]
> There are 5 batteries on the map. But the already plugged-in one wont respawn.

Oh I thought there were only three. That's on me then.
