### ISSUE TITLE
[TF2] Request - create more rebalances for existing weapons and add more weapons created by the community every major seasonal update.

### ISSUE THREAD

**Issue by EthanTheCool** [ValveSoftware/Source-1-Games#6885]
(to kisak-valve, this is an important request and denying it will make tf2 abandoned.. if you want to contract me please message me. do not Close this and call it unactionable, this is NOT the same as #6340 and #6767. I am never making any undefined changes in all of my posts and I am defining additions to the update cycle...  this game has 144k people active and yet the update cycle remains the same for 7 years and counting... changing how updates are rolled out is a really actionable detail on tf2 can be changed to positively improve EVERY SINGLE player's experience. I don't want to tell the steam group about you denying my suggestion and it could get bad for you.. I'm warning you if you take this down you're positivity will be taken down by the community.. I am not being mean and I don't want to resort to this warning.. thank you for reading. now lets get into the real request.)

the seasonal updates are to be expected and boring... new maps, new taunts, a cosmetic crate and key, and war paints.. its been 7 years and we still have the same weapons.. same stats.. and no changes... but in the workshop, many weapons and ideas for rebalancing are being created.. even today they are still being created.. so I want valve to add new weapons for every community major update starting next year.. please... we want new weapons... if you want an example, the summer 2025 update should include adding the nail gun as a primary  for the scout, [g-maw](https://steamcommunity.com/sharedfiles/filedetails/?id=3385652384&searchtext=) for soldier, and adding 3 other weapons from the community workshop.. I want to have tf2 receive  more updates again..

**Comment by kisak-valve** [comment]
Congratulations @EthanTheCool, you've failed to understand the basic concept of an issue tracker and how to use one. Your choice to repeat the same topic has resulted in being blocked from further posts.

Closing as duplicate, unactionable issue report yet again.
