### ISSUE TITLE
[HL2] Workshop navigation issues on Steamdeck

### ISSUE THREAD

**Issue by B-Bud** [ValveSoftware/Source-1-Games#6887]
Workshop on the SteamDeck version of Half-Life 2 has a couple of issues with navigation and enabling/disabling mods:

- In-Game workshop menu only shows the first page of 'Content' addons currently subscribed by the user. Preventing the user from enabling/disabling all addons they have installed.
- A workaround to enable/disable any addon is to go through the workshop settings through Steam, however this solution does not work when the user is not connected to Wi-Fi, as any change to addons with this method will simply mass disable all addons in game.

**Comment by kisak-valve** [comment]
Hello @B-Bud, this issue is already being tracked at #6664. Closing as a duplicate.

**Comment by B-Bud** [comment]
#6664 Does not mention the issue with Workshop items being mass disabled when not connected to Wi-Fi.

**Comment by B-Bud** [comment]
> Hello @B-Bud, this issue is already being tracked at #6664. Closing as a duplicate.

#6664 Does not mention the issue with Workshop items being mass disabled when not connected to Wi-Fi.
