### ISSUE TITLE
[TF2] Battle Balaclava No Gloves Style Removes Hands

### ISSUE THREAD

**Issue by DRAG4YOU** [ValveSoftware/Source-1-Games#6890]
The second style of this cosmetics removes heavy's hands

I see no issues on the workshop 
![steamuserimages-a akamaihd](https://github.com/user-attachments/assets/f0553b1d-9093-4ef9-9191-78099f89bb51)
See the middle heavy

In-game
![Untitled](https://github.com/user-attachments/assets/d3978a0c-f8f2-4f06-a0de-79916dfc65ab)

Heavy has no hands on miniguns, secondaries and stock fists while using the no gloves style.

**Comment by jh34ghu43gu** [comment]
Right now it has a duplicate keyvalue for "visuals", the first one globally hides hands for all styles, should be a simple fix to move it to the 0 style in the second visuals KV.

**Comment by DRAG4YOU** [comment]
They fixed :)
