### ISSUE TITLE
[CS:S] The game crashes when using the microphone

### ISSUE THREAD

**Issue by pavlokozlenko** [ValveSoftware/Source-1-Games#6892]
In any distro. I`m trying Ubuntu 24.10, Arch, Debian 12.

Steps to reproduce the problem: go to the server and press the microphone button

This is a video where I launch the game and demonstrate the crash of the game:
https://github.com/user-attachments/assets/6b20a996-7049-4cb4-9e36-9214278d5e5c

All log steam:
[steam.txt](https://github.com/user-attachments/files/18231233/steam.txt)

My inxi -Fxxxrz:
[inxiFxxxrz.txt](https://github.com/user-attachments/files/18231280/inxiFxxxrz.txt)

My crash dump:
[crash_20241223180035_3.zip](https://github.com/user-attachments/files/18231270/crash_20241223180035_3.zip)
For some reason, I can't send the file with the .dmp extension, so I packed it into an archive

In the game settings, I hear my voice, and when playing with bots, it does not crash

**Comment by kisak-valve** [comment]
Hello @pavlokozlenko, this issue is already being tracked at #3740. Closing in favor of the older issue report.

**Comment by pavlokozlenko** [comment]
> Привіт @pavlokozlenko, ця проблема вже відстежується на [ #3740 ](https://github.com/ValveSoftware/Source-1-Games/issues/3740) . Закриття на користь старішого звіту про випуск.

@kisak-valve Last comment date Mar 9
