### ISSUE TITLE
[TF2] Sandman ball inconsistently hits giants

### ISSUE THREAD

**Issue by Gangren3** [ValveSoftware/Source-1-Games#6900]
The sandman can **hit** any giant, but more often than not it bounces off for no damage or effect.
I *think* what's happening is the sandman is becoming "inactive" before it hits a valid target, IE the robots. Because the sandman's trail and appearance does not noticeably change when it becomes inactive, it's hard to know when this happens. My suspicion is that the giant's per-bone hitboxes are deactivating the ball before it hits the hull. Or perhaps there is some distance check related to hit detection that the sandman ball isn't passing due to a distance not being scaled for giants.

**Comment by JoriKos** [comment]
Pretty sure the bounding box automatically adjusts based on the scale of the model, so I doubt it hits the hitboxes before hitting the bounding box.

**Comment by jh34ghu43gu** [comment]
This is 99% a duplicate of #3471
If a robot is healed in spawn and is shot at, the flashed uber will activate the bug and make it invulnerable to balls.

**Comment by Gangren3** [comment]
> This is 99% a duplicate of #3471 If a robot is healed in spawn and is shot at, the flashed uber will activate the bug and make it invulnerable to balls.

Honestly probably, actually. This sounds more likely.

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
