### ISSUE TITLE
[TF2] Crates give only stranges????

### ISSUE THREAD

**Issue by XTERMlN8** [ValveSoftware/Source-1-Games#6901]
I tried opening a few crates today just for fun and I quickly realized something was wrong when I unboxed 5 strange pain trains almost in a row... This could be a pretty massive issue but I haven't seen anyone talk about it at all anywhere. I've tried this with Mann Co. Supply Munition Series #92 and the Mann Co. Supply Crate Series #55 and for both it only ever gave me stranges. All of the stranges in this screenshot were obtained from this bug. I hope we don't have a second crate depression on our hands...
![20241225233219_1](https://github.com/user-attachments/assets/0b370431-b3eb-4f25-9787-95e5d194deae)

**Comment by JoriKos** [comment]
No, they are supposed to drop only Stranges.

![afbeelding](https://github.com/user-attachments/assets/f09524d9-3a50-4c65-8583-2a4364685f7a)
![afbeelding](https://github.com/user-attachments/assets/94044678-faf2-486d-94aa-23dd97086312)
