### ISSUE TITLE
[TF2] [Feature Request] Remove text and voice chat restrictions on Free2Play accounts

### ISSUE THREAD

**Issue by Ninou-the-Cat** [ValveSoftware/Source-1-Games#6902]
As of [June 16, 2020 Patch](https://wiki.teamfortress.com/wiki/June_16,_2020_Patch), F2P players have been banned from using text and voice chat in official servers as well as the removal of voice commands for the goal of stopping bots from spamming in chat. Since the measures taken by Valve last June, there is no reason to keep those restrictions.
### Why Text Chat and Voice Commands are important?
As many players have stated, not being able to chat is a hindrance and always puts them at a disadvantage due to the lack of communication (e.g., calling for medics). In addition, making relations in-game has always been a big part of TF2, including but not limited to Freeze Cams, Domination-Revenge, and Partner Taunts, and removing text chat feels so out of place.

**Comment by kisak-valve** [comment]
Hello @Ninou-the-Cat, this request is already being tracked at #3289 / #4177. Closing as a duplicate.
