### ISSUE TITLE
[TF2] Stray polygon in Spy's wrist in stab animation

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#6905]
Apparently according to the Wiki, the stock Knife (not sure if this affects others) has a stray polygon that appears in Spy's wrist. There aren't any screenshots of the bug that I can provide, sorry.

**Comment by JoriKos** [comment]
This bug was submitted in 2011, likely when the Knife model was bigger. I checked the animation in HLMV, I couldn't see anything like it. I've removed it from the article itself as well, so this might as well be considered fixed.
