### ISSUE TITLE
[TF2 Bug + Fix] Ullapool Caber does not deal minicrit damage from charging

### ISSUE THREAD

**Issue by Marxvee** [ValveSoftware/Source-1-Games#6907]
Currently, as shown in this video https://www.youtube.com/watch?v=WJe-6x3Jl8M, the Ullapool Caber does not deal minicrit damage via charging with any shield (particularly the Tide Turner). This is due to two things:
1) The Caber’s weapon ID is exempt from the statement responsible for granting the Demoman’s melee weapons mini-crits via charging in tf_gamerules.
2) The explosion hit does not have the m_bMiniCrit check for adding the DMG_RADIUS_MAX damagebit.

To fix this so the Caber can be consistent with the rest of Demoman’s melee weapons in terms of charging mini-crits, the following two changes should be implemented:

In game/shared/tf/tf_gamerules.cpp under bool CTFGameRules::ApplyOnDamageModifyRules( CTakeDamageInfo &info, CBaseEntity *pVictimBaseEntity, bool bAllowDamage ), find the following if statement

            else if ( pTFAttacker && (bitsDamage & DMG_RADIUS_MAX) && pWeapon && ( (pWeapon->GetWeaponID() == TF_WEAPON_SWORD) || (pWeapon->GetWeaponID() == TF_WEAPON_BOTTLE)|| (pWeapon->GetWeaponID() == TF_WEAPON_WRENCH) ) )
            {
                // First sword or bottle attack after a charge is a mini-crit.
                bAllSeeCrit = true;
                info.SetCritType( CTakeDamageInfo::CRIT_MINI );
                eBonusEffect = kBonusEffect_MiniCrit;
            }
and add TF_WEAPON_STICKBOMB to the list of eligible weapon IDs, like so (unsure why TF_WEAPON_WRENCH is there, but I digress):

            else if ( pTFAttacker && (bitsDamage & DMG_RADIUS_MAX) && pWeapon && ( (pWeapon->GetWeaponID() == TF_WEAPON_SWORD) || (pWeapon->GetWeaponID() == TF_WEAPON_BOTTLE)|| (pWeapon->GetWeaponID() == TF_WEAPON_STICKBOMB)|| (pWeapon->GetWeaponID() == TF_WEAPON_WRENCH) ) )
            {
                // First sword or bottle attack after a charge is a mini-crit.
                bAllSeeCrit = true;
                info.SetCritType( CTakeDamageInfo::CRIT_MINI );
                eBonusEffect = kBonusEffect_MiniCrit;
            }
This will allow the non-explosion hit to now deal mini-crits via charging. To fix the explosion as well from not minicritting, head over to game/shared/tf/tf_weapon_bottle.cpp and add the following statement to void CTFStickBomb::Smack( void ), changing the following block of code from
```
 int dmgType = DMG_BLAST | DMG_USEDISTANCEMOD;
            if ( IsCurrentAttackACrit() )
                dmgType |= DMG_CRITICAL;
 ```
to
```
 int dmgType = DMG_BLAST | DMG_USEDISTANCEMOD;
            if ( IsCurrentAttackACrit() )
                dmgType |= DMG_CRITICAL;
            else if ( m_bMiniCrit )
                dmgType |= DMG_RADIUS_MAX;
```
This should now allow the explosion to also minicrit, fixing the Ullapool Caber to now be fully consistent with the rest of Demoman’s melee weapons with charge mini-crits.

I am aware of the duplicate issue at #4428, but I wanted to directly present a fix to this bug. Thank you!

**Comment by kisak-valve** [comment]
Hello @Marxvee, as you noted, this issue is already being tracked at #4428. You should have added this as a comment on the older issue report.

Since this adds a bit more detail, I've transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/4428#issuecomment-2563967960. Closing as a duplicate.
