### ISSUE TITLE
[L4D2] Team Versus/Scavenge modes don't work

### ISSUE THREAD

**Issue by sugarbro** [ValveSoftware/Source-1-Games#6909]
With two full lobbies, even if there is a match, the game doesn't start, both in Local or Official Dedicated servers. Due to this, the only other way to get the achievement STRENGTH IN NUMBERS is through using addons to allow bots in Team Scavenge.

**Comment by kisak-valve** [comment]
Hello @sugarbro, this issue is already being tracked at #4112. Closing as a duplicate.
