### ISSUE TITLE
[TF2][Linux] Materials with capital letters in file path broken in recent update

### ISSUE THREAD

**Issue by pokemonpasta** [ValveSoftware/Source-1-Games#6917]
Noticed this on a couple maps which have material file paths in all caps, none of the textures load at all. I've asked around and it seems only people on linux can replicate this. I've confirmed it happens on several maps, including maps that were working fine a few months ago (with no changes to those maps). I don't know exactly which update it was unfortunately.

![Screenshot_20241231_185218](https://github.com/user-attachments/assets/f545ca95-b6e2-4c28-be28-00bfa978c303)
![Screenshot_20241231_185327](https://github.com/user-attachments/assets/65946b94-7570-4043-8e0d-3a60efbcf22b)

**Comment by kisak-valve** [comment]
Hello @pokemonpasta, this issue is already being tracked at #6868. Closing as a duplicate.

**Comment by Tolfx** [comment]
I tested and found the issue. Is due to Linux not being able to handled if they are capitalized. I took a map and extracted all materials and renamed to lower and put it back in which resolved the whole issue.

Rather silly but works to manually fix it for now. Might create a script for it.
