### ISSUE TITLE
[HL2] Going back from d1_trainstation_03 to d1_trainstation_02 active a strange fog and disable breen speech loop.

### ISSUE THREAD

**Issue by Freeman-51** [ValveSoftware/Source-1-Games#696]
![2013-05-15_00008](https://f.cloud.github.com/assets/3642053/507871/e3ffada4-bd78-11e2-83c7-ac7ac359201b.jpg)
![2013-05-15_00010](https://f.cloud.github.com/assets/3642053/507873/e6268bd4-bd78-11e2-83e9-d8740a639e77.jpg)

**Comment by Yetoo1** [comment]
The fog is gone but the Breen speech loop still stops.

HL2 Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

System info here:
https://web.archive.org/web/20191207232514/https://pastebin.com/qJ5SPXg3

**Comment by Yetoo1** [comment]
Actually, I was mistaken the Breen loop stops only when you've gone passed the fence and back.
