### ISSUE TITLE
Setting texture detail to “very high” causes TF2 to lag

### ISSUE THREAD

**Issue by FutureSuture** [ValveSoftware/Source-1-Games#701]
Setting texture detail to “very high” causes entire game to lag, including the menus. Problem never occurred in Windows 7. Problem always occurred in Linux Mint 14 Cinnamon (with Nvidia driver 310.14) and now in openSUSE 12.3 KDE (with Nvidia driver 319.17). Game needs to be restarted when lowering the texture detail back down to “high” for the changes to take effect and for the lag to go away. Game stays unplayable otherwise. Enabling or disabling multicore rendering does not help whatsoever as the issue remains.

My system information:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 4301 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "openSUSE 12.3 (x86_64)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.10-1.4-desktop
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 570/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 319.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1081
Number of Monitors:  1
Number of Video Cards Not Detected
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.70" x 13.35"  (27.17" diag)
                                        60.2cm x 33.9cm  (69.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1280 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Nvidia GPU 18 HDMI/DP

Memory:
    RAM:  7983 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  110103 Mb
    Largest Free Hard Disk Block:  91286 Mb

Installed software:

Recent Failure Reports:
    Wed May 15 15:03:41 2013 GMT: file ''/tmp/dumps/assert_20130515160335_1.dmp'', upload yes: ''CrashID=bp-1ce0d28a-ebdc-49ae-9156-128782130515''
    Wed May 15 15:03:56 2013 GMT: file ''/tmp/dumps/assert_20130515160149_1.dmp'', upload no: ''Couldn't connect to server''
    Wed May 15 15:04:16 2013 GMT: file ''/tmp/dumps/assert_20130515160409_1.dmp'', upload yes: ''CrashID=bp-d2767a02-8aaa-4a92-ab76-7831e2130515''
    Wed May 15 15:08:49 2013 GMT: file ''/tmp/dumps/assert_20130515160843_1.dmp'', upload yes: ''CrashID=bp-8ad2412c-feb2-4754-ad5d-96a262130515''
    Wed May 15 15:09:16 2013 GMT: file ''/tmp/dumps/assert_20130515160455_1.dmp'', upload no: ''Failure when receiving data from the peer''

**Comment by kisak-valve** [comment]
This appears to be from the additional cpu overhead from using ToGL (the internal DirectX to OpenGL translation layer) and OpenGL 2.1.

There is no specifically actionable issue here so I'm going to close this issue report.
