### ISSUE TITLE
[TF2] Replays get corrupted when using 3rth party models.

### ISSUE THREAD

**Issue by riemers** [ValveSoftware/Source-1-Games#702]
With the use of steampipe, people dont need to place models/materials on the server as long as plugins (sourcemod) cache those files. They will be downloaded from the download server and shown to the client. This works fine in most cases, but replays will show an error. So this means you still need particular materials/models on the server in order for it to render correctly in the replay. However, once you do that it will always crash the replay system (tf2 will crash) once you replay that movie. I've seen multiple posts on the forums too regarding these types of issues. It would be better if there was a good "howto" to go about not having incorrect replays with models or that at least replays wont crash on 3rth party models.

See example crash window.
![replaycrash](https://f.cloud.github.com/assets/682041/509278/27ec063a-bda0-11e2-9daf-de09bbdb0b0a.png)

**Comment by kisak-valve** [comment]
Hello @riemers, are you still experiencing this issue?

**Comment by riemers** [comment]
Don't know, it has been 3+ years ago and my community of TF2 servers pretty much died after all the changes so there is no need for me anymore to have this resolved. You can close this if you want.

**Comment by kisak-valve** [comment]
Thanks for letting me know.
