### ISSUE TITLE
Spray Import Error (L4D2, Linux)

### ISSUE THREAD

**Issue by DaddyWarcrimes** [ValveSoftware/Source-1-Games#705]
Using import spray option, upon selecting the file and hitting open I receive the following:
'Spray Import Error
Unable to load vtex.dll. Try restarting steam to get the latest updates.'

Restarting Steam did not seem to have any effect.

Running Xubuntu 13.04

**Comment by i5heu** [comment]
Still Present :(

**Comment by lyn1337** [comment]
@i5heu Sadly!

**Comment by sagir3** [comment]
Still present...

All I want to do is use this spray in game, but I can only do so on Windows. I use Linux 99% of the time.
![you're already dead](https://i.imgur.com/ZfH94qw.png)

**Comment by lyn1337** [comment]
Denial, Anger, Bargaining, Depression, Acceptance.

**Comment by Jigoku** [comment]
Still no fix after ~5 years? 👎

**Comment by vitacell** [comment]
Valve still did not fix this windoze dll crap. The bug is still present. So hard?

**Comment by lyn1337** [comment]
You still have to start up a different L4D2 installation via wine in order to upload your spray file.

**Comment by attilaM68K** [comment]
It's still not fixed after 7 years.

**Comment by vitacell** [comment]
> 
> 
> It's still not fixed after 7 years.

Yeah, amazing.

**Comment by JoneKone** [comment]
This is still relevant! Plz fix.. My son is just a pup he doesn't even understand Folders... and he is sad cause he cannot get a custom spray..

**Comment by AndreyLapiuk** [comment]
There is a way to work around the problem. Just follow the instructions here: https://doitonlinux.blogspot.com/2015/04/custom-spray-in-l4d2.html . The issue described there is different but it resolves this problem as well. In short, one has to create .vtf .vmt logos from one’s pic and then copy it to [...]/left4dead/vgui/logos/custom/ . Once it is done, one can choose the option "Custom Logo" in the game and enter the vft file name (e.g. mylogo.vtf).

**Comment by leagris** [comment]
@AndreyLapiuk then how do you create the .vtf and .vmt at all?
The path in the article don't match my Steam Linux

**Comment by leagris** [comment]
Now that you have plenty of time working on stuffs @ValveSoftware since we are all locked with Covid, can you fix this, or maybe finish and publish HL3 ;D

**Comment by AndreyLapiuk** [comment]
> @AndreyLapiuk then how do you create the .vtf and .vmt at all?
Just google "convert png to vtf"
> The path in the article don't match my Steam Linux
Im using ubuntu 18.04 and my path is different as well and it looks like this ~/.steam/steam/steamapps/common/Left 4 Dead 2/left4dead2/materials/vgui/logos/custom
Hope it helps

**Comment by DaddyWarcrimes** [comment]
Closing because it will never get fixed.

**Comment by vitacell** [comment]
> Closing because it will never get fixed.

They don't give a F....
They prefer to support Windoze.

**Comment by lyn1337** [comment]
You're just too impatient, you couldn't even wait 10 full years before closing the ticket.

**Comment by SakuraWald** [comment]
> You're just too impatient, you couldn't even wait 10 full years before closing the ticket.

Maybe 100 years to fix this bug.

**Comment by meow6969** [comment]
valve is very good at supporting their old games and supporting operating systems other than windows!! i love valve so much thank you for ~~patching~~ not patching this bug after more than 10 years of you being notified of its existence
