### ISSUE TITLE
TF2 crashed by Opera's notification

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#72]
Issue transferred from ValveSoftware/steam-for-linux#684
@WhiteWind posted at 2013-01-13T08:04:53Z:

When Opera pops up a notification about new email TF2 crashes:
/home/whitewind/.local/share/Steam/SteamApps/whitearchey/Team Fortress 2/hl2.sh: line 72:  7282 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

**Comment by kisak-valve** [comment]
Closing as this issue report is no longer actionable. @WhiteWind, If you are still experiencing this issue, please open a new issue report.
