### ISSUE TITLE
[Portal Beta Linux] Crash on monitor change.

### ISSUE THREAD

**Issue by jamie-marchant** [ValveSoftware/Source-1-Games#720]
Trying to get the game to display on monitor 1(2nd monitor) causes the game to crash. I then have to kill it and when I start it up again it comes up in a window but I can't click anything. I have to reload be deleting my configuration file.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
