### ISSUE TITLE
Players Timed out.

### ISSUE THREAD

**Issue by xomp** [ValveSoftware/Source-1-Games#724]
Ever since Steampipe went live I've noticed that the majority of our players will time out at different times. Some are immediately upon joining while others are after maybe 10mins or so of gameplay. I know today they released a "fix" for this but it doesn't seem to have helped.

Here's just a small sample of how often our players are disconnecting with timestamps. They are connecting from direct connections mostly since Quickplay doesn't appear to send us any traffic even though the server has been registered for months.

18:57: hbo1ulises, STEAM_0:1:59623750, 4 connected.
18:57: hbo1ulises, STEAM_0:1:59623750, 2 disconnected (hbo1ulises timed out).
19:19: kingcaleb05, STEAM_0:1:65333542, 6 connected.
19:22: goodguyJM, STEAM_0:0:16551285, 7 connected.
19:24: kingcaleb05, STEAM_0:1:65333542, 6 disconnected (kingcaleb05 timed out).
19:26: goodguyJM, STEAM_0:0:16551285, 7 disconnected (goodguyJM timed out).
19:34: Azura, STEAM_0:1:46476804, 12 connected.
19:42: Azura, STEAM_0:1:46476804, 12 disconnected (Azura timed out).
20:01: Soulcrusher4497, STEAM_0:1:44978480, 35 connected.
20:06: Soulcrusher4497, STEAM_0:1:44978480, 35 disconnected (Soulcrusher4497 timed out).
20:12: [Maxi]:D_ARG, STEAM_0:0:62080589, 21 connected.
20:28: [Maxi]:D_ARG, STEAM_0:0:62080589, 21 disconnected ([Maxi]:D_ARG timed out).
21:07: captainawesomepants, STEAM_0:0:59572860, 27 connected.
21:12: captainawesomepants, STEAM_0:0:59572860, 27 disconnected (captainawesomepants timed out).
21:38: Deadpool, STEAM_0:0:45809122, 80 connected.
21:43: Deadpool, STEAM_0:0:45809122, 80 disconnected (Deadpool timed out).

**Comment by kisak-valve** [comment]
Hello @xomp, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
