### ISSUE TITLE
Troubles with startup and mapchange

### ISSUE THREAD

**Issue by ET-NiK** [ValveSoftware/Source-1-Games#733]
Im got some troubles with startup mapchange. The map changes too long.
Sometimes its changes maps over 1 minute.
Server downloaded by SteamCMD, without SourceMod.

Game: Team Fortress 2

Server version:
Protocol version 24
Exe version 1765266 (tf)
Exe build: 15:42:29 May 16 2013 (5304) (440)

System specs:
CPU: 2.8 Ghz Dual Core
RAM: 512 Mb
OS: Debian 6 (32 bit)

When server is full (has users playing) it uses 20-50 CPU and apromixy 400 MB of RAM.
When server is empty or it changes map it uses 1-5% CPU and 256 mb of RAM.

<pre>
Auto detecting CPUntinue to launch in 1 secondss
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.
Using breakpad minidump system
Using breakpad crash handler

Console initialized.
Loaded 3260 VPK file hashes from /servers/tf2/tf/tf2_textures.vpk for pure server operation.
Loaded 3260 VPK file hashes from /servers/tf2/tf/tf2_textures.vpk for pure server operation.
Loaded 961 VPK file hashes from /servers/tf2/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 961 VPK file hashes from /servers/tf2/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 802 VPK file hashes from /servers/tf2/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 802 VPK file hashes from /servers/tf2/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 974 VPK file hashes from /servers/tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 974 VPK file hashes from /servers/tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 1213 VPK file hashes from /servers/tf2/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /servers/tf2/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 381 VPK file hashes from /servers/tf2/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 432 VPK file hashes from /servers/tf2/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /servers/tf2/platform/platform_misc.vpk for pure server operation.
Game_srv.so loaded for "Team Fortress"
Setting breakpad minidump AppID = 440
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
maxplayers set to 24
No '-replayserverdir' parameter found - using default replay folder.
Replay: Creating thread pool...succeeded.
Replay: Starting thread pool with 4 threads...succeeded.
Cleaning files from temp dir, "/servers/tf2/tf/replay/server/tmp/" ...no files removed.
Unknown command "r_decal_cullsize"
Unknown command "port"
Unknown command "startupmenu"
WARNING: Port 27005 was unavailable - bound to port 27006 instead
WARNING: Port 27020 was unavailable - bound to port 27021 instead
Network: IP 46.38.50.185, mode MP, dedicated Yes, ports 27016 SV / 27006 CL
L 05/13/2013 - 10:14:46: -------- Mapchange to plr_hightower --------
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
</pre>

[waiting about 60 second]

<pre>
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file server.cfg

Connection to Steam servers successful.
   Public IP is 46.38.50.185.
Assigned anonymous gameserver Steam ID [A-1:2146495489(3406)].
VAC secure mode is activated.
Connection to game coordinator established.
Received auth challenge; signing into gameserver account...
L 05/13/2013 - 10:15:54: Received auth challenge; signing into gameserver account...
Game server authentication: SUCCESS! Standing: Good. Trend: Upward Fast
L 05/13/2013 - 10:15:55: Game server authentication: SUCCESS! Standing: Good. Trend: Upward Fast
L 05/13/2013 - 10:15:55: server_cvar: "sv_registration_message" ""
L 05/13/2013 - 10:15:55: server_cvar: "sv_registration_successful" "1"
L 05/13/2013 - 10:15:55: server_cvar: "sv_tags" "_registered,alltalk,payload"
L 05/13/2013 - 10:15:55: server_cvar: "sv_tags" "_registered,alltalk,payload"
Received 1672236 bytes item schema version E586D803 direct data; update is queued.
</pre>

**Comment by kisak-valve** [comment]
Closing as there isn't something specifically actionable in this issue report.

In general, free memory in a Linux server is used as disk cache to offset the effects of slow storage mediums and random access patterns.
