### ISSUE TITLE
[HL2][HL2:EP1][Linux]Can't open any save game from before yesterdays update

### ISSUE THREAD

**Issue by svein** [ValveSoftware/Source-1-Games#734]
I can't seem to open any savegames from before yesterdays update of hl2 and hl2:ep1 neither quicksave, autosave or regular saves. If I start a new chapter and save, I am able to open those.

**Comment by pimentelleo** [comment]
Wtf i having the same issue on Windows, that's wierd. (not asking for help btw), the button for open de developer console doesn't work.
