### ISSUE TITLE
Steam randomly closes in background while playing TF2

### ISSUE THREAD

**Issue by PyGuy95** [ValveSoftware/Source-1-Games#758]
Hey guys. I have been having issues playing Team Fortress 2, due to random instances of Steam closing in the background. After that, I'd get disconnected from the server with a message that says I've been disconnected from the VAC server. This seems to happen a lot more ever since I started playing the game in a separate X server. To do this, I set the launch options to "/usr/bin/xinit %command% -windowed -noborder -- :1"
Here's my system info: http://pastebin.com/Dvquj2aZ

**Comment by kisak-valve** [comment]
Hello @PyGuy95, if you are still experiencing this issue, please open a new issue report in the steam-for-linux issue tracker.
