### ISSUE TITLE
TF2 thinks I pressed "Play Multiplayer" when I launch straight to a server

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#771]
This is a cross-platform/setup-independent issue, I think; I don't use the Linux version much because the performance with my video card makes it virtually unplayable. I do know that it happens in Windows.

What I do:
Launch the game by double-clicking a server in the Steam client server browser
OR
Launch the game by right-clicking one of my friends and clicking Join Game

What happens:
Game launches
The "Try quickplay beta?" window pops up over the connecting-to-server screen
Closing that brings up the Start Playing window with the standard quickplay options
Closing that gives me a clean connecting-to-server screen

This does NOT happen if I do either of those things while the game is already running.

**Comment by agrastiOs** [comment]
@kisak-valve this should be closed as Quickplay no longer exists.
