### ISSUE TITLE
Physics model for "weapon_colt" in DoD:S is missing or corrupted

### ISSUE THREAD

**Issue by zadroot** [ValveSoftware/Source-1-Games#774]
Sometimes when I drop colt it sliding at a ground and going through walls, or just stay in air

![300_screenshots_2013-04-10_00001](https://f.cloud.github.com/assets/2519059/554540/7be3c9e2-c3ab-11e2-9deb-b22e7e0f9803.jpg)

**Comment by kisak-valve** [comment]
Hello @zadroot, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
