### ISSUE TITLE
[TF2] Backpack: item's popup not correctly drawn

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#78]
Issue transferred from ValveSoftware/steam-for-linux#727
@dance posted at 2013-01-17T20:35:57Z:

When hovering mouse on items with long descriptions in backpack part of description could be hidden by bottom panel:
![backpack_item_descr](https://f.cloud.github.com/assets/965020/76206/632b67b2-60e5-11e2-94c7-aac48a2e1698.jpg)

**Comment by kisak-valve** [comment]
Hello @dance, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
