### ISSUE TITLE
Opening loadout after acquiring new item in TF2 does not work

### ISSUE THREAD

**Issue by FutureSuture** [ValveSoftware/Source-1-Games#793]
In Team Fortress 2 for Linux, whenever I acquire a new weapon and want to open the loadout of the class the weapon is for, nothing happens. The image below depicts what I am referring to.

![tf2 loadout issue](https://f.cloud.github.com/assets/3709560/563990/c3179728-c52f-11e2-9040-30968c22227e.png)

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
