### ISSUE TITLE
[CSS] player classname crash

### ISSUE THREAD

**Issue by nyronic** [ValveSoftware/Source-1-Games#818]
If a player whose classname has been changed is sitting in spectate when the game resets the map on round ending, the server will crash. If the player is on a team when round restarts it will not crash, regardless if they are dead or not.

A mapper can fix this by ensuring that the player's classname is changed back to the default "player" when they die. 

I discovered this on CSS, but it probably affects CS:GO as well.

**Comment by kisak-valve** [comment]
Hello @nyronic, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
