### ISSUE TITLE
[L4D2][Linux][Beta] Latest update (May 29th 2013) causes "#03:MasterRequestRestart" messages

### ISSUE THREAD

**Issue by salamanderrake** [ValveSoftware/Source-1-Games#822]
the last update for the left4dead beta causes this message for the server needing restarted to get latest update.
#03:MasterRequestRestart
#03:Your server needs to be restarted in order to receive the latest update.

**Comment by kisak-valve** [comment]
Hello @salamanderrake, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed. If you are still experiencing this issue, please open a new issue report.
