### ISSUE TITLE
[L4D2 Beta] Weapon spawns in out-of-reach area

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#825]
I found this today while playing Death Toll:

![2013-05-30_00002](https://f.cloud.github.com/assets/3085348/583332/6d629320-c8e8-11e2-9560-21f1bea268d0.jpg)

status output:
    hostname: Gordon Frohman
    version : 2.1.1.8 5289 insecure  
    udp/ip  : 127.0.1.1:27015 [ public n/a ]
    os      : Linux Listen
    map     : c10m4_mainstreet at ( 195, -2770, 6 )
    players : 1 humans, 0 bots (4 max) (not hibernating) (unreserved)

```
# userid name uniqueid connected ping loss state rate adr
#319 1 "Gordon Frohman" STEAM_1:1:18005037 45:20 34 0 active 20000 loopback
#418 "Francis" BOT active
#419 "Louis" BOT active
#420 "Bill" BOT active
#438 "Smoker" BOT active
#437 "Boomer" BOT active
#end
```

**Comment by kisak-valve** [comment]
Hello @stevethepocket, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
