### ISSUE TITLE
[HL2] Chapter 10: Anticitizen One - Game Always Freezes at Certain Points

### ISSUE THREAD

**Issue by dominicbarnes** [ValveSoftware/Source-1-Games#837]
When playing HL2 (Linux version) there are some seemingly random places where the game always seems to freeze. (even if I resume from various saves leading up to that point) The examples I will mention here are from Chapter 10 only.

When I say freeze, it appears like the window manager hits some sort of fatal error, and has to restart itself. Sometimes it fails altogether and my monitor completely shuts off due to no input. Hitting `Esc` sometimes helps and is able to recover my game to the pause screen, other times this does not work at all.
- Lambda Locator Location 37 (according to [this guide](http://forums.steampowered.com/forums/showthread.php?t=1290125)) always triggers a freeze when you approach the gate and attempt to destroy the boxes behind it.
- The part with the firefight on the roof of some buildings before letting the bridge down to cross. It always freezes as I get to be within the Combine Soldiers' line of sight.

My Specs:
- AMD 64-bit CPU
- ATI Radeon HD 5500 GPU (open-source drivers: "xserver-xorg-video-ati")
- Ubuntu 13.04 (64-bit)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue on an up to date system, please open a new issue report.
