### ISSUE TITLE
[TF2] Half-Zatoichi with Blu Soldier/Demoman show Red Soldier/Demoman Arms.

### ISSUE THREAD

**Issue by andregomesdepaiva** [ValveSoftware/Source-1-Games#838]
If you are with a blu soldier or demoman holding a Half-Zatoichi, the arms still from the Red Team

**Comment by kisak-valve** [comment]
Hello @andregomesdepaiva, are you still experiencing this issue?

**Comment by hahagoni** [comment]
Appears to be working properly by now

**Comment by kisak-valve** [comment]
Thanks, closing.
