### ISSUE TITLE
Source1-games on certain Macs: display profile makes the games blueish

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Source-1-Games#841]
On some Macs (MacBooks in particular), the games look totally blueish as the display appears to be switched to some particular profile. This won't be visible on a screenshot, and games settings don't affect the issue, but it is fixed by going to the displays preference pane - color tab while in game. So the display profile that is chosen is obviously wrong. 
This has been experienced by many Mac users using MacBook(Pros) with the geforce 9XXX series cards (and possibly others), since the initial OS X release, and is still visible on 10.8.
Just don't use that profile, it's completely blueish.
Thanks.

My Mac is a MacBook Pro 5.1, running 10.8.3. 
My Mac Pro using a 4870 and a BenQ display is not affected.

**Comment by kisak-valve** [comment]
Hello @jeanlain, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
