### ISSUE TITLE
[HL2] Game slows down to a crawl, sound starts looping

### ISSUE THREAD

**Issue by ComputerDruid** [ValveSoftware/Source-1-Games#862]
The game is quite playable, but occasionally it gets stuck in some kind of error condition where it updates less than once a second, and the audio loops whatever clip is currently playing.

On the terminal is many copies of:

> !! ERROR: bad input/output link:
> !! env_fire(propanetanks_1_fire_a,Extinguish) doesn't match type from <null>(<null>)

Although that may be unrelated. Alt-tab responds (after 1 minute or so of delay), and from there I can kill the process, but I have found no way of stopping it otherwise.

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 2800 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "NAME=Gentoo" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.9.4
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11401000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  NVIDIA Corporation GeForce GTS 450/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 319.23
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xdc4
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.08" x 11.42"  (23.07" diag)
                                        51.0cm x 29.0cm  (58.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7987 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  30109 Mb
    Largest Free Hard Disk Block:  780 Mb

Installed software:

Recent Failure Reports:
    Wed May 29 19:18:52 2013 GMT: file ''/tmp/dumps/crash_20130529151849_1.dmp'', upload yes: ''CrashID=bp-41ef2fcd-976a-4fc9-91b4-1d5de2130529''
    Wed May 29 19:19:29 2013 GMT: file ''/tmp/dumps/crash_20130529151927_1.dmp'', upload yes: ''CrashID=bp-d686921c-b0c7-4e02-8e46-7af1d2130529''
    Fri May 31 02:35:21 2013 GMT: file ''/tmp/dumps/crash_20130530223521_1.dmp'', upload no: ''HTTP response code said error''

**Comment by kisak-valve** [comment]
Hello @ComputerDruid, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
