### ISSUE TITLE
CPU governor causing games to drop framerates

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/Source-1-Games#869]
I noticed there's a bug regarding CPU governor. After a few minutes playing Source Games it clocks my CPU down causing my frames to drop from 150 to 10. It's fixable by a software called "Jupiter" but it's discontinued, so it's pretty much a bug on some Valve games, because it only happens on them.

Regards.

**Comment by kisak-valve** [comment]
This issue is out of scope of the source-1-games issue tracker. If you are still experiencing this issue on an up to date system, please contact the kernel devs related to this subsystem.
