### ISSUE TITLE
[CS:S/DOD:S/HL2:DM][Linux] Language diffrent than Steam language set.

### ISSUE THREAD

**Issue by suore** [ValveSoftware/Source-1-Games#873]
Hello Vave Devs.
*Counter-Strike Source
*Day of Defeat Source 
*Left4Dead 2 beta
*Half-Life 2 Deathmath 

have other language ( English) than Steam language set (Polish).
Last You repair Half-Life 2 and addons (EP1,EP2,LC), and work greats!.
Can You repair this too?.

**Comment by kisak-valve** [comment]
Hello @suore, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
