### ISSUE TITLE
[EP2] All faces (minus the top one) in Skybox sky_day01_09 show as purple checkboard.

### ISSUE THREAD

**Issue by Gambini007** [ValveSoftware/Source-1-Games#878]
Link to example screenshot: http://steamcommunity.com/sharedfiles/filedetails/?id=150566937

Also, the console reads this (which is very likely related): 

Initializing renderer...
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09rt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09bk)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/sky_day01_09bk)

**Comment by kisak-valve** [comment]
Hello @Gambini007, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
