### ISSUE TITLE
[TF2] crash with [Steam]

### ISSUE THREAD

**Issue by lahtis** [ValveSoftware/Source-1-Games#899]
Team Fortress 2 crash with steam.

Start Steam. 
Play Team Fortress 2 game. 
I noticed when I finished the TF2 game Steam has crash.

Suorittimen tiedot:
    Toimittaja:  GenuineIntel
    Nopeus: 2000 Mhz
    2 loogista suoritinta
    2 fyysistä suoritinta
    HyperThreading:  Ei tuettu
    FCMOV:  Tuettu
    SSE2:  Tuettu
    SSE3:  Tuettu
    SSSE3:  Tuettu
    SSE4a:  Ei tuettu
    SSE41:  Ei tuettu
    SSE42:  Ei tuettu

Verkon tiedot:
    Verkon nopeus:  

Käyttöjärjestelmän versio:
    Ubuntu 12.10 (64 bittiä)
    Ytimen nimi: Linux
    Ytimen versio: 3.7.0-7-generic
    X-palvelimen julkaisija: The X.Org Foundation
    X-palvelimen julkaisu: 11304000
    X-ikkunointiohjelma: Compiz
    Steam Runtime -versio: steam-runtime-release-i386_2013-05-08

Näytönohjain:
    Ajuri:  NVIDIA Corporation GeForce 9800 GT/PCIe/SSE2

```
Ajurin versio:  3.3.0 NVIDIA 319.23
Työpöydän värisyvyys: 24 bittiä/pikseli
Näytön virkistystaajuus: 60 Hz
Toimittajatunnus:  0x10de
Laitetunnus:  0x614
Näyttöjen lukumäärä:  1
Loogisten näytönohjainten lukumäärä:  1
Ensisijainen näyttötarkkuus:  1360 x 768
Työpöydän näyttötarkkuus: 1360 x 768
Ensisijainen näytön koko: 6,30" x 3,54" (halkaisija 7,20")
                                        16,0 cm x 9,0 cm (halkaisija 18,3 cm)
Ensisijainen väylä: PCI Express 16x
Ensisijainen VRAM: 512 Mt
Tuetut MSAA-tilat:  2x 4x 8x 16x 
```

Äänikortti:
    Äänikortti: CMedia PCI

Muisti:
    Käyttömuisti:  1986 Mt

Muut:
    Käyttöliittymän kieli:  suomi
    LANG:  fi_FI.UTF-8
    Mikrofoni:  Not set
    Kiintolevytilaa yhteensä:  1406066 Mt
    Suurin vapaa levylohko:  1172413 Mt

Asennetut ohjelmat:

Viimeaikaiset virheilmoitukset:
    Mon Jun 10 19:22:18 2013 GMT: file ''/tmp/dumps/assert_20130610222158_1.dmp'', upload yes: ''CrashID=bp-67cc0cc1-8860-4c03-803f-fd7822130610''
    Mon Jun 10 19:22:18 2013 GMT: file ''/tmp/dumps/assert_20130610222211_2.dmp'', upload yes: ''CrashID=bp-e9cf9eb7-fd41-4e2e-9e64-f903d2130610''
    Mon Jun 10 19:22:30 2013 GMT: file ''/tmp/dumps/assert_20130610222225_3.dmp'', upload yes: ''CrashID=bp-08eb00b5-4451-4338-9571-0a69a2130610''
    Mon Jun 10 19:22:45 2013 GMT: file ''/tmp/dumps/assert_20130610222238_4.dmp'', upload yes: ''CrashID=bp-2c65bcbd-532c-4e81-9b15-944fe2130610''
    Mon Jun 10 19:58:07 2013 GMT: file ''/tmp/dumps/assert_20130610225755_5.dmp'', upload yes: ''CrashID=bp-13346813-9c90-4007-89ac-67c272130610''
    Mon Jun 10 20:14:23 2013 GMT: file ''/tmp/dumps/assert_20130610231414_6.dmp'', upload yes: ''CrashID=bp-e499c3c2-1d64-48cb-a3e5-931f62130610''
    Mon Jun 10 20:14:48 2013 GMT: file ''/tmp/dumps/assert_20130610231440_7.dmp'', upload yes: ''CrashID=bp-efd203aa-3f0c-4dce-947b-df7622130610''
    Mon Jun 10 20:14:59 2013 GMT: file ''/tmp/dumps/assert_20130610231454_8.dmp'', upload yes: ''CrashID=bp-c11776f4-4228-48e5-85bd-e47ab2130610''
    Mon Jun 10 20:15:13 2013 GMT: file ''/tmp/dumps/assert_20130610231507_9.dmp'', upload yes: ''CrashID=bp-f7777336-9f01-4510-bad3-af97f2130610''
    Mon Jun 10 20:15:49 2013 GMT: file ''/tmp/dumps/assert_20130610231541_10.dmp'', upload yes: ''CrashID=bp-0776a721-239c-45cc-8730-518752130610''
    Mon Jun 10 20:17:19 2013 GMT: file ''/tmp/dumps/assert_20130610231710_11.dmp'', upload yes: ''CrashID=bp-bb2c4d19-71ae-47fa-8bf2-1bd822130610''
    Mon Jun 10 20:19:57 2013 GMT: file ''/tmp/dumps/assert_20130610231951_12.dmp'', upload yes: ''CrashID=bp-67e5e821-b96b-4f01-8543-b9cee2130610''
    Mon Jun 10 20:20:08 2013 GMT: file ''/tmp/dumps/assert_20130610232001_13.dmp'', upload yes: ''CrashID=bp-70060982-1b02-4712-8cfc-796742130610''
    Mon Jun 10 20:20:24 2013 GMT: file ''/tmp/dumps/assert_20130610232018_14.dmp'', upload yes: ''CrashID=bp-bd6261f2-cdf1-460a-8d6a-9cb4f2130610''
    Mon Jun 10 20:20:37 2013 GMT: file ''/tmp/dumps/assert_20130610232031_1.dmp'', upload yes: ''CrashID=bp-060b512d-6110-4daf-83f7-04a3b2130610''

**Comment by kisak-valve** [comment]
Hello @lahtis, if you are still experiencing this issue, please open a new issue report in the steam-for-linux issue tracker.
