### ISSUE TITLE
[LD2] Segfaults: unkown cause

### ISSUE THREAD

**Issue by qantourisc** [ValveSoftware/Source-1-Games#900]
hl2_linux[9016]: segfault at 0 ip 00000000f74aedff sp 00000000ffc0578c error 6 in libc-2.15.so[f742e000+1a3000]
I'll see if I can obtain a stack dump from my end.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
