### ISSUE TITLE
[TF2] [REPLAY] Invisible player model in 3rd person view

### ISSUE THREAD

**Issue by tupperware** [ValveSoftware/Source-1-Games#901]
I think this has been an issue for at least several months. Such a good feature is pretty much useless when you can't see the player model. If we're going to just sit in first person view then we may as well just use demos. This needs a fix.

**Comment by kisak-valve** [comment]
Closing as general quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report.
