### ISSUE TITLE
Anti-aliasing broken on Source engine games under Linux

### ISSUE THREAD

**Issue by ElectricTriangle** [ValveSoftware/Source-1-Games#904]
When I try to enable anti-aliasing in source engine titles by setting it to any value other than off (I've tested TF2, portal, L4D2, Half-Life 2, HL2 episodes 1 and 2) the graphics stop working properly (flickering between the last two frames, corrupted graphics) and upon forcibly closing the game and restarting it I get this lovely message listed below.

Failed to create OpenGL device!
Error 0xFFFFFFFF.

Please see the following for more info.
http://support.steampowered.com/cgi-bin/steampowered.cfg/php/enduser/std_adp.php?p_faqid=772

Deleting the video config does solve the problem, but I think Source titles deserve proper AA.

I tried to get the correct information into this report, but please let me know if there's anything I've missed, or anything else that is needed.

```

--Distro

Crunchbang, based on Debian Wheezy.

--Graphics driver

Catalyst Legacy v13.1

--System Info

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3300 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 4600 Series
    Driver Version:  3.3.11672 Compatibility Profile Context
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x9490
    Primary Display Resolution:  1440 x 900

Memory:
    RAM:  16080 Mb

Miscellaneous:
    Total Hard Disk Space Available:  492153 Mb
    Largest Free Hard Disk Block:  162885 Mb
```

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If anyone is still experiencing this issue with an up to date system, please open a new issue report.
