### ISSUE TITLE
compile source games for 64 bit (x86_64)

### ISSUE THREAD

**Issue by TheJJ** [ValveSoftware/Source-1-Games#906]
It shouldn't be difficult to compile Source engine games for 64 bit CPUs.

So, what's the deal of not just compiling stuff with -m64 ?

**Comment by melvyn2** [comment]
Yes, I realize that this issue is 5 years old, and yes, I do realize that this is probably never going to happen, but offering an x64 version of source games WOULD fix #2212, which is a very annoying issue for me.
