### ISSUE TITLE
[TF2] Spy-cicle cooldown is not reset on respawn

### ISSUE THREAD

**Issue by dirkd** [ValveSoftware/Source-1-Games#908]
If you die while your Spy-cicle is on cooldown due to taking fire damage before dying that cooldown is not reset when you respawn.

So if you happen to respawn before the cooldown timer has elapsed you spawn without a melee weapon and have to hit the respawn locker before heading out of spawn or wait for the cooldown timer to elapse (and hope you don't need the fire resistance before this happens).

It's mainly an issue on servers with lowered respawn times (but it can also happen using default settings).

Steps to reproduce:
1. Choose Spy and equip the Spy-cicle.
2. Take fire damage to melt the Spy-cicle.
3. Get killed.
4. Respawn before the Spy-cicle's cooldown timer elapses (<15s after melting).
5. You now have no melee weapon.

**Comment by kisak-valve** [comment]
Hello @dirkd, are you still experiencing this issue?

**Comment by dirkd** [comment]
This was fixed on [July 10, 2013](https://wiki.teamfortress.com/wiki/July_10,_2013_Patch) (found via https://wiki.teamfortress.com/wiki/Spy-cicle#Update_history).
