### ISSUE TITLE
[HL2][Linux] Lighting issue on water in hovercraft level

### ISSUE THREAD

**Issue by nullguy** [ValveSoftware/Source-1-Games#916]
I've just noticed that lighting on some levels seems very weird.
Here's a couple of screenshots:
![2013-06-17_00002](https://f.cloud.github.com/assets/4153468/660055/32edae2c-d6e0-11e2-9f81-bce358a2b6b9.jpg)
Just look at the water 
The first one was tested on AMD graphics card with 'radeon' driver ( all screenshots were made on it ) and on Nvidia graphics card with proprietary driver.
EDIT: More screenshots:
![2013-06-18_00003](https://f.cloud.github.com/assets/4153468/665232/ef7f68fc-d797-11e2-9d03-6d94c90deb8c.jpg)
![2013-06-18_00004](https://f.cloud.github.com/assets/4153468/665234/ef86f9d2-d797-11e2-86bb-f5b8f8a26162.jpg)
![2013-06-18_00002](https://f.cloud.github.com/assets/4153468/665233/ef87bc46-d797-11e2-9558-3eebd49fcf31.jpg)
![2013-06-18_00008](https://f.cloud.github.com/assets/4153468/665235/ef8c0bf2-d797-11e2-993f-30d2668b139c.jpg)
![2013-06-18_00007](https://f.cloud.github.com/assets/4153468/665236/ef8d26b8-d797-11e2-9b66-2d5f0d4a4df0.jpg)

**Comment by kisak-valve** [comment]
Closing pending feedback.
