### ISSUE TITLE
[HL2][Linux] Instant performance drop on toggling flashlight on

### ISSUE THREAD

**Issue by nullguy** [ValveSoftware/Source-1-Games#917]
When toggling on flashlight, i'm experiencing huge performance drop. It happens even if i aim it to the ground under myself or on a place where nothing is able to cast shadows.
This happens when "Shadows" parameter is set on "High" and does not appear on "Low".
I've always thought that fps should depend on complexity of the scene, but it's relatively  same if i point it to flat surface or complex shadow-casting obstacle like elevator fence.
If stand still, it rapidly changes between ~20 and ~30 FPS no matter of what.
![2013-06-17_00015](https://f.cloud.github.com/assets/4153468/660190/050d26ac-d6ec-11e2-8235-a7d96d4e3112.jpg)
![2013-06-17_00016](https://f.cloud.github.com/assets/4153468/660191/052bd0c0-d6ec-11e2-8009-10d8532c230e.jpg)
Notice the fps difference
![2013-06-17_00019](https://f.cloud.github.com/assets/4153468/660192/0526d35e-d6ec-11e2-8544-6e2ed0d818dc.jpg)
![2013-06-17_00020](https://f.cloud.github.com/assets/4153468/660193/052b1496-d6ec-11e2-901c-fb02b1bbff45.jpg)

Here are my system specs:

<pre><code>
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3013 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 13.04 (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-25-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RV670

    Driver Version:  3.0 Mesa 9.1.1
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x9501
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 2944 x 1080
    Primary Display Size: 18,78" x 10,55"  (21,54" diag)
                                            47,7cm x 26,8cm  (54,7cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Analog Devices AD1988B
    
Memory:
    RAM:  5047 Mb
   
    
</code></pre>

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If anyone is still experiencing this issue with an up to date system, please open a new issue report.
