### ISSUE TITLE
Half-Life 2 Beta - Wrong borders of the scroll bar

### ISSUE THREAD

**Issue by UAVXP** [ValveSoftware/Source-1-Games#924]
In the beta build I have this issue:
screenshot - http://cloud-2.steampowered.com/ugc/577866662863379715/B205326D2253443713B0F7A31590432E449303ED/

**Comment by RiverHornet3209** [comment]
> It's like concaved, instead of convex.

This also still happens in L4D1 and Source SDK 2013 Singleplayer:

<img width="146" height="809" alt="Image" src="https://github.com/user-attachments/assets/abeeaf95-be2b-4c1e-9bfa-7bf230aca692" />

<img width="242" height="809" alt="Image" src="https://github.com/user-attachments/assets/835ca875-9086-45a6-a6ec-eece4afec0ac" />
