### ISSUE TITLE
Options dialog lists only 2 speakers config

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#93]
@WhiteWind posted ValveSoftware/steam-for-linux#1057 at 2013-01-30T15:24:30Z:

I have 5.1 audio and "Analog Surround 5.1 Output" profile is selected in PulseAudio.
But Audio options offers only "2 speakers" and by default nothing is selected.
![2013-01-31_00001](https://f.cloud.github.com/assets/1281277/111301/ad6af472-6af0-11e2-85e1-5aceeca52024.jpg)

System info: https://gist.github.com/4634761

**Comment by lonaowna** [comment]
Valve just added surround sound support to CS:GO:
http://blog.counter-strike.net/index.php/2015/03/11734/
– Add surround sound support (quad/5.1) on Linux.

Hopefully this means it will also be coming to other Source games!

**Comment by ask-compu** [comment]
did valve ever add the support to tf2? im wondering cuz i want to set up quad audio but i dont have the set up yet

**Comment by scorpius2k1** [comment]
**January 2021** - Still ZERO support on HL2DM/TF2/CSS for multichannel audio > 2

**Comment by chicco-carone** [comment]
Even after the 20th anniversary half life 2 update there is still no option for surround sound in linux.
Edit: it does show up and work if using the windows version via proton bit with the native client it doesn't.

**Comment by landfillbaby** [comment]
> The UI has been fixed, it will no longer select an empty choice in the drop down. But the only option on Linux is 2 speakers. There are no audio speaker configuration options. The fixed UI will be out in a week or so (didn't make it into the end of Feb release). There are no plans to add support for more speaker configurations at this time.

why even have the "2 speakers" option show up at all on linux then? it's a dropdown that does nothing. taunting the linux (including steamos) users who want surround sound in source engine games
