### ISSUE TITLE
Window icon has broken transparency

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/Source-1-Games#931]
Window icon has a white fill, visible in taskbar on gnome 2 and themes that display the icon on the window border.
Happens for HL2, EP1, EP2, LC & DM

![screenshot from 2013-06-20 15 01 10](https://f.cloud.github.com/assets/7708/681486/c8b5cd20-d9b2-11e2-9e02-6760cc4374dc.png)

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-18-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Metacity
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630/PCIe/SSE2
    Driver Version:  4.3.0 NVIDIA 310.14
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xf00
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3520 x 1080
    Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                            47.7cm x 26.8cm  (54.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ID 662

Memory:
    RAM:  16050 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  295295 Mb
    Largest Free Hard Disk Block:  2963 Mb

Recent Failure Reports:
    Wed Jun 19 08:46:06 2013 GMT: file ''/tmp/dumps/crash_20130619093546_1.dmp'', upload yes: ''CrashID=bp-7ca6b2a6-02ad-4967-9f44-cc31b2130619''
    Thu Jun 20 09:28:59 2013 GMT: file ''/tmp/dumps/crash_20130620102823_1.dmp'', upload yes: ''CrashID=bp-62e3c335-5a8f-4a37-83a6-002e22130620''

**Comment by kisak-valve** [comment]
Closing as fixed.
