### ISSUE TITLE
TF2: eyes at floor level

### ISSUE THREAD

**Issue by mxttie** [ValveSoftware/Source-1-Games#936]
I had this once:

![2013-06-18_00001](https://f.cloud.github.com/assets/178714/684116/0eeca6b4-d9f0-11e2-916e-0b070a0df8f5.jpg)

but after I respawned it was back to normal. Until now, only once.
I could move and shoot stuff, just a bit difficult to see everything ;)

[sys info](https://gist.github.com/mxttie/5826727)

**Comment by kisak-valve** [comment]
Closing pending steps to reproduce this issue.
