### ISSUE TITLE
game stutters for a moment after loading a Map (L4D2  beta - OS X)

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Source-1-Games#944]
After loading a Map, there is some stuttering for a moment. It affects the initial camera flyby at the beginning of an episode, especially as the camera moves into the head of your character, and when killing the first few zombies of every map. If you die and the map restarts, the issue no longer appear. So I suppose it's due to assets that are now cached in RAM and were previously read from disk. This issue doesn't affect Windows on the same Mac/Hard drive, which suggests it is OS X specific, and that it could be solved.
Tested on OS X 10.7.5, Mac Pro 1,1 radeon 4870. The game is installed on a standard 7200 rpm HD.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. In general, this kind of render stalling is expected with OpenGL video drivers that do not support an on-disk shader cache.
