### ISSUE TITLE
Raw input + Loadout screen bug

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#95]
Issue transferred from ValveSoftware/steam-for-linux#1064
@gutigen posted at 2013-01-30T18:13:07Z:

If I got RAW Input enabled, characters in Loadout view spin at least 100 times faster then they should. It looks like this (trying to move my mouse as slow as I can): 

http://www.youtube.com/watch?v=tVTy6ZHJtX4

If RAW Input is off it's fine.

Mouse and settings:
Razer Abyssus set to 3500DPI and 1000hz refresh rate
Ingame senistivity - 1.4

System info:
Ubuntu 12.10 Gnome Remix 64bit
Kernel 3.5.0-22
NVIDIA 313.18 drivers

**Comment by amitbar05** [comment]
It has been three years and you still haven't fixed it.
I am still experiencing this issue. Please solve this ASAP.

**Comment by Munoida** [comment]
In 2022 this has still not been fixed

Unfortunate. Never knew this was being tracked from all the way in 2013

**Comment by Bumper3241** [comment]
I was having this issue before when RAW input was on, for somereason something in my config files was forcing it to re-enable every time I reopen the game, but now it has the same effect no matter if I have Raw Input on or off.

**Comment by Tiagoquix** [comment]
@kisak-valve Same issue as https://github.com/ValveSoftware/Source-1-Games/issues/2790#issuecomment-2143201860. It's fixed now.

**Comment by kisak-valve** [comment]
Closing per the last comment.
