### ISSUE TITLE
[L4D2 Beta] Add-ons sometimes working, sometimes not.

### ISSUE THREAD

**Issue by V10lator** [ValveSoftware/Source-1-Games#950]
I installed some add-ons (just re-textured things from the workshop) but they aren't always working. Sometimes they even work first, but after changing the campaign they stop working.

**Comment by kisak-valve** [comment]
Hello @V10lator, are you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing in favor of #1912.
