### ISSUE TITLE
[TF2] Mapcycle_quickplay files have no effect on Quickplay server selection

### ISSUE THREAD

**Issue by RollingStar** [ValveSoftware/Source-1-Games#957]
I found these files in my cfg folder:

mapcycle_quickplay_arena.txt
mapcycle_quickplay_attackdefense.txt
mapcycle_quickplay_cp.txt
mapcycle_quickplay_ctf_sd.txt
mapcycle_quickplay_koth.txt
mapcycle_quickplay_payload.txt
mapcycle_quickplay_payloadrace.txt

I think they may be a leftover from before the Steampipe conversion for TF2. In an attempt to continue to use these files, I placed them in

```
\Team Fortress 2\tf\custom\My scripts\cfg\
```

Here are the contents of mapcycle_quickplay_cp.txt:

```
cp_5gorge
cp_badlands
cp_coldfront
cp_fastlane
cp_freight_final1
cp_granary
cp_well
cp_yukon_final
cp_foundry
cp_gullywash_final1
```

If a user did not like the map cp_badlands, they should be able to delete that line and have quickplay never connect to servers running cp_badlands. That does not seem to be the case.

One can reproduce this bug by modifying mapcycle_quickplay_cp to only include these lines:

```
cp_badlands
cp_coldfront
cp_gullywash_final1
```

Intuitively, the quickplay beta search for Standard Control Points 5CP should only return servers running **Badlands, Coldfront, or Gullywash** if configured as written above. Instead, Quickplay ignores the config file and any map can be loaded.

When searching for servers while using this configuration, the Quickplay beta ran for about 25 minutes. I started at 10:30 PM EDT and after an extremely long time was matched with a Lotus Clan server that had just started on cp_foundry.

I am running the normal TF2 client on Windows 7 Professional x64.

I don't know if this is a bug or not, though. Maybe the mapcycle_quickplay files are for something else. Maybe they have been deprecated long ago. Any help on this would be greatly appreciated.

**Comment by agrastiOs** [comment]
@kisak-valve Quickplay no longer exists so this should be closes
