### ISSUE TITLE
Modifying the value of mat_antialias in-game (even via the video setting panel) halted TF2 display output

### ISSUE THREAD

**Issue by UnknownzD** [ValveSoftware/Source-1-Games#968]
Well although I know that all those mat_\* stuffs are not designed to be changed during in game, but apparently there is a mistake for the default flag setting for mat_antialias, which is 0x0000000 atm. By using the video setting panel to modify the setting of antialising mode (i.e. changing the value of mat_antialias) will halt any in-game display output.

   I was able to tackle the problem down to the antialias setting by changing the value of mat_antialias in game via console (which is allowed by default), which makes the game display output halted. And if I have done it while I am not connected to any server, the console variable is actually working well.

   And as the current default cvar flag setting for mat_antialias is 0x00000000, which means nothing at all. So would valve dev considers to change the default flag of it to something like SP_ONLY or NOT_CONNECTED so that user won't get their game display halted after setting it via the video setting panel?

  Testing procedure :
  1) Changed the value of mat_antialias in a connected game (via console)
  2) The display will just halted
  3) Restarted the game, and changed the value of mat_antialias in the main menu (via console)
  4) The game didn't crash at all

  Tested with the following command line parameter :
  -insecure -console -allowdebug -dev -nobreakpad -nominidumps -noassert -novid -nohltv -noipx -heapsize 524288 -threads 4 -dxlevel 70 -window -w 1600 -h 900 -refresh 60 -preload -port 27015

  Tested with following drivers and OS
  GeForce Driver 314.22 WHQL
  Windows NT  6.2

  In addition, I guess the same problem may happen in other branches (for example, L4D, L4D2, CSGO and Portal 2) as well. So if this problem was found to exist for TF2, would someone try to merge the solution to other source engine games as well?

Best regards,
UnknownzD

**Comment by kisak-valve** [comment]
Hello @UnknownzD, while there is a render stall while processing the change of this console variable, I am unable to reproduce a crash. If you are still experiencing this issue and the client does not recover after a while, please let me know and we can reopen this issue report.
