### ISSUE TITLE
TF2 takes over 3 minutes to start from SSD

### ISSUE THREAD

**Issue by Kiwii** [ValveSoftware/Source-1-Games#978]
The native TF2 client takes 3m06s for a complete start (11s until it goes fullscreen and 2m55s loading at the gray image), even though TF2, Steam and the system are all installed on an SSD. On the same machine running Windows on an HDD it takes about 20s. 
This problem exists since Steam on Linux was in beta and it has not gotten better with the switch to steampipe and a complete reinstall of the game. Many friends of mine running Windows have TF2 startup times of less than ten seconds. 

As you can see from the [console output](https://gist.github.com/Kiwii/2768dcd62b32c9e3b391#file-steam-console-output), most of that time is spend for "precaching":

```
Precache: Took 159908 ms, Vertex 2262, Pixel 3250
```

(159908ms are about 2m 40s)

From my understanding (having done some Google research), in that step DirectX shaders are compiled to OpenGL shaders and this should only take that long once after either TF2 or Catalyst have been updated. _However, it takes that long on every subsequent start of TF2._

**My specs overview:**

```
Distro: Arch Linux, kernel 3.9.7 with ck patches
DE: KDE 4.10.4 with compositing disabled in KWin
CPU: AMD Phenom II x4 955 BE @ 3.2 GHz
GFX: XFX AMD Radeon HD7870 GHz Edition 2GB DDR5 with Catalyst 13.6 beta
RAM: 12 GiB  @ 2x666 MHz (dual channel)
SSD: Mushkin Chronos 120GB
```

For more info, see [detailed system info](https://gist.github.com/Kiwii/2768dcd62b32c9e3b391#file-system-info), as given by Steam.

During startup, CPU load on all four cores fluctuates between 50% and 60% and RAM usage stays under one Gigabyte, so the system doesn't seem to work at it's limits.

I know Arch isn't officially supported but startup times were the same when I used Ubuntu on the same machine a few weeks ago. Also, there seems to be no difference between Catalyst versions.

**Comment by BotoX** [comment]
I am experiencing the same issue with Counter-Strike: Source.

I replaced the glshaders.cfg with an empty, read-only file and it fixed this issue.
I am not sure whether this will impact ingame loading times.

**Comment by kisak-valve** [comment]
Last comment aside, this is the expected behavior of any OpenGL video driver that does not support an on disk shader cache. Closing as general video driver quality from 2013 / 2014 is no longer relevant.
